{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierBlock","preciseIdentifier":"c:SDWebImageDownloaderResponseModifier.h@T@SDWebImageDownloaderResponseModifierBlock","text":"SDWebImageDownloaderResponseModifierBlock"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(block:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(block:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(block:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the response modifier with block"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderResponseModifierBlock","preciseIdentifier":"c:SDWebImageDownloaderResponseModifier.h@T@SDWebImageDownloaderResponseModifierBlock"},{"kind":"text","text":")"}],"title":"init(block:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDWebImageDownloaderResponseModifier(im)initWithBlock:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(block:)":{"role":"symbol","title":"init(block:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderResponseModifierBlock","preciseIdentifier":"c:SDWebImageDownloaderResponseModifier.h@T@SDWebImageDownloaderResponseModifierBlock"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the response modifier with block"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(block:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(block:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifierBlock":{"role":"symbol","title":"SDWebImageDownloaderResponseModifierBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class":{"role":"symbol","title":"SDWebImageDownloaderResponseModifier","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"abstract":[{"type":"text","text":"A downloader response modifier class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLResponse *(^)(NSURLResponse *)","preciseIdentifier":"c:BF*$objc(cs)NSURLResponse(#S2_)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(block:)\/title","value":"initWithBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(block:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierBlock\/title","value":"SDWebImageDownloaderResponseModifierBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/title","value":"SDWebImageDownloaderResponseModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}