{"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:version:headers:)"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"statusCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"version","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"statusCode","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HTTP Status Code."}]}]},{"name":"version","content":[{"inlineContent":[{"type":"text","text":"HTTP Version, nil means “HTTP\/1.1”."}],"type":"paragraph"}]},{"name":"headers","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HTTP Headers. Case insensitive according to HTTP\/1.1(HTTP\/2) standard. The headers will override the same fields from original response."}]}]}]},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"aside","content":[{"inlineContent":[{"text":"This is for convenience, if you need code to control the logic, use block API instead.","type":"text"}],"type":"paragraph"}],"name":"Note","style":"note"}]}],"abstract":[{"text":"Create the response modifier with HTTP Status Code, Version and Headers.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(statuscode:version:headers:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(statuscode:version:headers:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"statusCode"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"text":"version","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"headers","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":" : "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?)"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Initializer","title":"init(statusCode:version:headers:)","role":"symbol","externalID":"c:objc(cs)SDWebImageDownloaderResponseModifier(im)initWithStatusCode:version:headers:","symbolKind":"init","extendedModule":"SDWebImage","navigatorTitle":[{"text":"initWithStatusCode:version:headers:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(statusCode:version:headers:)":{"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(statuscode:version:headers:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"statusCode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"version"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"]?)","kind":"text"}],"title":"init(statusCode:version:headers:)","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:version:headers:)","abstract":[{"text":"Create the response modifier with HTTP Status Code, Version and Headers.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"initWithStatusCode:version:headers:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class":{"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class","abstract":[{"text":"A downloader response modifier class with block.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class","type":"topic","title":"SDWebImageDownloaderResponseModifier","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithStatusCode:version:headers:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStatusCode:version:headers:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithStatusCode:"},{"text":"(","kind":"text"},{"text":"NSInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"statusCode"},{"kind":"text","text":" "},{"text":"version:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"version","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"headers:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSDictionary","kind":"typeIdentifier","text":"NSDictionary<NSString *,NSString *>"},{"text":" *) ","kind":"text"},{"text":"headers","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"statusCode","content":[{"type":"paragraph","inlineContent":[{"text":"HTTP Status Code.","type":"text"}]}]},{"name":"version","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"HTTP Version, nil means “HTTP\/1.1”."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"HTTP Headers. Case insensitive according to HTTP\/1.1(HTTP\/2) standard. The headers will override the same fields from original response.","type":"text"}]}],"name":"headers"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(statusCode:version:headers:)\/title","value":"initWithStatusCode:version:headers:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithStatusCode:version:headers:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(statusCode:version:headers:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/title","value":"SDWebImageDownloaderResponseModifier"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/fragments","value":[{"text":"SDWebImageDownloaderResponseModifier","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}