{"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"Create the response modifier with block"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/responsemodifierwithblock:"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"metadata":{"symbolKind":"method","externalID":"c:objc(cs)SDWebImageDownloaderResponseModifier(cm)responseModifierWithBlock:","fragments":[{"text":"+ ","kind":"text"},{"text":"responseModifierWithBlock:","kind":"identifier"}],"role":"symbol","title":"responseModifierWithBlock:","roleHeading":"Type Method","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"responseModifierWithBlock:"}]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/responseModifierWithBlock:","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"responseModifierWithBlock:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLResponse *(^)(NSURLResponse *)","kind":"typeIdentifier","preciseIdentifier":"c:BF*$objc(cs)NSURLResponse(#S2_)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"block"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block to control modifier logic"}]}],"name":"block"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class":{"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class","abstract":[{"text":"A downloader response modifier class with block.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class","type":"topic","title":"SDWebImageDownloaderResponseModifier","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/responseModifierWithBlock:":{"abstract":[{"type":"text","text":"Create the response modifier with block"}],"title":"responseModifierWithBlock:","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/responsemodifierwithblock:","fragments":[{"kind":"text","text":"+ "},{"text":"responseModifierWithBlock:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/responseModifierWithBlock:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"responseModifierWithBlock:"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SDWebImageDownloaderResponseModifier","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/fragments","value":[{"text":"SDWebImageDownloaderResponseModifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/navigatorTitle","value":[{"text":"SDWebImageDownloaderResponseModifier","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}