{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalCachePathBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheAdditionalCachePathBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheAdditionalCachePathBlock","text":"SDImageCacheAdditionalCachePathBlock"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/additionalcachepathblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/additionalcachepathblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/additionalCachePathBlock","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The additional disk cache path to check if the query from disk cache not exist;"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"key"},{"type":"text","text":" param is the image cache key. The returned file path will be used to load the disk cache. If return nil, ignore it."},{"type":"text","text":" "},{"type":"text","text":"Useful if you want to bundle pre-loaded images with your app"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalCachePathBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheAdditionalCachePathBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheAdditionalCachePathBlock"},{"kind":"text","text":"?"}],"title":"additionalCachePathBlock","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCache(py)additionalCachePathBlock","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"additionalCachePathBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/additionalCachePathBlock":{"role":"symbol","title":"additionalCachePathBlock","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalCachePathBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheAdditionalCachePathBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheAdditionalCachePathBlock"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The additional disk cache path to check if the query from disk cache not exist;"},{"type":"text","text":" "},{"type":"text","text":"The "},{"type":"codeVoice","code":"key"},{"type":"text","text":" param is the image cache key. The returned file path will be used to load the disk cache. If return nil, ignore it."},{"type":"text","text":" "},{"type":"text","text":"Useful if you want to bundle pre-loaded images with your app"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/additionalCachePathBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"additionalCachePathBlock"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/additionalcachepathblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"role":"symbol","title":"SDImageCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCache"}],"abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"type":"text","text":"asynchronous so it doesn’t add unnecessary latency to the UI."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheAdditionalCachePathBlock":{"role":"symbol","title":"SDImageCacheAdditionalCachePathBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheAdditionalCachePathBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}],"url":"\/documentation\/sdwebimage\/sdimagecacheadditionalcachepathblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"additionalCachePathBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"additionalCachePathBlock"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString *(^)(NSString *)","preciseIdentifier":"c:BF*$objc(cs)NSString(#S2_)"},{"kind":"text","text":" "},{"kind":"identifier","text":"additionalCachePathBlock"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1additionalCachePathBlock\/title","value":"additionalCachePathBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1additionalCachePathBlock\/fragments","value":[{"kind":"identifier","text":"additionalCachePathBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheAdditionalCachePathBlock\/title","value":"SDImageCacheAdditionalCachePathBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheAdditionalCachePathBlock\/fragments","value":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}