{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheCalculateSizeBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheCalculateSizeBlock","text":"SDImageCacheCalculateSizeBlock"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/calculatesize(completionblock:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/calculatesize(completionblock:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/calculateSize(completionBlock:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronously calculate the disk cache’s size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheCalculateSizeBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheCalculateSizeBlock"},{"kind":"text","text":"?)"}],"title":"calculateSize(completionBlock:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCache(im)calculateSizeWithCompletionBlock:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"calculateSizeWithCompletionBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"role":"symbol","title":"SDImageCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCache"}],"abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"type":"text","text":"asynchronous so it doesn’t add unnecessary latency to the UI."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheCalculateSizeBlock":{"role":"symbol","title":"SDImageCacheCalculateSizeBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheCalculateSizeBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}],"url":"\/documentation\/sdwebimage\/sdimagecachecalculatesizeblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/calculateSize(completionBlock:)":{"role":"symbol","title":"calculateSize(completionBlock:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"calculateSize"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheCalculateSizeBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheCalculateSizeBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Asynchronously calculate the disk cache’s size."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/calculateSize(completionBlock:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"calculateSizeWithCompletionBlock:"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/calculatesize(completionblock:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"calculateSizeWithCompletionBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateSizeWithCompletionBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"calculateSizeWithCompletionBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(unsigned long, unsigned long)","preciseIdentifier":"c:BFv(#l#l)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCalculateSizeBlock\/title","value":"SDImageCacheCalculateSizeBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCalculateSizeBlock\/fragments","value":[{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1calculateSize(completionBlock:)\/title","value":"calculateSizeWithCompletionBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1calculateSize(completionBlock:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"calculateSizeWithCompletionBlock:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}