{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"abstract":[{"text":"Asynchronously clear all disk cached images. Non-blocking method - returns immediately.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/cleardisk(oncompletion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/cleardisk(oncompletion:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearDisk(onCompletion:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"method","externalID":"c:objc(cs)SDImageCache(im)clearDiskOnCompletion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearDisk"},{"text":"(","kind":"text"},{"text":"onCompletion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"title":"clearDisk(onCompletion:)","role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"clearDiskOnCompletion:","kind":"identifier"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearDisk","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"onCompletion"},{"text":" ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]},{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"clearDiskOnCompletion"},{"text":"() ","kind":"text"},{"text":"async","kind":"keyword"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"A block that should be executed after cache expiration completes (optional)","type":"text"}],"type":"paragraph"}],"name":"completion"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/clearDisk(onCompletion:)":{"title":"clearDisk(onCompletion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearDisk","kind":"identifier"},{"kind":"text","text":"("},{"text":"onCompletion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearDiskOnCompletion:"}],"abstract":[{"type":"text","text":"Asynchronously clear all disk cached images. Non-blocking method - returns immediately."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearDisk(onCompletion:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/cleardisk(oncompletion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageNoParamsBlock":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageNoParamsBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagenoparamsblock","title":"SDWebImageNoParamsBlock","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"clearDiskOnCompletion:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"clearDiskOnCompletion:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"clearDiskOnCompletion:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"text":") ","kind":"text"},{"text":"completion","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"A block that should be executed after cache expiration completes (optional)","type":"text"}]}],"name":"completion"}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDImageCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1clearDisk(onCompletion:)\/title","value":"clearDiskOnCompletion:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearDiskOnCompletion:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1clearDisk(onCompletion:)\/fragments"},{"op":"replace","value":"SDWebImageNoParamsBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/title"},{"value":[{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/fragments"},{"value":[{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/navigatorTitle"}]}]}