{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/config"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/config"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/config","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Cache Config object - storing all kind of settings."},{"type":"text","text":" "},{"type":"text","text":"The property is copy so change of current config will not accidentally affect other cache’s config."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"}],"title":"config","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCache(py)config","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"config"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","title":"SDImageCacheConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"role":"symbol","title":"SDImageCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCache"}],"abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"type":"text","text":"asynchronous so it doesn’t add unnecessary latency to the UI."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"}],"abstract":[{"type":"text","text":"Cache Config object - storing all kind of settings."},{"type":"text","text":" "},{"type":"text","text":"The property is copy so change of current config will not accidentally affect other cache’s config."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/config","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"config"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/config"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"config"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"config"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"kind":"text","text":" *"},{"kind":"identifier","text":"config"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1config\/title","value":"config"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1config\/fragments","value":[{"kind":"identifier","text":"config"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}