{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultDiskCacheDirectory","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"! { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","anchor":"discussion","text":"Discussion"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you pass nil, the value will be reset to "},{"type":"codeVoice","code":"~\/Library\/Caches\/com.hackemist.SDImageCache"},{"text":".","type":"text"}]}]},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We still preserve the "},{"type":"codeVoice","code":"namespace"},{"text":" arg, which means, if you change this property into ","type":"text"},{"type":"codeVoice","code":"\/path\/to\/use"},{"type":"text","text":",  the "},{"type":"codeVoice","code":"SDImageCache.sharedImageCache.diskCachePath"},{"text":" should be ","type":"text"},{"type":"codeVoice","code":"\/path\/to\/use\/default"},{"type":"text","text":" because shared image cache use "},{"type":"codeVoice","code":"default"},{"text":" as namespace.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil."}]}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/defaultdiskcachedirectory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/defaultdiskcachedirectory"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/defaultDiskCacheDirectory"},"abstract":[{"text":"Control the default disk cache directory. This will effect all the SDImageCache instance created after modification, even for shared image cache.","type":"text"},{"text":" ","type":"text"},{"text":"This can be used to share the same disk cache with the App and App Extension (Today\/Notification Widget) using ","type":"text"},{"type":"codeVoice","code":"- [NSFileManager.containerURLForSecurityApplicationGroupIdentifier:]"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Type Property","title":"defaultDiskCacheDirectory","symbolKind":"property","navigatorTitle":[{"text":"defaultDiskCacheDirectory","kind":"identifier"}],"externalID":"c:objc(cs)SDImageCache(cpy)defaultDiskCacheDirectory","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"defaultDiskCacheDirectory","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"!","kind":"text"}],"role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/defaultDiskCacheDirectory":{"type":"topic","abstract":[{"type":"text","text":"Control the default disk cache directory. This will effect all the SDImageCache instance created after modification, even for shared image cache."},{"text":" ","type":"text"},{"type":"text","text":"This can be used to share the same disk cache with the App and App Extension (Today\/Notification Widget) using "},{"type":"codeVoice","code":"- [NSFileManager.containerURLForSecurityApplicationGroupIdentifier:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/defaultDiskCacheDirectory","title":"defaultDiskCacheDirectory","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/defaultdiskcachedirectory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultDiskCacheDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"defaultDiskCacheDirectory","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","value":"defaultDiskCacheDirectory","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"defaultDiskCacheDirectory"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readwrite"},{"text":") ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"defaultDiskCacheDirectory"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle"},{"value":"defaultDiskCacheDirectory","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1defaultDiskCacheDirectory\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1defaultDiskCacheDirectory\/fragments","value":[{"kind":"identifier","text":"defaultDiskCacheDirectory"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}