{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"diskImageDataQuery","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"kind":"text","text":" "},{"text":"completionBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SDImageCacheQueryDataCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryDataCompletionBlock","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryDataCompletionBlock"},{"kind":"text","text":"? = nil)"}],"platforms":["iOS"],"languages":["swift"]},{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskImageDataQuery","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"?) "},{"kind":"keyword","text":"async"},{"text":" -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"key","content":[{"inlineContent":[{"type":"text","text":"The unique key used to store the wanted image"}],"type":"paragraph"}]},{"name":"completionBlock","content":[{"inlineContent":[{"text":"The block to be executed when the query is done.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"The completion block will be always executed on the main queue","type":"text"}]}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"kind":"symbol","abstract":[{"text":"Asynchronously query the image data for the given key in disk cache. You can decode the image data to image after loaded.","type":"text"}],"metadata":{"externalID":"c:objc(cs)SDImageCache(im)diskImageDataQueryForKey:completion:","title":"diskImageDataQuery(forKey:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"diskImageDataQuery","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryDataCompletionBlock","kind":"typeIdentifier","text":"SDImageCacheQueryDataCompletionBlock"},{"kind":"text","text":"?)"}],"symbolKind":"method","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","navigatorTitle":[{"kind":"identifier","text":"diskImageDataQueryForKey:completion:"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimagedataquery(forkey:completion:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimagedataquery(forkey:completion:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataQuery(forKey:completion:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskImageDataQuery(forKey:completion:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataQuery(forKey:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskImageDataQuery"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryDataCompletionBlock","text":"SDImageCacheQueryDataCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"diskImageDataQueryForKey:completion:"}],"title":"diskImageDataQuery(forKey:completion:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimagedataquery(forkey:completion:)","abstract":[{"type":"text","text":"Asynchronously query the image data for the given key in disk cache. You can decode the image data to image after loaded."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryDataCompletionBlock":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecachequerydatacompletionblock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryDataCompletionBlock","kind":"symbol","title":"SDImageCacheQueryDataCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryDataCompletionBlock"}],"navigatorTitle":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","value":"diskImageDataQueryForKey:completion:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"diskImageDataQueryForKey:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"diskImageDataQueryForKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(NSData *)","preciseIdentifier":"c:BFv(#*$objc(cs)NSData)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completionBlock","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The unique key used to store the wanted image","type":"text"}],"type":"paragraph"}],"name":"key"},{"name":"completionBlock","content":[{"inlineContent":[{"type":"text","text":"The block to be executed when the query is done."}],"type":"paragraph"}]}]}},{"op":"replace","value":"diskImageDataQueryForKey:completion:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageDataQuery(forKey:completion:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"diskImageDataQueryForKey:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageDataQuery(forKey:completion:)\/fragments"},{"value":"SDImageCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","op":"replace","value":[{"text":"SDImageCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryDataCompletionBlock\/title","op":"replace","value":"SDImageCacheQueryDataCompletionBlock"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryDataCompletionBlock\/fragments","value":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryDataCompletionBlock\/navigatorTitle"}]}]}