{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageFromCache"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique key used to store the image","type":"text"}]}],"name":"key"}]},{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The image for the given key, or nil if not found."}]}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:)"},"metadata":{"roleHeading":"Instance Method","title":"imageFromCache(forKey:)","navigatorTitle":[{"kind":"identifier","text":"imageFromCacheForKey:"}],"externalID":"c:objc(cs)SDImageCache(im)imageFromCacheForKey:","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageFromCache"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"role":"symbol","modules":[{"name":"SDWebImage"}],"symbolKind":"method"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromcache(forkey:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromcache(forkey:)"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"abstract":[{"type":"text","text":"Synchronously query the cache (memory and or disk) after checking the memory cache."}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/imageFromCache(forKey:)":{"abstract":[{"text":"Synchronously query the cache (memory and or disk) after checking the memory cache.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageFromCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"imageFromCache(forKey:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromcache(forkey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:)","navigatorTitle":[{"text":"imageFromCacheForKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"imageFromCacheForKey:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"imageFromCacheForKey:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imageFromCacheForKey:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"key","content":[{"inlineContent":[{"text":"The unique key used to store the image","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The image for the given key, or nil if not found."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromCache(forKey:)\/title","value":"imageFromCacheForKey:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageFromCacheForKey:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromCache(forKey:)\/fragments"},{"value":"SDImageCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace"}]}]}