{"abstract":[{"type":"text","text":"Init a new cache store with a specific namespace, directory and config."},{"type":"text","text":" "},{"text":"The final disk cache directory should looks like ($directory\/$namespace). And the default config of shared cache, should result in (~\/Library\/Caches\/com.hackemist.SDImageCache\/default\/)","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/init(namespace:diskcachedirectory:config:)"]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/init(namespace:diskcachedirectory:config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:config:)"},"metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"namespace"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"diskCacheDirectory"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"text":"SDImageCacheConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"},{"kind":"text","text":"?)"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"initWithNamespace:diskCacheDirectory:config:"}],"title":"init(namespace:diskCacheDirectory:config:)","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDImageCache(im)initWithNamespace:diskCacheDirectory:config:","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"namespace"},{"kind":"text","text":" "},{"text":"ns","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"diskCacheDirectory"},{"text":" ","kind":"text"},{"text":"directory","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"text":"?)","kind":"text"}],"languages":["swift"]}]},{"parameters":[{"name":"ns","content":[{"type":"paragraph","inlineContent":[{"text":"The namespace to use for this cache store","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"Directory to cache disk images in","type":"text"}],"type":"paragraph"}],"name":"directory"},{"name":"config","content":[{"inlineContent":[{"text":"The cache config to be used to create the cache. You can provide custom memory cache or disk cache class in the cache config","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/init(namespace:diskCacheDirectory:config:)":{"type":"topic","abstract":[{"type":"text","text":"Init a new cache store with a specific namespace, directory and config."},{"text":" ","type":"text"},{"type":"text","text":"The final disk cache directory should looks like ($directory\/$namespace). And the default config of shared cache, should result in (~\/Library\/Caches\/com.hackemist.SDImageCache\/default\/)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:config:)","title":"init(namespace:diskCacheDirectory:config:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/init(namespace:diskcachedirectory:config:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"namespace","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"diskCacheDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"SDImageCacheConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"initWithNamespace:diskCacheDirectory:config:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"initWithNamespace:diskCacheDirectory:config:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithNamespace:diskCacheDirectory:config:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithNamespace:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier","text":"NSString"},{"text":" *) ","kind":"text"},{"text":"ns","kind":"internalParam"},{"kind":"text","text":" "},{"text":"diskCacheDirectory:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"directory","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"config:"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"text":" *) ","kind":"text"},{"text":"config","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"ns","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The namespace to use for this cache store"}]}]},{"name":"directory","content":[{"type":"paragraph","inlineContent":[{"text":"Directory to cache disk images in","type":"text"}]}]},{"name":"config","content":[{"type":"paragraph","inlineContent":[{"text":"The cache config to be used to create the cache. You can provide custom memory cache or disk cache class in the cache config","type":"text"}]}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","op":"replace","value":"SDImageCacheConfig"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle","value":[{"text":"SDImageCacheConfig","kind":"identifier"}]},{"value":"initWithNamespace:diskCacheDirectory:config:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:diskCacheDirectory:config:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:diskCacheDirectory:config:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNamespace:diskCacheDirectory:config:"}],"op":"replace"},{"value":"SDImageCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}