{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/memoryCache","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memoryCache","kind":"identifier"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","text":"SDMemoryCacheProtocol","preciseIdentifier":"c:objc(pl)SDMemoryCache"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"To customize this class, check "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass"},{"type":"text","text":" property."}]}]}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/memorycache"]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/memorycache"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"memoryCache","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"memoryCache","kind":"identifier"},{"kind":"text","text":": any "},{"text":"SDMemoryCacheProtocol","preciseIdentifier":"c:objc(pl)SDMemoryCache","kind":"typeIdentifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageCache(py)memoryCache","title":"memoryCache","symbolKind":"property","role":"symbol"},"abstract":[{"text":"The memory cache implementation object used for current image cache.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"By default we use "},{"code":"SDMemoryCache","type":"codeVoice"},{"type":"text","text":" class, you can also use this to call your own implementation class method."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"title":"SDMemoryCacheProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","abstract":[{"type":"text","text":"A protocol to allow custom memory cache used in SDImageCache."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/memoryCache":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/memoryCache","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"memoryCache","kind":"identifier"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDMemoryCache","text":"SDMemoryCacheProtocol"}],"navigatorTitle":[{"text":"memoryCache","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/memorycache","title":"memoryCache","type":"topic","abstract":[{"type":"text","text":"The memory cache implementation object used for current image cache."},{"text":" ","type":"text"},{"type":"text","text":"By default we use "},{"type":"codeVoice","code":"SDMemoryCache"},{"text":" class, you can also use this to call your own implementation class method.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"memoryCache"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"memoryCache","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<SDMemoryCache>","preciseIdentifier":"c:Qoobjc(pl)SDMemoryCache","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memoryCache"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","op":"replace","value":"SDImageCache"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/title","value":"SDMemoryCache","op":"replace"},{"value":[{"text":"SDMemoryCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDMemoryCache"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/navigatorTitle"},{"op":"replace","value":"memoryCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1memoryCache\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1memoryCache\/fragments","value":[{"kind":"identifier","text":"memoryCache"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}