{"kind":"symbol","metadata":{"symbolKind":"method","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"queryCacheOperationForKey:done:"}],"title":"queryCacheOperation(forKey:done:)","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","externalID":"c:objc(cs)SDImageCache(im)queryCacheOperationForKey:done:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryCacheOperation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"done","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken","kind":"typeIdentifier"},{"kind":"text","text":"?"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryCacheOperation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"done"},{"kind":"text","text":" "},{"text":"doneBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"? = nil) -> "},{"kind":"typeIdentifier","text":"SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with ","type":"text"},{"code":"SDTransformedKeyForKey","type":"codeVoice"},{"type":"text","text":", "},{"code":"SDThumbnailedKeyForKey","type":"codeVoice"},{"text":", or generate the cache key from url with ","type":"text"},{"type":"codeVoice","code":"cacheKeyForURL:context:"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}]}],"name":"doneBlock"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancelled"}],"type":"paragraph"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:done:)"]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:done:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:done:)","interfaceLanguage":"swift"},"sections":[],"abstract":[{"text":"Asynchronously queries the cache with operation and call the completion when done.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryCompletionBlock":{"kind":"symbol","type":"topic","title":"SDImageCacheQueryCompletionBlock","url":"\/documentation\/sdwebimage\/sdimagecachequerycompletionblock","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","navigatorTitle":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:done:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:done:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryCacheOperation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"done","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","text":"SDImageCacheQueryCompletionBlock"},{"text":"?) -> ","kind":"text"},{"text":"SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"queryCacheOperationForKey:done:"}],"title":"queryCacheOperation(forKey:done:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:done:)","abstract":[{"text":"Asynchronously queries the cache with operation and call the completion when done.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheToken":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheToken"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheToken"}],"title":"SDImageCacheToken","kind":"symbol","abstract":[{"text":"A token associated with each cache query. Can be used to cancel a cache query","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachetoken","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"queryCacheOperationForKey:done:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"queryCacheOperationForKey:done:"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"},{"text":" *) ","kind":"text"},{"text":"queryCacheOperationForKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"done:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(UIImage *, NSData *, enum SDImageCacheType)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#$@E@SDImageCacheType)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"doneBlock","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with "},{"code":"SDTransformedKeyForKey","type":"codeVoice"},{"text":", ","type":"text"},{"type":"codeVoice","code":"SDThumbnailedKeyForKey"},{"text":", or generate the cache key from url with ","type":"text"},{"type":"codeVoice","code":"cacheKeyForURL:context:"},{"type":"text","text":"."}]}]},{"name":"doneBlock","content":[{"inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace"},{"path":"\/primaryContentSections\/2","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancelled","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"value":"SDImageCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","op":"replace","value":[{"text":"SDImageCache","kind":"identifier"}]},{"value":"SDImageCacheQueryCompletionBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/title","op":"replace"},{"op":"replace","value":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:done:)\/title","value":"queryCacheOperationForKey:done:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryCacheOperationForKey:done:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:done:)\/fragments"},{"value":"SDImageCacheToken","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/fragments","value":[{"text":"SDImageCacheToken","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/navigatorTitle","value":[{"text":"SDImageCacheToken","kind":"identifier"}]}]}]}