{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:done:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:done:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"metadata":{"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","symbolKind":"method","role":"symbol","navigatorTitle":[{"text":"queryCacheOperationForKey:options:done:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryCacheOperation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"kind":"text","text":", "},{"text":"done","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken"},{"kind":"text","text":"?"}],"title":"queryCacheOperation(forKey:options:done:)","externalID":"c:objc(cs)SDImageCache(im)queryCacheOperationForKey:options:done:"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryCacheOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":" "},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions"},{"kind":"text","text":" = [], "},{"kind":"externalParam","text":"done"},{"kind":"text","text":" "},{"text":"doneBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"text":"? = nil) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"},{"text":"?","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with "},{"type":"codeVoice","code":"SDTransformedKeyForKey"},{"type":"text","text":", "},{"code":"SDThumbnailedKeyForKey","type":"codeVoice"},{"type":"text","text":", or generate the cache key from url with "},{"code":"cacheKeyForURL:context:","type":"codeVoice"},{"type":"text","text":"."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A mask to specify options to use for this cache query"}]}],"name":"options"},{"name":"doneBlock","content":[{"inlineContent":[{"text":"The completion block. Will not get called if the operation is cancelled","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancelled"}]}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:done:)","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheToken":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheToken"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheToken"}],"title":"SDImageCacheToken","kind":"symbol","abstract":[{"text":"A token associated with each cache query. Can be used to cancel a cache query","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachetoken","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions","navigatorTitle":[{"text":"SDImageCacheOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheOptions","kind":"identifier"}],"title":"SDImageCacheOptions","abstract":[{"text":"Image Cache Options","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:options:done:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:done:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheOperation"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"kind":"text","text":", "},{"text":"done","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"SDImageCacheToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"queryCacheOperationForKey:options:done:","kind":"identifier"}],"title":"queryCacheOperation(forKey:options:done:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:done:)","abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryCompletionBlock":{"kind":"symbol","type":"topic","title":"SDImageCacheQueryCompletionBlock","url":"\/documentation\/sdwebimage\/sdimagecachequerycompletionblock","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","navigatorTitle":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"queryCacheOperationForKey:options:done:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"text","text":"- "},{"text":"queryCacheOperationForKey:options:done:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"SDImageCacheToken","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"queryCacheOperationForKey:"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"done:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(UIImage *, NSData *, enum SDImageCacheType)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#$@E@SDImageCacheType)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"doneBlock","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"key","content":[{"inlineContent":[{"text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with ","type":"text"},{"type":"codeVoice","code":"SDTransformedKeyForKey"},{"type":"text","text":", "},{"code":"SDThumbnailedKeyForKey","type":"codeVoice"},{"type":"text","text":", or generate the cache key from url with "},{"code":"cacheKeyForURL:context:","type":"codeVoice"},{"text":".","type":"text"}],"type":"paragraph"}]},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this cache query"}],"type":"paragraph"}]},{"name":"doneBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}]}]}]}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancelled","type":"text"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","op":"replace","value":"SDImageCache"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/title","value":"SDImageCacheToken"},{"op":"replace","value":[{"text":"SDImageCacheToken","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageCacheToken"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","value":"SDImageCacheOptions","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/navigatorTitle","op":"replace","value":[{"text":"SDImageCacheOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:done:)\/title","value":"queryCacheOperationForKey:options:done:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:done:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryCacheOperationForKey:options:done:"}]},{"op":"replace","value":"SDImageCacheQueryCompletionBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/title"},{"op":"replace","value":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}]}]}]}