{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:done:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"queryCacheOperation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions"},{"kind":"text","text":" = [], "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"done"},{"text":" ","kind":"text"},{"text":"doneBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with ","type":"text"},{"type":"codeVoice","code":"SDTransformedKeyForKey"},{"type":"text","text":", "},{"type":"codeVoice","code":"SDThumbnailedKeyForKey"},{"type":"text","text":", or generate the cache key from url with "},{"type":"codeVoice","code":"cacheKeyForURL:context:"},{"text":".","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"A mask to specify options to use for this cache query","type":"text"}],"type":"paragraph"}],"name":"options"},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"type":"codeVoice","code":"SDWebImageContextOption"},{"type":"text","text":". This hold the extra objects which "},{"code":"options","type":"codeVoice"},{"text":" enum can not hold.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}],"type":"paragraph"}],"name":"doneBlock"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancellederation, will callback immediately when cancelled"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:done:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:done:)"]}],"metadata":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"queryCacheOperation","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"text":"done","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","text":"SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)SDImageCacheToken","kind":"typeIdentifier","text":"SDImageCacheToken"},{"text":"?","kind":"text"}],"role":"symbol","roleHeading":"Instance Method","modules":[{"name":"SDWebImage"}],"title":"queryCacheOperation(forKey:options:context:done:)","externalID":"c:objc(cs)SDImageCache(im)queryCacheOperationForKey:options:context:done:","symbolKind":"method","navigatorTitle":[{"text":"queryCacheOperationForKey:options:context:done:","kind":"identifier"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions","navigatorTitle":[{"text":"SDImageCacheOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheOptions","kind":"identifier"}],"title":"SDImageCacheOptions","abstract":[{"text":"Image Cache Options","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryCompletionBlock":{"kind":"symbol","type":"topic","title":"SDImageCacheQueryCompletionBlock","url":"\/documentation\/sdwebimage\/sdimagecachequerycompletionblock","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","navigatorTitle":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:options:context:done:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"queryCacheOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"done"},{"kind":"text","text":": "},{"text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"queryCacheOperationForKey:options:context:done:","kind":"identifier"}],"type":"topic","role":"symbol","title":"queryCacheOperation(forKey:options:context:done:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:done:)","abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:done:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheToken":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheToken"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheToken"}],"title":"SDImageCacheToken","kind":"symbol","abstract":[{"text":"A token associated with each cache query. Can be used to cancel a cache query","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachetoken","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"queryCacheOperationForKey:options:context:done:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryCacheOperationForKey:options:context:done:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken","kind":"typeIdentifier","text":"SDImageCacheToken"},{"text":" *) ","kind":"text"},{"text":"queryCacheOperationForKey:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","text":"SDWebImageContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"done:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSData *, enum SDImageCacheType)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#$@E@SDImageCacheType)"},{"text":") ","kind":"text"},{"text":"doneBlock","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with "},{"type":"codeVoice","code":"SDTransformedKeyForKey"},{"type":"text","text":", "},{"type":"codeVoice","code":"SDThumbnailedKeyForKey"},{"text":", or generate the cache key from url with ","type":"text"},{"type":"codeVoice","code":"cacheKeyForURL:context:"},{"text":".","type":"text"}],"type":"paragraph"}],"name":"key"},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A mask to specify options to use for this cache query"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A context contains different options to perform specify changes or processes, see ","type":"text"},{"code":"SDWebImageContextOption","type":"codeVoice"},{"type":"text","text":". This hold the extra objects which "},{"type":"codeVoice","code":"options"},{"text":" enum can not hold.","type":"text"}]}],"name":"context"},{"name":"doneBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancellederation, will callback immediately when cancelled","type":"text"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","op":"replace","value":"SDImageCacheOptions"},{"value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/title","value":"SDImageCacheQueryCompletionBlock","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/fragments","value":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]},{"value":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/navigatorTitle"},{"value":"queryCacheOperationForKey:options:context:done:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:done:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:done:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"queryCacheOperationForKey:options:context:done:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/title","op":"replace","value":"SDImageCacheToken"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/fragments","value":[{"kind":"identifier","text":"SDImageCacheToken"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/navigatorTitle","value":[{"text":"SDImageCacheToken","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]}]}]}