{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:cacheType:done:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheOperation"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"},{"kind":"text","text":" = [], "},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":" "},{"kind":"internalParam","text":"queryCacheType"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"done","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"doneBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil) -> ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken"},{"kind":"text","text":"?"}]}]},{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with ","type":"text"},{"code":"SDTransformedKeyForKey","type":"codeVoice"},{"text":", ","type":"text"},{"code":"SDThumbnailedKeyForKey","type":"codeVoice"},{"type":"text","text":", or generate the cache key from url with "},{"code":"cacheKeyForURL:context:","type":"codeVoice"},{"text":".","type":"text"}]}]},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this cache query"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"code":"SDWebImageContextOption","type":"codeVoice"},{"text":". This hold the extra objects which ","type":"text"},{"code":"options","type":"codeVoice"},{"text":" enum can not hold.","type":"text"}]}],"name":"context"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Specify where to query the cache from. By default we use ","type":"text"},{"code":".all","type":"codeVoice"},{"type":"text","text":", which means both memory cache and disk cache. You can choose to query memory only or disk only as well. Pass "},{"type":"codeVoice","code":".none"},{"type":"text","text":" is invalid and callback with nil immediately."}]}],"name":"queryCacheType"},{"name":"doneBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}]}]}]},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"inlineContent":[{"text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancelled","type":"text"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:cachetype:done:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:cachetype:done:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"queryCacheOperationForKey:options:context:cacheType:done:","kind":"identifier"}],"roleHeading":"Instance Method","symbolKind":"method","title":"queryCacheOperation(forKey:options:context:cacheType:done:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryCacheOperation"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"cacheType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"text":", ","kind":"text"},{"text":"done","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock"},{"text":"?) -> ","kind":"text"},{"text":"SDImageCacheToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken"},{"text":"?","kind":"text"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","externalID":"c:objc(cs)SDImageCache(im)queryCacheOperationForKey:options:context:cacheType:done:"},"abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:options:context:cacheType:done:)":{"navigatorTitle":[{"kind":"identifier","text":"queryCacheOperationForKey:options:context:cacheType:done:"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:cacheType:done:)","title":"queryCacheOperation(forKey:options:context:cacheType:done:)","abstract":[{"text":"Asynchronously queries the cache with operation and call the completion when done.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:cachetype:done:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryCacheOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"SDImageCacheOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"text":"SDImageCacheType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"done"},{"kind":"text","text":": "},{"text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryCompletionBlock":{"kind":"symbol","type":"topic","title":"SDImageCacheQueryCompletionBlock","url":"\/documentation\/sdwebimage\/sdimagecachequerycompletionblock","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","navigatorTitle":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheToken":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheToken"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheToken"}],"title":"SDImageCacheToken","kind":"symbol","abstract":[{"text":"A token associated with each cache query. Can be used to cancel a cache query","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachetoken","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image Cache Type"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","url":"\/documentation\/sdwebimage\/sdimagecachetype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheType"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions","navigatorTitle":[{"text":"SDImageCacheOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheOptions","kind":"identifier"}],"title":"SDImageCacheOptions","abstract":[{"text":"Image Cache Options","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"queryCacheOperationForKey:options:context:cacheType:done:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"queryCacheOperationForKey:options:context:cacheType:done:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","text":"SDImageCacheToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken"},{"text":" *) ","kind":"text"},{"text":"queryCacheOperationForKey:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"text":" ","kind":"text"},{"text":"context:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","text":"SDWebImageContext","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheType:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType"},{"text":") ","kind":"text"},{"text":"queryCacheType","kind":"internalParam"},{"kind":"text","text":" "},{"text":"done:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(UIImage *, NSData *, enum SDImageCacheType)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#$@E@SDImageCacheType)"},{"kind":"text","text":") "},{"text":"doneBlock","kind":"internalParam"},{"text":";","kind":"text"}]}]}},{"value":{"parameters":[{"name":"key","content":[{"inlineContent":[{"text":"The unique key used to store the wanted image. If you want transformed or thumbnail image, calculate the key with ","type":"text"},{"type":"codeVoice","code":"SDTransformedKeyForKey"},{"type":"text","text":", "},{"code":"SDThumbnailedKeyForKey","type":"codeVoice"},{"text":", or generate the cache key from url with ","type":"text"},{"code":"cacheKeyForURL:context:","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this cache query"}],"type":"paragraph"}],"name":"options"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"code":"SDWebImageContextOption","type":"codeVoice"},{"type":"text","text":". This hold the extra objects which "},{"type":"codeVoice","code":"options"},{"type":"text","text":" enum can not hold."}]}],"name":"context"},{"content":[{"inlineContent":[{"text":"Specify where to query the cache from. By default we use ","type":"text"},{"code":".all","type":"codeVoice"},{"text":", which means both memory cache and disk cache. You can choose to query memory only or disk only as well. Pass ","type":"text"},{"code":".none","type":"codeVoice"},{"text":" is invalid and callback with nil immediately.","type":"text"}],"type":"paragraph"}],"name":"queryCacheType"},{"name":"doneBlock","content":[{"inlineContent":[{"text":"The completion block. Will not get called if the operation is cancelled","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":{"content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A SDImageCacheToken instance containing the cache operation, will callback immediately when cancelled"}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","value":"SDImageCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:cacheType:done:)\/title","value":"queryCacheOperationForKey:options:context:cacheType:done:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"queryCacheOperationForKey:options:context:cacheType:done:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:cacheType:done:)\/fragments"},{"value":"SDWebImageContextOption","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/title","value":"SDImageCacheQueryCompletionBlock"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/title","op":"replace","value":"SDImageCacheToken"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheToken"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheToken"}]},{"value":"SDImageCacheType","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title"},{"value":[{"kind":"identifier","text":"SDImageCacheType"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/navigatorTitle","value":[{"text":"SDImageCacheType","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","value":"SDImageCacheOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments","value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageCacheOptions"}]}]}]}