{"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completionBlock","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"kind":"text","text":"? = nil)"}]},{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?) ","kind":"text"},{"text":"async","kind":"keyword"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The image to store","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The unique image cache key, usually it’s image absolute URL","type":"text"}]}],"name":"key"},{"name":"completionBlock","content":[{"inlineContent":[{"text":"A block executed after the operation is finished","type":"text"}],"type":"paragraph"}]}]}],"abstract":[{"text":"Asynchronously store an image into memory and disk cache at the given key.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:forkey:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:forkey:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"metadata":{"roleHeading":"Instance Method","modules":[{"name":"SDWebImage"}],"role":"symbol","title":"store(_:forKey:completion:)","symbolKind":"method","navigatorTitle":[{"text":"storeImage:forKey:completion:","kind":"identifier"}],"externalID":"c:objc(cs)SDImageCache(im)storeImage:forKey:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:completion:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/store(_:forKey:completion:)":{"abstract":[{"text":"Asynchronously store an image into memory and disk cache at the given key.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"storeImage:forKey:completion:"}],"title":"store(_:forKey:completion:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:forkey:completion:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"store"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageNoParamsBlock":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageNoParamsBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagenoparamsblock","title":"SDWebImageNoParamsBlock","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"storeImage:forKey:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeImage:forKey:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"storeImage:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":" *) "},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"forKey:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"text":"void (^)(void)","preciseIdentifier":"c:BFv()","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"completionBlock","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"text":"The image to store","type":"text"}]}]},{"name":"key","content":[{"inlineContent":[{"text":"The unique image cache key, usually it’s image absolute URL","type":"text"}],"type":"paragraph"}]},{"name":"completionBlock","content":[{"inlineContent":[{"text":"A block executed after the operation is finished","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:forKey:completion:)\/title","value":"storeImage:forKey:completion:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:forKey:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"storeImage:forKey:completion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/title","op":"replace","value":"SDWebImageNoParamsBlock"},{"op":"replace","value":[{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/fragments"},{"value":[{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/navigatorTitle","op":"replace"},{"value":"SDImageCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}