{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(body:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(body:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(body:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the request modifier with HTTP Body."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithBody:"}],"role":"symbol","title":"init(body:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"symbolKind":"init","externalID":"c:objc(cs)SDWebImageDownloaderRequestModifier(im)initWithBody:","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class":{"role":"symbol","title":"SDWebImageDownloaderRequestModifier","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"abstract":[{"type":"text","text":"A downloader request modifier class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(body:)":{"role":"symbol","title":"init(body:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Create the request modifier with HTTP Body."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(body:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBody:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(body:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBody:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBody:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBody:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"body"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/title","value":"SDWebImageDownloaderRequestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(body:)\/title","value":"initWithBody:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(body:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBody:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}