{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(method:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(method:)"]}],"metadata":{"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"title":"init(method:)","role":"symbol","roleHeading":"Initializer","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"initWithMethod:","kind":"identifier"}],"externalID":"c:objc(cs)SDWebImageDownloaderRequestModifier(im)initWithMethod:","symbolKind":"init"},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"abstract":[{"type":"text","text":"Create the request modifier with HTTP Method."}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"method"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"HTTP Method, nil means to GET.","type":"text"}]}],"name":"method"}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is for convenience, if you need code to control the logic, use block API instead."}]}],"style":"note","type":"aside"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class","role":"symbol","abstract":[{"text":"A downloader request modifier class with block.","type":"text"}],"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"type":"topic","title":"SDWebImageDownloaderRequestModifier","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(method:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:)","abstract":[{"text":"Create the request modifier with HTTP Method.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(method:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"method"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithMethod:","kind":"identifier"}],"kind":"symbol","title":"init(method:)","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"initWithMethod:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMethod:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithMethod:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"method","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"HTTP Method, nil means to GET.","type":"text"}],"type":"paragraph"}],"name":"method"}]},"path":"\/primaryContentSections\/1"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/title","value":"SDWebImageDownloaderRequestModifier","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/navigatorTitle","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(method:)\/title","value":"initWithMethod:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(method:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithMethod:","kind":"identifier"}]}]}]}