{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagepixelformat\/alignment"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagepixelformat\/alignment"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/alignment","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Typically is 32, the 8 pixels bytesPerRow."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"title":"alignment","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@S@SDImagePixelFormat@FI@alignment","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"alignment"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat":{"role":"symbol","title":"SDImagePixelFormat","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePixelFormat"}],"abstract":[{"type":"text","text":"The pixel format about the information to call "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":" suitable for current hardware rendering"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImagePixelFormat"}],"url":"\/documentation\/sdwebimage\/sdimagepixelformat"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat/alignment":{"role":"symbol","title":"alignment","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"Typically is 32, the 8 pixels bytesPerRow."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/alignment","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"alignment"}],"url":"\/documentation\/sdwebimage\/sdimagepixelformat\/alignment"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"alignment"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"alignment"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"size_t","preciseIdentifier":"c:@T@size_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"alignment"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/title","value":"SDImagePixelFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/fragments","value":[{"kind":"identifier","text":"SDImagePixelFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat~1alignment\/title","value":"alignment"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat~1alignment\/fragments","value":[{"kind":"identifier","text":"alignment"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}