{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitmapInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGBitmapInfo","preciseIdentifier":"c:@E@CGBitmapInfo"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagepixelformat\/bitmapinfo"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagepixelformat\/bitmapinfo"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/bitmapInfo","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Typically is pre-multiplied RGBA8888 for alpha image, RGBX8888 for non-alpha image."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitmapInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGBitmapInfo","preciseIdentifier":"c:@E@CGBitmapInfo"}],"title":"bitmapInfo","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@S@SDImagePixelFormat@FI@bitmapInfo","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"bitmapInfo"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat":{"role":"symbol","title":"SDImagePixelFormat","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePixelFormat"}],"abstract":[{"type":"text","text":"The pixel format about the information to call "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":" suitable for current hardware rendering"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImagePixelFormat"}],"url":"\/documentation\/sdwebimage\/sdimagepixelformat"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat/bitmapInfo":{"role":"symbol","title":"bitmapInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitmapInfo"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGBitmapInfo","preciseIdentifier":"c:@E@CGBitmapInfo"}],"abstract":[{"type":"text","text":"Typically is pre-multiplied RGBA8888 for alpha image, RGBX8888 for non-alpha image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/bitmapInfo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"bitmapInfo"}],"url":"\/documentation\/sdwebimage\/sdimagepixelformat\/bitmapinfo"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"bitmapInfo"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"bitmapInfo"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"typeIdentifier","text":"CGBitmapInfo","preciseIdentifier":"c:@E@CGBitmapInfo"},{"kind":"text","text":" "},{"kind":"identifier","text":"bitmapInfo"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/title","value":"SDImagePixelFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/fragments","value":[{"kind":"identifier","text":"SDImagePixelFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat~1bitmapInfo\/title","value":"bitmapInfo"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat~1bitmapInfo\/fragments","value":[{"kind":"identifier","text":"bitmapInfo"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}