{"metadata":{"modules":[{"name":"SDWebImage"}],"externalID":"s:So18SDImagePixelFormatVABycfc","role":"symbol","symbolKind":"init","title":"init()","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"()"}],"roleHeading":"Initializer"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagepixelformat\/init()"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"()","kind":"text"}],"platforms":["iOS"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/init()"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat/init()":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"()","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdimagepixelformat\/init()","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/init()","title":"init()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat":{"navigatorTitle":[{"text":"SDImagePixelFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"The pixel format about the information to call "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":" suitable for current hardware rendering"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImagePixelFormat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagepixelformat","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat","title":"SDImagePixelFormat"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/title","op":"replace","value":"SDImagePixelFormat"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/fragments","op":"replace","value":[{"text":"SDImagePixelFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/navigatorTitle","value":[{"text":"SDImagePixelFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}