{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"bitmapInfo","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGBitmapInfo","kind":"typeIdentifier","preciseIdentifier":"c:@E@CGBitmapInfo"},{"text":", ","kind":"text"},{"text":"alignment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagepixelformat\/init(bitmapinfo:alignment:)"]}],"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/init(bitmapInfo:alignment:)","interfaceLanguage":"swift"},"metadata":{"symbolKind":"init","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"bitmapInfo"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CGBitmapInfo","kind":"typeIdentifier","text":"CGBitmapInfo"},{"text":", ","kind":"text"},{"text":"alignment","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"role":"symbol","title":"init(bitmapInfo:alignment:)","roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"externalID":"s:So18SDImagePixelFormatV10bitmapInfo9alignmentABSo08CGBitmapE0V_Sitcfc"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat":{"navigatorTitle":[{"text":"SDImagePixelFormat","kind":"identifier"}],"abstract":[{"type":"text","text":"The pixel format about the information to call "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":" suitable for current hardware rendering"}],"role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImagePixelFormat","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagepixelformat","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat","title":"SDImagePixelFormat"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePixelFormat/init(bitmapInfo:alignment:)":{"type":"topic","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"bitmapInfo","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@CGBitmapInfo","text":"CGBitmapInfo","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"alignment"},{"kind":"text","text":": "},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":")","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdimagepixelformat\/init(bitmapinfo:alignment:)","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePixelFormat\/init(bitmapInfo:alignment:)","title":"init(bitmapInfo:alignment:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SDImagePixelFormat","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/fragments","op":"replace","value":[{"text":"SDImagePixelFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePixelFormat\/navigatorTitle","value":[{"text":"SDImagePixelFormat","kind":"identifier"}]}]}]}