{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispatch"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/dispatch"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/dispatch"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/dispatch","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Follow async\/sync using the correspond "},{"type":"codeVoice","code":"dispatch_async"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"dispatch_sync"},{"type":"text","text":" to dispatch block on queue"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispatch"}],"title":"SDCallbackPolicy.dispatch","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDCallbackPolicy@SDCallbackPolicyDispatch","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDCallbackPolicyDispatch"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/dispatch":{"role":"symbol","title":"SDCallbackPolicy.dispatch","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"dispatch"}],"abstract":[{"type":"text","text":"Follow async\/sync using the correspond "},{"type":"codeVoice","code":"dispatch_async"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"dispatch_sync"},{"type":"text","text":" to dispatch block on queue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/dispatch","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDCallbackPolicyDispatch"}],"url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/dispatch"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy":{"role":"symbol","title":"SDCallbackPolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDCallbackPolicy"}],"abstract":[{"type":"text","text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use "},{"type":"codeVoice","code":"dispatch_async\/dispatch_sync"},{"type":"text","text":", check if current queue match target queue, or just invoke without any context."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDCallbackPolicy"}],"url":"\/documentation\/sdwebimage\/sdcallbackpolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDCallbackPolicyDispatch"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDCallbackPolicyDispatch"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDCallbackPolicyDispatch"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1dispatch\/title","value":"SDCallbackPolicyDispatch"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1dispatch\/fragments","value":[{"kind":"identifier","text":"SDCallbackPolicyDispatch"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/title","value":"SDCallbackPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/fragments","value":[{"kind":"identifier","text":"SDCallbackPolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}