{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/invoke"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/invoke"]},{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/invoke"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy"]]},"kind":"symbol","sections":[],"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Case","externalID":"c:@E@SDCallbackPolicy@SDCallbackPolicyInvoke","title":"SDCallbackPolicy.invoke","symbolKind":"case","navigatorTitle":[{"text":"SDCallbackPolicyInvoke","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invoke"}]},"abstract":[{"type":"text","text":"Ignore any async\/sync and just directly invoke "},{"type":"codeVoice","code":"block"},{"type":"text","text":" in current queue (without "},{"type":"codeVoice","code":"dispatch_async"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"dispatch_sync"},{"type":"text","text":")"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invoke","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use "},{"type":"codeVoice","code":"dispatch_async\/dispatch_sync"},{"text":", check if current queue match target queue, or just invoke without any context.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","url":"\/documentation\/sdwebimage\/sdcallbackpolicy","navigatorTitle":[{"text":"SDCallbackPolicy","kind":"identifier"}],"title":"SDCallbackPolicy","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/invoke":{"title":"SDCallbackPolicy.invoke","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invoke","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Ignore any async\/sync and just directly invoke "},{"type":"codeVoice","code":"block"},{"text":" in current queue (without ","type":"text"},{"type":"codeVoice","code":"dispatch_async"},{"text":"\/","type":"text"},{"code":"dispatch_sync","type":"codeVoice"},{"text":")","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/invoke","navigatorTitle":[{"kind":"identifier","text":"SDCallbackPolicyInvoke"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/invoke","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","value":"SDCallbackPolicyInvoke","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDCallbackPolicyInvoke","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SDCallbackPolicyInvoke","kind":"identifier"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/title","value":"SDCallbackPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/fragments","value":[{"text":"SDCallbackPolicy","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDCallbackPolicy"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/navigatorTitle"},{"value":"SDCallbackPolicyInvoke","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1invoke\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDCallbackPolicyInvoke"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1invoke\/fragments"}]}]}