{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"safeAsyncMainThread","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy"]]},"metadata":{"title":"SDCallbackPolicy.safeAsyncMainThread","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDCallbackPolicySafeAsyncMainThread","kind":"identifier"}],"roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safeAsyncMainThread"}],"externalID":"c:@E@SDCallbackPolicy@SDCallbackPolicySafeAsyncMainThread","symbolKind":"case","role":"symbol"},"abstract":[{"type":"text","text":"Ensure callback in main thread. Do "},{"type":"codeVoice","code":"dispatch_async"},{"type":"text","text":" if the "},{"type":"codeVoice","code":"NSThread.isMainTrhead == true"},{"text":" ; else do invoke ","type":"text"},{"type":"codeVoice","code":"block"},{"type":"text","text":". Never use "},{"type":"codeVoice","code":"dispatch_sync"},{"type":"text","text":", suitable for special UI-related code"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/safeasyncmainthread"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/safeasyncmainthread"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeAsyncMainThread"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/safeAsyncMainThread":{"title":"SDCallbackPolicy.safeAsyncMainThread","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"safeAsyncMainThread","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ensure callback in main thread. Do ","type":"text"},{"type":"codeVoice","code":"dispatch_async"},{"text":" if the ","type":"text"},{"code":"NSThread.isMainTrhead == true","type":"codeVoice"},{"text":" ; else do invoke ","type":"text"},{"type":"codeVoice","code":"block"},{"type":"text","text":". Never use "},{"type":"codeVoice","code":"dispatch_sync"},{"text":", suitable for special UI-related code","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeAsyncMainThread","navigatorTitle":[{"text":"SDCallbackPolicySafeAsyncMainThread","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/safeasyncmainthread","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use "},{"type":"codeVoice","code":"dispatch_async\/dispatch_sync"},{"text":", check if current queue match target queue, or just invoke without any context.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","url":"\/documentation\/sdwebimage\/sdcallbackpolicy","navigatorTitle":[{"text":"SDCallbackPolicy","kind":"identifier"}],"title":"SDCallbackPolicy","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SDCallbackPolicySafeAsyncMainThread"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDCallbackPolicySafeAsyncMainThread"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDCallbackPolicySafeAsyncMainThread"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SDCallbackPolicySafeAsyncMainThread","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeAsyncMainThread\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeAsyncMainThread\/fragments","value":[{"text":"SDCallbackPolicySafeAsyncMainThread","kind":"identifier"}]},{"value":"SDCallbackPolicy","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/fragments","op":"replace","value":[{"text":"SDCallbackPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"SDCallbackPolicy"}],"op":"replace"}]}]}