{"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy"]]},"abstract":[{"text":"When the current queue is equal to callback queue, sync\/async will just invoke ","type":"text"},{"type":"codeVoice","code":"block"},{"type":"text","text":" directly without dispatch. Else it use "},{"type":"codeVoice","code":"dispatch_async"},{"text":"\/","type":"text"},{"code":"dispatch_sync","type":"codeVoice"},{"type":"text","text":" to dispatch block on queue. This is useful for UIKit rendering to ensure all blocks executed in the same runloop"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safeExecute"}],"languages":["swift"],"platforms":["iOS"]}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeExecute","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Case","navigatorTitle":[{"text":"SDCallbackPolicySafeExecute","kind":"identifier"}],"symbolKind":"case","role":"symbol","title":"SDCallbackPolicy.safeExecute","externalID":"c:@E@SDCallbackPolicy@SDCallbackPolicySafeExecute","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"safeExecute","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/safeexecute"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy\/safeexecute"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/safeExecute":{"role":"symbol","type":"topic","title":"SDCallbackPolicy.safeExecute","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/safeexecute","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safeExecute"}],"kind":"symbol","abstract":[{"type":"text","text":"When the current queue is equal to callback queue, sync\/async will just invoke "},{"type":"codeVoice","code":"block"},{"text":" directly without dispatch. Else it use ","type":"text"},{"code":"dispatch_async","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"dispatch_sync","type":"codeVoice"},{"type":"text","text":" to dispatch block on queue. This is useful for UIKit rendering to ensure all blocks executed in the same runloop"}],"navigatorTitle":[{"text":"SDCallbackPolicySafeExecute","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeExecute"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use "},{"type":"codeVoice","code":"dispatch_async\/dispatch_sync"},{"text":", check if current queue match target queue, or just invoke without any context.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","url":"\/documentation\/sdwebimage\/sdcallbackpolicy","navigatorTitle":[{"text":"SDCallbackPolicy","kind":"identifier"}],"title":"SDCallbackPolicy","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SDCallbackPolicySafeExecute"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDCallbackPolicySafeExecute"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDCallbackPolicySafeExecute"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SDCallbackPolicySafeExecute","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeExecute\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeExecute\/fragments","value":[{"text":"SDCallbackPolicySafeExecute","kind":"identifier"}]},{"value":"SDCallbackPolicy","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/title"},{"op":"replace","value":[{"text":"SDCallbackPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDCallbackPolicy"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/navigatorTitle"}]}]}