{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(cs)UIImage"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSItemProviderReading","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSItemProviderWriting","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSSecureCoding","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSObject","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)SDAnimatedImage","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)SDAnimatedImageProvider","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s7CVarArgP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SQ","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SH","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s8SendableP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)UIAccessibilityIdentification","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)UIItemProviderPresentationSizeProviding"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A UIImage subclass wrapper for Lottie animation"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"title":"LottieImage","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SDWebImageLottiePlugin@objc(cs)LottieImage","modules":[{"name":"SDWebImageLottiePlugin"}],"navigatorTitle":[{"kind":"identifier","text":"LottieImage"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(animatedCoder:scale:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(animation:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(coder:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(data:scale:options:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageData","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrameCount","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageLoopCount","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animation","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/fontProvider","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/imageProvider","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/size","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/textProvider"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageDuration(at:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrame(at:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/encode(with:)"]}],"references":{"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)SDAnimatedImageProvider":{"type":"unresolvable","title":"SDWebImage.SDAnimatedImageProvider","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)SDAnimatedImageProvider"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSSecureCoding"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageFrame(at:)":{"role":"symbol","title":"animatedImageFrame(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:22SDWebImageLottiePlugin08PlatformB0a"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrame(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameAtIndex:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframe(at:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSObject"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/init(animation:)":{"role":"symbol","title":"init(animation:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Animation","preciseIdentifier":"s:6Lottie9AnimationC"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Init the LottieImage with lottie animation model"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(animation:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(animation:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSCoding"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageFrameCount":{"role":"symbol","title":"animatedImageFrameCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrameCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrameCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameCount"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframecount"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSItemProviderReading":{"type":"unresolvable","title":"Foundation.NSItemProviderReading","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSItemProviderReading"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/imageProvider":{"role":"symbol","title":"imageProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationImageProvider","preciseIdentifier":"s:6Lottie22AnimationImageProviderP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The lottie image provider, used for frame extracting"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/imageProvider","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/imageprovider"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageDuration(at:)":{"role":"symbol","title":"animatedImageDuration(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageDuration(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageDurationAtIndex:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageduration(at:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s8SendableP"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)SDAnimatedImage":{"type":"unresolvable","title":"SDAnimatedImage","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)SDAnimatedImage"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/size":{"role":"symbol","title":"size","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/size","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"size"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/size"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage":{"role":"symbol","title":"LottieImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"abstract":[{"type":"text","text":"A UIImage subclass wrapper for Lottie animation"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LottieImage"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSItemProviderWriting":{"type":"unresolvable","title":"Foundation.NSItemProviderWriting","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSItemProviderWriting"},"doc://org.cocoapods.SDWebImageLottiePlugin/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SH"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageLoopCount":{"role":"symbol","title":"animatedImageLoopCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageLoopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageLoopCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageLoopCount"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageloopcount"},"doc://org.cocoapods.SDWebImageLottiePlugin/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SDWebImageLottiePlugin/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/encode(with:)":{"role":"symbol","title":"encode(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/encode(with:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"encodeWithCoder:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/encode(with:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/init(data:scale:options:)":{"role":"symbol","title":"init(data:scale:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(data:scale:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:options:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(data:scale:options:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SQ"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(coder:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)UIItemProviderPresentationSizeProviding":{"type":"unresolvable","title":"UIKit.UIItemProviderPresentationSizeProviding","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)UIItemProviderPresentationSizeProviding"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/init(animatedCoder:scale:)":{"role":"symbol","title":"init(animatedCoder:scale:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"animatedCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImageCoder","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(animatedCoder:scale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithAnimatedCoder:scale:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(animatedcoder:scale:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s7CVarArgP"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/fontProvider":{"role":"symbol","title":"fontProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fontProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationFontProvider","preciseIdentifier":"s:6Lottie21AnimationFontProviderP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The lottie font provider, used for frame extracting"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/fontProvider","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/fontprovider"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(cs)UIImage":{"type":"unresolvable","title":"UIImage","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(cs)UIImage"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animation":{"role":"symbol","title":"animation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Animation","preciseIdentifier":"s:6Lottie9AnimationC"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The lottie animation model"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animation","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animation"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/textProvider":{"role":"symbol","title":"textProvider","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"textProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationTextProvider","preciseIdentifier":"s:6Lottie21AnimationTextProviderP"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The lottie text provider, used for frame extracting"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/textProvider","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/textprovider"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)UIAccessibilityIdentification"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageData":{"role":"symbol","title":"animatedImageData","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageData"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimagedata"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin":{"role":"collection","title":"SDWebImageLottiePlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LottieImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LottieImage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LottieImage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageData","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrameCount","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageLoopCount","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/size"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageDuration(at:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrame(at:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/encode(with:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(animatedCoder:scale:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(coder:)","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(data:scale:options:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrame(at:)\/title","value":"animatedImageFrameAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrame(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animatedImageFrameAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrameCount\/title","value":"animatedImageFrameCount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrameCount\/fragments","value":[{"kind":"identifier","text":"animatedImageFrameCount"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageDuration(at:)\/title","value":"animatedImageDurationAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageDuration(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animatedImageDurationAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1size\/title","value":"size"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1size\/fragments","value":[{"kind":"identifier","text":"size"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/title","value":"LottieImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/fragments","value":[{"kind":"identifier","text":"LottieImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageLoopCount\/title","value":"animatedImageLoopCount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageLoopCount\/fragments","value":[{"kind":"identifier","text":"animatedImageLoopCount"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1encode(with:)\/title","value":"encodeWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1encode(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodeWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(data:scale:options:)\/title","value":"initWithData:scale:options:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(data:scale:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:scale:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(animatedCoder:scale:)\/title","value":"initWithAnimatedCoder:scale:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(animatedCoder:scale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAnimatedCoder:scale:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageData\/title","value":"animatedImageData"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageData\/fragments","value":[{"kind":"identifier","text":"animatedImageData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}