{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieCompositionLayer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagelottieplugin\/lottiecompositionlayer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagelottieplugin\/lottiecompositionlayer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(cs)CALayer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSCoding","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSSecureCoding","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSObject","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)CAMediaTiming","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s7CVarArgP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SQ","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieCompositionLayer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This layer is used like Lottie 2’s"},{"type":"codeVoice","code":"LOTCompositionContainer"},{"type":"text","text":". Typically private, use with caution :)"},{"type":"text","text":" "},{"type":"text","text":"Which can render the specify frame into CGBitmapContext by calling "},{"type":"codeVoice","code":"layer.render(in:)"},{"type":"text","text":", used for debugging or some snapshot use case"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieCompositionLayer"}],"title":"LottieCompositionLayer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:@M@SDWebImageLottiePlugin@objc(cs)LottieCompositionLayer","modules":[{"name":"SDWebImageLottiePlugin"}],"navigatorTitle":[{"kind":"identifier","text":"LottieCompositionLayer"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieCompositionLayer\/init(animation:imageProvider:textProvider:fontProvider:)"]},{"title":"Instance Methods","identifiers":["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieCompositionLayer\/displayWithFrame(frame:forceUpdates:)"]}],"references":{"doc://org.cocoapods.SDWebImageLottiePlugin/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSCoding"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSObject"},"doc://org.cocoapods.SDWebImageLottiePlugin/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SH"},"doc://org.cocoapods.SDWebImageLottiePlugin/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SDWebImageLottiePlugin/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/s7CVarArgP"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)NSSecureCoding":{"type":"unresolvable","title":"Foundation.NSSecureCoding","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)NSSecureCoding"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(cs)CALayer":{"type":"unresolvable","title":"CALayer","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(cs)CALayer"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin":{"role":"collection","title":"SDWebImageLottiePlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin"},"doc://org.cocoapods.SDWebImageLottiePlugin/objc(pl)CAMediaTiming":{"type":"unresolvable","title":"QuartzCore.CAMediaTiming","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/objc(pl)CAMediaTiming"},"doc://org.cocoapods.SDWebImageLottiePlugin/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/SQ"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieCompositionLayer/displayWithFrame(frame:forceUpdates:)":{"role":"symbol","title":"displayWithFrame(frame:forceUpdates:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"displayWithFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"forceUpdates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Display the layer tree to specify frame time, then call "},{"type":"codeVoice","code":"render(in:)"},{"type":"text","text":" to draw on CGBitmapContext"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieCompositionLayer\/displayWithFrame(frame:forceUpdates:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottiecompositionlayer\/displaywithframe(frame:forceupdates:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieCompositionLayer":{"role":"symbol","title":"LottieCompositionLayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieCompositionLayer"}],"abstract":[{"type":"text","text":"This layer is used like Lottie 2’s"},{"type":"codeVoice","code":"LOTCompositionContainer"},{"type":"text","text":". Typically private, use with caution :)"},{"type":"text","text":" "},{"type":"text","text":"Which can render the specify frame into CGBitmapContext by calling "},{"type":"codeVoice","code":"layer.render(in:)"},{"type":"text","text":", used for debugging or some snapshot use case"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieCompositionLayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LottieCompositionLayer"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottiecompositionlayer"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieCompositionLayer/init(animation:imageProvider:textProvider:fontProvider:)":{"role":"symbol","title":"init(animation:imageProvider:textProvider:fontProvider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"animation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Animation","preciseIdentifier":"s:6Lottie9AnimationC"},{"kind":"text","text":", "},{"kind":"externalParam","text":"imageProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationImageProvider","preciseIdentifier":"s:6Lottie22AnimationImageProviderP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"textProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationTextProvider","preciseIdentifier":"s:6Lottie21AnimationTextProviderP"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"fontProvider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnimationFontProvider","preciseIdentifier":"s:6Lottie21AnimationFontProviderP"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Initializes an LottieCompositionLayer with an animation."}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieCompositionLayer\/init(animation:imageProvider:textProvider:fontProvider:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin\/lottiecompositionlayer\/init(animation:imageprovider:textprovider:fontprovider:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"LottieCompositionLayer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"LottieCompositionLayer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"LottieCompositionLayer"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieCompositionLayer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"CALayer","preciseIdentifier":"c:objc(cs)CALayer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieCompositionLayer\/title","value":"LottieCompositionLayer"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieCompositionLayer\/fragments","value":[{"kind":"identifier","text":"LottieCompositionLayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}