{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": (","kind":"text"},{"text":"CGContext","preciseIdentifier":"c:@T@CGContextRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"actions","content":[{"type":"paragraph","inlineContent":[{"text":"A SDGraphicsImageDrawingActions block that, when invoked by the renderer, executes a set of drawing instructions to create the output image.","type":"text"}]}]}]},{"content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"A UIImage object created by the supplied drawing actions.","type":"text"}]}],"kind":"content"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"You should not retain or use the context outside the block, it’s non-escaping."}]}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/image(actions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/image(actions:)"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer"]]},"metadata":{"externalID":"c:objc(cs)SDGraphicsImageRenderer(im)imageWithActions:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"image"},{"text":"(","kind":"text"},{"text":"actions","kind":"externalParam"},{"kind":"text","text":": ("},{"text":"CGContext","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGContextRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"}],"navigatorTitle":[{"text":"imageWithActions:","kind":"identifier"}],"title":"image(actions:)","modules":[{"name":"SDWebImage"}]},"abstract":[{"type":"text","text":"Creates an image by following a set of drawing instructions."}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/image(actions:)","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer/image(actions:)":{"abstract":[{"type":"text","text":"Creates an image by following a set of drawing instructions."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithActions:"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/image(actions:)","type":"topic","title":"image(actions:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/image(actions:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer","role":"symbol","abstract":[{"type":"text","text":"A graphics renderer for creating Core Graphics-backed images."}],"navigatorTitle":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"type":"topic","title":"SDGraphicsImageRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRenderer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"imageWithActions:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"imageWithActions:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"imageWithActions:"},{"kind":"text","text":"("},{"text":"void (^)(struct CGContext *)","preciseIdentifier":"c:BFv(#*$@S@CGContext)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"actions"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"actions","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A SDGraphicsImageDrawingActions block that, when invoked by the renderer, executes a set of drawing instructions to create the output image."}]}]}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"A UIImage object created by the supplied drawing actions."}],"type":"paragraph"}]},"op":"replace"},{"op":"replace","value":"imageWithActions:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1image(actions:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1image(actions:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"imageWithActions:","kind":"identifier"}],"op":"replace"},{"value":"SDGraphicsImageRenderer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/fragments","value":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/navigatorTitle","value":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"op":"replace"}]}]}