{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:)"]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"title":"init(size:)","externalID":"c:objc(cs)SDGraphicsImageRenderer(im)initWithSize:","role":"symbol","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithSize:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Creates an image renderer for drawing images of a given size."}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":")"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The size of images output from the renderer, specified in points."}]}],"name":"size"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer","role":"symbol","abstract":[{"type":"text","text":"A graphics renderer for creating Core Graphics-backed images."}],"navigatorTitle":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"type":"topic","title":"SDGraphicsImageRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRenderer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer/init(size:)":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:)","navigatorTitle":[{"kind":"identifier","text":"initWithSize:"}],"type":"topic","kind":"symbol","title":"init(size:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates an image renderer for drawing images of a given size."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"initWithSize:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSize:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"text":"initWithSize:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"size","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"size","content":[{"inlineContent":[{"text":"The size of images output from the renderer, specified in points.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"add","value":{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"An initialized image renderer.","type":"text"}]}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/title","value":"SDGraphicsImageRenderer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRenderer"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRenderer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:)\/title","op":"replace","value":"initWithSize:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithSize:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}