{"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:format:)"]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:format:)"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Creates a new image renderer with a given size and format."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDGraphicsImageRendererFormat","text":"SDGraphicsImageRendererFormat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"size","content":[{"type":"paragraph","inlineContent":[{"text":"The size of images output from the renderer, specified in points.","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"A SDGraphicsImageRendererFormat object that encapsulates the format used to create the renderer context."}],"type":"paragraph"}],"name":"format"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer"]]},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:format:)","interfaceLanguage":"swift"},"metadata":{"title":"init(size:format:)","symbolKind":"init","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDGraphicsImageRenderer(im)initWithSize:format:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDGraphicsImageRendererFormat","text":"SDGraphicsImageRendererFormat","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol","navigatorTitle":[{"text":"initWithSize:format:","kind":"identifier"}],"roleHeading":"Initializer"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer/init(size:format:)":{"title":"init(size:format:)","abstract":[{"type":"text","text":"Creates a new image renderer with a given size and format."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:format:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithSize:format:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDGraphicsImageRendererFormat","text":"SDGraphicsImageRendererFormat"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:format:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat":{"title":"SDGraphicsImageRendererFormat","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"abstract":[{"text":"A set of drawing attributes that represent the configuration of an image renderer context.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer","role":"symbol","abstract":[{"type":"text","text":"A graphics renderer for creating Core Graphics-backed images."}],"navigatorTitle":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"type":"topic","title":"SDGraphicsImageRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRenderer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithSize:format:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSize:format:"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithSize:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":") "},{"kind":"internalParam","text":"size"},{"kind":"text","text":" "},{"text":"format:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SDGraphicsImageRendererFormat","preciseIdentifier":"c:objc(cs)SDGraphicsImageRendererFormat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"format","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"size","content":[{"type":"paragraph","inlineContent":[{"text":"The size of images output from the renderer, specified in points.","type":"text"}]}]},{"name":"format","content":[{"inlineContent":[{"text":"A SDGraphicsImageRendererFormat object that encapsulates the format used to create the renderer context.","type":"text"}],"type":"paragraph"}]}]},"path":"\/primaryContentSections\/1"},{"op":"add","value":{"kind":"content","content":[{"text":"Return Value","level":2,"anchor":"return-value","type":"heading"},{"inlineContent":[{"text":"An initialized image renderer.","type":"text"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"value":"initWithSize:format:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:format:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:format:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithSize:format:","kind":"identifier"}]},{"value":"SDGraphicsImageRendererFormat","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/title"},{"value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/fragments"},{"value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/navigatorTitle","op":"replace"},{"op":"replace","value":"SDGraphicsImageRenderer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/title"},{"value":[{"kind":"identifier","text":"SDGraphicsImageRenderer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRenderer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/navigatorTitle"}]}]}