{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateIncrementalData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdprogressiveimagecoder\/updateincrementaldata(_:finished:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdprogressiveimagecoder\/updateincrementaldata(_:finished:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder\/updateIncrementalData(_:finished:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Update the incremental decoding when new image data available"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"updateIncrementalData:finished:"}],"role":"symbol","title":"updateIncrementalData(_:finished:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateIncrementalData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)SDProgressiveImageCoder(im)updateIncrementalData:finished:","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"role":"symbol","title":"SDProgressiveImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}],"url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder/updateIncrementalData(_:finished:)":{"navigatorTitle":[{"kind":"identifier","text":"updateIncrementalData:finished:"}],"role":"symbol","title":"updateIncrementalData(_:finished:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateIncrementalData"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"finished"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update the incremental decoding when new image data available"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder\/updateIncrementalData(_:finished:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder\/updateincrementaldata(_:finished:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"updateIncrementalData:finished:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateIncrementalData:finished:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"updateIncrementalData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"finished:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":")"},{"kind":"internalParam","text":"finished"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title","value":"SDProgressiveImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments","value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder~1updateIncrementalData(_:finished:)\/title","value":"updateIncrementalData:finished:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder~1updateIncrementalData(_:finished:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateIncrementalData:finished:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}