{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode"]]},"metadata":{"modules":[{"name":"SDWebImage"}],"roleHeading":"API Collection","title":"Equatable Implementations","role":"collectionGroup"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/Equatable-Implementations","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"article","topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/!=(_:_:)"],"title":"Operators","generated":true,"anchor":"Operators"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode":{"type":"topic","role":"symbol","title":"SDAnimatedImagePlaybackMode","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"abstract":[{"text":"Animated image playback mode","type":"text"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/!=(_:_:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/!=(_:_:)","abstract":[],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/!=(_:_:)","role":"symbol","title":"!=(_:_:)","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/title","op":"replace","value":"SDAnimatedImagePlaybackMode"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/navigatorTitle","value":[{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}