{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode"]]},"metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackModeReverse"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"reverse","kind":"identifier"}],"role":"symbol","externalID":"c:@E@SDAnimatedImagePlaybackMode@SDAnimatedImagePlaybackModeReverse","roleHeading":"Case","title":"SDAnimatedImagePlaybackMode.reverse","symbolKind":"case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverse"}]}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reverse","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/reverse"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/reverse"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"type":"text","text":"From last frame to first frame and stop or next loop."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/reverse":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverse"}],"kind":"symbol","abstract":[{"text":"From last frame to first frame and stop or next loop.","type":"text"}],"title":"SDAnimatedImagePlaybackMode.reverse","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reverse","navigatorTitle":[{"text":"SDAnimatedImagePlaybackModeReverse","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/reverse","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode":{"type":"topic","role":"symbol","title":"SDAnimatedImagePlaybackMode","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"abstract":[{"text":"Animated image playback mode","type":"text"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SDAnimatedImagePlaybackModeReverse","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"text":"SDAnimatedImagePlaybackModeReverse","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SDAnimatedImagePlaybackModeReverse","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1reverse\/title","value":"SDAnimatedImagePlaybackModeReverse","op":"replace"},{"value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackModeReverse"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1reverse\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/title","value":"SDAnimatedImagePlaybackMode"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}]},{"op":"replace","value":[{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/navigatorTitle"}]}]}