{"sections":[],"metadata":{"navigatorTitle":[{"text":"diskCacheReadingOptions","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskCacheReadingOptions","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@NSDataReadingOptions","text":"ReadingOptions","kind":"typeIdentifier"}],"externalID":"c:objc(cs)SDImageCacheConfig(py)diskCacheReadingOptions","title":"diskCacheReadingOptions","modules":[{"name":"SDWebImage"}],"role":"symbol","symbolKind":"property","roleHeading":"Instance Property"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskCacheReadingOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDataReadingOptions","text":"ReadingOptions"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","abstract":[{"type":"text","text":"The reading options while reading cache from disk."},{"type":"text","text":" "},{"text":"Defaults to 0. You can set this to ","type":"text"},{"type":"codeVoice","code":"NSDataReadingMappedIfSafe"},{"text":" to improve performance.","type":"text"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheReadingOptions"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachereadingoptions"]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachereadingoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheReadingOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachereadingoptions","title":"diskCacheReadingOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheReadingOptions","abstract":[{"type":"text","text":"The reading options while reading cache from disk."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 0. You can set this to "},{"code":"NSDataReadingMappedIfSafe","type":"codeVoice"},{"type":"text","text":" to improve performance."}],"navigatorTitle":[{"text":"diskCacheReadingOptions","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"diskCacheReadingOptions","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@NSDataReadingOptions","text":"ReadingOptions","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"diskCacheReadingOptions","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"diskCacheReadingOptions"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@NSDataReadingOptions","text":"NSDataReadingOptions"},{"kind":"text","text":" "},{"text":"diskCacheReadingOptions","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheReadingOptions\/title","value":"diskCacheReadingOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheReadingOptions\/fragments","value":[{"text":"diskCacheReadingOptions","kind":"identifier"}]},{"op":"replace","value":"SDImageCacheConfig","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheConfig"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments"},{"value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}