{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheWritingOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WritingOptions","preciseIdentifier":"c:@E@NSDataWritingOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachewritingoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachewritingoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheWritingOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The writing options while writing cache to disk."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"NSDataWritingAtomic"},{"type":"text","text":". You can set this to "},{"type":"codeVoice","code":"NSDataWritingWithoutOverwriting"},{"type":"text","text":" to prevent overwriting an existing file."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheWritingOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WritingOptions","preciseIdentifier":"c:@E@NSDataWritingOptions"}],"title":"diskCacheWritingOptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCacheConfig(py)diskCacheWritingOptions","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"diskCacheWritingOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheWritingOptions":{"role":"symbol","title":"diskCacheWritingOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheWritingOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WritingOptions","preciseIdentifier":"c:@E@NSDataWritingOptions"}],"abstract":[{"type":"text","text":"The writing options while writing cache to disk."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"NSDataWritingAtomic"},{"type":"text","text":". You can set this to "},{"type":"codeVoice","code":"NSDataWritingWithoutOverwriting"},{"type":"text","text":" to prevent overwriting an existing file."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheWritingOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"diskCacheWritingOptions"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachewritingoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","title":"SDImageCacheConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"diskCacheWritingOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"diskCacheWritingOptions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSDataWritingOptions","preciseIdentifier":"c:@E@NSDataWritingOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheWritingOptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheWritingOptions\/title","value":"diskCacheWritingOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheWritingOptions\/fragments","value":[{"kind":"identifier","text":"diskCacheWritingOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}