{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheExpireType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","preciseIdentifier":"c:@E@SDImageCacheConfigExpireType","text":"SDImageCacheConfigExpireType"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcacheexpiretype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcacheexpiretype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheExpireType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheExpireType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfigExpireType","preciseIdentifier":"c:@E@SDImageCacheConfigExpireType"}],"title":"diskCacheExpireType","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCacheConfig(py)diskCacheExpireType","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"diskCacheExpireType"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType":{"role":"symbol","title":"SDImageCacheConfigExpireType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfigExpireType"}],"abstract":[{"type":"text","text":"Image Cache Expire Type"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","title":"SDImageCacheConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheExpireType":{"role":"symbol","title":"diskCacheExpireType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheExpireType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfigExpireType","preciseIdentifier":"c:@E@SDImageCacheConfigExpireType"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheExpireType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"diskCacheExpireType"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcacheexpiretype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"diskCacheExpireType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"diskCacheExpireType"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","preciseIdentifier":"c:@E@SDImageCacheConfigExpireType","text":"SDImageCacheConfigExpireType"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheExpireType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/title","value":"SDImageCacheConfigExpireType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheExpireType\/title","value":"diskCacheExpireType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheExpireType\/fragments","value":[{"kind":"identifier","text":"diskCacheExpireType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}