{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","role":"symbol","externalID":"c:objc(cs)SDImageCacheConfig(py)ioQueueAttributes","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ioQueueAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"dispatch_queue_attr_t"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"ioQueueAttributes","kind":"identifier"}],"title":"ioQueueAttributes","symbolKind":"property"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/ioqueueattributes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/ioqueueattributes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"abstract":[{"text":"The dispatch queue attr for ioQueue. You can config the QoS and concurrent\/serial to internal IO queue. The ioQueue is used by SDImageCache to access read\/write for disk data.","type":"text"},{"type":"text","text":" "},{"text":"Defaults we use ","type":"text"},{"type":"codeVoice","code":"DISPATCH_QUEUE_SERIAL"},{"type":"text","text":"(NULL) under iOS 10, "},{"type":"codeVoice","code":"DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL"},{"text":" above and equal iOS 10, using serial dispatch queue is to ensure single access for disk data. It’s safe but may be slow.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/ioQueueAttributes"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"ioQueueAttributes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"dispatch_queue_attr_t","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"You can override this to use "},{"code":"DISPATCH_QUEUE_CONCURRENT","type":"codeVoice"},{"text":", use concurrent queue.","type":"text"}],"type":"paragraph"}]}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/ioQueueAttributes":{"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/ioqueueattributes","abstract":[{"type":"text","text":"The dispatch queue attr for ioQueue. You can config the QoS and concurrent\/serial to internal IO queue. The ioQueue is used by SDImageCache to access read\/write for disk data."},{"type":"text","text":" "},{"type":"text","text":"Defaults we use "},{"code":"DISPATCH_QUEUE_SERIAL","type":"codeVoice"},{"type":"text","text":"(NULL) under iOS 10, "},{"type":"codeVoice","code":"DISPATCH_QUEUE_SERIAL_WITH_AUTORELEASE_POOL"},{"text":" above and equal iOS 10, using serial dispatch queue is to ensure single access for disk data. It’s safe but may be slow.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/ioQueueAttributes","navigatorTitle":[{"text":"ioQueueAttributes","kind":"identifier"}],"title":"ioQueueAttributes","type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ioQueueAttributes","kind":"identifier"},{"kind":"text","text":": "},{"text":"dispatch_queue_attr_t","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"ioQueueAttributes","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"ioQueueAttributes"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSObject<OS_dispatch_queue_attr>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue_attr","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"ioQueueAttributes"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"ioQueueAttributes","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1ioQueueAttributes\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1ioQueueAttributes\/fragments","value":[{"kind":"identifier","text":"ioQueueAttributes"}]},{"op":"replace","value":"SDImageCacheConfig","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title"},{"value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle","value":[{"text":"SDImageCacheConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}