{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Defaults to 0. Which means there is no memory cost limit."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycost"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycost"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCost","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The maximum “total cost” of the in-memory image cache. The cost function is the bytes size held in memory."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"maxMemoryCost","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCacheConfig(py)maxMemoryCost","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"maxMemoryCost"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","title":"SDImageCacheConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/maxMemoryCost":{"role":"symbol","title":"maxMemoryCost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum “total cost” of the in-memory image cache. The cost function is the bytes size held in memory."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxMemoryCost"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycost"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxMemoryCost"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxMemoryCost"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCost"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCost\/title","value":"maxMemoryCost"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCost\/fragments","value":[{"kind":"identifier","text":"maxMemoryCost"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}