{"sections":[],"abstract":[{"type":"text","text":"The maximum number of objects in-memory image cache should hold."},{"text":" ","type":"text"},{"text":"Defaults to 0. Which means there is no memory count limit.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxMemoryCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycount"]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycount"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCount","interfaceLanguage":"swift"},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCount"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","symbolKind":"property","title":"maxMemoryCount","externalID":"c:objc(cs)SDImageCacheConfig(py)maxMemoryCount","navigatorTitle":[{"text":"maxMemoryCount","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/maxMemoryCount":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxMemoryCount"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCount","url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycount","abstract":[{"type":"text","text":"The maximum number of objects in-memory image cache should hold."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 0. Which means there is no memory count limit."}],"title":"maxMemoryCount","kind":"symbol","navigatorTitle":[{"text":"maxMemoryCount","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"maxMemoryCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"maxMemoryCount","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxMemoryCount"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCount\/title","value":"maxMemoryCount","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCount\/fragments","value":[{"text":"maxMemoryCount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig","op":"replace"},{"value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle","value":[{"text":"SDImageCacheConfig","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}