{"metadata":{"title":"memoryCacheClass","modules":[{"name":"SDWebImage"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryCacheClass"},{"text":": ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)SDImageCacheConfig(py)memoryCacheClass","navigatorTitle":[{"kind":"identifier","text":"memoryCacheClass"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"memoryCacheClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"This value does not support dynamic changes. Which means further modification on this value after cache initialized has no effect."}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/memorycacheclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/memorycacheclass"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/memoryCacheClass","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"type":"text","text":"The custom memory cache class. Provided class instance must conform to "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" protocol to allow usage."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to built-in "},{"code":"SDMemoryCache","type":"codeVoice"},{"type":"text","text":" class."}],"kind":"symbol","sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/memoryCacheClass":{"role":"symbol","kind":"symbol","type":"topic","title":"memoryCacheClass","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/memoryCacheClass","abstract":[{"text":"The custom memory cache class. Provided class instance must conform to ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"text":" protocol to allow usage.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to built-in "},{"code":"SDMemoryCache","type":"codeVoice"},{"text":" class.","type":"text"}],"navigatorTitle":[{"text":"memoryCacheClass","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"memoryCacheClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/memorycacheclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"value":"memoryCacheClass","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"memoryCacheClass","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"kind":"text","text":") "},{"text":"Class","kind":"typeIdentifier","preciseIdentifier":"c:*QO"},{"text":" ","kind":"text"},{"kind":"identifier","text":"memoryCacheClass"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1memoryCacheClass\/title","op":"replace","value":"memoryCacheClass"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1memoryCacheClass\/fragments","value":[{"kind":"identifier","text":"memoryCacheClass"}],"op":"replace"},{"op":"replace","value":"SDImageCacheConfig","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle","value":[{"text":"SDImageCacheConfig","kind":"identifier"}]}]}]}