{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/shouldremoveexpireddatawhenenterbackground"]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig\/shouldremoveexpireddatawhenenterbackground"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)SDImageCacheConfig(py)shouldRemoveExpiredDataWhenEnterBackground","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"shouldRemoveExpiredDataWhenEnterBackground","navigatorTitle":[{"kind":"identifier","text":"shouldRemoveExpiredDataWhenEnterBackground"}],"modules":[{"name":"SDWebImage"}]},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenEnterBackground","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether or not to remove the expired disk data when application entering the background. (Not works for macOS)"},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES."}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/shouldRemoveExpiredDataWhenEnterBackground":{"abstract":[{"text":"Whether or not to remove the expired disk data when application entering the background. (Not works for macOS)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to YES."}],"title":"shouldRemoveExpiredDataWhenEnterBackground","navigatorTitle":[{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenEnterBackground","url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/shouldremoveexpireddatawhenenterbackground","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"shouldRemoveExpiredDataWhenEnterBackground","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SDImageCacheConfig","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"text":"SDImageCacheConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDImageCacheConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldRemoveExpiredDataWhenEnterBackground\/title","value":"shouldRemoveExpiredDataWhenEnterBackground","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldRemoveExpiredDataWhenEnterBackground\/fragments","op":"replace","value":[{"text":"shouldRemoveExpiredDataWhenEnterBackground","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}