{"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_SwiftNewtypeWrapper.hash(into:)"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageformat\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/hash(into:)","interfaceLanguage":"swift"},"metadata":{"extendedModule":"Swift","role":"symbol","symbolKind":"method","modules":[{"relatedModules":["Swift"],"name":"SDWebImage"}],"roleHeading":"Instance Method","externalID":"s:s20_SwiftNewtypeWrapperPsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:NSData+ImageContentType.h@T@SDImageFormat","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}]},"title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Hasher","preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/_SwiftNewtypeWrapper-Implementations"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"hasher","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/hash(into:)":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","text":"Hasher","kind":"typeIdentifier"},{"text":")","kind":"text"}],"conformance":{"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"type":"topic","abstract":[],"role":"symbol","title":"hash(into:)","url":"\/documentation\/sdwebimage\/sdimageformat\/hash(into:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/_SwiftNewtypeWrapper-Implementations":{"url":"\/documentation\/sdwebimage\/sdimageformat\/_swiftnewtypewrapper-implementations","type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/_SwiftNewtypeWrapper-Implementations","abstract":[],"title":"_SwiftNewtypeWrapper Implementations"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title","value":"SDImageFormat"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments","value":[{"text":"SDImageFormat","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle","value":[{"text":"SDImageFormat","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}