{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/HEIF","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SDWebImage"}],"title":"HEIF","externalID":"c:NSData+ImageContentType.h@SDImageFormatHEIF","roleHeading":"Type Property","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"HEIF"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat"}],"navigatorTitle":[{"text":"SDImageFormatHEIF","kind":"identifier"}],"extendedModule":"SDWebImage","symbolKind":"property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"HEIF","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageformat\/heif"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageformat\/heif"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/HEIF":{"navigatorTitle":[{"text":"SDImageFormatHEIF","kind":"identifier"}],"title":"HEIF","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/HEIF","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"HEIF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/heif","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SDImageFormatHEIF"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageFormatHEIF"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"SDImageFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageFormatHEIF"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1HEIF\/title","op":"replace","value":"SDImageFormatHEIF"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1HEIF\/fragments","value":[{"kind":"identifier","text":"SDImageFormatHEIF"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title","op":"replace","value":"SDImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments","value":[{"kind":"identifier","text":"SDImageFormat"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageFormat"}],"op":"replace"}]}]}