{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"PDF","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageFormat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","kind":"typeIdentifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/PDF","interfaceLanguage":"swift"},"metadata":{"symbolKind":"property","externalID":"c:NSData+ImageContentType.h@SDImageFormatPDF","extendedModule":"SDWebImage","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"PDF"},{"text":": ","kind":"text"},{"text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","kind":"typeIdentifier"}],"role":"symbol","title":"PDF","roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDImageFormatPDF","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageformat\/pdf"]},{"paths":["\/documentation\/sdwebimage\/sdimageformat\/pdf"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/PDF":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"PDF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/pdf","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"SDImageFormatPDF","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/PDF","title":"PDF"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDImageFormatPDF","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageFormatPDF"}],"path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"kind":"text","text":" "},{"text":"SDImageFormatPDF","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"SDImageFormat","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title"},{"value":[{"text":"SDImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle","value":[{"text":"SDImageFormat","kind":"identifier"}],"op":"replace"},{"value":"SDImageFormatPDF","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1PDF\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1PDF\/fragments","value":[{"text":"SDImageFormatPDF","kind":"identifier"}],"op":"replace"}]}]}