{"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webP","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"}]}]}],"kind":"symbol","metadata":{"externalID":"c:NSData+ImageContentType.h@SDImageFormatWebP","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"webP","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"role":"symbol","navigatorTitle":[{"text":"SDImageFormatWebP","kind":"identifier"}],"title":"webP","roleHeading":"Type Property","symbolKind":"property","extendedModule":"SDWebImage"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageformat\/webp"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageformat\/webp"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/webP"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/webP":{"abstract":[],"title":"webP","navigatorTitle":[{"text":"SDImageFormatWebP","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webP","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/webP","url":"\/documentation\/sdwebimage\/sdimageformat\/webp","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Global Variable","path":"\/metadata\/roleHeading"},{"value":"SDImageFormatWebP","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"value":[{"text":"SDImageFormatWebP","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageFormatWebP"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1webP\/title","value":"SDImageFormatWebP"},{"value":[{"text":"SDImageFormatWebP","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1webP\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title","value":"SDImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments","value":[{"kind":"identifier","text":"SDImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}