{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/changeDate","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType"]]},"sections":[],"metadata":{"roleHeading":"Case","externalID":"c:@E@SDImageCacheConfigExpireType@SDImageCacheConfigExpireTypeChangeDate","symbolKind":"case","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"changeDate","kind":"identifier"}],"title":"SDImageCacheConfigExpireType.changeDate","navigatorTitle":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}],"modules":[{"name":"SDWebImage"}]},"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/changedate"]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/changedate"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeDate","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"When the image cache is created, modified, renamed, file attribute updated (like permission, xattr)  it will update this value","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/changeDate":{"title":"SDImageCacheConfigExpireType.changeDate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/changeDate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeDate","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}],"abstract":[{"text":"When the image cache is created, modified, renamed, file attribute updated (like permission, xattr)  it will update this value","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/changedate","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype","abstract":[{"type":"text","text":"Image Cache Expire Type"}],"kind":"symbol","title":"SDImageCacheConfigExpireType","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SDImageCacheConfigExpireTypeChangeDate","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"value":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1changeDate\/title","value":"SDImageCacheConfigExpireTypeChangeDate","op":"replace"},{"value":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1changeDate\/fragments","op":"replace"},{"value":"SDImageCacheConfigExpireType","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/fragments","op":"replace","value":[{"text":"SDImageCacheConfigExpireType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/navigatorTitle","op":"replace","value":[{"text":"SDImageCacheConfigExpireType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}