{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/modificationDate"},"abstract":[{"type":"text","text":"When the image cache is created or modified it will update this value (Default)"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modificationDate"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/modificationdate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/modificationdate"]}],"metadata":{"roleHeading":"Case","modules":[{"name":"SDWebImage"}],"externalID":"c:@E@SDImageCacheConfigExpireType@SDImageCacheConfigExpireTypeModificationDate","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modificationDate"}],"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireTypeModificationDate"}],"role":"symbol","title":"SDImageCacheConfigExpireType.modificationDate"},"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype","abstract":[{"type":"text","text":"Image Cache Expire Type"}],"kind":"symbol","title":"SDImageCacheConfigExpireType","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/modificationDate":{"title":"SDImageCacheConfigExpireType.modificationDate","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/modificationdate","type":"topic","abstract":[{"text":"When the image cache is created or modified it will update this value (Default)","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/modificationDate","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireTypeModificationDate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modificationDate"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SDImageCacheConfigExpireTypeModificationDate"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SDImageCacheConfigExpireTypeModificationDate"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SDImageCacheConfigExpireTypeModificationDate","kind":"identifier"}],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/title","value":"SDImageCacheConfigExpireType"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/fragments","value":[{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/navigatorTitle"},{"value":"SDImageCacheConfigExpireTypeModificationDate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1modificationDate\/title"},{"value":[{"text":"SDImageCacheConfigExpireTypeModificationDate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1modificationDate\/fragments"}]}]}