{"metadata":{"roleHeading":"API Collection","title":"RawRepresentable Implementations","role":"collectionGroup","modules":[{"name":"SDWebImage"}]},"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/hashValue"],"title":"Instance Properties","generated":true},{"generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/RawRepresentable-Implementations"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType"]]},"kind":"article","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/rawrepresentable-implementations"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/hash(into:)":{"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":".","type":"text"}]},"role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/hash(into:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/hash(into:)","kind":"symbol","abstract":[],"title":"hash(into:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"text":"Hasher","kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype","abstract":[{"type":"text","text":"Image Cache Expire Type"}],"kind":"symbol","title":"SDImageCacheConfigExpireType","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/hashValue":{"title":"hashValue","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/hashValue","abstract":[],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/hashvalue","role":"symbol","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]}},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/title","value":"SDImageCacheConfigExpireType","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/navigatorTitle"}]}]}