{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shouldblockfailedurl:witherror:)"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shouldblockfailedurl:witherror:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldBlockFailedURL:withError:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"role":"symbol","platforms":[{"introducedAt":"8.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false},{"deprecated":false,"beta":false,"introducedAt":"8.0","unavailable":false,"name":"iPadOS"},{"beta":false,"name":"Mac Catalyst","introducedAt":"8.0","unavailable":false,"deprecated":false}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"imageManager:shouldBlockFailedURL:withError:","kind":"identifier"}],"title":"imageManager(_:shouldBlockFailedURL:withError:)","externalID":"c:objc(pl)SDWebImageManagerDelegate(im)imageManager:shouldBlockFailedURL:withError:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageManager","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager"},{"text":", ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"withError","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"required":true},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate"]]},"abstract":[{"text":"Controls the complicated logic to mark as failed URLs when download error occur.","type":"text"},{"type":"text","text":" "},{"text":"If the delegate implement this method, we will not use the built-in way to mark URL as failed based on error code;","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageManager"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"imageManager","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": any "},{"preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier","text":"Error"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"text":"The current ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"}],"type":"paragraph"}],"name":"imageManager"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the image"}]}],"name":"imageURL"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The download error for the url"}]}],"name":"error"}],"kind":"parameters"},{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to block this url or not. Return YES to mark this URL as failed."}]}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate/imageManager(_:shouldBlockFailedURL:withError:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldBlockFailedURL:withError:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shouldblockfailedurl:witherror:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SDWebImageManager","text":"SDWebImageManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"text":"Controls the complicated logic to mark as failed URLs when download error occur.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the delegate implement this method, we will not use the built-in way to mark URL as failed based on error code;"}],"kind":"symbol","title":"imageManager(_:shouldBlockFailedURL:withError:)","navigatorTitle":[{"kind":"identifier","text":"imageManager:shouldBlockFailedURL:withError:"}],"required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate","navigatorTitle":[{"text":"SDWebImageManagerDelegate","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate","abstract":[{"type":"text","text":"The manager delegate protocol."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"role":"symbol","title":"SDWebImageManagerDelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","url":"\/documentation\/sdwebimage\/sdwebimagemanager","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","navigatorTitle":[{"text":"SDWebImageManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"text":" ","type":"text"},{"text":"You can use this class directly to benefit from web image downloading with caching in another context than","type":"text"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","value":"imageManager:shouldBlockFailedURL:withError:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"imageManager:shouldBlockFailedURL:withError:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":") "},{"text":"imageManager:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImageManager","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"imageManager","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"shouldBlockFailedURL:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":" "},{"kind":"identifier","text":"withError:"},{"kind":"text","text":"("},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"error"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"imageManager","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current "},{"type":"codeVoice","code":"SDWebImageManager"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url of the image"}]}],"name":"imageURL"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The download error for the url"}]}]}]},"op":"replace"},{"value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether to block this url or not. Return YES to mark this URL as failed."}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"imageManager:shouldBlockFailedURL:withError:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldBlockFailedURL:withError:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldBlockFailedURL:withError:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"imageManager:shouldBlockFailedURL:withError:","kind":"identifier"}]},{"op":"replace","value":"SDWebImageManagerDelegate","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/title"},{"value":[{"text":"SDWebImageManagerDelegate","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/navigatorTitle","op":"replace"},{"value":"SDWebImageManager","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"text":"SDWebImageManager","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageManager"}]}]}]}