{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageManager"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager","text":"SDWebImageManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDownloadImageFor"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shoulddownloadimagefor:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shoulddownloadimagefor:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldDownloadImageFor:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Controls which image should be downloaded when the image is not found in the cache."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDownloadImageFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"imageManager(_:shouldDownloadImageFor:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(pl)SDWebImageManagerDelegate(im)imageManager:shouldDownloadImageForURL:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"imageManager:shouldDownloadImageForURL:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate":{"role":"symbol","title":"SDWebImageManagerDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"abstract":[{"type":"text","text":"The manager delegate protocol."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate/imageManager(_:shouldDownloadImageFor:)":{"role":"symbol","title":"imageManager(_:shouldDownloadImageFor:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageManager"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldDownloadImageFor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Controls which image should be downloaded when the image is not found in the cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldDownloadImageFor:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageManager:shouldDownloadImageForURL:"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shoulddownloadimagefor:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManager"}],"abstract":[{"type":"text","text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes."},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"type":"text","text":" "},{"type":"text","text":"You can use this class directly to benefit from web image downloading with caching in another context than"},{"type":"text","text":" "},{"type":"text","text":"a UIView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageManager"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"imageManager:shouldDownloadImageForURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageManager:shouldDownloadImageForURL:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"imageManager:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager","text":"SDWebImageManager"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageManager"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldDownloadImageForURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/title","value":"SDWebImageManagerDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/fragments","value":[{"kind":"identifier","text":"SDWebImageManagerDelegate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldDownloadImageFor:)\/title","value":"imageManager:shouldDownloadImageForURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldDownloadImageFor:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageManager:shouldDownloadImageForURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}