{"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/continueInBackground"},"kind":"symbol","metadata":{"externalID":"c:@E@SDWebImageDownloaderOptions@SDWebImageDownloaderContinueInBackground","title":"continueInBackground","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueInBackground"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"symbolKind":"property","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"SDWebImageDownloaderContinueInBackground","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/continueinbackground"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/continueinbackground"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"continueInBackground"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"]]},"abstract":[{"type":"text","text":"In iOS 4+, continue the download of the image if the app goes to background. This is achieved by asking the system for"},{"type":"text","text":" "},{"text":"extra time in background to let the request finish. If the background task expires the operation will be cancelled.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/continueInBackground":{"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueInBackground","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"abstract":[{"text":"In iOS 4+, continue the download of the image if the app goes to background. This is achieved by asking the system for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"extra time in background to let the request finish. If the background task expires the operation will be cancelled."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderContinueInBackground","kind":"identifier"}],"title":"continueInBackground","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/continueInBackground","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/continueinbackground"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageDownloaderContinueInBackground"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDWebImageDownloaderContinueInBackground","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDWebImageDownloaderContinueInBackground"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1continueInBackground\/title","value":"SDWebImageDownloaderContinueInBackground","op":"replace"},{"value":[{"text":"SDWebImageDownloaderContinueInBackground","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1continueInBackground\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","value":"SDWebImageDownloaderOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"op":"replace"}]}]}