{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreCachedResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/ignorecachedresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/ignorecachedresponse"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/ignoreCachedResponse","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Call completion block with nil image\/imageData if the image was read from NSURLCache"},{"type":"text","text":" "},{"type":"text","text":"And the error code is "},{"type":"codeVoice","code":"SDWebImageErrorCacheNotModified"},{"type":"text","text":" "},{"type":"text","text":"This flag should be combined with "},{"type":"codeVoice","code":"SDWebImageDownloaderUseNSURLCache"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreCachedResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"title":"ignoreCachedResponse","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@SDWebImageDownloaderOptions@SDWebImageDownloaderIgnoreCachedResponse","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderIgnoreCachedResponse"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"abstract":[{"type":"text","text":"Downloader options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/ignoreCachedResponse":{"role":"symbol","title":"ignoreCachedResponse","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ignoreCachedResponse"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"abstract":[{"type":"text","text":"Call completion block with nil image\/imageData if the image was read from NSURLCache"},{"type":"text","text":" "},{"type":"text","text":"And the error code is "},{"type":"codeVoice","code":"SDWebImageErrorCacheNotModified"},{"type":"text","text":" "},{"type":"text","text":"This flag should be combined with "},{"type":"codeVoice","code":"SDWebImageDownloaderUseNSURLCache"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/ignoreCachedResponse","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderIgnoreCachedResponse"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/ignorecachedresponse"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderIgnoreCachedResponse"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderIgnoreCachedResponse"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImageDownloaderIgnoreCachedResponse"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","value":"SDWebImageDownloaderOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1ignoreCachedResponse\/title","value":"SDWebImageDownloaderIgnoreCachedResponse"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1ignoreCachedResponse\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderIgnoreCachedResponse"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}