{"sections":[],"abstract":[{"type":"text","text":"Inherited from "},{"code":"SetAlgebra.isEmpty","type":"codeVoice"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"extendedModule":"Swift","modules":[{"name":"SDWebImage","relatedModules":["Swift"]}],"title":"isEmpty","externalID":"s:s10SetAlgebraPsE7isEmptySbvp::SYNTHESIZED::c:@E@SDWebImageDownloaderOptions","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isEmpty"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/isempty"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/isEmpty","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/SetAlgebra-Implementations"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/SetAlgebra-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/setalgebra-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/SetAlgebra-Implementations","kind":"article","role":"collectionGroup","title":"SetAlgebra Implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/isEmpty":{"role":"symbol","abstract":[],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/isempty","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/isEmpty","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"isEmpty","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"type":"topic","title":"isEmpty"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SDWebImageDownloaderOptions","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}