{"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"matchAnimatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/matchAnimatedImageClass"},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"matchAnimatedImageClass","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","kind":"typeIdentifier"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDWebImageDownloaderMatchAnimatedImageClass","kind":"identifier"}],"roleHeading":"Type Property","symbolKind":"property","title":"matchAnimatedImageClass","role":"symbol","externalID":"c:@E@SDWebImageDownloaderOptions@SDWebImageDownloaderMatchAnimatedImageClass"},"abstract":[{"text":"By default, when you use ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"text":" context option (like using ","type":"text"},{"code":"SDAnimatedImageView","type":"codeVoice"},{"type":"text","text":" which designed to use "},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":"), we may still use ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" when the memory cache hit, or image decoder is not available, to behave as a fallback solution."},{"text":" ","type":"text"},{"type":"text","text":"Using this option, can ensure we always produce image with your provided class. If failed, a error with code "},{"code":"SDWebImageErrorBadImageData","type":"codeVoice"},{"type":"text","text":" will been used."},{"text":" ","type":"text"},{"text":"Note this options is not compatible with ","type":"text"},{"code":"SDWebImageDownloaderDecodeFirstFrameOnly","type":"codeVoice"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/matchanimatedimageclass"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/matchanimatedimageclass"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/matchAnimatedImageClass":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/matchAnimatedImageClass","type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/matchanimatedimageclass","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderMatchAnimatedImageClass"}],"abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"text":" context option (like using ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":"), we may still use ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":" when the memory cache hit, or image decoder is not available, to behave as a fallback solution.","type":"text"},{"type":"text","text":" "},{"text":"Using this option, can ensure we always produce image with your provided class. If failed, a error with code ","type":"text"},{"type":"codeVoice","code":"SDWebImageErrorBadImageData"},{"text":" will been used.","type":"text"},{"text":" ","type":"text"},{"text":"Note this options is not compatible with ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderDecodeFirstFrameOnly"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"title":"matchAnimatedImageClass","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchAnimatedImageClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDWebImageDownloaderMatchAnimatedImageClass","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderMatchAnimatedImageClass"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SDWebImageDownloaderMatchAnimatedImageClass","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"SDWebImageDownloaderMatchAnimatedImageClass","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1matchAnimatedImageClass\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1matchAnimatedImageClass\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderMatchAnimatedImageClass","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","value":"SDWebImageDownloaderOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},{"value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle"}]}]}