{"kind":"symbol","abstract":[{"text":"By default, for ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":", we decode the animated image frame during rendering to reduce memory usage. This flag actually trigger ","type":"text"},{"type":"codeVoice","code":"preloadAllAnimatedImageFrames = YES"},{"text":" after image load from network","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"preloadAllFrames","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/preloadallframes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/preloadallframes"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/preloadAllFrames"},"metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}],"role":"symbol","title":"preloadAllFrames","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preloadAllFrames","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}],"symbolKind":"property","externalID":"c:@E@SDWebImageDownloaderOptions@SDWebImageDownloaderPreloadAllFrames"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/preloadAllFrames":{"role":"symbol","title":"preloadAllFrames","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preloadAllFrames","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/preloadAllFrames","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/preloadallframes","navigatorTitle":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}],"abstract":[{"text":"By default, for ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":", we decode the animated image frame during rendering to reduce memory usage. This flag actually trigger "},{"type":"codeVoice","code":"preloadAllAnimatedImageFrames = YES"},{"type":"text","text":" after image load from network"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderPreloadAllFrames"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}],"platforms":["iOS"]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","value":"SDWebImageDownloaderOptions","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1preloadAllFrames\/title","value":"SDWebImageDownloaderPreloadAllFrames","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1preloadAllFrames\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}