{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/scaleDownLargeImages"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"text":"By default, images are decoded respecting their original size. On iOS, this flag will scale down the","type":"text"},{"type":"text","text":" "},{"type":"text","text":"images to a size compatible with the constrained memory of devices."},{"type":"text","text":" "},{"text":"This flag take no effect if ","type":"text"},{"code":"SDWebImageDownloaderAvoidDecodeImage","type":"codeVoice"},{"text":" is set. And it will be ignored if ","type":"text"},{"code":"SDWebImageDownloaderProgressiveLoad","type":"codeVoice"},{"text":" is set.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Type Property","role":"symbol","title":"scaleDownLargeImages","externalID":"c:@E@SDWebImageDownloaderOptions@SDWebImageDownloaderScaleDownLargeImages","symbolKind":"property","navigatorTitle":[{"text":"SDWebImageDownloaderScaleDownLargeImages","kind":"identifier"}]},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/scaledownlargeimages"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/scaledownlargeimages"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/scaleDownLargeImages":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/scaleDownLargeImages","navigatorTitle":[{"text":"SDWebImageDownloaderScaleDownLargeImages","kind":"identifier"}],"title":"scaleDownLargeImages","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/scaledownlargeimages","abstract":[{"type":"text","text":"By default, images are decoded respecting their original size. On iOS, this flag will scale down the"},{"type":"text","text":" "},{"type":"text","text":"images to a size compatible with the constrained memory of devices."},{"text":" ","type":"text"},{"text":"This flag take no effect if ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderAvoidDecodeImage"},{"type":"text","text":" is set. And it will be ignored if "},{"code":"SDWebImageDownloaderProgressiveLoad","type":"codeVoice"},{"type":"text","text":" is set."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaleDownLargeImages"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageDownloaderScaleDownLargeImages"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageDownloaderScaleDownLargeImages","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImageDownloaderScaleDownLargeImages"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SDWebImageDownloaderScaleDownLargeImages","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1scaleDownLargeImages\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1scaleDownLargeImages\/fragments","value":[{"text":"SDWebImageDownloaderScaleDownLargeImages","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","value":"SDWebImageDownloaderOptions"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}