{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animatedImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"frames","kind":"internalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SDImageFrame","preciseIdentifier":"c:objc(cs)SDImageFrame","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"frames","content":[{"type":"paragraph","inlineContent":[{"text":"The frames array. If no frames or frames is empty, return nil","type":"text"}]}]}],"kind":"parameters"},{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A animated image for rendering on UIImageView(UIKit) or NSImageView(AppKit)"}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"abstract":[{"text":"Return an animated image with frames array.","type":"text"},{"type":"text","text":" "},{"text":"For UIKit, this will apply the patch and then create animated UIImage. The patch is because that ","type":"text"},{"code":"+[UIImage animatedImageWithImages:duration:]","type":"codeVoice"},{"text":" just use the average of duration for each image. So it will not work if different frame has different duration. Therefore we repeat the specify frame for specify times to let it work.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit, NSImage does not support animates other than GIF. This will try to encode the frames to GIF format and then create an animated NSImage for rendering. Attention the animated image may loss some detail if the input frames contain full alpha channel because GIF only supports 1 bit alpha channel. (For 1 pixel, either transparent or not)","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/animatedImage(with:)"},"metadata":{"symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)animatedImageWithFrames:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatedImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageFrame","text":"SDImageFrame","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"role":"symbol","title":"animatedImage(with:)","roleHeading":"Type Method","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"animatedImageWithFrames:"}]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/animatedimage(with:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/animatedimage(with:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame","title":"SDImageFrame","navigatorTitle":[{"text":"SDImageFrame","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageFrame","kind":"identifier"}],"abstract":[{"text":"This class is used for creating animated images via ","type":"text"},{"code":"animatedImageWithFrames","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"SDImageCoderHelper","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdimageframe","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/animatedImage(with:)":{"role":"symbol","abstract":[{"text":"Return an animated image with frames array.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For UIKit, this will apply the patch and then create animated UIImage. The patch is because that "},{"type":"codeVoice","code":"+[UIImage animatedImageWithImages:duration:]"},{"type":"text","text":" just use the average of duration for each image. So it will not work if different frame has different duration. Therefore we repeat the specify frame for specify times to let it work."},{"type":"text","text":" "},{"type":"text","text":"For AppKit, NSImage does not support animates other than GIF. This will try to encode the frames to GIF format and then create an animated NSImage for rendering. Attention the animated image may loss some detail if the input frames contain full alpha channel because GIF only supports 1 bit alpha channel. (For 1 pixel, either transparent or not)"}],"type":"topic","navigatorTitle":[{"text":"animatedImageWithFrames:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/animatedimage(with:)","kind":"symbol","title":"animatedImage(with:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/animatedImage(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animatedImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageFrame","text":"SDImageFrame","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"animatedImageWithFrames:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"animatedImageWithFrames:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"animatedImageWithFrames:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SDImageFrame *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"frames"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"frames","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The frames array. If no frames or frames is empty, return nil"}]}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":{"content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"A animated image for rendering on UIImageView(UIKit) or NSImageView(AppKit)"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/title","value":"SDImageFrame","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/fragments","value":[{"text":"SDImageFrame","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/navigatorTitle","value":[{"text":"SDImageFrame","kind":"identifier"}]},{"value":"animatedImageWithFrames:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1animatedImage(with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1animatedImage(with:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"animatedImageWithFrames:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","value":"SDImageCoderHelper","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","op":"replace","value":[{"text":"SDImageCoderHelper","kind":"identifier"}]}]}]}