{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"method","roleHeading":"Type Method","title":"cgImageCreateDecoded(_:)","externalID":"c:objc(cs)SDImageCoderHelper(cm)CGImageCreateDecoded:","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageCreateDecoded"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"CGImageCreateDecoded:","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatedecoded(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatedecoded(_:)"]}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cgImageCreateDecoded","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cgImage","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"text":") -> ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":"?"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"cgImage","content":[{"inlineContent":[{"type":"text","text":"The CGImage"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A new created decoded image","type":"text"}],"type":"paragraph"}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This actually call "},{"type":"codeVoice","code":"CGImageCreateDecoded:orientation:"},{"text":" with the Up orientation.","type":"text"}]}]}],"kind":"content"}],"abstract":[{"text":"Create a decoded CGImage by the provided CGImage. This follows The Create Rule and you are response to call release after usage.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"It will detect whether image contains alpha channel, then create a new bitmap context with the same size of image, and draw it. This can ensure that the image do not need extra decoding after been set to the imageView."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageCreateDecoded(_:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:)","kind":"symbol","navigatorTitle":[{"text":"CGImageCreateDecoded:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatedecoded(_:)","abstract":[{"text":"Create a decoded CGImage by the provided CGImage. This follows The Create Rule and you are response to call release after usage.","type":"text"},{"type":"text","text":" "},{"text":"It will detect whether image contains alpha channel, then create a new bitmap context with the same size of image, and draw it. This can ensure that the image do not need extra decoding after been set to the imageView.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgImageCreateDecoded","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"cgImageCreateDecoded(_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"CGImageCreateDecoded:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"text":"CGImageCreateDecoded:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"+ ("},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"text":" *) ","kind":"text"},{"text":"CGImageCreateDecoded:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:@S@CGImage","kind":"typeIdentifier","text":"CGImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The CGImage","type":"text"}]}],"name":"cgImage"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"A new created decoded image","type":"text"}],"type":"paragraph"}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","op":"replace","value":"SDImageCoderHelper"},{"value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","value":[{"text":"SDImageCoderHelper","kind":"identifier"}]},{"op":"replace","value":"CGImageCreateDecoded:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateDecoded(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateDecoded(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"CGImageCreateDecoded:","kind":"identifier"}]}]}]}