{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageContainsAlpha"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecontainsalpha(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecontainsalpha(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageContainsAlpha(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check whether CGImage contains alpha channel."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageContainsAlpha"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"cgImageContainsAlpha(_:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)CGImageContainsAlpha:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageContainsAlpha:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","title":"SDImageCoderHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderHelper"}],"abstract":[{"type":"text","text":"Provide some common helper methods for building the image decoder\/encoder."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageContainsAlpha(_:)":{"role":"symbol","title":"cgImageContainsAlpha(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageContainsAlpha"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Check whether CGImage contains alpha channel."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageContainsAlpha(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGImageContainsAlpha:"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecontainsalpha(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"CGImageContainsAlpha:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"CGImageContainsAlpha:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"CGImageContainsAlpha:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","value":"SDImageCoderHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageContainsAlpha(_:)\/title","value":"CGImageContainsAlpha:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageContainsAlpha(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"CGImageContainsAlpha:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}