{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageCreateScaled"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatescaled(_:size:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatescaled(_:size:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateScaled(_:size:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create a scaled CGImage by the provided CGImage and size. This follows The Create Rule and you are response to call release after usage."},{"type":"text","text":" "},{"type":"text","text":"It will detect whether the image size matching the scale size, if not, stretch the image to the target size."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageCreateScaled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":"?"}],"title":"cgImageCreateScaled(_:size:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)CGImageCreateScaled:size:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageCreateScaled:size:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageCreateScaled(_:size:)":{"role":"symbol","title":"cgImageCreateScaled(_:size:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageCreateScaled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":", "},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Create a scaled CGImage by the provided CGImage and size. This follows The Create Rule and you are response to call release after usage."},{"type":"text","text":" "},{"type":"text","text":"It will detect whether the image size matching the scale size, if not, stretch the image to the target size."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateScaled(_:size:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"CGImageCreateScaled:size:"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatescaled(_:size:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","title":"SDImageCoderHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderHelper"}],"abstract":[{"type":"text","text":"Provide some common helper methods for building the image decoder\/encoder."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"CGImageCreateScaled:size:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"CGImageCreateScaled:size:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"CGImageCreateScaled:"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@S@CGImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cgImage"},{"kind":"text","text":" "},{"kind":"identifier","text":"size:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":")"},{"kind":"internalParam","text":"size"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateScaled(_:size:)\/title","value":"CGImageCreateScaled:size:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateScaled(_:size:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"CGImageCreateScaled:size:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","value":"SDImageCoderHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}