{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cgImageIsHardwareSupported","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"cgImage","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]}]}],"abstract":[{"text":"Check whether CGImage is hardware supported to rendering on screen, without the trigger of ","type":"text"},{"type":"codeVoice","code":"CA::Render::copy_image"},{"text":" ","type":"text"},{"text":"You can debug the copied image by using Xcode’s ","type":"text"},{"code":"Color Copied Image","type":"codeVoice"},{"type":"text","text":", the copied image will turn Cyan and occupy double RAM for bitmap buffer."},{"type":"text","text":" "},{"type":"text","text":"Typically, when the CGImage’s using the method above ("},{"type":"codeVoice","code":"colorspace"},{"type":"text","text":" \/ "},{"type":"codeVoice","code":"alignment"},{"text":" \/ ","type":"text"},{"type":"codeVoice","code":"bitmapInfo"},{"text":") can render withtout the copy.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishardwaresupported(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishardwaresupported(_:)"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cgImageIsHardwareSupported","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:objc(cs)SDImageCoderHelper(cm)CGImageIsHardwareSupported:","symbolKind":"method","modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Type Method","title":"cgImageIsHardwareSupported(_:)","navigatorTitle":[{"text":"CGImageIsHardwareSupported:","kind":"identifier"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHardwareSupported(_:)","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageIsHardwareSupported(_:)":{"navigatorTitle":[{"kind":"identifier","text":"CGImageIsHardwareSupported:"}],"role":"symbol","title":"cgImageIsHardwareSupported(_:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHardwareSupported(_:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishardwaresupported(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cgImageIsHardwareSupported","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Check whether CGImage is hardware supported to rendering on screen, without the trigger of ","type":"text"},{"type":"codeVoice","code":"CA::Render::copy_image"},{"type":"text","text":" "},{"type":"text","text":"You can debug the copied image by using Xcode’s "},{"code":"Color Copied Image","type":"codeVoice"},{"text":", the copied image will turn Cyan and occupy double RAM for bitmap buffer.","type":"text"},{"type":"text","text":" "},{"text":"Typically, when the CGImage’s using the method above (","type":"text"},{"type":"codeVoice","code":"colorspace"},{"text":" \/ ","type":"text"},{"type":"codeVoice","code":"alignment"},{"type":"text","text":" \/ "},{"code":"bitmapInfo","type":"codeVoice"},{"type":"text","text":") can render withtout the copy."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"CGImageIsHardwareSupported:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"CGImageIsHardwareSupported:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"CGImageIsHardwareSupported:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage","text":"CGImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cgImage"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","value":"CGImageIsHardwareSupported:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHardwareSupported(_:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHardwareSupported(_:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"CGImageIsHardwareSupported:"}]},{"op":"replace","value":"SDImageCoderHelper","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]}]}]}