{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHDR(_:)","interfaceLanguage":"swift"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishdr(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishdr(_:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"metadata":{"externalID":"c:objc(cs)SDImageCoderHelper(cm)CGImageIsHDR:","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Method","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageIsHDR"},{"kind":"text","text":"("},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"role":"symbol","title":"cgImageIsHDR(_:)","symbolKind":"method","navigatorTitle":[{"text":"CGImageIsHDR:","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgImageIsHDR","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cgImage","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"This use the same implementation like Apple, to checkl if color space uses transfer functions defined in ITU Rec.2100","type":"text"}]}],"style":"note"}],"kind":"content"}],"abstract":[{"text":"Check if the CGImage is using HDR color space.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageIsHDR(_:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHDR(_:)","role":"symbol","navigatorTitle":[{"text":"CGImageIsHDR:","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishdr(_:)","abstract":[{"type":"text","text":"Check if the CGImage is using HDR color space."}],"title":"cgImageIsHDR(_:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgImageIsHDR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"CGImageIsHDR:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"CGImageIsHDR:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"CGImageIsHDR:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"cgImage"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"CGImageIsHDR:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHDR(_:)\/title"},{"value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"CGImageIsHDR:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHDR(_:)\/fragments"},{"value":"SDImageCoderHelper","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}