{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cgImageIsLazy"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"cgImage","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageislazy(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageislazy(_:)"]}],"abstract":[{"text":"Detect whether the CGImage is lazy and not-yet decoded. (lazy means, only when the caller access the underlying bitmap buffer via provider like ","type":"text"},{"type":"codeVoice","code":"CGDataProviderCopyData"},{"type":"text","text":" or "},{"code":"CGDataProviderRetainBytePtr","type":"codeVoice"},{"type":"text","text":", the decoder will allocate memory, it’s a lazy allocation)"},{"text":" ","type":"text"},{"type":"text","text":"The implementation use the Core Graphics internal to check whether the CGImage is "},{"type":"codeVoice","code":"CGImageProvider"},{"text":" based, or ","type":"text"},{"type":"codeVoice","code":"CGDataProvider"},{"type":"text","text":" based. The "},{"type":"codeVoice","code":"CGDataProvider"},{"text":" based is treated as non-lazy.","type":"text"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsLazy(_:)","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageIsLazy"},{"kind":"text","text":"("},{"text":"CGImage","preciseIdentifier":"c:@T@CGImageRef","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"roleHeading":"Type Method","modules":[{"name":"SDWebImage"}],"role":"symbol","navigatorTitle":[{"text":"CGImageIsLazy:","kind":"identifier"}],"symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)CGImageIsLazy:","title":"cgImageIsLazy(_:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageIsLazy(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageIsLazy"},{"text":"(","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageislazy(_:)","type":"topic","navigatorTitle":[{"text":"CGImageIsLazy:","kind":"identifier"}],"role":"symbol","title":"cgImageIsLazy(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsLazy(_:)","abstract":[{"type":"text","text":"Detect whether the CGImage is lazy and not-yet decoded. (lazy means, only when the caller access the underlying bitmap buffer via provider like "},{"type":"codeVoice","code":"CGDataProviderCopyData"},{"type":"text","text":" or "},{"code":"CGDataProviderRetainBytePtr","type":"codeVoice"},{"text":", the decoder will allocate memory, it’s a lazy allocation)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The implementation use the Core Graphics internal to check whether the CGImage is "},{"type":"codeVoice","code":"CGImageProvider"},{"type":"text","text":" based, or "},{"type":"codeVoice","code":"CGDataProvider"},{"type":"text","text":" based. The "},{"code":"CGDataProvider","type":"codeVoice"},{"text":" based is treated as non-lazy.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Type Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"CGImageIsLazy:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"CGImageIsLazy:"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier","text":"BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"CGImageIsLazy:"},{"text":"(","kind":"text"},{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGImage","text":"CGImage"},{"kind":"text","text":" *) "},{"text":"cgImage","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SDImageCoderHelper","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCoderHelper"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle"},{"op":"replace","value":"CGImageIsLazy:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsLazy(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsLazy(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"CGImageIsLazy:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}