{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorSpaceGetDeviceRGB"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGColorSpace","preciseIdentifier":"c:@T@CGColorSpaceRef"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Return the shared device-dependent RGB color space. This follows The Get Rule."},{"type":"text","text":" "},{"type":"text","text":"Because it’s shared, you should not retain or release this object."},{"type":"text","text":" "},{"type":"text","text":"Typically is sRGB for iOS, screen color space (like Color LCD) for macOS."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/colorspacegetdevicergb()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/colorspacegetdevicergb()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/colorSpaceGetDeviceRGB()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For coders who use "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":", use the information below to create an effient CGImage which can be render on GPU without Core Animation’s extra copy ("},{"type":"codeVoice","code":"CA::Render::copy_image"},{"type":"text","text":"), which can be debugged using "},{"type":"codeVoice","code":"Color Copied Image"},{"type":"text","text":" in Xcode Instruments"},{"type":"text","text":" "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"bytesPerRow"},{"type":"text","text":", "},{"type":"codeVoice","code":"space"},{"type":"text","text":", "},{"type":"codeVoice","code":"bitmapInfo"},{"type":"text","text":" params should use the information below."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorSpaceGetDeviceRGB"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGColorSpace","preciseIdentifier":"c:@T@CGColorSpaceRef"}],"title":"colorSpaceGetDeviceRGB()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)colorSpaceGetDeviceRGB","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"colorSpaceGetDeviceRGB"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/colorSpaceGetDeviceRGB()":{"role":"symbol","title":"colorSpaceGetDeviceRGB()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"colorSpaceGetDeviceRGB"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGColorSpace","preciseIdentifier":"c:@T@CGColorSpaceRef"}],"abstract":[{"type":"text","text":"For coders who use "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":", use the information below to create an effient CGImage which can be render on GPU without Core Animation’s extra copy ("},{"type":"codeVoice","code":"CA::Render::copy_image"},{"type":"text","text":"), which can be debugged using "},{"type":"codeVoice","code":"Color Copied Image"},{"type":"text","text":" in Xcode Instruments"},{"type":"text","text":" "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":"’s "},{"type":"codeVoice","code":"bytesPerRow"},{"type":"text","text":", "},{"type":"codeVoice","code":"space"},{"type":"text","text":", "},{"type":"codeVoice","code":"bitmapInfo"},{"type":"text","text":" params should use the information below."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/colorSpaceGetDeviceRGB()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"colorSpaceGetDeviceRGB"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/colorspacegetdevicergb()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","title":"SDImageCoderHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderHelper"}],"abstract":[{"type":"text","text":"Provide some common helper methods for building the image decoder\/encoder."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"colorSpaceGetDeviceRGB"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"colorSpaceGetDeviceRGB"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGColorSpace","preciseIdentifier":"c:@S@CGColorSpace"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"colorSpaceGetDeviceRGB"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1colorSpaceGetDeviceRGB()\/title","value":"colorSpaceGetDeviceRGB"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1colorSpaceGetDeviceRGB()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"colorSpaceGetDeviceRGB"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","value":"SDImageCoderHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}