{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","preciseIdentifier":"c:@E@SDImageForceDecodePolicy","text":"SDImageForceDecodePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedimage(with:policy:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedimage(with:policy:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:policy:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return the decoded image by the provided image. This one unlike "},{"type":"codeVoice","code":"CGImageCreateDecoded:"},{"type":"text","text":", will not decode the image which contains alpha channel or animated image. On iOS 15+, this may use "},{"type":"codeVoice","code":"UIImage.preparingForDisplay()"},{"type":"text","text":" to use CMPhoto for better performance than the old solution."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageForceDecodePolicy","preciseIdentifier":"c:@E@SDImageForceDecodePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"title":"decodedImage(with:policy:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)decodedImageWithImage:policy:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"decodedImageWithImage:policy:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/decodedImage(with:policy:)":{"role":"symbol","title":"decodedImage(with:policy:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageForceDecodePolicy","preciseIdentifier":"c:@E@SDImageForceDecodePolicy"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Return the decoded image by the provided image. This one unlike "},{"type":"codeVoice","code":"CGImageCreateDecoded:"},{"type":"text","text":", will not decode the image which contains alpha channel or animated image. On iOS 15+, this may use "},{"type":"codeVoice","code":"UIImage.preparingForDisplay()"},{"type":"text","text":" to use CMPhoto for better performance than the old solution."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:policy:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decodedImageWithImage:policy:"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedimage(with:policy:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","title":"SDImageCoderHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderHelper"}],"abstract":[{"type":"text","text":"Provide some common helper methods for building the image decoder\/encoder."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy":{"role":"symbol","title":"SDImageForceDecodePolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"type":"text","text":" "},{"type":"text","text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"type":"codeVoice","code":"pre-process"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"type":"text","text":" "},{"type":"text","text":"The downside is that force-decode may consume RAM and CPU, and may loss the "},{"type":"codeVoice","code":"lazy"},{"type":"text","text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: "},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"decodedImageWithImage:policy:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedImageWithImage:policy:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"decodedImageWithImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"policy:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","preciseIdentifier":"c:@E@SDImageForceDecodePolicy","text":"SDImageForceDecodePolicy"},{"kind":"text","text":")"},{"kind":"internalParam","text":"policy"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedImage(with:policy:)\/title","value":"decodedImageWithImage:policy:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedImage(with:policy:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedImageWithImage:policy:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","value":"SDImageCoderHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/title","value":"SDImageForceDecodePolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}