{"metadata":{"roleHeading":"Type Property","title":"defaultScaleDownLimitBytes","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultScaleDownLimitBytes"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"externalID":"c:objc(cs)SDImageCoderHelper(cpy)defaultScaleDownLimitBytes","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"defaultScaleDownLimitBytes","kind":"identifier"}],"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Control the default limit bytes to scale down largest images."},{"type":"text","text":" "},{"type":"text","text":"This value must be larger than 4 Bytes (at least 1x1 pixel). Defaults to 60MB on iOS\/tvOS, 90MB on macOS, 30MB on watchOS."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/defaultscaledownlimitbytes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/defaultscaledownlimitbytes"]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultScaleDownLimitBytes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultScaleDownLimitBytes"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/defaultScaleDownLimitBytes":{"type":"topic","abstract":[{"type":"text","text":"Control the default limit bytes to scale down largest images."},{"text":" ","type":"text"},{"type":"text","text":"This value must be larger than 4 Bytes (at least 1x1 pixel). Defaults to 60MB on iOS\/tvOS, 90MB on macOS, 30MB on watchOS."}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/defaultscaledownlimitbytes","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultScaleDownLimitBytes","kind":"identifier"}],"kind":"symbol","title":"defaultScaleDownLimitBytes","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultScaleDownLimitBytes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"defaultScaleDownLimitBytes"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"defaultScaleDownLimitBytes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultScaleDownLimitBytes"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SDImageCoderHelper","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"text":"SDImageCoderHelper","kind":"identifier"}]},{"value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle"},{"op":"replace","value":"defaultScaleDownLimitBytes","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1defaultScaleDownLimitBytes\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1defaultScaleDownLimitBytes\/fragments","value":[{"text":"defaultScaleDownLimitBytes","kind":"identifier"}]}]}]}