{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exifOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageOrientation"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Orientation","preciseIdentifier":"c:@E@UIImageOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImagePropertyOrientation","preciseIdentifier":"c:@E@CGImagePropertyOrientation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/exiforientation(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/exiforientation(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/exifOrientation(from:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Convert an iOS orientation to an EXIF image orientation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exifOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Orientation","preciseIdentifier":"c:@E@UIImageOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImagePropertyOrientation","preciseIdentifier":"c:@E@CGImagePropertyOrientation"}],"title":"exifOrientation(from:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCoderHelper(cm)exifOrientationFromImageOrientation:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"exifOrientationFromImageOrientation:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/exifOrientation(from:)":{"role":"symbol","title":"exifOrientation(from:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"exifOrientation"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Orientation","preciseIdentifier":"c:@E@UIImageOrientation"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGImagePropertyOrientation","preciseIdentifier":"c:@E@CGImagePropertyOrientation"}],"abstract":[{"type":"text","text":"Convert an iOS orientation to an EXIF image orientation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/exifOrientation(from:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exifOrientationFromImageOrientation:"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/exiforientation(from:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","title":"SDImageCoderHelper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderHelper"}],"abstract":[{"type":"text","text":"Provide some common helper methods for building the image decoder\/encoder."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"exifOrientationFromImageOrientation:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"exifOrientationFromImageOrientation:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"CGImagePropertyOrientation","preciseIdentifier":"c:@E@CGImagePropertyOrientation"},{"kind":"text","text":") "},{"kind":"identifier","text":"exifOrientationFromImageOrientation:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImageOrientation","preciseIdentifier":"c:@E@UIImageOrientation"},{"kind":"text","text":")"},{"kind":"internalParam","text":"imageOrientation"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1exifOrientation(from:)\/title","value":"exifOrientationFromImageOrientation:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1exifOrientation(from:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"exifOrientationFromImageOrientation:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","value":"SDImageCoderHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}