{"sections":[],"abstract":[{"text":"Convert an EXIF image orientation to an iOS one.","type":"text"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/imageOrientation(from:)"},"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/imageorientation(from:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/imageorientation(from:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:objc(cs)SDImageCoderHelper(cm)imageOrientationFromEXIFOrientation:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"imageOrientationFromEXIFOrientation:","kind":"identifier"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CGImagePropertyOrientation","text":"CGImagePropertyOrientation","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"text":"Orientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@UIImageOrientation"}],"title":"imageOrientation(from:)","roleHeading":"Type Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageOrientation","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":" "},{"text":"exifOrientation","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGImagePropertyOrientation","preciseIdentifier":"c:@E@CGImagePropertyOrientation","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":".","kind":"text"},{"text":"Orientation","preciseIdentifier":"c:@E@UIImageOrientation","kind":"typeIdentifier"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"EXIF orientation"}]}],"name":"exifOrientation"}]},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"iOS orientation","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/imageOrientation(from:)":{"type":"topic","abstract":[{"type":"text","text":"Convert an EXIF image orientation to an iOS one."}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/imageorientation(from:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageOrientation","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImagePropertyOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@CGImagePropertyOrientation"},{"kind":"text","text":") -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageOrientation","text":"Orientation","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageOrientationFromEXIFOrientation:","kind":"identifier"}],"kind":"symbol","title":"imageOrientation(from:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/imageOrientation(from:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"imageOrientationFromEXIFOrientation:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"imageOrientationFromEXIFOrientation:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:@E@UIImageOrientation","text":"UIImageOrientation","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"imageOrientationFromEXIFOrientation:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@CGImagePropertyOrientation","text":"CGImagePropertyOrientation"},{"kind":"text","text":") "},{"kind":"internalParam","text":"exifOrientation"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"parameters":[{"name":"exifOrientation","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"EXIF orientation"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"anchor":"return-value","text":"Return Value","type":"heading"},{"inlineContent":[{"text":"iOS orientation","type":"text"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1imageOrientation(from:)\/title","value":"imageOrientationFromEXIFOrientation:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1imageOrientation(from:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"imageOrientationFromEXIFOrientation:","kind":"identifier"}]},{"value":"SDImageCoderHelper","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}],"op":"replace"},{"value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","op":"replace"}]}]}