{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"scaledSize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withImageSize"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"imageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"scale","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"scaleSize","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preserveAspectRatio","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"shouldScaleUp"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image size (in pixel or point defined by caller)","type":"text"}]}],"name":"imageSize"},{"name":"scaleSize","content":[{"type":"paragraph","inlineContent":[{"text":"The scale size (in pixel or point defined by caller)","type":"text"}]}]},{"name":"preserveAspectRatio","content":[{"inlineContent":[{"text":"Whether or not to preserve aspect ratio","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whether or not to scale up (or scale down only)"}]}],"name":"shouldScaleUp"}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"type":"aside","content":[{"inlineContent":[{"text":"For example, if you implements thumnail decoding, pass ","type":"text"},{"type":"codeVoice","code":"shouldScaleUp"},{"text":" to NO to avoid the calculated size larger than image size.","type":"text"}],"type":"paragraph"}],"name":"Note","style":"note"}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"kind":"symbol","abstract":[{"type":"text","text":"Scale the image size based on provided scale size, whether or not to preserve aspect ratio, whether or not to scale up."}],"metadata":{"externalID":"c:objc(cs)SDImageCoderHelper(cm)scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:","title":"scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaledSize","kind":"identifier"},{"text":"(","kind":"text"},{"text":"withImageSize","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"preserveAspectRatio"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldScaleUp","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"symbolKind":"method","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Method","navigatorTitle":[{"text":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:","kind":"identifier"}],"role":"symbol"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:scale:preserveaspectratio:shouldscaleup:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:scale:preserveaspectratio:shouldscaleup:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)":{"abstract":[{"type":"text","text":"Scale the image size based on provided scale size, whether or not to preserve aspect ratio, whether or not to scale up."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaledSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preserveAspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldScaleUp"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"kind":"symbol","title":"scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:scale:preserveaspectratio:shouldscaleup:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)","navigatorTitle":[{"text":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scaledSizeWithImageSize:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") ","kind":"text"},{"text":"imageSize","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaleSize:"},{"kind":"text","text":"("},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"scaleSize"},{"kind":"text","text":" "},{"text":"preserveAspectRatio:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@BOOL","text":"BOOL","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"preserveAspectRatio"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldScaleUp:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"text":") ","kind":"text"},{"text":"shouldScaleUp","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The image size (in pixel or point defined by caller)","type":"text"}],"type":"paragraph"}],"name":"imageSize"},{"name":"scaleSize","content":[{"type":"paragraph","inlineContent":[{"text":"The scale size (in pixel or point defined by caller)","type":"text"}]}]},{"name":"preserveAspectRatio","content":[{"type":"paragraph","inlineContent":[{"text":"Whether or not to preserve aspect ratio","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"Whether or not to scale up (or scale down only)","type":"text"}]}],"name":"shouldScaleUp"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)\/title","value":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:"}]},{"value":"SDImageCoderHelper","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","op":"replace","value":[{"text":"SDImageCoderHelper","kind":"identifier"}]}]}]}