{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:limitbytes:bytesperpixel:framecount:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:limitbytes:bytesperpixel:framecount:)"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"abstract":[{"text":"Calculate the limited image size with the bytes, when using ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeScaleDownLimitBytes"},{"type":"text","text":". This preserve aspect ratio and never scale up"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scaledSize","kind":"identifier"},{"kind":"text","text":"("},{"text":"withImageSize","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"kind":"externalParam","text":"limitBytes"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytesPerPixel"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"frameCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageCoderHelper(cm)scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:","title":"scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","roleHeading":"Type Method","role":"symbol","navigatorTitle":[{"text":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:","kind":"identifier"}],"symbolKind":"method"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scaledSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"kind":"text","text":" "},{"kind":"internalParam","text":"imageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"limitBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"bytesPerPixel"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"frameCount","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}]}],"kind":"declarations"},{"parameters":[{"name":"imageSize","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image size (in pixel or point defined by caller)"}]}]},{"name":"limitBytes","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The limit bytes"}]}]},{"name":"bytesPerPixel","content":[{"inlineContent":[{"type":"text","text":"The bytes per pixel"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The image frame count, 0 means 1 frame as well","type":"text"}],"type":"paragraph"}],"name":"frameCount"}],"kind":"parameters"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)":{"role":"symbol","kind":"symbol","title":"scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","navigatorTitle":[{"text":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scaledSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"limitBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"text":"bytesPerPixel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"frameCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Calculate the limited image size with the bytes, when using "},{"type":"codeVoice","code":"SDImageCoderDecodeScaleDownLimitBytes"},{"type":"text","text":". This preserve aspect ratio and never scale up"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:limitbytes:bytesperpixel:framecount:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":") ","kind":"text"},{"kind":"identifier","text":"scaledSizeWithImageSize:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"imageSize","kind":"internalParam"},{"kind":"text","text":" "},{"text":"limitBytes:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"text":"limitBytes","kind":"internalParam"},{"kind":"text","text":" "},{"text":"bytesPerPixel:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"bytesPerPixel"},{"text":" ","kind":"text"},{"text":"frameCount:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"frameCount"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image size (in pixel or point defined by caller)"}]}],"name":"imageSize"},{"content":[{"inlineContent":[{"type":"text","text":"The limit bytes"}],"type":"paragraph"}],"name":"limitBytes"},{"name":"bytesPerPixel","content":[{"type":"paragraph","inlineContent":[{"text":"The bytes per pixel","type":"text"}]}]},{"name":"frameCount","content":[{"type":"paragraph","inlineContent":[{"text":"The image frame count, 0 means 1 frame as well","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)\/title","value":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","op":"replace","value":"SDImageCoderHelper"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"text":"SDImageCoderHelper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","value":[{"text":"SDImageCoderHelper","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}