{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdmemorycache-swift.class\/init(config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdmemorycache-swift.class\/init(config:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class\/init(config:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create a new memory cache instance with the specify cache config. You can check "},{"type":"codeVoice","code":"maxMemoryCost"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxMemoryCount"},{"type":"text","text":" used for memory cache."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfig:"}],"role":"symbol","title":"init(config:)","roleHeading":"Initializer","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"},{"kind":"text","text":")"}],"symbolKind":"init","externalID":"c:objc(pl)SDMemoryCache(im)initWithConfig:","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCache-swift.class":{"role":"symbol","title":"SDMemoryCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCache"}],"abstract":[{"type":"text","text":"A memory cache which auto purge the cache on memory warning and support weak cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDMemoryCache"}],"url":"\/documentation\/sdwebimage\/sdmemorycache-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","title":"SDImageCacheConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCache-swift.class/init(config:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithConfig:"}],"role":"symbol","title":"init(config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a new memory cache instance with the specify cache config. You can check "},{"type":"codeVoice","code":"maxMemoryCost"},{"type":"text","text":" and "},{"type":"codeVoice","code":"maxMemoryCount"},{"type":"text","text":" used for memory cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class\/init(config:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdmemorycache-swift.class\/init(config:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithConfig:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithConfig:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"config"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class\/title","value":"SDMemoryCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDMemoryCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class~1init(config:)\/title","value":"initWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class~1init(config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}