{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageLoadState"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageLoadState\/progress","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Progress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"abstract":[{"text":"Image loading progress. The unit count is the received size and excepted size of download.","type":"text"}],"metadata":{"role":"symbol","title":"progress","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","externalID":"c:objc(cs)SDWebImageLoadState(py)progress","navigatorTitle":[{"kind":"identifier","text":"progress"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Progress","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress"},{"text":"?","kind":"text"}],"symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageloadstate\/progress"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageloadstate\/progress"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageLoadState/progress":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageLoadState\/progress","abstract":[{"type":"text","text":"Image loading progress. The unit count is the received size and excepted size of download."}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"progress","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSProgress","text":"Progress"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"progress"}],"url":"\/documentation\/sdwebimage\/sdwebimageloadstate\/progress","title":"progress","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageLoadState":{"navigatorTitle":[{"text":"SDWebImageLoadState","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageloadstate","title":"SDWebImageLoadState","type":"topic","abstract":[{"type":"text","text":"A loading state to manage View Category which contains multiple states. Like UIImgeView.image && UIImageView.highlightedImage"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageLoadState","kind":"identifier"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageLoadState"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"progress","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"progress","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSProgress","preciseIdentifier":"c:objc(cs)NSProgress","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"progress","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"progress","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageLoadState~1progress\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageLoadState~1progress\/fragments","value":[{"text":"progress","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageLoadState\/title","value":"SDWebImageLoadState","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageLoadState\/fragments","value":[{"text":"SDWebImageLoadState","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageLoadState\/navigatorTitle","value":[{"text":"SDWebImageLoadState","kind":"identifier"}]}]}]}