{"schemaVersion":{"minor":3,"patch":0,"major":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/concurrent"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/concurrent"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/concurrent"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy"]]},"sections":[],"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","title":"SDImageCachesManagerOperationPolicy.concurrent","symbolKind":"case","externalID":"c:@E@SDImageCachesManagerOperationPolicy@SDImageCachesManagerOperationPolicyConcurrent","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicyConcurrent","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"concurrent","kind":"identifier"}],"roleHeading":"Case"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"concurrent"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/concurrent":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/concurrent","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"concurrent","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicyConcurrent","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy.concurrent","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/concurrent"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy","type":"topic","abstract":[{"text":"Policy for cache operation","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDImageCachesManagerOperationPolicyConcurrent","op":"replace"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SDImageCachesManagerOperationPolicyConcurrent","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SDImageCachesManagerOperationPolicyConcurrent","kind":"identifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1concurrent\/title","value":"SDImageCachesManagerOperationPolicyConcurrent","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1concurrent\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicyConcurrent"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title","value":"SDImageCachesManagerOperationPolicy"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments","op":"replace","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/navigatorTitle","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}]}]}]}