{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/rawrepresentable-implementations"]}],"metadata":{"modules":[{"name":"SDWebImage"}],"title":"RawRepresentable Implementations","roleHeading":"API Collection","role":"collectionGroup"},"kind":"article","sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy"]]},"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/hashValue"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/hash(into:)"],"anchor":"Instance-Methods","generated":true}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/hashValue":{"role":"symbol","conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hashValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/hashValue","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/hashvalue","kind":"symbol","title":"hashValue"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/hash(into:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"text":")","kind":"text"}],"kind":"symbol","type":"topic","conformance":{"constraints":[{"code":"Self","type":"codeVoice"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"Hashable"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}]},"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/hash(into:)","title":"hash(into:)","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/hash(into:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy","type":"topic","abstract":[{"text":"Policy for cache operation","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy"}},"variantOverrides":[{"patch":[{"value":"SDImageCachesManagerOperationPolicy","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}