{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notauthorized"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notauthorized"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notAuthorized","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Photos framework access is not authorized by user"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"title":"SDWebImagePhotosError.Code.notAuthorized","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDWebImagePhotosError@SDWebImagePhotosErrorNotAuthorized","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code"]]},"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct":{"role":"symbol","title":"SDWebImagePhotosError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosError"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/notAuthorized":{"role":"symbol","title":"SDWebImagePhotosError.Code.notAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"abstract":[{"type":"text","text":"Photos framework access is not authorized by user"}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notauthorized"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code":{"role":"symbol","title":"SDWebImagePhotosError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImagePhotosErrorNotAuthorized"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notAuthorized\/title","value":"SDWebImagePhotosErrorNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notAuthorized\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code\/title","value":"SDWebImagePhotosError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosError"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}