{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notImageAsset"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notimageasset"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notimageasset"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notImageAsset","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Photos URL is not image asset type (like Video or Audio)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notImageAsset"}],"title":"SDWebImagePhotosError.Code.notImageAsset","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDWebImagePhotosError@SDWebImagePhotosErrorNotImageAsset","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code"]]},"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code":{"role":"symbol","title":"SDWebImagePhotosError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct":{"role":"symbol","title":"SDWebImagePhotosError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosError"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/notImageAsset":{"role":"symbol","title":"SDWebImagePhotosError.Code.notImageAsset","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notImageAsset"}],"abstract":[{"type":"text","text":"Photos URL is not image asset type (like Video or Audio)"}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notImageAsset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notimageasset"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImagePhotosErrorNotImageAsset"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code\/title","value":"SDWebImagePhotosError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosError"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notImageAsset\/title","value":"SDWebImagePhotosErrorNotImageAsset"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notImageAsset\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}