{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllData"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/removealldata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/removealldata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeAllData()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Empties the cache."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file delete finished."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeAllData"}],"role":"symbol","title":"removeAllData()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllData"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)SDDiskCache(im)removeAllData","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol":{"role":"symbol","title":"SDDiskCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDDiskCacheProtocol"}],"abstract":[{"type":"text","text":"A protocol to allow custom disk cache used in SDImageCache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDDiskCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/removeAllData()":{"navigatorTitle":[{"kind":"identifier","text":"removeAllData"}],"role":"symbol","title":"removeAllData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllData"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Empties the cache."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file delete finished."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeAllData()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/removealldata()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeAllData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeAllData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/title","value":"SDDiskCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDDiskCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeAllData()\/title","value":"removeAllData"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeAllData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeAllData"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}