{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeExpiredData"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/removeexpireddata()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/removeexpireddata()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeExpiredData()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes the expired data from the cache. You can choose the data to remove base on "},{"type":"codeVoice","code":"ageLimit"},{"type":"text","text":", "},{"type":"codeVoice","code":"countLimit"},{"type":"text","text":" and "},{"type":"codeVoice","code":"sizeLimit"},{"type":"text","text":" options."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"removeExpiredData"}],"role":"symbol","title":"removeExpiredData()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeExpiredData"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)SDDiskCache(im)removeExpiredData","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/removeExpiredData()":{"navigatorTitle":[{"kind":"identifier","text":"removeExpiredData"}],"role":"symbol","title":"removeExpiredData()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeExpiredData"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Removes the expired data from the cache. You can choose the data to remove base on "},{"type":"codeVoice","code":"ageLimit"},{"type":"text","text":", "},{"type":"codeVoice","code":"countLimit"},{"type":"text","text":" and "},{"type":"codeVoice","code":"sizeLimit"},{"type":"text","text":" options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeExpiredData()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/removeexpireddata()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol":{"role":"symbol","title":"SDDiskCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDDiskCacheProtocol"}],"abstract":[{"type":"text","text":"A protocol to allow custom disk cache used in SDImageCache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDDiskCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"removeExpiredData"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeExpiredData"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeExpiredData"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeExpiredData()\/title","value":"removeExpiredData"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeExpiredData()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeExpiredData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/title","value":"SDDiskCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDDiskCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}