{"metadata":{"modules":[{"name":"SDWebImage"}],"symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"required":true,"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"setData:forKey:"}],"roleHeading":"Instance Method","title":"setData(_:forKey:)","platforms":[{"introducedAt":"8.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"introducedAt":"8.0","deprecated":false,"beta":false,"name":"iPadOS","unavailable":false},{"name":"Mac Catalyst","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false}],"externalID":"c:objc(pl)SDDiskCache(im)setData:forKey:"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setData(_:forKey:)"},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setData","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The data to be stored in the cache.","type":"text"}],"type":"paragraph"}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The key with which to associate the value. If nil, this method has no effect.","type":"text"}]}],"name":"key"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"Sets the value of the specified key in the cache.","type":"text"},{"type":"text","text":" "},{"text":"This method may blocks the calling thread until file write finished.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/setdata(_:forkey:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/setdata(_:forkey:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/setData(_:forKey:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setData","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","required":true,"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setData(_:forKey:)","title":"setData(_:forKey:)","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/setdata(_:forkey:)","abstract":[{"text":"Sets the value of the specified key in the cache.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method may blocks the calling thread until file write finished."}],"role":"symbol","navigatorTitle":[{"text":"setData:forKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol":{"title":"SDDiskCacheProtocol","abstract":[{"text":"A protocol to allow custom disk cache used in SDImageCache.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDDiskCacheProtocol"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol","navigatorTitle":[{"text":"SDDiskCacheProtocol","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"setData:forKey:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"setData:forKey:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setData:"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *) "},{"text":"data","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forKey:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The data to be stored in the cache.","type":"text"}],"type":"paragraph"}],"name":"data"},{"content":[{"inlineContent":[{"type":"text","text":"The key with which to associate the value. If nil, this method has no effect."}],"type":"paragraph"}],"name":"key"}]},"op":"replace"},{"value":"setData:forKey:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1setData(_:forKey:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1setData(_:forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setData:forKey:"}]},{"op":"replace","value":"SDDiskCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDDiskCache"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/navigatorTitle","value":[{"text":"SDDiskCache","kind":"identifier"}]}]}]}