{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/totalsize()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol\/totalsize()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalSize()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the total size (in bytes) of data in this cache."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file read finished."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"totalSize"}],"role":"symbol","title":"totalSize()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"symbolKind":"method","externalID":"c:objc(pl)SDDiskCache(im)totalSize","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/totalSize()":{"navigatorTitle":[{"kind":"identifier","text":"totalSize"}],"role":"symbol","title":"totalSize()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"totalSize"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Returns the total size (in bytes) of data in this cache."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file read finished."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalSize()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/totalsize()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol":{"role":"symbol","title":"SDDiskCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDDiskCacheProtocol"}],"abstract":[{"type":"text","text":"A protocol to allow custom disk cache used in SDImageCache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDDiskCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"totalSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"totalSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":") "},{"kind":"identifier","text":"totalSize"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1totalSize()\/title","value":"totalSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1totalSize()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"totalSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/title","value":"SDDiskCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDDiskCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}