{"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol"]]},"metadata":{"externalID":"c:objc(pl)SDWebImageCacheSerializer(im)cacheDataWithImage:originalData:imageURL:","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheDataWithImage:originalData:imageURL:"}],"title":"cacheData(with:originalData:imageURL:)","required":true,"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cacheData"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"originalData","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageURL"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"platforms":[{"name":"iOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false},{"unavailable":false,"name":"iPadOS","beta":false,"introducedAt":"8.0","deprecated":false},{"unavailable":false,"introducedAt":"8.0","beta":false,"name":"Mac Catalyst","deprecated":false}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol\/cacheData(with:originalData:imageURL:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provide the image data associated to the image and store to disk cache"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol\/cachedata(with:originaldata:imageurl:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol\/cachedata(with:originaldata:imageurl:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cacheData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"originalData","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"imageURL","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The loaded image"}],"type":"paragraph"}],"name":"image"},{"content":[{"inlineContent":[{"type":"text","text":"The original loaded image data. May be nil when image is transformed (UIImage.sd_isTransformed = YES)"}],"type":"paragraph"}],"name":"data"},{"name":"imageURL","content":[{"type":"paragraph","inlineContent":[{"text":"The image URL","type":"text"}]}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializerProtocol/cacheData(with:originalData:imageURL:)":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol\/cacheData(with:originalData:imageURL:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"originalData","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Provide the image data associated to the image and store to disk cache","type":"text"}],"role":"symbol","required":true,"navigatorTitle":[{"text":"cacheDataWithImage:originalData:imageURL:","kind":"identifier"}],"title":"cacheData(with:originalData:imageURL:)","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol\/cachedata(with:originaldata:imageurl:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializerProtocol":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol","navigatorTitle":[{"text":"SDWebImageCacheSerializerProtocol","kind":"identifier"}],"title":"SDWebImageCacheSerializerProtocol","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol","abstract":[{"type":"text","text":"This is the protocol for cache serializer."},{"text":" ","type":"text"},{"text":"We can use a block to specify the cache serializer. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"type":"text","text":" to store a block into context options."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheSerializerProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"cacheDataWithImage:originalData:imageURL:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheDataWithImage:originalData:imageURL:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"cacheDataWithImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"image"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalData:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"imageURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageURL"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The loaded image","type":"text"}]}],"name":"image"},{"name":"data","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original loaded image data. May be nil when image is transformed (UIImage.sd_isTransformed = YES)"}]}]},{"name":"imageURL","content":[{"inlineContent":[{"text":"The image URL","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"cacheDataWithImage:originalData:imageURL:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol~1cacheData(with:originalData:imageURL:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol~1cacheData(with:originalData:imageURL:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"cacheDataWithImage:originalData:imageURL:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol\/title","value":"SDWebImageCacheSerializer","op":"replace"},{"value":[{"text":"SDWebImageCacheSerializer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol\/navigatorTitle","value":[{"text":"SDWebImageCacheSerializer","kind":"identifier"}],"op":"replace"}]}]}