{"abstract":[{"type":"text","text":"A bitmask value that identifies the corners that you want"},{"text":" ","type":"text"},{"type":"text","text":"rounded. You can use this parameter to round only a subset"},{"text":" ","type":"text"},{"text":"of the corners of the rectangle.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageroundcornertransformer\/corners"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageroundcornertransformer\/corners"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/corners","interfaceLanguage":"swift"},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"corners","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner","text":"SDRectCorner","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDRectCorner"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"metadata":{"externalID":"c:objc(cs)SDImageRoundCornerTransformer(py)corners","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"corners","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDRectCorner","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"corners","kind":"identifier"}],"title":"corners","modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDRectCorner":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdrectcorner","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDRectCorner","kind":"identifier"}],"navigatorTitle":[{"text":"SDRectCorner","kind":"identifier"}],"kind":"symbol","title":"SDRectCorner","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDRectCorner"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer":{"abstract":[{"type":"text","text":"Image round corner transformer"}],"title":"SDImageRoundCornerTransformer","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","kind":"symbol","navigatorTitle":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/corners":{"type":"topic","abstract":[{"type":"text","text":"A bitmask value that identifies the corners that you want"},{"text":" ","type":"text"},{"text":"rounded. You can use this parameter to round only a subset","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the corners of the rectangle."}],"url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/corners","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"corners","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner","text":"SDRectCorner","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"corners","kind":"identifier"}],"kind":"symbol","title":"corners","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/corners"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"corners"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"corners"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDRectCorner","text":"SDRectCorner","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"corners","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDRectCorner\/title","op":"replace","value":"SDRectCorner"},{"value":[{"text":"SDRectCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDRectCorner\/fragments"},{"value":[{"text":"SDRectCorner","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDRectCorner\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/title","value":"SDImageRoundCornerTransformer","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1corners\/title","value":"corners"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1corners\/fragments","value":[{"text":"corners","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}