{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"radius","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cornerRadius"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"corners","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDRectCorner","text":"SDRectCorner","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner"},{"text":", ","kind":"text"},{"text":"borderWidth","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/init(radius:corners:borderWidth:borderColor:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageroundcornertransformer\/init(radius:corners:borderwidth:bordercolor:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageroundcornertransformer\/init(radius:corners:borderwidth:bordercolor:)"]}],"kind":"symbol","metadata":{"symbolKind":"init","externalID":"c:objc(cs)SDImageRoundCornerTransformer(cm)transformerWithRadius:corners:borderWidth:borderColor:","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"corners"},{"text":": ","kind":"text"},{"text":"SDRectCorner","kind":"typeIdentifier","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner"},{"text":", ","kind":"text"},{"text":"borderWidth","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":"?)","kind":"text"}],"role":"symbol","title":"init(radius:corners:borderWidth:borderColor:)","roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"transformerWithRadius:corners:borderWidth:borderColor:"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/init(radius:corners:borderWidth:borderColor:)":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"transformerWithRadius:corners:borderWidth:borderColor:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/init(radius:corners:borderwidth:bordercolor:)","kind":"symbol","title":"init(radius:corners:borderWidth:borderColor:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/init(radius:corners:borderWidth:borderColor:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDRectCorner","kind":"typeIdentifier","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"borderWidth"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?)","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer":{"abstract":[{"type":"text","text":"Image round corner transformer"}],"title":"SDImageRoundCornerTransformer","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","kind":"symbol","navigatorTitle":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDRectCorner":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdrectcorner","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDRectCorner","kind":"identifier"}],"navigatorTitle":[{"text":"SDRectCorner","kind":"identifier"}],"kind":"symbol","title":"SDRectCorner","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDRectCorner"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"transformerWithRadius:corners:borderWidth:borderColor:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithRadius:corners:borderWidth:borderColor:","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transformerWithRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":") "},{"text":"cornerRadius","kind":"internalParam"},{"kind":"text","text":" "},{"text":"corners:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDRectCorner","kind":"typeIdentifier","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDRectCorner"},{"text":") ","kind":"text"},{"text":"corners","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"borderWidth:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"text":") ","kind":"text"},{"text":"borderWidth","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"borderColor:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"borderColor","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1init(radius:corners:borderWidth:borderColor:)\/title","op":"replace","value":"transformerWithRadius:corners:borderWidth:borderColor:"},{"value":[{"text":"+ ","kind":"text"},{"text":"transformerWithRadius:corners:borderWidth:borderColor:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1init(radius:corners:borderWidth:borderColor:)\/fragments","op":"replace"},{"value":"SDImageRoundCornerTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/fragments","value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/navigatorTitle"},{"op":"replace","value":"SDRectCorner","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDRectCorner\/title"},{"value":[{"text":"SDRectCorner","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDRectCorner\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDRectCorner\/navigatorTitle","value":[{"text":"SDRectCorner","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}