{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePhotosLoader"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/objc(pl)NSObject","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/objc(pl)SDImageLoader","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s7CVarArgP","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SQ","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The imgae loader to load image asset from Photos library. You need to register the loader into manager firstly. Use "},{"type":"codeVoice","code":"@import SDWebImagePhotosPlugin"},{"type":"text","text":" to import full framework instead of each header."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePhotosLoader"}],"title":"SDImagePhotosLoader","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDImagePhotosLoader","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"SDImagePhotosLoader"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/fetchOptions","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/imageRequestOptions","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/requestImageAssetOnly"]},{"title":"Type Properties","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/shared"]}],"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/objc(pl)SDImageLoader":{"type":"unresolvable","title":"SDImageLoader","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/objc(pl)SDImageLoader"},"doc://org.cocoapods.SDWebImagePhotosPlugin/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SH"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader/requestImageAssetOnly":{"role":"symbol","title":"requestImageAssetOnly","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestImageAssetOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether we request only "},{"type":"codeVoice","code":"PHAssetMediaTypeImage"},{"type":"text","text":" asset and ignore other types (video\/audio\/unknown)."},{"type":"text","text":" "},{"type":"text","text":"When we found other type, an error "},{"type":"codeVoice","code":"SDWebImagePhotosErrorNotImageAsset"},{"type":"text","text":" will be reported."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES. If you prefer to load other type like video asset’s poster image, set this value to NO."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/requestImageAssetOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestImageAssetOnly"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/requestimageassetonly"},"doc://org.cocoapods.SDWebImagePhotosPlugin/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s23CustomStringConvertibleP"},"doc://org.cocoapods.SDWebImagePhotosPlugin/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SQ"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader/fetchOptions":{"role":"symbol","title":"fetchOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fetchOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PHFetchOptions","preciseIdentifier":"c:objc(cs)PHFetchOptions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The default "},{"type":"codeVoice","code":"fetchOptions"},{"type":"text","text":" used for PHAsset fetch with the localIdentifier."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/fetchOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fetchOptions"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/fetchoptions"},"doc://org.cocoapods.SDWebImagePhotosPlugin/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s7CVarArgP"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImagePhotosLoader","preciseIdentifier":"c:objc(cs)SDImagePhotosLoader"}],"abstract":[{"type":"text","text":"The global shared instance for Photos loader."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedLoader"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/shared"},"doc://org.cocoapods.SDWebImagePhotosPlugin/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/objc(pl)NSObject"},"doc://org.cocoapods.SDWebImagePhotosPlugin/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s28CustomDebugStringConvertibleP"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader/imageRequestOptions":{"role":"symbol","title":"imageRequestOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageRequestOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"PHImageRequestOptions","preciseIdentifier":"c:objc(cs)PHImageRequestOptions"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The default "},{"type":"codeVoice","code":"imageRequestOptions"},{"type":"text","text":" used for image asset request."},{"type":"text","text":" "},{"type":"text","text":"Defatuls value are these:"},{"type":"text","text":" "},{"type":"text","text":"networkAccessAllowed = YES;"},{"type":"text","text":" "},{"type":"text","text":"resizeMode = PHImageRequestOptionsResizeModeFast;"},{"type":"text","text":" "},{"type":"text","text":"deliveryMode = PHImageRequestOptionsDeliveryModeOpportunistic;"},{"type":"text","text":" "},{"type":"text","text":"version = PHImageRequestOptionsVersionCurrent;"}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/imageRequestOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageRequestOptions"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/imagerequestoptions"},"doc://org.cocoapods.SDWebImagePhotosPlugin/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/objc(cs)NSObject"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader":{"role":"symbol","title":"SDImagePhotosLoader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePhotosLoader"}],"abstract":[{"type":"text","text":"The imgae loader to load image asset from Photos library. You need to register the loader into manager firstly. Use "},{"type":"codeVoice","code":"@import SDWebImagePhotosPlugin"},{"type":"text","text":" to import full framework instead of each header."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImagePhotosLoader"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDImagePhotosLoader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImagePhotosLoader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImagePhotosLoader"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/fetchOptions","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/imageRequestOptions","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/requestImageAssetOnly","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/shared"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePhotosLoader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1requestImageAssetOnly\/title","value":"requestImageAssetOnly"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1requestImageAssetOnly\/fragments","value":[{"kind":"identifier","text":"requestImageAssetOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1fetchOptions\/title","value":"fetchOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1fetchOptions\/fragments","value":[{"kind":"identifier","text":"fetchOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1shared\/title","value":"sharedLoader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1shared\/fragments","value":[{"kind":"identifier","text":"sharedLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1imageRequestOptions\/title","value":"imageRequestOptions"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1imageRequestOptions\/fragments","value":[{"kind":"identifier","text":"imageRequestOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader\/title","value":"SDImagePhotosLoader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader\/fragments","value":[{"kind":"identifier","text":"SDImagePhotosLoader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}