{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotosprogressexpectedsize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotosprogressexpectedsize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosProgressExpectedSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Because Photos Framework progressBlock does not contains the file size, only the progress. See "},{"type":"codeVoice","code":"PHAssetImageProgressHandler"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This value is used to represent the "},{"type":"codeVoice","code":"exceptedSize"},{"type":"text","text":", and the "},{"type":"codeVoice","code":"receivedSize"},{"type":"text","text":" is calculated by multiplying with the progress value."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"title":"SDWebImagePhotosProgressExpectedSize","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@SDWebImagePhotosProgressExpectedSize","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin"]]},"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosProgressExpectedSize":{"role":"symbol","title":"SDWebImagePhotosProgressExpectedSize","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int64","preciseIdentifier":"s:s5Int64V"}],"abstract":[{"type":"text","text":"Because Photos Framework progressBlock does not contains the file size, only the progress. See "},{"type":"codeVoice","code":"PHAssetImageProgressHandler"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This value is used to represent the "},{"type":"codeVoice","code":"exceptedSize"},{"type":"text","text":", and the "},{"type":"codeVoice","code":"receivedSize"},{"type":"text","text":" is calculated by multiplying with the progress value."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosProgressExpectedSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotosprogressexpectedsize"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImagePhotosProgressExpectedSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"int64_t","preciseIdentifier":"c:@T@int64_t"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosProgressExpectedSize\/title","value":"SDWebImagePhotosProgressExpectedSize"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosProgressExpectedSize\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosProgressExpectedSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}