{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserrordomain"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserrordomain"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosErrorDomain","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"SDWebImagePhotosErrorDomain","roleHeading":"Global Variable","role":"symbol","symbolKind":"var","externalID":"c:@SDWebImagePhotosErrorDomain","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin"]]},"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosErrorDomain":{"role":"symbol","title":"SDWebImagePhotosErrorDomain","fragments":[{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosErrorDomain","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserrordomain"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImagePhotosErrorDomain"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosErrorDomain\/title","value":"SDWebImagePhotosErrorDomain"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosErrorDomain\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorDomain"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}