{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProgress"},{"kind":"text","text":" "},{"kind":"internalParam","text":"progressBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock","text":"SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completedBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"decodeOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? = nil) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/addhandlers(forprogress:completed:decodeoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/addhandlers(forprogress:completed:decodeoptions:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:decodeOptions:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}],"role":"symbol","title":"addHandlers(forProgress:completed:decodeOptions:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"decodeOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:objc(pl)SDWebImageDownloaderOperation(im)addHandlersForProgress:completed:decodeOptions:","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderProgressBlock":{"role":"symbol","title":"SDWebImageDownloaderProgressBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderprogressblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOptions":{"role":"symbol","title":"SDImageCoderOptions","fragments":[{"kind":"identifier","text":"SDImageCoderOptions"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderCompletedBlock":{"role":"symbol","title":"SDWebImageDownloaderCompletedBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloadercompletedblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol":{"role":"symbol","title":"SDWebImageDownloaderOperationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"abstract":[{"type":"text","text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from "},{"type":"codeVoice","code":"NSOperation"},{"type":"text","text":" and conform to this protocol"},{"type":"text","text":" "},{"type":"text","text":"For the description about these methods, see "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"role":"symbol","title":"SDImageCoderOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/addHandlers(forProgress:completed:decodeOptions:)":{"navigatorTitle":[{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}],"role":"symbol","title":"addHandlers(forProgress:completed:decodeOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"decodeOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:decodeOptions:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/addhandlers(forprogress:completed:decodeoptions:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addHandlersForProgress:completed:decodeOptions:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"addHandlersForProgress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(long, long, NSURL *)","preciseIdentifier":"c:BFv(#L#L#*$objc(cs)NSURL)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"progressBlock"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSData *, NSError *, _Bool)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#*$objc(cs)NSError#b)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completedBlock"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeOptions:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOptions","text":"SDImageCoderOptions"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"decodeOptions"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/title","value":"SDWebImageDownloaderProgressBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/title","value":"SDWebImageDownloaderCompletedBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1addHandlers(forProgress:completed:decodeOptions:)\/title","value":"addHandlersForProgress:completed:decodeOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1addHandlers(forProgress:completed:decodeOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}