{"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataTask","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/datatask"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/datatask"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","externalID":"c:objc(pl)SDWebImageDownloaderOperation(py)dataTask","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"dataTask","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask"},{"kind":"text","text":"?"}],"role":"symbol","title":"dataTask","roleHeading":"Instance Property","platforms":[{"name":"iOS","unavailable":false,"deprecated":false,"introducedAt":"7.0","beta":false},{"deprecated":false,"beta":false,"introducedAt":"7.0","unavailable":false,"name":"iPadOS"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"7.0"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"dataTask","kind":"identifier"}],"required":true},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/dataTask"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol":{"title":"SDWebImageDownloaderOperationProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol","abstract":[{"text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from ","type":"text"},{"type":"codeVoice","code":"NSOperation"},{"text":" and conform to this protocol","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For the description about these methods, see "},{"code":"SDWebImageDownloaderOperation","type":"codeVoice"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/dataTask":{"kind":"symbol","navigatorTitle":[{"text":"dataTask","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/datatask","title":"dataTask","abstract":[],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dataTask"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSessionTask","text":"URLSessionTask","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"required":true,"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/dataTask","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"dataTask"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"dataTask","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURLSessionTask","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"text":" * ","kind":"text"},{"text":"dataTask","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1dataTask\/title","value":"dataTask"},{"op":"replace","value":[{"text":"dataTask","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1dataTask\/fragments"}]}]}