{"metadata":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"kind":"text","text":"?, "},{"text":"inSession","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"title":"init(request:inSession:options:context:)","externalID":"c:objc(pl)SDWebImageDownloaderOperation(im)initWithRequest:inSession:options:context:::SYNTHESIZED::c:objc(pl)SDWebImageDownloaderOperation","symbolKind":"init","roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"platforms":[]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLRequest","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inSession"},{"kind":"text","text":" "},{"text":"session","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"text":" = [], ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:insession:options:context:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:context:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/init(request:inSession:options:context:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:context:)","type":"topic","title":"init(request:inSession:options:context:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"request","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:insession:options:context:)","kind":"symbol","role":"symbol","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol":{"title":"SDWebImageDownloaderOperationProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol","abstract":[{"text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from ","type":"text"},{"type":"codeVoice","code":"NSOperation"},{"text":" and conform to this protocol","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For the description about these methods, see "},{"code":"SDWebImageDownloaderOperation","type":"codeVoice"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"SDWebImageDownloaderOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}]},{"value":"SDWebImageDownloaderOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/title"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]}]}]}