{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"request","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"in"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"session"},{"kind":"text","text":": "},{"text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"text":" = [], ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier","text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLRequest","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV"},{"text":"?, ","kind":"text"},{"text":"in","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"platforms":[{"deprecated":false,"introducedAt":"8.0","unavailable":false,"beta":false,"name":"iOS"},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"8.0"},{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst"}],"required":true,"symbolKind":"init","navigatorTitle":[{"text":"initWithRequest:inSession:options:context:","kind":"identifier"}],"roleHeading":"Initializer","externalID":"c:objc(pl)SDWebImageDownloaderOperation(im)initWithRequest:inSession:options:context:","modules":[{"name":"SDWebImage"}],"role":"symbol","title":"init(request:in:options:context:)"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:in:options:context:)"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:in:options:context:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:in:options:context:)"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol":{"title":"SDWebImageDownloaderOperationProtocol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol","abstract":[{"text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from ","type":"text"},{"type":"codeVoice","code":"NSOperation"},{"text":" and conform to this protocol","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For the description about these methods, see "},{"code":"SDWebImageDownloaderOperation","type":"codeVoice"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/init(request:in:options:context:)":{"role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"request","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"in"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSession","text":"URLSession","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithRequest:inSession:options:context:"}],"title":"init(request:in:options:context:)","required":true,"kind":"symbol","abstract":[],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:in:options:context:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:in:options:context:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"initWithRequest:inSession:options:context:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithRequest:inSession:options:context:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithRequest:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURLRequest","preciseIdentifier":"c:objc(cs)NSURLRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"kind":"text","text":" "},{"text":"inSession:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSURLSession","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":" *) "},{"text":"session","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"kind":"text","text":"("},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"context:","kind":"identifier"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","text":"SDWebImageContext","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/title","value":"SDWebImageDownloaderOperation"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/navigatorTitle","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]},{"op":"replace","value":"SDWebImageDownloaderOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace","value":"SDWebImageContextOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1init(request:in:options:context:)\/title","value":"initWithRequest:inSession:options:context:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithRequest:inSession:options:context:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1init(request:in:options:context:)\/fragments","op":"replace"}]}]}