{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder","preciseIdentifier":"c:objc(cs)SDImageWebPCoder","text":"SDImageWebPCoder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/shared","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageWebPCoder","preciseIdentifier":"c:objc(cs)SDImageWebPCoder"}],"title":"shared","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageWebPCoder(cpy)sharedCoder","modules":[{"name":"SDWebImageWebPCoder"}],"navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}]},"hierarchy":{"paths":[["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder"]]},"references":{"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder":{"role":"collection","title":"SDWebImageWebPCoder","abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageWebPCoder","preciseIdentifier":"c:objc(cs)SDImageWebPCoder"}],"abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}],"url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder\/shared"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder":{"role":"symbol","title":"SDImageWebPCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageWebPCoder"}],"abstract":[{"type":"text","text":"Built in coder that supports WebP and animated WebP"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageWebPCoder"}],"url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedCoder"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder","preciseIdentifier":"c:objc(cs)SDImageWebPCoder","text":"SDImageWebPCoder"},{"kind":"text","text":" *"},{"kind":"identifier","text":"sharedCoder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder~1shared\/title","value":"sharedCoder"},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder~1shared\/fragments","value":[{"kind":"identifier","text":"sharedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder\/title","value":"SDImageWebPCoder"},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder\/fragments","value":[{"kind":"identifier","text":"SDImageWebPCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}