{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"blendMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CGBlendMode","text":"CGBlendMode","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"The blend mode, defaults to "},{"code":"sourceIn","type":"codeVoice"},{"type":"text","text":" if you use the initializer without blend mode"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer\/blendmode"]},{"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer\/blendmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/blendMode","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)SDImageTintTransformer(py)blendMode","navigatorTitle":[{"kind":"identifier","text":"blendMode"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"blendMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGBlendMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@CGBlendMode"}],"modules":[{"name":"SDWebImage"}],"title":"blendMode","symbolKind":"property","role":"symbol"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer":{"title":"SDImageTintTransformer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer","type":"topic","navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}],"abstract":[{"type":"text","text":"Image tint color transformer"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/blendMode":{"navigatorTitle":[{"text":"blendMode","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/blendmode","abstract":[{"text":"The blend mode, defaults to ","type":"text"},{"type":"codeVoice","code":"sourceIn"},{"type":"text","text":" if you use the initializer without blend mode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"blendMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGBlendMode","preciseIdentifier":"c:@E@CGBlendMode"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/blendMode","kind":"symbol","title":"blendMode","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"blendMode"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"blendMode","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"CGBlendMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@CGBlendMode"},{"text":" ","kind":"text"},{"kind":"identifier","text":"blendMode"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SDImageTintTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageTintTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/fragments"},{"op":"replace","value":[{"text":"SDImageTintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1blendMode\/title","value":"blendMode","op":"replace"},{"value":[{"kind":"identifier","text":"blendMode"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1blendMode\/fragments"}]}]}