{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:blendmode:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:blendmode:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"navigatorTitle":[{"text":"transformerWithColor:blendMode:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageTintTransformer(cm)transformerWithColor:blendMode:","title":"init(color:blendMode:)","fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIColor","preciseIdentifier":"c:objc(cs)UIColor"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"blendMode"},{"kind":"text","text":": "},{"text":"CGBlendMode","kind":"typeIdentifier","preciseIdentifier":"c:@E@CGBlendMode"},{"text":")","kind":"text"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer"},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:blendMode:)"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tintColor"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":", ","kind":"text"},{"text":"blendMode","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGBlendMode","preciseIdentifier":"c:@E@CGBlendMode"},{"kind":"text","text":")"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer":{"title":"SDImageTintTransformer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer","type":"topic","navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}],"abstract":[{"type":"text","text":"Image tint color transformer"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/init(color:blendMode:)":{"navigatorTitle":[{"kind":"identifier","text":"transformerWithColor:blendMode:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:blendMode:)","type":"topic","title":"init(color:blendMode:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"blendMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CGBlendMode","text":"CGBlendMode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:blendmode:)","kind":"symbol","role":"symbol","abstract":[]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"transformerWithColor:blendMode:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithColor:blendMode:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"transformerWithColor:","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":" *) ","kind":"text"},{"text":"tintColor","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"blendMode:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGBlendMode","preciseIdentifier":"c:@E@CGBlendMode"},{"kind":"text","text":") "},{"kind":"internalParam","text":"blendMode"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","value":"SDImageTintTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageTintTransformer"}],"op":"replace"},{"value":[{"text":"SDImageTintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:blendMode:)\/title","value":"transformerWithColor:blendMode:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:blendMode:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"transformerWithColor:blendMode:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}