{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:)"]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:)"},"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"tintColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"text":")","kind":"text"}]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"]]},"metadata":{"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDImageTintTransformer(cm)transformerWithColor:","navigatorTitle":[{"kind":"identifier","text":"transformerWithColor:"}],"roleHeading":"Initializer","title":"init(color:)","modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer":{"title":"SDImageTintTransformer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer","type":"topic","navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}],"abstract":[{"type":"text","text":"Image tint color transformer"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/init(color:)":{"navigatorTitle":[{"text":"transformerWithColor:","kind":"identifier"}],"title":"init(color:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:)","role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":")"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:)","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"transformerWithColor:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"transformerWithColor:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"+ (","kind":"text"},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"kind":"text","text":") "},{"text":"transformerWithColor:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"tintColor"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/title","value":"SDImageTintTransformer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/fragments","value":[{"text":"SDImageTintTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/navigatorTitle","value":[{"text":"SDImageTintTransformer","kind":"identifier"}]},{"value":"transformerWithColor:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithColor:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}