{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestImageAssetOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/requestimageassetonly"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/requestimageassetonly"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/requestImageAssetOnly","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether we request only "},{"type":"codeVoice","code":"PHAssetMediaTypeImage"},{"type":"text","text":" asset and ignore other types (video\/audio\/unknown)."},{"type":"text","text":" "},{"type":"text","text":"When we found other type, an error "},{"type":"codeVoice","code":"SDWebImagePhotosErrorNotImageAsset"},{"type":"text","text":" will be reported."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES. If you prefer to load other type like video asset’s poster image, set this value to NO."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestImageAssetOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"title":"requestImageAssetOnly","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImagePhotosLoader(py)requestImageAssetOnly","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"requestImageAssetOnly"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader"]]},"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader":{"role":"symbol","title":"SDImagePhotosLoader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePhotosLoader"}],"abstract":[{"type":"text","text":"The imgae loader to load image asset from Photos library. You need to register the loader into manager firstly. Use "},{"type":"codeVoice","code":"@import SDWebImagePhotosPlugin"},{"type":"text","text":" to import full framework instead of each header."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImagePhotosLoader"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader/requestImageAssetOnly":{"role":"symbol","title":"requestImageAssetOnly","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestImageAssetOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether we request only "},{"type":"codeVoice","code":"PHAssetMediaTypeImage"},{"type":"text","text":" asset and ignore other types (video\/audio\/unknown)."},{"type":"text","text":" "},{"type":"text","text":"When we found other type, an error "},{"type":"codeVoice","code":"SDWebImagePhotosErrorNotImageAsset"},{"type":"text","text":" will be reported."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES. If you prefer to load other type like video asset’s poster image, set this value to NO."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/requestImageAssetOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestImageAssetOnly"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/requestimageassetonly"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"requestImageAssetOnly"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requestImageAssetOnly"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"identifier","text":"requestImageAssetOnly"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader\/title","value":"SDImagePhotosLoader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader\/fragments","value":[{"kind":"identifier","text":"SDImagePhotosLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1requestImageAssetOnly\/title","value":"requestImageAssetOnly"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1requestImageAssetOnly\/fragments","value":[{"kind":"identifier","text":"requestImageAssetOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}