{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader","preciseIdentifier":"c:objc(cs)SDImagePhotosLoader","text":"SDImagePhotosLoader"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/shared","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The global shared instance for Photos loader."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImagePhotosLoader","preciseIdentifier":"c:objc(cs)SDImagePhotosLoader"}],"title":"shared","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImagePhotosLoader(cpy)sharedLoader","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"sharedLoader"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader"]]},"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImagePhotosLoader","preciseIdentifier":"c:objc(cs)SDImagePhotosLoader"}],"abstract":[{"type":"text","text":"The global shared instance for Photos loader."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedLoader"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader\/shared"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDImagePhotosLoader":{"role":"symbol","title":"SDImagePhotosLoader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePhotosLoader"}],"abstract":[{"type":"text","text":"The imgae loader to load image asset from Photos library. You need to register the loader into manager firstly. Use "},{"type":"codeVoice","code":"@import SDWebImagePhotosPlugin"},{"type":"text","text":" to import full framework instead of each header."}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImagePhotosLoader"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdimagephotosloader"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedLoader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedLoader"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDImagePhotosLoader","preciseIdentifier":"c:objc(cs)SDImagePhotosLoader","text":"SDImagePhotosLoader"},{"kind":"text","text":" *"},{"kind":"identifier","text":"sharedLoader"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1shared\/title","value":"sharedLoader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader~1shared\/fragments","value":[{"kind":"identifier","text":"sharedLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader\/title","value":"SDImagePhotosLoader"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDImagePhotosLoader\/fragments","value":[{"kind":"identifier","text":"SDImagePhotosLoader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}