{"metadata":{"navigatorTitle":[{"text":"transformerWithRadius:","kind":"identifier"}],"fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"externalID":"c:objc(cs)SDImageBlurTransformer(cm)transformerWithRadius:","title":"init(radius:)","modules":[{"name":"SDWebImage"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/init(radius:)","interfaceLanguage":"swift"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"kind":"text","text":" "},{"text":"blurRadius","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageblurtransformer\/init(radius:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageblurtransformer\/init(radius:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer/init(radius:)":{"navigatorTitle":[{"kind":"identifier","text":"transformerWithRadius:"}],"url":"\/documentation\/sdwebimage\/sdimageblurtransformer\/init(radius:)","title":"init(radius:)","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/init(radius:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer":{"url":"\/documentation\/sdwebimage\/sdimageblurtransformer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBlurTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","type":"topic","navigatorTitle":[{"text":"SDImageBlurTransformer","kind":"identifier"}],"abstract":[{"text":"Image blur effect transformer","type":"text"}],"role":"symbol","title":"SDImageBlurTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"value":"transformerWithRadius:","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithRadius:","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"transformerWithRadius:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"text":") ","kind":"text"},{"text":"blurRadius","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer~1init(radius:)\/title","value":"transformerWithRadius:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer~1init(radius:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithRadius:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/title","value":"SDImageBlurTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/fragments","value":[{"text":"SDImageBlurTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/navigatorTitle","value":[{"text":"SDImageBlurTransformer","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}