{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodeToHDR","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"Supported by iOS 17 and above when using ImageIO coder (third-party coder can support lower firmware)"},{"type":"text","text":" "},{"type":"text","text":"Defaults to @(NO), decoder will automatically convert SDR."}],"type":"paragraph"}],"type":"aside"},{"style":"note","type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"works for "},{"type":"codeVoice","code":"SDImageCoder"}],"type":"paragraph"}]}],"kind":"content"}],"abstract":[{"type":"text","text":"A Boolean ("},{"code":"SDImageHDRType.rawValue","type":"codeVoice"},{"text":") value (stored inside NSNumber) to provide converting to HDR during decoding. Currently if number is 0 (","type":"text"},{"code":"SDImageHDRTypeSDR","type":"codeVoice"},{"text":"), use SDR, else use HDR. But we may extend this option to represent ","type":"text"},{"type":"codeVoice","code":"SDImageHDRType"},{"type":"text","text":" all cases in the future (means, think this options as uint number, but not actual boolean)"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeToHDR","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodetohdr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodetohdr"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"property","roleHeading":"Type Property","title":"decodeToHDR","extendedModule":"SDWebImage","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeToHDR"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"}],"role":"symbol","externalID":"c:@SDImageCoderDecodeToHDR","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeToHDR"}],"modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeToHDR":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeToHDR","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","abstract":[{"type":"text","text":"A Boolean ("},{"type":"codeVoice","code":"SDImageHDRType.rawValue"},{"text":") value (stored inside NSNumber) to provide converting to HDR during decoding. Currently if number is 0 (","type":"text"},{"code":"SDImageHDRTypeSDR","type":"codeVoice"},{"type":"text","text":"), use SDR, else use HDR. But we may extend this option to represent "},{"type":"codeVoice","code":"SDImageHDRType"},{"text":" all cases in the future (means, think this options as uint number, but not actual boolean)","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeToHDR","navigatorTitle":[{"text":"SDImageCoderDecodeToHDR","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodetohdr","kind":"symbol","title":"decodeToHDR","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodeToHDR"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","value":[{"text":"SDImageCoderDecodeToHDR","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderDecodeToHDR","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeToHDR\/title","value":"SDImageCoderDecodeToHDR"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeToHDR\/fragments","value":[{"text":"SDImageCoderDecodeToHDR","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle","op":"replace","value":[{"text":"SDImageCoderOption","kind":"identifier"}]}]}]}