{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"kind":"symbol","sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodetypeidentifierhint"]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodetypeidentifierhint"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"navigatorTitle":[{"text":"SDImageCoderDecodeTypeIdentifierHint","kind":"identifier"}],"roleHeading":"Type Property","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodeTypeIdentifierHint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"decodeTypeIdentifierHint","externalID":"c:@SDImageCoderDecodeTypeIdentifierHint","modules":[{"name":"SDWebImage"}],"extendedModule":"SDWebImage","role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeTypeIdentifierHint","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you provide "},{"type":"codeVoice","code":"TypeIdentifierHint"},{"text":", the ","type":"text"},{"code":"FileExtensionHint","type":"codeVoice"},{"type":"text","text":" option above will be ignored (because UTType has high priority)"}]}]},{"type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"If you really don’t want any hint which effect the image result, pass ","type":"text"},{"type":"codeVoice","code":"NSNull.null"},{"text":" instead","type":"text"}]}],"style":"note"}],"kind":"content"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeTypeIdentifierHint","interfaceLanguage":"swift"},"abstract":[{"text":"A NSString value (UTI) indicating the source image’s file extension. Example: “public.jpeg-2000”, “com.nikon.raw-image”, “public.tiff”","type":"text"},{"type":"text","text":" "},{"text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF","type":"text"},{"text":" ","type":"text"},{"text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeTypeIdentifierHint":{"type":"topic","abstract":[{"type":"text","text":"A NSString value (UTI) indicating the source image’s file extension. Example: “public.jpeg-2000”, “com.nikon.raw-image”, “public.tiff”"},{"type":"text","text":" "},{"text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF","type":"text"},{"text":" ","type":"text"},{"text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodetypeidentifierhint","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeTypeIdentifierHint","navigatorTitle":[{"text":"SDImageCoderDecodeTypeIdentifierHint","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeTypeIdentifierHint"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"decodeTypeIdentifierHint","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodeTypeIdentifierHint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"path":"\/metadata\/fragments","value":[{"text":"SDImageCoderDecodeTypeIdentifierHint","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"SDImageCoderDecodeTypeIdentifierHint","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeTypeIdentifierHint\/title","value":"SDImageCoderDecodeTypeIdentifierHint"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCoderDecodeTypeIdentifierHint"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeTypeIdentifierHint\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"text":"SDImageCoderOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}