{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFileExtensionHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodefileextensionhint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodefileextensionhint"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeFileExtensionHint","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A NSString value indicating the source image’s file extension. Example: “jpg”, “nef”, “tif”, don’t prefix the dot"},{"type":"text","text":" "},{"type":"text","text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF"},{"type":"text","text":" "},{"type":"text","text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeFileExtensionHint"}],"role":"symbol","title":"decodeFileExtensionHint","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFileExtensionHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"symbolKind":"property","externalID":"c:@SDImageCoderDecodeFileExtensionHint","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeFileExtensionHint":{"role":"symbol","title":"decodeFileExtensionHint","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFileExtensionHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"abstract":[{"type":"text","text":"A NSString value indicating the source image’s file extension. Example: “jpg”, “nef”, “tif”, don’t prefix the dot"},{"type":"text","text":" "},{"type":"text","text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF"},{"type":"text","text":" "},{"type":"text","text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeFileExtensionHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeFileExtensionHint"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodefileextensionhint"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"role":"symbol","title":"SDImageCoderOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodeFileExtensionHint"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeFileExtensionHint"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeFileExtensionHint"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeFileExtensionHint\/title","value":"SDImageCoderDecodeFileExtensionHint"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeFileExtensionHint\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeFileExtensionHint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}