{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodePreserveAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodepreserveaspectratio"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodepreserveaspectratio"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodePreserveAspectRatio","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Boolean value indicating whether to keep the original aspect ratio when generating thumbnail images (or bitmap images from vector format)."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}],"role":"symbol","title":"decodePreserveAspectRatio","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodePreserveAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"symbolKind":"property","externalID":"c:@SDImageCoderDecodePreserveAspectRatio","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"role":"symbol","title":"SDImageCoderOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodePreserveAspectRatio":{"role":"symbol","title":"decodePreserveAspectRatio","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodePreserveAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether to keep the original aspect ratio when generating thumbnail images (or bitmap images from vector format)."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodePreserveAspectRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodepreserveaspectratio"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodePreserveAspectRatio"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodePreserveAspectRatio\/title","value":"SDImageCoderDecodePreserveAspectRatio"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodePreserveAspectRatio\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}