{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeUseLazyDecoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodeuselazydecoding"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/decodeuselazydecoding"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeUseLazyDecoding","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A BOOL value indicating whether to use lazy-decoding. Defaults to NO on animated image coder, but defaults to YES on static image coder."},{"type":"text","text":" "},{"type":"text","text":"CGImageRef, this image object typically support lazy-decoding, via the "},{"type":"codeVoice","code":"CGDataProviderCreateDirectAccess"},{"type":"text","text":" or "},{"type":"codeVoice","code":"CGDataProviderCreateSequential"},{"type":"text","text":" "},{"type":"text","text":"Which allows you to provide a lazy-called callback to access bitmap buffer, so that you can achieve lazy-decoding when consumer actually need bitmap buffer"},{"type":"text","text":" "},{"type":"text","text":"UIKit on iOS use heavy on this and ImageIO codec prefers to lazy-decoding for common Hardware-Accelerate format like JPEG\/PNG\/HEIC"},{"type":"text","text":" "},{"type":"text","text":"But however, the consumer may access bitmap buffer when running on main queue, like CoreAnimation layer render image. So this is a trade-off"},{"type":"text","text":" "},{"type":"text","text":"You can force us to disable the lazy-decoding and always allocate bitmap buffer on RAM, but this may have higher ratio of OOM (out of memory)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeUseLazyDecoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"decodeUseLazyDecoding","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDImageCoderDecodeUseLazyDecoding","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"role":"symbol","title":"SDImageCoderOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeUseLazyDecoding":{"role":"symbol","title":"decodeUseLazyDecoding","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeUseLazyDecoding"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"abstract":[{"type":"text","text":"A BOOL value indicating whether to use lazy-decoding. Defaults to NO on animated image coder, but defaults to YES on static image coder."},{"type":"text","text":" "},{"type":"text","text":"CGImageRef, this image object typically support lazy-decoding, via the "},{"type":"codeVoice","code":"CGDataProviderCreateDirectAccess"},{"type":"text","text":" or "},{"type":"codeVoice","code":"CGDataProviderCreateSequential"},{"type":"text","text":" "},{"type":"text","text":"Which allows you to provide a lazy-called callback to access bitmap buffer, so that you can achieve lazy-decoding when consumer actually need bitmap buffer"},{"type":"text","text":" "},{"type":"text","text":"UIKit on iOS use heavy on this and ImageIO codec prefers to lazy-decoding for common Hardware-Accelerate format like JPEG\/PNG\/HEIC"},{"type":"text","text":" "},{"type":"text","text":"But however, the consumer may access bitmap buffer when running on main queue, like CoreAnimation layer render image. So this is a trade-off"},{"type":"text","text":" "},{"type":"text","text":"You can force us to disable the lazy-decoding and always allocate bitmap buffer on RAM, but this may have higher ratio of OOM (out of memory)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeUseLazyDecoding","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodeuselazydecoding"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodeUseLazyDecoding"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeUseLazyDecoding\/title","value":"SDImageCoderDecodeUseLazyDecoding"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeUseLazyDecoding\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}