{"abstract":[{"type":"text","text":"A NSUInteger ("},{"type":"codeVoice","code":"SDImageHDRType.rawValue"},{"text":") value (stored inside NSNumber) to provide converting to HDR during encoding. Read the below carefully to choose the value.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/encodetohdr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/encodetohdr"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeToHDR"},"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToHDR"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","text":"SDImageCoderOption"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"text":"0(","type":"text"},{"type":"codeVoice","code":"SDImageHDRTypeSDR"},{"type":"text","text":") means SDR; 1("},{"type":"codeVoice","code":"SDImageHDRTypeISOHDR"},{"type":"text","text":") means ISO HDR (at least using 10 bits per components or above, supported by AVIF\/HEIF\/JPEG-XL); 2("},{"type":"codeVoice","code":"SDImageHDRTypeISOGainMap"},{"type":"text","text":") means ISO Gain Map HDR (may use 8 bits per components, supported by AVIF\/HEIF\/JPEG-XL, as well as traditional JPEG)"}],"type":"paragraph"}]},{"style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Gain Map like a mask image with metadata, which contains the depth\/bright information for pixels (1\/4 resolution), which used to convert between HDR and SDR."}]}],"name":"Note"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you use CIImage as HDR pipeline, you can export as CGImage for encoding. (But it’s also recommanded to use CIImage’s "},{"type":"codeVoice","code":"JPEGRepresentationOfImage"},{"type":"text","text":" or "},{"code":"HEIFRepresentationOfImage","type":"codeVoice"},{"type":"text","text":")"}]}]},{"type":"aside","style":"note","name":"Note","content":[{"type":"paragraph","inlineContent":[{"text":"Supported by iOS 18 and above when using ImageIO coder (third-party coder can support lower firmware)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Defaults to @(0), encoder will automatically convert SDR."}]}]},{"name":"Note","style":"note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"works for "},{"type":"codeVoice","code":"SDImageCoder"}],"type":"paragraph"}]}]}],"metadata":{"modules":[{"name":"SDWebImage"}],"extendedModule":"SDWebImage","role":"symbol","roleHeading":"Type Property","title":"encodeToHDR","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeToHDR"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToHDR"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier"}],"externalID":"c:@SDImageCoderEncodeToHDR","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeToHDR":{"abstract":[{"text":"A NSUInteger (","type":"text"},{"type":"codeVoice","code":"SDImageHDRType.rawValue"},{"type":"text","text":") value (stored inside NSNumber) to provide converting to HDR during encoding. Read the below carefully to choose the value."}],"title":"encodeToHDR","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodetohdr","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToHDR"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeToHDR","kind":"symbol","navigatorTitle":[{"text":"SDImageCoderEncodeToHDR","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SDImageCoderEncodeToHDR"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderEncodeToHDR"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderEncodeToHDR","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]}},{"value":"SDImageCoderEncodeToHDR","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeToHDR\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeToHDR\/fragments","value":[{"kind":"identifier","text":"SDImageCoderEncodeToHDR"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments"},{"value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle"}]}]}