{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeEmbedThumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/encodeembedthumbnail"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/encodeembedthumbnail"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeEmbedThumbnail","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Boolean value indicating the encoding format should contains a thumbnail image into the output data. Only some of image format (like JPEG\/HEIF\/AVIF) support this behavior. The embed thumbnail will be used during next time thumbnail decoding (provided "},{"type":"codeVoice","code":".thumbnailPixelSize"},{"type":"text","text":"), which is faster than full image thumbnail decoding. (NSNumber)"},{"type":"text","text":" "},{"type":"text","text":"Defaults to NO, which does not embed any thumbnail."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeEmbedThumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"encodeEmbedThumbnail","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDImageCoderEncodeEmbedThumbnail","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeEmbedThumbnail"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeEmbedThumbnail":{"role":"symbol","title":"encodeEmbedThumbnail","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeEmbedThumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"abstract":[{"type":"text","text":"A Boolean value indicating the encoding format should contains a thumbnail image into the output data. Only some of image format (like JPEG\/HEIF\/AVIF) support this behavior. The embed thumbnail will be used during next time thumbnail decoding (provided "},{"type":"codeVoice","code":".thumbnailPixelSize"},{"type":"text","text":"), which is faster than full image thumbnail decoding. (NSNumber)"},{"type":"text","text":" "},{"type":"text","text":"Defaults to NO, which does not embed any thumbnail."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeEmbedThumbnail","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeEmbedThumbnail"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodeembedthumbnail"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"role":"symbol","title":"SDImageCoderOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderEncodeEmbedThumbnail"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderEncodeEmbedThumbnail"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderEncodeEmbedThumbnail"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeEmbedThumbnail\/title","value":"SDImageCoderEncodeEmbedThumbnail"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeEmbedThumbnail\/fragments","value":[{"kind":"identifier","text":"SDImageCoderEncodeEmbedThumbnail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}