{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeMaxFileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/encodemaxfilesize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/encodemaxfilesize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeMaxFileSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A NSUInteger value specify the max output data bytes size after encoding. Some lossy format like JPEG\/HEIF supports the hint for codec to automatically reduce the quality and match the file size you want. Note this option will override the "},{"type":"codeVoice","code":"SDImageCoderEncodeCompressionQuality"},{"type":"text","text":", because now the quality is decided by the encoder. (NSNumber)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeMaxFileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"encodeMaxFileSize","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDImageCoderEncodeMaxFileSize","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeMaxFileSize"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeMaxFileSize":{"role":"symbol","title":"encodeMaxFileSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeMaxFileSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"abstract":[{"type":"text","text":"A NSUInteger value specify the max output data bytes size after encoding. Some lossy format like JPEG\/HEIF supports the hint for codec to automatically reduce the quality and match the file size you want. Note this option will override the "},{"type":"codeVoice","code":"SDImageCoderEncodeCompressionQuality"},{"type":"text","text":", because now the quality is decided by the encoder. (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeMaxFileSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeMaxFileSize"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodemaxfilesize"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"role":"symbol","title":"SDImageCoderOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderEncodeMaxFileSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderEncodeMaxFileSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderEncodeMaxFileSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeMaxFileSize\/title","value":"SDImageCoderEncodeMaxFileSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeMaxFileSize\/fragments","value":[{"kind":"identifier","text":"SDImageCoderEncodeMaxFileSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"kind":"identifier","text":"SDImageCoderOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}