{"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"No longer supported. Use SDWebImageContextDecodeOptions in loader API to provide options. Use SDImageCoderOptions in coder API to retrieve options.","type":"text"}]}],"abstract":[{"text":"A SDWebImageContext object which hold the original context options from top-level API. (SDWebImageContext)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This option is ignored for all built-in coders and take no effect."},{"text":" ","type":"text"},{"type":"text","text":"But this may be useful for some custom coders, because some business logic may dependent on things other than image or image data information only."},{"text":" ","type":"text"},{"type":"text","text":"Only the unknown context from top-level API (See SDWebImageDefine.h) may be passed in during image loading."},{"text":" ","type":"text"},{"type":"text","text":"See "},{"type":"codeVoice","code":"SDWebImageContext"},{"text":" for more detailed information.","type":"text"}],"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/webimagecontext"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption\/webimagecontext"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/webImageContext"},"metadata":{"externalID":"c:@SDImageCoderWebImageContext","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webImageContext","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false,"deprecatedAt":"8.0","message":"No longer supported. Use SDWebImageContextDecodeOptions in loader API to provide options. Use SDImageCoderOptions in coder API to retrieve options."},{"message":"No longer supported. Use SDWebImageContextDecodeOptions in loader API to provide options. Use SDImageCoderOptions in coder API to retrieve options.","deprecated":false,"introducedAt":"8.0","deprecatedAt":"8.0","beta":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"8.0","unavailable":false,"message":"No longer supported. Use SDWebImageContextDecodeOptions in loader API to provide options. Use SDImageCoderOptions in coder API to retrieve options.","beta":false,"deprecated":false,"deprecatedAt":"8.0","name":"Mac Catalyst"}],"extendedModule":"SDWebImage","roleHeading":"Type Property","role":"symbol","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDImageCoderWebImageContext","kind":"identifier"}],"title":"webImageContext"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"webImageContext","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCoderOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/webImageContext":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/webImageContext","abstract":[{"text":"A SDWebImageContext object which hold the original context options from top-level API. (SDWebImageContext)","type":"text"},{"type":"text","text":" "},{"text":"This option is ignored for all built-in coders and take no effect.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"But this may be useful for some custom coders, because some business logic may dependent on things other than image or image data information only."},{"type":"text","text":" "},{"type":"text","text":"Only the unknown context from top-level API (See SDWebImageDefine.h) may be passed in during image loading."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"SDWebImageContext"},{"text":" for more detailed information.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/webimagecontext","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webImageContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"navigatorTitle":[{"text":"SDImageCoderWebImageContext","kind":"identifier"}],"deprecated":true,"kind":"symbol","title":"webImageContext","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"iOS","deprecatedAt":"8.0"},{"unavailable":false,"deprecated":false,"deprecatedAt":"8.0","introducedAt":"8.0","name":"iPadOS","beta":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"deprecatedAt":"8.0","introducedAt":"8.0","deprecated":false}]},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"value":"SDImageCoderWebImageContext","op":"replace","path":"\/metadata\/title"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCoderWebImageContext"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"text":"SDImageCoderWebImageContext","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1webImageContext\/title","value":"SDImageCoderWebImageContext"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1webImageContext\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderWebImageContext"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"op":"replace","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace"}]}]}