{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/animatedcoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/animatedcoder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/animatedCoder"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"required":true,"title":"animatedCoder","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(pl)SDAnimatedImage(py)animatedCoder","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatedCoder","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","text":"SDAnimatedImageCoder"},{"kind":"text","text":")?"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"text":"animatedCoder","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol"]]},"abstract":[{"text":"Return the animated image coder if the image is created with ","type":"text"},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" method."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animatedCoder"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","text":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"]}]},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We use this with animated coder which conforms to "},{"type":"codeVoice","code":"SDProgressiveImageCoder"},{"text":" for progressive animation decoding.","type":"text"}]}],"style":"note","name":"Note"}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/animatedCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/animatedCoder","type":"topic","kind":"symbol","required":true,"title":"animatedCoder","navigatorTitle":[{"text":"animatedCoder","kind":"identifier"}],"abstract":[{"text":"Return the animated image coder if the image is created with ","type":"text"},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"text":" method.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animatedCoder"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","text":"SDAnimatedImageCoder"},{"kind":"text","text":")?"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/animatedcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol":{"title":"SDAnimatedImageProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"animatedCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"animatedCoder"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"id<SDAnimatedImageCoder>","preciseIdentifier":"c:Qoobjc(pl)SDAnimatedImageCoder","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"animatedCoder","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1animatedCoder\/title","value":"animatedCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1animatedCoder\/fragments","op":"replace","value":[{"text":"animatedCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/title","value":"SDAnimatedImage","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/fragments","value":[{"text":"SDAnimatedImage","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDAnimatedImage","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/navigatorTitle"},{"value":"SDAnimatedImageCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","op":"replace"},{"value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}