{"metadata":{"symbolKind":"init","title":"init(data:scale:options:)","roleHeading":"Initializer","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"data","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"role":"symbol","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:options:"}],"required":true,"platforms":[{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0","name":"iOS"},{"beta":false,"introducedAt":"8.0","deprecated":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"8.0","name":"Mac Catalyst","beta":false,"unavailable":false}],"externalID":"c:objc(pl)SDAnimatedImage(im)initWithData:scale:options:"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/init(data:scale:options:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/init(data:scale:options:)"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": [","kind":"text"},{"text":"SDImageCoderOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The data object containing the image data."}]}],"name":"data"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The scale factor to assume when interpreting the image data. Applying a scale factor of 1.0 results in an image whose size matches the pixel-based dimensions of the image. Applying a different scale factor changes the size of the image as reported by the ","type":"text"},{"type":"codeVoice","code":"size"},{"text":" property.","type":"text"}]}],"name":"scale"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary containing any animation decoding options.","type":"text"}]}],"name":"options"}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"We use this to create animated image instance for normal animation decoding."}]}],"style":"note","name":"Note"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/init(data:scale:options:)"},"abstract":[{"text":"Initializes and returns the image object with the specified data, scale factor and possible animation decoding options.","type":"text"}],"sections":[],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/init(data:scale:options:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"data","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:options:"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/init(data:scale:options:)","type":"topic","title":"init(data:scale:options:)","abstract":[{"text":"Initializes and returns the image object with the specified data, scale factor and possible animation decoding options.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/init(data:scale:options:)","required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol":{"title":"SDAnimatedImageProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOptions":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"SDImageCoderOptions"}],"title":"SDImageCoderOptions","url":"\/documentation\/sdwebimage\/sdimagecoderoptions","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithData:scale:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithData:scale:options:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithData:"},{"kind":"text","text":"("},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":") "},{"text":"scale","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOptions","text":"SDImageCoderOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions"},{"text":" *) ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The data object containing the image data.","type":"text"}]}],"name":"data"},{"name":"scale","content":[{"inlineContent":[{"text":"The scale factor to assume when interpreting the image data. Applying a scale factor of 1.0 results in an image whose size matches the pixel-based dimensions of the image. Applying a different scale factor changes the size of the image as reported by the ","type":"text"},{"type":"codeVoice","code":"size"},{"text":" property.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A dictionary containing any animation decoding options.","type":"text"}]}],"name":"options"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"op":"add","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"An initialized object","type":"text"}]}]},"path":"\/primaryContentSections\/2"},{"op":"replace","value":"initWithData:scale:options:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1init(data:scale:options:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithData:scale:options:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1init(data:scale:options:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/title","value":"SDAnimatedImage","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/fragments","op":"replace","value":[{"text":"SDAnimatedImage","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImage"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/navigatorTitle"},{"op":"replace","value":"SDImageCoderOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title"},{"op":"replace","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments"},{"value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}