{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/init(animatedCoder:scale:)"},"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Initializes the image with an animated coder. You can use the coder to decode the image frame later."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"text":"?(","kind":"text"},{"text":"animatedCoder","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","text":"SDAnimatedImageCoder"},{"text":", ","kind":"text"},{"text":"scale","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":")","kind":"text"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"animatedCoder","content":[{"inlineContent":[{"type":"text","text":"An animated coder which conform "},{"type":"codeVoice","code":"SDAnimatedImageCoder"},{"text":" protocol","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"The scale factor to assume when interpreting the image data. Applying a scale factor of 1.0 results in an image whose size matches the pixel-based dimensions of the image. Applying a different scale factor changes the size of the image as reported by the "},{"code":"size","type":"codeVoice"},{"type":"text","text":" property."}],"type":"paragraph"}],"name":"scale"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"name":"Note","content":[{"inlineContent":[{"text":"We use this with animated coder which conforms to ","type":"text"},{"type":"codeVoice","code":"SDProgressiveImageCoder"},{"text":" for progressive animation decoding.","type":"text"}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/init(animatedcoder:scale:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/init(animatedcoder:scale:)"]}],"sections":[],"metadata":{"required":true,"navigatorTitle":[{"kind":"identifier","text":"initWithAnimatedCoder:scale:"}],"platforms":[{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"iOS","beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"2.0","name":"Mac Catalyst"}],"modules":[{"name":"SDWebImage"}],"title":"init(animatedCoder:scale:)","externalID":"c:objc(pl)SDAnimatedImage(im)initWithAnimatedCoder:scale:","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"animatedCoder","kind":"externalParam"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","text":"SDAnimatedImageCoder","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"scale","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"kind":"text","text":")"}],"symbolKind":"init","role":"symbol","roleHeading":"Initializer"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol":{"title":"SDAnimatedImageProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/init(animatedCoder:scale:)":{"title":"init(animatedCoder:scale:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/init(animatedCoder:scale:)","type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/init(animatedcoder:scale:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"animatedCoder","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"SDAnimatedImageCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder"},{"text":", ","kind":"text"},{"text":"scale","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"initWithAnimatedCoder:scale:","kind":"identifier"}],"abstract":[{"type":"text","text":"Initializes the image with an animated coder. You can use the coder to decode the image frame later."}],"required":true,"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"value":"initWithAnimatedCoder:scale:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithAnimatedCoder:scale:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithAnimatedCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SDAnimatedImageCoder","text":"id<SDAnimatedImageCoder>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"animatedCoder","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":") "},{"text":"scale","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"An animated coder which conform "},{"type":"codeVoice","code":"SDAnimatedImageCoder"},{"type":"text","text":" protocol"}]}],"name":"animatedCoder"},{"name":"scale","content":[{"inlineContent":[{"type":"text","text":"The scale factor to assume when interpreting the image data. Applying a scale factor of 1.0 results in an image whose size matches the pixel-based dimensions of the image. Applying a different scale factor changes the size of the image as reported by the "},{"type":"codeVoice","code":"size"},{"text":" property.","type":"text"}],"type":"paragraph"}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"add","value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"An initialized object"}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","op":"replace","value":"SDAnimatedImageCoder"},{"op":"replace","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments"},{"value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/title","value":"SDAnimatedImage","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImage"}],"op":"replace"},{"value":"initWithAnimatedCoder:scale:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1init(animatedCoder:scale:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithAnimatedCoder:scale:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1init(animatedCoder:scale:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}