{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/isAllFramesLoaded","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(pl)SDAnimatedImage(py)allFramesLoaded","title":"isAllFramesLoaded","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isAllFramesLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"property","role":"symbol","required":true,"roleHeading":"Instance Property","navigatorTitle":[{"text":"allFramesLoaded","kind":"identifier"}],"modules":[{"name":"SDWebImage"}]},"sections":[],"abstract":[{"text":"Returns a Boolean value indicating whether all animated image frames are already pre-loaded into memory.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/isallframesloaded"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol\/isallframesloaded"]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAllFramesLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/isAllFramesLoaded":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"isAllFramesLoaded","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/isAllFramesLoaded","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/isallframesloaded","navigatorTitle":[{"text":"allFramesLoaded","kind":"identifier"}],"type":"topic","role":"symbol","title":"isAllFramesLoaded","abstract":[{"text":"Returns a Boolean value indicating whether all animated image frames are already pre-loaded into memory.","type":"text"}],"kind":"symbol","required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol":{"title":"SDAnimatedImageProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","value":"allFramesLoaded","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"allFramesLoaded","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":", ","kind":"text"},{"text":"getter","kind":"keyword"},{"kind":"text","text":"="},{"text":"isAllFramesLoaded","kind":"identifier"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL","text":"BOOL"},{"kind":"text","text":" "},{"kind":"identifier","text":"allFramesLoaded"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1isAllFramesLoaded\/title","op":"replace","value":"allFramesLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1isAllFramesLoaded\/fragments","value":[{"kind":"identifier","text":"allFramesLoaded"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/title","value":"SDAnimatedImage"},{"value":[{"kind":"identifier","text":"SDAnimatedImage"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/navigatorTitle","value":[{"text":"SDAnimatedImage","kind":"identifier"}]}]}]}