{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"internalParam","text":"lhs"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"internalParam","text":"rhs"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/Equatable-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"type":"text","text":"."}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/!=(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/!=(_:_:)"},"sections":[],"metadata":{"modules":[{"name":"SDWebImage","relatedModules":["Swift"]}],"title":"!=(_:_:)","extendedModule":"Swift","roleHeading":"Operator","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"symbolKind":"op","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@SDImageCoderDecodeSolution"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution":{"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"abstract":[{"text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility","type":"text"}],"title":"SDImageCoderDecodeSolution"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/!=(_:_:)":{"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/!=(_:_:)","kind":"symbol","role":"symbol","title":"!=(_:_:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/Equatable-Implementations":{"title":"Equatable Implementations","url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/equatable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/Equatable-Implementations","type":"topic","role":"collectionGroup","kind":"article","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/title","value":"SDImageCoderDecodeSolution"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/navigatorTitle","value":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}