{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/automatic"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/automatic"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/automatic","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"automatically choose the solution based on image format, hardware, OS version. This keep balance for compatibility and performance. Default after SDWebImage 5.13.0"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"title":"SDImageCoderDecodeSolution.automatic","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDImageCoderDecodeSolution@SDImageCoderDecodeSolutionAutomatic","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/automatic":{"role":"symbol","title":"SDImageCoderDecodeSolution.automatic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"abstract":[{"type":"text","text":"automatically choose the solution based on image format, hardware, OS version. This keep balance for compatibility and performance. Default after SDWebImage 5.13.0"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/automatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/automatic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution":{"role":"symbol","title":"SDImageCoderDecodeSolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"abstract":[{"type":"text","text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodeSolutionAutomatic"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1automatic\/title","value":"SDImageCoderDecodeSolutionAutomatic"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1automatic\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/title","value":"SDImageCoderDecodeSolution"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}