{"metadata":{"roleHeading":"Case","externalID":"c:@E@SDImageCoderDecodeSolution@SDImageCoderDecodeSolutionCoreGraphics","navigatorTitle":[{"text":"SDImageCoderDecodeSolutionCoreGraphics","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coreGraphics"}],"modules":[{"name":"SDWebImage"}],"title":"SDImageCoderDecodeSolution.coreGraphics","symbolKind":"case","role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"coreGraphics"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/coregraphics"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/coregraphics"]}],"kind":"symbol","abstract":[{"text":"always use CoreGraphics to draw on bitmap context and trigger decode. Best compatibility. Default before SDWebImage 5.13.0","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/coreGraphics","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/coreGraphics":{"abstract":[{"text":"always use CoreGraphics to draw on bitmap context and trigger decode. Best compatibility. Default before SDWebImage 5.13.0","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/coregraphics","title":"SDImageCoderDecodeSolution.coreGraphics","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"coreGraphics","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCoderDecodeSolutionCoreGraphics","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/coreGraphics","type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution":{"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"abstract":[{"text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility","type":"text"}],"title":"SDImageCoderDecodeSolution"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SDImageCoderDecodeSolutionCoreGraphics"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SDImageCoderDecodeSolutionCoreGraphics","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionCoreGraphics"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SDImageCoderDecodeSolutionCoreGraphics","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1coreGraphics\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1coreGraphics\/fragments","op":"replace","value":[{"text":"SDImageCoderDecodeSolutionCoreGraphics","kind":"identifier"}]},{"op":"replace","value":"SDImageCoderDecodeSolution","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/title"},{"op":"replace","value":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/navigatorTitle","value":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"op":"replace"}]}]}