{"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"topicSections":[{"generated":true,"title":"Operators","anchor":"Operators","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/!=(_:_:)"]}],"kind":"article","metadata":{"roleHeading":"API Collection","role":"collectionGroup","title":"Equatable Implementations","modules":[{"name":"SDWebImage"}]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/Equatable-Implementations","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/!=(_:_:)":{"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/!=(_:_:)","kind":"symbol","role":"symbol","title":"!=(_:_:)","abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"!="},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution":{"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"abstract":[{"text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility","type":"text"}],"title":"SDImageCoderDecodeSolution"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/title","value":"SDImageCoderDecodeSolution","op":"replace"},{"value":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/navigatorTitle"}]}]}