{"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/uikit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/uikit"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:@E@SDImageCoderDecodeSolution@SDImageCoderDecodeSolutionUIKit","title":"SDImageCoderDecodeSolution.uiKit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"uiKit"}],"symbolKind":"case","modules":[{"name":"SDWebImage"}],"roleHeading":"Case","navigatorTitle":[{"text":"SDImageCoderDecodeSolutionUIKit","kind":"identifier"}],"role":"symbol"},"abstract":[{"text":"available on iOS\/tvOS 15+, use UIKit’s new CGImageDecompressor\/CMPhoto to decode. Best performance. If failed, will fallback to CoreGraphics as well","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/uiKit","interfaceLanguage":"swift"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"uiKit","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution":{"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","type":"topic","kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"abstract":[{"text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility","type":"text"}],"title":"SDImageCoderDecodeSolution"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/uiKit":{"abstract":[{"text":"available on iOS\/tvOS 15+, use UIKit’s new CGImageDecompressor\/CMPhoto to decode. Best performance. If failed, will fallback to CoreGraphics as well","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/uikit","title":"SDImageCoderDecodeSolution.uiKit","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiKit","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCoderDecodeSolutionUIKit","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/uiKit","type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDImageCoderDecodeSolutionUIKit","op":"replace"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageCoderDecodeSolutionUIKit","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"SDImageCoderDecodeSolutionUIKit","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SDImageCoderDecodeSolution","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/title"},{"value":[{"text":"SDImageCoderDecodeSolution","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1uiKit\/title","value":"SDImageCoderDecodeSolutionUIKit"},{"value":[{"text":"SDImageCoderDecodeSolutionUIKit","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1uiKit\/fragments"}]}]}