{"metadata":{"role":"symbol","modules":[{"name":"SDWebImageYYPlugin"}],"navigatorTitle":[{"text":"SDImageYYCoder","kind":"identifier"}],"roleHeading":"Class","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageYYCoder","kind":"identifier"}],"externalID":"c:objc(cs)SDImageYYCoder","title":"SDImageYYCoder"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin"]]},"abstract":[{"type":"text","text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in "},{"type":"codeVoice","code":"YYImageType"},{"type":"text","text":"."}],"topicSections":[{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/decoder"]},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/shared"],"anchor":"Type-Properties"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)NSObject","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDAnimatedImageCoder","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDAnimatedImageProvider","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDImageCoder","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDProgressiveImageCoder","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/s7CVarArgP","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/s28CustomDebugStringConvertibleP","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/s23CustomStringConvertibleP","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/SQ","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/SH"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageYYCoder"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"type":"heading","anchor":"overview","text":"Overview","level":2},{"style":"note","name":"Note","content":[{"inlineContent":[{"type":"text","text":"This class conforms to "},{"code":"SDProgressiveImageCoder","type":"codeVoice"},{"text":" && ","type":"text"},{"code":"SDAnimatedImageCoder","type":"codeVoice"},{"type":"text","text":", supports static progressive decoding and animation decoding. However, it does not supports progressive animation decoding like "},{"type":"codeVoice","code":"SDImageGIFCoder"},{"type":"text","text":". Which means you can not use any method in "},{"type":"codeVoice","code":"SDAnimatedImageProvider"},{"type":"text","text":" protocol if you create the instance with "},{"type":"codeVoice","code":"initIncrementalWithOptions:"},{"text":" method.","type":"text"}],"type":"paragraph"}],"type":"aside"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder"]}],"kind":"symbol","references":{"doc://org.cocoapods.SDWebImageYYPlugin/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/SQ","type":"unresolvable"},"doc://org.cocoapods.SDWebImageYYPlugin/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(cs)NSObject","type":"unresolvable"},"doc://org.cocoapods.SDWebImageYYPlugin/objc(pl)SDProgressiveImageCoder":{"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDProgressiveImageCoder","title":"SDProgressiveImageCoder","type":"unresolvable"},"doc://org.cocoapods.SDWebImageYYPlugin/objc(pl)NSObject":{"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://org.cocoapods.SDWebImageYYPlugin/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/s7CVarArgP","type":"unresolvable"},"doc://org.cocoapods.SDWebImageYYPlugin/objc(pl)SDAnimatedImageCoder":{"title":"SDAnimatedImageCoder","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDAnimatedImageCoder","type":"unresolvable"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin":{"url":"\/documentation\/sdwebimageyyplugin","type":"topic","title":"SDWebImageYYPlugin","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","abstract":[],"role":"collection"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder":{"navigatorTitle":[{"kind":"identifier","text":"SDImageYYCoder"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageYYCoder"}],"url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder","abstract":[{"text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in ","type":"text"},{"code":"YYImageType","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder","role":"symbol","title":"SDImageYYCoder"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder/decoder":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decoder","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)YYImageDecoder","text":"YYImageDecoder"}],"url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/decoder","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/decoder","abstract":[{"text":"The wrapped ","type":"text"},{"code":"YYImageDecoder","type":"codeVoice"},{"text":" instance, to support static progressive and animation decoding.","type":"text"}],"title":"decoder","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"decoder"}],"role":"symbol"},"doc://org.cocoapods.SDWebImageYYPlugin/objc(pl)SDAnimatedImageProvider":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDAnimatedImageProvider","title":"SDWebImage.SDAnimatedImageProvider"},"doc://org.cocoapods.SDWebImageYYPlugin/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://org.cocoapods.SDWebImageYYPlugin/SH":{"type":"unresolvable","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/SH","title":"Swift.Hashable"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder/shared":{"abstract":[{"type":"text","text":"The shared coder instance."}],"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"SDImageYYCoder","preciseIdentifier":"c:objc(cs)SDImageYYCoder","kind":"typeIdentifier"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/shared","kind":"symbol","navigatorTitle":[{"text":"sharedCoder","kind":"identifier"}],"url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/shared"},"doc://org.cocoapods.SDWebImageYYPlugin/objc(pl)SDImageCoder":{"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDImageCoder","type":"unresolvable","title":"SDImageCoder"},"doc://org.cocoapods.SDWebImageYYPlugin/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Class","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"SDImageYYCoder","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageYYCoder"}],"op":"replace"},{"value":[{"text":"SDImageYYCoder","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/decoder"],"title":"Instance Properties"},{"identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/shared"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"op":"replace","path":"\/topicSections"},{"op":"replace","value":[{"identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDAnimatedImageCoder","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDImageCoder","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/objc(pl)SDProgressiveImageCoder"]}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageYYCoder"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/title","value":"SDImageYYCoder","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageYYCoder"}],"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageYYCoder"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1decoder\/title","op":"replace","value":"decoder"},{"value":[{"kind":"identifier","text":"decoder"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1decoder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1shared\/title","value":"sharedCoder"},{"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1shared\/fragments","value":[{"kind":"identifier","text":"sharedCoder"}],"op":"replace"}]}]}