{"kind":"symbol","abstract":[{"text":"Add a new coder to the end of coders array. Which has the highest priority.","type":"text"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/addCoder(_:)","interfaceLanguage":"swift"},"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addCoder","kind":"identifier"},{"text":"(any ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(cs)SDImageCodersManager(im)addCoder:","title":"addCoder(_:)","navigatorTitle":[{"text":"addCoder:","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"addCoder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"coder"},{"kind":"text","text":": any "},{"text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]},{"parameters":[{"name":"coder","content":[{"inlineContent":[{"type":"text","text":"Coder"}],"type":"paragraph"}]}],"kind":"parameters"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager\/addcoder(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager\/addcoder(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager"]]},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/addCoder(_:)":{"abstract":[{"text":"Add a new coder to the end of coders array. Which has the highest priority.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/addCoder(_:)","navigatorTitle":[{"kind":"identifier","text":"addCoder:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"addCoder","kind":"identifier"},{"text":"(any ","kind":"text"},{"text":"SDImageCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"text":")","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/addcoder(_:)","type":"topic","kind":"symbol","role":"symbol","title":"addCoder(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager":{"navigatorTitle":[{"text":"SDImageCodersManager","kind":"identifier"}],"title":"SDImageCodersManager","kind":"symbol","abstract":[{"type":"text","text":"Global object holding the array of coders, so that we avoid passing them from object to object."},{"text":" ","type":"text"},{"type":"text","text":"Uses a priority queue behind scenes, which means the latest added coders have the highest priority."},{"type":"text","text":" "},{"text":"This is done so when encoding\/decoding something, we go through the list and ask each coder if they can handle the current data.","type":"text"},{"text":" ","type":"text"},{"text":"That way, users can add their custom coders while preserving our existing prebuilt ones","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCodersManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"type":"topic","title":"SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder","navigatorTitle":[{"text":"SDImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the image coder protocol to provide custom image decoding\/encoding.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods are all required to implement."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"addCoder:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"addCoder:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"text":"addCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SDImageCoder","text":"id<SDImageCoder>","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"coder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Coder"}]}]}]}},{"value":"addCoder:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1addCoder(_:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1addCoder(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addCoder:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/title","value":"SDImageCodersManager","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCodersManager"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/navigatorTitle","value":[{"text":"SDImageCodersManager","kind":"identifier"}],"op":"replace"},{"value":"SDImageCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","op":"replace"},{"value":[{"text":"SDImageCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments"},{"value":[{"text":"SDImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/navigatorTitle","op":"replace"}]}]}