{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder","text":"SDImageCoder"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager\/coders"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager\/coders"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/coders","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"All coders in coders manager. The coders array is a priority queue, which means the later added coder will have the highest priority"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"kind":"text","text":"]?"}],"title":"coders","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCodersManager(py)coders","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"coders"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager":{"role":"symbol","title":"SDImageCodersManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"}],"abstract":[{"type":"text","text":"Global object holding the array of coders, so that we avoid passing them from object to object."},{"type":"text","text":" "},{"type":"text","text":"Uses a priority queue behind scenes, which means the latest added coders have the highest priority."},{"type":"text","text":" "},{"type":"text","text":"This is done so when encoding\/decoding something, we go through the list and ask each coder if they can handle the current data."},{"type":"text","text":" "},{"type":"text","text":"That way, users can add their custom coders while preserving our existing prebuilt ones"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCodersManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"role":"symbol","title":"SDImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom image decoding\/encoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/coders":{"role":"symbol","title":"coders","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"All coders in coders manager. The coders array is a priority queue, which means the later added coder will have the highest priority"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/coders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coders"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/coders"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"coders"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"coders"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<SDImageCoder>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" *"},{"kind":"identifier","text":"coders"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/title","value":"SDImageCodersManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/fragments","value":[{"kind":"identifier","text":"SDImageCodersManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments","value":[{"kind":"identifier","text":"SDImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1coders\/title","value":"coders"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1coders\/fragments","value":[{"kind":"identifier","text":"coders"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}