{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","preciseIdentifier":"c:objc(cs)SDImageCodersManager","text":"SDImageCodersManager"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/shared","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns the global shared coders manager instance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCodersManager","preciseIdentifier":"c:objc(cs)SDImageCodersManager"}],"title":"shared","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCodersManager(cpy)sharedManager","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"sharedManager"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCodersManager","preciseIdentifier":"c:objc(cs)SDImageCodersManager"}],"abstract":[{"type":"text","text":"Returns the global shared coders manager instance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/shared"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager":{"role":"symbol","title":"SDImageCodersManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"}],"abstract":[{"type":"text","text":"Global object holding the array of coders, so that we avoid passing them from object to object."},{"type":"text","text":" "},{"type":"text","text":"Uses a priority queue behind scenes, which means the latest added coders have the highest priority."},{"type":"text","text":" "},{"type":"text","text":"This is done so when encoding\/decoding something, we go through the list and ask each coder if they can handle the current data."},{"type":"text","text":" "},{"type":"text","text":"That way, users can add their custom coders while preserving our existing prebuilt ones"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCodersManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedManager"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","preciseIdentifier":"c:objc(cs)SDImageCodersManager","text":"SDImageCodersManager"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedManager"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1shared\/title","value":"sharedManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1shared\/fragments","value":[{"kind":"identifier","text":"sharedManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/title","value":"SDImageCodersManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/fragments","value":[{"kind":"identifier","text":"SDImageCodersManager"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}