{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"optionsProcessorWithBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDWebImageOptionsResult *(^)(NSURL *, enum SDWebImageOptions, NSDictionary<NSString *,id> *)","preciseIdentifier":"c:BF*$objc(cs)SDWebImageOptionsResult(#*$objc(cs)NSURL#$@E@SDWebImageOptions#*Q$objc(cs)NSDictionary)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptionsprocessor-swift.class\/optionsprocessorwithblock:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class\/optionsProcessorWithBlock:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"optionsProcessorWithBlock:"}],"title":"optionsProcessorWithBlock:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImageOptionsProcessor(cm)optionsProcessorWithBlock:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"optionsProcessorWithBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptionsProcessor-swift.class/optionsProcessorWithBlock:":{"role":"symbol","title":"optionsProcessorWithBlock:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"optionsProcessorWithBlock:"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class\/optionsProcessorWithBlock:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"optionsProcessorWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptionsprocessor-swift.class\/optionsprocessorwithblock:"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptionsProcessor-swift.class":{"role":"symbol","title":"SDWebImageOptionsProcessor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptionsProcessor"}],"abstract":[{"type":"text","text":"A options processor class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptionsProcessor"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptionsprocessor-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessor-swift.class\/title","value":"SDWebImageOptionsProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessor-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptionsProcessor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}