{"primaryContentSections":[{"kind":"content","content":[{"anchor":"Overview","level":2,"type":"heading","text":"Overview"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageswiftui"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimageswiftui"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ImageManager","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ImagePlayer","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ProgressIndicatorWrapper"]},{"title":"Protocols","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/IndicatorReportable"]},{"title":"Structures","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ActivityIndicator","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/Indicator","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/IndicatorViewModifier","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ProgressIndicator","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/WebImage"]},{"title":"Type Aliases","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/PlatformImage","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/PlatformView","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/PlatformViewRepresentable"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SDWebImageSwiftUI","title":"SDWebImageSwiftUI","symbolKind":"module","role":"collection","modules":[{"name":"SDWebImageSwiftUI"}]},"hierarchy":{"paths":[[]]},"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/PlatformView":{"role":"symbol","title":"PlatformView","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlatformView"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/PlatformView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlatformView"}],"url":"\/documentation\/sdwebimageswiftui\/platformview"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/IndicatorReportable":{"role":"symbol","title":"IndicatorReportable","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndicatorReportable"}],"abstract":[{"type":"text","text":"A protocol to report indicator progress"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/IndicatorReportable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndicatorReportable"}],"url":"\/documentation\/sdwebimageswiftui\/indicatorreportable"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage":{"role":"symbol","title":"AnimatedImage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImage"}],"abstract":[{"type":"text","text":"A Image View type to load image from url, data or bundle. Supports animated and static image format."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImage"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimage"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator":{"role":"symbol","title":"AnimatedImageCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageCoordinator"}],"abstract":[{"type":"text","text":"A coordinator object used for "},{"type":"codeVoice","code":"AnimatedImage"},{"type":"text","text":"native view  bridge for UIKit\/AppKit."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageCoordinator"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/ProgressIndicatorWrapper":{"role":"symbol","title":"ProgressIndicatorWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressIndicatorWrapper"}],"abstract":[{"type":"text","text":"Use wrapper to solve the "},{"type":"codeVoice","code":"UIProgressView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSProgressIndicator"},{"type":"text","text":" frame origin NaN crash (SwiftUI’s bug)"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ProgressIndicatorWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressIndicatorWrapper"}],"url":"\/documentation\/sdwebimageswiftui\/progressindicatorwrapper"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","title":"AnimatedImageViewWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/SDWebImageSwiftUIVersionString":{"role":"symbol","title":"SDWebImageSwiftUIVersionString","fragments":[{"kind":"identifier","text":"SDWebImageSwiftUIVersionString"}],"abstract":[{"type":"text","text":"Project version string for SDWebImageSwiftUI."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/SDWebImageSwiftUIVersionString","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui\/sdwebimageswiftuiversionstring"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/PlatformViewRepresentable":{"role":"symbol","title":"PlatformViewRepresentable","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlatformViewRepresentable"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/PlatformViewRepresentable","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlatformViewRepresentable"}],"url":"\/documentation\/sdwebimageswiftui\/platformviewrepresentable"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/IndicatorViewModifier":{"role":"symbol","title":"IndicatorViewModifier","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"IndicatorViewModifier"}],"abstract":[{"type":"text","text":"A implementation detail View Modifier with indicator"},{"type":"text","text":" "},{"type":"text","text":"SwiftUI View Modifier construced by using a internal View type which modify the "},{"type":"codeVoice","code":"body"},{"type":"text","text":" "},{"type":"text","text":"It use type system to represent the view hierarchy, and Swift "},{"type":"codeVoice","code":"some View"},{"type":"text","text":" syntax to hide the type detail for users"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/IndicatorViewModifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"IndicatorViewModifier"}],"url":"\/documentation\/sdwebimageswiftui\/indicatorviewmodifier"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/ActivityIndicator":{"role":"symbol","title":"ActivityIndicator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ActivityIndicator"}],"abstract":[{"type":"text","text":"An activity indicator (system style)"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ActivityIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ActivityIndicator"}],"url":"\/documentation\/sdwebimageswiftui\/activityindicator"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/ImagePlayer":{"role":"symbol","title":"ImagePlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImagePlayer"}],"abstract":[{"type":"text","text":"A Image observable object for handle aniamted image playback. This is used to avoid "},{"type":"codeVoice","code":"@State"},{"type":"text","text":" update may capture the View struct type and cause memory leak."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ImagePlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImagePlayer"}],"url":"\/documentation\/sdwebimageswiftui\/imageplayer"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"role":"collection","title":"SDWebImageSwiftUI","abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/ImageManager":{"role":"symbol","title":"ImageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"ImageManager"}],"abstract":[{"type":"text","text":"A Image observable object for handle image load process. This drive the Source of Truth for image loading status."},{"type":"text","text":" "},{"type":"text","text":"You can use "},{"type":"codeVoice","code":"@ObservedObject"},{"type":"text","text":" to associate each instance of manager to your View type, which update your view’s body from SwiftUI framework when image was loaded."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ImageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ImageManager"}],"url":"\/documentation\/sdwebimageswiftui\/imagemanager"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/Indicator":{"role":"symbol","title":"Indicator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"Indicator"}],"abstract":[{"type":"text","text":"A  type to build the indicator"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/Indicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Indicator"}],"url":"\/documentation\/sdwebimageswiftui\/indicator"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/SDWebImageSwiftUIVersionNumber":{"role":"symbol","title":"SDWebImageSwiftUIVersionNumber","fragments":[{"kind":"identifier","text":"SDWebImageSwiftUIVersionNumber"}],"abstract":[{"type":"text","text":"Project version number for SDWebImageSwiftUI."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/SDWebImageSwiftUIVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui\/sdwebimageswiftuiversionnumber"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/PlatformImage":{"role":"symbol","title":"PlatformImage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlatformImage"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/PlatformImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlatformImage"}],"url":"\/documentation\/sdwebimageswiftui\/platformimage"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/ProgressIndicator":{"role":"symbol","title":"ProgressIndicator","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"ProgressIndicator"}],"abstract":[{"type":"text","text":"A progress bar indicator (system style)"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ProgressIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ProgressIndicator"}],"url":"\/documentation\/sdwebimageswiftui\/progressindicator"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/WebImage":{"role":"symbol","title":"WebImage","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"WebImage"}],"abstract":[{"type":"text","text":"A Image View type to load image from url. Supports static\/animated image format."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/WebImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"WebImage"}],"url":"\/documentation\/sdwebimageswiftui\/webimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/ProgressIndicatorWrapper"]},{"title":"Variables","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/SDWebImageSwiftUIVersionNumber","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/SDWebImageSwiftUIVersionString"]}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/title","value":"AnimatedImageCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/fragments","value":[{"kind":"identifier","text":"AnimatedImageCoordinator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1ProgressIndicatorWrapper\/title","value":"ProgressIndicatorWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1ProgressIndicatorWrapper\/fragments","value":[{"kind":"identifier","text":"ProgressIndicatorWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title","value":"AnimatedImageViewWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments","value":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}