{"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageyyplugin"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimageyyplugin"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"SDWebImageYYPlugin","symbolKind":"module","title":"SDWebImageYYPlugin","modules":[{"name":"SDWebImageYYPlugin"}],"role":"collection","roleHeading":"Framework"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[[]]},"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","interfaceLanguage":"swift"},"topicSections":[{"anchor":"Classes","generated":true,"identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"],"title":"Classes"}],"references":{"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin":{"type":"topic","abstract":[],"role":"collection","title":"SDWebImageYYPlugin","kind":"symbol","url":"\/documentation\/sdwebimageyyplugin","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDWebImageYYPluginVersionNumber":{"kind":"symbol","role":"symbol","type":"topic","abstract":[],"title":"SDWebImageYYPluginVersionNumber","url":"\/documentation\/sdwebimageyyplugin\/sdwebimageyypluginversionnumber","fragments":[{"kind":"identifier","text":"SDWebImageYYPluginVersionNumber"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDWebImageYYPluginVersionNumber"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder":{"type":"topic","abstract":[{"text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in ","type":"text"},{"type":"codeVoice","code":"YYImageType"},{"text":".","type":"text"}],"role":"symbol","title":"SDImageYYCoder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageYYCoder"}],"navigatorTitle":[{"text":"SDImageYYCoder","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDWebImageYYPluginVersionString":{"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDWebImageYYPluginVersionString","abstract":[],"role":"symbol","title":"SDWebImageYYPluginVersionString","kind":"symbol","fragments":[{"text":"SDWebImageYYPluginVersionString","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimageyyplugin\/sdwebimageyypluginversionstring"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"],"anchor":"Classes","title":"Classes","generated":true},{"generated":true,"title":"Variables","anchor":"Variables","identifiers":["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDWebImageYYPluginVersionNumber","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDWebImageYYPluginVersionString"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/title","value":"SDImageYYCoder"},{"value":[{"text":"SDImageYYCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/navigatorTitle","value":[{"text":"SDImageYYCoder","kind":"identifier"}]}]}]}