{"variants":[{"paths":["\/documentation\/sdwebimagewebpcoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagewebpcoder"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"identifier":{"url":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder","interfaceLanguage":"swift"},"topicSections":[{"title":"Classes","identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder"]}],"kind":"symbol","metadata":{"roleHeading":"Framework","externalID":"SDWebImageWebPCoder","title":"SDWebImageWebPCoder","symbolKind":"module","role":"collection","modules":[{"name":"SDWebImageWebPCoder"}]},"hierarchy":{"paths":[[]]},"references":{"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPPartitionLimit":{"role":"symbol","title":"SDImageCoderEncodeWebPPartitionLimit","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPPartitionLimit"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Quality degradation allowed to fit the 512k limit on"},{"type":"text","text":" "},{"type":"text","text":"Prediction modes coding (0: no degradation, 100: maximum possible degradation)."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPartitionLimit","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebppartitionlimit"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPAlphaQuality":{"role":"symbol","title":"SDImageCoderEncodeWebPAlphaQuality","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPAlphaQuality"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Between 0 (smallest size) and 100 (lossless)."},{"type":"text","text":" "},{"type":"text","text":"Default is 100."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAlphaQuality","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpalphaquality"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder":{"role":"collection","title":"SDWebImageWebPCoder","abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPFilterType":{"role":"symbol","title":"SDImageCoderEncodeWebPFilterType","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPFilterType"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Filtering type: 0 = simple, 1 = strong (only used If filter_strength > 0 or autofilter > 0)"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPFilterType","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpfiltertype"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPPartitions":{"role":"symbol","title":"SDImageCoderEncodeWebPPartitions","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPPartitions"}],"abstract":[{"type":"text","text":"Integer"},{"type":"text","text":" "},{"type":"text","text":"Log2(number of token partitions) in [0..3]"},{"type":"text","text":" "},{"type":"text","text":"Default is set to 0 for easier progressive decoding."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPartitions","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebppartitions"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder":{"role":"symbol","title":"SDImageWebPCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageWebPCoder"}],"abstract":[{"type":"text","text":"Built in coder that supports WebP and animated WebP"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageWebPCoder"}],"url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPTargetPSNR":{"role":"symbol","title":"SDImageCoderEncodeWebPTargetPSNR","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPTargetPSNR"}],"abstract":[{"type":"text","text":"Float value"},{"type":"text","text":" "},{"type":"text","text":"if non-zero, specifies the minimal distortion to try to achieve. Takes precedence over target_size."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPTargetPSNR","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebptargetpsnr"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPPass":{"role":"symbol","title":"SDImageCoderEncodeWebPPass","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPPass"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Number of entropy-analysis passes (in [1..10])"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPass","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebppass"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPSegments":{"role":"symbol","title":"SDImageCoderEncodeWebPSegments","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPSegments"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"if non-zero, specifies the minimal distortion to try to achieve. Takes precedence over target_size."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPSegments","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpsegments"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPLowMemory":{"role":"symbol","title":"SDImageCoderEncodeWebPLowMemory","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPLowMemory"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"If set, reduce memory usage (but increase CPU use)."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPLowMemory","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebplowmemory"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPAlphaFiltering":{"role":"symbol","title":"SDImageCoderEncodeWebPAlphaFiltering","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPAlphaFiltering"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Predictive filtering method for alpha plane. 0: none, 1: fast, 2: best. Default if 1."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAlphaFiltering","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpalphafiltering"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDWebImageWebPCoderVersionString":{"role":"symbol","title":"SDWebImageWebPCoderVersionString","fragments":[{"kind":"identifier","text":"SDWebImageWebPCoderVersionString"}],"abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDWebImageWebPCoderVersionString","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdwebimagewebpcoderversionstring"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPFilterStrength":{"role":"symbol","title":"SDImageCoderEncodeWebPFilterStrength","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPFilterStrength"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Range: [0 = off .. 100 = strongest]"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPFilterStrength","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpfilterstrength"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPShowCompressed":{"role":"symbol","title":"SDImageCoderEncodeWebPShowCompressed","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPShowCompressed"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"If true, export the compressed picture back."},{"type":"text","text":" "},{"type":"text","text":"In-loop filtering is not applied."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPShowCompressed","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpshowcompressed"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDWebImageWebPCoderVersionNumber":{"role":"symbol","title":"SDWebImageWebPCoderVersionNumber","fragments":[{"kind":"identifier","text":"SDWebImageWebPCoderVersionNumber"}],"abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDWebImageWebPCoderVersionNumber","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdwebimagewebpcoderversionnumber"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPSnsStrength":{"role":"symbol","title":"SDImageCoderEncodeWebPSnsStrength","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPSnsStrength"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Spatial Noise Shaping. 0=off, 100=maximum."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPSnsStrength","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpsnsstrength"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPFilterSharpness":{"role":"symbol","title":"SDImageCoderEncodeWebPFilterSharpness","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPFilterSharpness"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"range: [0 = off .. 7 = least sharp]"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPFilterSharpness","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpfiltersharpness"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPAutofilter":{"role":"symbol","title":"SDImageCoderEncodeWebPAutofilter","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPAutofilter"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Auto adjust filter’s strength [0 = off, 1 = on]"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAutofilter","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpautofilter"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPUseSharpYuv":{"role":"symbol","title":"SDImageCoderEncodeWebPUseSharpYuv","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPUseSharpYuv"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"if needed, use sharp (and slow) RGB->YUV conversion"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPUseSharpYuv","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpusesharpyuv"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPMethod":{"role":"symbol","title":"SDImageCoderEncodeWebPMethod","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPMethod"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Quality\/speed trade-off (0=fast, 6=slower-better)"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPMethod","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpmethod"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPThreadLevel":{"role":"symbol","title":"SDImageCoderEncodeWebPThreadLevel","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPThreadLevel"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"If non-zero, try and use multi-threaded encoding."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPThreadLevel","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpthreadlevel"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPAlphaCompression":{"role":"symbol","title":"SDImageCoderEncodeWebPAlphaCompression","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPAlphaCompression"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Algorithm for encoding the alpha plane (0 = none, 1 = compressed with WebP lossless). Default is 1."}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAlphaCompression","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebpalphacompression"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageCoderEncodeWebPPreprocessing":{"role":"symbol","title":"SDImageCoderEncodeWebPPreprocessing","fragments":[{"kind":"identifier","text":"SDImageCoderEncodeWebPPreprocessing"}],"abstract":[{"type":"text","text":"Integer value"},{"type":"text","text":" "},{"type":"text","text":"Preprocessing filter (0=none, 1=segment-smooth)"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPreprocessing","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagecoderencodewebppreprocessing"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/topicSections","value":[{"title":"Classes","identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder"]},{"title":"Variables","identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAlphaCompression","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAlphaFiltering","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAlphaQuality","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPAutofilter","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPFilterSharpness","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPFilterStrength","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPFilterType","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPLowMemory","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPMethod","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPartitionLimit","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPartitions","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPass","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPPreprocessing","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPSegments","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPShowCompressed","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPSnsStrength","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPTargetPSNR","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPThreadLevel","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageCoderEncodeWebPUseSharpYuv","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDWebImageWebPCoderVersionNumber","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDWebImageWebPCoderVersionString"]}]},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder\/title","value":"SDImageWebPCoder"},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder\/fragments","value":[{"kind":"identifier","text":"SDImageWebPCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}