{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"final"},{"kind":"text","text":" "},{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageCoordinator"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimagecoordinator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimageswiftui\/animatedimagecoordinator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)NSObject","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s7CVarArgP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s28CustomDebugStringConvertibleP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s23CustomStringConvertibleP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SQ","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A coordinator object used for "},{"type":"codeVoice","code":"AnimatedImage"},{"type":"text","text":"native view  bridge for UIKit\/AppKit."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AnimatedImageCoordinator"}],"role":"symbol","title":"AnimatedImageCoordinator","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageCoordinator"}],"symbolKind":"class","externalID":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageCoordinator","modules":[{"name":"SDWebImageSwiftUI"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.15","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"watchOS","introducedAt":"6.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/object","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/userInfo"]}],"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SQ"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)NSObject"},"doc://com.dreampiggy.SDWebImageSwiftUI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SH"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator/object":{"role":"symbol","title":"object","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Any user-provided object for actual coordinator, such as delegate method, taget-action"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/object","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator\/object"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator":{"role":"symbol","title":"AnimatedImageCoordinator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageCoordinator"}],"abstract":[{"type":"text","text":"A coordinator object used for "},{"type":"codeVoice","code":"AnimatedImage"},{"type":"text","text":"native view  bridge for UIKit\/AppKit."}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageCoordinator"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator/init":{"role":"symbol","title":"init","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"init"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/init","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"init"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator\/init"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator/userInfo":{"role":"symbol","title":"userInfo","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"userInfo"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"Any user-provided info stored into coordinator, such as status value used for coordinator"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/userInfo","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator\/userinfo"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"role":"collection","title":"SDWebImageSwiftUI","abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui"},"doc://com.dreampiggy.SDWebImageSwiftUI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s23CustomStringConvertibleP"},"doc://com.dreampiggy.SDWebImageSwiftUI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s7CVarArgP"},"doc://com.dreampiggy.SDWebImageSwiftUI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s28CustomDebugStringConvertibleP"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(cs)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AnimatedImageCoordinator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AnimatedImageCoordinator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AnimatedImageCoordinator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/init"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageCoordinator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/title","value":"AnimatedImageCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/fragments","value":[{"kind":"identifier","text":"AnimatedImageCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}