{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(cs)UIView"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)NSCoding","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)NSObject","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)CALayerDelegate","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s7CVarArgP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s28CustomDebugStringConvertibleP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s23CustomStringConvertibleP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SQ","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SH","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s8SendableP","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIAppearance","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIAppearanceContainer","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UICoordinateSpace","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIDynamicItem","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIFocusEnvironment","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIFocusItem","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIFocusItemContainer","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UILargeContentViewerItem","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UITraitEnvironment","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIUserActivityRestoring"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"role":"symbol","title":"AnimatedImageViewWrapper","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"symbolKind":"class","externalID":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper","modules":[{"name":"SDWebImageSwiftUI"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"macOS","introducedAt":"10.15","deprecated":false},{"beta":false,"unavailable":false,"name":"tvOS","introducedAt":"13.0","deprecated":false},{"beta":false,"unavailable":false,"name":"watchOS","introducedAt":"6.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(coder:)","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(frame:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/intrinsicContentSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/draw(_:)","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/layoutSubviews()"]}],"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIFocusEnvironment":{"type":"unresolvable","title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIFocusEnvironment"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIAppearanceContainer":{"type":"unresolvable","title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIAppearanceContainer"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)CALayerDelegate":{"type":"unresolvable","title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)CALayerDelegate"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIAccessibilityIdentification":{"type":"unresolvable","title":"UIKit.UIAccessibilityIdentification","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIAccessibilityIdentification"},"doc://com.dreampiggy.SDWebImageSwiftUI/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SH"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIAppearance":{"type":"unresolvable","title":"UIKit.UIAppearance","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIAppearance"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(cs)UIView":{"type":"unresolvable","title":"UIView","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(cs)UIView"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/intrinsicContentSize":{"role":"symbol","title":"intrinsicContentSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/intrinsicContentSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/intrinsiccontentsize"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)NSObject"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIFocusItem":{"type":"unresolvable","title":"UIKit.UIFocusItem","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIFocusItem"},"doc://com.dreampiggy.SDWebImageSwiftUI/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s23CustomStringConvertibleP"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"role":"collection","title":"SDWebImageSwiftUI","abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimageswiftui"},"doc://com.dreampiggy.SDWebImageSwiftUI/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s7CVarArgP"},"doc://com.dreampiggy.SDWebImageSwiftUI/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s8SendableP"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIFocusItemContainer":{"type":"unresolvable","title":"UIKit.UIFocusItemContainer","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIFocusItemContainer"},"doc://com.dreampiggy.SDWebImageSwiftUI/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/s28CustomDebugStringConvertibleP"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/init(coder:)":{"role":"symbol","title":"init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"coder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSCoder","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(coder:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithCoder:"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/init(coder:)"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)NSCoding":{"type":"unresolvable","title":"Foundation.NSCoding","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)NSCoding"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","title":"UIKit.UIUserActivityRestoring","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIUserActivityRestoring"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UILargeContentViewerItem":{"type":"unresolvable","title":"UIKit.UILargeContentViewerItem","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UILargeContentViewerItem"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/init(frame:)":{"role":"symbol","title":"init(frame:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"frame"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(frame:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithFrame:"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/init(frame:)"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIDynamicItem":{"type":"unresolvable","title":"UIKit.UIDynamicItem","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIDynamicItem"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIActivityItemsConfigurationProviding":{"type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIActivityItemsConfigurationProviding"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","title":"AnimatedImageViewWrapper","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UITraitEnvironment":{"type":"unresolvable","title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UITraitEnvironment"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UICoordinateSpace":{"type":"unresolvable","title":"UIKit.UICoordinateSpace","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UICoordinateSpace"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIPasteConfigurationSupporting":{"type":"unresolvable","title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIPasteConfigurationSupporting"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/draw(_:)":{"role":"symbol","title":"draw(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"draw"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/draw(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"drawRect:"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/draw(_:)"},"doc://com.dreampiggy.SDWebImageSwiftUI/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/SQ"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIPopoverPresentationControllerSourceItem":{"type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIPopoverPresentationControllerSourceItem"},"doc://com.dreampiggy.SDWebImageSwiftUI/objc(pl)UIResponderStandardEditActions":{"type":"unresolvable","title":"UIKit.UIResponderStandardEditActions","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/objc(pl)UIResponderStandardEditActions"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/layoutSubviews()":{"role":"symbol","title":"layoutSubviews()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"layoutSubviews"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/layoutSubviews()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"layoutSubviews"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/layoutsubviews()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"AnimatedImageViewWrapper"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/intrinsicContentSize"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/draw(_:)","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(coder:)","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(frame:)","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/layoutSubviews()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"AnimatedImageViewWrapper"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1intrinsicContentSize\/title","value":"intrinsicContentSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1init(coder:)\/title","value":"initWithCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1init(coder:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1init(frame:)\/title","value":"initWithFrame:"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1init(frame:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithFrame:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title","value":"AnimatedImageViewWrapper"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments","value":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1draw(_:)\/title","value":"drawRect:"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1draw(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"drawRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1layoutSubviews()\/title","value":"layoutSubviews"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1layoutSubviews()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"layoutSubviews"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}