{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifiedResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierprotocol\/modifiedresponse(with:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierprotocol\/modifiedresponse(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol\/modifiedResponse(with:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Modify the original URL response and return a new response. You can use this to check MIME-Type, mock server response, etc."}],"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"modifiedResponseWithResponse:"}],"role":"symbol","title":"modifiedResponse(with:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifiedResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?"}],"symbolKind":"method","externalID":"c:objc(pl)SDWebImageDownloaderResponseModifier(im)modifiedResponseWithResponse:","required":true,"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"2.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifierProtocol":{"role":"symbol","title":"SDWebImageDownloaderResponseModifierProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for downloader response modifier."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the downloader response modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifierProtocol/modifiedResponse(with:)":{"navigatorTitle":[{"kind":"identifier","text":"modifiedResponseWithResponse:"}],"role":"symbol","title":"modifiedResponse(with:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"modifiedResponse"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Modify the original URL response and return a new response. You can use this to check MIME-Type, mock server response, etc."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol\/modifiedResponse(with:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierprotocol\/modifiedresponse(with:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"modifiedResponseWithResponse:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifiedResponseWithResponse:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSURLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"modifiedResponseWithResponse:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"response"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/title","value":"SDWebImageDownloaderResponseModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol~1modifiedResponse(with:)\/title","value":"modifiedResponseWithResponse:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol~1modifiedResponse(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifiedResponseWithResponse:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}