{"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"Schedules a block asynchronously for execution."}],"metadata":{"symbolKind":"method","roleHeading":"Instance Method","title":"async(_:)","externalID":"c:objc(cs)SDCallbackQueue(im)async:","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"async","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"async:","kind":"identifier"}],"role":"symbol"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/async(_:)"]},{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/async(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/async(_:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"async"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"block"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" () -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"block","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block that contains the work to perform."}]}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"url":"\/documentation\/sdwebimage\/sdcallbackqueue","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}],"title":"SDCallbackQueue","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/async(_:)":{"navigatorTitle":[{"text":"async:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/async(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"async","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"title":"async(_:)","abstract":[{"type":"text","text":"Schedules a block asynchronously for execution."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/async(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"async:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"async:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"async:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv()","text":"void (^)(void)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"block"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block that contains the work to perform."}]}],"name":"block"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","value":"SDCallbackQueue"},{"value":[{"kind":"identifier","text":"SDCallbackQueue"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments"},{"value":[{"kind":"identifier","text":"SDCallbackQueue"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/navigatorTitle"},{"op":"replace","value":"async:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1async(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1async(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"async:"}]}]}]}