{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/current"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/current"]}],"metadata":{"role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"current","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"currentQueue"}],"title":"current","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDCallbackQueue(cpy)currentQueue","symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/current"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"current","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDCallbackQueue","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","text":"SDCallbackQueue"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"abstract":[{"text":"The caller current queue. Using ","type":"text"},{"type":"codeVoice","code":"dispatch_get_current_queue"},{"text":". This is not a dynamic value and only keep the first call time queue.","type":"text"},{"text":" ","type":"text"},{"text":"The policy defaults to ","type":"text"},{"code":"SDCallbackPolicySafeExecute","type":"codeVoice"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"url":"\/documentation\/sdwebimage\/sdcallbackqueue","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}],"title":"SDCallbackQueue","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/current":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"current"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue"}],"title":"current","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/current","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/current","abstract":[{"type":"text","text":"The caller current queue. Using "},{"type":"codeVoice","code":"dispatch_get_current_queue"},{"type":"text","text":". This is not a dynamic value and only keep the first call time queue."},{"text":" ","type":"text"},{"type":"text","text":"The policy defaults to "},{"code":"SDCallbackPolicySafeExecute","type":"codeVoice"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentQueue"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"currentQueue","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"currentQueue"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SDCallbackQueue","preciseIdentifier":"c:objc(cs)SDCallbackQueue","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"},{"kind":"text","text":" * "},{"text":"currentQueue","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","value":"SDCallbackQueue"},{"value":[{"kind":"identifier","text":"SDCallbackQueue"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/navigatorTitle","value":[{"kind":"identifier","text":"SDCallbackQueue"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1current\/title","value":"currentQueue","op":"replace"},{"value":[{"kind":"identifier","text":"currentQueue"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1current\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}