{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"global"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/global"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/global"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/global","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The global concurrent queue (user-initiated QoS). Using "},{"type":"codeVoice","code":"dispatch_get_global_queue"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"global"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDCallbackQueue","preciseIdentifier":"c:objc(cs)SDCallbackQueue"}],"title":"global","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDCallbackQueue(cpy)globalQueue","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"globalQueue"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"role":"symbol","title":"SDCallbackQueue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDCallbackQueue"}],"abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Manager"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Loader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"url":"\/documentation\/sdwebimage\/sdcallbackqueue"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/global":{"role":"symbol","title":"global","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"global"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDCallbackQueue","preciseIdentifier":"c:objc(cs)SDCallbackQueue"}],"abstract":[{"type":"text","text":"The global concurrent queue (user-initiated QoS). Using "},{"type":"codeVoice","code":"dispatch_get_global_queue"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/global","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"globalQueue"}],"url":"\/documentation\/sdwebimage\/sdcallbackqueue\/global"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"globalQueue"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"globalQueue"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue"},{"kind":"text","text":" * "},{"kind":"identifier","text":"globalQueue"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","value":"SDCallbackQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","value":[{"kind":"identifier","text":"SDCallbackQueue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1global\/title","value":"globalQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1global\/fragments","value":[{"kind":"identifier","text":"globalQueue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}