{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dispatchQueue"},{"kind":"text","text":" "},{"kind":"internalParam","text":"queue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"queue","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The GCD queue, should not be NULL"}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/init(dispatchqueue:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/init(dispatchqueue:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/init(dispatchQueue:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the callback queue with a GCD queue"}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dispatchQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":")"}],"title":"init(dispatchQueue:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDCallbackQueue(im)initWithDispatchQueue:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"initWithDispatchQueue:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"role":"symbol","title":"SDCallbackQueue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDCallbackQueue"}],"abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Manager"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Loader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"url":"\/documentation\/sdwebimage\/sdcallbackqueue"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/init(dispatchQueue:)":{"role":"symbol","title":"init(dispatchQueue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"dispatchQueue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"DispatchQueue","preciseIdentifier":"c:objc(cs)OS_dispatch_queue"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the callback queue with a GCD queue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/init(dispatchQueue:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithDispatchQueue:"}],"url":"\/documentation\/sdwebimage\/sdcallbackqueue\/init(dispatchqueue:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithDispatchQueue:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDispatchQueue:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithDispatchQueue:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSObject<OS_dispatch_queue>","preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"queue"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","value":"SDCallbackQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","value":[{"kind":"identifier","text":"SDCallbackQueue"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1init(dispatchQueue:)\/title","value":"initWithDispatchQueue:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1init(dispatchQueue:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithDispatchQueue:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}