{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/main"]},{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/main"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/main"},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"abstract":[{"type":"text","text":"The main queue. This is the default value, has the same effect when passing "},{"code":"nil","type":"codeVoice"},{"text":" to ","type":"text"},{"code":"SDWebImageContextCallbackQueue","type":"codeVoice"},{"type":"text","text":" "},{"text":"The policy defaults to ","type":"text"},{"type":"codeVoice","code":"SDCallbackPolicySafeAsyncMainThread"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"main"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","kind":"typeIdentifier","text":"SDCallbackQueue","preciseIdentifier":"c:objc(cs)SDCallbackQueue"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"metadata":{"externalID":"c:objc(cs)SDCallbackQueue(cpy)mainQueue","title":"main","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"mainQueue","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/main":{"navigatorTitle":[{"text":"mainQueue","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/main","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/main","kind":"symbol","abstract":[{"type":"text","text":"The main queue. This is the default value, has the same effect when passing "},{"code":"nil","type":"codeVoice"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextCallbackQueue"},{"text":" ","type":"text"},{"type":"text","text":"The policy defaults to "},{"code":"SDCallbackPolicySafeAsyncMainThread","type":"codeVoice"}],"role":"symbol","title":"main","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"url":"\/documentation\/sdwebimage\/sdcallbackqueue","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}],"title":"SDCallbackQueue","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"mainQueue"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"mainQueue","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","text":"SDCallbackQueue","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDCallbackQueue"},{"text":" * ","kind":"text"},{"text":"mainQueue","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1main\/title","op":"replace","value":"mainQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1main\/fragments","value":[{"text":"mainQueue","kind":"identifier"}]},{"value":"SDCallbackQueue","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","value":[{"kind":"identifier","text":"SDCallbackQueue"}],"op":"replace"},{"value":[{"text":"SDCallbackQueue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/navigatorTitle"}]}]}