{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","preciseIdentifier":"c:@E@SDCallbackPolicy","text":"SDCallbackPolicy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/policy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/policy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/policy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The current queue’s callback policy, defaults to "},{"type":"codeVoice","code":"SDCallbackPolicySafeExecute"},{"type":"text","text":", which behaves like the old macro  "},{"type":"codeVoice","code":"dispatch_main_async_safe"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDCallbackPolicy","preciseIdentifier":"c:@E@SDCallbackPolicy"}],"title":"policy","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDCallbackQueue(py)policy","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"policy"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy":{"role":"symbol","title":"SDCallbackPolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDCallbackPolicy"}],"abstract":[{"type":"text","text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use "},{"type":"codeVoice","code":"dispatch_async\/dispatch_sync"},{"type":"text","text":", check if current queue match target queue, or just invoke without any context."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDCallbackPolicy"}],"url":"\/documentation\/sdwebimage\/sdcallbackpolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/policy":{"role":"symbol","title":"policy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"policy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDCallbackPolicy","preciseIdentifier":"c:@E@SDCallbackPolicy"}],"abstract":[{"type":"text","text":"The current queue’s callback policy, defaults to "},{"type":"codeVoice","code":"SDCallbackPolicySafeExecute"},{"type":"text","text":", which behaves like the old macro  "},{"type":"codeVoice","code":"dispatch_main_async_safe"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/policy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"policy"}],"url":"\/documentation\/sdwebimage\/sdcallbackqueue\/policy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"role":"symbol","title":"SDCallbackQueue","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDCallbackQueue"}],"abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Manager"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Loader"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"url":"\/documentation\/sdwebimage\/sdcallbackqueue"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"policy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"policy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","preciseIdentifier":"c:@E@SDCallbackPolicy","text":"SDCallbackPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"policy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/title","value":"SDCallbackPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/fragments","value":[{"kind":"identifier","text":"SDCallbackPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1policy\/title","value":"policy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1policy\/fragments","value":[{"kind":"identifier","text":"policy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","value":"SDCallbackQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","value":[{"kind":"identifier","text":"SDCallbackQueue"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}