{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/sync(_:)","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)SDCallbackQueue(im)sync:","roleHeading":"Instance Method","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"sync:","kind":"identifier"}],"platforms":[{"introducedAt":"8.0","deprecated":false,"message":"No longer use, may cause deadlock when misused","name":"iOS","unavailable":false,"deprecatedAt":"8.0","beta":false},{"deprecated":false,"beta":false,"introducedAt":"8.0","message":"No longer use, may cause deadlock when misused","name":"iPadOS","unavailable":false,"deprecatedAt":"8.0"},{"message":"No longer use, may cause deadlock when misused","deprecatedAt":"8.0","name":"Mac Catalyst","deprecated":false,"introducedAt":"8.0","beta":false,"unavailable":false}],"title":"sync(_:)","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sync"},{"text":"(() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"text":"No longer use, may cause deadlock when misused","type":"text"}]}],"abstract":[{"type":"text","text":"Submits a block for execution and returns after that block finishes executing."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sync","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"block","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" () -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")","kind":"text"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block that contains the work to perform."}]}],"name":"block"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/sync(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue\/sync(_:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"url":"\/documentation\/sdwebimage\/sdcallbackqueue","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}],"title":"SDCallbackQueue","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/sync(_:)":{"type":"topic","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/sync(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/sync(_:)","abstract":[{"type":"text","text":"Submits a block for execution and returns after that block finishes executing."}],"navigatorTitle":[{"text":"sync:","kind":"identifier"}],"kind":"symbol","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sync","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"sync(_:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"8.0","deprecated":false,"beta":false,"name":"iOS","unavailable":false,"deprecatedAt":"8.0"},{"introducedAt":"8.0","name":"iPadOS","beta":false,"deprecated":false,"unavailable":false,"deprecatedAt":"8.0"},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","deprecatedAt":"8.0","introducedAt":"8.0"}]},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"sync:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"sync:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"sync:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv()","text":"void (^)(void)"},{"kind":"text","text":") "},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The block that contains the work to perform."}],"type":"paragraph"}],"name":"block"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","value":"SDCallbackQueue"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","value":[{"text":"SDCallbackQueue","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/navigatorTitle","value":[{"text":"SDCallbackQueue","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"sync:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1sync(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1sync(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sync:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}