{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"]]},"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/preserveImageMetadata","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"preserveImageMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Defaults to YES if you don’t implements this method.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We keep some metadata like Image Format ("},{"code":"sd_imageFormat","type":"codeVoice"},{"type":"text","text":")\/ Animated Loop Count ("},{"type":"codeVoice","code":"sd_imageLoopCount"},{"text":") via associated object on UIImage instance.","type":"text"},{"type":"text","text":" "},{"text":"When transformer generate a new UIImage instance, in most cases you still want to keep these information. So this is what for during the image loading pipeline.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the value is YES, we will keep and override the metadata "},{"type":"strong","inlineContent":[{"type":"text","text":"After you generate the UIImage"}]},{"text":" ","type":"text"},{"text":"If the value is NO, we will not touch the UIImage metadata and it’s controlled by you during the generation. Read ","type":"text"},{"type":"codeVoice","code":"UIImage+Medata.h"},{"type":"text","text":" and pick the metadata you want for the new generated UIImage."}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preserveImageMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}],"roleHeading":"Instance Property","required":true,"title":"preserveImageMetadata","navigatorTitle":[{"kind":"identifier","text":"preserveImageMetadata"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(pl)SDImageTransformer(py)preserveImageMetadata","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagetransformer\/preserveimagemetadata"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagetransformer\/preserveimagemetadata"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer/preserveImageMetadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"preserveImageMetadata"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preserveImageMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimagetransformer\/preserveimagemetadata","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Defaults to YES if you don’t implements this method."},{"text":" ","type":"text"},{"type":"text","text":"We keep some metadata like Image Format ("},{"code":"sd_imageFormat","type":"codeVoice"},{"text":")\/ Animated Loop Count (","type":"text"},{"code":"sd_imageLoopCount","type":"codeVoice"},{"text":") via associated object on UIImage instance.","type":"text"},{"text":" ","type":"text"},{"text":"When transformer generate a new UIImage instance, in most cases you still want to keep these information. So this is what for during the image loading pipeline.","type":"text"},{"text":" ","type":"text"},{"text":"If the value is YES, we will keep and override the metadata ","type":"text"},{"inlineContent":[{"text":"After you generate the UIImage","type":"text"}],"type":"strong"},{"type":"text","text":" "},{"text":"If the value is NO, we will not touch the UIImage metadata and it’s controlled by you during the generation. Read ","type":"text"},{"type":"codeVoice","code":"UIImage+Medata.h"},{"text":" and pick the metadata you want for the new generated UIImage.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/preserveImageMetadata","type":"topic","title":"preserveImageMetadata"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"preserveImageMetadata","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"preserveImageMetadata"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"preserveImageMetadata","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1preserveImageMetadata\/title","value":"preserveImageMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1preserveImageMetadata\/fragments","value":[{"kind":"identifier","text":"preserveImageMetadata"}]},{"value":"SDImageTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","op":"replace","value":[{"text":"SDImageTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageTransformer"}]}]}]}