{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","text":"SDAnimatedImageCoder"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedcoder-6fsjl"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedcoder-6fsjl"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/animatedCoder-6fsjl","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return the animated image coder if the image is created with "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" method."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImageCoder","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder"},{"kind":"text","text":"?"}],"title":"animatedCoder","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImage(py)animatedCoder","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"animatedCoder"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/animatedCoder-6fsjl":{"role":"symbol","title":"animatedCoder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImageCoder","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Return the animated image coder if the image is created with "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/animatedCoder-6fsjl","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedcoder-6fsjl"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","title":"SDAnimatedImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}],"abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":". You can also use it on normal UIImageView\/NSImageView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImage"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"role":"symbol","title":"SDAnimatedImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"abstract":[{"type":"text","text":"This is the animated image coder protocol for custom animated image class like  "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":". Through it inherit from "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":" to detect the proper coder for specify animated image format."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"animatedCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"animatedCoder"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SDAnimatedImageCoder>","preciseIdentifier":"c:Qoobjc(pl)SDAnimatedImageCoder"},{"kind":"text","text":" * "},{"kind":"identifier","text":"animatedCoder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1animatedCoder-6fsjl\/title","value":"animatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1animatedCoder-6fsjl\/fragments","value":[{"kind":"identifier","text":"animatedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","value":"SDAnimatedImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}