{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"role":"symbol","title":"animatedCoder","symbolKind":"property","navigatorTitle":[{"text":"animatedCoder","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDAnimatedImage(py)animatedCoder","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatedCoder","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"SDAnimatedImageCoder","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"roleHeading":"Instance Property"},"abstract":[{"text":"Return the animated image coder if the image is created with ","type":"text"},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"text":" method.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedcoder"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedcoder"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedCoder"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","text":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"style":"note","content":[{"inlineContent":[{"type":"text","text":"We use this with animated coder which conforms to "},{"type":"codeVoice","code":"SDProgressiveImageCoder"},{"text":" for progressive animation decoding.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Note"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/animatedCoder"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/animatedCoder":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedcoder","title":"animatedCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/animatedCoder","navigatorTitle":[{"text":"animatedCoder","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Return the animated image coder if the image is created with "},{"code":"initWithAnimatedCoder:scale:","type":"codeVoice"},{"text":" method.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatedCoder","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder","kind":"typeIdentifier","text":"SDAnimatedImageCoder"},{"text":")?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","kind":"symbol","title":"SDAnimatedImage","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","navigatorTitle":[{"text":"SDAnimatedImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":". You can also use it on normal UIImageView\/NSImageView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"animatedCoder","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"animatedCoder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"id<SDAnimatedImageCoder>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDAnimatedImageCoder"},{"text":" ","kind":"text"},{"text":"animatedCoder","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"animatedCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1animatedCoder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1animatedCoder\/fragments","value":[{"kind":"identifier","text":"animatedCoder"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","op":"replace","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"text":"SDAnimatedImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/navigatorTitle","op":"replace","value":[{"text":"SDAnimatedImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","value":"SDAnimatedImageCoder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}