{"sections":[],"metadata":{"role":"symbol","externalID":"c:objc(cs)SDAnimatedImage(py)animatedImageFormat","navigatorTitle":[{"kind":"identifier","text":"animatedImageFormat"}],"modules":[{"name":"SDWebImage"}],"title":"animatedImageFormat","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"animatedImageFormat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"roleHeading":"Instance Property","symbolKind":"property"},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedimageformat"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedimageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/animatedImageFormat","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"animatedImageFormat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"This format is only valid when "},{"code":"animatedImageData","type":"codeVoice"},{"type":"text","text":" not nil."}],"type":"paragraph"}],"name":"Note","style":"note"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"This actually just call "},{"code":"[NSData sd_imageFormatForImageData:self.animatedImageData]","type":"codeVoice"}],"type":"paragraph"}],"style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"abstract":[{"type":"text","text":"Current animated image format."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","kind":"symbol","title":"SDAnimatedImage","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","navigatorTitle":[{"text":"SDAnimatedImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":". You can also use it on normal UIImageView\/NSImageView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/animatedImageFormat":{"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatedImageFormat","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"abstract":[{"text":"Current animated image format.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/animatedimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/animatedImageFormat","title":"animatedImageFormat","navigatorTitle":[{"text":"animatedImageFormat","kind":"identifier"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"animatedImageFormat","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"animatedImageFormat","kind":"identifier"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animatedImageFormat"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SDImageFormat","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments","op":"replace","value":[{"text":"SDImageFormat","kind":"identifier"}]},{"value":[{"text":"SDImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","op":"replace","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1animatedImageFormat\/title","value":"animatedImageFormat","op":"replace"},{"value":[{"text":"animatedImageFormat","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1animatedImageFormat\/fragments"}]}]}