{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"imageWithData:"},{"text":"(","kind":"text"},{"text":"NSData","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSData"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale:"},{"text":"(","kind":"text"},{"text":"CGFloat","preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"scale"},{"text":";","kind":"text"}]}]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/imagewithdata:scale:"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"+ ","kind":"text"},{"text":"imageWithData:scale:","kind":"identifier"}],"symbolKind":"method","role":"symbol","externalID":"c:objc(cs)SDAnimatedImage(cm)imageWithData:scale:","navigatorTitle":[{"kind":"identifier","text":"imageWithData:scale:"}],"roleHeading":"Type Method","title":"imageWithData:scale:","modules":[{"name":"SDWebImage"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/imageWithData:scale:","interfaceLanguage":"occ"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","kind":"symbol","title":"SDAnimatedImage","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","navigatorTitle":[{"text":"SDAnimatedImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":". You can also use it on normal UIImageView\/NSImageView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/imageWithData:scale:":{"title":"imageWithData:scale:","fragments":[{"text":"+ ","kind":"text"},{"text":"imageWithData:scale:","kind":"identifier"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/imageWithData:scale:","navigatorTitle":[{"kind":"identifier","text":"imageWithData:scale:"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/imagewithdata:scale:","role":"symbol"}},"variantOverrides":[{"patch":[{"value":"SDAnimatedImage","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"text":"SDAnimatedImage","kind":"identifier"}]},{"value":[{"text":"SDAnimatedImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}