{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"named"},{"kind":"text","text":" "},{"kind":"internalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":" "},{"kind":"internalParam","text":"bundle"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"compatibleWith"},{"kind":"text","text":" "},{"kind":"internalParam","text":"traitCollection"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(named:in:compatiblewith:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(named:in:compatiblewith:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/init(named:in:compatibleWith:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"named"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"compatibleWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"title":"init(named:in:compatibleWith:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDAnimatedImage(cm)imageNamed:inBundle:compatibleWithTraitCollection:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"imageNamed:inBundle:compatibleWithTraitCollection:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/init(named:in:compatibleWith:)":{"role":"symbol","title":"init(named:in:compatibleWith:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"named"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":", "},{"kind":"externalParam","text":"in"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"compatibleWith"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":"?)"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/init(named:in:compatibleWith:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageNamed:inBundle:compatibleWithTraitCollection:"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(named:in:compatiblewith:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","title":"SDAnimatedImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}],"abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":". You can also use it on normal UIImageView\/NSImageView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImage"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"imageNamed:inBundle:compatibleWithTraitCollection:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageNamed:inBundle:compatibleWithTraitCollection:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"imageNamed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"name"},{"kind":"text","text":" "},{"kind":"identifier","text":"inBundle:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSBundle","preciseIdentifier":"c:objc(cs)NSBundle"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"bundle"},{"kind":"text","text":" "},{"kind":"identifier","text":"compatibleWithTraitCollection:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UITraitCollection","preciseIdentifier":"c:objc(cs)UITraitCollection"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"traitCollection"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1init(named:in:compatibleWith:)\/title","value":"imageNamed:inBundle:compatibleWithTraitCollection:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1init(named:in:compatibleWith:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageNamed:inBundle:compatibleWithTraitCollection:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}