{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(named:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(named:)"]}],"metadata":{"externalID":"c:objc(cs)SDAnimatedImage(cm)imageNamed:","role":"symbol","symbolKind":"init","title":"init(named:)","navigatorTitle":[{"kind":"identifier","text":"imageNamed:"}],"roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"named"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/init(named:)"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"named","kind":"externalParam"},{"kind":"text","text":" "},{"text":"name","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","kind":"symbol","title":"SDAnimatedImage","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","navigatorTitle":[{"text":"SDAnimatedImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":". You can also use it on normal UIImageView\/NSImageView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/init(named:)":{"abstract":[],"title":"init(named:)","navigatorTitle":[{"text":"imageNamed:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"named","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/init(named:)","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(named:)","kind":"symbol","role":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"value":"imageNamed:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"imageNamed:"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"preciseIdentifier":"c:*Qo","kind":"typeIdentifier","text":"id"},{"text":") ","kind":"text"},{"text":"imageNamed:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"name","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","op":"replace","value":"SDAnimatedImage"},{"value":[{"text":"SDAnimatedImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/navigatorTitle","value":[{"text":"SDAnimatedImage","kind":"identifier"}]},{"value":"imageNamed:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1init(named:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1init(named:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"imageNamed:"}]}]}]}