{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(data:scale:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(data:scale:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/init(data:scale:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"title":"init(data:scale:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDAnimatedImage(im)initWithData:scale:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","title":"SDAnimatedImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}],"abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":". You can also use it on normal UIImageView\/NSImageView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImage"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class/init(data:scale:)":{"role":"symbol","title":"init(data:scale:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class\/init(data:scale:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class\/init(data:scale:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithData:scale:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:scale:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"scale"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1init(data:scale:)\/title","value":"initWithData:scale:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class~1init(data:scale:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:scale:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}