{"metadata":{"roleHeading":"Type Property","externalID":"c:objc(cs)SDWebImageDownloaderDecryptor(cpy)base64Decryptor","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"base64Decryptor","kind":"identifier"}],"title":"base64","symbolKind":"property","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"base64","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderDecryptor","text":"SDWebImageDownloaderDecryptor"}]},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/base64"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/base64"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Base64 Encoded image data decryptor"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/base64","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"base64","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","text":"SDWebImageDownloaderDecryptor","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderDecryptor"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderDecryptor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class","title":"SDWebImageDownloaderDecryptor","type":"topic","abstract":[{"type":"text","text":"A downloader response modifier class with block."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class/base64":{"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/base64","title":"base64","navigatorTitle":[{"text":"base64Decryptor","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"base64","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImageDownloaderDecryptor","text":"SDWebImageDownloaderDecryptor","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Base64 Encoded image data decryptor"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/base64","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"base64Decryptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"base64Decryptor","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","text":"SDWebImageDownloaderDecryptor","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderDecryptor"},{"kind":"text","text":" * "},{"kind":"identifier","text":"base64Decryptor"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"SDWebImageDownloaderDecryptor","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"op":"replace"},{"value":[{"text":"SDWebImageDownloaderDecryptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1base64\/title","value":"base64Decryptor","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1base64\/fragments","value":[{"text":"base64Decryptor","kind":"identifier"}]}]}]}