{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"decryptorWithBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData *(^)(NSData *, NSURLResponse *)","preciseIdentifier":"c:BF*$objc(cs)NSData(#S2_#*$objc(cs)NSURLResponse)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/decryptorwithblock:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/decryptorWithBlock:","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create the data decryptor with block"}],"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decryptorWithBlock:"}],"title":"decryptorWithBlock:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImageDownloaderDecryptor(cm)decryptorWithBlock:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"decryptorWithBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class":{"role":"symbol","title":"SDWebImageDownloaderDecryptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"abstract":[{"type":"text","text":"A downloader response modifier class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class/decryptorWithBlock:":{"role":"symbol","title":"decryptorWithBlock:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decryptorWithBlock:"}],"abstract":[{"type":"text","text":"Create the data decryptor with block"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/decryptorWithBlock:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decryptorWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/decryptorwithblock:"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/title","value":"SDWebImageDownloaderDecryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}