{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"symbolKind":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"title":"init(block:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"block","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDownloaderDecryptor.h@T@SDWebImageDownloaderDecryptorBlock","text":"SDWebImageDownloaderDecryptorBlock","kind":"typeIdentifier"},{"kind":"text","text":")"}],"roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDWebImageDownloaderDecryptor(im)initWithBlock:"},"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/init(block:)","interfaceLanguage":"swift"},"abstract":[{"text":"Create the data decryptor with block","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"("},{"text":"block","kind":"externalParam"},{"kind":"text","text":": "},{"text":"@escaping","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorBlock","text":"SDWebImageDownloaderDecryptorBlock","preciseIdentifier":"c:SDWebImageDownloaderDecryptor.h@T@SDWebImageDownloaderDecryptorBlock"},{"kind":"text","text":")"}]}]},{"kind":"parameters","parameters":[{"name":"block","content":[{"inlineContent":[{"type":"text","text":"A block to control decrypt logic"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/init(block:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/init(block:)"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class/init(block:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageDownloaderDecryptorBlock","preciseIdentifier":"c:SDWebImageDownloaderDecryptor.h@T@SDWebImageDownloaderDecryptorBlock"},{"kind":"text","text":")"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/init(block:)","role":"symbol","title":"init(block:)","abstract":[{"text":"Create the data decryptor with block","type":"text"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/init(block:)","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptorBlock":{"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderDecryptorBlock"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptorblock","role":"symbol","title":"SDWebImageDownloaderDecryptorBlock","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorBlock","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptorBlock"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderDecryptor","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class","title":"SDWebImageDownloaderDecryptor","type":"topic","abstract":[{"type":"text","text":"A downloader response modifier class with block."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"initWithBlock:"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"initWithBlock:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData *(^)(NSData *, NSURLResponse *)","preciseIdentifier":"c:BF*$objc(cs)NSData(#S2_#*$objc(cs)NSURLResponse)"},{"kind":"text","text":") "},{"text":"block","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block to control decrypt logic"}]}],"name":"block"}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1init(block:)\/title","op":"replace","value":"initWithBlock:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1init(block:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorBlock\/title","value":"SDWebImageDownloaderDecryptorBlock"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptorBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorBlock\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptorBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorBlock\/navigatorTitle"},{"value":"SDWebImageDownloaderDecryptor","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]}]}]}