{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableStatusCodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes-8qb9b"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes-8qb9b"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes-8qb9b","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the acceptable HTTP Response status code. The status code which beyond the range will mark the download operation failed."},{"type":"text","text":" "},{"type":"text","text":"For example, if we config [200, 400) but server response is 503, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadStatusCode"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to [200,400). Nil means no validation at all."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableStatusCodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"?"}],"title":"acceptableStatusCodes","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageDownloaderOperation(py)acceptableStatusCodes","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"acceptableStatusCodes"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/acceptableStatusCodes-8qb9b":{"role":"symbol","title":"acceptableStatusCodes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableStatusCodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response status code. The status code which beyond the range will mark the download operation failed."},{"type":"text","text":" "},{"type":"text","text":"For example, if we config [200, 400) but server response is 503, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadStatusCode"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to [200,400). Nil means no validation at all."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes-8qb9b","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptableStatusCodes"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes-8qb9b"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"role":"symbol","title":"SDWebImageDownloaderOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"abstract":[{"type":"text","text":"The download operation class for SDWebImageDownloader."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"acceptableStatusCodes"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"acceptableStatusCodes"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSIndexSet","preciseIdentifier":"c:objc(cs)NSIndexSet"},{"kind":"text","text":" *"},{"kind":"identifier","text":"acceptableStatusCodes"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableStatusCodes-8qb9b\/title","value":"acceptableStatusCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableStatusCodes-8qb9b\/fragments","value":[{"kind":"identifier","text":"acceptableStatusCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}