{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptableStatusCodes","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes"},"sections":[],"metadata":{"title":"acceptableStatusCodes","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptableStatusCodes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"roleHeading":"Instance Property","modules":[{"name":"SDWebImage"}],"role":"symbol","externalID":"c:objc(cs)SDWebImageDownloaderOperation(py)acceptableStatusCodes","navigatorTitle":[{"kind":"identifier","text":"acceptableStatusCodes"}]},"abstract":[{"text":"Set the acceptable HTTP Response status code. The status code which beyond the range will mark the download operation failed.","type":"text"},{"text":" ","type":"text"},{"text":"For example, if we config [200, 400) but server response is 503, the download will fail with error code ","type":"text"},{"code":"SDWebImageErrorInvalidDownloadStatusCode","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to [200,400). Nil means no validation at all."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes"]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"title":"SDWebImageDownloaderOperation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class","abstract":[{"text":"The download operation class for SDWebImageDownloader.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/acceptableStatusCodes":{"navigatorTitle":[{"text":"acceptableStatusCodes","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes","kind":"symbol","role":"symbol","title":"acceptableStatusCodes","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptableStatusCodes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation8IndexSetV","text":"IndexSet","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response status code. The status code which beyond the range will mark the download operation failed."},{"type":"text","text":" "},{"text":"For example, if we config [200, 400) but server response is 503, the download will fail with error code ","type":"text"},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadStatusCode"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to [200,400). Nil means no validation at all."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"acceptableStatusCodes"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"acceptableStatusCodes"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSIndexSet","text":"NSIndexSet","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"acceptableStatusCodes","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title","value":"SDWebImageDownloaderOperation","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/navigatorTitle"},{"op":"replace","value":"acceptableStatusCodes","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableStatusCodes\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableStatusCodes\/fragments","value":[{"kind":"identifier","text":"acceptableStatusCodes"}],"op":"replace"}]}]}