{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Set the acceptable HTTP Response content type. The content type beyond the set will mark the download operation failed."},{"text":" ","type":"text"},{"type":"text","text":"For example, if we config [“image\/png”] but server response is “application\/json”, the download will fail with error code "},{"code":"SDWebImageErrorInvalidDownloadContentType","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Normally you don’t need this for image format detection because we use image’s data file signature magic bytes: https:\/\/en.wikipedia.org\/wiki\/List_of_file_signatures","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to nil. Nil means no validation at all.","type":"text"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableContentTypes","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"acceptableContentTypes"},{"kind":"text","text":": "},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablecontenttypes"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablecontenttypes"]}],"metadata":{"externalID":"c:objc(cs)SDWebImageDownloaderOperation(py)acceptableContentTypes","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptableContentTypes","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Set","kind":"typeIdentifier","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">?"}],"role":"symbol","title":"acceptableContentTypes","symbolKind":"property","navigatorTitle":[{"text":"acceptableContentTypes","kind":"identifier"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/acceptableContentTypes":{"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablecontenttypes","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptableContentTypes"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableContentTypes","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"acceptableContentTypes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"text":"<","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":">?","kind":"text"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response content type. The content type beyond the set will mark the download operation failed."},{"text":" ","type":"text"},{"type":"text","text":"For example, if we config [“image\/png”] but server response is “application\/json”, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadContentType"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Normally you don’t need this for image format detection because we use image’s data file signature magic bytes: https:\/\/en.wikipedia.org\/wiki\/List_of_file_signatures"},{"text":" ","type":"text"},{"text":"Defaults to nil. Nil means no validation at all.","type":"text"}],"title":"acceptableContentTypes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"title":"SDWebImageDownloaderOperation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class","abstract":[{"text":"The download operation class for SDWebImageDownloader.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"acceptableContentTypes","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"acceptableContentTypes","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"text":"NSSet<NSString *>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSSet"},{"kind":"text","text":" * "},{"kind":"identifier","text":"acceptableContentTypes"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"acceptableContentTypes","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableContentTypes\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableContentTypes\/fragments","value":[{"text":"acceptableContentTypes","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDWebImageDownloaderOperation","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/navigatorTitle","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}