{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:)"},"metadata":{"navigatorTitle":[{"text":"addHandlersForProgress:completed:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"addHandlers(forProgress:completed:)","externalID":"c:objc(cs)SDWebImageDownloaderOperation(im)addHandlersForProgress:completed:","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"text":"forProgress","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"symbolKind":"method","role":"symbol","roleHeading":"Instance Method"},"abstract":[{"text":"Adds handlers for progress and completion. Returns a token that can be passed to -cancel: to cancel this set of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"callbacks."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forProgress"},{"text":" ","kind":"text"},{"text":"progressBlock","kind":"internalParam"},{"kind":"text","text":": "},{"text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completedBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"text":"? = nil) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The block executed when a new chunk of data arrives.","type":"text"},{"text":" ","type":"text"},{"text":"@note the progress block is executed on a background queue","type":"text"}]}],"name":"progressBlock"},{"content":[{"inlineContent":[{"text":"The block executed when the download is done.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@note the completed block is executed on the main queue for success. If errors are found, there is a chance the block will be executed on a background queue"}],"type":"paragraph"}],"name":"completedBlock"}]},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"The token to use to cancel this set of handlers"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:)"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderCompletedBlock":{"abstract":[],"title":"SDWebImageDownloaderCompletedBlock","url":"\/documentation\/sdwebimage\/sdwebimagedownloadercompletedblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderCompletedBlock","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","kind":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderCompletedBlock","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"title":"SDWebImageDownloaderOperation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class","abstract":[{"text":"The download operation class for SDWebImageDownloader.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderProgressBlock":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"title":"SDWebImageDownloaderProgressBlock","navigatorTitle":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderprogressblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/addHandlers(forProgress:completed:)":{"navigatorTitle":[{"kind":"identifier","text":"addHandlersForProgress:completed:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:)","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:)","kind":"symbol","role":"symbol","title":"addHandlers(forProgress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"text":"forProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock","text":"SDWebImageDownloaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"abstract":[{"text":"Adds handlers for progress and completion. Returns a token that can be passed to -cancel: to cancel this set of","type":"text"},{"type":"text","text":" "},{"type":"text","text":"callbacks."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"addHandlersForProgress:completed:","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"addHandlersForProgress:completed:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"addHandlersForProgress:"},{"text":"(","kind":"text"},{"text":"void (^)(long, long, NSURL *)","preciseIdentifier":"c:BFv(#L#L#*$objc(cs)NSURL)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"progressBlock","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSData *, NSError *, _Bool)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#*$objc(cs)NSError#b)"},{"kind":"text","text":") "},{"text":"completedBlock","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block executed when a new chunk of data arrives."},{"type":"text","text":" "},{"text":"@note the progress block is executed on a background queue","type":"text"}]}],"name":"progressBlock"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The block executed when the download is done.","type":"text"},{"type":"text","text":" "},{"text":"@note the completed block is executed on the main queue for success. If errors are found, there is a chance the block will be executed on a background queue","type":"text"}]}],"name":"completedBlock"}]}},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The token to use to cancel this set of handlers"}]}]},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/title","value":"SDWebImageDownloaderCompletedBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"op":"replace"},{"value":"SDWebImageDownloaderOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/navigatorTitle","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/title","value":"SDWebImageDownloaderProgressBlock"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/navigatorTitle","value":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1addHandlers(forProgress:completed:)\/title","value":"addHandlersForProgress:completed:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"addHandlersForProgress:completed:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1addHandlers(forProgress:completed:)\/fragments"}]}]}