{"abstract":[{"text":"Adds handlers for progress and completion, and optional decode options (which need another image other than the initial one). Returns a token that can be passed to -cancel: to cancel this set of","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"callbacks."}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:decodeOptions:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addHandlers"},{"text":"(","kind":"text"},{"text":"forProgress","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImageDownloaderProgressBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"decodeOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImageDownloaderOperation(im)addHandlersForProgress:completed:decodeOptions:","roleHeading":"Instance Method","title":"addHandlers(forProgress:completed:decodeOptions:)","navigatorTitle":[{"text":"addHandlersForProgress:completed:decodeOptions:","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"addHandlers","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forProgress","kind":"externalParam"},{"kind":"text","text":" "},{"text":"progressBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"text":" ","kind":"text"},{"text":"completedBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock"},{"text":"?, ","kind":"text"},{"text":"decodeOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDImageCoderOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? = nil) -> ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The block executed when a new chunk of data arrives."},{"text":" ","type":"text"},{"text":"@note the progress block is executed on a background queue","type":"text"}]}],"name":"progressBlock"},{"content":[{"inlineContent":[{"type":"text","text":"The block executed when the download is done."},{"type":"text","text":" "},{"text":"@note the completed block is executed on the main queue for success. If errors are found, there is a chance the block will be executed on a background queue","type":"text"}],"type":"paragraph"}],"name":"completedBlock"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The optional decode options, used when in thumbnail decoding for current completion block callback. For example, request <url1, {thumbnail: 100x100}> and then <url1, {thumbnail: 200x200}>, we may callback these two completion block with different size.","type":"text"}]}],"name":"decodeOptions"}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The token to use to cancel this set of handlers"}],"type":"paragraph"}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:decodeoptions:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:decodeoptions:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOptions":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"SDImageCoderOptions"}],"title":"SDImageCoderOptions","url":"\/documentation\/sdwebimage\/sdimagecoderoptions","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderProgressBlock":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"title":"SDWebImageDownloaderProgressBlock","navigatorTitle":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderprogressblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderCompletedBlock":{"abstract":[],"title":"SDWebImageDownloaderCompletedBlock","url":"\/documentation\/sdwebimage\/sdwebimagedownloadercompletedblock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderCompletedBlock","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","kind":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderCompletedBlock","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"title":"SDWebImageDownloaderOperation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class","abstract":[{"text":"The download operation class for SDWebImageDownloader.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/addHandlers(forProgress:completed:decodeOptions:)":{"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:decodeoptions:)","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"addHandlers","kind":"identifier"},{"kind":"text","text":"("},{"text":"forProgress","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","text":"SDWebImageDownloaderCompletedBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"decodeOptions","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"keyword","text":"Any"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"addHandlersForProgress:completed:decodeOptions:","kind":"identifier"}],"type":"topic","kind":"symbol","title":"addHandlers(forProgress:completed:decodeOptions:)","abstract":[{"text":"Adds handlers for progress and completion, and optional decode options (which need another image other than the initial one). Returns a token that can be passed to -cancel: to cancel this set of","type":"text"},{"type":"text","text":" "},{"text":"callbacks.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:decodeOptions:)"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addHandlersForProgress:completed:decodeOptions:"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"addHandlersForProgress:completed:decodeOptions:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"addHandlersForProgress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(long, long, NSURL *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#L#L#*$objc(cs)NSURL)"},{"text":") ","kind":"text"},{"text":"progressBlock","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"text":"void (^)(UIImage *, NSData *, NSError *, _Bool)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#*$objc(cs)NSError#b)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completedBlock"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeOptions:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOptions","kind":"typeIdentifier","text":"SDImageCoderOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions"},{"text":" *) ","kind":"text"},{"text":"decodeOptions","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"progressBlock","content":[{"inlineContent":[{"text":"The block executed when a new chunk of data arrives.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@note the progress block is executed on a background queue"}],"type":"paragraph"}]},{"name":"completedBlock","content":[{"type":"paragraph","inlineContent":[{"text":"The block executed when the download is done.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@note the completed block is executed on the main queue for success. If errors are found, there is a chance the block will be executed on a background queue"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The optional decode options, used when in thumbnail decoding for current completion block callback. For example, request <url1, {thumbnail: 100x100}> and then <url1, {thumbnail: 200x200}>, we may callback these two completion block with different size.","type":"text"}]}],"name":"decodeOptions"}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The token to use to cancel this set of handlers"}],"type":"paragraph"}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/title","value":"SDWebImageDownloaderProgressBlock","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageCoderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/title","value":"SDWebImageDownloaderCompletedBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/navigatorTitle","value":[{"text":"SDWebImageDownloaderCompletedBlock","kind":"identifier"}]},{"value":"SDWebImageDownloaderOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1addHandlers(forProgress:completed:decodeOptions:)\/title","value":"addHandlersForProgress:completed:decodeOptions:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1addHandlers(forProgress:completed:decodeOptions:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}