{"metadata":{"externalID":"c:objc(cs)SDWebImageDownloaderOperation(py)metrics","platforms":[{"unavailable":false,"beta":false,"name":"iOS","introducedAt":"10.0","deprecated":false},{"deprecated":false,"name":"iPadOS","unavailable":false,"beta":false,"introducedAt":"10.0"},{"deprecated":false,"unavailable":false,"introducedAt":"10.0","beta":false,"name":"Mac Catalyst"}],"role":"symbol","roleHeading":"Instance Property","navigatorTitle":[{"kind":"identifier","text":"metrics"}],"modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metrics"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics","text":"URLSessionTaskMetrics","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"metrics","symbolKind":"property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/metrics"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/metrics"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","abstract":[{"type":"text","text":"The collected metrics from "},{"code":"-URLSession:task:didFinishCollectingMetrics:","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"This can be used to collect the network metrics like download duration, DNS lookup duration, SSL handshake duration, etc. See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskmetrics","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/metrics"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"metrics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics","text":"URLSessionTaskMetrics","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/metrics":{"navigatorTitle":[{"text":"metrics","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/metrics","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/metrics","kind":"symbol","role":"symbol","title":"metrics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"metrics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics","kind":"typeIdentifier","text":"URLSessionTaskMetrics"},{"text":"?","kind":"text"}],"abstract":[{"type":"text","text":"The collected metrics from "},{"code":"-URLSession:task:didFinishCollectingMetrics:","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"text":"This can be used to collect the network metrics like download duration, DNS lookup duration, SSL handshake duration, etc. See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskmetrics","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"title":"SDWebImageDownloaderOperation","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class","abstract":[{"text":"The download operation class for SDWebImageDownloader.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":[{"unavailable":false,"beta":false,"deprecated":false,"introducedAt":"10.0","name":"iOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.0","name":"iPadOS"},{"deprecated":false,"unavailable":false,"beta":false,"introducedAt":"10.0","name":"Mac Catalyst"}],"path":"\/metadata\/platforms","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"metrics","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"metrics","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSURLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"metrics"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"op":"replace","value":"metrics","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1metrics\/title"},{"value":[{"text":"metrics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1metrics\/fragments"},{"value":"SDWebImageDownloaderOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/navigatorTitle","value":[{"text":"SDWebImageDownloaderOperation","kind":"identifier"}]}]}]}