{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/options"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/options"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/options","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options for the receiver."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"title":"options","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageDownloaderOperation(py)options","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"options"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"role":"symbol","title":"SDWebImageDownloaderOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"abstract":[{"type":"text","text":"The download operation class for SDWebImageDownloader."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"abstract":[{"type":"text","text":"The options for the receiver."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/options","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"options"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/options"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"abstract":[{"type":"text","text":"Downloader options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"options"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"options"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1options\/title","value":"options"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1options\/fragments","value":[{"kind":"identifier","text":"options"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","value":"SDWebImageDownloaderOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}