{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isoGainMap","kind":"identifier"}],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"title":"SDImageHDRType.isoGainMap","symbolKind":"case","navigatorTitle":[{"text":"SDImageHDRTypeISOGainMap","kind":"identifier"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"isoGainMap","kind":"identifier"}],"roleHeading":"Case","externalID":"c:@E@SDImageHDRType@SDImageHDRTypeISOGainMap"},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagehdrtype\/isogainmap"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagehdrtype\/isogainmap"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/isoGainMap"},"abstract":[{"type":"text","text":"ISO Gain Map based HDR (supported by nearly all format, including tranditional JPEG, which stored the gain map into XMP)"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageHDRType","kind":"identifier"}],"title":"SDImageHDRType","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRType"}],"abstract":[{"type":"text","text":"These enum is used to represent the High Dynamic Range type during image encoding\/decoding."},{"type":"text","text":" "},{"type":"text","text":"There are alao other HDR type in history before ISO Standard (ISO 21496-1), including Google and Apple’s old OSs captured photos, but which is non-standard and we do not support."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/isoGainMap":{"abstract":[{"text":"ISO Gain Map based HDR (supported by nearly all format, including tranditional JPEG, which stored the gain map into XMP)","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"isoGainMap"}],"kind":"symbol","title":"SDImageHDRType.isoGainMap","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/isogainmap","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/isoGainMap","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRTypeISOGainMap"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SDImageHDRTypeISOGainMap","op":"replace","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageHDRTypeISOGainMap","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDImageHDRTypeISOGainMap"}]}]}},{"value":"SDImageHDRType","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/fragments","op":"replace","value":[{"text":"SDImageHDRType","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageHDRType"}]},{"value":"SDImageHDRTypeISOGainMap","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1isoGainMap\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageHDRTypeISOGainMap"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1isoGainMap\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}