{"metadata":{"modules":[{"name":"SDWebImage"}],"role":"collectionGroup","title":"RawRepresentable Implementations","roleHeading":"API Collection"},"kind":"article","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagehdrtype\/rawrepresentable-implementations"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/hashValue"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/hash(into:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/RawRepresentable-Implementations","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/hashValue":{"role":"symbol","kind":"symbol","title":"hashValue","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/hashvalue","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"hashValue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}],"availabilityPrefix":[{"type":"text","text":"Available when"}]},"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/hashValue","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageHDRType","kind":"identifier"}],"title":"SDImageHDRType","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRType"}],"abstract":[{"type":"text","text":"These enum is used to represent the High Dynamic Range type during image encoding\/decoding."},{"type":"text","text":" "},{"type":"text","text":"There are alao other HDR type in history before ISO Standard (ISO 21496-1), including Google and Apple’s old OSs captured photos, but which is non-standard and we do not support."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/hash(into:)":{"title":"hash(into:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/hash(into:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/hash(into:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"into"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s6HasherV","text":"Hasher"},{"text":")","kind":"text"}],"conformance":{"conformancePrefix":[{"type":"text","text":"Conforms when"}],"availabilityPrefix":[{"text":"Available when","type":"text"}],"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"RawValue"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":".","type":"text"}]},"abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SDImageHDRType","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/fragments","value":[{"text":"SDImageHDRType","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/navigatorTitle","value":[{"text":"SDImageHDRType","kind":"identifier"}]}]}]}