{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType"]]},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagehdrtype\/sdr"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagehdrtype\/sdr"]}],"metadata":{"roleHeading":"Case","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDR","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageHDRTypeSDR","kind":"identifier"}],"symbolKind":"case","externalID":"c:@E@SDImageHDRType@SDImageHDRTypeSDR","role":"symbol","title":"SDImageHDRType.SDR"},"abstract":[{"text":"SDR, mostly only 8 bits color per components, RGBA8","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDR"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/SDR","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/SDR":{"abstract":[{"type":"text","text":"SDR, mostly only 8 bits color per components, RGBA8"}],"title":"SDImageHDRType.SDR","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRTypeSDR"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDR"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/SDR","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/sdr","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageHDRType","kind":"identifier"}],"title":"SDImageHDRType","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRType"}],"abstract":[{"type":"text","text":"These enum is used to represent the High Dynamic Range type during image encoding\/decoding."},{"type":"text","text":" "},{"type":"text","text":"There are alao other HDR type in history before ISO Standard (ISO 21496-1), including Google and Apple’s old OSs captured photos, but which is non-standard and we do not support."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SDImageHDRTypeSDR","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageHDRTypeSDR"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageHDRTypeSDR"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1SDR\/title","op":"replace","value":"SDImageHDRTypeSDR"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1SDR\/fragments","value":[{"kind":"identifier","text":"SDImageHDRTypeSDR"}],"op":"replace"},{"op":"replace","value":"SDImageHDRType","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/fragments","value":[{"text":"SDImageHDRType","kind":"identifier"}]},{"value":[{"text":"SDImageHDRType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/navigatorTitle"}]}]}