{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameBuffer"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/clearframebuffer()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/clearframebuffer()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/clearFrameBuffer()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clear the frame cache buffer. The frame cache buffer size can be controlled by "},{"type":"codeVoice","code":"maxBufferSize"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"By default, when stop or pause the animation, the frame buffer is still kept to ready for the next restart"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameBuffer"},{"kind":"text","text":"()"}],"title":"clearFrameBuffer()","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDAnimatedImagePlayer(im)clearFrameBuffer","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"clearFrameBuffer"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"role":"symbol","title":"SDAnimatedImagePlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"abstract":[{"type":"text","text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/clearFrameBuffer()":{"role":"symbol","title":"clearFrameBuffer()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearFrameBuffer"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Clear the frame cache buffer. The frame cache buffer size can be controlled by "},{"type":"codeVoice","code":"maxBufferSize"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"By default, when stop or pause the animation, the frame buffer is still kept to ready for the next restart"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/clearFrameBuffer()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearFrameBuffer"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/clearframebuffer()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearFrameBuffer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearFrameBuffer"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearFrameBuffer"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","value":"SDAnimatedImagePlayer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1clearFrameBuffer()\/title","value":"clearFrameBuffer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1clearFrameBuffer()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearFrameBuffer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}