{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"kind":"symbol","metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)SDAnimatedImagePlayer(py)currentFrameIndex","modules":[{"name":"SDWebImage"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentFrameIndex"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"currentFrameIndex","kind":"identifier"}],"title":"currentFrameIndex","symbolKind":"property"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrameIndex"},"abstract":[{"text":"Current frame index, zero based. This value is KVO Compliance.","type":"text"}],"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentFrameIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentframeindex"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentframeindex"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/currentFrameIndex":{"kind":"symbol","type":"topic","title":"currentFrameIndex","navigatorTitle":[{"text":"currentFrameIndex","kind":"identifier"}],"abstract":[{"text":"Current frame index, zero based. This value is KVO Compliance.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrameIndex","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentframeindex","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentFrameIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"title":"SDAnimatedImagePlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"currentFrameIndex","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"currentFrameIndex","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentFrameIndex"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"currentFrameIndex","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentFrameIndex\/title","op":"replace"},{"value":[{"text":"currentFrameIndex","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentFrameIndex\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","value":"SDAnimatedImagePlayer"},{"value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/navigatorTitle"}]}]}