{"kind":"symbol","abstract":[{"text":"Current loop count since its latest animating. This value is KVO Compliance.","type":"text"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentLoopCount","interfaceLanguage":"swift"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentloopcount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentloopcount"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentLoopCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"currentLoopCount","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentLoopCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"currentLoopCount","kind":"identifier"}],"externalID":"c:objc(cs)SDAnimatedImagePlayer(py)currentLoopCount","role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/currentLoopCount":{"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentloopcount","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentLoopCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"currentLoopCount","abstract":[{"type":"text","text":"Current loop count since its latest animating. This value is KVO Compliance."}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentLoopCount","navigatorTitle":[{"text":"currentLoopCount","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"title":"SDAnimatedImagePlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"currentLoopCount"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"currentLoopCount"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"text":"currentLoopCount","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentLoopCount\/title","value":"currentLoopCount","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"currentLoopCount"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentLoopCount\/fragments"},{"value":"SDAnimatedImagePlayer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"op":"replace"}]}]}