{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","preciseIdentifier":"c:objc(pl)SDAnimatedImageProvider","text":"SDAnimatedImageProvider"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/init(provider:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/init(provider:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/init(provider:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Create a player with animated image provider. If the provider’s "},{"type":"codeVoice","code":"animatedImageFrameCount"},{"type":"text","text":" is less than 1, returns nil."},{"type":"text","text":" "},{"type":"text","text":"The provider can be any protocol implementation, like "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":", "},{"type":"codeVoice","code":"SDImageGIFCoder"},{"type":"text","text":", etc."}],"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImageProvider","preciseIdentifier":"c:objc(pl)SDAnimatedImageProvider"},{"kind":"text","text":")"}],"title":"init(provider:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDAnimatedImagePlayer(im)initWithProvider:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"initWithProvider:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/init(provider:)":{"role":"symbol","title":"init(provider:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"provider"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImageProvider","preciseIdentifier":"c:objc(pl)SDAnimatedImageProvider"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create a player with animated image provider. If the provider’s "},{"type":"codeVoice","code":"animatedImageFrameCount"},{"type":"text","text":" is less than 1, returns nil."},{"type":"text","text":" "},{"type":"text","text":"The provider can be any protocol implementation, like "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":", "},{"type":"codeVoice","code":"SDImageGIFCoder"},{"type":"text","text":", etc."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/init(provider:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithProvider:"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/init(provider:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"role":"symbol","title":"SDAnimatedImageProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageProvider"}],"abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SDAnimatedImageCoder"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageProvider"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageprovider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"role":"symbol","title":"SDAnimatedImagePlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"abstract":[{"type":"text","text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithProvider:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithProvider:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithProvider:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SDAnimatedImageProvider>","preciseIdentifier":"c:Qoobjc(pl)SDAnimatedImageProvider"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"provider"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1init(provider:)\/title","value":"initWithProvider:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1init(provider:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithProvider:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","value":"SDAnimatedImageProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","value":"SDAnimatedImagePlayer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}