{"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/pauseplaying()"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/pauseplaying()"]}],"metadata":{"title":"pausePlaying()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"pausePlaying","kind":"identifier"},{"kind":"text","text":"()"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDAnimatedImagePlayer(im)pausePlaying","symbolKind":"method","navigatorTitle":[{"text":"pausePlaying","kind":"identifier"}],"role":"symbol"},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Pause the animation. Keep the current frame index and loop count."}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/pausePlaying()","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"pausePlaying","kind":"identifier"},{"kind":"text","text":"()"}],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"title":"SDAnimatedImagePlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/pausePlaying()":{"title":"pausePlaying()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/pausePlaying()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pausePlaying","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pausePlaying","kind":"identifier"}],"abstract":[{"text":"Pause the animation. Keep the current frame index and loop count.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/pauseplaying()","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"pausePlaying","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"pausePlaying","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"pausePlaying","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","value":"SDAnimatedImagePlayer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/navigatorTitle","value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}]},{"value":"pausePlaying","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1pausePlaying()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"pausePlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1pausePlaying()\/fragments","op":"replace"}]}]}