{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","preciseIdentifier":"c:@E@SDAnimatedImagePlaybackMode","text":"SDAnimatedImagePlaybackMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronous setup animation playback mode. Default mode is SDAnimatedImagePlaybackModeNormal."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImagePlaybackMode","preciseIdentifier":"c:@E@SDAnimatedImagePlaybackMode"}],"title":"playbackMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImagePlayer(py)playbackMode","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"playbackMode"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode":{"role":"symbol","title":"SDAnimatedImagePlaybackMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"role":"symbol","title":"SDAnimatedImagePlayer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"abstract":[{"type":"text","text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/playbackMode":{"role":"symbol","title":"playbackMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImagePlaybackMode","preciseIdentifier":"c:@E@SDAnimatedImagePlaybackMode"}],"abstract":[{"type":"text","text":"Asynchronous setup animation playback mode. Default mode is SDAnimatedImagePlaybackModeNormal."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playbackMode"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"playbackMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"playbackMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","preciseIdentifier":"c:@E@SDAnimatedImagePlaybackMode","text":"SDAnimatedImagePlaybackMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/title","value":"SDAnimatedImagePlaybackMode"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","value":"SDAnimatedImagePlayer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackMode\/title","value":"playbackMode"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackMode\/fragments","value":[{"kind":"identifier","text":"playbackMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}