{"abstract":[{"type":"text","text":"The animation playback rate. Default is 1.0"},{"text":" ","type":"text"},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" means the normal speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"0.0"},{"text":" means stopping the animation.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"0.0-1.0"},{"type":"text","text":" means the slow speed."},{"text":" ","type":"text"},{"type":"codeVoice","code":"> 1.0"},{"type":"text","text":" means the fast speed."},{"text":" ","type":"text"},{"type":"codeVoice","code":"< 0.0"},{"text":" is not supported currently and stop animation. (may support reverse playback in the future)","type":"text"}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"}],"roleHeading":"Instance Property","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"playbackRate","kind":"identifier"}],"symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImagePlayer(py)playbackRate","role":"symbol","title":"playbackRate"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackrate"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackrate"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackRate","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"title":"SDAnimatedImagePlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/playbackRate":{"abstract":[{"type":"text","text":"The animation playback rate. Default is 1.0"},{"type":"text","text":" "},{"type":"codeVoice","code":"1.0"},{"text":" means the normal speed.","type":"text"},{"type":"text","text":" "},{"code":"0.0","type":"codeVoice"},{"type":"text","text":" means stopping the animation."},{"text":" ","type":"text"},{"type":"codeVoice","code":"0.0-1.0"},{"text":" means the slow speed.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"> 1.0"},{"type":"text","text":" means the fast speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"< 0.0"},{"type":"text","text":" is not supported currently and stop animation. (may support reverse playback in the future)"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackRate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"playbackRate","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackRate","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackrate","navigatorTitle":[{"text":"playbackRate","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"playbackRate"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"playbackRate","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:d","text":"double","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"SDAnimatedImagePlayer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title"},{"value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/navigatorTitle","value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"op":"replace"},{"value":"playbackRate","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackRate\/title","op":"replace"},{"value":[{"kind":"identifier","text":"playbackRate"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackRate\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}