{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalFrameCount","interfaceLanguage":"swift"},"metadata":{"title":"totalFrameCount","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"totalFrameCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDAnimatedImagePlayer(py)totalFrameCount","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"totalFrameCount"}],"role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalFrameCount"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]},{"kind":"content","content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"name":"Note","content":[{"inlineContent":[{"type":"text","text":"For progressive animation, you can update this value when your provider receive more frames."}],"type":"paragraph"}],"type":"aside","style":"note"}]}],"abstract":[{"type":"text","text":"Total frame count for animated image rendering. Defaults is animated image’s frame count."}],"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/totalframecount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer\/totalframecount"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"title":"SDAnimatedImagePlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/totalFrameCount":{"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/totalframecount","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalFrameCount","navigatorTitle":[{"text":"totalFrameCount","kind":"identifier"}],"abstract":[{"type":"text","text":"Total frame count for animated image rendering. Defaults is animated image’s frame count."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalFrameCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"totalFrameCount"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"totalFrameCount","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"totalFrameCount"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":" ","kind":"text"},{"text":"totalFrameCount","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SDAnimatedImagePlayer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title"},{"value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/navigatorTitle","value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}]},{"value":"totalFrameCount","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1totalFrameCount\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1totalFrameCount\/fragments","value":[{"text":"totalFrameCount","kind":"identifier"}]}]}]}