{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/clear(with:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/clear(with:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/clear(with:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Clear all the cached images for image cache. If cache type is memory only, completion is called synchronously, else asynchronously."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"clearWithCacheType:completion:"}],"role":"symbol","title":"clear(with:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)SDImageCache(im)clearWithCacheType:completion:","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"role":"symbol","title":"SDImageCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"}],"abstract":[{"type":"text","text":"This is the image cache protocol to provide custom image cache for "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Though the best practice to custom image cache, is to write your own class which conform "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol for "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"However, if your own cache implementation contains more advanced feature beyond "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like "},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/clear(with:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"clearWithCacheType:completion:"}],"role":"symbol","title":"clear(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Clear all the cached images for image cache. If cache type is memory only, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/clear(with:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/clear(with:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageNoParamsBlock":{"role":"symbol","title":"SDWebImageNoParamsBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageNoParamsBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageNoParamsBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagenoparamsblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"role":"symbol","title":"SDImageCacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"}],"abstract":[{"type":"text","text":"Image Cache Type"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"clearWithCacheType:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearWithCacheType:completion:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"clearWithCacheType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cacheType"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(void)","preciseIdentifier":"c:BFv()"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1clear(with:completion:)\/title","value":"clearWithCacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1clear(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearWithCacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/title","value":"SDWebImageNoParamsBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageNoParamsBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","value":"SDImageCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","value":[{"kind":"identifier","text":"SDImageCacheType"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}