{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completionBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheContainsCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheContainsCompletionBlock","text":"SDImageCacheContainsCompletionBlock"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/containsimage(forkey:cachetype:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/containsimage(forkey:cachetype:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/containsImage(forKey:cacheType:completion:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Check if image cache contains the image for the given key (does not load the image). If image is cached in memory, completion is called synchronously, else asynchronously."}],"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"containsImageForKey:cacheType:completion:"}],"role":"symbol","title":"containsImage(forKey:cacheType:completion:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheContainsCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheContainsCompletionBlock"},{"kind":"text","text":"?)"}],"symbolKind":"method","externalID":"c:objc(pl)SDImageCache(im)containsImageForKey:cacheType:completion:","required":true,"platforms":[{"unavailable":false,"deprecatedAt":"100000.0","message":"No longer use. Cast to cache instance and call its API","introducedAt":"8.0","deprecated":false,"name":"iOS","beta":false}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"]]},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"No longer use. Cast to cache instance and call its API"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"role":"symbol","title":"SDImageCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"}],"abstract":[{"type":"text","text":"This is the image cache protocol to provide custom image cache for "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Though the best practice to custom image cache, is to write your own class which conform "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol for "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"However, if your own cache implementation contains more advanced feature beyond "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like "},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/containsImage(forKey:cacheType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"containsImageForKey:cacheType:completion:"}],"deprecated":true,"role":"symbol","title":"containsImage(forKey:cacheType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheContainsCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheContainsCompletionBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Check if image cache contains the image for the given key (does not load the image). If image is cached in memory, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/containsImage(forKey:cacheType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/containsimage(forkey:cachetype:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"role":"symbol","title":"SDImageCacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"}],"abstract":[{"type":"text","text":"Image Cache Type"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheContainsCompletionBlock":{"role":"symbol","title":"SDImageCacheContainsCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheContainsCompletionBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheContainsCompletionBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheContainsCompletionBlock"}],"url":"\/documentation\/sdwebimage\/sdimagecachecontainscompletionblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecatedAt":"34464.0","beta":false,"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"containsImageForKey:cacheType:completion:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsImageForKey:cacheType:completion:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"containsImageForKey:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheType:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cacheType"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(enum SDImageCacheType)","preciseIdentifier":"c:BFv(#$@E@SDImageCacheType)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1containsImage(forKey:cacheType:completion:)\/title","value":"containsImageForKey:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1containsImage(forKey:cacheType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsImageForKey:cacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","value":"SDImageCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheContainsCompletionBlock\/title","value":"SDImageCacheContainsCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheContainsCompletionBlock\/fragments","value":[{"kind":"identifier","text":"SDImageCacheContainsCompletionBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}