{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryImage"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":" = [], ","kind":"text"},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":" "},{"text":"completionBlock","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil) -> (any ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","kind":"typeIdentifier","text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation"},{"kind":"text","text":")?"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image cache key"}]}]},{"name":"options","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A mask to specify options to use for this query"}]}]},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"code":"SDWebImageContextOption","type":"codeVoice"},{"text":". This hold the extra objects which ","type":"text"},{"type":"codeVoice","code":"options"},{"text":" enum can not hold. Pass ","type":"text"},{"type":"codeVoice","code":".callbackQueue"},{"type":"text","text":" to control callback queue"}]}]},{"name":"cacheType","content":[{"inlineContent":[{"text":"Specify where to query the cache from. By default we use ","type":"text"},{"code":".all","type":"codeVoice"},{"type":"text","text":", which means both memory cache and disk cache. You can choose to query memory only or disk only as well. Pass "},{"type":"codeVoice","code":".none"},{"type":"text","text":" is invalid and callback with nil immediately."}],"type":"paragraph"}]},{"name":"completionBlock","content":[{"inlineContent":[{"type":"text","text":"The completion block. Will not get called if the operation is cancelled"}],"type":"paragraph"}]}],"kind":"parameters"},{"content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The operation for this query","type":"text"}]}],"kind":"content"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:cacheType:completion:)","interfaceLanguage":"swift"},"kind":"symbol","abstract":[{"type":"text","text":"Query the cached image from image cache for given key. The operation can be used to cancel the query."},{"type":"text","text":" "},{"text":"If image is cached in memory, completion is called synchronously, else asynchronously and depends on the options arg (See ","type":"text"},{"code":"SDWebImageQueryDiskSync","type":"codeVoice"},{"text":")","type":"text"}],"metadata":{"required":true,"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(pl)SDImageCache(im)queryImageForKey:options:context:cacheType:completion:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"queryImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"text":": ","kind":"text"},{"text":"SDImageCacheType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock"},{"text":"?) -> (any ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation"},{"kind":"text","text":")?"}],"role":"symbol","navigatorTitle":[{"text":"queryImageForKey:options:context:cacheType:completion:","kind":"identifier"}],"title":"queryImage(forKey:options:context:cacheType:completion:)","roleHeading":"Instance Method","symbolKind":"method"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/queryimage(forkey:options:context:cachetype:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/queryimage(forkey:options:context:cachetype:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheProtocol"}],"navigatorTitle":[{"text":"SDImageCacheProtocol","kind":"identifier"}],"abstract":[{"text":"This is the image cache protocol to provide custom image cache for ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Though the best practice to custom image cache, is to write your own class which conform ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"code":"SDDiskCache","type":"codeVoice"},{"type":"text","text":" protocol for "},{"code":"SDImageCache","type":"codeVoice"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"However, if your own cache implementation contains more advanced feature beyond ","type":"text"},{"code":"SDImageCache","type":"codeVoice"},{"text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like ","type":"text"},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"title":"SDImageCacheProtocol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image Cache Type"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","url":"\/documentation\/sdwebimage\/sdimagecachetype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheType"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"url":"\/documentation\/sdwebimage\/sdwebimageoperation","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOperation"}],"navigatorTitle":[{"text":"SDWebImageOperation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SDWebImageOperation","abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryCompletionBlock":{"kind":"symbol","type":"topic","title":"SDImageCacheQueryCompletionBlock","url":"\/documentation\/sdwebimage\/sdimagecachequerycompletionblock","role":"symbol","abstract":[],"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryCompletionBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryCompletionBlock","navigatorTitle":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/queryImage(forKey:options:context:cacheType:completion:)":{"abstract":[{"text":"Query the cached image from image cache for given key. The operation can be used to cancel the query.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If image is cached in memory, completion is called synchronously, else asynchronously and depends on the options arg (See "},{"code":"SDWebImageQueryDiskSync","type":"codeVoice"},{"type":"text","text":")"}],"required":true,"role":"symbol","title":"queryImage(forKey:options:context:cacheType:completion:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:cacheType:completion:)","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/queryimage(forkey:options:context:cachetype:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryImage"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"cacheType","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> (any "},{"preciseIdentifier":"c:objc(pl)SDWebImageOperation","text":"SDWebImageOperation","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"navigatorTitle":[{"text":"queryImageForKey:options:context:cacheType:completion:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"queryImageForKey:options:context:cacheType:completion:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"queryImageForKey:options:context:cacheType:completion:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDWebImageOperation","text":"id<SDWebImageOperation>"},{"kind":"text","text":") "},{"kind":"identifier","text":"queryImageForKey:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" *) "},{"text":"key","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"text":" ","kind":"text"},{"text":"context:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","text":"SDWebImageContext","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cacheType:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCacheType","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":") "},{"text":"cacheType","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"completion:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#$@E@SDImageCacheType)","text":"void (^)(UIImage *, NSData *, enum SDImageCacheType)"},{"kind":"text","text":") "},{"text":"completionBlock","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image cache key"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A mask to specify options to use for this query"}]}],"name":"options"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A context contains different options to perform specify changes or processes, see ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextOption"},{"type":"text","text":". This hold the extra objects which "},{"type":"codeVoice","code":"options"},{"text":" enum can not hold. Pass ","type":"text"},{"code":".callbackQueue","type":"codeVoice"},{"text":" to control callback queue","type":"text"}]}],"name":"context"},{"name":"cacheType","content":[{"inlineContent":[{"text":"Specify where to query the cache from. By default we use ","type":"text"},{"code":".all","type":"codeVoice"},{"type":"text","text":", which means both memory cache and disk cache. You can choose to query memory only or disk only as well. Pass "},{"code":".none","type":"codeVoice"},{"text":" is invalid and callback with nil immediately.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The completion block. Will not get called if the operation is cancelled","type":"text"}]}],"name":"completionBlock"}]},"path":"\/primaryContentSections\/1"},{"value":{"content":[{"level":2,"anchor":"return-value","type":"heading","text":"Return Value"},{"type":"paragraph","inlineContent":[{"text":"The operation for this query","type":"text"}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","op":"replace","value":"SDImageCache"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]},{"op":"replace","value":"SDWebImageOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","op":"replace","value":[{"text":"SDWebImageOptions","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","value":"SDImageCacheType"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"value":"SDWebImageOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title"},{"value":[{"text":"SDWebImageOperation","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImageOperation"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/title","op":"replace","value":"SDImageCacheQueryCompletionBlock"},{"value":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryCompletionBlock\/navigatorTitle","op":"replace","value":[{"text":"SDImageCacheQueryCompletionBlock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1queryImage(forKey:options:context:cacheType:completion:)\/title","op":"replace","value":"queryImageForKey:options:context:cacheType:completion:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1queryImage(forKey:options:context:cacheType:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"queryImageForKey:options:context:cacheType:completion:","kind":"identifier"}]}]}]}