{"metadata":{"platforms":[{"name":"iOS","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false},{"unavailable":false,"deprecated":false,"introducedAt":"8.0","beta":false,"name":"iPadOS"},{"introducedAt":"8.0","beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst"}],"modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"store"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageData"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"text":"SDImageCacheType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"externalID":"c:objc(pl)SDImageCache(im)storeImage:imageData:forKey:options:context:cacheType:completion:","symbolKind":"method","role":"symbol","roleHeading":"Instance Method","title":"store(_:imageData:forKey:options:context:cacheType:completion:)","navigatorTitle":[{"kind":"identifier","text":"storeImage:imageData:forKey:options:context:cacheType:completion:"}]},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:options:context:cacheType:completion:)","interfaceLanguage":"swift"},"abstract":[{"text":"Store the image into image cache for the given key. If cache type is memory only, completion is called synchronously, else asynchronously.","type":"text"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"store"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"text":"imageData","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":" "},{"text":"key","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"text":" = [], ","kind":"text"},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"text":"cacheType","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":" ","kind":"text"},{"text":"completionBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"? = nil)"}],"languages":["swift"],"platforms":["iOS"]},{"tokens":[{"kind":"keyword","text":"optional"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"store"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageData"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":" = [], "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"text":"SDWebImageContextOption","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheType","kind":"typeIdentifier","text":"SDImageCacheType","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType"},{"kind":"text","text":") "},{"kind":"keyword","text":"async"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to store"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image data to be used for disk storage"}]}],"name":"imageData"},{"content":[{"inlineContent":[{"text":"The image cache key","type":"text"}],"type":"paragraph"}],"name":"key"},{"content":[{"inlineContent":[{"text":"A mask to specify options to use for this store","type":"text"}],"type":"paragraph"}],"name":"options"},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The context options to use. Pass "},{"type":"codeVoice","code":".callbackQueue"},{"type":"text","text":" to control callback queue"}]}]},{"name":"cacheType","content":[{"inlineContent":[{"text":"The image store op cache type","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block executed after the operation is finished","type":"text"}]}],"name":"completionBlock"}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/store(_:imagedata:forkey:options:context:cachetype:completion:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol\/store(_:imagedata:forkey:options:context:cachetype:completion:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageNoParamsBlock":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageNoParamsBlock","kind":"symbol","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageNoParamsBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagenoparamsblock","title":"SDWebImageNoParamsBlock","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/store(_:imageData:forKey:options:context:cacheType:completion:)":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:options:context:cacheType:completion:)","abstract":[{"text":"Store the image into image cache for the given key. If cache type is memory only, completion is called synchronously, else asynchronously.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"storeImage:imageData:forKey:options:context:cacheType:completion:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/store(_:imagedata:forkey:options:context:cachetype:completion:)","title":"store(_:imageData:forKey:options:context:cacheType:completion:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"store","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageData"},{"text":": ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheProtocol"}],"navigatorTitle":[{"text":"SDImageCacheProtocol","kind":"identifier"}],"abstract":[{"text":"This is the image cache protocol to provide custom image cache for ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Though the best practice to custom image cache, is to write your own class which conform ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"code":"SDDiskCache","type":"codeVoice"},{"type":"text","text":" protocol for "},{"code":"SDImageCache","type":"codeVoice"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"However, if your own cache implementation contains more advanced feature beyond ","type":"text"},{"code":"SDImageCache","type":"codeVoice"},{"text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like ","type":"text"},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"title":"SDImageCacheProtocol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image Cache Type"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","url":"\/documentation\/sdwebimage\/sdimagecachetype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheType"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","path":"\/metadata\/roleHeading","op":"replace"},{"value":"storeImage:imageData:forKey:options:context:cacheType:completion:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"storeImage:imageData:forKey:options:context:cacheType:completion:"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"storeImage:"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageData:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"imageData"},{"kind":"text","text":" "},{"text":"forKey:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"options"},{"text":" ","kind":"text"},{"text":"context:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","kind":"typeIdentifier","text":"SDWebImageContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"cacheType:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheType","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","kind":"typeIdentifier","text":"SDImageCacheType"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cacheType"},{"kind":"text","text":" "},{"text":"completion:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(void)","preciseIdentifier":"c:BFv()","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"completionBlock","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"image","content":[{"inlineContent":[{"text":"The image to store","type":"text"}],"type":"paragraph"}]},{"name":"imageData","content":[{"type":"paragraph","inlineContent":[{"text":"The image data to be used for disk storage","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The image cache key","type":"text"}]}],"name":"key"},{"content":[{"inlineContent":[{"text":"A mask to specify options to use for this store","type":"text"}],"type":"paragraph"}],"name":"options"},{"name":"context","content":[{"inlineContent":[{"type":"text","text":"The context options to use. Pass "},{"code":".callbackQueue","type":"codeVoice"},{"type":"text","text":" to control callback queue"}],"type":"paragraph"}]},{"name":"cacheType","content":[{"inlineContent":[{"text":"The image store op cache type","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block executed after the operation is finished"}]}],"name":"completionBlock"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/title","value":"SDWebImageNoParamsBlock"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/fragments","value":[{"text":"SDWebImageNoParamsBlock","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageNoParamsBlock\/navigatorTitle","value":[{"text":"SDWebImageNoParamsBlock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1store(_:imageData:forKey:options:context:cacheType:completion:)\/title","value":"storeImage:imageData:forKey:options:context:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1store(_:imageData:forKey:options:context:cacheType:completion:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"storeImage:imageData:forKey:options:context:cacheType:completion:"}]},{"op":"replace","value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title"},{"op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle"},{"value":"SDImageCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title"},{"op":"replace","value":[{"text":"SDImageCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCache"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","op":"replace","value":"SDWebImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"text":"SDWebImageOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageOptions"}],"op":"replace"},{"value":"SDImageCacheType","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","op":"replace","value":[{"text":"SDImageCacheType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/navigatorTitle","value":[{"text":"SDImageCacheType","kind":"identifier"}]}]}]}