{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class\/cachekeyfilterwithblock:"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/cacheKeyFilterWithBlock:","interfaceLanguage":"occ"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class"]]},"metadata":{"symbolKind":"method","role":"symbol","title":"cacheKeyFilterWithBlock:","fragments":[{"text":"+ ","kind":"text"},{"text":"cacheKeyFilterWithBlock:","kind":"identifier"}],"navigatorTitle":[{"text":"cacheKeyFilterWithBlock:","kind":"identifier"}],"externalID":"c:objc(cs)SDWebImageCacheKeyFilter(cm)cacheKeyFilterWithBlock:","roleHeading":"Type Method","modules":[{"name":"SDWebImage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"identifier","text":"cacheKeyFilterWithBlock:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:BF*$objc(cs)NSString(#*$objc(cs)NSURL)","text":"NSString *(^)(NSURL *)"},{"text":") ","kind":"text"},{"text":"block","kind":"internalParam"},{"text":";","kind":"text"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilter-swift.class/cacheKeyFilterWithBlock:":{"abstract":[],"title":"cacheKeyFilterWithBlock:","navigatorTitle":[{"kind":"identifier","text":"cacheKeyFilterWithBlock:"}],"fragments":[{"kind":"text","text":"+ "},{"text":"cacheKeyFilterWithBlock:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/cacheKeyFilterWithBlock:","url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class\/cachekeyfilterwithblock:","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilter-swift.class":{"role":"symbol","kind":"symbol","title":"SDWebImageCacheKeyFilter","url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class","navigatorTitle":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A cache key filter class with block."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SDWebImageCacheKeyFilter","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/navigatorTitle"}]}]}