{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/badimagedata"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/badImageData","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","symbolKind":"property","title":"badImageData","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badImageData"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC15SDWebImageErrorLeV","text":"SDWebImageError","kind":"typeIdentifier"},{"kind":"text","text":"."},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageError"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","externalID":"s:SC15SDWebImageErrorLeV03badB4DataSoAAVvpZ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"badImageData"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SC15SDWebImageErrorLeV","kind":"typeIdentifier","text":"SDWebImageError","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct"},{"text":".","kind":"text"},{"text":"Code","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","preciseIdentifier":"c:@E@SDWebImageError"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/badImageData":{"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/badImageData","type":"topic","title":"badImageData","abstract":[],"url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/badimagedata","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"badImageData","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageError","kind":"typeIdentifier","preciseIdentifier":"s:SC15SDWebImageErrorLeV"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageError","text":"Code"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct":{"title":"SDWebImageError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageError"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code":{"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","title":"SDWebImageError.Code","abstract":[{"type":"text","text":"SDWebImage error domain and codes"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SDWebImageError","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/fragments","op":"replace","value":[{"text":"SDWebImageError","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDWebImageError"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/navigatorTitle"}]}]}