{"metadata":{"symbolKind":"property","title":"invalidDownloadStatusCode","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Property","role":"symbol","externalID":"s:SC15SDWebImageErrorLeV25invalidDownloadStatusCodeSoAAVvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidDownloadStatusCode","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC15SDWebImageErrorLeV","text":"SDWebImageError"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageError","text":"Code","kind":"typeIdentifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidDownloadStatusCode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC15SDWebImageErrorLeV","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","text":"SDWebImageError","kind":"typeIdentifier"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@SDWebImageError","text":"Code","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/invaliddownloadstatuscode"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/invalidDownloadStatusCode"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct":{"title":"SDWebImageError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageError"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code":{"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","title":"SDWebImageError.Code","abstract":[{"type":"text","text":"SDWebImage error domain and codes"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/invalidDownloadStatusCode":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/invalidDownloadStatusCode","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/invaliddownloadstatuscode","abstract":[],"kind":"symbol","role":"symbol","title":"invalidDownloadStatusCode","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"invalidDownloadStatusCode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageError","kind":"typeIdentifier","preciseIdentifier":"s:SC15SDWebImageErrorLeV"},{"text":".","kind":"text"},{"text":"Code","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageError"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SDWebImageError","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/fragments","value":[{"text":"SDWebImageError","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/navigatorTitle","value":[{"text":"SDWebImageError","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}