{"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidDownloadContentType"},{"text":": ","kind":"text"},{"text":"SDWebImageError","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","kind":"typeIdentifier","preciseIdentifier":"s:SC15SDWebImageErrorLeV"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageError","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","text":"Code","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/invalidDownloadContentType","interfaceLanguage":"swift"},"metadata":{"roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"role":"symbol","title":"invalidDownloadContentType","symbolKind":"property","externalID":"s:SC15SDWebImageErrorLeV26invalidDownloadContentTypeSoAAVvpZ","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDownloadContentType"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SC15SDWebImageErrorLeV","text":"SDWebImageError","kind":"typeIdentifier"},{"text":".","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageError","text":"Code"}]},"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/invaliddownloadcontenttype"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct"]]},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct":{"title":"SDWebImageError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageError"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/invalidDownloadContentType":{"abstract":[],"kind":"symbol","title":"invalidDownloadContentType","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidDownloadContentType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SC15SDWebImageErrorLeV","text":"SDWebImageError"},{"text":".","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageError","kind":"typeIdentifier","text":"Code"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/invalidDownloadContentType","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/invaliddownloadcontenttype","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code":{"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","title":"SDWebImageError.Code","abstract":[{"type":"text","text":"SDWebImage error domain and codes"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/title","op":"replace","value":"SDWebImageError"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"SDWebImageError"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageError"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}