{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"text":"transformers","kind":"externalParam"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageTransformer","kind":"typeIdentifier","text":"SDImageTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"},{"kind":"text","text":"])"}]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)SDImagePipelineTransformer(cm)transformerWithTransformers:","title":"init(transformers:)","fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"transformers","kind":"externalParam"},{"text":": [any ","kind":"text"},{"text":"SDImageTransformer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageTransformer"},{"text":"])","kind":"text"}],"symbolKind":"init","modules":[{"name":"SDWebImage"}],"roleHeading":"Initializer","navigatorTitle":[{"kind":"identifier","text":"transformerWithTransformers:"}],"role":"symbol"},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/init(transformers:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer\/init(transformers:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer\/init(transformers:)"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImagePipelineTransformer","kind":"identifier"}],"type":"topic","title":"SDImagePipelineTransformer","abstract":[{"text":"Pipeline transformer. Which you can bind multiple transformers together to let the image to be transformed one by one in order and generate the final image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer/init(transformers:)":{"title":"init(transformers:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"transformers"},{"text":": [any ","kind":"text"},{"text":"SDImageTransformer","preciseIdentifier":"c:objc(pl)SDImageTransformer","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/init(transformers:)","navigatorTitle":[{"kind":"identifier","text":"transformerWithTransformers:"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer\/init(transformers:)","role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"transformerWithTransformers:","path":"\/metadata\/title","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithTransformers:","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"kind":"text","text":") "},{"text":"transformerWithTransformers:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<id<SDImageTransformer>>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"transformers","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/title","op":"replace","value":"SDImagePipelineTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/fragments","value":[{"text":"SDImagePipelineTransformer","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/navigatorTitle"},{"value":"SDImageTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title"},{"value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace"},{"value":"transformerWithTransformers:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1init(transformers:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1init(transformers:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"transformerWithTransformers:"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}