{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer"]]},"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"symbolKind":"property","externalID":"c:objc(cs)SDImagePipelineTransformer(py)preserveImageMetadata","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preserveImageMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"role":"symbol","title":"preserveImageMetadata","roleHeading":"Instance Property","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"preserveImageMetadata"}]},"abstract":[{"type":"text","text":"For pipeline transformer, this property is readonly and always return NO. We handle each transformer’s choice inside implementation"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer\/preserveimagemetadata"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer\/preserveimagemetadata"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preserveImageMetadata","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/preserveImageMetadata"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer/preserveImageMetadata":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer\/preserveimagemetadata","title":"preserveImageMetadata","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/preserveImageMetadata","navigatorTitle":[{"text":"preserveImageMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"For pipeline transformer, this property is readonly and always return NO. We handle each transformer’s choice inside implementation","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preserveImageMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImagePipelineTransformer","kind":"identifier"}],"type":"topic","title":"SDImagePipelineTransformer","abstract":[{"text":"Pipeline transformer. Which you can bind multiple transformers together to let the image to be transformed one by one in order and generate the final image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"preserveImageMetadata","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"preserveImageMetadata","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"preserveImageMetadata","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1preserveImageMetadata\/title","op":"replace","value":"preserveImageMetadata"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1preserveImageMetadata\/fragments","value":[{"text":"preserveImageMetadata","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/title","op":"replace","value":"SDImagePipelineTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/fragments","value":[{"text":"SDImagePipelineTransformer","kind":"identifier"}]},{"value":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}