{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","preciseIdentifier":"c:objc(pl)SDImageTransformer","text":"SDImageTransformer"},{"kind":"text","text":"] { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer\/transformers"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer\/transformers"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/transformers","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"All transformers in pipeline"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageTransformer","preciseIdentifier":"c:objc(pl)SDImageTransformer"},{"kind":"text","text":"]"}],"title":"transformers","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImagePipelineTransformer(py)transformers","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"transformers"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer":{"role":"symbol","title":"SDImagePipelineTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePipelineTransformer"}],"abstract":[{"type":"text","text":"Pipeline transformer. Which you can bind multiple transformers together to let the image to be transformed one by one in order and generate the final image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImagePipelineTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer/transformers":{"role":"symbol","title":"transformers","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageTransformer","preciseIdentifier":"c:objc(pl)SDImageTransformer"},{"kind":"text","text":"]"}],"abstract":[{"type":"text","text":"All transformers in pipeline"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/transformers","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transformers"}],"url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer\/transformers"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"role":"symbol","title":"SDImageTransformer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageTransformer"}],"abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"type":"text","text":"You can provide transformer to cache and manager (Through the "},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"type":"codeVoice","code":"SDWebImageContextImageTransformer"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagetransformer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"transformers"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"transformers"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSArray<id<SDImageTransformer>>","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"kind":"text","text":" * "},{"kind":"identifier","text":"transformers"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/title","value":"SDImagePipelineTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/fragments","value":[{"kind":"identifier","text":"SDImagePipelineTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1transformers\/title","value":"transformers"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1transformers\/fragments","value":[{"kind":"identifier","text":"transformers"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","value":"SDImageTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageTransformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}