{"sections":[],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scaleMode"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","text":"SDImageScaleMode","preciseIdentifier":"c:@E@SDImageScaleMode","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer\/init(size:scaleMode:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageresizingtransformer\/init(size:scalemode:)"]},{"paths":["\/documentation\/sdwebimage\/sdimageresizingtransformer\/init(size:scalemode:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer"]]},"kind":"symbol","metadata":{"symbolKind":"init","roleHeading":"Initializer","title":"init(size:scaleMode:)","externalID":"c:objc(cs)SDImageResizingTransformer(cm)transformerWithSize:scaleMode:","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"size"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"scaleMode"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageScaleMode","text":"SDImageScaleMode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"transformerWithSize:scaleMode:","kind":"identifier"}],"role":"symbol"},"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageResizingTransformer/init(size:scaleMode:)":{"type":"topic","role":"symbol","fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scaleMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageScaleMode","text":"SDImageScaleMode"},{"kind":"text","text":")"}],"title":"init(size:scaleMode:)","abstract":[],"navigatorTitle":[{"text":"transformerWithSize:scaleMode:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer\/init(size:scaleMode:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageresizingtransformer\/init(size:scalemode:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageResizingTransformer":{"navigatorTitle":[{"text":"SDImageResizingTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageresizingtransformer","title":"SDImageResizingTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","type":"topic","abstract":[{"type":"text","text":"Image resizing transformer"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageResizingTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode":{"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleMode"}],"url":"\/documentation\/sdwebimage\/sdimagescalemode","title":"SDImageScaleMode","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","type":"topic","abstract":[{"type":"text","text":"The scale mode to apply when image drawing on a container with different sizes."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageScaleMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"transformerWithSize:scaleMode:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"+ "},{"text":"transformerWithSize:scaleMode:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"text":"id","preciseIdentifier":"c:*Qo","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"transformerWithSize:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":") ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaleMode:"},{"text":"(","kind":"text"},{"text":"SDImageScaleMode","preciseIdentifier":"c:@E@SDImageScaleMode","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"scaleMode","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer~1init(size:scaleMode:)\/title","value":"transformerWithSize:scaleMode:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer~1init(size:scaleMode:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"transformerWithSize:scaleMode:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/title","value":"SDImageResizingTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/fragments","value":[{"text":"SDImageResizingTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageResizingTransformer"}],"op":"replace"},{"value":"SDImageScaleMode","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/title"},{"value":[{"text":"SDImageScaleMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/navigatorTitle","value":[{"text":"SDImageScaleMode","kind":"identifier"}]}]}]}