{"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageresizingtransformer\/scalemode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageresizingtransformer\/scalemode"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:objc(cs)SDImageResizingTransformer(py)scaleMode","title":"scaleMode","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"scaleMode"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaleMode","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageScaleMode","text":"SDImageScaleMode","kind":"typeIdentifier"}],"roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer\/scaleMode"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer"]]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaleMode","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","kind":"typeIdentifier","text":"SDImageScaleMode","preciseIdentifier":"c:@E@SDImageScaleMode"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"sections":[],"abstract":[{"text":"The scale mode for image content.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageResizingTransformer":{"navigatorTitle":[{"text":"SDImageResizingTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageresizingtransformer","title":"SDImageResizingTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","type":"topic","abstract":[{"type":"text","text":"Image resizing transformer"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageResizingTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageResizingTransformer/scaleMode":{"title":"scaleMode","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer\/scaleMode","type":"topic","navigatorTitle":[{"text":"scaleMode","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageresizingtransformer\/scalemode","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"scaleMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageScaleMode","text":"SDImageScaleMode","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The scale mode for image content."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode":{"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleMode"}],"url":"\/documentation\/sdwebimage\/sdimagescalemode","title":"SDImageScaleMode","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","type":"topic","abstract":[{"type":"text","text":"The scale mode to apply when image drawing on a container with different sizes."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageScaleMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"scaleMode","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"scaleMode","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","text":"SDImageScaleMode","preciseIdentifier":"c:@E@SDImageScaleMode"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleMode"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/title","value":"SDImageResizingTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageResizingTransformer"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/navigatorTitle","value":[{"text":"SDImageResizingTransformer","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"scaleMode","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer~1scaleMode\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer~1scaleMode\/fragments","value":[{"kind":"identifier","text":"scaleMode"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/title","value":"SDImageScaleMode"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageScaleMode"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageScaleMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}