{"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage"]]},"abstract":[{"type":"text","text":"Inherited from "},{"code":"UIViewRepresentable.Coordinator","type":"codeVoice"},{"text":".","type":"text"}],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimageswiftui\/animatedimage\/coordinator"]}],"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage\/Coordinator","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"Coordinator"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"platforms":[{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iOS"},{"name":"iPadOS","deprecated":false,"beta":false,"introducedAt":"14.0","unavailable":false},{"name":"Mac Catalyst","introducedAt":"14.0","unavailable":false,"deprecated":false,"beta":false},{"introducedAt":"11.0","name":"macOS","unavailable":false,"beta":false,"deprecated":false},{"introducedAt":"14.0","beta":false,"name":"tvOS","deprecated":false,"unavailable":false},{"introducedAt":"7.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}],"roleHeading":"Type Alias","symbolKind":"typealias","role":"symbol","modules":[{"name":"SDWebImageSwiftUI"}],"title":"AnimatedImage.Coordinator","externalID":"s:17SDWebImageSwiftUI08AnimatedB0V11Coordinatora"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"Coordinator"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"AnimatedImageCoordinator","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","preciseIdentifier":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageCoordinator"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator":{"abstract":[{"text":"A coordinator object used for ","type":"text"},{"type":"codeVoice","code":"AnimatedImage"},{"type":"text","text":"native view  bridge for UIKit\/AppKit."}],"title":"AnimatedImageCoordinator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AnimatedImageCoordinator","kind":"identifier"}],"navigatorTitle":[{"text":"AnimatedImageCoordinator","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","type":"topic","kind":"symbol"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage/Coordinator":{"abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Coordinator","kind":"identifier"}],"type":"topic","navigatorTitle":[{"text":"Coordinator","kind":"identifier"}],"title":"AnimatedImage.Coordinator","url":"\/documentation\/sdwebimageswiftui\/animatedimage\/coordinator","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage\/Coordinator","role":"symbol","kind":"symbol"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimatedImage","kind":"identifier"}],"abstract":[{"text":"A Image View type to load image from url, data or bundle. Supports animated and static image format.","type":"text"}],"title":"AnimatedImage","url":"\/documentation\/sdwebimageswiftui\/animatedimage","type":"topic","role":"symbol","navigatorTitle":[{"text":"AnimatedImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"AnimatedImageCoordinator","op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/fragments","value":[{"kind":"identifier","text":"AnimatedImageCoordinator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/navigatorTitle","value":[{"text":"AnimatedImageCoordinator","kind":"identifier"}]}]}]}