{"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage"]]},"kind":"symbol","metadata":{"modules":[{"name":"SDWebImageSwiftUI"}],"title":"makeUIView(context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"makeUIView"},{"kind":"text","text":"("},{"text":"context","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper","text":"AnimatedImageViewWrapper","kind":"typeIdentifier"}],"symbolKind":"method","roleHeading":"Instance Method","externalID":"s:17SDWebImageSwiftUI08AnimatedB0V10makeUIView7contextAA0eB11ViewWrapperC0cD00G20RepresentableContextVyACG_tF","platforms":[{"unavailable":false,"deprecated":false,"beta":false,"name":"iOS","introducedAt":"14.0"},{"deprecated":false,"introducedAt":"14.0","name":"iPadOS","beta":false,"unavailable":false},{"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false},{"name":"macOS","unavailable":false,"beta":false,"introducedAt":"11.0","deprecated":false},{"beta":false,"deprecated":false,"introducedAt":"14.0","name":"tvOS","unavailable":false},{"deprecated":false,"unavailable":false,"introducedAt":"7.0","name":"watchOS","beta":false}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"makeUIView","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"context"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Context","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"text":") -> ","kind":"text"},{"text":"AnimatedImageViewWrapper","preciseIdentifier":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper","kind":"typeIdentifier","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper"}],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage\/makeUIView(context:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimage\/makeuiview(context:)"],"traits":[{"interfaceLanguage":"swift"}]}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"UIViewRepresentable.makeUIView(context:)","type":"codeVoice"},{"type":"text","text":"."}],"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"title":"AnimatedImageViewWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"type":"topic","navigatorTitle":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage/makeUIView(context:)":{"title":"makeUIView(context:)","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage\/makeUIView(context:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"makeUIView","kind":"identifier"},{"text":"(","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Context","kind":"typeIdentifier","preciseIdentifier":"s:7SwiftUI19UIViewRepresentableP7Contexta"},{"kind":"text","text":") -> "},{"text":"AnimatedImageViewWrapper","preciseIdentifier":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/sdwebimageswiftui\/animatedimage\/makeuiview(context:)","type":"topic","abstract":[]},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimatedImage","kind":"identifier"}],"abstract":[{"text":"A Image View type to load image from url, data or bundle. Supports animated and static image format.","type":"text"}],"title":"AnimatedImage","url":"\/documentation\/sdwebimageswiftui\/animatedimage","type":"topic","role":"symbol","navigatorTitle":[{"text":"AnimatedImage","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"AnimatedImageViewWrapper","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title"},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments","value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/navigatorTitle","op":"replace","value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}]}]}]}