{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlatformViewType","kind":"identifier"},{"text":" = ","kind":"text"},{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","text":"AnimatedImageViewWrapper","kind":"typeIdentifier","preciseIdentifier":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage\/PlatformViewType"},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimage\/platformviewtype"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","metadata":{"title":"AnimatedImage.PlatformViewType","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"PlatformViewType","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"PlatformViewType"}],"symbolKind":"typealias","modules":[{"name":"SDWebImageSwiftUI"}],"externalID":"s:17SDWebImageSwiftUI08AnimatedB0V16PlatformViewTypea","roleHeading":"Type Alias","platforms":[{"introducedAt":"14.0","name":"iOS","unavailable":false,"beta":false,"deprecated":false},{"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false},{"name":"Mac Catalyst","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"beta":false,"name":"macOS","introducedAt":"11.0","deprecated":false,"unavailable":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"tvOS","introducedAt":"14.0"},{"unavailable":false,"name":"watchOS","introducedAt":"7.0","deprecated":false,"beta":false}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage"]]},"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage","kind":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"AnimatedImage","kind":"identifier"}],"abstract":[{"text":"A Image View type to load image from url, data or bundle. Supports animated and static image format.","type":"text"}],"title":"AnimatedImage","url":"\/documentation\/sdwebimageswiftui\/animatedimage","type":"topic","role":"symbol","navigatorTitle":[{"text":"AnimatedImage","kind":"identifier"}]},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImage/PlatformViewType":{"role":"symbol","url":"\/documentation\/sdwebimageswiftui\/animatedimage\/platformviewtype","navigatorTitle":[{"kind":"identifier","text":"PlatformViewType"}],"kind":"symbol","title":"AnimatedImage.PlatformViewType","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"PlatformViewType","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImage\/PlatformViewType","abstract":[]},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"title":"AnimatedImageViewWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"type":"topic","navigatorTitle":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title","value":"AnimatedImageViewWrapper","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments","value":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}]},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AnimatedImageViewWrapper"}]}]}]}