{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder"]]},"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderFIFOExecutionOrder"}],"title":"SDWebImageDownloaderExecutionOrder.fifoExecutionOrder","symbolKind":"case","modules":[{"name":"SDWebImage"}],"roleHeading":"Case","externalID":"c:@E@SDWebImageDownloaderExecutionOrder@SDWebImageDownloaderFIFOExecutionOrder","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"fifoExecutionOrder","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"fifoExecutionOrder"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Default value. All download operations will execute in queue style (first-in-first-out).","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder\/fifoexecutionorder"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder\/fifoexecutionorder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder\/fifoExecutionOrder"},"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderExecutionOrder":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderExecutionOrder"}],"title":"SDWebImageDownloaderExecutionOrder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderExecutionOrder","kind":"identifier"}],"abstract":[{"type":"text","text":"Operation execution order"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderExecutionOrder/fifoExecutionOrder":{"title":"SDWebImageDownloaderExecutionOrder.fifoExecutionOrder","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"fifoExecutionOrder"}],"type":"topic","abstract":[{"type":"text","text":"Default value. All download operations will execute in queue style (first-in-first-out)."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder\/fifoExecutionOrder","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderFIFOExecutionOrder"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder\/fifoexecutionorder","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageDownloaderFIFOExecutionOrder"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderFIFOExecutionOrder"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDWebImageDownloaderFIFOExecutionOrder"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder\/title","value":"SDWebImageDownloaderExecutionOrder","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderExecutionOrder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder\/navigatorTitle","value":[{"text":"SDWebImageDownloaderExecutionOrder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder~1fifoExecutionOrder\/title","value":"SDWebImageDownloaderFIFOExecutionOrder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder~1fifoExecutionOrder\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderFIFOExecutionOrder"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}