{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder\/lifoExecutionOrder","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder\/lifoexecutionorder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder\/lifoexecutionorder"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder"]]},"kind":"symbol","sections":[],"metadata":{"role":"symbol","symbolKind":"case","title":"SDWebImageDownloaderExecutionOrder.lifoExecutionOrder","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderLIFOExecutionOrder"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:@E@SDWebImageDownloaderExecutionOrder@SDWebImageDownloaderLIFOExecutionOrder","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"lifoExecutionOrder","kind":"identifier"}],"roleHeading":"Case"},"abstract":[{"type":"text","text":"All download operations will execute in stack style (last-in-first-out)."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"lifoExecutionOrder","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderExecutionOrder":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderExecutionOrder"}],"title":"SDWebImageDownloaderExecutionOrder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderExecutionOrder","kind":"identifier"}],"abstract":[{"type":"text","text":"Operation execution order"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderExecutionOrder/lifoExecutionOrder":{"role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderLIFOExecutionOrder","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderexecutionorder\/lifoexecutionorder","abstract":[{"type":"text","text":"All download operations will execute in stack style (last-in-first-out)."}],"title":"SDWebImageDownloaderExecutionOrder.lifoExecutionOrder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderExecutionOrder\/lifoExecutionOrder","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"lifoExecutionOrder"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderLIFOExecutionOrder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderLIFOExecutionOrder","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SDWebImageDownloaderLIFOExecutionOrder"}]}]}},{"value":"SDWebImageDownloaderExecutionOrder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder\/fragments","value":[{"text":"SDWebImageDownloaderExecutionOrder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderExecutionOrder"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder~1lifoExecutionOrder\/title","value":"SDWebImageDownloaderLIFOExecutionOrder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderExecutionOrder~1lifoExecutionOrder\/fragments","value":[{"text":"SDWebImageDownloaderLIFOExecutionOrder","kind":"identifier"}]}]}]}