{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"indicatorView","kind":"identifier"},{"kind":"text","text":": "},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The indicator view"}]}],"kind":"content"}],"metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","required":true,"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"text":": ","kind":"text"},{"text":"UIView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIView"}],"title":"indicatorView","platforms":[{"unavailable":false,"name":"iOS","deprecated":false,"introducedAt":"2.0","beta":false},{"name":"iPadOS","deprecated":false,"introducedAt":"2.0","unavailable":false,"beta":false},{"unavailable":false,"introducedAt":"2.0","beta":false,"name":"Mac Catalyst","deprecated":false}],"externalID":"c:objc(pl)SDWebImageIndicator(py)indicatorView","navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"symbolKind":"property"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator"]]},"abstract":[{"type":"text","text":"The view associate to the indicator."}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/indicatorView"},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/indicatorview"]},{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/indicatorview"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","abstract":[{"text":"A protocol to custom the indicator during the image loading.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageIndicator","kind":"identifier"}],"kind":"symbol","title":"SDWebImageIndicator","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/indicatorView":{"navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageindicator\/indicatorview","kind":"symbol","abstract":[{"type":"text","text":"The view associate to the indicator."}],"title":"indicatorView","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/indicatorView","required":true,"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicatorView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIView","text":"UIView","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"indicatorView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"text":"indicatorView","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"indicatorView"},{"text":";","kind":"text"}]}]}},{"op":"replace","value":"SDWebImageIndicator","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageIndicator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]},{"value":"indicatorView","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1indicatorView\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1indicatorView\/fragments","op":"replace","value":[{"text":"indicatorView","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}