{"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/startanimatingindicator()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/startanimatingindicator()"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"type":"text","text":"Start the animating for indicator."}],"metadata":{"roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"startAnimatingIndicator","kind":"identifier"},{"kind":"text","text":"()"}],"title":"startAnimatingIndicator()","modules":[{"name":"SDWebImage"}],"required":true,"externalID":"c:objc(pl)SDWebImageIndicator(im)startAnimatingIndicator","role":"symbol","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"startAnimatingIndicator"}]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/startAnimatingIndicator()","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startAnimatingIndicator"},{"kind":"text","text":"()"}],"languages":["swift"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","abstract":[{"text":"A protocol to custom the indicator during the image loading.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageIndicator","kind":"identifier"}],"kind":"symbol","title":"SDWebImageIndicator","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/startAnimatingIndicator()":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/startAnimatingIndicator()","role":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"startAnimatingIndicator"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator\/startanimatingindicator()","abstract":[{"type":"text","text":"Start the animating for indicator."}],"title":"startAnimatingIndicator()","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimatingIndicator"},{"text":"()","kind":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"op":"replace","value":"startAnimatingIndicator","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAnimatingIndicator"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"text":"startAnimatingIndicator","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SDWebImageIndicator","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]},{"op":"replace","value":[{"text":"SDWebImageIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/navigatorTitle"},{"value":"startAnimatingIndicator","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1startAnimatingIndicator()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1startAnimatingIndicator()\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"startAnimatingIndicator","kind":"identifier"}]}]}]}