{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAnimatingIndicator"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/stopanimatingindicator()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/stopanimatingindicator()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/stopAnimatingIndicator()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Stop the animating for indicator."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"stopAnimatingIndicator"}],"role":"symbol","title":"stopAnimatingIndicator()","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAnimatingIndicator"},{"kind":"text","text":"()"}],"symbolKind":"method","externalID":"c:objc(pl)SDWebImageIndicator(im)stopAnimatingIndicator","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/stopAnimatingIndicator()":{"navigatorTitle":[{"kind":"identifier","text":"stopAnimatingIndicator"}],"role":"symbol","title":"stopAnimatingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAnimatingIndicator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stop the animating for indicator."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/stopAnimatingIndicator()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator\/stopanimatingindicator()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"role":"symbol","title":"SDWebImageIndicator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageIndicator"}],"abstract":[{"type":"text","text":"A protocol to custom the indicator during the image loading."},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"stopAnimatingIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAnimatingIndicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"stopAnimatingIndicator"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1stopAnimatingIndicator()\/title","value":"stopAnimatingIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1stopAnimatingIndicator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAnimatingIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title","value":"SDWebImageIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}