{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateProgress"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The progress, value between 0 and 1.0"}],"type":"paragraph"}],"name":"progress"}],"kind":"parameters"}],"abstract":[{"text":"Update the loading progress (0-1.0) for indicator. Optional","type":"text"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/updateProgress(_:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"updateIndicatorProgress:","kind":"identifier"}],"title":"updateProgress(_:)","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"updateProgress"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":")","kind":"text"}],"symbolKind":"method","externalID":"c:objc(pl)SDWebImageIndicator(im)updateIndicatorProgress:","roleHeading":"Instance Method","modules":[{"name":"SDWebImage"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/updateprogress(_:)"]},{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator\/updateprogress(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/updateProgress(_:)":{"role":"symbol","abstract":[{"text":"Update the loading progress (0-1.0) for indicator. Optional","type":"text"}],"type":"topic","navigatorTitle":[{"text":"updateIndicatorProgress:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageindicator\/updateprogress(_:)","kind":"symbol","title":"updateProgress(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/updateProgress(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"updateProgress","kind":"identifier"},{"kind":"text","text":"("},{"text":"Double","kind":"typeIdentifier","preciseIdentifier":"s:Sd"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","abstract":[{"text":"A protocol to custom the indicator during the image loading.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageIndicator","kind":"identifier"}],"kind":"symbol","title":"SDWebImageIndicator","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"updateIndicatorProgress:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"updateIndicatorProgress:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"identifier","text":"updateIndicatorProgress:"},{"kind":"text","text":"("},{"text":"double","preciseIdentifier":"c:d","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"progress","kind":"internalParam"},{"text":";","kind":"text"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"parameters":[{"content":[{"inlineContent":[{"text":"The progress, value between 0 and 1.0","type":"text"}],"type":"paragraph"}],"name":"progress"}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1updateProgress(_:)\/title","value":"updateIndicatorProgress:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1updateProgress(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateIndicatorProgress:"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title","value":"SDWebImageIndicator"},{"op":"replace","value":[{"text":"SDWebImageIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]}]}]}