{"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decoder"},{"text":": ","kind":"text"},{"text":"YYImageDecoder","preciseIdentifier":"c:objc(cs)YYImageDecoder","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This property is only useful for static progressive or animation decoding. For normal decoding process, we will use a temporary ","type":"text"},{"type":"codeVoice","code":"YYImageDecoder"},{"type":"text","text":" to do decoding because it does not need to keep decoded context."}]}]}],"kind":"content"}],"metadata":{"roleHeading":"Instance Property","navigatorTitle":[{"text":"decoder","kind":"identifier"}],"modules":[{"name":"SDWebImageYYPlugin"}],"symbolKind":"property","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoder"},{"kind":"text","text":": "},{"text":"YYImageDecoder","preciseIdentifier":"c:objc(cs)YYImageDecoder","kind":"typeIdentifier"}],"externalID":"c:objc(cs)SDImageYYCoder(py)decoder","title":"decoder","role":"symbol"},"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"]]},"sections":[],"abstract":[{"type":"text","text":"The wrapped "},{"type":"codeVoice","code":"YYImageDecoder"},{"type":"text","text":" instance, to support static progressive and animation decoding."}],"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/decoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/decoder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/decoder","interfaceLanguage":"swift"},"references":{"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin":{"url":"\/documentation\/sdwebimageyyplugin","type":"topic","title":"SDWebImageYYPlugin","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","abstract":[],"role":"collection"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder":{"type":"topic","abstract":[{"text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in ","type":"text"},{"type":"codeVoice","code":"YYImageType"},{"text":".","type":"text"}],"role":"symbol","title":"SDImageYYCoder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageYYCoder"}],"navigatorTitle":[{"text":"SDImageYYCoder","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder/decoder":{"navigatorTitle":[{"kind":"identifier","text":"decoder"}],"kind":"symbol","type":"topic","role":"symbol","abstract":[{"type":"text","text":"The wrapped "},{"code":"YYImageDecoder","type":"codeVoice"},{"type":"text","text":" instance, to support static progressive and animation decoding."}],"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/decoder","title":"decoder","url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/decoder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decoder"},{"kind":"text","text":": "},{"text":"YYImageDecoder","preciseIdentifier":"c:objc(cs)YYImageDecoder","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"decoder","path":"\/metadata\/title","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"decoder"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)YYImageDecoder","text":"YYImageDecoder"},{"kind":"text","text":" * "},{"kind":"identifier","text":"decoder"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/title","value":"SDImageYYCoder"},{"value":[{"text":"SDImageYYCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/navigatorTitle","value":[{"text":"SDImageYYCoder","kind":"identifier"}]},{"value":"decoder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1decoder\/title"},{"value":[{"kind":"identifier","text":"decoder"}],"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1decoder\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}