{"kind":"symbol","metadata":{"symbolKind":"init","title":"init(incrementalWithOptions:)","modules":[{"name":"SDWebImageYYPlugin"}],"fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"incrementalWithOptions"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier","text":"SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"role":"symbol","roleHeading":"Initializer","externalID":"c:objc(pl)SDProgressiveImageCoder(im)initIncrementalWithOptions:::SYNTHESIZED::c:objc(cs)SDImageYYCoder"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"SDImageYYCoder.init(incrementalWithOptions:)"},{"text":".","type":"text"}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/init(incrementalWithOptions:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"incrementalWithOptions","kind":"externalParam"},{"kind":"text","text":" "},{"text":"options","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"]]},"variants":[{"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/init(incrementalwithoptions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin":{"role":"collection","title":"SDWebImageYYPlugin","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","url":"\/documentation\/sdwebimageyyplugin","kind":"symbol"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder":{"url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder","title":"SDImageYYCoder","type":"topic","abstract":[{"type":"text","text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in "},{"type":"codeVoice","code":"YYImageType"},{"type":"text","text":"."}],"kind":"symbol","navigatorTitle":[{"text":"SDImageYYCoder","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDImageYYCoder","kind":"identifier"}]},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder/init(incrementalWithOptions:)":{"role":"symbol","title":"init(incrementalWithOptions:)","abstract":[],"type":"topic","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/init(incrementalWithOptions:)","url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/init(incrementalwithoptions:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"incrementalWithOptions"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/title","value":"SDImageYYCoder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/fragments","value":[{"kind":"identifier","text":"SDImageYYCoder"}]},{"value":[{"kind":"identifier","text":"SDImageYYCoder"}],"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}