{"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/init(animatedImageData:options:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"]]},"variants":[{"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/init(animatedimagedata:options:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"init","kind":"keyword"},{"kind":"text","text":"?("},{"text":"animatedImageData","kind":"externalParam"},{"kind":"text","text":" "},{"text":"data","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]? = nil)","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"SDImageYYCoder.init(animatedImageData:options:)"},{"type":"text","text":"."}],"metadata":{"roleHeading":"Initializer","title":"init(animatedImageData:options:)","modules":[{"name":"SDWebImageYYPlugin"}],"externalID":"c:objc(pl)SDAnimatedImageCoder(im)initWithAnimatedImageData:options:::SYNTHESIZED::c:objc(cs)SDImageYYCoder","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"animatedImageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"symbolKind":"init","role":"symbol"},"references":{"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder":{"navigatorTitle":[{"kind":"identifier","text":"SDImageYYCoder"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageYYCoder"}],"url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder","abstract":[{"text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in ","type":"text"},{"code":"YYImageType","type":"codeVoice"},{"text":".","type":"text"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder","role":"symbol","title":"SDImageYYCoder"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder/init(animatedImageData:options:)":{"url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/init(animatedimagedata:options:)","abstract":[],"kind":"symbol","title":"init(animatedImageData:options:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"animatedImageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"type":"topic","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/init(animatedImageData:options:)","role":"symbol"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin":{"url":"\/documentation\/sdwebimageyyplugin","type":"topic","title":"SDWebImageYYPlugin","kind":"symbol","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","abstract":[],"role":"collection"}},"variantOverrides":[{"patch":[{"value":"SDImageYYCoder","op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/title"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/fragments","value":[{"text":"SDImageYYCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageYYCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}