{"abstract":[{"text":"The shared coder instance.","type":"text"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageYYCoder","text":"SDImageYYCoder","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}],"symbolKind":"property","roleHeading":"Type Property","role":"symbol","externalID":"c:objc(cs)SDImageYYCoder(cpy)sharedCoder","title":"shared","modules":[{"name":"SDWebImageYYPlugin"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/shared","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder","text":"SDImageYYCoder","preciseIdentifier":"c:objc(cs)SDImageYYCoder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/shared"]},{"paths":["\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin":{"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimageyyplugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin","title":"SDWebImageYYPlugin","role":"collection"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder/shared":{"type":"topic","kind":"symbol","url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder\/shared","navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}],"abstract":[{"type":"text","text":"The shared coder instance."}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageYYCoder","preciseIdentifier":"c:objc(cs)SDImageYYCoder","kind":"typeIdentifier"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder\/shared","title":"shared","role":"symbol"},"doc://org.cocoapods.SDWebImageYYPlugin/documentation/SDWebImageYYPlugin/SDImageYYCoder":{"type":"topic","abstract":[{"text":"YYImageEncoder && YYImageDecoder bridge to supports SDWebImage coder protocol. This class use YYImage’s decoding && encoding system. It supports any image format listed in ","type":"text"},{"type":"codeVoice","code":"YYImageType"},{"text":".","type":"text"}],"role":"symbol","title":"SDImageYYCoder","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageYYCoder"}],"navigatorTitle":[{"text":"SDImageYYCoder","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimageyyplugin\/sdimageyycoder","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"sharedCoder","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"text":"sharedCoder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"SDImageYYCoder","identifier":"doc:\/\/org.cocoapods.SDWebImageYYPlugin\/documentation\/SDWebImageYYPlugin\/SDImageYYCoder","preciseIdentifier":"c:objc(cs)SDImageYYCoder"},{"text":" * ","kind":"text"},{"text":"sharedCoder","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":"sharedCoder","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1shared\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder~1shared\/fragments","value":[{"text":"sharedCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/title","op":"replace","value":"SDImageYYCoder"},{"value":[{"text":"SDImageYYCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageYYPlugin~1documentation~1SDWebImageYYPlugin~1SDImageYYCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageYYCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}