{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageduration(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageduration(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageDuration(at:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"title":"animatedImageDuration(at:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SDWebImageLottiePlugin@objc(cs)LottieImage(im)animatedImageDurationAtIndex:","modules":[{"name":"SDWebImageLottiePlugin"}],"navigatorTitle":[{"kind":"identifier","text":"animatedImageDurationAtIndex:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage"]]},"references":{"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin":{"role":"collection","title":"SDWebImageLottiePlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageDuration(at:)":{"role":"symbol","title":"animatedImageDuration(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageDuration"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageDuration(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageDurationAtIndex:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageduration(at:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage":{"role":"symbol","title":"LottieImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"abstract":[{"type":"text","text":"A UIImage subclass wrapper for Lottie animation"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LottieImage"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animatedImageDurationAtIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animatedImageDurationAtIndex:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"kind":"identifier","text":"animatedImageDurationAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageDuration(at:)\/title","value":"animatedImageDurationAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageDuration(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animatedImageDurationAtIndex:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/title","value":"LottieImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/fragments","value":[{"kind":"identifier","text":"LottieImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}