{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrameCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframecount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframecount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrameCount","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrameCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"animatedImageFrameCount","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:@M@SDWebImageLottiePlugin@objc(cs)LottieImage(py)animatedImageFrameCount","modules":[{"name":"SDWebImageLottiePlugin"}],"navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameCount"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage"]]},"references":{"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin":{"role":"collection","title":"SDWebImageLottiePlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage":{"role":"symbol","title":"LottieImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"abstract":[{"type":"text","text":"A UIImage subclass wrapper for Lottie animation"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LottieImage"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageFrameCount":{"role":"symbol","title":"animatedImageFrameCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrameCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrameCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameCount"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframecount"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"animatedImageFrameCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"animatedImageFrameCount"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"identifier","text":"animatedImageFrameCount"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/title","value":"LottieImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/fragments","value":[{"kind":"identifier","text":"LottieImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrameCount\/title","value":"animatedImageFrameCount"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrameCount\/fragments","value":[{"kind":"identifier","text":"animatedImageFrameCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}