{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/PlatformImage","preciseIdentifier":"s:22SDWebImageLottiePlugin08PlatformB0a","text":"PlatformImage"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframe(at:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframe(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrame(at:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:22SDWebImageLottiePlugin08PlatformB0a"},{"kind":"text","text":"?"}],"title":"animatedImageFrame(at:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:@M@SDWebImageLottiePlugin@objc(cs)LottieImage(im)animatedImageFrameAtIndex:","modules":[{"name":"SDWebImageLottiePlugin"}],"navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameAtIndex:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage"]]},"references":{"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin":{"role":"collection","title":"SDWebImageLottiePlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/PlatformImage":{"role":"symbol","title":"PlatformImage","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"PlatformImage"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/PlatformImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"PlatformImage"}],"url":"\/documentation\/sdwebimagelottieplugin\/platformimage"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage":{"role":"symbol","title":"LottieImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"abstract":[{"type":"text","text":"A UIImage subclass wrapper for Lottie animation"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LottieImage"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/animatedImageFrame(at:)":{"role":"symbol","title":"animatedImageFrame(at:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"PlatformImage","preciseIdentifier":"s:22SDWebImageLottiePlugin08PlatformB0a"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/animatedImageFrame(at:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameAtIndex:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/animatedimageframe(at:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"animatedImageFrameAtIndex:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animatedImageFrameAtIndex:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"animatedImageFrameAtIndex:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"index"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/title","value":"LottieImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/fragments","value":[{"kind":"identifier","text":"LottieImage"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrame(at:)\/title","value":"animatedImageFrameAtIndex:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1animatedImageFrame(at:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"animatedImageFrameAtIndex:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}