{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"kind":"keyword","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]? = nil)"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(data:scale:options:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(data:scale:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(data:scale:options:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"title":"init(data:scale:options:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:@M@SDWebImageLottiePlugin@objc(cs)LottieImage(im)initWithData:scale:options:","modules":[{"name":"SDWebImageLottiePlugin"}],"navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:options:"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage"]]},"references":{"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage/init(data:scale:options:)":{"role":"symbol","title":"init(data:scale:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"data"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"scale"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage\/init(data:scale:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithData:scale:options:"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage\/init(data:scale:options:)"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin":{"role":"collection","title":"SDWebImageLottiePlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagelottieplugin"},"doc://org.cocoapods.SDWebImageLottiePlugin/documentation/SDWebImageLottiePlugin/LottieImage":{"role":"symbol","title":"LottieImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"LottieImage"}],"abstract":[{"type":"text","text":"A UIImage subclass wrapper for Lottie animation"}],"identifier":"doc:\/\/org.cocoapods.SDWebImageLottiePlugin\/documentation\/SDWebImageLottiePlugin\/LottieImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"LottieImage"}],"url":"\/documentation\/sdwebimagelottieplugin\/lottieimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithData:scale:options:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:scale:options:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithData:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"data"},{"kind":"text","text":" "},{"kind":"identifier","text":"scale:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"scale"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSDictionary<NSString *,id>","preciseIdentifier":"c:Q$objc(cs)NSDictionary"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(data:scale:options:)\/title","value":"initWithData:scale:options:"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage~1init(data:scale:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithData:scale:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/title","value":"LottieImage"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImageLottiePlugin~1documentation~1SDWebImageLottiePlugin~1LottieImage\/fragments","value":[{"kind":"identifier","text":"LottieImage"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}