{"deprecationSummary":[{"inlineContent":[{"text":"Use SDWebImageContextCallbackQueue context param instead, see SDCallbackQueue","type":"text"}],"type":"paragraph"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/delegatequeue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/delegatequeue"]}],"abstract":[{"type":"text","text":"Queue options for prefetcher when call the progressBlock, completionBlock and delegate methods. Defaults to Main Queue."}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher"]]},"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"delegateQueue"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/delegateQueue","interfaceLanguage":"swift"},"metadata":{"role":"symbol","title":"delegateQueue","externalID":"c:objc(cs)SDWebImagePrefetcher(py)delegateQueue","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegateQueue"},{"text":": ","kind":"text"},{"text":"dispatch_queue_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@dispatch_queue_t"}],"navigatorTitle":[{"kind":"identifier","text":"delegateQueue"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","platforms":[{"beta":false,"deprecated":false,"unavailable":false,"message":"Use SDWebImageContextCallbackQueue context param instead, see SDCallbackQueue","deprecatedAt":"8.0","introducedAt":"8.0","name":"iOS"},{"unavailable":false,"deprecatedAt":"8.0","name":"iPadOS","introducedAt":"8.0","beta":false,"message":"Use SDWebImageContextCallbackQueue context param instead, see SDCallbackQueue","deprecated":false},{"beta":false,"deprecated":false,"introducedAt":"8.0","name":"Mac Catalyst","unavailable":false,"message":"Use SDWebImageContextCallbackQueue context param instead, see SDCallbackQueue","deprecatedAt":"8.0"}]},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher/delegateQueue":{"abstract":[{"type":"text","text":"Queue options for prefetcher when call the progressBlock, completionBlock and delegate methods. Defaults to Main Queue."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"delegateQueue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@dispatch_queue_t","text":"dispatch_queue_t","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher\/delegatequeue","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/delegateQueue","navigatorTitle":[{"kind":"identifier","text":"delegateQueue"}],"type":"topic","title":"delegateQueue","deprecated":true,"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher":{"title":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","navigatorTitle":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Prefetch some URLs in the cache for future use. Images are downloaded in low priority.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecatedAt":"8.0","unavailable":false,"beta":false,"name":"iOS","introducedAt":"8.0","deprecated":false},{"unavailable":false,"deprecatedAt":"8.0","beta":false,"name":"iPadOS","introducedAt":"8.0","deprecated":false},{"deprecatedAt":"8.0","introducedAt":"8.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}]},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"delegateQueue"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"delegateQueue","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSObjectobjc(pl)OS_dispatch_queue","text":"NSObject<OS_dispatch_queue>","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"delegateQueue"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1delegateQueue\/title","value":"delegateQueue"},{"value":[{"text":"delegateQueue","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1delegateQueue\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/title","value":"SDWebImagePrefetcher","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImagePrefetcher"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/navigatorTitle","op":"replace","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}]}]}]}