{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentPrefetchCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"type":"text","text":"Maximum number of URLs to prefetch at the same time. Defaults to 3."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/maxconcurrentprefetchcount"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/maxconcurrentprefetchcount"]}],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"maxConcurrentPrefetchCount"}],"symbolKind":"property","role":"symbol","modules":[{"name":"SDWebImage"}],"title":"maxConcurrentPrefetchCount","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentPrefetchCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"externalID":"c:objc(cs)SDWebImagePrefetcher(py)maxConcurrentPrefetchCount","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/maxConcurrentPrefetchCount","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher":{"title":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","navigatorTitle":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Prefetch some URLs in the cache for future use. Images are downloaded in low priority.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher/maxConcurrentPrefetchCount":{"type":"topic","abstract":[{"text":"Maximum number of URLs to prefetch at the same time. Defaults to 3.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/maxConcurrentPrefetchCount","url":"\/documentation\/sdwebimage\/sdwebimageprefetcher\/maxconcurrentprefetchcount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"maxConcurrentPrefetchCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"maxConcurrentPrefetchCount","kind":"identifier"}],"title":"maxConcurrentPrefetchCount"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxConcurrentPrefetchCount"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxConcurrentPrefetchCount"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxConcurrentPrefetchCount"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/title","op":"replace","value":"SDWebImagePrefetcher"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/fragments","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImagePrefetcher"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/navigatorTitle"},{"value":"maxConcurrentPrefetchCount","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1maxConcurrentPrefetchCount\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1maxConcurrentPrefetchCount\/fragments","value":[{"kind":"identifier","text":"maxConcurrentPrefetchCount"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}