{"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/prefetchurls(_:progress:completed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/prefetchurls(_:progress:completed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"title":"prefetchURLs(_:progress:completed:)","navigatorTitle":[{"kind":"identifier","text":"prefetchURLs:progress:completed:"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"prefetchURLs","kind":"identifier"},{"text":"([","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImagePrefetcherProgressBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherProgressBlock"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImagePrefetcherCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherCompletionBlock"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","text":"SDWebImagePrefetchToken"},{"text":"?","kind":"text"}],"externalID":"c:objc(cs)SDWebImagePrefetcher(im)prefetchURLs:progress:completed:","symbolKind":"method"},"abstract":[{"text":"Assign list of URLs to let SDWebImagePrefetcher to queue the prefetching. It based on the image manager so the image may from the cache and network according to the ","type":"text"},{"type":"codeVoice","code":"options"},{"type":"text","text":" property."},{"type":"text","text":" "},{"text":"Prefetching is separate to each other, which means the progressBlock and completionBlock you provide is bind to the prefetching for the list of urls.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Attention that call this will not cancel previous fetched urls. You should keep the token return by this to cancel or cancel all the prefetch."}],"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/prefetchURLs(_:progress:completed:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prefetchURLs","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"urls"},{"kind":"text","text":": ["},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"text":"progress","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"progressBlock"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherProgressBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherProgressBlock","text":"SDWebImagePrefetcherProgressBlock"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"kind":"text","text":" "},{"text":"completionBlock","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherCompletionBlock","text":"SDWebImagePrefetcherCompletionBlock","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherCompletionBlock"},{"text":"? = nil) -> ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImagePrefetchToken","preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"},{"kind":"text","text":"?"}]}]},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"List of URLs to prefetch"}],"type":"paragraph"}],"name":"urls"},{"content":[{"inlineContent":[{"text":"Block to be called when progress updates;","type":"text"},{"type":"text","text":" "},{"type":"text","text":"first parameter is the number of completed (successful or not) requests,"},{"type":"text","text":" "},{"type":"text","text":"second parameter is the total number of images originally requested to be prefetched"}],"type":"paragraph"}],"name":"progressBlock"},{"content":[{"inlineContent":[{"type":"text","text":"Block to be called when the current prefetching is completed"},{"type":"text","text":" "},{"type":"text","text":"first param is the number of completed (successful or not) requests,"},{"type":"text","text":" "},{"type":"text","text":"second parameter is the number of skipped requests"}],"type":"paragraph"}],"name":"completionBlock"}],"kind":"parameters"},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"The token to cancel the current prefetching."}],"type":"paragraph"}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher/prefetchURLs(_:progress:completed:)":{"role":"symbol","navigatorTitle":[{"text":"prefetchURLs:progress:completed:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher\/prefetchurls(_:progress:completed:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/prefetchURLs(_:progress:completed:)","kind":"symbol","abstract":[{"text":"Assign list of URLs to let SDWebImagePrefetcher to queue the prefetching. It based on the image manager so the image may from the cache and network according to the ","type":"text"},{"code":"options","type":"codeVoice"},{"text":" property.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Prefetching is separate to each other, which means the progressBlock and completionBlock you provide is bind to the prefetching for the list of urls."},{"text":" ","type":"text"},{"text":"Attention that call this will not cancel previous fetched urls. You should keep the token return by this to cancel or cancel all the prefetch.","type":"text"}],"title":"prefetchURLs(_:progress:completed:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"prefetchURLs","kind":"identifier"},{"text":"([","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherProgressBlock","text":"SDWebImagePrefetcherProgressBlock"},{"text":"?, ","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImagePrefetcherCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherCompletionBlock"},{"text":"?) -> ","kind":"text"},{"text":"SDWebImagePrefetchToken","preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher":{"title":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","navigatorTitle":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Prefetch some URLs in the cache for future use. Images are downloaded in low priority.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherCompletionBlock":{"title":"SDWebImagePrefetcherCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherCompletionBlock","navigatorTitle":[{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetchercompletionblock","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetchToken":{"type":"topic","abstract":[{"text":"A token represents a list of URLs, can be used to cancel the download.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SDWebImagePrefetchToken","kind":"identifier"}],"title":"SDWebImagePrefetchToken","url":"\/documentation\/sdwebimage\/sdwebimageprefetchtoken","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetchToken","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherProgressBlock":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherprogressblock","kind":"symbol","title":"SDWebImagePrefetcherProgressBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherProgressBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"prefetchURLs:progress:completed:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"prefetchURLs:progress:completed:","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"SDWebImagePrefetchToken","preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"},{"text":" *) ","kind":"text"},{"text":"prefetchURLs:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"kind":"text","text":" *) "},{"text":"urls","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"progress:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(unsigned long, unsigned long)","preciseIdentifier":"c:BFv(#l#l)"},{"kind":"text","text":") "},{"text":"progressBlock","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:BFv(#l#l)","text":"void (^)(unsigned long, unsigned long)","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"completionBlock"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"urls","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of URLs to prefetch"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Block to be called when progress updates;"},{"type":"text","text":" "},{"text":"first parameter is the number of completed (successful or not) requests,","type":"text"},{"type":"text","text":" "},{"type":"text","text":"second parameter is the total number of images originally requested to be prefetched"}]}],"name":"progressBlock"},{"name":"completionBlock","content":[{"inlineContent":[{"type":"text","text":"Block to be called when the current prefetching is completed"},{"type":"text","text":" "},{"text":"first param is the number of completed (successful or not) requests,","type":"text"},{"type":"text","text":" "},{"text":"second parameter is the number of skipped requests","type":"text"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","value":{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"The token to cancel the current prefetching."}]}],"kind":"content"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1prefetchURLs(_:progress:completed:)\/title","value":"prefetchURLs:progress:completed:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1prefetchURLs(_:progress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"prefetchURLs:progress:completed:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/title","value":"SDWebImagePrefetcher"},{"op":"replace","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImagePrefetcher"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/navigatorTitle"},{"value":"SDWebImagePrefetcherCompletionBlock","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherCompletionBlock\/title"},{"value":[{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherCompletionBlock\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherCompletionBlock\/navigatorTitle"},{"value":"SDWebImagePrefetchToken","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/fragments","value":[{"text":"SDWebImagePrefetchToken","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/navigatorTitle","value":[{"text":"SDWebImagePrefetchToken","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherProgressBlock\/title","op":"replace","value":"SDWebImagePrefetcherProgressBlock"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherProgressBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImagePrefetcherProgressBlock"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherProgressBlock\/navigatorTitle","value":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}