{"metadata":{"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImagePrefetcher(im)prefetchURLs:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"prefetchURLs:"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"prefetchURLs"},{"text":"([","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","text":"SDWebImagePrefetchToken"},{"kind":"text","text":"?"}],"title":"prefetchURLs(_:)"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/prefetchurls(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcher\/prefetchurls(_:)"]}],"kind":"symbol","sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/prefetchURLs(_:)","interfaceLanguage":"swift"},"abstract":[{"text":"Assign list of URLs to let SDWebImagePrefetcher to queue the prefetching. It based on the image manager so the image may from the cache and network according to the ","type":"text"},{"code":"options","type":"codeVoice"},{"text":" property.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Prefetching is separate to each other, which means the progressBlock and completionBlock you provide is bind to the prefetching for the list of urls."},{"type":"text","text":" "},{"text":"Attention that call this will not cancel previous fetched urls. You should keep the token return by this to cancel or cancel all the prefetch.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prefetchURLs","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"urls"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","text":"SDWebImagePrefetchToken","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"},{"text":"?","kind":"text"}]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"List of URLs to prefetch","type":"text"}]}],"name":"urls"}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"inlineContent":[{"type":"text","text":"The token to cancel the current prefetching."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetchToken":{"type":"topic","abstract":[{"text":"A token represents a list of URLs, can be used to cancel the download.","type":"text"}],"kind":"symbol","navigatorTitle":[{"text":"SDWebImagePrefetchToken","kind":"identifier"}],"title":"SDWebImagePrefetchToken","url":"\/documentation\/sdwebimage\/sdwebimageprefetchtoken","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetchToken","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher/prefetchURLs(_:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"prefetchURLs","kind":"identifier"},{"text":"([","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","text":"SDWebImagePrefetchToken"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageprefetcher\/prefetchurls(_:)","title":"prefetchURLs(_:)","abstract":[{"type":"text","text":"Assign list of URLs to let SDWebImagePrefetcher to queue the prefetching. It based on the image manager so the image may from the cache and network according to the "},{"code":"options","type":"codeVoice"},{"type":"text","text":" property."},{"text":" ","type":"text"},{"text":"Prefetching is separate to each other, which means the progressBlock and completionBlock you provide is bind to the prefetching for the list of urls.","type":"text"},{"type":"text","text":" "},{"text":"Attention that call this will not cancel previous fetched urls. You should keep the token return by this to cancel or cancel all the prefetch.","type":"text"}],"navigatorTitle":[{"text":"prefetchURLs:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher\/prefetchURLs(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher":{"title":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","navigatorTitle":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Prefetch some URLs in the cache for future use. Images are downloaded in low priority.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"prefetchURLs:","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetchURLs:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)SDWebImagePrefetchToken","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken","kind":"typeIdentifier","text":"SDWebImagePrefetchToken"},{"text":" *) ","kind":"text"},{"text":"prefetchURLs:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","kind":"typeIdentifier","text":"NSArray<NSURL *>"},{"text":" *) ","kind":"text"},{"text":"urls","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"List of URLs to prefetch"}]}],"name":"urls"}]},"path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The token to cancel the current prefetching.","type":"text"}]}]},"op":"replace"},{"value":"SDWebImagePrefetchToken","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/fragments","value":[{"text":"SDWebImagePrefetchToken","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImagePrefetchToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1prefetchURLs(_:)\/title","value":"prefetchURLs:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher~1prefetchURLs(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"prefetchURLs:"}]},{"value":"SDWebImagePrefetcher","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/fragments","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImagePrefetcher"}],"op":"replace"}]}]}