{"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/animationrepeatcount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/animationrepeatcount"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Total loop count for animated image rendering. Default is animated image’s loop count.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If you need to set custom loop count, set "},{"type":"codeVoice","code":"shouldCustomLoopCount"},{"type":"text","text":" to YES and change this value."},{"text":" ","type":"text"},{"type":"text","text":"This class override UIImageView’s "},{"type":"codeVoice","code":"animationRepeatCount"},{"type":"text","text":" property on iOS, use this property as well."}],"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationRepeatCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationRepeatCount"},"metadata":{"roleHeading":"Instance Property","externalID":"c:objc(cs)SDAnimatedImageView(py)animationRepeatCount","title":"animationRepeatCount","role":"symbol","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"animationRepeatCount"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationRepeatCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"symbolKind":"property"},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/animationRepeatCount":{"navigatorTitle":[{"text":"animationRepeatCount","kind":"identifier"}],"abstract":[{"text":"Total loop count for animated image rendering. Default is animated image’s loop count.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you need to set custom loop count, set "},{"type":"codeVoice","code":"shouldCustomLoopCount"},{"type":"text","text":" to YES and change this value."},{"type":"text","text":" "},{"type":"text","text":"This class override UIImageView’s "},{"type":"codeVoice","code":"animationRepeatCount"},{"type":"text","text":" property on iOS, use this property as well."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"animationRepeatCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/animationrepeatcount","type":"topic","title":"animationRepeatCount","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationRepeatCount"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"animationRepeatCount","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"animationRepeatCount","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:@T@NSInteger","kind":"typeIdentifier","text":"NSInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationRepeatCount"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SDAnimatedImageView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","op":"replace"},{"value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments"},{"value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1animationRepeatCount\/title","op":"replace","value":"animationRepeatCount"},{"op":"replace","value":[{"text":"animationRepeatCount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1animationRepeatCount\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}