{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentLoopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/currentloopcount"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/currentloopcount"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentLoopCount","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Current loop count since its latest animating. This value is KVO Compliance."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentLoopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"currentLoopCount","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImageView(py)currentLoopCount","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"currentLoopCount"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/currentLoopCount":{"role":"symbol","title":"currentLoopCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentLoopCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Current loop count since its latest animating. This value is KVO Compliance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentLoopCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentLoopCount"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/currentloopcount"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"role":"symbol","title":"SDAnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageView"}],"abstract":[{"type":"text","text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"setImage:"},{"type":"text","text":" with "},{"type":"codeVoice","code":"UIImage(NSImage)"},{"type":"text","text":" which conforms to "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"type":"codeVoice","code":"-startAnimating"},{"type":"text","text":", "},{"type":"codeVoice","code":"-stopAnimating"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"type":"text","text":" to check animation state."},{"type":"text","text":" "},{"type":"text","text":"For AppKit: use "},{"type":"codeVoice","code":"-setAnimates:"},{"type":"text","text":" to control animating, "},{"type":"codeVoice","code":"animates"},{"type":"text","text":" to check animation state. This view is layer-backed."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"currentLoopCount"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"currentLoopCount"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentLoopCount"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentLoopCount\/title","value":"currentLoopCount"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentLoopCount\/fragments","value":[{"kind":"identifier","text":"currentLoopCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}