{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/maxbuffersize"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/maxbuffersize"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/maxBufferSize","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Provide a max buffer size by bytes. This is used to adjust frame buffer count and can be useful when the decoding cost is expensive (such as Animated WebP software decoding). Default is 0."},{"type":"text","text":" "},{"type":"codeVoice","code":"0"},{"type":"text","text":" means automatically adjust by calculating current memory usage."},{"type":"text","text":" "},{"type":"codeVoice","code":"1"},{"type":"text","text":" means without any buffer cache, each of frames will be decoded and then be freed after rendering. (Lowest Memory and Highest CPU)"},{"type":"text","text":" "},{"type":"codeVoice","code":"NSUIntegerMax"},{"type":"text","text":" means cache all the buffer. (Lowest CPU and Highest Memory)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"title":"maxBufferSize","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImageView(py)maxBufferSize","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"maxBufferSize"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"role":"symbol","title":"SDAnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageView"}],"abstract":[{"type":"text","text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"setImage:"},{"type":"text","text":" with "},{"type":"codeVoice","code":"UIImage(NSImage)"},{"type":"text","text":" which conforms to "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"type":"codeVoice","code":"-startAnimating"},{"type":"text","text":", "},{"type":"codeVoice","code":"-stopAnimating"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"type":"text","text":" to check animation state."},{"type":"text","text":" "},{"type":"text","text":"For AppKit: use "},{"type":"codeVoice","code":"-setAnimates:"},{"type":"text","text":" to control animating, "},{"type":"codeVoice","code":"animates"},{"type":"text","text":" to check animation state. This view is layer-backed."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/maxBufferSize":{"role":"symbol","title":"maxBufferSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBufferSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Provide a max buffer size by bytes. This is used to adjust frame buffer count and can be useful when the decoding cost is expensive (such as Animated WebP software decoding). Default is 0."},{"type":"text","text":" "},{"type":"codeVoice","code":"0"},{"type":"text","text":" means automatically adjust by calculating current memory usage."},{"type":"text","text":" "},{"type":"codeVoice","code":"1"},{"type":"text","text":" means without any buffer cache, each of frames will be decoded and then be freed after rendering. (Lowest Memory and Highest CPU)"},{"type":"text","text":" "},{"type":"codeVoice","code":"NSUIntegerMax"},{"type":"text","text":" means cache all the buffer. (Lowest CPU and Highest Memory)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/maxBufferSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxBufferSize"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/maxbuffersize"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"maxBufferSize"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"maxBufferSize"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxBufferSize"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1maxBufferSize\/title","value":"maxBufferSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1maxBufferSize\/fragments","value":[{"kind":"identifier","text":"maxBufferSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}