{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/playbackrate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/playbackrate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackRate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The animation playback rate. Default is 1.0."},{"type":"text","text":" "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" means the normal speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" means stopping the animation."},{"type":"text","text":" "},{"type":"codeVoice","code":"0.0-1.0"},{"type":"text","text":" means the slow speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"> 1.0"},{"type":"text","text":" means the fast speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"< 0.0"},{"type":"text","text":" is not supported currently and stop animation. (may support reverse playback in the future)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"title":"playbackRate","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImageView(py)playbackRate","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"playbackRate"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/playbackRate":{"role":"symbol","title":"playbackRate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The animation playback rate. Default is 1.0."},{"type":"text","text":" "},{"type":"codeVoice","code":"1.0"},{"type":"text","text":" means the normal speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" means stopping the animation."},{"type":"text","text":" "},{"type":"codeVoice","code":"0.0-1.0"},{"type":"text","text":" means the slow speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"> 1.0"},{"type":"text","text":" means the fast speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"< 0.0"},{"type":"text","text":" is not supported currently and stop animation. (may support reverse playback in the future)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackRate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"playbackRate"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/playbackrate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"role":"symbol","title":"SDAnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageView"}],"abstract":[{"type":"text","text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"setImage:"},{"type":"text","text":" with "},{"type":"codeVoice","code":"UIImage(NSImage)"},{"type":"text","text":" which conforms to "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"type":"codeVoice","code":"-startAnimating"},{"type":"text","text":", "},{"type":"codeVoice","code":"-stopAnimating"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"type":"text","text":" to check animation state."},{"type":"text","text":" "},{"type":"text","text":"For AppKit: use "},{"type":"codeVoice","code":"-setAnimates:"},{"type":"text","text":" to control animating, "},{"type":"codeVoice","code":"animates"},{"type":"text","text":" to check animation state. This view is layer-backed."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"playbackRate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"playbackRate"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"double","preciseIdentifier":"c:d"},{"kind":"text","text":" "},{"kind":"identifier","text":"playbackRate"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1playbackRate\/title","value":"playbackRate"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1playbackRate\/fragments","value":[{"kind":"identifier","text":"playbackRate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}