{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"runLoopMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RunLoop","preciseIdentifier":"c:objc(cs)NSRunLoop"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"c:@T@NSRunLoopMode"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/runloopmode"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/runloopmode"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/runLoopMode","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"You can specify a runloop mode to let it rendering."},{"type":"text","text":" "},{"type":"text","text":"Default is NSRunLoopCommonModes on multi-core device, NSDefaultRunLoopMode on single-core device"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"runLoopMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RunLoop","preciseIdentifier":"c:objc(cs)NSRunLoop"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"c:@T@NSRunLoopMode"}],"title":"runLoopMode","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImageView(py)runLoopMode","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"runLoopMode"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"role":"symbol","title":"SDAnimatedImageView","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageView"}],"abstract":[{"type":"text","text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering."},{"type":"text","text":" "},{"type":"text","text":"Call "},{"type":"codeVoice","code":"setImage:"},{"type":"text","text":" with "},{"type":"codeVoice","code":"UIImage(NSImage)"},{"type":"text","text":" which conforms to "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"type":"codeVoice","code":"-startAnimating"},{"type":"text","text":", "},{"type":"codeVoice","code":"-stopAnimating"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"type":"text","text":" to check animation state."},{"type":"text","text":" "},{"type":"text","text":"For AppKit: use "},{"type":"codeVoice","code":"-setAnimates:"},{"type":"text","text":" to control animating, "},{"type":"codeVoice","code":"animates"},{"type":"text","text":" to check animation state. This view is layer-backed."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/runLoopMode":{"role":"symbol","title":"runLoopMode","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"runLoopMode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"RunLoop","preciseIdentifier":"c:objc(cs)NSRunLoop"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"Mode","preciseIdentifier":"c:@T@NSRunLoopMode"}],"abstract":[{"type":"text","text":"You can specify a runloop mode to let it rendering."},{"type":"text","text":" "},{"type":"text","text":"Default is NSRunLoopCommonModes on multi-core device, NSDefaultRunLoopMode on single-core device"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/runLoopMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"runLoopMode"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/runloopmode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"runLoopMode"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"runLoopMode"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"runLoopMode"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1runLoopMode\/title","value":"runLoopMode"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1runLoopMode\/fragments","value":[{"kind":"identifier","text":"runLoopMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}