{"schemaVersion":{"minor":3,"patch":0,"major":0},"abstract":[{"text":"Set the imageView ","type":"text"},{"type":"codeVoice","code":"image"},{"type":"text","text":" with an "},{"code":"url","type":"codeVoice"},{"text":" and a placeholder.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:"]}],"sections":[],"metadata":{"role":"symbol","title":"sd_setImageWithURL:placeholderImage:","symbolKind":"method","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDAnimatedImageView(im)sd_setImageWithURL:placeholderImage:","fragments":[{"kind":"text","text":"- "},{"text":"sd_setImageWithURL:placeholderImage:","kind":"identifier"}],"roleHeading":"Instance Method"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:","interfaceLanguage":"occ"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","kind":"typeIdentifier","text":"void"},{"text":") ","kind":"text"},{"text":"sd_setImageWithURL:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"url"},{"text":" ","kind":"text"},{"text":"placeholderImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url for the image."}]}]},{"name":"placeholder","content":[{"inlineContent":[{"text":"The image to be set initially, until the image request finishes.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"The download is asynchronous and cached."}],"type":"paragraph"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImageWithURL:placeholderImage:":{"role":"symbol","kind":"symbol","title":"sd_setImageWithURL:placeholderImage:","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Set the imageView "},{"type":"codeVoice","code":"image"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"url"},{"text":" and a placeholder.","type":"text"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SDAnimatedImageView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}