{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"text":"sd_setImageWithURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"kind":"text","text":" "},{"text":"placeholderImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"placeholder","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The url for the image."}],"type":"paragraph"}],"name":"url"},{"name":"placeholder","content":[{"inlineContent":[{"type":"text","text":"The image to be set initially, until the image request finishes."}],"type":"paragraph"}]},{"name":"options","content":[{"inlineContent":[{"text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values.","type":"text"}],"type":"paragraph"}]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"inlineContent":[{"type":"text","text":"The download is asynchronous and cached."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:options:","interfaceLanguage":"occ"},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"metadata":{"symbolKind":"method","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","title":"sd_setImageWithURL:placeholderImage:options:","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:","kind":"identifier"}],"externalID":"c:objc(cs)SDAnimatedImageView(im)sd_setImageWithURL:placeholderImage:options:","role":"symbol","fragments":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:placeholderImage:options:","kind":"identifier"}]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:options:"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"Set the imageView "},{"type":"codeVoice","code":"image"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"url"},{"text":", placeholder and custom options.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImageWithURL:placeholderImage:options:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:options:","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:options:","abstract":[{"text":"Set the imageView ","type":"text"},{"code":"image","type":"codeVoice"},{"type":"text","text":" with an "},{"code":"url","type":"codeVoice"},{"text":", placeholder and custom options.","type":"text"}],"title":"sd_setImageWithURL:placeholderImage:options:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","op":"replace","value":[{"text":"SDAnimatedImageView","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"op":"replace","value":"SDWebImageOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title"},{"value":[{"kind":"identifier","text":"SDWebImageOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"value":[{"text":"SDWebImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","op":"replace"}]}]}