{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"placeholderImage","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"kind":"text","text":" = [], "},{"text":"progress","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"progressBlock"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"completedBlock"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","text":"SDExternalCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The url for the image.","type":"text"}],"type":"paragraph"}],"name":"url"},{"name":"placeholder","content":[{"inlineContent":[{"type":"text","text":"The image to be set initially, until the image request finishes."}],"type":"paragraph"}]},{"name":"options","content":[{"inlineContent":[{"text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values.","type":"text"}],"type":"paragraph"}]},{"name":"progressBlock","content":[{"type":"paragraph","inlineContent":[{"text":"A block called while image is downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@note the progress block is executed on a background queue"}]}]},{"name":"completedBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block called when operation has been completed. This block has no return value"},{"text":" ","type":"text"},{"type":"text","text":"and takes the requested UIImage as first parameter. In case of error the image parameter"},{"type":"text","text":" "},{"text":"is nil and the second parameter may contain an NSError. The third parameter is a Boolean","type":"text"},{"type":"text","text":" "},{"text":"indicating if the image was retrieved from the local cache or from the network.","type":"text"},{"type":"text","text":" "},{"text":"The fourth parameter is the original image url.","type":"text"}]}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"inlineContent":[{"type":"text","text":"The download is asynchronous and cached."}],"type":"paragraph"}],"kind":"content"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:progress:completed:)"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:progress:completed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:progress:completed:)"},"abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"url"},{"text":", placeholder and custom options.","type":"text"}],"metadata":{"roleHeading":"Instance Method","title":"sd_setImage(with:placeholderImage:options:progress:completed:)","modules":[{"name":"SDWebImage"}],"role":"symbol","externalID":"c:objc(cs)SDAnimatedImageView(im)sd_setImageWithURL:placeholderImage:options:progress:completed:","symbolKind":"method","extendedModule":"SDWebImage","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"placeholderImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","kind":"typeIdentifier","text":"SDImageLoaderProgressBlock"},{"text":"?, ","kind":"text"},{"text":"completed","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDExternalCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:progress:completed:"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:progress:completed:)":{"title":"sd_setImage(with:placeholderImage:options:progress:completed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","text":"SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"text":"SDExternalCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:progress:completed:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"text":", placeholder and custom options.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:progress:completed:)","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:progress:completed:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderProgressBlock":{"abstract":[],"title":"SDImageLoaderProgressBlock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","url":"\/documentation\/sdwebimage\/sdimageloaderprogressblock","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDExternalCompletionBlock":{"url":"\/documentation\/sdwebimage\/sdexternalcompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDExternalCompletionBlock","kind":"identifier"}],"title":"SDExternalCompletionBlock","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDExternalCompletionBlock"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"value":"sd_setImageWithURL:placeholderImage:options:progress:completed:","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:placeholderImage:options:progress:completed:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"sd_setImageWithURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"text":" ","kind":"text"},{"text":"placeholderImage:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":" *) ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"kind":"text","text":" "},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":") "},{"text":"options","kind":"internalParam"},{"kind":"text","text":" "},{"text":"progress:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"void (^)(long, long, NSURL *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#L#L#*$objc(cs)NSURL)"},{"kind":"text","text":") "},{"text":"progressBlock","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"text":"void (^)(UIImage *, NSError *, enum SDImageCacheType, NSURL *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSError#$@E@SDImageCacheType#*$objc(cs)NSURL)"},{"text":") ","kind":"text"},{"text":"completedBlock","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The url for the image.","type":"text"}]}],"name":"url"},{"name":"placeholder","content":[{"type":"paragraph","inlineContent":[{"text":"The image to be set initially, until the image request finishes.","type":"text"}]}]},{"content":[{"inlineContent":[{"text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values.","type":"text"}],"type":"paragraph"}],"name":"options"},{"content":[{"type":"paragraph","inlineContent":[{"text":"A block called while image is downloading","type":"text"},{"type":"text","text":" "},{"text":"@note the progress block is executed on a background queue","type":"text"}]}],"name":"progressBlock"},{"content":[{"inlineContent":[{"type":"text","text":"A block called when operation has been completed. This block has no return value"},{"type":"text","text":" "},{"text":"and takes the requested UIImage as first parameter. In case of error the image parameter","type":"text"},{"text":" ","type":"text"},{"text":"is nil and the second parameter may contain an NSError. The third parameter is a Boolean","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"indicating if the image was retrieved from the local cache or from the network."},{"text":" ","type":"text"},{"text":"The fourth parameter is the original image url.","type":"text"}],"type":"paragraph"}],"name":"completedBlock"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"SDAnimatedImageView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDAnimatedImageView"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","op":"replace","value":"SDWebImageOptions"},{"value":[{"kind":"identifier","text":"SDWebImageOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"text":"SDWebImageOptions","kind":"identifier"}]},{"value":"sd_setImageWithURL:placeholderImage:options:progress:completed:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:progress:completed:)\/title"},{"value":[{"kind":"text","text":"- "},{"text":"sd_setImageWithURL:placeholderImage:options:progress:completed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:progress:completed:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/title","value":"SDImageLoaderProgressBlock"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/fragments","value":[{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/navigatorTitle","value":[{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDExternalCompletionBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/fragments","value":[{"kind":"identifier","text":"SDExternalCompletionBlock"}]},{"op":"replace","value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/navigatorTitle"}]}]}