{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:completed:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:completed:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:completed:)"},"metadata":{"title":"sd_setImage(with:placeholderImage:options:completed:)","extendedModule":"SDWebImage","role":"symbol","externalID":"c:objc(cs)SDAnimatedImageView(im)sd_setImageWithURL:placeholderImage:options:completed:","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"sd_setImage"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"placeholderImage","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"text":"SDExternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"symbolKind":"method","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:completed:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sd_setImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"placeholderImage","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placeholder"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier"},{"kind":"text","text":" = [], "},{"text":"completed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completedBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SDExternalCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"text":"The url for the image.","type":"text"}]}]},{"name":"placeholder","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to be set initially, until the image request finishes."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values.","type":"text"}]}],"name":"options"},{"name":"completedBlock","content":[{"type":"paragraph","inlineContent":[{"text":"A block called when operation has been completed. This block has no return value","type":"text"},{"type":"text","text":" "},{"type":"text","text":"and takes the requested UIImage as first parameter. In case of error the image parameter"},{"text":" ","type":"text"},{"text":"is nil and the second parameter may contain an NSError. The third parameter is a Boolean","type":"text"},{"type":"text","text":" "},{"type":"text","text":"indicating if the image was retrieved from the local cache or from the network."},{"type":"text","text":" "},{"text":"The fourth parameter is the original image url.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"anchor":"discussion","type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"text":"The download is asynchronous and cached.","type":"text"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Set the imageView "},{"type":"codeVoice","code":"image"},{"type":"text","text":" with an "},{"code":"url","type":"codeVoice"},{"text":", placeholder and custom options.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:completed:)":{"role":"symbol","title":"sd_setImage(with:placeholderImage:options:completed:)","kind":"symbol","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:completed:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:completed:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","kind":"typeIdentifier","text":"SDExternalCompletionBlock"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:completed:)","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"text":" with an ","type":"text"},{"code":"url","type":"codeVoice"},{"type":"text","text":", placeholder and custom options."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDExternalCompletionBlock":{"url":"\/documentation\/sdwebimage\/sdexternalcompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDExternalCompletionBlock","kind":"identifier"}],"title":"SDExternalCompletionBlock","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDExternalCompletionBlock"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"sd_setImageWithURL:placeholderImage:options:completed:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:completed:"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"sd_setImageWithURL:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"url"},{"text":" ","kind":"text"},{"text":"placeholderImage:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"placeholder","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"text":"(","kind":"text"},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completed:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSError#$@E@SDImageCacheType#*$objc(cs)NSURL)","kind":"typeIdentifier","text":"void (^)(UIImage *, NSError *, enum SDImageCacheType, NSURL *)"},{"kind":"text","text":") "},{"text":"completedBlock","kind":"internalParam"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"url","content":[{"inlineContent":[{"type":"text","text":"The url for the image."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image to be set initially, until the image request finishes."}]}],"name":"placeholder"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values."}]}],"name":"options"},{"name":"completedBlock","content":[{"inlineContent":[{"text":"A block called when operation has been completed. This block has no return value","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"and takes the requested UIImage as first parameter. In case of error the image parameter"},{"text":" ","type":"text"},{"text":"is nil and the second parameter may contain an NSError. The third parameter is a Boolean","type":"text"},{"text":" ","type":"text"},{"text":"indicating if the image was retrieved from the local cache or from the network.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The fourth parameter is the original image url."}],"type":"paragraph"}]}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","value":"sd_setImageWithURL:placeholderImage:options:completed:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:completed:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:completed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:placeholderImage:options:completed:","kind":"identifier"}]},{"value":"SDAnimatedImageView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDWebImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/title","value":"SDExternalCompletionBlock","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/fragments","op":"replace","value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/navigatorTitle","value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}