{"abstract":[{"type":"text","text":"Set the imageView "},{"type":"codeVoice","code":"image"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"type":"text","text":"."}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:completed:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:completed:)"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:completed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SDWebImage"}],"symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","kind":"typeIdentifier","text":"SDExternalCompletionBlock"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"sd_setImageWithURL:completed:","kind":"identifier"}],"title":"sd_setImage(with:completed:)","roleHeading":"Instance Method","extendedModule":"SDWebImage","role":"symbol","externalID":"c:objc(cs)SDAnimatedImageView(im)sd_setImageWithURL:completed:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completedBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","text":"SDExternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","kind":"typeIdentifier"},{"text":"? = nil)","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url for the image."}]}]},{"name":"completedBlock","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block called when operation has been completed. This block has no return value"},{"type":"text","text":" "},{"text":"and takes the requested UIImage as first parameter. In case of error the image parameter","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is nil and the second parameter may contain an NSError. The third parameter is a Boolean"},{"type":"text","text":" "},{"type":"text","text":"indicating if the image was retrieved from the local cache or from the network."},{"type":"text","text":" "},{"text":"The fourth parameter is the original image url.","type":"text"}]}]}]},{"kind":"content","content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"inlineContent":[{"text":"The download is asynchronous and cached.","type":"text"}],"type":"paragraph"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDExternalCompletionBlock":{"url":"\/documentation\/sdwebimage\/sdexternalcompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDExternalCompletionBlock","kind":"identifier"}],"title":"SDExternalCompletionBlock","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDExternalCompletionBlock"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:completed:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:completed:)","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDExternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock"},{"text":"?)","kind":"text"}],"title":"sd_setImage(with:completed:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:completed:"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:completed:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"sd_setImageWithURL:completed:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:completed:","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"sd_setImageWithURL:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"text":"void (^)(UIImage *, NSError *, enum SDImageCacheType, NSURL *)","kind":"typeIdentifier","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSError#$@E@SDImageCacheType#*$objc(cs)NSURL)"},{"text":") ","kind":"text"},{"text":"completedBlock","kind":"internalParam"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"url","content":[{"inlineContent":[{"text":"The url for the image.","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block called when operation has been completed. This block has no return value"},{"type":"text","text":" "},{"text":"and takes the requested UIImage as first parameter. In case of error the image parameter","type":"text"},{"text":" ","type":"text"},{"text":"is nil and the second parameter may contain an NSError. The third parameter is a Boolean","type":"text"},{"type":"text","text":" "},{"text":"indicating if the image was retrieved from the local cache or from the network.","type":"text"},{"type":"text","text":" "},{"text":"The fourth parameter is the original image url.","type":"text"}]}],"name":"completedBlock"}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/title","value":"SDExternalCompletionBlock","op":"replace"},{"value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SDExternalCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:completed:)\/title","value":"sd_setImageWithURL:completed:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:completed:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:completed:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"text":"SDAnimatedImageView","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImageView"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle"}]}]}