{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","abstract":[{"text":"Set the imageView ","type":"text"},{"type":"codeVoice","code":"image"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"url"},{"text":", placeholder, custom options and context.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:context:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:context:)"]}],"metadata":{"navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:context:","kind":"identifier"}],"symbolKind":"method","title":"sd_setImage(with:placeholderImage:options:context:)","externalID":"c:objc(cs)SDAnimatedImageView(im)sd_setImageWithURL:placeholderImage:options:context:","extendedModule":"SDWebImage","roleHeading":"Instance Method","modules":[{"name":"SDWebImage"}],"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?)","kind":"text"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"@","kind":"attribute"},{"preciseIdentifier":"s:ScM","text":"MainActor","kind":"attribute"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"placeholderImage","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"placeholder"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"text":" = [], ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The url for the image."}],"type":"paragraph"}],"name":"url"},{"name":"placeholder","content":[{"type":"paragraph","inlineContent":[{"text":"The image to be set initially, until the image request finishes.","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values."}]}],"name":"options"},{"content":[{"inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"code":"SDWebImageContextOption","type":"codeVoice"},{"text":". This hold the extra objects which ","type":"text"},{"type":"codeVoice","code":"options"},{"type":"text","text":" enum can not hold."}],"type":"paragraph"}],"name":"context"}],"kind":"parameters"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The download is asynchronous and cached."}]}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:context:)":{"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:context:)","type":"topic","abstract":[{"text":"Set the imageView ","type":"text"},{"type":"codeVoice","code":"image"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"text":", placeholder, custom options and context.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:context:"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:)","role":"symbol","title":"sd_setImage(with:placeholderImage:options:context:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"sd_setImageWithURL:placeholderImage:options:context:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:context:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:"},{"text":"(","kind":"text"},{"text":"NSURL","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"placeholderImage:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"placeholder"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"text":"context:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","text":"SDWebImageContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":{"parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The url for the image."}]}]},{"content":[{"type":"paragraph","inlineContent":[{"text":"The image to be set initially, until the image request finishes.","type":"text"}]}],"name":"placeholder"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The options to use when downloading the image. @see SDWebImageOptions for the possible values."}]}],"name":"options"},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"text":"A context contains different options to perform specify changes or processes, see ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextOption"},{"text":". This hold the extra objects which ","type":"text"},{"type":"codeVoice","code":"options"},{"text":" enum can not hold.","type":"text"}]}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle"},{"value":"sd_setImageWithURL:placeholderImage:options:context:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:context:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:context:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace","value":"SDWebImageContextOption"},{"value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","op":"replace","value":"SDAnimatedImageView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}