{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/shouldincrementalload"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview\/shouldincrementalload"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldIncrementalLoad","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView"]]},"metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"shouldIncrementalLoad","kind":"identifier"}],"title":"shouldIncrementalLoad","symbolKind":"property","externalID":"c:objc(cs)SDAnimatedImageView(py)shouldIncrementalLoad","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldIncrementalLoad","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"abstract":[{"type":"text","text":"Whehter or not to enable incremental image load for animated image. This is for the animated image which "},{"type":"codeVoice","code":"sd_isIncremental"},{"text":" is YES (See ","type":"text"},{"code":"UIImage+Metadata.h","type":"codeVoice"},{"type":"text","text":"). If enable, animated image rendering will stop at the last frame available currently, and continue when another "},{"code":"setImage:","type":"codeVoice"},{"text":" trigger, where the new animated image’s ","type":"text"},{"type":"codeVoice","code":"animatedImageData"},{"text":" should be updated from the previous one. If the ","type":"text"},{"code":"sd_isIncremental","type":"codeVoice"},{"type":"text","text":" is NO. The incremental image load stop."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","kind":"attribute","preciseIdentifier":"s:ScM"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldIncrementalLoad","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"name":"Note","type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"If you are confused about this description, open Chrome browser to view some large GIF images with low network speed to see the animation behavior.","type":"text"}]}]},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"The best practice to use incremental load is using "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" in "},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" with animated coder which conform to ","type":"text"},{"type":"codeVoice","code":"SDProgressiveImageCoder"},{"type":"text","text":" as well. Then call incremental update and incremental decode method to produce the image."},{"type":"text","text":" "},{"text":"Default is YES. Set to NO to only render the static poster for incremental animated image.","type":"text"}],"type":"paragraph"}],"style":"note","name":"Note"}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/shouldIncrementalLoad":{"type":"topic","title":"shouldIncrementalLoad","navigatorTitle":[{"text":"shouldIncrementalLoad","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldIncrementalLoad","abstract":[{"text":"Whehter or not to enable incremental image load for animated image. This is for the animated image which ","type":"text"},{"type":"codeVoice","code":"sd_isIncremental"},{"type":"text","text":" is YES (See "},{"type":"codeVoice","code":"UIImage+Metadata.h"},{"type":"text","text":"). If enable, animated image rendering will stop at the last frame available currently, and continue when another "},{"type":"codeVoice","code":"setImage:"},{"type":"text","text":" trigger, where the new animated image’s "},{"code":"animatedImageData","type":"codeVoice"},{"text":" should be updated from the previous one. If the ","type":"text"},{"type":"codeVoice","code":"sd_isIncremental"},{"text":" is NO. The incremental image load stop.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldIncrementalLoad"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/shouldincrementalload"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"shouldIncrementalLoad"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"text":"shouldIncrementalLoad","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"text":") ","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":" "},{"text":"shouldIncrementalLoad","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1shouldIncrementalLoad\/title","op":"replace","value":"shouldIncrementalLoad"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1shouldIncrementalLoad\/fragments","value":[{"text":"shouldIncrementalLoad","kind":"identifier"}],"op":"replace"},{"value":"SDAnimatedImageView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","op":"replace"},{"value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace"}]}]}