{"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"always","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/always"},"metadata":{"symbolKind":"case","title":"SDImageForceDecodePolicy.always","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"always","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageForceDecodePolicyAlways","kind":"identifier"}],"externalID":"c:@E@SDImageForceDecodePolicy@SDImageForceDecodePolicyAlways","roleHeading":"Case","role":"symbol"},"sections":[],"kind":"symbol","abstract":[{"text":"Always force decode input CGImage (only once)","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/always"]},{"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/always"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"title":"SDImageForceDecodePolicy","role":"symbol","navigatorTitle":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy","type":"topic","abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"text":" ","type":"text"},{"text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"code":"pre-process","type":"codeVoice"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"text":" ","type":"text"},{"text":"The downside is that force-decode may consume RAM and CPU, and may loss the ","type":"text"},{"type":"codeVoice","code":"lazy"},{"text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/always":{"title":"SDImageForceDecodePolicy.always","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/always","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Always force decode input CGImage (only once)"}],"navigatorTitle":[{"text":"SDImageForceDecodePolicyAlways","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/always","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"always","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SDImageForceDecodePolicyAlways","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicyAlways"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SDImageForceDecodePolicyAlways","kind":"identifier"}],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","value":"SDImageForceDecodePolicy","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/title"},{"value":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/navigatorTitle","value":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"op":"replace"},{"value":"SDImageForceDecodePolicyAlways","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1always\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1always\/fragments","value":[{"text":"SDImageForceDecodePolicyAlways","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}