{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/automatic"},"abstract":[{"text":"Based on input CGImage’s colorspace, alignment, bitmapinfo, if it may trigger ","type":"text"},{"type":"codeVoice","code":"CA::copy_image"},{"text":" extra copy, we will force-decode, else don’t","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}]}]}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/automatic"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/automatic"]}],"metadata":{"externalID":"c:@E@SDImageForceDecodePolicy@SDImageForceDecodePolicyAutomatic","symbolKind":"case","role":"symbol","roleHeading":"Case","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"automatic","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageForceDecodePolicyAutomatic","kind":"identifier"}],"title":"SDImageForceDecodePolicy.automatic","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy"]]},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/automatic":{"abstract":[{"text":"Based on input CGImage’s colorspace, alignment, bitmapinfo, if it may trigger ","type":"text"},{"type":"codeVoice","code":"CA::copy_image"},{"type":"text","text":" extra copy, we will force-decode, else don’t"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/automatic","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"automatic","kind":"identifier"}],"title":"SDImageForceDecodePolicy.automatic","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/automatic","navigatorTitle":[{"text":"SDImageForceDecodePolicyAutomatic","kind":"identifier"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"title":"SDImageForceDecodePolicy","role":"symbol","navigatorTitle":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy","type":"topic","abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"text":" ","type":"text"},{"text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"code":"pre-process","type":"codeVoice"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"text":" ","type":"text"},{"text":"The downside is that force-decode may consume RAM and CPU, and may loss the ","type":"text"},{"type":"codeVoice","code":"lazy"},{"text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDImageForceDecodePolicyAutomatic","op":"replace"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDImageForceDecodePolicyAutomatic","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"SDImageForceDecodePolicyAutomatic","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SDImageForceDecodePolicyAutomatic","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1automatic\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1automatic\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicyAutomatic"}]},{"value":"SDImageForceDecodePolicy","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},{"value":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/navigatorTitle"}]}]}