{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/init(rawvalue:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/init(rawValue:)"},"metadata":{"externalID":"s:So24SDImageForceDecodePolicyV8rawValueABSgSu_tcfc","title":"init(rawValue:)","symbolKind":"init","role":"symbol","roleHeading":"Initializer","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"title":"SDImageForceDecodePolicy","role":"symbol","navigatorTitle":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy","type":"topic","abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"text":" ","type":"text"},{"text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"code":"pre-process","type":"codeVoice"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"text":" ","type":"text"},{"text":"The downside is that force-decode may consume RAM and CPU, and may loss the ","type":"text"},{"type":"codeVoice","code":"lazy"},{"text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/init(rawValue:)":{"role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/init(rawvalue:)","title":"init(rawValue:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/init(rawValue:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SDImageForceDecodePolicy","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/title"},{"value":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/navigatorTitle","op":"replace","value":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}