{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"never","kind":"identifier"}]}]}],"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/never"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/never"]}],"metadata":{"modules":[{"name":"SDWebImage"}],"externalID":"c:@E@SDImageForceDecodePolicy@SDImageForceDecodePolicyNever","roleHeading":"Case","symbolKind":"case","role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"never"}],"navigatorTitle":[{"text":"SDImageForceDecodePolicyNever","kind":"identifier"}],"title":"SDImageForceDecodePolicy.never"},"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/never"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy"]]},"sections":[],"abstract":[{"text":"Never force decode input CGImage","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"title":"SDImageForceDecodePolicy","role":"symbol","navigatorTitle":[{"text":"SDImageForceDecodePolicy","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy","type":"topic","abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"text":" ","type":"text"},{"text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"code":"pre-process","type":"codeVoice"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"text":" ","type":"text"},{"text":"The downside is that force-decode may consume RAM and CPU, and may loss the ","type":"text"},{"type":"codeVoice","code":"lazy"},{"text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/never":{"navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicyNever"}],"abstract":[{"text":"Never force decode input CGImage","type":"text"}],"role":"symbol","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"never","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/never","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/never","title":"SDImageForceDecodePolicy.never"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDImageForceDecodePolicyNever"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicyNever"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"SDImageForceDecodePolicyNever","kind":"identifier"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/title","value":"SDImageForceDecodePolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1never\/title","value":"SDImageForceDecodePolicyNever","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageForceDecodePolicyNever"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1never\/fragments"}]}]}