{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","preciseIdentifier":"c:objc(cs)SDImageHEICCoder","text":"SDImageHEICCoder"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageheiccoder\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageheiccoder\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder\/shared","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}],"role":"symbol","title":"shared","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageHEICCoder","preciseIdentifier":"c:objc(cs)SDImageHEICCoder"}],"symbolKind":"property","externalID":"c:objc(cs)SDImageHEICCoder(cpy)sharedCoder","modules":[{"name":"SDWebImage"}],"platforms":[{"beta":false,"unavailable":false,"name":"iOS","introducedAt":"13.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHEICCoder/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageHEICCoder","preciseIdentifier":"c:objc(cs)SDImageHEICCoder"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}],"url":"\/documentation\/sdwebimage\/sdimageheiccoder\/shared"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHEICCoder":{"role":"symbol","title":"SDImageHEICCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageHEICCoder"}],"abstract":[{"type":"text","text":"This coder is used for HEIC (HEIF with HEVC container codec) image format."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the static HEIC (.heic) support in iOS 11\/macOS 10.13\/tvOS 11\/watchOS 4+."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the animated HEIC (.heics) support in iOS 13\/macOS 10.15\/tvOS 13\/watchOS 6+."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/nokiatech.github.io\/heif\/technical.html for the standard."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageHEICCoder"}],"url":"\/documentation\/sdwebimage\/sdimageheiccoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"sharedCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"sharedCoder"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","preciseIdentifier":"c:objc(cs)SDImageHEICCoder","text":"SDImageHEICCoder"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedCoder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder~1shared\/title","value":"sharedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder~1shared\/fragments","value":[{"kind":"identifier","text":"sharedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/title","value":"SDImageHEICCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/fragments","value":[{"kind":"identifier","text":"SDImageHEICCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}