{"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"invalidDownloadResponse","kind":"identifier"}]}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code\/invalidDownloadResponse","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadResponse"}],"modules":[{"name":"SDWebImage"}],"title":"SDWebImageError.Code.invalidDownloadResponse","externalID":"c:@E@SDWebImageError@SDWebImageErrorInvalidDownloadResponse","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidDownloadResponse"}],"symbolKind":"case","role":"symbol","roleHeading":"Case"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code\/invaliddownloadresponse"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code\/invaliddownloadresponse"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct":{"title":"SDWebImageError","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageError"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageError","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code":{"kind":"symbol","navigatorTitle":[{"text":"Code","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","title":"SDWebImageError.Code","abstract":[{"type":"text","text":"SDWebImage error domain and codes"}],"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"Code","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code/invalidDownloadResponse":{"url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code\/invaliddownloadresponse","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadResponse"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code\/invalidDownloadResponse","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"invalidDownloadResponse"}],"type":"topic","role":"symbol","abstract":[],"title":"SDWebImageError.Code.invalidDownloadResponse"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","value":"SDWebImageErrorInvalidDownloadResponse","path":"\/metadata\/title"},{"value":"case","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadResponse"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SDWebImageErrorInvalidDownloadResponse","kind":"identifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SDWebImageError","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/fragments","value":[{"text":"SDWebImageError","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageError"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code~1invalidDownloadResponse\/title","op":"replace","value":"SDWebImageErrorInvalidDownloadResponse"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code~1invalidDownloadResponse\/fragments","op":"replace","value":[{"text":"SDWebImageErrorInvalidDownloadResponse","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}