{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDownloadOperation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code\/invaliddownloadoperation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code\/invaliddownloadoperation"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code\/invalidDownloadOperation","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDownloadOperation"}],"title":"SDWebImageError.Code.invalidDownloadOperation","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDWebImageError@SDWebImageErrorInvalidDownloadOperation","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadOperation"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct":{"role":"symbol","title":"SDWebImageError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageError"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageError"}],"url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code":{"role":"symbol","title":"SDWebImageError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[{"type":"text","text":"SDWebImage error domain and codes"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageError-swift.struct/Code/invalidDownloadOperation":{"role":"symbol","title":"SDWebImageError.Code.invalidDownloadOperation","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidDownloadOperation"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageError-swift.struct\/Code\/invalidDownloadOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimageerror-swift.struct\/code\/invaliddownloadoperation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageErrorInvalidDownloadOperation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadOperation"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadOperation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/title","value":"SDWebImageError"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"SDWebImageError"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code~1invalidDownloadOperation\/title","value":"SDWebImageErrorInvalidDownloadOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageError-swift.struct~1Code~1invalidDownloadOperation\/fragments","value":[{"kind":"identifier","text":"SDWebImageErrorInvalidDownloadOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}