{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modifiedRequest"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"request"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The original URL request for image loading","type":"text"}]}],"name":"request"}]},{"content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"If return nil, the URL request will be cancelled.","type":"text"}]}],"name":"Note","style":"note"}],"kind":"content"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol\/modifiedRequest(with:)"},"abstract":[{"text":"Modify the original URL request and return a new one instead. You can modify the HTTP header, cachePolicy, etc for this URL.","type":"text"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol\/modifiedrequest(with:)"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol\/modifiedrequest(with:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","metadata":{"externalID":"c:objc(pl)SDWebImageDownloaderRequestModifier(im)modifiedRequestWithRequest:","title":"modifiedRequest(with:)","platforms":[{"name":"iOS","beta":false,"introducedAt":"8.0","deprecated":false,"unavailable":false},{"unavailable":false,"deprecated":false,"beta":false,"introducedAt":"8.0","name":"iPadOS"},{"deprecated":false,"name":"Mac Catalyst","unavailable":false,"beta":false,"introducedAt":"8.0"}],"modules":[{"name":"SDWebImage"}],"required":true,"roleHeading":"Instance Method","role":"symbol","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"modifiedRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"modifiedRequestWithRequest:"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierProtocol":{"type":"topic","abstract":[{"type":"text","text":"This is the protocol for downloader request modifier."},{"type":"text","text":" "},{"text":"We can use a block to specify the downloader request modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","kind":"symbol","title":"SDWebImageDownloaderRequestModifierProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifierProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierProtocol/modifiedRequest(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"modifiedRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"text":"?","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol\/modifiedrequest(with:)","abstract":[{"text":"Modify the original URL request and return a new one instead. You can modify the HTTP header, cachePolicy, etc for this URL.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"modifiedRequestWithRequest:","kind":"identifier"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol\/modifiedRequest(with:)","role":"symbol","title":"modifiedRequest(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"modifiedRequestWithRequest:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"modifiedRequestWithRequest:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"text":"NSURLRequest","preciseIdentifier":"c:objc(cs)NSURLRequest","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"identifier","text":"modifiedRequestWithRequest:"},{"text":"(","kind":"text"},{"text":"NSURLRequest","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLRequest"},{"text":" *) ","kind":"text"},{"text":"request","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"request","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original URL request for image loading"}]}]}],"kind":"parameters"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/title","value":"SDWebImageDownloaderRequestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/fragments","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/navigatorTitle","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"modifiedRequestWithRequest:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol~1modifiedRequest(with:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol~1modifiedRequest(with:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"modifiedRequestWithRequest:"}]}]}]}