{"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avoidAutoCancelImage","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"style":"note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This options is UI level options, has no usage on ImageManager or other components."}]}],"type":"aside","name":"Note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/avoidautocancelimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/avoidautocancelimage"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidAutoCancelImage","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"By defaults, when you use UI-level category like ","type":"text"},{"type":"codeVoice","code":"sd_setImageWithURL:"},{"type":"text","text":" on UIImageView, it will cancel the loading image requests."},{"type":"text","text":" "},{"type":"text","text":"However, some users may choose to not cancel the loading image requests and always start new pipeline."},{"type":"text","text":" "},{"type":"text","text":"Use this flag to disable automatic cancel behavior."}],"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","title":"avoidAutoCancelImage","symbolKind":"property","externalID":"c:@E@SDWebImageOptions@SDWebImageAvoidAutoCancelImage","navigatorTitle":[{"kind":"identifier","text":"SDWebImageAvoidAutoCancelImage"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidAutoCancelImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/avoidAutoCancelImage":{"navigatorTitle":[{"text":"SDWebImageAvoidAutoCancelImage","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/avoidautocancelimage","title":"avoidAutoCancelImage","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidAutoCancelImage","kind":"symbol","type":"topic","abstract":[{"text":"By defaults, when you use UI-level category like ","type":"text"},{"code":"sd_setImageWithURL:","type":"codeVoice"},{"text":" on UIImageView, it will cancel the loading image requests.","type":"text"},{"text":" ","type":"text"},{"text":"However, some users may choose to not cancel the loading image requests and always start new pipeline.","type":"text"},{"text":" ","type":"text"},{"text":"Use this flag to disable automatic cancel behavior.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidAutoCancelImage"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageAvoidAutoCancelImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"text":"SDWebImageAvoidAutoCancelImage","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDWebImageAvoidAutoCancelImage"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidAutoCancelImage\/title","value":"SDWebImageAvoidAutoCancelImage","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageAvoidAutoCancelImage"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidAutoCancelImage\/fragments"},{"value":"SDWebImageOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"value":[{"kind":"identifier","text":"SDWebImageOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","op":"replace"}]}]}