{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidDecodeImage","interfaceLanguage":"swift"},"deprecationSummary":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use SDWebImageContextImageForceDecodePolicy instead"}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/avoiddecodeimage"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/avoiddecodeimage"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"SDWebImage"}],"platforms":[{"unavailable":false,"deprecated":false,"name":"iOS","introducedAt":"8.0","deprecatedAt":"8.0","message":"Use SDWebImageContextImageForceDecodePolicy instead","beta":false},{"deprecatedAt":"8.0","introducedAt":"8.0","name":"iPadOS","unavailable":false,"deprecated":false,"message":"Use SDWebImageContextImageForceDecodePolicy instead","beta":false},{"name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false,"message":"Use SDWebImageContextImageForceDecodePolicy instead","introducedAt":"8.0","deprecatedAt":"8.0"}],"roleHeading":"Type Property","externalID":"c:@E@SDWebImageOptions@SDWebImageAvoidDecodeImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avoidDecodeImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions"}],"title":"avoidDecodeImage","navigatorTitle":[{"text":"SDWebImageAvoidDecodeImage","kind":"identifier"}]},"abstract":[{"text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"However, this process may increase the memory usage as well. If you are experiencing an issue due to excessive memory consumption, This flag can prevent decode the image."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"avoidDecodeImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"content":[{"anchor":"discussion","text":"Discussion","type":"heading","level":2},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"5.14.0 introduce ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"},{"text":", use that for better control from codec, instead of post-processing. Which acts the similar like this option but works for SDAnimatedImage as well (this one does not)","type":"text"}]}]}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/avoidDecodeImage":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidDecodeImage","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/avoiddecodeimage","role":"symbol","abstract":[{"text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation.","type":"text"},{"type":"text","text":" "},{"text":"However, this process may increase the memory usage as well. If you are experiencing an issue due to excessive memory consumption, This flag can prevent decode the image.","type":"text"}],"navigatorTitle":[{"text":"SDWebImageAvoidDecodeImage","kind":"identifier"}],"deprecated":true,"type":"topic","title":"avoidDecodeImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"avoidDecodeImage","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"deprecatedAt":"8.0","introducedAt":"8.0","name":"iOS","deprecated":false,"beta":false,"unavailable":false},{"deprecatedAt":"8.0","introducedAt":"8.0","unavailable":false,"beta":false,"deprecated":false,"name":"iPadOS"},{"unavailable":false,"introducedAt":"8.0","name":"Mac Catalyst","beta":false,"deprecated":false,"deprecatedAt":"8.0"}],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"value":"SDWebImageAvoidDecodeImage","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SDWebImageAvoidDecodeImage"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"SDWebImageAvoidDecodeImage","kind":"identifier"}]}]},"op":"replace"},{"value":"SDWebImageAvoidDecodeImage","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidDecodeImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidDecodeImage\/fragments","value":[{"text":"SDWebImageAvoidDecodeImage","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"text":"SDWebImageOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}