{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/continueinbackground"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/continueinbackground"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/continueInBackground","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"In iOS 4+, continue the download of the image if the app goes to background. This is achieved by asking the system for"},{"type":"text","text":" "},{"type":"text","text":"extra time in background to let the request finish. If the background task expires the operation will be cancelled."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"title":"continueInBackground","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@SDWebImageOptions@SDWebImageContinueInBackground","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"role":"symbol","title":"SDWebImageOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"}],"abstract":[{"type":"text","text":"WebCache options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/continueInBackground":{"role":"symbol","title":"continueInBackground","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"In iOS 4+, continue the download of the image if the app goes to background. This is achieved by asking the system for"},{"type":"text","text":" "},{"type":"text","text":"extra time in background to let the request finish. If the background task expires the operation will be cancelled."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/continueInBackground","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/continueinbackground"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContinueInBackground"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1continueInBackground\/title","value":"SDWebImageContinueInBackground"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1continueInBackground\/fragments","value":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}