{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/decodeFirstFrameOnly"},"metadata":{"externalID":"c:@E@SDWebImageOptions@SDWebImageDecodeFirstFrameOnly","title":"decodeFirstFrameOnly","roleHeading":"Type Property","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDecodeFirstFrameOnly"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"decodeFirstFrameOnly","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"}],"symbolKind":"property","role":"symbol","modules":[{"name":"SDWebImage"}]},"abstract":[{"type":"text","text":"By default, we decode the animated image. This flag can force decode the first frame only and produce the static image."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFirstFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/decodefirstframeonly"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/decodefirstframeonly"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/decodeFirstFrameOnly":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDecodeFirstFrameOnly"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/decodeFirstFrameOnly","type":"topic","title":"decodeFirstFrameOnly","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFirstFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/decodefirstframeonly","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"By default, we decode the animated image. This flag can force decode the first frame only and produce the static image."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration Case","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SDWebImageDecodeFirstFrameOnly","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"value":[{"text":"SDWebImageDecodeFirstFrameOnly","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDWebImageDecodeFirstFrameOnly"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SDWebImageDecodeFirstFrameOnly","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1decodeFirstFrameOnly\/title","op":"replace"},{"value":[{"text":"SDWebImageDecodeFirstFrameOnly","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1decodeFirstFrameOnly\/fragments"},{"value":"SDWebImageOptions","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}]}]}]}