{"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/formunion(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"mutating"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formUnion"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"code":"OptionSet.formUnion(_:)","type":"codeVoice"},{"type":"text","text":"."}],"metadata":{"role":"symbol","conformance":{"conformancePrefix":[{"text":"Conforms when","type":"text"}],"constraints":[{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"FixedWidthInteger","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"text":"Available when","type":"text"}]},"externalID":"s:s9OptionSetPss17FixedWidthInteger8RawValueRpzrlE9formUnionyyxF::SYNTHESIZED::c:@E@SDWebImageOptions","symbolKind":"method","modules":[{"name":"SDWebImage","relatedModules":["Swift"]}],"roleHeading":"Instance Method","title":"formUnion(_:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"formUnion"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":")","kind":"text"}],"extendedModule":"Swift"},"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/formUnion(_:)"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/OptionSet-Implementations"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/OptionSet-Implementations":{"role":"collectionGroup","abstract":[],"title":"OptionSet Implementations","type":"topic","kind":"article","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/OptionSet-Implementations","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/optionset-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/formUnion(_:)":{"type":"topic","abstract":[],"role":"symbol","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"formUnion","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":")"}],"conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"type":"codeVoice","code":"FixedWidthInteger"},{"type":"text","text":"."}]},"title":"formUnion(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/formUnion(_:)","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/formunion(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","op":"replace","value":"SDWebImageOptions"},{"value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace"}]}]}