{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/fromloaderonly"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/fromloaderonly"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromLoaderOnly","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"metadata":{"modules":[{"name":"SDWebImage"}],"title":"fromLoaderOnly","externalID":"c:@E@SDWebImageOptions@SDWebImageFromLoaderOnly","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromLoaderOnly"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property","navigatorTitle":[{"text":"SDWebImageFromLoaderOnly","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"abstract":[{"type":"text","text":"By default, we query the cache before the image is load from the loader. This flag can prevent this to load from loader only."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fromLoaderOnly","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/fromLoaderOnly":{"abstract":[{"type":"text","text":"By default, we query the cache before the image is load from the loader. This flag can prevent this to load from loader only."}],"title":"fromLoaderOnly","navigatorTitle":[{"text":"SDWebImageFromLoaderOnly","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"fromLoaderOnly","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromLoaderOnly","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/fromloaderonly","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SDWebImageFromLoaderOnly","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"case"},{"value":[{"kind":"identifier","text":"SDWebImageFromLoaderOnly"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"identifier","text":"SDWebImageFromLoaderOnly"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1fromLoaderOnly\/title","value":"SDWebImageFromLoaderOnly","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1fromLoaderOnly\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageFromLoaderOnly"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"text":"SDWebImageOptions","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}