{"sections":[],"abstract":[{"text":"By default, when you use ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"type":"text","text":" context option (like using "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":" which designed to use ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":"), we may still use ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" when the memory cache hit, or image decoder is not available to produce one exactlly matching your custom class as a fallback solution."},{"type":"text","text":" "},{"type":"text","text":"Using this option, can ensure we always callback image with your provided class. If failed to produce one, a error with code "},{"code":"SDWebImageErrorBadImageData","type":"codeVoice"},{"text":" will been used.","type":"text"},{"text":" ","type":"text"},{"text":"Note this options is not compatible with ","type":"text"},{"code":"SDWebImageDecodeFirstFrameOnly","type":"codeVoice"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"matchAnimatedImageClass"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"matchAnimatedImageClass","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchAnimatedImageClass"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier"}],"externalID":"c:@E@SDWebImageOptions@SDWebImageMatchAnimatedImageClass","navigatorTitle":[{"kind":"identifier","text":"SDWebImageMatchAnimatedImageClass"}],"roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"symbolKind":"property"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/matchanimatedimageclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/matchanimatedimageclass"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/matchAnimatedImageClass"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/matchAnimatedImageClass":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchAnimatedImageClass"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SDWebImageMatchAnimatedImageClass","kind":"identifier"}],"title":"matchAnimatedImageClass","abstract":[{"type":"text","text":"By default, when you use "},{"code":"SDWebImageContextAnimatedImageClass","type":"codeVoice"},{"text":" context option (like using ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":"), we may still use ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" when the memory cache hit, or image decoder is not available to produce one exactlly matching your custom class as a fallback solution."},{"type":"text","text":" "},{"type":"text","text":"Using this option, can ensure we always callback image with your provided class. If failed to produce one, a error with code "},{"type":"codeVoice","code":"SDWebImageErrorBadImageData"},{"text":" will been used.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Note this options is not compatible with "},{"type":"codeVoice","code":"SDWebImageDecodeFirstFrameOnly"},{"text":", which always produce a UIImage\/NSImage.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/matchanimatedimageclass","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/matchAnimatedImageClass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration Case","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageMatchAnimatedImageClass"},{"op":"replace","value":"case","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageMatchAnimatedImageClass","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SDWebImageMatchAnimatedImageClass","kind":"identifier"}],"platforms":["iOS"]}]}},{"value":"SDWebImageOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"text":"SDWebImageOptions","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1matchAnimatedImageClass\/title","value":"SDWebImageMatchAnimatedImageClass"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1matchAnimatedImageClass\/fragments","value":[{"text":"SDWebImageMatchAnimatedImageClass","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}