{"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"title":"refreshCached","symbolKind":"property","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageRefreshCached"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshCached"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"}],"roleHeading":"Type Property","externalID":"c:@E@SDWebImageOptions@SDWebImageRefreshCached","modules":[{"name":"SDWebImage"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"refreshCached","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","text":"Discussion","level":2,"type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Use this flag only if you can’t make your URLs static with embedded cache busting parameter.","type":"text"}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/refreshcached"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/refreshcached"],"traits":[{"interfaceLanguage":"occ"}]}],"abstract":[{"text":"Even if the image is cached, respect the HTTP response cache control, and refresh the image from remote location if needed.","type":"text"},{"text":" ","type":"text"},{"text":"The disk caching will be handled by NSURLCache instead of SDWebImage leading to slight performance degradation.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This option helps deal with images changing behind the same request URL, e.g. Facebook graph api profile pics."},{"text":" ","type":"text"},{"text":"If a cached image is refreshed, the completion block is called once with the cached image and again with the final image.","type":"text"}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/refreshCached"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/refreshCached":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"refreshCached"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/refreshcached","title":"refreshCached","abstract":[{"type":"text","text":"Even if the image is cached, respect the HTTP response cache control, and refresh the image from remote location if needed."},{"text":" ","type":"text"},{"type":"text","text":"The disk caching will be handled by NSURLCache instead of SDWebImage leading to slight performance degradation."},{"type":"text","text":" "},{"type":"text","text":"This option helps deal with images changing behind the same request URL, e.g. Facebook graph api profile pics."},{"text":" ","type":"text"},{"text":"If a cached image is refreshed, the completion block is called once with the cached image and again with the final image.","type":"text"}],"navigatorTitle":[{"text":"SDWebImageRefreshCached","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/refreshCached"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageRefreshCached"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageRefreshCached"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDWebImageRefreshCached"}],"platforms":["iOS"]}]}},{"value":"SDWebImageOptions","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"text":"SDWebImageOptions","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDWebImageRefreshCached","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1refreshCached\/title"},{"value":[{"kind":"identifier","text":"SDWebImageRefreshCached"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1refreshCached\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}