{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/scaledownlargeimages"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/scaledownlargeimages"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/scaleDownLargeImages","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"By default, images are decoded respecting their original size."},{"type":"text","text":" "},{"type":"text","text":"This flag will scale down the images to a size compatible with the constrained memory of devices."},{"type":"text","text":" "},{"type":"text","text":"To control the limit memory bytes, check "},{"type":"codeVoice","code":"SDImageCoderHelper.defaultScaleDownLimitBytes"},{"type":"text","text":" (Defaults to 60MB on iOS)"},{"type":"text","text":" "},{"type":"text","text":"This will actually translate to use context option "},{"type":"codeVoice","code":".imageThumbnailPixelSize"},{"type":"text","text":" from v5.5.0 (Defaults to (3966, 3966) on iOS). Previously does not."},{"type":"text","text":" "},{"type":"text","text":"This flags effect the progressive and animated images as well from v5.5.0. Previously does not."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"title":"scaleDownLargeImages","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@SDWebImageOptions@SDWebImageScaleDownLargeImages","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"role":"symbol","title":"SDWebImageOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"}],"abstract":[{"type":"text","text":"WebCache options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/scaleDownLargeImages":{"role":"symbol","title":"scaleDownLargeImages","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, images are decoded respecting their original size."},{"type":"text","text":" "},{"type":"text","text":"This flag will scale down the images to a size compatible with the constrained memory of devices."},{"type":"text","text":" "},{"type":"text","text":"To control the limit memory bytes, check "},{"type":"codeVoice","code":"SDImageCoderHelper.defaultScaleDownLimitBytes"},{"type":"text","text":" (Defaults to 60MB on iOS)"},{"type":"text","text":" "},{"type":"text","text":"This will actually translate to use context option "},{"type":"codeVoice","code":".imageThumbnailPixelSize"},{"type":"text","text":" from v5.5.0 (Defaults to (3966, 3966) on iOS). Previously does not."},{"type":"text","text":" "},{"type":"text","text":"This flags effect the progressive and animated images as well from v5.5.0. Previously does not."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/scaleDownLargeImages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/scaledownlargeimages"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageScaleDownLargeImages"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1scaleDownLargeImages\/title","value":"SDWebImageScaleDownLargeImages"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1scaleDownLargeImages\/fragments","value":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}