{"sections":[],"kind":"symbol","metadata":{"symbolKind":"property","roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"externalID":"c:@E@SDWebImageOptions@SDWebImageWaitTransition","title":"waitTransition","navigatorTitle":[{"text":"SDWebImageWaitTransition","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"waitTransition","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/waitTransition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"By defaults, for "},{"code":"SDWebImageTransition","type":"codeVoice"},{"type":"text","text":", we just submit to UI transition and inmeediatelly callback the final "},{"type":"codeVoice","code":"completedBlock"},{"text":" (","type":"text"},{"code":"SDExternalCompletionBlock\/SDInternalCompletionBlock","type":"codeVoice"},{"type":"text","text":")."},{"text":" ","type":"text"},{"text":"This may cause un-wanted behavior if you do another transition inside ","type":"text"},{"type":"codeVoice","code":"completedBlock"},{"text":", because the previous transition is still runnning and un-cancellable, which mass-up the UI status.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For this case, you can pass this option, we will delay the final callback, until your transition end. So when you inside "},{"code":"completedBlock","type":"codeVoice"},{"text":", no any transition is running on image view and safe to submit new transition.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"waitTransition"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","text":"Discussion","level":2},{"content":[{"inlineContent":[{"type":"text","text":"Currently we do not support "},{"code":"pausable\/cancellable","type":"codeVoice"},{"type":"text","text":" transition. But possible in the future by using the https:\/\/developer.apple.com\/documentation\/uikit\/uiviewpropertyanimator."}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"},{"style":"note","type":"aside","name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you have complicated transition animation, just use "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":" and do UI state management by yourself, do not use the top-level API ("},{"code":"sd_setImageWithURL:","type":"codeVoice"},{"text":")","type":"text"}]}]}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/waittransition"]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions\/waittransition"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/waitTransition":{"role":"symbol","abstract":[{"type":"text","text":"By defaults, for "},{"type":"codeVoice","code":"SDWebImageTransition"},{"text":", we just submit to UI transition and inmeediatelly callback the final ","type":"text"},{"code":"completedBlock","type":"codeVoice"},{"type":"text","text":" ("},{"type":"codeVoice","code":"SDExternalCompletionBlock\/SDInternalCompletionBlock"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"This may cause un-wanted behavior if you do another transition inside ","type":"text"},{"code":"completedBlock","type":"codeVoice"},{"type":"text","text":", because the previous transition is still runnning and un-cancellable, which mass-up the UI status."},{"type":"text","text":" "},{"type":"text","text":"For this case, you can pass this option, we will delay the final callback, until your transition end. So when you inside "},{"type":"codeVoice","code":"completedBlock"},{"type":"text","text":", no any transition is running on image view and safe to submit new transition."}],"type":"topic","navigatorTitle":[{"text":"SDWebImageWaitTransition","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/waittransition","kind":"symbol","title":"waitTransition","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/waitTransition","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"waitTransition","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageWaitTransition"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDWebImageWaitTransition","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"SDWebImageWaitTransition","kind":"identifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1waitTransition\/title","value":"SDWebImageWaitTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1waitTransition\/fragments","value":[{"text":"SDWebImageWaitTransition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle"}]}]}