{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachetype\/all"]},{"paths":["\/documentation\/sdwebimage\/sdimagecachetype\/all"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"symbolKind":"case","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeAll"}],"roleHeading":"Case","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"externalID":"c:@E@SDImageCacheType@SDImageCacheTypeAll","title":"SDImageCacheType.all","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/all"},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"all","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"For query and contains op in response, this type is not available and take no effect."},{"text":" ","type":"text"},{"text":"For op in request, means process both memory cache and disk cache.","type":"text"}],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/all":{"abstract":[{"type":"text","text":"For query and contains op in response, this type is not available and take no effect."},{"type":"text","text":" "},{"text":"For op in request, means process both memory cache and disk cache.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/all","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"title":"SDImageCacheType.all","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachetype\/all","navigatorTitle":[{"text":"SDImageCacheTypeAll","kind":"identifier"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image Cache Type"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","url":"\/documentation\/sdwebimage\/sdimagecachetype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheType"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"path":"\/metadata\/title","op":"replace","value":"SDImageCacheTypeAll"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheTypeAll"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDImageCacheTypeAll"}],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SDImageCacheTypeAll","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1all\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1all\/fragments","value":[{"text":"SDImageCacheTypeAll","kind":"identifier"}]},{"value":"SDImageCacheType","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title"},{"value":[{"text":"SDImageCacheType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/navigatorTitle","op":"replace","value":[{"text":"SDImageCacheType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}