{"metadata":{"role":"symbol","title":"SDImageCacheType.memory","roleHeading":"Case","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeMemory"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memory","kind":"identifier"}],"externalID":"c:@E@SDImageCacheType@SDImageCacheTypeMemory","symbolKind":"case","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/memory","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For query and contains op in response, means the image was obtained from the memory cache."},{"type":"text","text":" "},{"text":"For op in request, means process only memory cache.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachetype\/memory"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachetype\/memory"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"memory","kind":"identifier"}],"platforms":["iOS"]}]}],"sections":[],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/memory":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/memory","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeMemory"}],"type":"topic","abstract":[{"type":"text","text":"For query and contains op in response, means the image was obtained from the memory cache."},{"type":"text","text":" "},{"text":"For op in request, means process only memory cache.","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memory"}],"title":"SDImageCacheType.memory","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecachetype\/memory"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image Cache Type"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","url":"\/documentation\/sdwebimage\/sdimagecachetype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheTypeMemory"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeMemory"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"SDImageCacheTypeMemory","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1memory\/title","value":"SDImageCacheTypeMemory","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheTypeMemory"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1memory\/fragments"},{"op":"replace","value":"SDImageCacheType","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title"},{"value":[{"kind":"identifier","text":"SDImageCacheType"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments"},{"op":"replace","value":[{"text":"SDImageCacheType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/navigatorTitle"}]}]}