{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachetype\/none"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachetype\/none"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/none","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"For query and contains op in response, means the image isn’t available in the image cache"},{"type":"text","text":" "},{"type":"text","text":"For op in request, this type is not available and take no effect."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"title":"SDImageCacheType.none","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDImageCacheType@SDImageCacheTypeNone","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeNone"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"role":"symbol","title":"SDImageCacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"}],"abstract":[{"type":"text","text":"Image Cache Type"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/none":{"role":"symbol","title":"SDImageCacheType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"For query and contains op in response, means the image isn’t available in the image cache"},{"type":"text","text":" "},{"type":"text","text":"For op in request, this type is not available and take no effect."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeNone"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype\/none"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheTypeNone"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeNone"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageCacheTypeNone"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","value":"SDImageCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1none\/title","value":"SDImageCacheTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1none\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeNone"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}