{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageiocoder\/init(incrementalwithoptions:)"]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Inherited from "},{"code":"SDImageIOCoder.init(incrementalWithOptions:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOCoder"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"incrementalWithOptions"},{"text":" ","kind":"text"},{"text":"options","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]? = nil)"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOCoder\/init(incrementalWithOptions:)"},"kind":"symbol","metadata":{"symbolKind":"init","roleHeading":"Initializer","title":"init(incrementalWithOptions:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"incrementalWithOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(pl)SDProgressiveImageCoder(im)initIncrementalWithOptions:::SYNTHESIZED::c:objc(cs)SDImageIOCoder"},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOCoder":{"kind":"symbol","type":"topic","title":"SDImageIOCoder","navigatorTitle":[{"text":"SDImageIOCoder","kind":"identifier"}],"abstract":[{"text":"Built in coder that supports PNG, JPEG, TIFF, includes support for progressive decoding.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOCoder","url":"\/documentation\/sdwebimage\/sdimageiocoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDImageIOCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOCoder/init(incrementalWithOptions:)":{"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOCoder\/init(incrementalWithOptions:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"incrementalWithOptions"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}],"type":"topic","title":"init(incrementalWithOptions:)","url":"\/documentation\/sdwebimage\/sdimageiocoder\/init(incrementalwithoptions:)","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"SDImageIOCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOCoder\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageIOCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOCoder\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOCoder\/navigatorTitle","value":[{"text":"SDImageIOCoder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","op":"replace","value":[{"text":"SDImageCoderOption","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle","value":[{"text":"SDImageCoderOption","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}