{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SQ","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SH","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SY","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Inherited from "},{"type":"codeVoice","code":"_BridgedStoredNSError.Code"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"title":"SDWebImagePhotosError.Code","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@SDWebImagePhotosError","modules":[{"name":"SDWebImagePhotosPlugin"}],"navigatorTitle":[{"kind":"identifier","text":"Code"}]},"hierarchy":{"paths":[["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notAuthorized","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notImageAsset"]},{"title":"Initializers","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/Equatable-Implementations","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin":{"role":"collection","title":"SDWebImagePhotosPlugin","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/rawrepresentable-implementations"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/notAuthorized":{"role":"symbol","title":"SDWebImagePhotosError.Code.notAuthorized","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notAuthorized"}],"abstract":[{"type":"text","text":"Photos framework access is not authorized by user"}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notAuthorized","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notauthorized"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code":{"role":"symbol","title":"SDWebImagePhotosError.Code","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"Code"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"Code"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/notImageAsset":{"role":"symbol","title":"SDWebImagePhotosError.Code.notImageAsset","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"notImageAsset"}],"abstract":[{"type":"text","text":"Photos URL is not image asset type (like Video or Audio)"}],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notImageAsset","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/notimageasset"},"doc://org.cocoapods.SDWebImagePhotosPlugin/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SQ"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct":{"role":"symbol","title":"SDWebImagePhotosError","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosError"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePhotosError"}],"url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/init(rawvalue:)"},"doc://org.cocoapods.SDWebImagePhotosPlugin/documentation/SDWebImagePhotosPlugin/SDWebImagePhotosError-swift.struct/Code/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimagephotosplugin\/sdwebimagephotoserror-swift.struct\/code\/equatable-implementations"},"doc://org.cocoapods.SDWebImagePhotosPlugin/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SH"},"doc://org.cocoapods.SDWebImagePhotosPlugin/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/SY"},"doc://org.cocoapods.SDWebImagePhotosPlugin/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImagePhotosError"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosError"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImagePhotosError"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notAuthorized","doc:\/\/org.cocoapods.SDWebImagePhotosPlugin\/documentation\/SDWebImagePhotosPlugin\/SDWebImagePhotosError-swift.struct\/Code\/notImageAsset"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePhotosError"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notAuthorized\/title","value":"SDWebImagePhotosErrorNotAuthorized"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notAuthorized\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotAuthorized"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code\/title","value":"SDWebImagePhotosError"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosError"}]},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notImageAsset\/title","value":"SDWebImagePhotosErrorNotImageAsset"},{"op":"replace","path":"\/references\/doc:~1~1org.cocoapods.SDWebImagePhotosPlugin~1documentation~1SDWebImagePhotosPlugin~1SDWebImagePhotosError-swift.struct~1Code~1notImageAsset\/fragments","value":[{"kind":"identifier","text":"SDWebImagePhotosErrorNotImageAsset"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}