{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecombinedoperation\/cancel()"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecombinedoperation\/cancel()"]}],"metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"cancel","kind":"identifier"}],"role":"symbol","title":"cancel()","symbolKind":"method","roleHeading":"Instance Method","externalID":"c:objc(cs)SDWebImageCombinedOperation(im)cancel","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation\/cancel()","interfaceLanguage":"swift"},"abstract":[{"text":"Cancel the current operation, including cache and loader process","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"kind":"text","text":"()"}]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation/cancel()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cancel","kind":"identifier"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"cancel","kind":"identifier"}],"role":"symbol","kind":"symbol","type":"topic","title":"cancel()","url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation\/cancel()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation\/cancel()","abstract":[{"type":"text","text":"Cancel the current operation, including cache and loader process"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation":{"title":"SDWebImageCombinedOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"navigatorTitle":[{"text":"SDWebImageCombinedOperation","kind":"identifier"}],"abstract":[{"text":"A combined operation representing the cache and loader operation. You can use it to cancel the load process.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"cancel"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"cancel","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation~1cancel()\/title","value":"cancel","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation~1cancel()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cancel","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/title","value":"SDWebImageCombinedOperation","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}]}]}]}