{"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loaderOperation"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","text":"SDWebImageOperation"},{"kind":"text","text":")? { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"abstract":[{"text":"The loader operation from the image loader (such as download operation)","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecombinedoperation\/loaderoperation"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecombinedoperation\/loaderoperation"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation\/loaderOperation"},"metadata":{"modules":[{"name":"SDWebImage"}],"title":"loaderOperation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"loaderOperation","kind":"identifier"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageOperation","text":"SDWebImageOperation"},{"text":")?","kind":"text"}],"navigatorTitle":[{"text":"loaderOperation","kind":"identifier"}],"externalID":"c:objc(cs)SDWebImageCombinedOperation(py)loaderOperation","roleHeading":"Instance Property","symbolKind":"property","role":"symbol"},"schemaVersion":{"patch":0,"minor":3,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"url":"\/documentation\/sdwebimage\/sdwebimageoperation","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOperation"}],"navigatorTitle":[{"text":"SDWebImageOperation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SDWebImageOperation","abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation/loaderOperation":{"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"loaderOperation","kind":"identifier"}],"abstract":[{"type":"text","text":"The loader operation from the image loader (such as download operation)"}],"title":"loaderOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation\/loaderOperation","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loaderOperation"},{"kind":"text","text":": (any "},{"text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation\/loaderoperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation":{"title":"SDWebImageCombinedOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"navigatorTitle":[{"text":"SDWebImageCombinedOperation","kind":"identifier"}],"abstract":[{"text":"A combined operation representing the cache and loader operation. You can use it to cancel the load process.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","value":"loaderOperation","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"loaderOperation"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"strong"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Qoobjc(pl)SDWebImageOperation","text":"id<SDWebImageOperation>","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"loaderOperation","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title","value":"SDWebImageOperation"},{"value":[{"kind":"identifier","text":"SDWebImageOperation"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments"},{"value":[{"text":"SDWebImageOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation~1loaderOperation\/title","value":"loaderOperation"},{"value":[{"text":"loaderOperation","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation~1loaderOperation\/fragments","op":"replace"},{"op":"replace","value":"SDWebImageCombinedOperation","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/fragments","value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageCombinedOperation","kind":"identifier"}]}]}]}