{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The option to scale the content to fill the size of the view. Some portion of the content may be clipped to fill the view’s bounds."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/aspectFill"},"kind":"symbol","primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectFill"}],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagescalemode\/aspectfill"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagescalemode\/aspectfill"]}],"sections":[],"metadata":{"roleHeading":"Case","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"aspectFill"}],"title":"SDImageScaleMode.aspectFill","modules":[{"name":"SDWebImage"}],"externalID":"c:@E@SDImageScaleMode@SDImageScaleModeAspectFill","role":"symbol","symbolKind":"case","navigatorTitle":[{"text":"SDImageScaleModeAspectFill","kind":"identifier"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode/aspectFill":{"kind":"symbol","abstract":[{"type":"text","text":"The option to scale the content to fill the size of the view. Some portion of the content may be clipped to fill the view’s bounds."}],"type":"topic","title":"SDImageScaleMode.aspectFill","url":"\/documentation\/sdwebimage\/sdimagescalemode\/aspectfill","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/aspectFill","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"aspectFill","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleModeAspectFill"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode":{"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleMode"}],"url":"\/documentation\/sdwebimage\/sdimagescalemode","title":"SDImageScaleMode","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","type":"topic","abstract":[{"type":"text","text":"The scale mode to apply when image drawing on a container with different sizes."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageScaleMode","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Enumeration Case","op":"replace"},{"value":"SDImageScaleModeAspectFill","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"case","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageScaleModeAspectFill","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageScaleModeAspectFill"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SDImageScaleModeAspectFill","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode~1aspectFill\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageScaleModeAspectFill"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode~1aspectFill\/fragments"},{"value":"SDImageScaleMode","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/title"},{"value":[{"kind":"identifier","text":"SDImageScaleMode"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageScaleMode"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/navigatorTitle"}]}]}