{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectFit"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagescalemode\/aspectfit"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagescalemode\/aspectfit"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/aspectFit","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The option to scale the content to fit the size of the view by maintaining the aspect ratio. Any remaining area of the view’s bounds is transparent."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectFit"}],"title":"SDImageScaleMode.aspectFit","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDImageScaleMode@SDImageScaleModeAspectFit","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleModeAspectFit"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode/aspectFit":{"role":"symbol","title":"SDImageScaleMode.aspectFit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"aspectFit"}],"abstract":[{"type":"text","text":"The option to scale the content to fit the size of the view by maintaining the aspect ratio. Any remaining area of the view’s bounds is transparent."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/aspectFit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageScaleModeAspectFit"}],"url":"\/documentation\/sdwebimage\/sdimagescalemode\/aspectfit"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode":{"role":"symbol","title":"SDImageScaleMode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageScaleMode"}],"abstract":[{"type":"text","text":"The scale mode to apply when image drawing on a container with different sizes."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageScaleMode"}],"url":"\/documentation\/sdwebimage\/sdimagescalemode"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageScaleModeAspectFit"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageScaleModeAspectFit"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageScaleModeAspectFit"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode~1aspectFit\/title","value":"SDImageScaleModeAspectFit"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode~1aspectFit\/fragments","value":[{"kind":"identifier","text":"SDImageScaleModeAspectFit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/title","value":"SDImageScaleMode"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/fragments","value":[{"kind":"identifier","text":"SDImageScaleMode"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}