{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"topicSections":[{"title":"Operators","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/!=(_:_:)"],"anchor":"Operators","generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/Equatable-Implementations"},"metadata":{"modules":[{"name":"SDWebImage"}],"role":"collectionGroup","roleHeading":"API Collection","title":"Equatable Implementations"},"kind":"article","variants":[{"paths":["\/documentation\/sdwebimage\/sdimagescalemode\/equatable-implementations"],"traits":[{"interfaceLanguage":"swift"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode/!=(_:_:)":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"kind":"text","text":"("},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"title":"!=(_:_:)","kind":"symbol","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagescalemode\/!=(_:_:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode\/!=(_:_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleMode":{"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleMode"}],"url":"\/documentation\/sdwebimage\/sdimagescalemode","title":"SDImageScaleMode","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleMode","type":"topic","abstract":[{"type":"text","text":"The scale mode to apply when image drawing on a container with different sizes."}],"kind":"symbol","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageScaleMode","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SDImageScaleMode","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/fragments","value":[{"text":"SDImageScaleMode","kind":"identifier"}]},{"value":[{"text":"SDImageScaleMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleMode\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}