{"sections":[],"abstract":[{"type":"text","text":"Specifying whether the bitmap context should use extended color."},{"text":" ","type":"text"},{"text":"For iOS 12+, the value is from system ","type":"text"},{"type":"codeVoice","code":"preferredRange"},{"type":"text","text":" property"},{"type":"text","text":" "},{"text":"For iOS 10-11, the value is from system ","type":"text"},{"type":"codeVoice","code":"prefersExtendedRange"},{"text":" property","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For iOS 9-, the value is "},{"type":"codeVoice","code":".standard"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredRange"},{"kind":"text","text":": "},{"text":"SDGraphicsImageRendererFormatRange","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDGraphicsImageRendererFormatRange"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferredrange"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferredrange"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat"]]},"metadata":{"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDGraphicsImageRendererFormat(py)preferredRange","roleHeading":"Instance Property","symbolKind":"property","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferredRange","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDGraphicsImageRendererFormatRange","text":"SDGraphicsImageRendererFormatRange"}],"navigatorTitle":[{"kind":"identifier","text":"preferredRange"}],"title":"preferredRange"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferredRange","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat":{"title":"SDGraphicsImageRendererFormat","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"abstract":[{"text":"A set of drawing attributes that represent the configuration of an image renderer context.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange","abstract":[{"type":"text","text":"Constants that specify the color range of the image renderer context."}],"title":"SDGraphicsImageRendererFormatRange","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/preferredRange":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferredRange","abstract":[{"text":"Specifying whether the bitmap context should use extended color.","type":"text"},{"type":"text","text":" "},{"text":"For iOS 12+, the value is from system ","type":"text"},{"type":"codeVoice","code":"preferredRange"},{"type":"text","text":" property"},{"text":" ","type":"text"},{"text":"For iOS 10-11, the value is from system ","type":"text"},{"type":"codeVoice","code":"prefersExtendedRange"},{"text":" property","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For iOS 9-, the value is "},{"type":"codeVoice","code":".standard"}],"title":"preferredRange","kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferredrange","navigatorTitle":[{"text":"preferredRange","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredRange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDGraphicsImageRendererFormatRange","text":"SDGraphicsImageRendererFormatRange","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"preferredRange"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"preferredRange","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SDGraphicsImageRendererFormatRange","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDGraphicsImageRendererFormatRange"},{"kind":"text","text":" "},{"text":"preferredRange","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/title","value":"SDGraphicsImageRendererFormat"},{"op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/fragments"},{"value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/navigatorTitle","op":"replace"},{"value":"SDGraphicsImageRendererFormatRange","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/navigatorTitle","op":"replace","value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]},{"value":"preferredRange","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferredRange\/title"},{"value":[{"text":"preferredRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferredRange\/fragments"}]}]}