{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferred"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferred()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferred()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferred()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns a new format best suited for the main screen’s current configuration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferred"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"preferred()","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDGraphicsImageRendererFormat(cm)preferredFormat","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"preferredFormat"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat":{"role":"symbol","title":"SDGraphicsImageRendererFormat","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}],"abstract":[{"type":"text","text":"A set of drawing attributes that represent the configuration of an image renderer context."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/preferred()":{"role":"symbol","title":"preferred()","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferred"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Returns a new format best suited for the main screen’s current configuration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferred()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"preferredFormat"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferred()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"preferredFormat"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"preferredFormat"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"preferredFormat"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/title","value":"SDGraphicsImageRendererFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferred()\/title","value":"preferredFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferred()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"preferredFormat"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}