{"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/scale","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","abstract":[{"type":"text","text":"The display scale of the image renderer context."},{"text":" ","type":"text"},{"text":"The default value is equal to the scale of the main screen.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/scale"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/scale"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"scale","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","symbolKind":"property","title":"scale","roleHeading":"Instance Property","externalID":"c:objc(cs)SDGraphicsImageRendererFormat(py)scale","navigatorTitle":[{"text":"scale","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/scale":{"title":"scale","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/scale","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"text":"scale","kind":"identifier"}],"abstract":[{"type":"text","text":"The display scale of the image renderer context."},{"type":"text","text":" "},{"text":"The default value is equal to the scale of the main screen.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/scale","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat":{"title":"SDGraphicsImageRendererFormat","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"abstract":[{"text":"A set of drawing attributes that represent the configuration of an image renderer context.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"scale","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","value":[{"text":"scale","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"text":"scale","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1scale\/title","op":"replace","value":"scale"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1scale\/fragments","op":"replace","value":[{"text":"scale","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/title","value":"SDGraphicsImageRendererFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/navigatorTitle","op":"replace","value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}]}]}]}