{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/uiformat"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"uiformat","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGraphicsImageRendererFormat","text":"UIGraphicsImageRendererFormat"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"type":"text","text":"The underlying uiformat for UIKit. This usage of this API should be careful, which may cause out of sync."}],"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/uiformat"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/uiformat"]}],"metadata":{"title":"uiformat","externalID":"c:objc(cs)SDGraphicsImageRendererFormat(py)uiformat","symbolKind":"property","role":"symbol","navigatorTitle":[{"text":"uiformat","kind":"identifier"}],"roleHeading":"Instance Property","platforms":[{"introducedAt":"10.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"introducedAt":"10.0","beta":false},{"unavailable":false,"name":"Mac Catalyst","introducedAt":"10.0","deprecated":false,"beta":false}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"uiformat","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGraphicsImageRendererFormat","text":"UIGraphicsImageRendererFormat"}],"modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat":{"title":"SDGraphicsImageRendererFormat","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"abstract":[{"text":"A set of drawing attributes that represent the configuration of an image renderer context.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/uiformat":{"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/uiformat","type":"topic","abstract":[{"type":"text","text":"The underlying uiformat for UIKit. This usage of this API should be careful, which may cause out of sync."}],"kind":"symbol","title":"uiformat","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/uiformat","navigatorTitle":[{"kind":"identifier","text":"uiformat"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiformat"},{"text":": ","kind":"text"},{"text":"UIGraphicsImageRendererFormat","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGraphicsImageRendererFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":[{"introducedAt":"10.0","deprecated":false,"unavailable":false,"name":"iOS","beta":false},{"deprecated":false,"name":"iPadOS","introducedAt":"10.0","unavailable":false,"beta":false},{"introducedAt":"10.0","beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst"}],"op":"replace","path":"\/metadata\/platforms"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"value":"uiformat","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"uiformat","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGraphicsImageRendererFormat","text":"UIGraphicsImageRendererFormat"},{"text":" * ","kind":"text"},{"text":"uiformat","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/title","op":"replace","value":"SDGraphicsImageRendererFormat"},{"op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/navigatorTitle","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1uiformat\/title","value":"uiformat"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1uiformat\/fragments","value":[{"text":"uiformat","kind":"identifier"}],"op":"replace"}]}]}