{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator","preciseIdentifier":"c:objc(cs)SDWebImageProgressIndicator","text":"SDWebImageProgressIndicator"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprogressindicator\/default"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageprogressindicator\/default"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/default","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"default-style progress indicator"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"defaultIndicator"}],"role":"symbol","title":"default","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageProgressIndicator","preciseIdentifier":"c:objc(cs)SDWebImageProgressIndicator"}],"symbolKind":"property","externalID":"c:objc(cs)SDWebImageProgressIndicator(cpy)defaultIndicator","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator":{"role":"symbol","title":"SDWebImageProgressIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"abstract":[{"type":"text","text":"Progress indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"type":"codeVoice","code":"UIProgressView"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"type":"codeVoice","code":"NSProgressIndicator"},{"type":"text","text":" with the bar style."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator/default":{"role":"symbol","title":"default","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageProgressIndicator","preciseIdentifier":"c:objc(cs)SDWebImageProgressIndicator"}],"abstract":[{"type":"text","text":"default-style progress indicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator\/default"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultIndicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator","preciseIdentifier":"c:objc(cs)SDWebImageProgressIndicator","text":"SDWebImageProgressIndicator"},{"kind":"text","text":" * "},{"kind":"identifier","text":"defaultIndicator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/title","value":"SDWebImageProgressIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1default\/title","value":"defaultIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1default\/fragments","value":[{"kind":"identifier","text":"defaultIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}