{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/indicatorView"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"indicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UIProgressView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIProgressView"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprogressindicator\/indicatorview"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprogressindicator\/indicatorview"]}],"sections":[],"metadata":{"navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDWebImageProgressIndicator(py)indicatorView","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"indicatorView","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIProgressView","text":"UIProgressView","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator","abstract":[{"type":"text","text":"Progress indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIProgressView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"type":"codeVoice","code":"NSProgressIndicator"},{"text":" with the bar style.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"kind":"symbol","type":"topic","title":"SDWebImageProgressIndicator","url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator/indicatorView":{"role":"symbol","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"indicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIProgressView","text":"UIProgressView","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator\/indicatorview","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/indicatorView","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"indicatorView"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"indicatorView","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"UIProgressView","preciseIdentifier":"c:objc(cs)UIProgressView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"indicatorView"},{"kind":"text","text":";"}]}]},"op":"replace"},{"value":"SDWebImageProgressIndicator","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/fragments","op":"replace","value":[{"text":"SDWebImageProgressIndicator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/navigatorTitle","value":[{"text":"SDWebImageProgressIndicator","kind":"identifier"}]},{"value":"indicatorView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1indicatorView\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1indicatorView\/fragments","value":[{"text":"indicatorView","kind":"identifier"}],"op":"replace"}]}]}