{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageWebPCoder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)NSObject","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDAnimatedImageCoder","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDAnimatedImageProvider","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDImageCoder","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDProgressiveImageCoder","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/s7CVarArgP","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/s28CustomDebugStringConvertibleP","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/s23CustomStringConvertibleP","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/SQ","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Built in coder that supports WebP and animated WebP"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageWebPCoder"}],"title":"SDImageWebPCoder","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDImageWebPCoder","modules":[{"name":"SDWebImageWebPCoder"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageWebPCoder"}]},"hierarchy":{"paths":[["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/init(animatedImageData:options:)","doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/init(incrementalWithOptions:)"]},{"title":"Type Properties","identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/shared"]}],"references":{"doc://org.SDWebImage.SDWebImageWebPCoder/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)NSObject"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageWebPCoder","preciseIdentifier":"c:objc(cs)SDImageWebPCoder"}],"abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedCoder"}],"url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder\/shared"},"doc://org.SDWebImage.SDWebImageWebPCoder/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/s28CustomDebugStringConvertibleP"},"doc://org.SDWebImage.SDWebImageWebPCoder/objc(pl)SDAnimatedImageCoder":{"type":"unresolvable","title":"SDWebImage.SDAnimatedImageCoder","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDAnimatedImageCoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/s23CustomStringConvertibleP"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder/init(incrementalWithOptions:)":{"role":"symbol","title":"init(incrementalWithOptions:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"incrementalWithOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/init(incrementalWithOptions:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder\/init(incrementalwithoptions:)"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder":{"role":"symbol","title":"SDImageWebPCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageWebPCoder"}],"abstract":[{"type":"text","text":"Built in coder that supports WebP and animated WebP"}],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageWebPCoder"}],"url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/SH"},"doc://org.SDWebImage.SDWebImageWebPCoder/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/SQ"},"doc://org.SDWebImage.SDWebImageWebPCoder/objc(pl)SDAnimatedImageProvider":{"type":"unresolvable","title":"SDWebImage.SDAnimatedImageProvider","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDAnimatedImageProvider"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder":{"role":"collection","title":"SDWebImageWebPCoder","abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/objc(cs)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObject","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(cs)NSObject"},"doc://org.SDWebImage.SDWebImageWebPCoder/documentation/SDWebImageWebPCoder/SDImageWebPCoder/init(animatedImageData:options:)":{"role":"symbol","title":"init(animatedImageData:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"animatedImageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/init(animatedImageData:options:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimagewebpcoder\/sdimagewebpcoder\/init(animatedimagedata:options:)"},"doc://org.SDWebImage.SDWebImageWebPCoder/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/s7CVarArgP"},"doc://org.SDWebImage.SDWebImageWebPCoder/objc(pl)SDProgressiveImageCoder":{"type":"unresolvable","title":"SDWebImage.SDProgressiveImageCoder","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDProgressiveImageCoder"},"doc://org.SDWebImage.SDWebImageWebPCoder/objc(pl)SDImageCoder":{"type":"unresolvable","title":"SDWebImage.SDImageCoder","identifier":"doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/objc(pl)SDImageCoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDImageWebPCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageWebPCoder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageWebPCoder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/org.SDWebImage.SDWebImageWebPCoder\/documentation\/SDWebImageWebPCoder\/SDImageWebPCoder\/shared"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageWebPCoder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder~1shared\/title","value":"sharedCoder"},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder~1shared\/fragments","value":[{"kind":"identifier","text":"sharedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder\/title","value":"SDImageWebPCoder"},{"op":"replace","path":"\/references\/doc:~1~1org.SDWebImage.SDWebImageWebPCoder~1documentation~1SDWebImageWebPCoder~1SDImageWebPCoder\/fragments","value":[{"kind":"identifier","text":"SDImageWebPCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}