{"abstract":[{"type":"text","text":"Inherited from "},{"code":"Equatable.!=(_:_:)","type":"codeVoice"},{"text":".","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"text":"lhs","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"rhs","kind":"internalParam"},{"kind":"text","text":": "},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/!=(_:_:)"]}],"sections":[],"kind":"symbol","metadata":{"role":"symbol","title":"!=(_:_:)","extendedModule":"Swift","externalID":"s:SQsE2neoiySbx_xtFZ::SYNTHESIZED::c:@E@SDGraphicsImageRendererFormatRange","roleHeading":"Operator","modules":[{"name":"SDWebImage","relatedModules":["Swift"]}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"kind":"text","text":" "},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"symbolKind":"op"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/!=(_:_:)"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/Equatable-Implementations"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange","abstract":[{"type":"text","text":"Constants that specify the color range of the image renderer context."}],"title":"SDGraphicsImageRendererFormatRange","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","kind":"article","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/equatable-implementations","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/Equatable-Implementations","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/!=(_:_:)":{"type":"topic","abstract":[],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/!=(_:_:)","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/!=(_:_:)","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"!=","kind":"identifier"},{"text":" ","kind":"text"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"text":", ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"!=(_:_:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"SDGraphicsImageRendererFormatRange","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments","value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/navigatorTitle","op":"replace","value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]}]}]}