{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"extended"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/extended"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/extended"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/extended","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The image renderer context supports wide color."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"extended"}],"title":"SDGraphicsImageRendererFormatRange.extended","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@E@SDGraphicsImageRendererFormatRange@SDGraphicsImageRendererFormatRangeExtended","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/extended":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange.extended","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"extended"}],"abstract":[{"type":"text","text":"The image renderer context supports wide color."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/extended","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/extended"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"abstract":[{"type":"text","text":"Constants that specify the color range of the image renderer context."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsImageRendererFormatRangeExtended"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1extended\/title","value":"SDGraphicsImageRendererFormatRangeExtended"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1extended\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title","value":"SDGraphicsImageRendererFormatRange"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}