{"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/hash(into:)"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/hash(into:)"],"traits":[{"interfaceLanguage":"swift"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/RawRepresentable-Implementations"]]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"hash","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"into"},{"kind":"text","text":" "},{"kind":"internalParam","text":"hasher"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"s:s6HasherV","kind":"typeIdentifier","text":"Hasher"},{"kind":"text","text":")"}]}],"kind":"declarations"}],"abstract":[{"text":"Inherited from ","type":"text"},{"type":"codeVoice","code":"RawRepresentable.hash(into:)"},{"text":".","type":"text"}],"kind":"symbol","metadata":{"roleHeading":"Instance Method","role":"symbol","modules":[{"relatedModules":["Swift"],"name":"SDWebImage"}],"externalID":"s:SYsSHRzSH8RawValueSYRpzrlE4hash4intoys6HasherVz_tF::SYNTHESIZED::c:@E@SDGraphicsImageRendererFormatRange","symbolKind":"method","conformance":{"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"type":"text","text":"Conforms when"}],"constraints":[{"code":"Self","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"RawValue","type":"codeVoice"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}]},"title":"hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"inout","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"extendedModule":"Swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/hash(into:)":{"title":"hash(into:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/hash(into:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"hash"},{"text":"(","kind":"text"},{"text":"into","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"inout"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"Hasher","preciseIdentifier":"s:s6HasherV"},{"text":")","kind":"text"}],"conformance":{"constraints":[{"type":"codeVoice","code":"Self"},{"text":" conforms to ","type":"text"},{"type":"codeVoice","code":"Hashable"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"RawValue"},{"type":"text","text":" conforms to "},{"code":"Hashable","type":"codeVoice"},{"type":"text","text":"."}],"availabilityPrefix":[{"type":"text","text":"Available when"}],"conformancePrefix":[{"text":"Conforms when","type":"text"}]},"abstract":[],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/hash(into:)","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","kind":"article","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/RawRepresentable-Implementations","role":"collectionGroup","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/rawrepresentable-implementations","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange","abstract":[{"type":"text","text":"Constants that specify the color range of the image renderer context."}],"title":"SDGraphicsImageRendererFormatRange","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"SDGraphicsImageRendererFormatRange","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title"},{"value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/navigatorTitle","value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}