{"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange"]]},"sections":[],"abstract":[{"text":"The image renderer context doesn’t support extended colors.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/standard"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/standard"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}]}]}],"metadata":{"modules":[{"name":"SDWebImage"}],"roleHeading":"Case","role":"symbol","symbolKind":"case","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeStandard"}],"title":"SDGraphicsImageRendererFormatRange.standard","externalID":"c:@E@SDGraphicsImageRendererFormatRange@SDGraphicsImageRendererFormatRangeStandard"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/standard","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/standard":{"role":"symbol","type":"topic","kind":"symbol","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"standard","kind":"identifier"}],"navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRangeStandard","kind":"identifier"}],"title":"SDGraphicsImageRendererFormatRange.standard","abstract":[{"text":"The image renderer context doesn’t support extended colors.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/standard","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/standard"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange","abstract":[{"type":"text","text":"Constants that specify the color range of the image renderer context."}],"title":"SDGraphicsImageRendererFormatRange","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsImageRendererFormatRangeStandard"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeStandard"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"SDGraphicsImageRendererFormatRangeStandard","kind":"identifier"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1standard\/title","value":"SDGraphicsImageRendererFormatRangeStandard","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1standard\/fragments","value":[{"text":"SDGraphicsImageRendererFormatRangeStandard","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title","value":"SDGraphicsImageRendererFormatRange"},{"value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments"},{"op":"replace","value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}