{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/unspecified","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange"]]},"kind":"symbol","sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"unspecified","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The image renderer context doesn’t specify a color range.","type":"text"}],"metadata":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange.unspecified","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRangeUnspecified","kind":"identifier"}],"externalID":"c:@E@SDGraphicsImageRendererFormatRange@SDGraphicsImageRendererFormatRangeUnspecified","roleHeading":"Case","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"}],"symbolKind":"case"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/unspecified"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/unspecified"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange","abstract":[{"type":"text","text":"Constants that specify the color range of the image renderer context."}],"title":"SDGraphicsImageRendererFormatRange","type":"topic","kind":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/unspecified":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/unspecified","abstract":[{"text":"The image renderer context doesn’t specify a color range.","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"unspecified","kind":"identifier"}],"title":"SDGraphicsImageRendererFormatRange.unspecified","navigatorTitle":[{"text":"SDGraphicsImageRendererFormatRangeUnspecified","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/unspecified"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsImageRendererFormatRangeUnspecified"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDGraphicsImageRendererFormatRangeUnspecified","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"SDGraphicsImageRendererFormatRangeUnspecified","kind":"identifier"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title","value":"SDGraphicsImageRendererFormatRange","op":"replace"},{"value":[{"text":"SDGraphicsImageRendererFormatRange","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1unspecified\/title","value":"SDGraphicsImageRendererFormatRangeUnspecified","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1unspecified\/fragments","value":[{"text":"SDGraphicsImageRendererFormatRangeUnspecified","kind":"identifier"}],"op":"replace"}]}]}