{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder\/defaultloopcount"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder\/defaultloopcount"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLoopCount"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","content":[{"inlineContent":[{"type":"text","text":"Subclass override."}],"type":"paragraph"}],"name":"Note","style":"note"}]}],"metadata":{"roleHeading":"Type Property","symbolKind":"property","title":"defaultLoopCount","role":"symbol","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"defaultLoopCount","kind":"identifier"}],"externalID":"c:objc(cs)SDImageIOAnimatedCoder(cpy)defaultLoopCount","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultLoopCount"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/defaultLoopCount","interfaceLanguage":"swift"},"abstract":[{"text":"The default loop count when there are no any loop count information inside image container metadata.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For example, for GIF format, the standard use 1 (play once). For APNG format, the standard use 0 (infinity loop)."}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/defaultLoopCount":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/defaultLoopCount","url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/defaultloopcount","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultLoopCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"type":"topic","kind":"symbol","abstract":[{"text":"The default loop count when there are no any loop count information inside image container metadata.","type":"text"},{"type":"text","text":" "},{"text":"For example, for GIF format, the standard use 1 (play once). For APNG format, the standard use 0 (infinity loop).","type":"text"}],"title":"defaultLoopCount","navigatorTitle":[{"kind":"identifier","text":"defaultLoopCount"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder","type":"topic","title":"SDImageIOAnimatedCoder","kind":"symbol","abstract":[{"text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"role":"symbol","navigatorTitle":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"op":"replace","value":"defaultLoopCount","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"defaultLoopCount","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultLoopCount"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"defaultLoopCount","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1defaultLoopCount\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1defaultLoopCount\/fragments","value":[{"kind":"identifier","text":"defaultLoopCount"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title","op":"replace","value":"SDImageIOAnimatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/navigatorTitle","op":"replace","value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}