{"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder\/init(incrementalwithoptions:)"],"traits":[{"interfaceLanguage":"swift"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/init(incrementalWithOptions:)","interfaceLanguage":"swift"},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"incrementalWithOptions","kind":"externalParam"},{"kind":"text","text":" "},{"text":"options","kind":"internalParam"},{"text":": [","kind":"text"},{"text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]? = nil)","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"SDImageIOAnimatedCoder.init(incrementalWithOptions:)","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"]]},"metadata":{"externalID":"c:objc(pl)SDProgressiveImageCoder(im)initIncrementalWithOptions:::SYNTHESIZED::c:objc(cs)SDImageIOAnimatedCoder","title":"init(incrementalWithOptions:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"incrementalWithOptions","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?)","kind":"text"}],"symbolKind":"init","modules":[{"name":"SDWebImage"}],"roleHeading":"Initializer","role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder","type":"topic","title":"SDImageIOAnimatedCoder","kind":"symbol","abstract":[{"text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"role":"symbol","navigatorTitle":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/init(incrementalWithOptions:)":{"kind":"symbol","role":"symbol","type":"topic","title":"init(incrementalWithOptions:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/init(incrementalWithOptions:)","url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/init(incrementalwithoptions:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"incrementalWithOptions","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?)"}]}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title","op":"replace","value":"SDImageIOAnimatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},{"value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/navigatorTitle"},{"value":"SDImageCoderOption","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title"},{"value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}