{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopCountProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder\/loopcountproperty"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder\/loopcountproperty"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/loopCountProperty","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The image loop count property key used in Image\/IO API. Such as "},{"type":"codeVoice","code":"kCGImagePropertyGIFLoopCount"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopCountProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"loopCountProperty","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageIOAnimatedCoder(cpy)loopCountProperty","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"loopCountProperty"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/loopCountProperty":{"role":"symbol","title":"loopCountProperty","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"loopCountProperty"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"abstract":[{"type":"text","text":"The image loop count property key used in Image\/IO API. Such as "},{"type":"codeVoice","code":"kCGImagePropertyGIFLoopCount"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/loopCountProperty","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loopCountProperty"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/loopcountproperty"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"role":"symbol","title":"SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"abstract":[{"type":"text","text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class."},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"loopCountProperty"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"loopCountProperty"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"atomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"loopCountProperty"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1loopCountProperty\/title","value":"loopCountProperty"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1loopCountProperty\/fragments","value":[{"kind":"identifier","text":"loopCountProperty"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title","value":"SDImageIOAnimatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}