{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"required":true,"roleHeading":"Instance Method","role":"symbol","platforms":[{"introducedAt":"8.0","name":"iOS","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0"},{"introducedAt":"8.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false}],"symbolKind":"method","navigatorTitle":[{"text":"canDecodeFromData:","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDecode"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"title":"canDecode(from:)","externalID":"c:objc(pl)SDImageCoder(im)canDecodeFromData:"},"abstract":[{"text":"Returns YES if this coder can decode some data. Otherwise, the data should be passed to another coder.","type":"text"}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canDecode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"data"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image data so we can look at it"}]}],"name":"data"}]},{"content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"YES if this coder can decode the data, NO otherwise"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoder\/candecode(from:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoder\/candecode(from:)"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canDecode(from:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"type":"topic","title":"SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder","navigatorTitle":[{"text":"SDImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the image coder protocol to provide custom image decoding\/encoding.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods are all required to implement."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/canDecode(from:)":{"url":"\/documentation\/sdwebimage\/sdimagecoder\/candecode(from:)","required":true,"navigatorTitle":[{"text":"canDecodeFromData:","kind":"identifier"}],"title":"canDecode(from:)","abstract":[{"text":"Returns YES if this coder can decode some data. Otherwise, the data should be passed to another coder.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canDecode(from:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"canDecode","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","op":"replace","value":"canDecodeFromData:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"canDecodeFromData:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"canDecodeFromData:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSData","kind":"typeIdentifier","text":"NSData"},{"text":" *) ","kind":"text"},{"text":"data","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The image data so we can look at it","type":"text"}]}],"name":"data"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"type":"text","text":"YES if this coder can decode the data, NO otherwise"}]}]}},{"value":"SDImageCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","op":"replace"},{"value":[{"text":"SDImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/navigatorTitle"},{"op":"replace","value":"canDecodeFromData:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canDecode(from:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canDecode(from:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"canDecodeFromData:","kind":"identifier"}]}]}]}