{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canEncode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":" "},{"kind":"internalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"static const SDImageFormat SDImageFormatHEIF = 10;"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoder\/canencode(to:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoder\/canencode(to:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canEncode(to:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Returns YES if this coder can encode some image. Otherwise, it should be passed to another coder."},{"type":"text","text":" "},{"type":"text","text":"For custom coder which introduce new image format, you’d better define a new "},{"type":"codeVoice","code":"SDImageFormat"},{"type":"text","text":" using like this. If you’re creating public coder plugin for new image format, also update "},{"type":"codeVoice","code":"https:\/\/github.com\/rs\/SDWebImage\/wiki\/Coder-Plugin-List"},{"type":"text","text":" to avoid same value been defined twice."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"canEncodeToFormat:"}],"role":"symbol","title":"canEncode(to:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canEncode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)SDImageCoder(im)canEncodeToFormat:","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"role":"symbol","title":"SDImageFormat","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageFormat"}],"abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"type":"text","text":" "},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}],"url":"\/documentation\/sdwebimage\/sdimageformat"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/canEncode(to:)":{"navigatorTitle":[{"kind":"identifier","text":"canEncodeToFormat:"}],"role":"symbol","title":"canEncode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canEncode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns YES if this coder can encode some image. Otherwise, it should be passed to another coder."},{"type":"text","text":" "},{"type":"text","text":"For custom coder which introduce new image format, you’d better define a new "},{"type":"codeVoice","code":"SDImageFormat"},{"type":"text","text":" using like this. If you’re creating public coder plugin for new image format, also update "},{"type":"codeVoice","code":"https:\/\/github.com\/rs\/SDWebImage\/wiki\/Coder-Plugin-List"},{"type":"text","text":" to avoid same value been defined twice."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canEncode(to:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoder\/canencode(to:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"role":"symbol","title":"SDImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom image decoding\/encoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canEncodeToFormat:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canEncodeToFormat:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canEncodeToFormat:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat"},{"kind":"text","text":")"},{"kind":"internalParam","text":"format"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title","value":"SDImageFormat"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments","value":[{"kind":"identifier","text":"SDImageFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canEncode(to:)\/title","value":"canEncodeToFormat:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canEncode(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canEncodeToFormat:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments","value":[{"kind":"identifier","text":"SDImageCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}