{"sections":[],"metadata":{"modules":[{"name":"SDWebImage"}],"symbolKind":"method","navigatorTitle":[{"text":"encodedDataWithFrames:loopCount:format:options:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodedData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageFrame","text":"SDImageFrame"},{"kind":"text","text":"], "},{"text":"loopCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?"}],"title":"encodedData(with:loopCount:format:options:)","roleHeading":"Instance Method","platforms":[{"introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"beta":false,"unavailable":false,"deprecated":false,"name":"iPadOS","introducedAt":"8.0"},{"name":"Mac Catalyst","beta":false,"introducedAt":"8.0","unavailable":false,"deprecated":false}],"role":"symbol","externalID":"c:objc(pl)SDImageCoder(im)encodedDataWithFrames:loopCount:format:options:"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder"]]},"abstract":[{"text":"Encode the animated image frames to image data.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/encodedData(with:loopCount:format:options:)"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodedData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"frames","kind":"internalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageFrame","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame","kind":"typeIdentifier","text":"SDImageFrame"},{"kind":"text","text":"], "},{"text":"loopCount","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDImageFormat","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]? = nil) -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}]}]},{"parameters":[{"name":"frames","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The animated image frames to be encoded, should be at least 1 element, or it will fallback to static image encode."}]}]},{"name":"loopCount","content":[{"type":"paragraph","inlineContent":[{"text":"The final animated image loop count. 0 means infinity loop. This config ignore each frame’s ","type":"text"},{"type":"codeVoice","code":"sd_imageLoopCount"}]}]},{"name":"format","content":[{"inlineContent":[{"text":"The image format to encode, you should note ","type":"text"},{"code":"SDImageFormatUndefined","type":"codeVoice"},{"type":"text","text":" format is also  possible"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A dictionary containing any encoding options. Pass @{SDImageCoderEncodeCompressionQuality: @(1)} to specify compression quality."}],"type":"paragraph"}],"name":"options"}],"kind":"parameters"},{"content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"The encoded image data"}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecoder\/encodeddata(with:loopcount:format:options:)"]},{"paths":["\/documentation\/sdwebimage\/sdimagecoder\/encodeddata(with:loopcount:format:options:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"type":"topic","title":"SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder","navigatorTitle":[{"text":"SDImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the image coder protocol to provide custom image decoding\/encoding.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods are all required to implement."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame","title":"SDImageFrame","navigatorTitle":[{"text":"SDImageFrame","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageFrame","kind":"identifier"}],"abstract":[{"text":"This class is used for creating animated images via ","type":"text"},{"code":"animatedImageWithFrames","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"SDImageCoderHelper","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdimageframe","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOptions":{"role":"symbol","abstract":[],"fragments":[{"kind":"identifier","text":"SDImageCoderOptions"}],"title":"SDImageCoderOptions","url":"\/documentation\/sdwebimage\/sdimagecoderoptions","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/encodedData(with:loopCount:format:options:)":{"role":"symbol","navigatorTitle":[{"text":"encodedDataWithFrames:loopCount:format:options:","kind":"identifier"}],"abstract":[{"text":"Encode the animated image frames to image data.","type":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoder\/encodeddata(with:loopcount:format:options:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/encodedData(with:loopCount:format:options:)","title":"encodedData(with:loopCount:format:options:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"encodedData","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageFrame","preciseIdentifier":"c:objc(cs)SDImageFrame"},{"text":"], ","kind":"text"},{"kind":"externalParam","text":"loopCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"path":"\/metadata\/title","value":"encodedDataWithFrames:loopCount:format:options:","op":"replace"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encodedDataWithFrames:loopCount:format:options:"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"preciseIdentifier":"c:objc(cs)NSData","text":"NSData","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"encodedDataWithFrames:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSArray","text":"NSArray<SDImageFrame *>","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"frames","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loopCount:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"loopCount","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"format:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","kind":"typeIdentifier","text":"SDImageFormat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat"},{"text":") ","kind":"text"},{"text":"format","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOptions","kind":"typeIdentifier","text":"SDImageCoderOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOptions"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"options"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"frames","content":[{"type":"paragraph","inlineContent":[{"text":"The animated image frames to be encoded, should be at least 1 element, or it will fallback to static image encode.","type":"text"}]}]},{"name":"loopCount","content":[{"inlineContent":[{"type":"text","text":"The final animated image loop count. 0 means infinity loop. This config ignore each frame’s "},{"code":"sd_imageLoopCount","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image format to encode, you should note "},{"type":"codeVoice","code":"SDImageFormatUndefined"},{"text":" format is also  possible","type":"text"}]}],"name":"format"},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A dictionary containing any encoding options. Pass @{SDImageCoderEncodeCompressionQuality: @(1)} to specify compression quality."}],"type":"paragraph"}]}],"kind":"parameters"}},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"type":"heading","text":"Return Value","anchor":"return-value","level":2},{"inlineContent":[{"type":"text","text":"The encoded image data"}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/navigatorTitle","op":"replace","value":[{"text":"SDImageCoder","kind":"identifier"}]},{"op":"replace","value":"SDImageFrame","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/fragments","value":[{"text":"SDImageFrame","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/navigatorTitle","op":"replace","value":[{"text":"SDImageFrame","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title","value":"SDImageFormat","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageFormat"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle","value":[{"text":"SDImageFormat","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1encodedData(with:loopCount:format:options:)\/title","value":"encodedDataWithFrames:loopCount:format:options:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1encodedData(with:loopCount:format:options:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"encodedDataWithFrames:loopCount:format:options:"}],"op":"replace"}]}]}