{"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/acceptablecontenttypes"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/acceptablecontenttypes"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"acceptableContentTypes","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sh","text":"Set"},{"text":"<","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":">? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableContentTypes"},"abstract":[{"type":"text","text":"Set the acceptable HTTP Response content type. The content type beyond the set will mark the download operation failed."},{"text":" ","type":"text"},{"type":"text","text":"For example, if we config [“image\/png”] but server response is “application\/json”, the download will fail with error code "},{"code":"SDWebImageErrorInvalidDownloadContentType","type":"codeVoice"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Normally you don’t need this for image format detection because we use image’s data file signature magic bytes: https:\/\/en.wikipedia.org\/wiki\/List_of_file_signatures"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil. Nil means no validation at all."}],"metadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"acceptableContentTypes"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDWebImageDownloaderConfig(py)acceptableContentTypes","symbolKind":"property","roleHeading":"Instance Property","title":"acceptableContentTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableContentTypes"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":">?","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/acceptableContentTypes":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/acceptablecontenttypes","title":"acceptableContentTypes","navigatorTitle":[{"text":"acceptableContentTypes","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableContentTypes","abstract":[{"text":"Set the acceptable HTTP Response content type. The content type beyond the set will mark the download operation failed.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For example, if we config [“image\/png”] but server response is “application\/json”, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadContentType"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Normally you don’t need this for image format detection because we use image’s data file signature magic bytes: https:\/\/en.wikipedia.org\/wiki\/List_of_file_signatures"},{"type":"text","text":" "},{"text":"Defaults to nil. Nil means no validation at all.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"acceptableContentTypes","kind":"identifier"},{"kind":"text","text":": "},{"text":"Set","preciseIdentifier":"s:Sh","kind":"typeIdentifier"},{"text":"<","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":">?"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"navigatorTitle":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","abstract":[{"text":"The class contains all the config for image downloader","type":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"kind":"symbol","title":"SDWebImageDownloaderConfig"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"acceptableContentTypes","path":"\/metadata\/title","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"acceptableContentTypes","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:Q$objc(cs)NSSet","kind":"typeIdentifier","text":"NSSet<NSString *>"},{"kind":"text","text":" * "},{"kind":"identifier","text":"acceptableContentTypes"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"acceptableContentTypes","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1acceptableContentTypes\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1acceptableContentTypes\/fragments","op":"replace","value":[{"text":"acceptableContentTypes","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title","op":"replace","value":"SDWebImageDownloaderConfig"},{"value":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}