{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxConcurrentDownloads","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Int","preciseIdentifier":"s:Si","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/maxconcurrentdownloads"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/maxconcurrentdownloads"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"]]},"metadata":{"role":"symbol","title":"maxConcurrentDownloads","externalID":"c:objc(cs)SDWebImageDownloaderConfig(py)maxConcurrentDownloads","symbolKind":"property","navigatorTitle":[{"text":"maxConcurrentDownloads","kind":"identifier"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloads"},{"text":": ","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"}],"modules":[{"name":"SDWebImage"}]},"abstract":[{"text":"The maximum number of concurrent downloads.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to 6."}],"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/maxConcurrentDownloads","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"navigatorTitle":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","abstract":[{"text":"The class contains all the config for image downloader","type":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"kind":"symbol","title":"SDWebImageDownloaderConfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/maxConcurrentDownloads":{"type":"topic","title":"maxConcurrentDownloads","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/maxConcurrentDownloads","abstract":[{"type":"text","text":"The maximum number of concurrent downloads."},{"text":" ","type":"text"},{"text":"Defaults to 6.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/maxconcurrentdownloads","kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxConcurrentDownloads"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Si","text":"Int"}],"navigatorTitle":[{"kind":"identifier","text":"maxConcurrentDownloads"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","value":"maxConcurrentDownloads","op":"replace"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"maxConcurrentDownloads","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"},{"text":" ","kind":"text"},{"kind":"identifier","text":"maxConcurrentDownloads"},{"kind":"text","text":";"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title","value":"SDWebImageDownloaderConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}]},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1maxConcurrentDownloads\/title","value":"maxConcurrentDownloads"},{"op":"replace","value":[{"text":"maxConcurrentDownloads","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1maxConcurrentDownloads\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}