{"schemaVersion":{"major":0,"patch":0,"minor":3},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/minimumProgressInterval","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumProgressInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"externalID":"c:objc(cs)SDWebImageDownloaderConfig(py)minimumProgressInterval","navigatorTitle":[{"text":"minimumProgressInterval","kind":"identifier"}],"title":"minimumProgressInterval","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","role":"symbol"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/minimumprogressinterval"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/minimumprogressinterval"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"minimumProgressInterval","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","text":"Double","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"anchor":"discussion","type":"heading","text":"Discussion","level":2},{"name":"Note","content":[{"inlineContent":[{"text":"If you’re using progressive decoding feature, this will also effect the image refresh rate.","type":"text"}],"type":"paragraph"}],"style":"note","type":"aside"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This value may enhance the performance if you don’t want progress callback too frequently."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 0, which means each time we receive the new data from URLSession, we callback the progressBlock immediately."}]}],"name":"Note","type":"aside","style":"note"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"]]},"abstract":[{"text":"The minimum interval about progress percent during network downloading. Which means the next progress callback and current progress callback’s progress percent difference should be larger or equal to this value. However, the final finish download progress callback does not get effected.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The value should be 0.0-1.0."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"navigatorTitle":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","abstract":[{"text":"The class contains all the config for image downloader","type":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"kind":"symbol","title":"SDWebImageDownloaderConfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/minimumProgressInterval":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/minimumprogressinterval","title":"minimumProgressInterval","navigatorTitle":[{"text":"minimumProgressInterval","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/minimumProgressInterval","abstract":[{"text":"The minimum interval about progress percent during network downloading. Which means the next progress callback and current progress callback’s progress percent difference should be larger or equal to this value. However, the final finish download progress callback does not get effected.","type":"text"},{"type":"text","text":" "},{"text":"The value should be 0.0-1.0.","type":"text"}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"minimumProgressInterval","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"minimumProgressInterval"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"minimumProgressInterval","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"text":"double","kind":"typeIdentifier","preciseIdentifier":"c:d"},{"text":" ","kind":"text"},{"kind":"identifier","text":"minimumProgressInterval"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title","op":"replace","value":"SDWebImageDownloaderConfig"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}]},{"value":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1minimumProgressInterval\/title","value":"minimumProgressInterval","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1minimumProgressInterval\/fragments","value":[{"text":"minimumProgressInterval","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}