{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operationClass","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s8AnyClassa","text":"AnyClass","kind":"typeIdentifier"},{"text":"? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"Passing "},{"type":"codeVoice","code":"NSOperation<SDWebImageDownloaderOperation>"},{"type":"text","text":" to set as default. Passing "},{"code":"nil","type":"codeVoice"},{"type":"text","text":" will revert to "},{"code":"SDWebImageDownloaderOperation","type":"codeVoice"},{"type":"text","text":"."}],"type":"paragraph"}]}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/operationClass","interfaceLanguage":"swift"},"abstract":[{"text":"Gets\/Sets a subclass of ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"},{"text":" as the default","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"NSOperation"},{"type":"text","text":" to be used each time SDWebImage constructs a request"},{"text":" ","type":"text"},{"type":"text","text":"operation to download an image."},{"text":" ","type":"text"},{"text":"Defaults to nil.","type":"text"}],"metadata":{"navigatorTitle":[{"text":"operationClass","kind":"identifier"}],"symbolKind":"property","title":"operationClass","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"operationClass","kind":"identifier"},{"kind":"text","text":": "},{"text":"AnyClass","preciseIdentifier":"s:s8AnyClassa","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDWebImageDownloaderConfig(py)operationClass","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/operationclass"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/operationclass"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"navigatorTitle":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","abstract":[{"text":"The class contains all the config for image downloader","type":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"kind":"symbol","title":"SDWebImageDownloaderConfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/operationClass":{"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/operationClass","navigatorTitle":[{"kind":"identifier","text":"operationClass"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"operationClass","kind":"identifier"},{"text":": ","kind":"text"},{"text":"AnyClass","kind":"typeIdentifier","preciseIdentifier":"s:s8AnyClassa"},{"text":"?","kind":"text"}],"title":"operationClass","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/operationclass","abstract":[{"text":"Gets\/Sets a subclass of ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"},{"type":"text","text":" as the default"},{"type":"text","text":" "},{"type":"codeVoice","code":"NSOperation"},{"text":" to be used each time SDWebImage constructs a request","type":"text"},{"type":"text","text":" "},{"text":"operation to download an image.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"operationClass"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"operationClass"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"assign"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:*QO","text":"Class"},{"text":" ","kind":"text"},{"text":"operationClass","kind":"identifier"},{"text":";","kind":"text"}]}]}},{"value":"SDWebImageDownloaderConfig","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/navigatorTitle","value":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1operationClass\/title","value":"operationClass","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1operationClass\/fragments","value":[{"kind":"identifier","text":"operationClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}