{"metadata":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","symbolKind":"property","title":"sessionConfiguration","roleHeading":"Instance Property","externalID":"c:objc(cs)SDWebImageDownloaderConfig(py)sessionConfiguration","navigatorTitle":[{"text":"sessionConfiguration","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/sessionconfiguration"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/sessionconfiguration"]}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/sessionConfiguration","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"The custom session configuration in use by NSURLSession. If you don’t provide one, we will use "},{"type":"codeVoice","code":"defaultSessionConfiguration"},{"type":"text","text":" instead."},{"text":" ","type":"text"},{"text":"Defatuls to nil.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"sessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},{"content":[{"type":"heading","level":2,"anchor":"discussion","text":"Discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"This property does not support dynamic changes, means it’s immutable after the downloader instance initialized.","type":"text"}]}],"name":"Note","style":"note"}],"kind":"content"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/sessionConfiguration":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/sessionconfiguration","title":"sessionConfiguration","navigatorTitle":[{"kind":"identifier","text":"sessionConfiguration"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/sessionConfiguration","abstract":[{"text":"The custom session configuration in use by NSURLSession. If you don’t provide one, we will use ","type":"text"},{"type":"codeVoice","code":"defaultSessionConfiguration"},{"text":" instead.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defatuls to nil."}],"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sessionConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"},{"text":"?","kind":"text"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"navigatorTitle":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","abstract":[{"text":"The class contains all the config for image downloader","type":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"kind":"symbol","title":"SDWebImageDownloaderConfig"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"path":"\/metadata\/title","value":"sessionConfiguration","op":"replace"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"sessionConfiguration","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"NSURLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"},{"kind":"text","text":" * "},{"text":"sessionConfiguration","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1sessionConfiguration\/title","value":"sessionConfiguration"},{"value":[{"kind":"identifier","text":"sessionConfiguration"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1sessionConfiguration\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title","value":"SDWebImageDownloaderConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments","value":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/navigatorTitle"}]}]}