{"abstract":[{"type":"text","text":"Returns the frames’s duration from a specified index."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageduration(at:)"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageduration(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageDuration(at:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider"]]},"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animatedImageDuration","kind":"identifier"},{"kind":"text","text":"("},{"text":"at","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"index","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"index","content":[{"type":"paragraph","inlineContent":[{"text":"Frame index (zero based).","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"type":"heading","anchor":"return-value","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"Frame’s duration"}],"type":"paragraph"}]},{"kind":"content","content":[{"anchor":"discussion","type":"heading","level":2,"text":"Discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"The index maybe randomly if one image was set to different imageViews, keep it re-entrant. (It’s recommend to store the durations into array because it’s not memory-consuming)","type":"text"}]}],"name":"Note","style":"note","type":"aside"}]}],"metadata":{"externalID":"c:objc(pl)SDAnimatedImageProvider(im)animatedImageDurationAtIndex:","symbolKind":"method","role":"symbol","required":true,"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animatedImageDuration","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"navigatorTitle":[{"text":"animatedImageDurationAtIndex:","kind":"identifier"}],"title":"animatedImageDuration(at:)","modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageDuration(at:)":{"role":"symbol","kind":"symbol","title":"animatedImageDuration(at:)","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageduration(at:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageDuration(at:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"animatedImageDurationAtIndex:"}],"type":"topic","abstract":[{"type":"text","text":"Returns the frames’s duration from a specified index."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animatedImageDuration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"type":"topic","abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"code":"SDAnimatedImageCoder","type":"codeVoice"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"title":"SDAnimatedImageProvider"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"path":"\/metadata\/title","value":"animatedImageDurationAtIndex:","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"text":"animatedImageDurationAtIndex:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"NSTimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") "},{"text":"animatedImageDurationAtIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"index","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"index","content":[{"inlineContent":[{"text":"Frame index (zero based).","type":"text"}],"type":"paragraph"}]}]},"op":"replace"},{"value":{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Frame’s duration"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageDuration(at:)\/title","op":"replace","value":"animatedImageDurationAtIndex:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"animatedImageDurationAtIndex:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageDuration(at:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","value":"SDAnimatedImageProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}]},{"value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/navigatorTitle"}]}]}