{"abstract":[{"type":"text","text":"Returns the frame image from a specified index."}],"metadata":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"animatedImageFrame","kind":"identifier"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"modules":[{"name":"SDWebImage"}],"platforms":[{"introducedAt":"2.0","unavailable":false,"deprecated":false,"name":"iOS","beta":false},{"beta":false,"introducedAt":"2.0","deprecated":false,"name":"iPadOS","unavailable":false},{"deprecated":false,"introducedAt":"2.0","unavailable":false,"name":"Mac Catalyst","beta":false}],"roleHeading":"Instance Method","required":true,"externalID":"c:objc(pl)SDAnimatedImageProvider(im)animatedImageFrameAtIndex:","symbolKind":"method","title":"animatedImageFrame(at:)","navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameAtIndex:"}]},"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageframe(at:)"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageframe(at:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrame(at:)","interfaceLanguage":"swift"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animatedImageFrame"},{"kind":"text","text":"("},{"kind":"externalParam","text":"at"},{"kind":"text","text":" "},{"kind":"internalParam","text":"index"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"index","content":[{"inlineContent":[{"type":"text","text":"Frame index (zero based)."}],"type":"paragraph"}]}]},{"content":[{"anchor":"return-value","text":"Return Value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"Frame’s image"}],"type":"paragraph"}],"kind":"content"},{"kind":"content","content":[{"level":2,"anchor":"discussion","text":"Discussion","type":"heading"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"The index maybe randomly if one image was set to different imageViews, keep it re-entrant. (It’s not recommend to store the images into array because it’s memory consuming)"}],"type":"paragraph"}],"style":"note"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"type":"topic","abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"code":"SDAnimatedImageCoder","type":"codeVoice"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"title":"SDAnimatedImageProvider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageFrame(at:)":{"navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameAtIndex:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrame(at:)","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageframe(at:)","role":"symbol","abstract":[{"type":"text","text":"Returns the frame image from a specified index."}],"title":"animatedImageFrame(at:)","type":"topic","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animatedImageFrame"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"value":"animatedImageFrameAtIndex:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animatedImageFrameAtIndex:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":" *) "},{"text":"animatedImageFrameAtIndex:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"index"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame index (zero based)."}]}],"name":"index"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Frame’s image"}]}]}},{"value":"SDAnimatedImageProvider","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/navigatorTitle","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageFrame(at:)\/title","value":"animatedImageFrameAtIndex:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"animatedImageFrameAtIndex:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageFrame(at:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}