{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager\/loaders"]},{"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager\/loaders"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"loaders"},{"text":": [any ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader","text":"SDImageLoader"},{"kind":"text","text":"]? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}]}],"metadata":{"externalID":"c:objc(cs)SDImageLoadersManager(py)loaders","modules":[{"name":"SDWebImage"}],"symbolKind":"property","title":"loaders","navigatorTitle":[{"text":"loaders","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"loaders","kind":"identifier"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageLoader","kind":"typeIdentifier","text":"SDImageLoader"},{"kind":"text","text":"]?"}],"role":"symbol","roleHeading":"Instance Property"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/loaders","interfaceLanguage":"swift"},"abstract":[{"text":"All image loaders in manager. The loaders array is a priority queue, which means the later added loader will have the highest priority","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/loaders":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"loaders","kind":"identifier"},{"kind":"text","text":": [any "},{"text":"SDImageLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader"},{"text":"]?","kind":"text"}],"title":"loaders","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/loaders","navigatorTitle":[{"text":"loaders","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/loaders","abstract":[{"type":"text","text":"All image loaders in manager. The loaders array is a priority queue, which means the later added loader will have the highest priority"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoadersManager","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","title":"SDImageLoadersManager","navigatorTitle":[{"kind":"identifier","text":"SDImageLoadersManager"}],"kind":"symbol","abstract":[{"text":"A loaders manager to manage multiple loaders","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"loaders"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"loaders","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"copy","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSArray<id<SDImageLoader>>","kind":"typeIdentifier","preciseIdentifier":"c:Q$objc(cs)NSArray"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"loaders"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1loaders\/title","value":"loaders"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1loaders\/fragments","value":[{"text":"loaders","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDImageLoadersManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/fragments","value":[{"kind":"identifier","text":"SDImageLoadersManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/navigatorTitle","value":[{"text":"SDImageLoadersManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageLoader"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDImageLoader"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle"}]}]}