{"abstract":[{"type":"text","text":"Remove an image loader in the loaders array."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/removeLoader(_:)"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager"]]},"sections":[],"metadata":{"symbolKind":"method","title":"removeLoader(_:)","navigatorTitle":[{"text":"removeLoader:","kind":"identifier"}],"role":"symbol","roleHeading":"Instance Method","externalID":"c:objc(cs)SDImageLoadersManager(im)removeLoader:","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeLoader","kind":"identifier"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageLoader","kind":"typeIdentifier","text":"SDImageLoader"},{"text":")","kind":"text"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeLoader","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"loader"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageLoader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","text":"SDImageLoader","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Loader"}],"type":"paragraph"}],"name":"loader"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager\/removeloader(_:)"]},{"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager\/removeloader(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoadersManager","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","title":"SDImageLoadersManager","navigatorTitle":[{"kind":"identifier","text":"SDImageLoadersManager"}],"kind":"symbol","abstract":[{"text":"A loaders manager to manage multiple loaders","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/removeLoader(_:)":{"role":"symbol","navigatorTitle":[{"text":"removeLoader:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/removeLoader(_:)","type":"topic","title":"removeLoader(_:)","abstract":[{"type":"text","text":"Remove an image loader in the loaders array."}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/removeloader(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeLoader"},{"text":"(any ","kind":"text"},{"text":"SDImageLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader"},{"kind":"text","text":")"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"removeLoader:","path":"\/metadata\/title","op":"replace"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeLoader:","kind":"identifier"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"kind":"text","text":") "},{"kind":"identifier","text":"removeLoader:"},{"text":"(","kind":"text"},{"text":"id<SDImageLoader>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDImageLoader"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"loader"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"name":"loader","content":[{"inlineContent":[{"text":"Loader","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/title","value":"SDImageLoadersManager","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/fragments","value":[{"text":"SDImageLoadersManager","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageLoadersManager"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1removeLoader(_:)\/title","value":"removeLoader:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeLoader:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1removeLoader(_:)\/fragments","op":"replace"},{"value":"SDImageLoader","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"text":"SDImageLoader","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageLoader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}