{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager"]]},"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Returns the global shared loaders manager instance. By default we will set ["},{"type":"codeVoice","code":"SDWebImageDownloader.sharedDownloader"},{"type":"text","text":"] into the loaders array."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager\/shared"]},{"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageLoadersManager","text":"SDImageLoadersManager","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageLoadersManager","preciseIdentifier":"c:objc(cs)SDImageLoadersManager"}],"title":"shared","navigatorTitle":[{"kind":"identifier","text":"sharedManager"}],"externalID":"c:objc(cs)SDImageLoadersManager(cpy)sharedManager","modules":[{"name":"SDWebImage"}],"symbolKind":"property"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/shared","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/shared":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/shared","abstract":[{"type":"text","text":"Returns the global shared loaders manager instance. By default we will set ["},{"code":"SDWebImageDownloader.sharedDownloader","type":"codeVoice"},{"text":"] into the loaders array.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageLoadersManager","text":"SDImageLoadersManager","kind":"typeIdentifier"}],"title":"shared","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/shared"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoadersManager","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","title":"SDImageLoadersManager","navigatorTitle":[{"kind":"identifier","text":"SDImageLoadersManager"}],"kind":"symbol","abstract":[{"text":"A loaders manager to manage multiple loaders","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","value":"sharedManager","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"path":"\/metadata\/fragments","value":[{"text":"sharedManager","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"text":"SDImageLoadersManager","preciseIdentifier":"c:objc(cs)SDImageLoadersManager","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sharedManager"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"sharedManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1shared\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1shared\/fragments","value":[{"kind":"identifier","text":"sharedManager"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/title","op":"replace","value":"SDImageLoadersManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/fragments","value":[{"text":"SDImageLoadersManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/navigatorTitle","value":[{"text":"SDImageLoadersManager","kind":"identifier"}]}]}]}