{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageawebpcoder\/shared"]},{"paths":["\/documentation\/sdwebimage\/sdimageawebpcoder\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"modules":[{"name":"SDWebImage"}],"platforms":[{"unavailable":false,"beta":false,"introducedAt":"14.0","deprecated":false,"name":"iOS"},{"unavailable":false,"deprecated":false,"name":"iPadOS","beta":false,"introducedAt":"14.0"},{"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","unavailable":false,"beta":false}],"roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"text":": ","kind":"text"},{"text":"SDImageAWebPCoder","preciseIdentifier":"c:objc(cs)SDImageAWebPCoder","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"sharedCoder","kind":"identifier"}],"role":"symbol","externalID":"c:objc(cs)SDImageAWebPCoder(cpy)sharedCoder","symbolKind":"property","title":"shared"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder\/shared"},"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageAWebPCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","preciseIdentifier":"c:objc(cs)SDImageAWebPCoder"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder/shared":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageAWebPCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageAWebPCoder"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageawebpcoder\/shared","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder\/shared","title":"shared","type":"topic","abstract":[],"navigatorTitle":[{"text":"sharedCoder","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAWebPCoder","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"text":" ","type":"text"},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"url":"\/documentation\/sdwebimage\/sdimageawebpcoder","title":"SDImageAWebPCoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"value":"sharedCoder","op":"replace","path":"\/metadata\/title"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"sharedCoder","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"text":"SDImageAWebPCoder","preciseIdentifier":"c:objc(cs)SDImageAWebPCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"sharedCoder"},{"text":";","kind":"text"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder~1shared\/title","value":"sharedCoder","op":"replace"},{"value":[{"kind":"identifier","text":"sharedCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder~1shared\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/title","op":"replace","value":"SDImageAWebPCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageAWebPCoder"}]},{"value":[{"kind":"identifier","text":"SDImageAWebPCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/navigatorTitle","op":"replace"}]}]}