{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class\/config","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sddiskcache-swift.class\/config"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sddiskcache-swift.class\/config"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class"]]},"metadata":{"symbolKind":"property","roleHeading":"Instance Property","title":"config","externalID":"c:objc(cs)SDDiskCache(py)config","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"}],"navigatorTitle":[{"kind":"identifier","text":"config"}],"role":"symbol"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"Cache Config object - storing all kind of settings.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCache-swift.class/config":{"abstract":[{"type":"text","text":"Cache Config object - storing all kind of settings."}],"title":"config","url":"\/documentation\/sdwebimage\/sddiskcache-swift.class\/config","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class\/config","kind":"symbol","navigatorTitle":[{"text":"config","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCache-swift.class":{"abstract":[{"text":"The built-in disk cache.","type":"text"}],"title":"SDDiskCache","url":"\/documentation\/sdwebimage\/sddiskcache-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDDiskCache","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class","kind":"symbol","navigatorTitle":[{"text":"SDDiskCache","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"config"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"value":[{"text":"config","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"config"},{"kind":"text","text":";"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class~1config\/title","value":"config","op":"replace"},{"op":"replace","value":[{"text":"config","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class~1config\/fragments"},{"value":"SDDiskCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/fragments","value":[{"text":"SDDiskCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/navigatorTitle","op":"replace","value":[{"text":"SDDiskCache","kind":"identifier"}]},{"value":"SDImageCacheConfig","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title"},{"value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments"},{"value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}