{"metadata":{"role":"symbol","externalID":"c:objc(cs)SDDiskCache(im)moveCacheDirectoryFromPath:toPath:","symbolKind":"method","roleHeading":"Instance Method","title":"moveDirectory(fromPath:toPath:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"moveDirectory"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"fromPath"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"toPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"moveCacheDirectoryFromPath:toPath:","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sddiskcache-swift.class\/movedirectory(frompath:topath:)"]},{"paths":["\/documentation\/sdwebimage\/sddiskcache-swift.class\/movedirectory(frompath:topath:)"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"abstract":[{"type":"text","text":"Move the cache directory from old location to new location, the old location will be removed after finish."},{"text":" ","type":"text"},{"text":"If the old location does not exist, does nothing.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"If the new location does not exist, only do a movement of directory."},{"type":"text","text":" "},{"text":"If the new location does exist, will move and merge the files from old location.","type":"text"},{"type":"text","text":" "},{"text":"If the new location does exist, but is not a directory, will remove it and do a movement of directory.","type":"text"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"moveDirectory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromPath","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"srcPath"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"toPath","kind":"externalParam"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"dstPath"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"name":"srcPath","content":[{"type":"paragraph","inlineContent":[{"text":"Old location of cache directory","type":"text"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"New location of cache directory"}]}],"name":"dstPath"}],"kind":"parameters"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class\/moveDirectory(fromPath:toPath:)","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCache-swift.class":{"abstract":[{"text":"The built-in disk cache.","type":"text"}],"title":"SDDiskCache","url":"\/documentation\/sdwebimage\/sddiskcache-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDDiskCache","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class","kind":"symbol","navigatorTitle":[{"text":"SDDiskCache","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCache-swift.class/moveDirectory(fromPath:toPath:)":{"title":"moveDirectory(fromPath:toPath:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class\/moveDirectory(fromPath:toPath:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"moveDirectory","kind":"identifier"},{"text":"(","kind":"text"},{"text":"fromPath","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"text":"toPath","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":")","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"moveCacheDirectoryFromPath:toPath:"}],"abstract":[{"type":"text","text":"Move the cache directory from old location to new location, the old location will be removed after finish."},{"type":"text","text":" "},{"type":"text","text":"If the old location does not exist, does nothing."},{"type":"text","text":" "},{"type":"text","text":"If the new location does not exist, only do a movement of directory."},{"text":" ","type":"text"},{"text":"If the new location does exist, will move and merge the files from old location.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the new location does exist, but is not a directory, will remove it and do a movement of directory."}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sddiskcache-swift.class\/movedirectory(frompath:topath:)","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Method","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"moveCacheDirectoryFromPath:toPath:"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"moveCacheDirectoryFromPath:toPath:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"moveCacheDirectoryFromPath:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"srcPath","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"toPath:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"dstPath","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"name":"srcPath","content":[{"inlineContent":[{"text":"Old location of cache directory","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"New location of cache directory","type":"text"}],"type":"paragraph"}],"name":"dstPath"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/title","value":"SDDiskCache"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/fragments","op":"replace","value":[{"text":"SDDiskCache","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDDiskCache"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/navigatorTitle","op":"replace"},{"value":"moveCacheDirectoryFromPath:toPath:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class~1moveDirectory(fromPath:toPath:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class~1moveDirectory(fromPath:toPath:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"moveCacheDirectoryFromPath:toPath:","kind":"identifier"}]}]}]}