{"abstract":[{"text":"Downloader Config object - storing all kind of settings.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Most config properties support dynamic changes during download, except something like "},{"code":"sessionConfiguration","type":"codeVoice"},{"type":"text","text":", see "},{"code":"SDWebImageDownloaderConfig","type":"codeVoice"},{"type":"text","text":" for more detail."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"attribute","text":"@NSCopying"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig","kind":"typeIdentifier","text":"SDWebImageDownloaderConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"metadata":{"title":"config","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"config"}],"role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)SDWebImageDownloader(py)config"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/config"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/config"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/config"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"]]},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/config":{"role":"symbol","kind":"symbol","title":"config","url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/config","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/config","navigatorTitle":[{"kind":"identifier","text":"config"}],"type":"topic","abstract":[{"type":"text","text":"Downloader Config object - storing all kind of settings."},{"type":"text","text":" "},{"type":"text","text":"Most config properties support dynamic changes during download, except something like "},{"code":"sessionConfiguration","type":"codeVoice"},{"text":", see ","type":"text"},{"code":"SDWebImageDownloaderConfig","type":"codeVoice"},{"type":"text","text":" for more detail."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"config","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig","text":"SDWebImageDownloaderConfig","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloader","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloader","kind":"identifier"}],"role":"symbol","title":"SDWebImageDownloader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","abstract":[{"text":"Asynchronous downloader dedicated and optimized for image loading.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"navigatorTitle":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","abstract":[{"text":"The class contains all the config for image downloader","type":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"kind":"symbol","title":"SDWebImageDownloaderConfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"config","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"value":[{"kind":"identifier","text":"config"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageDownloaderConfig","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig"},{"kind":"text","text":" * "},{"kind":"identifier","text":"config"},{"text":";","kind":"text"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1config\/title","value":"config"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1config\/fragments","value":[{"text":"config","kind":"identifier"}]},{"op":"replace","value":"SDWebImageDownloader","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/navigatorTitle","value":[{"text":"SDWebImageDownloader","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title","value":"SDWebImageDownloaderConfig","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/navigatorTitle","value":[{"text":"SDWebImageDownloaderConfig","kind":"identifier"}]}]}]}