{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/decryptor"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/decryptor"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decryptor"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDWebImageDownloaderDecryptor","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorProtocol","text":"SDWebImageDownloaderDecryptorProtocol"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"type":"aside","style":"note","content":[{"inlineContent":[{"type":"text","text":"When using decryptor, progressive decoding will be disabled, to avoid data corrupt issue."}],"type":"paragraph"}],"name":"Note"},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you want to decrypt single download data, consider using "},{"code":"SDWebImageContextDownloadDecryptor","type":"codeVoice"},{"text":" context option.","type":"text"}]}],"style":"note"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/decryptor"},"metadata":{"externalID":"c:objc(cs)SDWebImageDownloader(py)decryptor","role":"symbol","symbolKind":"property","navigatorTitle":[{"kind":"identifier","text":"decryptor"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"decryptor","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"SDWebImageDownloaderDecryptorProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderDecryptor"},{"kind":"text","text":")?"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","title":"decryptor"},"schemaVersion":{"patch":0,"minor":3,"major":0},"sections":[],"abstract":[{"text":"Set the decryptor to decrypt the original download data before image decoding. This can be used for encrypted image data, like Base64.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This decryptor method will be called for each downloading image data. Return the original data means no modification. Return nil will mark this download failed."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download data."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloader","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloader","kind":"identifier"}],"role":"symbol","title":"SDWebImageDownloader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","abstract":[{"text":"Asynchronous downloader dedicated and optimized for image loading.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/decryptor":{"title":"decryptor","abstract":[{"text":"Set the decryptor to decrypt the original download data before image decoding. This can be used for encrypted image data, like Base64.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This decryptor method will be called for each downloading image data. Return the original data means no modification. Return nil will mark this download failed."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download data."}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/decryptor","url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/decryptor","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"decryptor"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"decryptor","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDWebImageDownloaderDecryptor","kind":"typeIdentifier","text":"SDWebImageDownloaderDecryptorProtocol"},{"text":")?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptorProtocol":{"navigatorTitle":[{"text":"SDWebImageDownloaderDecryptorProtocol","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptorprotocol","title":"SDWebImageDownloaderDecryptorProtocol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorProtocol","kind":"symbol","abstract":[{"type":"text","text":"This is the protocol for downloader decryptor. Which decrypt the original encrypted data before decoding. Note progressive decoding is not compatible for decryptor."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the downloader decryptor. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptorProtocol"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","value":"decryptor","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"decryptor"}],"op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDWebImageDownloaderDecryptor","text":"id<SDWebImageDownloaderDecryptor>"},{"kind":"text","text":" "},{"text":"decryptor","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title","op":"replace","value":"SDWebImageDownloader"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}],"op":"replace"},{"value":[{"text":"SDWebImageDownloader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1decryptor\/title","value":"decryptor"},{"op":"replace","value":[{"text":"decryptor","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1decryptor\/fragments"},{"value":"SDWebImageDownloaderDecryptor","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorProtocol\/title"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorProtocol\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorProtocol\/navigatorTitle","value":[{"text":"SDWebImageDownloaderDecryptor","kind":"identifier"}]}]}]}