{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderRequestModifier","text":"SDWebImageDownloaderRequestModifierProtocol"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/requestmodifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/requestmodifier"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/requestModifier","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Set the request modifier to modify the original download request before image load."},{"type":"text","text":" "},{"type":"text","text":"This request modifier method will be called for each downloading image request. Return the original request means no modification. Return nil will cancel the download request."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download request."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderRequestModifierProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderRequestModifier"},{"kind":"text","text":"?"}],"title":"requestModifier","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageDownloader(py)requestModifier","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"requestModifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierProtocol":{"role":"symbol","title":"SDWebImageDownloaderRequestModifierProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for downloader request modifier."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the downloader request modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/requestModifier":{"role":"symbol","title":"requestModifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderRequestModifierProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderRequestModifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the request modifier to modify the original download request before image load."},{"type":"text","text":" "},{"type":"text","text":"This request modifier method will be called for each downloading image request. Return the original request means no modification. Return nil will cancel the download request."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download request."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/requestModifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/requestmodifier"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"role":"symbol","title":"SDWebImageDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloader"}],"abstract":[{"type":"text","text":"Asynchronous downloader dedicated and optimized for image loading."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloader"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"requestModifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"requestModifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SDWebImageDownloaderRequestModifier>","preciseIdentifier":"c:Qoobjc(pl)SDWebImageDownloaderRequestModifier"},{"kind":"text","text":" * "},{"kind":"identifier","text":"requestModifier"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/title","value":"SDWebImageDownloaderRequestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1requestModifier\/title","value":"requestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1requestModifier\/fragments","value":[{"kind":"identifier","text":"requestModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title","value":"SDWebImageDownloader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}