{"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"]]},"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Property","role":"symbol","symbolKind":"property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"responseModifier","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SDWebImageDownloaderResponseModifier","text":"SDWebImageDownloaderResponseModifierProtocol","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"responseModifier"}],"title":"responseModifier","externalID":"c:objc(cs)SDWebImageDownloader(py)responseModifier"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/responseModifier"},"abstract":[{"type":"text","text":"Set the response modifier to modify the original download response during image load."},{"type":"text","text":" "},{"type":"text","text":"This response modifier method will be called for each downloading image response. Return the original response means no modification. Return nil will mark current download as cancelled."},{"type":"text","text":" "},{"text":"Defaults to nil, means does not modify the original download response.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/responsemodifier"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/responsemodifier"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"responseModifier","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"SDWebImageDownloaderResponseModifierProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderResponseModifier"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}]}]},{"content":[{"text":"Discussion","level":2,"type":"heading","anchor":"discussion"},{"type":"aside","style":"note","name":"Note","content":[{"inlineContent":[{"text":"If you want to modify single response, consider using ","type":"text"},{"code":"SDWebImageContextDownloadResponseModifier","type":"codeVoice"},{"type":"text","text":" context option."}],"type":"paragraph"}]}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/responseModifier":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"responseModifier","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"SDWebImageDownloaderResponseModifierProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderResponseModifier"},{"kind":"text","text":")?"}],"navigatorTitle":[{"kind":"identifier","text":"responseModifier"}],"role":"symbol","kind":"symbol","title":"responseModifier","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/responsemodifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/responseModifier","abstract":[{"type":"text","text":"Set the response modifier to modify the original download response during image load."},{"type":"text","text":" "},{"type":"text","text":"This response modifier method will be called for each downloading image response. Return the original response means no modification. Return nil will mark current download as cancelled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download response."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifierProtocol":{"title":"SDWebImageDownloaderResponseModifierProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol","navigatorTitle":[{"text":"SDWebImageDownloaderResponseModifierProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierprotocol","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"This is the protocol for downloader response modifier.","type":"text"},{"text":" ","type":"text"},{"text":"We can use a block to specify the downloader response modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloader","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloader","kind":"identifier"}],"role":"symbol","title":"SDWebImageDownloader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","abstract":[{"text":"Asynchronous downloader dedicated and optimized for image loading.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"value":"responseModifier","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"responseModifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","text":"id<SDWebImageDownloaderResponseModifier>","preciseIdentifier":"c:Qoobjc(pl)SDWebImageDownloaderResponseModifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"responseModifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1responseModifier\/title","op":"replace","value":"responseModifier"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1responseModifier\/fragments","op":"replace","value":[{"kind":"identifier","text":"responseModifier"}]},{"op":"replace","value":"SDWebImageDownloaderResponseModifier","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title","value":"SDWebImageDownloader"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}],"op":"replace"},{"value":[{"text":"SDWebImageDownloader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}