{"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"type":"text","text":"The configuration in use by the internal NSURLSession. If you want to provide a custom sessionConfiguration, use "},{"code":"SDWebImageDownloaderConfig.sessionConfiguration","type":"codeVoice"},{"type":"text","text":" and create a new downloader instance."}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/sessionConfiguration","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"]]},"kind":"symbol","metadata":{"title":"sessionConfiguration","role":"symbol","externalID":"c:objc(cs)SDWebImageDownloader(py)sessionConfiguration","roleHeading":"Instance Property","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"sessionConfiguration","kind":"identifier"},{"kind":"text","text":": "},{"text":"URLSessionConfiguration","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"}],"symbolKind":"property","navigatorTitle":[{"text":"sessionConfiguration","kind":"identifier"}],"modules":[{"name":"SDWebImage"}]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/sessionconfiguration"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/sessionconfiguration"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"sessionConfiguration","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"This is immutable according to NSURLSession’s documentation. Mutating this object directly has no effect."}]}],"style":"note","name":"Note","type":"aside"}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/sessionConfiguration":{"navigatorTitle":[{"text":"sessionConfiguration","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The configuration in use by the internal NSURLSession. If you want to provide a custom sessionConfiguration, use "},{"type":"codeVoice","code":"SDWebImageDownloaderConfig.sessionConfiguration"},{"type":"text","text":" and create a new downloader instance."}],"title":"sessionConfiguration","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/sessionConfiguration","url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/sessionconfiguration","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"sessionConfiguration"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","text":"URLSessionConfiguration","kind":"typeIdentifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloader","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloader","kind":"identifier"}],"role":"symbol","title":"SDWebImageDownloader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","abstract":[{"text":"Asynchronous downloader dedicated and optimized for image loading.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Instance Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sessionConfiguration"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","value":[{"kind":"identifier","text":"sessionConfiguration"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"NSURLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"sessionConfiguration"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"sessionConfiguration","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1sessionConfiguration\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1sessionConfiguration\/fragments","op":"replace","value":[{"text":"sessionConfiguration","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title","value":"SDWebImageDownloader","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","op":"replace","value":[{"text":"SDWebImageDownloader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloader"}],"op":"replace"}]}]}