{"sections":[],"abstract":[{"type":"text","text":"Returns the value of the specified HTTP header field."}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/value(forHTTPHeaderField:)","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/value(forhttpheaderfield:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader\/value(forhttpheaderfield:)"]}],"metadata":{"navigatorTitle":[{"text":"valueForHTTPHeaderField:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Instance Method","title":"value(forHTTPHeaderField:)","symbolKind":"method","externalID":"c:objc(cs)SDWebImageDownloader(im)valueForHTTPHeaderField:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"value"},{"text":"(","kind":"text"},{"text":"forHTTPHeaderField","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"value","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forHTTPHeaderField"},{"kind":"text","text":" "},{"text":"field","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?) -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Return Value","type":"heading","anchor":"return-value","level":2},{"type":"paragraph","inlineContent":[{"text":"The value associated with the header field field, or ","type":"text"},{"type":"codeVoice","code":"nil"},{"text":" if there is no corresponding header field.","type":"text"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloader","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloader","kind":"identifier"}],"role":"symbol","title":"SDWebImageDownloader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","abstract":[{"text":"Asynchronous downloader dedicated and optimized for image loading.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/value(forHTTPHeaderField:)":{"title":"value(forHTTPHeaderField:)","abstract":[{"type":"text","text":"Returns the value of the specified HTTP header field."}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/value(forHTTPHeaderField:)","url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/value(forhttpheaderfield:)","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"valueForHTTPHeaderField:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"value","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forHTTPHeaderField"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"valueForHTTPHeaderField:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"valueForHTTPHeaderField:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" *) ","kind":"text"},{"text":"valueForHTTPHeaderField:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" *) "},{"text":"field","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":{"content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The value associated with the header field field, or ","type":"text"},{"code":"nil","type":"codeVoice"},{"type":"text","text":" if there is no corresponding header field."}]}],"kind":"content"},"path":"\/primaryContentSections\/1"},{"op":"replace","value":"SDWebImageDownloader","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","op":"replace","value":[{"text":"SDWebImageDownloader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageDownloader","kind":"identifier"}]},{"op":"replace","value":"valueForHTTPHeaderField:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1value(forHTTPHeaderField:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1value(forHTTPHeaderField:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"valueForHTTPHeaderField:","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}