{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"SD_MAC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sd_mac"]},{"paths":["\/documentation\/sdwebimage\/sd_mac"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"externalID":"c:SDWebImageCompat.h@576@macro@SD_MAC","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"SD_MAC","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"SD_MAC","kind":"identifier"}],"role":"symbol","symbolKind":"var","title":"SD_MAC","roleHeading":"Global Variable","modules":[{"name":"SDWebImage"}]},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SD_MAC","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SD_MAC":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SD_MAC"}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SD_MAC","abstract":[],"url":"\/documentation\/sdwebimage\/sd_mac","title":"SD_MAC","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"SD_MAC","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Macro"},{"value":"SD_MAC","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"macro"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SD_MAC"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"#define","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SD_MAC","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SD_MAC\/title","value":"SD_MAC"},{"op":"replace","value":[{"text":"SD_MAC","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SD_MAC\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}