{"topicSections":[{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageData","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrameCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageLoopCount"],"generated":true,"title":"Instance Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageDuration(at:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrame(at:)"],"anchor":"Instance-Methods"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SDAnimatedImageProvider","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObjectProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"abstract":[{"text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SDAnimatedImageCoder"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprovider"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageprovider"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"title":"Inherited By","kind":"relationships","type":"inheritedBy","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol"]},{"type":"conformingTypes","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"kind":"relationships","title":"Conforming Types"}],"metadata":{"symbolKind":"protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"externalID":"c:objc(pl)SDAnimatedImageProvider","role":"symbol","roleHeading":"Protocol","modules":[{"name":"SDWebImage"}],"title":"SDAnimatedImageProvider","navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageData":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"animatedImageData","kind":"identifier"},{"kind":"text","text":": "},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?","kind":"text"}],"abstract":[{"text":"The original animated image data for current image. If current image is not an animated format, return nil.","type":"text"},{"text":" ","type":"text"},{"text":"We may use this method to grab back the original image data if need, such as NSCoding or compare.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageData","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimagedata","title":"animatedImageData","navigatorTitle":[{"text":"animatedImageData","kind":"identifier"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"type":"topic","abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"code":"SDAnimatedImageCoder","type":"codeVoice"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"title":"SDAnimatedImageProvider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol":{"title":"SDAnimatedImageProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProtocol","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHEICCoder":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageheiccoder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageHEICCoder"}],"navigatorTitle":[{"text":"SDImageHEICCoder","kind":"identifier"}],"abstract":[{"text":"This coder is used for HEIC (HEIF with HEVC container codec) image format.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the static HEIC (.heic) support in iOS 11\/macOS 10.13\/tvOS 11\/watchOS 4+."},{"text":" ","type":"text"},{"type":"text","text":"Image\/IO provide the animated HEIC (.heics) support in iOS 13\/macOS 10.15\/tvOS 13\/watchOS 6+."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/nokiatech.github.io\/heif\/technical.html for the standard."}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","title":"SDImageHEICCoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder","type":"topic","title":"SDImageIOAnimatedCoder","kind":"symbol","abstract":[{"text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"role":"symbol","navigatorTitle":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAWebPCoder","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"text":" ","type":"text"},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"url":"\/documentation\/sdwebimage\/sdimageawebpcoder","title":"SDImageAWebPCoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageLoopCount":{"role":"symbol","abstract":[{"text":"Animation loop count, 0 means infinite looping.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"animatedImageLoopCount","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageloopcount","kind":"symbol","title":"animatedImageLoopCount","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageLoopCount","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"animatedImageLoopCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAPNGCoder":{"type":"topic","title":"SDImageAPNGCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAPNGCoder","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageapngcoder","navigatorTitle":[{"kind":"identifier","text":"SDImageAPNGCoder"}],"kind":"symbol","abstract":[{"type":"text","text":"Built in coder using ImageIO that supports APNG encoding\/decoding"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageGIFCoder":{"kind":"symbol","type":"topic","title":"SDImageGIFCoder","navigatorTitle":[{"text":"SDImageGIFCoder","kind":"identifier"}],"abstract":[{"text":"Built in coder using ImageIO that supports animated GIF encoding\/decoding","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","url":"\/documentation\/sdwebimage\/sdimagegifcoder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageGIFCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageDuration(at:)":{"role":"symbol","kind":"symbol","title":"animatedImageDuration(at:)","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageduration(at:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageDuration(at:)","required":true,"navigatorTitle":[{"kind":"identifier","text":"animatedImageDurationAtIndex:"}],"type":"topic","abstract":[{"type":"text","text":"Returns the frames’s duration from a specified index."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animatedImageDuration","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageFrameCount":{"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animatedImageFrameCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Total animated frame count."},{"text":" ","type":"text"},{"text":"If the frame count is less than 1, then the methods below will be ignored.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrameCount","kind":"symbol","required":true,"role":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageframecount","title":"animatedImageFrameCount","navigatorTitle":[{"text":"animatedImageFrameCount","kind":"identifier"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider/animatedImageFrame(at:)":{"navigatorTitle":[{"kind":"identifier","text":"animatedImageFrameAtIndex:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrame(at:)","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider\/animatedimageframe(at:)","role":"symbol","abstract":[{"type":"text","text":"Returns the frame image from a specified index."}],"title":"animatedImageFrame(at:)","type":"topic","kind":"symbol","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animatedImageFrame"},{"text":"(","kind":"text"},{"text":"at","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","kind":"symbol","title":"SDAnimatedImage","url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","navigatorTitle":[{"text":"SDAnimatedImage","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":". You can also use it on normal UIImageView\/NSImageView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"path":"\/metadata\/title","value":"SDAnimatedImageProvider","op":"replace"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageData","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrameCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageLoopCount"]},{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageDuration(at:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider\/animatedImageFrame(at:)"],"generated":true}]},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Inherited By","type":"inheritedBy","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder"]}],"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"animatedImageData","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageData\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageData\/fragments","value":[{"text":"animatedImageData","kind":"identifier"}]},{"value":"SDAnimatedImageProvider","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/navigatorTitle","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/title","value":"SDAnimatedImage"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/fragments","value":[{"text":"SDAnimatedImage","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDAnimatedImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/title","value":"SDImageHEICCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/fragments","value":[{"text":"SDImageHEICCoder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageHEICCoder"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title","value":"SDImageIOAnimatedCoder","op":"replace"},{"value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/navigatorTitle"},{"value":"SDImageAWebPCoder","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageAWebPCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageAWebPCoder"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageLoopCount\/title","value":"animatedImageLoopCount","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageLoopCount\/fragments","value":[{"text":"animatedImageLoopCount","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/title","value":"SDImageAPNGCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/fragments","value":[{"text":"SDImageAPNGCoder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageAPNGCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/title","value":"SDImageGIFCoder"},{"value":[{"text":"SDImageGIFCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/fragments"},{"value":[{"kind":"identifier","text":"SDImageGIFCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/navigatorTitle","op":"replace"},{"op":"replace","value":"animatedImageDurationAtIndex:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageDuration(at:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageDuration(at:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"animatedImageDurationAtIndex:"}]},{"value":"animatedImageFrameCount","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageFrameCount\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageFrameCount\/fragments","value":[{"kind":"identifier","text":"animatedImageFrameCount"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","value":"SDAnimatedImageCoder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageFrame(at:)\/title","value":"animatedImageFrameAtIndex:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider~1animatedImageFrame(at:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"animatedImageFrameAtIndex:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","value":"SDAnimatedImage"},{"value":[{"kind":"identifier","text":"SDAnimatedImage"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImage"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}