{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","preciseIdentifier":"c:objc(pl)SDAnimatedImageProvider","text":"SDAnimatedImageProvider"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageProtocol"}],"title":"SDAnimatedImageProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDAnimatedImage","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/animatedCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/isAllFramesLoaded"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/preloadAllFrames()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/unloadAllFrames()"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"role":"symbol","title":"SDAnimatedImageProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageProvider"}],"abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SDAnimatedImageCoder"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageProvider"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageprovider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/animatedCoder":{"navigatorTitle":[{"kind":"identifier","text":"animatedCoder"}],"role":"symbol","title":"animatedCoder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDAnimatedImageCoder","preciseIdentifier":"c:objc(pl)SDAnimatedImageCoder"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Return the animated image coder if the image is created with "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" method."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/animatedCoder","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/animatedcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/unloadAllFrames()":{"navigatorTitle":[{"kind":"identifier","text":"unloadAllFrames"}],"role":"symbol","title":"unloadAllFrames()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"unloadAllFrames"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Unload all animated image frame from memory if are already pre-loaded. Then later frame image request need decoding. You can use this to free up the memory usage if need."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/unloadAllFrames()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/unloadallframes()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/preloadAllFrames()":{"navigatorTitle":[{"kind":"identifier","text":"preloadAllFrames"}],"role":"symbol","title":"preloadAllFrames()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preloadAllFrames"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Pre-load all animated image frame into memory. Then later frame image request can directly return the frame for index without decoding."},{"type":"text","text":" "},{"type":"text","text":"This method may be called on background thread."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/preloadAllFrames()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/preloadallframes()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol":{"role":"symbol","title":"SDAnimatedImageProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for SDAnimatedImage class only but not for SDAnimatedImageCoder. If you want to provide a custom animated image class with full advanced function, you can conform to this instead of the base protocol."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageProtocol"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImage-swift.class":{"role":"symbol","title":"SDAnimatedImage","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"}],"abstract":[{"type":"text","text":"The image class which supports animating on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":". You can also use it on normal UIImageView\/NSImageView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImage-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImage"}],"url":"\/documentation\/sdwebimage\/sdanimatedimage-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProtocol/isAllFramesLoaded":{"navigatorTitle":[{"kind":"identifier","text":"allFramesLoaded"}],"role":"symbol","title":"isAllFramesLoaded","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isAllFramesLoaded"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns a Boolean value indicating whether all animated image frames are already pre-loaded into memory."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/isAllFramesLoaded","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageprotocol\/isallframesloaded"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDAnimatedImage"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/animatedCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/isAllFramesLoaded"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/preloadAllFrames()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProtocol\/unloadAllFrames()"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImage"},{"kind":"text","text":"<"},{"kind":"keyword","text":"SDAnimatedImageProvider"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","value":"SDAnimatedImageProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1animatedCoder\/title","value":"animatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1animatedCoder\/fragments","value":[{"kind":"identifier","text":"animatedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1unloadAllFrames()\/title","value":"unloadAllFrames"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1unloadAllFrames()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"unloadAllFrames"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1preloadAllFrames()\/title","value":"preloadAllFrames"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1preloadAllFrames()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"preloadAllFrames"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/title","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/title","value":"SDAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImage-swift.class\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1isAllFramesLoaded\/title","value":"allFramesLoaded"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProtocol~1isAllFramesLoaded\/fragments","value":[{"kind":"identifier","text":"allFramesLoaded"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}