{"sections":[],"topicSections":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/bounce","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/normal","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reverse","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reversedBounce"],"generated":true,"title":"Enumeration Cases"},{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/init(rawValue:)"]},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/RawRepresentable-Implementations"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"externalID":"c:@E@SDAnimatedImagePlaybackMode","title":"SDAnimatedImagePlaybackMode","role":"symbol","roleHeading":"Enumeration","symbolKind":"enum","fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"}]},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"type":"conformsTo","kind":"relationships"}],"abstract":[{"type":"text","text":"Animated image playback mode"}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplaybackmode"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplaybackmode"]}],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/bounce":{"kind":"symbol","type":"topic","title":"SDAnimatedImagePlaybackMode.bounce","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackModeBounce"}],"abstract":[{"text":"From first frame to last frame and reverse again, like reciprocating.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/bounce","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/bounce","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"bounce"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/Equatable-Implementations":{"role":"collectionGroup","abstract":[],"title":"Equatable Implementations","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/equatable-implementations","kind":"article","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/Equatable-Implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/normal":{"abstract":[{"text":"From first to last frame and stop or next loop.","type":"text"}],"title":"SDAnimatedImagePlaybackMode.normal","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/normal","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"normal","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/normal","kind":"symbol","navigatorTitle":[{"text":"SDAnimatedImagePlaybackModeNormal","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/reversedBounce":{"role":"symbol","abstract":[{"type":"text","text":"From last frame to first frame and reverse again, like reversed reciprocating."}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"reversedBounce"}],"title":"SDAnimatedImagePlaybackMode.reversedBounce","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/reversedbounce","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackModeReversedBounce"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reversedBounce"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/rawrepresentable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/RawRepresentable-Implementations","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/reverse":{"type":"topic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"reverse"}],"kind":"symbol","abstract":[{"text":"From last frame to first frame and stop or next loop.","type":"text"}],"title":"SDAnimatedImagePlaybackMode.reverse","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reverse","navigatorTitle":[{"text":"SDAnimatedImagePlaybackModeReverse","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/reverse","role":"symbol"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode\/init(rawvalue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlaybackMode":{"type":"topic","role":"symbol","title":"SDAnimatedImagePlaybackMode","url":"\/documentation\/sdwebimage\/sdanimatedimageplaybackmode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"abstract":[{"text":"Animated image playback mode","type":"text"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDAnimatedImagePlaybackMode","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/bounce","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/normal","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reverse","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlaybackMode\/reversedBounce"],"generated":true,"anchor":"Enumeration-Cases"}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SDAnimatedImagePlaybackModeBounce","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1bounce\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1bounce\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackModeBounce"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1normal\/title","value":"SDAnimatedImagePlaybackModeNormal","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1normal\/fragments","value":[{"text":"SDAnimatedImagePlaybackModeNormal","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1reversedBounce\/title","value":"SDAnimatedImagePlaybackModeReversedBounce","op":"replace"},{"value":[{"text":"SDAnimatedImagePlaybackModeReversedBounce","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1reversedBounce\/fragments"},{"op":"replace","value":"SDAnimatedImagePlaybackModeReverse","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1reverse\/title"},{"value":[{"text":"SDAnimatedImagePlaybackModeReverse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode~1reverse\/fragments"},{"value":"SDAnimatedImagePlaybackMode","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImagePlaybackMode"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlaybackMode\/navigatorTitle","value":[{"text":"SDAnimatedImagePlaybackMode","kind":"identifier"}]}]}]}