{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageCoder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","preciseIdentifier":"c:objc(pl)SDAnimatedImageProvider","text":"SDAnimatedImageProvider"},{"kind":"text","text":", "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder","text":"SDImageCoder"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimagecoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimagecoder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the animated image coder protocol for custom animated image class like  "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":". Through it inherit from "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":" to detect the proper coder for specify animated image format."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"title":"SDAnimatedImageCoder","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDAnimatedImageCoder","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder\/init(animatedImageData:options:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAPNGCoder":{"role":"symbol","title":"SDImageAPNGCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageAPNGCoder"}],"abstract":[{"type":"text","text":"Built in coder using ImageIO that supports APNG encoding\/decoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageAPNGCoder"}],"url":"\/documentation\/sdwebimage\/sdimageapngcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"role":"symbol","title":"SDAnimatedImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"abstract":[{"type":"text","text":"This is the animated image coder protocol for custom animated image class like  "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":". Through it inherit from "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":" to detect the proper coder for specify animated image format."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder":{"role":"symbol","title":"SDImageAWebPCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageAWebPCoder"}],"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageAWebPCoder"}],"url":"\/documentation\/sdwebimage\/sdimageawebpcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder/init(animatedImageData:options:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithAnimatedImageData:options:"}],"role":"symbol","title":"init(animatedImageData:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"animatedImageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Because animated image coder should keep the original data, we will alloc a new instance with the same class for the specify animated image data"},{"type":"text","text":" "},{"type":"text","text":"The init method should return nil if it can’t decode the specify animated image data to produce any frame."},{"type":"text","text":" "},{"type":"text","text":"After the instance created, we may call methods in "},{"type":"codeVoice","code":"SDAnimatedImageProvider"},{"type":"text","text":" to produce animated image frame."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder\/init(animatedImageData:options:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimagecoder\/init(animatedimagedata:options:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageGIFCoder":{"role":"symbol","title":"SDImageGIFCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageGIFCoder"}],"abstract":[{"type":"text","text":"Built in coder using ImageIO that supports animated GIF encoding\/decoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageGIFCoder"}],"url":"\/documentation\/sdwebimage\/sdimagegifcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"role":"symbol","title":"SDImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom image decoding\/encoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"role":"symbol","title":"SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"abstract":[{"type":"text","text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class."},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"role":"symbol","title":"SDAnimatedImageProvider","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageProvider"}],"abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"type":"codeVoice","code":"SDAnimatedImageCoder"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageProvider"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageprovider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHEICCoder":{"role":"symbol","title":"SDImageHEICCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageHEICCoder"}],"abstract":[{"type":"text","text":"This coder is used for HEIC (HEIF with HEVC container codec) image format."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the static HEIC (.heic) support in iOS 11\/macOS 10.13\/tvOS 11\/watchOS 4+."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the animated HEIC (.heics) support in iOS 13\/macOS 10.15\/tvOS 13\/watchOS 6+."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/nokiatech.github.io\/heif\/technical.html for the standard."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageHEICCoder"}],"url":"\/documentation\/sdwebimage\/sdimageheiccoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDAnimatedImageCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder\/init(animatedImageData:options:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageCoder"},{"kind":"text","text":"<"},{"kind":"keyword","text":"SDImageCoder"},{"kind":"text","text":", "},{"kind":"keyword","text":"SDAnimatedImageProvider"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/title","value":"SDImageAPNGCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/fragments","value":[{"kind":"identifier","text":"SDImageAPNGCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","value":"SDAnimatedImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/title","value":"SDImageAWebPCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/fragments","value":[{"kind":"identifier","text":"SDImageAWebPCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder~1init(animatedImageData:options:)\/title","value":"initWithAnimatedImageData:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder~1init(animatedImageData:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithAnimatedImageData:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/title","value":"SDImageGIFCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/fragments","value":[{"kind":"identifier","text":"SDImageGIFCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments","value":[{"kind":"identifier","text":"SDImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title","value":"SDImageIOAnimatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","value":"SDAnimatedImageProvider"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/title","value":"SDImageHEICCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/fragments","value":[{"kind":"identifier","text":"SDImageHEICCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}