{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering."},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"text":" with ","type":"text"},{"code":"UIImage(NSImage)","type":"codeVoice"},{"type":"text","text":" which conforms to "},{"code":"SDAnimatedImage","type":"codeVoice"},{"type":"text","text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"type":"codeVoice","code":"-startAnimating"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"text":" to control animating. ","type":"text"},{"code":"isAnimating","type":"codeVoice"},{"type":"text","text":" to check animation state."},{"type":"text","text":" "},{"type":"text","text":"For AppKit: use "},{"code":"-setAnimates:","type":"codeVoice"},{"type":"text","text":" to control animating, "},{"code":"animates","type":"codeVoice"},{"type":"text","text":" to check animation state. This view is layer-backed."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"@","kind":"attribute"},{"kind":"attribute","preciseIdentifier":"s:ScM","text":"MainActor"},{"text":" ","kind":"text"},{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageView"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)UIImageView"]},{"title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCoding","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)CALayerDelegate","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAccessibilityIdentification","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIActivityItemsConfigurationProviding","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAppearance","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAppearanceContainer","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UICoordinateSpace","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIDynamicItem","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIFocusEnvironment","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIFocusItem","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIFocusItemContainer","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UILargeContentViewerItem","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIPasteConfigurationSupporting","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIPopoverPresentationControllerSourceItem","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIResponderStandardEditActions","doc:\/\/com.dailymotion.SDWebImage\/5UIKit23UITraitChangeObservableP","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UITraitEnvironment","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIUserActivityRestoring"],"type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageview"]},{"paths":["\/documentation\/sdwebimage\/sdanimatedimageview"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationRepeatCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/autoPlayAnimatedImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/clearBufferWhenStopped","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentFrame","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentFrameIndex","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/maxBufferSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackRate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/player","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/resetFrameIndexWhenStopped","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/runLoopMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldCustomLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldIncrementalLoad"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:progress:completed:)"]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageView"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)SDAnimatedImageView","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"title":"SDAnimatedImageView","symbolKind":"class"},"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/clearBufferWhenStopped":{"type":"topic","title":"clearBufferWhenStopped","navigatorTitle":[{"kind":"identifier","text":"clearBufferWhenStopped"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/clearBufferWhenStopped","abstract":[{"text":"Whether or not to clear the frame buffer cache when animation stopped. See ","type":"text"},{"type":"codeVoice","code":"maxBufferSize"},{"type":"text","text":" "},{"type":"text","text":"This is useful when you want to limit the memory usage during frequently visibility changes (such as image view inside a list view, then push and pop)"},{"type":"text","text":" "},{"text":"Default is NO.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearBufferWhenStopped","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/clearbufferwhenstopped"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/currentLoopCount":{"type":"topic","title":"currentLoopCount","navigatorTitle":[{"text":"currentLoopCount","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentLoopCount","abstract":[{"type":"text","text":"Current loop count since its latest animating. This value is KVO Compliance."}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentLoopCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/currentloopcount"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/shouldIncrementalLoad":{"type":"topic","title":"shouldIncrementalLoad","navigatorTitle":[{"text":"shouldIncrementalLoad","kind":"identifier"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldIncrementalLoad","abstract":[{"text":"Whehter or not to enable incremental image load for animated image. This is for the animated image which ","type":"text"},{"type":"codeVoice","code":"sd_isIncremental"},{"type":"text","text":" is YES (See "},{"type":"codeVoice","code":"UIImage+Metadata.h"},{"type":"text","text":"). If enable, animated image rendering will stop at the last frame available currently, and continue when another "},{"type":"codeVoice","code":"setImage:"},{"type":"text","text":" trigger, where the new animated image’s "},{"code":"animatedImageData","type":"codeVoice"},{"text":" should be updated from the previous one. If the ","type":"text"},{"type":"codeVoice","code":"sd_isIncremental"},{"text":" is NO. The incremental image load stop.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldIncrementalLoad"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/shouldincrementalload"},"doc://com.dailymotion.SDWebImage/objc(pl)NSCoding":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCoding","title":"Foundation.NSCoding"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageView","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView","abstract":[{"text":"A drop-in replacement for UIImageView\/NSImageView, you can use this for animated image rendering.","type":"text"},{"type":"text","text":" "},{"text":"Call ","type":"text"},{"code":"setImage:","type":"codeVoice"},{"type":"text","text":" with "},{"code":"UIImage(NSImage)","type":"codeVoice"},{"text":" which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol will start animated image rendering. Call with normal UIImage(NSImage) will back to normal UIImageView(NSImageView) rendering","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For UIKit: use "},{"code":"-startAnimating","type":"codeVoice"},{"type":"text","text":", "},{"code":"-stopAnimating","type":"codeVoice"},{"type":"text","text":" to control animating. "},{"type":"codeVoice","code":"isAnimating"},{"text":" to check animation state.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit: use ","type":"text"},{"code":"-setAnimates:","type":"codeVoice"},{"text":" to control animating, ","type":"text"},{"type":"codeVoice","code":"animates"},{"text":" to check animation state. This view is layer-backed.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview","title":"SDAnimatedImageView","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/objc(pl)UIFocusItemContainer":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIFocusItemContainer","title":"UIKit.UIFocusItemContainer"},"doc://com.dailymotion.SDWebImage/objc(pl)UIUserActivityRestoring":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIUserActivityRestoring","title":"UIKit.UIUserActivityRestoring"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/playbackMode":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"playbackMode","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackMode","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/playbackmode","abstract":[{"type":"text","text":"Asynchronous setup animation playback mode. Default mode is SDAnimatedImagePlaybackModeNormal."}],"title":"playbackMode","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"playbackMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDAnimatedImagePlaybackMode","preciseIdentifier":"c:@E@SDAnimatedImagePlaybackMode","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/shouldCustomLoopCount":{"type":"topic","abstract":[{"type":"text","text":"YES to choose "},{"type":"codeVoice","code":"animationRepeatCount"},{"text":" property for animation loop count. No to use animated image’s ","type":"text"},{"code":"animatedImageLoopCount","type":"codeVoice"},{"type":"text","text":" instead."},{"type":"text","text":" "},{"text":"Default is NO.","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldCustomLoopCount","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/shouldcustomloopcount","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shouldCustomLoopCount","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"kind":"identifier","text":"shouldCustomLoopCount"}],"title":"shouldCustomLoopCount"},"doc://com.dailymotion.SDWebImage/objc(cs)UIImageView":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)UIImageView","title":"UIImageView","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(pl)UIAppearance":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAppearance","title":"UIKit.UIAppearance","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:progress:completed:)":{"title":"sd_setImage(with:placeholderImage:options:progress:completed:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","text":"SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"text":"SDExternalCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock"},{"text":"?)","kind":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:progress:completed:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"text":", placeholder and custom options.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:progress:completed:)","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:progress:completed:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/objc(pl)UICoordinateSpace":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UICoordinateSpace","title":"UIKit.UICoordinateSpace","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:context:progress:completed:)":{"type":"topic","title":"sd_setImage(with:placeholderImage:options:context:progress:completed:)","navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:context:progress:completed:"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:progress:completed:)","abstract":[{"text":"Set the imageView ","type":"text"},{"type":"codeVoice","code":"image"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"type":"text","text":", placeholder, custom options and context."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"placeholderImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","text":"SDExternalCompletionBlock"},{"kind":"text","text":"?)"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:context:progress:completed:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/resetFrameIndexWhenStopped":{"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/resetframeindexwhenstopped","type":"topic","abstract":[{"type":"text","text":"Whether or not to reset the current frame index when animation stopped."},{"type":"text","text":" "},{"type":"text","text":"For some of use case, you may want to reset the frame index to 0 when stop, but some other want to keep the current frame index."},{"type":"text","text":" "},{"type":"text","text":"Default is NO."}],"navigatorTitle":[{"text":"resetFrameIndexWhenStopped","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/resetFrameIndexWhenStopped","role":"symbol","title":"resetFrameIndexWhenStopped","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"resetFrameIndexWhenStopped"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImageWithURL:":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:","navigatorTitle":[{"text":"sd_setImageWithURL:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:","role":"symbol","abstract":[{"text":"Set the imageView ","type":"text"},{"code":"image","type":"codeVoice"},{"type":"text","text":" with an "},{"code":"url","type":"codeVoice"},{"text":".","type":"text"}],"kind":"symbol","title":"sd_setImageWithURL:","fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/objc(pl)UIFocusEnvironment":{"title":"UIKit.UIFocusEnvironment","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIFocusEnvironment","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:context:)":{"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:context:)","type":"topic","abstract":[{"text":"Set the imageView ","type":"text"},{"type":"codeVoice","code":"image"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"text":", placeholder, custom options and context.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:context:"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:)","role":"symbol","title":"sd_setImage(with:placeholderImage:options:context:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}]},"doc://com.dailymotion.SDWebImage/objc(pl)UITraitEnvironment":{"title":"UIKit.UITraitEnvironment","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UITraitEnvironment","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(pl)UIPasteConfigurationSupporting":{"title":"UIKit.UIPasteConfigurationSupporting","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIPasteConfigurationSupporting","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/runLoopMode":{"kind":"symbol","abstract":[{"text":"You can specify a runloop mode to let it rendering.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Default is NSRunLoopCommonModes on multi-core device, NSDefaultRunLoopMode on single-core device"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/runLoopMode","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"runLoopMode","kind":"identifier"},{"text":": ","kind":"text"},{"text":"RunLoop","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSRunLoop"},{"text":".","kind":"text"},{"text":"Mode","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRunLoopMode"}],"navigatorTitle":[{"text":"runLoopMode","kind":"identifier"}],"title":"runLoopMode","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/runloopmode"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/animationRepeatCount":{"navigatorTitle":[{"text":"animationRepeatCount","kind":"identifier"}],"abstract":[{"text":"Total loop count for animated image rendering. Default is animated image’s loop count.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If you need to set custom loop count, set "},{"type":"codeVoice","code":"shouldCustomLoopCount"},{"type":"text","text":" to YES and change this value."},{"type":"text","text":" "},{"type":"text","text":"This class override UIImageView’s "},{"type":"codeVoice","code":"animationRepeatCount"},{"type":"text","text":" property on iOS, use this property as well."}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"animationRepeatCount","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Si","text":"Int","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/animationrepeatcount","type":"topic","title":"animationRepeatCount","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationRepeatCount"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImageWithURL:placeholderImage:":{"role":"symbol","kind":"symbol","title":"sd_setImageWithURL:placeholderImage:","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Set the imageView "},{"type":"codeVoice","code":"image"},{"type":"text","text":" with an "},{"type":"codeVoice","code":"url"},{"text":" and a placeholder.","type":"text"}],"fragments":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:"}]},"doc://com.dailymotion.SDWebImage/objc(pl)CALayerDelegate":{"title":"QuartzCore.CALayerDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)CALayerDelegate","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/currentFrame":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFrame"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentFrame","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/currentframe","abstract":[{"text":"Current display frame image. This value is KVO Compliance.","type":"text"}],"title":"currentFrame","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentFrame"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/animationTransformer":{"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/animationtransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationTransformer","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationTransformer"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SDImageTransformer","kind":"typeIdentifier","text":"SDImageTransformer"},{"text":")?","kind":"text"}],"abstract":[{"type":"text","text":"The transformer for each decoded animated image frame."},{"text":" ","type":"text"},{"type":"text","text":"We supports post-transform on animated image frame from version 5.20."},{"type":"text","text":" "},{"type":"text","text":"When you configure the transformer on "},{"code":"SDAnimatedImageView","type":"codeVoice"},{"text":" and animation is playing, the ","type":"text"},{"code":"transformedImageWithImage:forKey:","type":"codeVoice"},{"text":" will be called just after the frame is decoded. (note: The ","type":"text"},{"code":"key","type":"codeVoice"},{"text":" arg is always empty for backward-compatible and may be removed in the future)","type":"text"}],"title":"animationTransformer","navigatorTitle":[{"kind":"identifier","text":"animationTransformer"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/objc(pl)UIPopoverPresentationControllerSourceItem":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIPopoverPresentationControllerSourceItem","type":"unresolvable","title":"UIKit.UIPopoverPresentationControllerSourceItem"},"doc://com.dailymotion.SDWebImage/objc(pl)UIActivityItemsConfigurationProviding":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIActivityItemsConfigurationProviding","type":"unresolvable","title":"UIKit.UIActivityItemsConfigurationProviding"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImageWithURL:placeholderImage:completed:":{"role":"symbol","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:completed:"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:completed:","title":"sd_setImageWithURL:placeholderImage:completed:","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"type":"text","text":" with an "},{"code":"url","type":"codeVoice"},{"text":", placeholder.","type":"text"}],"navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:completed:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:completed:"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImageWithURL:placeholderImage:options:":{"type":"topic","fragments":[{"kind":"text","text":"- "},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:options:","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimagewithurl:placeholderimage:options:","abstract":[{"text":"Set the imageView ","type":"text"},{"code":"image","type":"codeVoice"},{"type":"text","text":" with an "},{"code":"url","type":"codeVoice"},{"text":", placeholder and custom options.","type":"text"}],"title":"sd_setImageWithURL:placeholderImage:options:","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:"}]},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/playbackRate":{"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"playbackRate","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sd","kind":"typeIdentifier","text":"Double"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackRate","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/playbackrate","abstract":[{"type":"text","text":"The animation playback rate. Default is 1.0."},{"text":" ","type":"text"},{"code":"1.0","type":"codeVoice"},{"type":"text","text":" means the normal speed."},{"text":" ","type":"text"},{"type":"codeVoice","code":"0.0"},{"type":"text","text":" means stopping the animation."},{"type":"text","text":" "},{"type":"codeVoice","code":"0.0-1.0"},{"type":"text","text":" means the slow speed."},{"type":"text","text":" "},{"code":"> 1.0","type":"codeVoice"},{"type":"text","text":" means the fast speed."},{"text":" ","type":"text"},{"code":"< 0.0","type":"codeVoice"},{"type":"text","text":" is not supported currently and stop animation. (may support reverse playback in the future)"}],"title":"playbackRate","kind":"symbol","navigatorTitle":[{"text":"playbackRate","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/currentFrameIndex":{"title":"currentFrameIndex","navigatorTitle":[{"kind":"identifier","text":"currentFrameIndex"}],"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"currentFrameIndex"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"kind":"symbol","abstract":[{"type":"text","text":"Current frame index, zero based. This value is KVO Compliance."}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/currentframeindex","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentFrameIndex"},"doc://com.dailymotion.SDWebImage/objc(pl)UIAppearanceContainer":{"title":"UIKit.UIAppearanceContainer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAppearanceContainer","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting":{"title":"UIKit.UIAccessibilityContentSizeCategoryImageAdjusting","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAccessibilityContentSizeCategoryImageAdjusting","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/maxBufferSize":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"maxBufferSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/maxbuffersize","title":"maxBufferSize","abstract":[{"text":"Provide a max buffer size by bytes. This is used to adjust frame buffer count and can be useful when the decoding cost is expensive (such as Animated WebP software decoding). Default is 0.","type":"text"},{"text":" ","type":"text"},{"type":"codeVoice","code":"0"},{"type":"text","text":" means automatically adjust by calculating current memory usage."},{"type":"text","text":" "},{"code":"1","type":"codeVoice"},{"type":"text","text":" means without any buffer cache, each of frames will be decoded and then be freed after rendering. (Lowest Memory and Highest CPU)"},{"text":" ","type":"text"},{"code":"NSUIntegerMax","type":"codeVoice"},{"type":"text","text":" means cache all the buffer. (Lowest CPU and Highest Memory)"}],"navigatorTitle":[{"text":"maxBufferSize","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/maxBufferSize"},"doc://com.dailymotion.SDWebImage/objc(pl)UIAccessibilityIdentification":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIAccessibilityIdentification","type":"unresolvable","title":"UIKit.UIAccessibilityIdentification"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/player":{"role":"symbol","abstract":[{"text":"The internal animation player.","type":"text"},{"type":"text","text":" "},{"text":"This property is only used for advanced usage, like inspecting\/debugging animation status, control progressive loading, complicated animation frame index control, etc.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"player"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/player","kind":"symbol","title":"player","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/player","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"player"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDAnimatedImagePlayer","text":"SDAnimatedImagePlayer"},{"text":"?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/objc(pl)UILargeContentViewerItem":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UILargeContentViewerItem","type":"unresolvable","title":"UIKit.UILargeContentViewerItem"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:placeholderImage:options:completed:)":{"role":"symbol","title":"sd_setImage(with:placeholderImage:options:completed:)","kind":"symbol","navigatorTitle":[{"text":"sd_setImageWithURL:placeholderImage:options:completed:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:placeholderimage:options:completed:)","type":"topic","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"placeholderImage","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","kind":"typeIdentifier","text":"SDExternalCompletionBlock"},{"kind":"text","text":"?)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:completed:)","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"text":" with an ","type":"text"},{"code":"url","type":"codeVoice"},{"type":"text","text":", placeholder and custom options."}]},"doc://com.dailymotion.SDWebImage/objc(pl)UIResponderStandardEditActions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIResponderStandardEditActions","type":"unresolvable","title":"UIKit.UIResponderStandardEditActions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/autoPlayAnimatedImage":{"title":"autoPlayAnimatedImage","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/autoPlayAnimatedImage","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageview\/autoplayanimatedimage","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"autoPlayAnimatedImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"autoPlayAnimatedImage","kind":"identifier"}],"abstract":[{"text":"If the image which conforms to ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"text":" protocol has more than one frame, set this value to ","type":"text"},{"type":"codeVoice","code":"YES"},{"text":" will automatically","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"play\/stop the animation when the view become visible\/invisible."},{"text":" ","type":"text"},{"type":"text","text":"Default is YES."}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/5UIKit23UITraitChangeObservableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/5UIKit23UITraitChangeObservableP","type":"unresolvable","title":"UIKit.UITraitChangeObservable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageView/sd_setImage(with:completed:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:completed:)","abstract":[{"type":"text","text":"Set the imageView "},{"code":"image","type":"codeVoice"},{"text":" with an ","type":"text"},{"type":"codeVoice","code":"url"},{"text":".","type":"text"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sd_setImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDExternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDExternalCompletionBlock"},{"text":"?)","kind":"text"}],"title":"sd_setImage(with:completed:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sd_setImageWithURL:completed:"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageview\/sd_setimage(with:completed:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/objc(pl)UIFocusItem":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIFocusItem","type":"unresolvable","title":"UIKit.UIFocusItem"},"doc://com.dailymotion.SDWebImage/objc(pl)UIDynamicItem":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)UIDynamicItem","type":"unresolvable","title":"UIKit.UIDynamicItem"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable","title":"Swift.Equatable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SDAnimatedImageView","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDAnimatedImageView","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDAnimatedImageView"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationRepeatCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/animationTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/autoPlayAnimatedImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/clearBufferWhenStopped","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentFrame","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentFrameIndex","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/currentLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/maxBufferSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/playbackRate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/player","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/resetFrameIndexWhenStopped","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/runLoopMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldCustomLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/shouldIncrementalLoad"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImage(with:placeholderImage:options:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:completed:","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageView\/sd_setImageWithURL:placeholderImage:options:"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}]},{"op":"replace","value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)UIImageView"],"kind":"relationships","title":"Inherits From"}],"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageView"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)UIImageView","kind":"typeIdentifier","text":"UIImageView"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1clearBufferWhenStopped\/title","value":"clearBufferWhenStopped","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1clearBufferWhenStopped\/fragments","value":[{"text":"clearBufferWhenStopped","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentLoopCount\/title","op":"replace","value":"currentLoopCount"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentLoopCount\/fragments","value":[{"text":"currentLoopCount","kind":"identifier"}],"op":"replace"},{"value":"shouldIncrementalLoad","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1shouldIncrementalLoad\/title","op":"replace"},{"value":[{"kind":"identifier","text":"shouldIncrementalLoad"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1shouldIncrementalLoad\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/title","value":"SDAnimatedImageView"},{"value":[{"text":"SDAnimatedImageView","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImageView"}]},{"value":"playbackMode","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1playbackMode\/title","op":"replace"},{"value":[{"kind":"identifier","text":"playbackMode"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1playbackMode\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1shouldCustomLoopCount\/title","value":"shouldCustomLoopCount"},{"op":"replace","value":[{"text":"shouldCustomLoopCount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1shouldCustomLoopCount\/fragments"},{"op":"replace","value":"sd_setImageWithURL:placeholderImage:options:progress:completed:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:progress:completed:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:placeholderImage:options:progress:completed:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:progress:completed:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:context:progress:completed:)\/title","op":"replace","value":"sd_setImageWithURL:placeholderImage:options:context:progress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:context:progress:completed:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:placeholderImage:options:context:progress:completed:"}]},{"value":"resetFrameIndexWhenStopped","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1resetFrameIndexWhenStopped\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1resetFrameIndexWhenStopped\/fragments","value":[{"kind":"identifier","text":"resetFrameIndexWhenStopped"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:context:)\/title","value":"sd_setImageWithURL:placeholderImage:options:context:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:context:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:placeholderImage:options:context:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1runLoopMode\/title","value":"runLoopMode","op":"replace"},{"value":[{"kind":"identifier","text":"runLoopMode"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1runLoopMode\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1animationRepeatCount\/title","op":"replace","value":"animationRepeatCount"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1animationRepeatCount\/fragments","op":"replace","value":[{"text":"animationRepeatCount","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentFrame\/title","value":"currentFrame","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentFrame\/fragments","value":[{"text":"currentFrame","kind":"identifier"}]},{"value":"animationTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1animationTransformer\/title"},{"value":[{"kind":"identifier","text":"animationTransformer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1animationTransformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1playbackRate\/title","value":"playbackRate","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1playbackRate\/fragments","value":[{"kind":"identifier","text":"playbackRate"}]},{"value":"currentFrameIndex","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentFrameIndex\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1currentFrameIndex\/fragments","value":[{"kind":"identifier","text":"currentFrameIndex"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1maxBufferSize\/title","value":"maxBufferSize","op":"replace"},{"value":[{"kind":"identifier","text":"maxBufferSize"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1maxBufferSize\/fragments","op":"replace"},{"op":"replace","value":"player","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1player\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1player\/fragments","op":"replace","value":[{"kind":"identifier","text":"player"}]},{"value":"sd_setImageWithURL:placeholderImage:options:completed:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:completed:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:placeholderImage:options:completed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"sd_setImageWithURL:placeholderImage:options:completed:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1autoPlayAnimatedImage\/title","op":"replace","value":"autoPlayAnimatedImage"},{"value":[{"text":"autoPlayAnimatedImage","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1autoPlayAnimatedImage\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:completed:)\/title","value":"sd_setImageWithURL:completed:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sd_setImageWithURL:completed:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageView~1sd_setImage(with:completed:)\/fragments","op":"replace"}]}]}