{"topicSections":[{"anchor":"Initializers","title":"Initializers","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/init(provider:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/animationFrameHandler","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/animationLoopHandler","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrame","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrameIndex","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/isPlaying","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/maxBufferSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackRate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/runLoopMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalFrameCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalLoopCount"],"anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/clearFrameBuffer()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/pausePlaying()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/seekToFrame(at:loopCount:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/startPlaying()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/stopPlaying()"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdanimatedimageplayer"]}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","title":"SDAnimatedImagePlayer","symbolKind":"class","externalID":"c:objc(cs)SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/seekToFrame(at:loopCount:)":{"abstract":[{"type":"text","text":"Seek to the desired frame index and loop count."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/seekToFrame(at:loopCount:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"seekToFrame"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"at"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":", "},{"kind":"externalParam","text":"loopCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"seekToFrame(at:loopCount:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/seektoframe(at:loopcount:)","navigatorTitle":[{"kind":"identifier","text":"seekToFrameAtIndex:loopCount:"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/totalFrameCount":{"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/totalframecount","kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalFrameCount","navigatorTitle":[{"text":"totalFrameCount","kind":"identifier"}],"abstract":[{"type":"text","text":"Total frame count for animated image rendering. Defaults is animated image’s frame count."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalFrameCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"totalFrameCount"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/playerWithProvider:":{"fragments":[{"kind":"text","text":"+ "},{"text":"playerWithProvider:","kind":"identifier"}],"title":"playerWithProvider:","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/playerwithprovider:","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playerWithProvider:","abstract":[{"type":"text","text":"Create a player with animated image provider. If the provider’s "},{"type":"codeVoice","code":"animatedImageFrameCount"},{"type":"text","text":" is less than 1, returns nil."},{"type":"text","text":" "},{"text":"The provider can be any protocol implementation, like ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" or "},{"code":"SDImageGIFCoder","type":"codeVoice"},{"text":", etc.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"playerWithProvider:"}]},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/isPlaying":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/isPlaying","abstract":[{"text":"Return the status whether animation is playing.","type":"text"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isPlaying"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"title":"isPlaying","navigatorTitle":[{"text":"isPlaying","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/isplaying"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/animationLoopHandler":{"kind":"symbol","abstract":[{"type":"text","text":"The handler block when one loop count finished."}],"title":"animationLoopHandler","navigatorTitle":[{"kind":"identifier","text":"animationLoopHandler"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/animationloophandler","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/animationLoopHandler","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animationLoopHandler","kind":"identifier"},{"kind":"text","text":": (("},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":") -> "},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/init(provider:)":{"navigatorTitle":[{"text":"initWithProvider:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/init(provider:)","abstract":[{"text":"Create a player with animated image provider. If the provider’s ","type":"text"},{"code":"animatedImageFrameCount","type":"codeVoice"},{"type":"text","text":" is less than 1, returns nil."},{"type":"text","text":" "},{"type":"text","text":"The provider can be any protocol implementation, like "},{"code":"SDAnimatedImage","type":"codeVoice"},{"type":"text","text":", "},{"code":"SDImageGIFCoder","type":"codeVoice"},{"type":"text","text":", etc."}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/init(provider:)","role":"symbol","title":"init(provider:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"provider","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"SDAnimatedImageProvider","preciseIdentifier":"c:objc(pl)SDAnimatedImageProvider","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","title":"NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer":{"title":"SDAnimatedImagePlayer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"abstract":[{"text":"A player to control the playback of animated image, which can be used to drive Animated ImageView or any rendering usage, like CALayer\/WatchKit\/SwiftUI rendering.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer","navigatorTitle":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/currentLoopCount":{"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentloopcount","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"currentLoopCount","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"title":"currentLoopCount","abstract":[{"type":"text","text":"Current loop count since its latest animating. This value is KVO Compliance."}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentLoopCount","navigatorTitle":[{"text":"currentLoopCount","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/clearFrameBuffer()":{"navigatorTitle":[{"kind":"identifier","text":"clearFrameBuffer"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"clearFrameBuffer","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"clearFrameBuffer()","abstract":[{"text":"Clear the frame cache buffer. The frame cache buffer size can be controlled by ","type":"text"},{"type":"codeVoice","code":"maxBufferSize"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"By default, when stop or pause the animation, the frame buffer is still kept to ready for the next restart","type":"text"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/clearFrameBuffer()","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/clearframebuffer()","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/stopPlaying()":{"abstract":[{"type":"text","text":"Stop the animation. Reset the current frame index and loop count."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stopPlaying","kind":"identifier"},{"text":"()","kind":"text"}],"kind":"symbol","title":"stopPlaying()","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/stopplaying()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/stopPlaying()","navigatorTitle":[{"text":"stopPlaying","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/pausePlaying()":{"title":"pausePlaying()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/pausePlaying()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"pausePlaying","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"pausePlaying","kind":"identifier"}],"abstract":[{"text":"Pause the animation. Keep the current frame index and loop count.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/pauseplaying()","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/playbackMode":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackMode","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackMode"},{"text":": ","kind":"text"},{"text":"SDAnimatedImagePlaybackMode","preciseIdentifier":"c:@E@SDAnimatedImagePlaybackMode","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"playbackMode"}],"title":"playbackMode","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackmode","type":"topic","abstract":[{"text":"Asynchronous setup animation playback mode. Default mode is SDAnimatedImagePlaybackModeNormal.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/totalLoopCount":{"abstract":[{"type":"text","text":"Total loop count for animated image rendering. Default is animated image’s loop count."}],"title":"totalLoopCount","navigatorTitle":[{"kind":"identifier","text":"totalLoopCount"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"totalLoopCount","kind":"identifier"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalLoopCount","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/totalloopcount","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/currentFrameIndex":{"kind":"symbol","type":"topic","title":"currentFrameIndex","navigatorTitle":[{"text":"currentFrameIndex","kind":"identifier"}],"abstract":[{"text":"Current frame index, zero based. This value is KVO Compliance.","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrameIndex","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentframeindex","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"currentFrameIndex","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/maxBufferSize":{"title":"maxBufferSize","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/maxBufferSize","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"maxBufferSize","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"kind":"identifier","text":"maxBufferSize"}],"abstract":[{"type":"text","text":"Provide a max buffer size by bytes. This is used to adjust frame buffer count and can be useful when the decoding cost is expensive (such as Animated WebP software decoding). Default is 0."},{"text":" ","type":"text"},{"type":"codeVoice","code":"0"},{"text":" means automatically adjust by calculating current memory usage.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"1"},{"text":" means without any buffer cache, each of frames will be decoded and then be freed after rendering. (Lowest Memory and Highest CPU)","type":"text"},{"type":"text","text":" "},{"code":"NSUIntegerMax","type":"codeVoice"},{"type":"text","text":" means cache all the buffer. (Lowest CPU and Highest Memory)"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/maxbuffersize","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/runLoopMode":{"navigatorTitle":[{"text":"runLoopMode","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"runLoopMode","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSRunLoop","text":"RunLoop","kind":"typeIdentifier"},{"kind":"text","text":"."},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSRunLoopMode","text":"Mode"}],"abstract":[{"type":"text","text":"You can specify a runloop mode to let it rendering."},{"text":" ","type":"text"},{"text":"Default is NSRunLoopCommonModes on multi-core device, NSDefaultRunLoopMode on single-core device","type":"text"}],"title":"runLoopMode","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/runloopmode","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/runLoopMode"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/playbackRate":{"abstract":[{"type":"text","text":"The animation playback rate. Default is 1.0"},{"type":"text","text":" "},{"type":"codeVoice","code":"1.0"},{"text":" means the normal speed.","type":"text"},{"type":"text","text":" "},{"code":"0.0","type":"codeVoice"},{"type":"text","text":" means stopping the animation."},{"text":" ","type":"text"},{"type":"codeVoice","code":"0.0-1.0"},{"text":" means the slow speed.","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"> 1.0"},{"type":"text","text":" means the fast speed."},{"type":"text","text":" "},{"type":"codeVoice","code":"< 0.0"},{"type":"text","text":" is not supported currently and stop animation. (may support reverse playback in the future)"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"playbackRate"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sd","text":"Double"}],"title":"playbackRate","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackRate","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/playbackrate","navigatorTitle":[{"text":"playbackRate","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/currentFrame":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrame","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/currentframe","role":"symbol","abstract":[{"type":"text","text":"Current playing frame image. This value is KVO Compliance."}],"navigatorTitle":[{"text":"currentFrame","kind":"identifier"}],"type":"topic","title":"currentFrame","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentFrame"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/startPlaying()":{"abstract":[{"text":"Start the animation. Or resume the previously paused animation.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/startPlaying()","type":"topic","navigatorTitle":[{"kind":"identifier","text":"startPlaying"}],"url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/startplaying()","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"startPlaying"},{"kind":"text","text":"()"}],"title":"startPlaying()"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImagePlayer/animationFrameHandler":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/animationFrameHandler","url":"\/documentation\/sdwebimage\/sdanimatedimageplayer\/animationframehandler","title":"animationFrameHandler","abstract":[{"type":"text","text":"The handler block when current frame and index changed."}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animationFrameHandler"},{"text":": ((","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"},{"text":")?","kind":"text"}],"type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"animationFrameHandler"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"value":"SDAnimatedImagePlayer","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/animationFrameHandler","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/animationLoopHandler","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrame","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentFrameIndex","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/currentLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/isPlaying","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/maxBufferSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playbackRate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/runLoopMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalFrameCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/totalLoopCount"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/clearFrameBuffer()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/init(provider:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/pausePlaying()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/seekToFrame(at:loopCount:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/startPlaying()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/stopPlaying()"],"title":"Instance Methods","generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImagePlayer\/playerWithProvider:"],"title":"Type Methods","anchor":"Type-Methods","generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImagePlayer"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"seekToFrameAtIndex:loopCount:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1seekToFrame(at:loopCount:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"seekToFrameAtIndex:loopCount:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1seekToFrame(at:loopCount:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1totalFrameCount\/title","value":"totalFrameCount"},{"value":[{"text":"totalFrameCount","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1totalFrameCount\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1isPlaying\/title","value":"isPlaying"},{"op":"replace","value":[{"text":"isPlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1isPlaying\/fragments"},{"value":"animationLoopHandler","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1animationLoopHandler\/title"},{"value":[{"text":"animationLoopHandler","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1animationLoopHandler\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1init(provider:)\/title","value":"initWithProvider:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithProvider:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1init(provider:)\/fragments"},{"value":"SDAnimatedImagePlayer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImagePlayer"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer\/navigatorTitle","op":"replace","value":[{"text":"SDAnimatedImagePlayer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentLoopCount\/title","value":"currentLoopCount","op":"replace"},{"value":[{"text":"currentLoopCount","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentLoopCount\/fragments","op":"replace"},{"value":"clearFrameBuffer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1clearFrameBuffer()\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1clearFrameBuffer()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"clearFrameBuffer"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1stopPlaying()\/title","value":"stopPlaying","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"stopPlaying","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1stopPlaying()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1pausePlaying()\/title","value":"pausePlaying"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1pausePlaying()\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"pausePlaying"}]},{"value":"playbackMode","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackMode\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackMode\/fragments","value":[{"text":"playbackMode","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1totalLoopCount\/title","value":"totalLoopCount","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1totalLoopCount\/fragments","value":[{"text":"totalLoopCount","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentFrameIndex\/title","value":"currentFrameIndex"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentFrameIndex\/fragments","value":[{"kind":"identifier","text":"currentFrameIndex"}],"op":"replace"},{"value":"maxBufferSize","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1maxBufferSize\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1maxBufferSize\/fragments","value":[{"kind":"identifier","text":"maxBufferSize"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1runLoopMode\/title","op":"replace","value":"runLoopMode"},{"value":[{"text":"runLoopMode","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1runLoopMode\/fragments"},{"value":"playbackRate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackRate\/title"},{"value":[{"kind":"identifier","text":"playbackRate"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1playbackRate\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentFrame\/title","value":"currentFrame"},{"value":[{"kind":"identifier","text":"currentFrame"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1currentFrame\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1startPlaying()\/title","value":"startPlaying"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1startPlaying()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startPlaying","kind":"identifier"}]},{"value":"animationFrameHandler","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1animationFrameHandler\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImagePlayer~1animationFrameHandler\/fragments","op":"replace","value":[{"text":"animationFrameHandler","kind":"identifier"}]}]}]}