{"relationshipsSections":[{"title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"type":"conformsTo"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdcallbackpolicy"]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"}]}]}],"abstract":[{"text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use ","type":"text"},{"code":"dispatch_async\/dispatch_sync","type":"codeVoice"},{"type":"text","text":", check if current queue match target queue, or just invoke without any context."}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"generated":true,"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/dispatch","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/invoke","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeAsyncMainThread","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeExecute"],"anchor":"Enumeration-Cases"},{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/RawRepresentable-Implementations"],"anchor":"Default-Implementations","generated":true}],"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"externalID":"c:@E@SDCallbackPolicy","title":"SDCallbackPolicy","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"}],"symbolKind":"enum","modules":[{"name":"SDWebImage"}],"roleHeading":"Enumeration","navigatorTitle":[{"text":"SDCallbackPolicy","kind":"identifier"}],"role":"symbol"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/safeExecute":{"role":"symbol","type":"topic","title":"SDCallbackPolicy.safeExecute","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/safeexecute","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"safeExecute"}],"kind":"symbol","abstract":[{"type":"text","text":"When the current queue is equal to callback queue, sync\/async will just invoke "},{"type":"codeVoice","code":"block"},{"text":" directly without dispatch. Else it use ","type":"text"},{"code":"dispatch_async","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"dispatch_sync","type":"codeVoice"},{"type":"text","text":" to dispatch block on queue. This is useful for UIKit rendering to ensure all blocks executed in the same runloop"}],"navigatorTitle":[{"text":"SDCallbackPolicySafeExecute","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeExecute"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/invoke":{"title":"SDCallbackPolicy.invoke","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"text":"invoke","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"Ignore any async\/sync and just directly invoke "},{"type":"codeVoice","code":"block"},{"text":" in current queue (without ","type":"text"},{"type":"codeVoice","code":"dispatch_async"},{"text":"\/","type":"text"},{"code":"dispatch_sync","type":"codeVoice"},{"text":")","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/invoke","navigatorTitle":[{"kind":"identifier","text":"SDCallbackPolicyInvoke"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/invoke","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/Equatable-Implementations":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/Equatable-Implementations","role":"collectionGroup","title":"Equatable Implementations","abstract":[],"url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/equatable-implementations","kind":"article","type":"topic"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/init(rawValue:)":{"abstract":[],"kind":"symbol","type":"topic","title":"init(rawValue:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/init(rawValue:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"kind":"text","text":")"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/dispatch":{"title":"SDCallbackPolicy.dispatch","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dispatch"}],"type":"topic","abstract":[{"type":"text","text":"Follow async\/sync using the correspond "},{"type":"codeVoice","code":"dispatch_async"},{"text":"\/","type":"text"},{"type":"codeVoice","code":"dispatch_sync"},{"type":"text","text":" to dispatch block on queue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/dispatch","navigatorTitle":[{"text":"SDCallbackPolicyDispatch","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/dispatch","role":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/safeAsyncMainThread":{"title":"SDCallbackPolicy.safeAsyncMainThread","fragments":[{"text":"case","kind":"keyword"},{"kind":"text","text":" "},{"text":"safeAsyncMainThread","kind":"identifier"}],"type":"topic","abstract":[{"text":"Ensure callback in main thread. Do ","type":"text"},{"type":"codeVoice","code":"dispatch_async"},{"text":" if the ","type":"text"},{"code":"NSThread.isMainTrhead == true","type":"codeVoice"},{"text":" ; else do invoke ","type":"text"},{"type":"codeVoice","code":"block"},{"type":"text","text":". Never use "},{"type":"codeVoice","code":"dispatch_sync"},{"text":", suitable for special UI-related code","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeAsyncMainThread","navigatorTitle":[{"text":"SDCallbackPolicySafeAsyncMainThread","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/safeasyncmainthread","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy":{"role":"symbol","kind":"symbol","abstract":[{"type":"text","text":"SDCallbackPolicy controls how we execute the block on the queue, like whether to use "},{"type":"codeVoice","code":"dispatch_async\/dispatch_sync"},{"text":", check if current queue match target queue, or just invoke without any context.","type":"text"}],"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy","url":"\/documentation\/sdwebimage\/sdcallbackpolicy","navigatorTitle":[{"text":"SDCallbackPolicy","kind":"identifier"}],"title":"SDCallbackPolicy","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackPolicy/RawRepresentable-Implementations":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/RawRepresentable-Implementations","role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/sdwebimage\/sdcallbackpolicy\/rawrepresentable-implementations","kind":"article","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Enumeration","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SDCallbackPolicy"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDCallbackPolicy","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SDCallbackPolicy","kind":"identifier"}]},{"value":[{"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/dispatch","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/invoke","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeAsyncMainThread","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackPolicy\/safeExecute"]}],"op":"replace","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SDCallbackPolicySafeExecute","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeExecute\/title"},{"value":[{"text":"SDCallbackPolicySafeExecute","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeExecute\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1invoke\/title","op":"replace","value":"SDCallbackPolicyInvoke"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1invoke\/fragments","value":[{"text":"SDCallbackPolicyInvoke","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1dispatch\/title","value":"SDCallbackPolicyDispatch","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1dispatch\/fragments","op":"replace","value":[{"text":"SDCallbackPolicyDispatch","kind":"identifier"}]},{"op":"replace","value":"SDCallbackPolicySafeAsyncMainThread","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeAsyncMainThread\/title"},{"value":[{"text":"SDCallbackPolicySafeAsyncMainThread","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy~1safeAsyncMainThread\/fragments","op":"replace"},{"op":"replace","value":"SDCallbackPolicy","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/fragments","value":[{"text":"SDCallbackPolicy","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackPolicy\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDCallbackPolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}