{"relationshipsSections":[{"type":"inheritsFrom","kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"type":"conformsTo","title":"Conforms To"}],"abstract":[{"text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our ","type":"text"},{"type":"codeVoice","code":"Cache"},{"text":"\/","type":"text"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Loader"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"symbolKind":"class","externalID":"c:objc(cs)SDCallbackQueue","role":"symbol","title":"SDCallbackQueue"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdcallbackqueue"]}],"topicSections":[{"anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/init(dispatchQueue:)"],"title":"Initializers"},{"generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/policy"],"anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/async(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/sync(_:)"],"generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/current","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/global","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/main"],"anchor":"Type-Properties","title":"Type Properties","generated":true}],"sections":[],"references":{"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/global":{"type":"topic","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/global","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/global","abstract":[{"text":"The global concurrent queue (user-initiated QoS). Using ","type":"text"},{"type":"codeVoice","code":"dispatch_get_global_queue"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"The policy defaults to "},{"type":"codeVoice","code":"SDCallbackPolicySafeExecute"}],"navigatorTitle":[{"kind":"identifier","text":"globalQueue"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"global"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDCallbackQueue","kind":"typeIdentifier","text":"SDCallbackQueue"}],"title":"global"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/current":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"current"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue"}],"title":"current","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/current","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/current","abstract":[{"type":"text","text":"The caller current queue. Using "},{"type":"codeVoice","code":"dispatch_get_current_queue"},{"type":"text","text":". This is not a dynamic value and only keep the first call time queue."},{"text":" ","type":"text"},{"type":"text","text":"The policy defaults to "},{"code":"SDCallbackPolicySafeExecute","type":"codeVoice"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"currentQueue"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/init(dispatchQueue:)":{"type":"topic","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/init(dispatchqueue:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/init(dispatchQueue:)","abstract":[{"type":"text","text":"Create the callback queue with a GCD queue. The policy defaults to "},{"code":"SDCallbackPolicySafeExecute","type":"codeVoice"}],"navigatorTitle":[{"text":"initWithDispatchQueue:","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"dispatchQueue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@dispatch_queue_t","kind":"typeIdentifier","text":"dispatch_queue_t"},{"kind":"text","text":")"}],"title":"init(dispatchQueue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/async(_:)":{"navigatorTitle":[{"text":"async:","kind":"identifier"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/async(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"async","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"text":")","kind":"text"}],"title":"async(_:)","abstract":[{"type":"text","text":"Schedules a block asynchronously for execution."}],"kind":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/async(_:)"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/sync(_:)":{"type":"topic","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/sync(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/sync(_:)","abstract":[{"type":"text","text":"Submits a block for execution and returns after that block finishes executing."}],"navigatorTitle":[{"text":"sync:","kind":"identifier"}],"kind":"symbol","deprecated":true,"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"sync","kind":"identifier"},{"text":"(() -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"},{"kind":"text","text":")"}],"title":"sync(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue":{"url":"\/documentation\/sdwebimage\/sdcallbackqueue","navigatorTitle":[{"kind":"identifier","text":"SDCallbackQueue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"}],"title":"SDCallbackQueue","role":"symbol","type":"topic","abstract":[{"type":"text","text":"SDCallbackQueue is a wrapper used to control how the completionBlock should perform on queues, used by our "},{"type":"codeVoice","code":"Cache"},{"type":"text","text":"\/"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"text":".","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Useful when you call SDWebImage in non-main queue and want to avoid it callback into main queue, which may cause issue."}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/main":{"navigatorTitle":[{"text":"mainQueue","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/main","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/main","kind":"symbol","abstract":[{"type":"text","text":"The main queue. This is the default value, has the same effect when passing "},{"code":"nil","type":"codeVoice"},{"text":" to ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextCallbackQueue"},{"text":" ","type":"text"},{"type":"text","text":"The policy defaults to "},{"code":"SDCallbackPolicySafeAsyncMainThread","type":"codeVoice"}],"role":"symbol","title":"main","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"main","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDCallbackQueue","text":"SDCallbackQueue","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDCallbackQueue/policy":{"kind":"symbol","title":"policy","url":"\/documentation\/sdwebimage\/sdcallbackqueue\/policy","navigatorTitle":[{"text":"policy","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"policy","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDCallbackPolicy","text":"SDCallbackPolicy"}],"abstract":[{"type":"text","text":"The current queue’s callback policy."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/policy","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SDCallbackQueue"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDCallbackQueue","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDCallbackQueue","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/policy"]},{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/async(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/init(dispatchQueue:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/sync(_:)"],"title":"Instance Methods","generated":true},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/current","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/global","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDCallbackQueue\/main"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SDCallbackQueue","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"platforms":["iOS"]}]},"op":"replace"},{"value":"globalQueue","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1global\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1global\/fragments","value":[{"kind":"identifier","text":"globalQueue"}],"op":"replace"},{"op":"replace","value":"currentQueue","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1current\/title"},{"value":[{"text":"currentQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1current\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1init(dispatchQueue:)\/title","op":"replace","value":"initWithDispatchQueue:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1init(dispatchQueue:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithDispatchQueue:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1async(_:)\/title","value":"async:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1async(_:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"async:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1sync(_:)\/title","value":"sync:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"sync:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1sync(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/title","op":"replace","value":"SDCallbackQueue"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/fragments","value":[{"text":"SDCallbackQueue","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue\/navigatorTitle","value":[{"text":"SDCallbackQueue","kind":"identifier"}]},{"value":"mainQueue","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1main\/title"},{"value":[{"text":"mainQueue","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1main\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1policy\/title","value":"policy","op":"replace"},{"value":[{"text":"policy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDCallbackQueue~1policy\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}