{"topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/init(cachePath:config:)"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/cachePath(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/containsData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/data(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/extendedData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeAllData()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeExpiredData()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setData(_:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setExtendedData(_:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalCount()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalSize()"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDDiskCacheProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"kind":"symbol","abstract":[{"type":"text","text":"A protocol to allow custom disk cache used in SDImageCache."}],"metadata":{"externalID":"c:objc(pl)SDDiskCache","title":"SDDiskCacheProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDDiskCacheProtocol"}],"symbolKind":"protocol","modules":[{"name":"SDWebImage"}],"roleHeading":"Protocol","navigatorTitle":[{"text":"SDDiskCacheProtocol","kind":"identifier"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sddiskcacheprotocol"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/setExtendedData(_:forKey:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setExtendedData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/setextendeddata(_:forkey:)","title":"setExtendedData(_:forKey:)","required":true,"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setExtendedData(_:forKey:)","abstract":[{"type":"text","text":"Set extended data with a given key."}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"setExtendedData:forKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/data(forKey:)":{"title":"data(forKey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/data(forKey:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"data"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"dataForKey:"}],"abstract":[{"text":"Returns the data associated with a given key.","type":"text"},{"text":" ","type":"text"},{"text":"This method may blocks the calling thread until file read finished.","type":"text"}],"required":true,"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/data(forkey:)","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/totalSize()":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalSize()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"totalSize","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"navigatorTitle":[{"text":"totalSize","kind":"identifier"}],"title":"totalSize()","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/totalsize()","type":"topic","required":true,"abstract":[{"type":"text","text":"Returns the total size (in bytes) of data in this cache."},{"text":" ","type":"text"},{"type":"text","text":"This method may blocks the calling thread until file read finished."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/init(cachePath:config:)":{"fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"text":"cachePath","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(cachePath:config:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/init(cachePath:config:)","type":"topic","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"initWithCachePath:config:","kind":"identifier"}],"abstract":[{"text":"Create a new disk cache based on the specified path. You can check ","type":"text"},{"type":"codeVoice","code":"maxDiskSize"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"maxDiskAge"},{"text":" used for disk cache.","type":"text"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/init(cachepath:config:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/removeAllData()":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeAllData","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/removealldata()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeAllData()","title":"removeAllData()","role":"symbol","kind":"symbol","required":true,"navigatorTitle":[{"kind":"identifier","text":"removeAllData"}],"abstract":[{"text":"Empties the cache.","type":"text"},{"type":"text","text":" "},{"text":"This method may blocks the calling thread until file delete finished.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCache-swift.class":{"abstract":[{"text":"The built-in disk cache.","type":"text"}],"title":"SDDiskCache","url":"\/documentation\/sdwebimage\/sddiskcache-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDDiskCache","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class","kind":"symbol","navigatorTitle":[{"text":"SDDiskCache","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/cachePath(forKey:)":{"required":true,"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/cachePath(forKey:)","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cachePathForKey:"}],"title":"cachePath(forKey:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"cachePath","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/cachepath(forkey:)","kind":"symbol","role":"symbol","abstract":[{"type":"text","text":"The cache path for key"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/removeData(forKey:)":{"abstract":[{"type":"text","text":"Removes the value of the specified key in the cache."},{"text":" ","type":"text"},{"text":"This method may blocks the calling thread until file delete finished.","type":"text"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/removedata(forkey:)","title":"removeData(forKey:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeData","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"required":true,"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeData(forKey:)","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"removeDataForKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/containsData(forKey:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsData","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"role":"symbol","navigatorTitle":[{"text":"containsDataForKey:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/containsdata(forkey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/containsData(forKey:)","kind":"symbol","abstract":[{"type":"text","text":"Returns a boolean value that indicates whether a given key is in cache."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file read finished."}],"title":"containsData(forKey:)","type":"topic","required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol":{"title":"SDDiskCacheProtocol","abstract":[{"text":"A protocol to allow custom disk cache used in SDImageCache.","type":"text"}],"type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDDiskCacheProtocol"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol","navigatorTitle":[{"text":"SDDiskCacheProtocol","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/extendedData(forKey:)":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"extendedData"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"extendedDataForKey:"}],"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/extendeddata(forkey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/extendedData(forKey:)","kind":"symbol","abstract":[{"type":"text","text":"Returns the extended data associated with a given key."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file read finished."}],"title":"extendedData(forKey:)","type":"topic","required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/removeExpiredData()":{"url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/removeexpireddata()","type":"topic","abstract":[{"text":"Removes the expired data from the cache. You can choose the data to remove base on ","type":"text"},{"type":"codeVoice","code":"ageLimit"},{"text":", ","type":"text"},{"type":"codeVoice","code":"countLimit"},{"type":"text","text":" and "},{"type":"codeVoice","code":"sizeLimit"},{"text":" options.","type":"text"}],"navigatorTitle":[{"text":"removeExpiredData","kind":"identifier"}],"kind":"symbol","required":true,"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeExpiredData()","role":"symbol","title":"removeExpiredData()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeExpiredData","kind":"identifier"},{"kind":"text","text":"()"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/totalCount()":{"title":"totalCount()","required":true,"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"totalCount","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Returns the number of data in this cache."},{"type":"text","text":" "},{"type":"text","text":"This method may blocks the calling thread until file read finished."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalCount()","navigatorTitle":[{"text":"totalCount","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/totalcount()","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDDiskCacheProtocol/setData(_:forKey:)":{"kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setData","kind":"identifier"},{"kind":"text","text":"("},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"type":"topic","required":true,"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setData(_:forKey:)","title":"setData(_:forKey:)","url":"\/documentation\/sdwebimage\/sddiskcacheprotocol\/setdata(_:forkey:)","abstract":[{"text":"Sets the value of the specified key in the cache.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This method may blocks the calling thread until file write finished."}],"role":"symbol","navigatorTitle":[{"text":"setData:forKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Protocol"},{"value":"SDDiskCache","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SDDiskCache","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDDiskCache","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/cachePath(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/containsData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/data(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/extendedData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/init(cachePath:config:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeAllData()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/removeExpiredData()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setData(_:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/setExtendedData(_:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalCount()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCacheProtocol\/totalSize()"],"generated":true}]},{"op":"replace","value":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"]},{"title":"Conforming Types","kind":"relationships","type":"conformingTypes","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDDiskCache-swift.class"]}],"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDDiskCache","kind":"identifier"},{"text":" <","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1setExtendedData(_:forKey:)\/title","value":"setExtendedData:forKey:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1setExtendedData(_:forKey:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setExtendedData:forKey:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1data(forKey:)\/title","value":"dataForKey:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"dataForKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1data(forKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1totalSize()\/title","value":"totalSize"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1totalSize()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"totalSize","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"initWithCachePath:config:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1init(cachePath:config:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithCachePath:config:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1init(cachePath:config:)\/fragments"},{"value":"removeAllData","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeAllData()\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"removeAllData","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeAllData()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/title","value":"SDDiskCache"},{"op":"replace","value":[{"text":"SDDiskCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCache-swift.class\/navigatorTitle","value":[{"text":"SDDiskCache","kind":"identifier"}]},{"value":"cachePathForKey:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1cachePath(forKey:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"cachePathForKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1cachePath(forKey:)\/fragments"},{"value":"removeDataForKey:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeData(forKey:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeData(forKey:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"removeDataForKey:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1containsData(forKey:)\/title","value":"containsDataForKey:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1containsData(forKey:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"containsDataForKey:","kind":"identifier"}],"op":"replace"},{"value":"SDDiskCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/title","op":"replace"},{"value":[{"text":"SDDiskCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDDiskCache"}]},{"value":"extendedDataForKey:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1extendedData(forKey:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1extendedData(forKey:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"extendedDataForKey:","kind":"identifier"}]},{"value":"removeExpiredData","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeExpiredData()\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1removeExpiredData()\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeExpiredData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1totalCount()\/title","value":"totalCount"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1totalCount()\/fragments","value":[{"kind":"text","text":"- "},{"text":"totalCount","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1setData(_:forKey:)\/title","value":"setData:forKey:"},{"value":[{"text":"- ","kind":"text"},{"text":"setData:forKey:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDDiskCacheProtocol~1setData(_:forKey:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}