{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","interfaceLanguage":"swift"},"metadata":{"symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDExternalCompletionBlock","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDExternalCompletionBlock"}],"externalID":"c:SDWebImageManager.h@T@SDExternalCompletionBlock","title":"SDExternalCompletionBlock","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Alias"},"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdexternalcompletionblock"]},{"paths":["\/documentation\/sdwebimage\/sdexternalcompletionblock"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDExternalCompletionBlock"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, (any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","text":"SDImageCacheType"},{"text":", ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ","kind":"text"},{"text":"Void","kind":"typeIdentifier","preciseIdentifier":"s:s4Voida"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDExternalCompletionBlock":{"url":"\/documentation\/sdwebimage\/sdexternalcompletionblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDExternalCompletionBlock","kind":"identifier"}],"title":"SDExternalCompletionBlock","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDExternalCompletionBlock","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDExternalCompletionBlock"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Image Cache Type"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","url":"\/documentation\/sdwebimage\/sdimagecachetype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheType"}]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","value":"SDExternalCompletionBlock","path":"\/metadata\/title"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSError *, enum SDImageCacheType, NSURL *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSError#$@E@SDImageCacheType#*$objc(cs)NSURL)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDExternalCompletionBlock"},{"kind":"text","text":";"}],"platforms":["iOS"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/title","value":"SDExternalCompletionBlock"},{"value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDExternalCompletionBlock\/navigatorTitle","op":"replace","value":[{"text":"SDExternalCompletionBlock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","op":"replace","value":"SDImageCacheType"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","op":"replace","value":[{"text":"SDImageCacheType","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/navigatorTitle","value":[{"text":"SDImageCacheType","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}