{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsBeginImageContextWithOptions(_:_:_:)"},"kind":"symbol","abstract":[{"text":"Creates a bitmap-based graphics context with the specified options.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsbeginimagecontextwithoptions(_:_:_:)"]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsbeginimagecontextwithoptions(_:_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"externalID":"c:@F@SDGraphicsBeginImageContextWithOptions","symbolKind":"func","role":"symbol","roleHeading":"Function","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDGraphicsBeginImageContextWithOptions"},{"text":"(","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"kind":"text","text":")"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsBeginImageContextWithOptions"}],"title":"SDGraphicsBeginImageContextWithOptions(_:_:_:)","modules":[{"name":"SDWebImage"}]},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDGraphicsBeginImageContextWithOptions"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"opaque"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"text":", ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"scale","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsBeginImageContextWithOptions(_:_:_:)":{"abstract":[{"text":"Creates a bitmap-based graphics context with the specified options.","type":"text"}],"title":"SDGraphicsBeginImageContextWithOptions(_:_:_:)","type":"topic","url":"\/documentation\/sdwebimage\/sdgraphicsbeginimagecontextwithoptions(_:_:_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsBeginImageContextWithOptions"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsBeginImageContextWithOptions(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"SDGraphicsBeginImageContextWithOptions","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"text":")","kind":"text"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Function","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SDGraphicsBeginImageContextWithOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDGraphicsBeginImageContextWithOptions","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDGraphicsBeginImageContextWithOptions"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":", ","kind":"text"},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"opaque","kind":"internalParam"},{"kind":"text","text":", "},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGFloat","text":"CGFloat"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scale"},{"text":");","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsBeginImageContextWithOptions(_:_:_:)\/title","value":"SDGraphicsBeginImageContextWithOptions"},{"op":"replace","value":[{"kind":"identifier","text":"SDGraphicsBeginImageContextWithOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsBeginImageContextWithOptions(_:_:_:)\/fragments"}]}]}