{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsEndImageContext"},{"kind":"text","text":"()"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsendimagecontext()"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsendimagecontext()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsEndImageContext()","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Removes the current bitmap-based graphics context from the top of the stack."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsEndImageContext"},{"kind":"text","text":"()"}],"title":"SDGraphicsEndImageContext()","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@SDGraphicsEndImageContext","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsEndImageContext"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsEndImageContext()":{"role":"symbol","title":"SDGraphicsEndImageContext()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsEndImageContext"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Removes the current bitmap-based graphics context from the top of the stack."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsEndImageContext()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsEndImageContext"}],"url":"\/documentation\/sdwebimage\/sdgraphicsendimagecontext()"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsEndImageContext"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDGraphicsEndImageContext"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsEndImageContext"},{"kind":"text","text":"()"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsEndImageContext()\/title","value":"SDGraphicsEndImageContext"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsEndImageContext()\/fragments","value":[{"kind":"identifier","text":"SDGraphicsEndImageContext"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}