{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageDrawingActions"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagedrawingactions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagedrawingactions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageDrawingActions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A closure for drawing an image."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}],"title":"SDGraphicsImageDrawingActions","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:SDGraphicsImageRenderer.h@T@SDGraphicsImageDrawingActions","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageDrawingActions":{"role":"symbol","title":"SDGraphicsImageDrawingActions","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}],"abstract":[{"type":"text","text":"A closure for drawing an image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageDrawingActions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagedrawingactions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsImageDrawingActions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(struct CGContext *)","preciseIdentifier":"c:BFv(#*$@S@CGContext)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageDrawingActions\/title","value":"SDGraphicsImageDrawingActions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageDrawingActions\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageDrawingActions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}