{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerenderer"]}],"sections":[],"metadata":{"title":"SDGraphicsImageRenderer","navigatorTitle":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Class","symbolKind":"class","externalID":"c:objc(cs)SDGraphicsImageRenderer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRenderer"}]},"kind":"symbol","abstract":[{"text":"A graphics renderer for creating Core Graphics-backed images.","type":"text"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","kind":"relationships"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDGraphicsImageRenderer"}]}],"kind":"declarations"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:format:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/image(actions:)"],"generated":true,"title":"Instance Methods","anchor":"Instance-Methods"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer/init(size:)":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:)","navigatorTitle":[{"kind":"identifier","text":"initWithSize:"}],"type":"topic","kind":"symbol","title":"init(size:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Creates an image renderer for drawing images of a given size."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:)"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer/image(actions:)":{"abstract":[{"type":"text","text":"Creates an image by following a set of drawing instructions."}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"image","kind":"identifier"},{"text":"(","kind":"text"},{"text":"actions","kind":"externalParam"},{"text":": (","kind":"text"},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"imageWithActions:"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/image(actions:)","type":"topic","title":"image(actions:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/image(actions:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer/init(size:format:)":{"title":"init(size:format:)","abstract":[{"type":"text","text":"Creates a new image renderer with a given size and format."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:format:)","role":"symbol","type":"topic","navigatorTitle":[{"text":"initWithSize:format:","kind":"identifier"}],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"size"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"format","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDGraphicsImageRendererFormat","text":"SDGraphicsImageRendererFormat"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer\/init(size:format:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRenderer":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer","url":"\/documentation\/sdwebimage\/sdgraphicsimagerenderer","role":"symbol","abstract":[{"type":"text","text":"A graphics renderer for creating Core Graphics-backed images."}],"navigatorTitle":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"type":"topic","title":"SDGraphicsImageRenderer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRenderer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","type":"unresolvable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","value":"SDGraphicsImageRenderer","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRenderer"}],"op":"replace"},{"op":"replace","value":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/image(actions:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRenderer\/init(size:format:)"],"title":"Instance Methods"}]},{"value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRenderer","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:)\/title","value":"initWithSize:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithSize:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1image(actions:)\/title","value":"imageWithActions:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageWithActions:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1image(actions:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:format:)\/title","value":"initWithSize:format:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithSize:format:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer~1init(size:format:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/title","op":"replace","value":"SDGraphicsImageRenderer"},{"value":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRenderer\/navigatorTitle","op":"replace","value":[{"text":"SDGraphicsImageRenderer","kind":"identifier"}]}]}]}