{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","interfaceLanguage":"swift"},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/automatic","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/extended","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/standard","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/unspecified"]},{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/RawRepresentable-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"title":"SDGraphicsImageRendererFormatRange","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@SDGraphicsImageRendererFormatRange","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/standard":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange.standard","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"standard"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/standard","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeStandard"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/standard"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/rawrepresentable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/extended":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange.extended","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"extended"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/extended","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/extended"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/unspecified":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange.unspecified","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"unspecified"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/unspecified","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeUnspecified"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/unspecified"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormatRange/automatic":{"role":"symbol","title":"SDGraphicsImageRendererFormatRange.automatic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/automatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeAutomatic"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformatrange\/automatic"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsImageRendererFormatRange"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/automatic","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/extended","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/standard","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormatRange\/unspecified"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/title","value":"SDGraphicsImageRendererFormatRange"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRange"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1standard\/title","value":"SDGraphicsImageRendererFormatRangeStandard"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1standard\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeStandard"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1extended\/title","value":"SDGraphicsImageRendererFormatRangeExtended"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1extended\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeExtended"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1unspecified\/title","value":"SDGraphicsImageRendererFormatRangeUnspecified"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1unspecified\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeUnspecified"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1automatic\/title","value":"SDGraphicsImageRendererFormatRangeAutomatic"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormatRange~1automatic\/fragments","value":[{"kind":"identifier","text":"SDGraphicsImageRendererFormatRangeAutomatic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}