{"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsgetcurrentcontext()"]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsgetcurrentcontext()"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsGetCurrentContext()"},"kind":"symbol","sections":[],"abstract":[{"text":"Returns the current graphics context.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsGetCurrentContext","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","text":"CGContext","preciseIdentifier":"c:@T@CGContextRef"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"externalID":"c:@F@SDGraphicsGetCurrentContext","symbolKind":"func","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"SDGraphicsGetCurrentContext","kind":"identifier"},{"kind":"text","text":"() -> "},{"text":"CGContext","preciseIdentifier":"c:@T@CGContextRef","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"SDGraphicsGetCurrentContext"}],"modules":[{"name":"SDWebImage"}],"title":"SDGraphicsGetCurrentContext()","role":"symbol","roleHeading":"Function"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsGetCurrentContext()":{"type":"topic","abstract":[{"type":"text","text":"Returns the current graphics context."}],"url":"\/documentation\/sdwebimage\/sdgraphicsgetcurrentcontext()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsGetCurrentContext()","navigatorTitle":[{"text":"SDGraphicsGetCurrentContext","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDGraphicsGetCurrentContext"},{"text":"() -> ","kind":"text"},{"preciseIdentifier":"c:@T@CGContextRef","text":"CGContext","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"title":"SDGraphicsGetCurrentContext()","role":"symbol","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"value":"SDGraphicsGetCurrentContext","op":"replace","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SDGraphicsGetCurrentContext"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"CGContext","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGContext"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SDGraphicsGetCurrentContext"},{"kind":"text","text":"();"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"value":"SDGraphicsGetCurrentContext","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsGetCurrentContext()\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsGetCurrentContext()\/fragments","op":"replace","value":[{"text":"SDGraphicsGetCurrentContext","kind":"identifier"}]}]}]}