{"abstract":[{"type":"text","text":"A set of drawing attributes that represent the configuration of an image renderer context."}],"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/init()"]},{"anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/opaque","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferredRange","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/scale","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/uiformat"],"generated":true,"title":"Instance Properties"},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferred()"],"generated":true,"anchor":"Type-Methods"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdgraphicsimagerendererformat"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat"},"sections":[],"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"metadata":{"roleHeading":"Class","externalID":"c:objc(cs)SDGraphicsImageRendererFormat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDGraphicsImageRendererFormat"}],"modules":[{"name":"SDWebImage"}],"symbolKind":"class","role":"symbol","title":"SDGraphicsImageRendererFormat","navigatorTitle":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/opaque":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/opaque","abstract":[{"type":"text","text":"A Boolean value indicating whether the underlying Core Graphics context has an alpha channel."},{"type":"text","text":" "},{"text":"The default value is NO.","type":"text"}],"title":"opaque","kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/opaque","navigatorTitle":[{"text":"opaque","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"opaque","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/preferred()":{"title":"preferred()","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferred()","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preferred","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"navigatorTitle":[{"kind":"identifier","text":"preferredFormat"}],"abstract":[{"text":"Returns a new format best suited for the main screen’s current configuration.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferred()","type":"topic"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat":{"title":"SDGraphicsImageRendererFormat","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"navigatorTitle":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"abstract":[{"text":"A set of drawing attributes that represent the configuration of an image renderer context.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/preferredRange":{"role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferredRange","abstract":[{"text":"Specifying whether the bitmap context should use extended color.","type":"text"},{"type":"text","text":" "},{"text":"For iOS 12+, the value is from system ","type":"text"},{"type":"codeVoice","code":"preferredRange"},{"type":"text","text":" property"},{"text":" ","type":"text"},{"text":"For iOS 10-11, the value is from system ","type":"text"},{"type":"codeVoice","code":"prefersExtendedRange"},{"text":" property","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For iOS 9-, the value is "},{"type":"codeVoice","code":".standard"}],"title":"preferredRange","kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/preferredrange","navigatorTitle":[{"text":"preferredRange","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"preferredRange"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDGraphicsImageRendererFormatRange","text":"SDGraphicsImageRendererFormatRange","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/init()":{"title":"init()","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/init()","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"navigatorTitle":[{"text":"init","kind":"identifier"}],"abstract":[{"type":"text","text":"Init the default format. See each properties’s default value."}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/init()","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/uiformat":{"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/uiformat","type":"topic","abstract":[{"type":"text","text":"The underlying uiformat for UIKit. This usage of this API should be careful, which may cause out of sync."}],"kind":"symbol","title":"uiformat","url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/uiformat","navigatorTitle":[{"kind":"identifier","text":"uiformat"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiformat"},{"text":": ","kind":"text"},{"text":"UIGraphicsImageRendererFormat","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIGraphicsImageRendererFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsImageRendererFormat/scale":{"title":"scale","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/scale","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scale"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier","text":"CGFloat"}],"navigatorTitle":[{"text":"scale","kind":"identifier"}],"abstract":[{"type":"text","text":"The display scale of the image renderer context."},{"type":"text","text":" "},{"text":"The default value is equal to the scale of the main screen.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdgraphicsimagerendererformat\/scale","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDGraphicsImageRendererFormat"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}]},{"value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"path":"\/metadata\/navigatorTitle","op":"replace"},{"op":"replace","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/opaque","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferredRange","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/scale","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/uiformat"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/init()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"},{"generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsImageRendererFormat\/preferred()"],"title":"Type Methods","anchor":"Type-Methods"}],"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"}]},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDGraphicsImageRendererFormat"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1opaque\/title","value":"opaque","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1opaque\/fragments","op":"replace","value":[{"kind":"identifier","text":"opaque"}]},{"value":"preferredFormat","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferred()\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferred()\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"preferredFormat"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/title","value":"SDGraphicsImageRendererFormat"},{"op":"replace","value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat\/navigatorTitle","value":[{"text":"SDGraphicsImageRendererFormat","kind":"identifier"}]},{"op":"replace","value":"preferredRange","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferredRange\/title"},{"op":"replace","value":[{"text":"preferredRange","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1preferredRange\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1init()\/title","op":"replace","value":"init"},{"value":[{"text":"- ","kind":"text"},{"text":"init","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1init()\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1uiformat\/title","value":"uiformat"},{"value":[{"text":"uiformat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1uiformat\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1scale\/title","value":"scale","op":"replace"},{"value":[{"text":"scale","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsImageRendererFormat~1scale\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}