{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsBeginImageContext(_:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdgraphicsbeginimagecontext(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdgraphicsbeginimagecontext(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"func","modules":[{"name":"SDWebImage"}],"roleHeading":"Function","externalID":"c:@F@SDGraphicsBeginImageContext","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDGraphicsBeginImageContext","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":")","kind":"text"}],"title":"SDGraphicsBeginImageContext(_:)","navigatorTitle":[{"kind":"identifier","text":"SDGraphicsBeginImageContext"}]},"abstract":[{"text":"Creates a bitmap-based graphics context and makes it the current context.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDGraphicsBeginImageContext","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"size","kind":"internalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"kind":"text","text":")"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDGraphicsBeginImageContext(_:)":{"kind":"symbol","url":"\/documentation\/sdwebimage\/sdgraphicsbeginimagecontext(_:)","title":"SDGraphicsBeginImageContext(_:)","role":"symbol","navigatorTitle":[{"text":"SDGraphicsBeginImageContext","kind":"identifier"}],"abstract":[{"type":"text","text":"Creates a bitmap-based graphics context and makes it the current context."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"SDGraphicsBeginImageContext","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDGraphicsBeginImageContext(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"path":"\/metadata\/title","op":"replace","value":"SDGraphicsBeginImageContext"},{"path":"\/metadata\/symbolKind","op":"replace","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDGraphicsBeginImageContext"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":" ","kind":"text"},{"text":"SDGraphicsBeginImageContext","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"kind":"text","text":" "},{"text":"size","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsBeginImageContext(_:)\/title","value":"SDGraphicsBeginImageContext","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDGraphicsBeginImageContext(_:)\/fragments","value":[{"text":"SDGraphicsBeginImageContext","kind":"identifier"}]}]}]}