{"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/concurrent","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/highestOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/lowestOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/serial"],"title":"Enumeration Cases","anchor":"Enumeration-Cases","generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"title":"Default Implementations","anchor":"Default-Implementations","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/RawRepresentable-Implementations"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy"},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","metadata":{"fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"role":"symbol","symbolKind":"enum","externalID":"c:@E@SDImageCachesManagerOperationPolicy","roleHeading":"Enumeration","title":"SDImageCachesManagerOperationPolicy","modules":[{"name":"SDWebImage"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy"]}],"abstract":[{"type":"text","text":"Policy for cache operation"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/serial":{"abstract":[],"title":"SDImageCachesManagerOperationPolicy.serial","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/serial","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"serial","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/serial","kind":"symbol","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicySerial","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy","type":"topic","abstract":[{"text":"Policy for cache operation","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/highestOnly":{"abstract":[],"title":"SDImageCachesManagerOperationPolicy.highestOnly","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/highestonly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"highestOnly"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/highestOnly","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicyHighestOnly"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/rawrepresentable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/RawRepresentable-Implementations","kind":"article","type":"topic","role":"collectionGroup"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/concurrent":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/concurrent","role":"symbol","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"text":"concurrent","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicyConcurrent","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy.concurrent","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/concurrent"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/lowestOnly":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicyLowestOnly"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/lowestonly","kind":"symbol","title":"SDImageCachesManagerOperationPolicy.lowestOnly","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/lowestOnly","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"lowestOnly","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/init(rawValue:)":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/init(rawvalue:)","role":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"kind":"symbol","title":"init(rawValue:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/init(rawValue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy/Equatable-Implementations":{"kind":"article","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy\/equatable-implementations","abstract":[],"title":"Equatable Implementations","type":"topic","role":"collectionGroup","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/Equatable-Implementations"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"SDImageCachesManagerOperationPolicy","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"enum","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}]},{"value":[{"title":"Enumeration Cases","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/concurrent","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/highestOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/lowestOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy\/serial"],"anchor":"Enumeration-Cases"}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1serial\/title","value":"SDImageCachesManagerOperationPolicySerial"},{"op":"replace","value":[{"text":"SDImageCachesManagerOperationPolicySerial","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1serial\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title","op":"replace","value":"SDImageCachesManagerOperationPolicy"},{"op":"replace","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1highestOnly\/title","value":"SDImageCachesManagerOperationPolicyHighestOnly","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1highestOnly\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicyHighestOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1concurrent\/title","value":"SDImageCachesManagerOperationPolicyConcurrent"},{"op":"replace","value":[{"text":"SDImageCachesManagerOperationPolicyConcurrent","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1concurrent\/fragments"},{"value":"SDImageCachesManagerOperationPolicyLowestOnly","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1lowestOnly\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy~1lowestOnly\/fragments","value":[{"text":"SDImageCachesManagerOperationPolicyLowestOnly","kind":"identifier"}]}]}]}