{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoderdecodesolution"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"title":"SDImageCoderDecodeSolution","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@SDImageCoderDecodeSolution","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/automatic","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/coreGraphics","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/uiKit"]},{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/rawrepresentable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/uiKit":{"role":"symbol","title":"SDImageCoderDecodeSolution.uiKit","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"uiKit"}],"abstract":[{"type":"text","text":"available on iOS\/tvOS 15+, use UIKit’s new CGImageDecompressor\/CMPhoto to decode. Best performance. If failed, will fallback to CoreGraphics as well"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/uiKit","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionUIKit"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/uikit"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution":{"role":"symbol","title":"SDImageCoderDecodeSolution","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"abstract":[{"type":"text","text":"The options controls how we force pre-draw the image (to avoid lazy-decoding). Which need OS’s framework compatibility"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/coreGraphics":{"role":"symbol","title":"SDImageCoderDecodeSolution.coreGraphics","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"coreGraphics"}],"abstract":[{"type":"text","text":"always use CoreGraphics to draw on bitmap context and trigger decode. Best compatibility. Default before SDWebImage 5.13.0"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/coreGraphics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionCoreGraphics"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/coregraphics"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/automatic":{"role":"symbol","title":"SDImageCoderDecodeSolution.automatic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"abstract":[{"type":"text","text":"automatically choose the solution based on image format, hardware, OS version. This keep balance for compatibility and performance. Default after SDWebImage 5.13.0"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/automatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}],"url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/automatic"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderDecodeSolution/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderdecodesolution\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoderDecodeSolution"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/automatic","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/coreGraphics","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderDecodeSolution\/uiKit"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderDecodeSolution"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1uiKit\/title","value":"SDImageCoderDecodeSolutionUIKit"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1uiKit\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionUIKit"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/title","value":"SDImageCoderDecodeSolution"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolution"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1coreGraphics\/title","value":"SDImageCoderDecodeSolutionCoreGraphics"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1coreGraphics\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionCoreGraphics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1automatic\/title","value":"SDImageCoderDecodeSolutionAutomatic"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderDecodeSolution~1automatic\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeSolutionAutomatic"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}