{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/s25ExpressibleByArrayLiteralP","doc:\/\/com.dailymotion.SDWebImage\/s9OptionSetP","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","doc:\/\/com.dailymotion.SDWebImage\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image Cache Options"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheOptions"}],"title":"SDImageCacheOptions","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@SDImageCacheOptions","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/avoidDecodeImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/matchAnimatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/preloadAllFrames","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryDiskDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryData","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/scaleDownLargeImages"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/OptionSet-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/SetAlgebra-Implementations"],"generated":true}],"references":{"doc://com.dailymotion.SDWebImage/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s25ExpressibleByArrayLiteralP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/queryDiskDataSync":{"role":"symbol","title":"queryDiskDataSync","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryDiskDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, when the memory cache miss, we query the disk cache asynchronously. This mask can force to query disk cache (when memory cache miss) synchronously."},{"type":"text","text":" "},{"type":"text","text":"@note These 3 query options can be combined together. For the full list about these masks combination, see wiki page."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryDiskDataSync","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/querydiskdatasync"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/preloadAllFrames":{"role":"symbol","title":"preloadAllFrames","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preloadAllFrames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, for "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":", we decode the animated image frame during rendering to reduce memory usage. This flag actually trigger "},{"type":"codeVoice","code":"preloadAllAnimatedImageFrames = YES"},{"type":"text","text":" after image load from disk cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/preloadAllFrames","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachePreloadAllFrames"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/preloadallframes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/setalgebra-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/scaleDownLargeImages":{"role":"symbol","title":"scaleDownLargeImages","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, images are decoded respecting their original size. On iOS, this flag will scale down the"},{"type":"text","text":" "},{"type":"text","text":"images to a size compatible with the constrained memory of devices."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/scaleDownLargeImages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheScaleDownLargeImages"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/scaledownlargeimages"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/queryMemoryDataSync":{"role":"symbol","title":"queryMemoryDataSync","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, when you only specify "},{"type":"codeVoice","code":"SDImageCacheQueryMemoryData"},{"type":"text","text":", we query the memory image data asynchronously. Combined this mask as well to query the memory image data synchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryDataSync","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/querymemorydatasync"},"doc://com.dailymotion.SDWebImage/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s9OptionSetP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/matchAnimatedImageClass":{"role":"symbol","title":"matchAnimatedImageClass","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchAnimatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"type":"text","text":" context option (like using "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":"), we may still use "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" when the memory cache hit, or image decoder is not available, to behave as a fallback solution."},{"type":"text","text":" "},{"type":"text","text":"Using this option, can ensure we always produce image with your provided class. If failed, an error with code "},{"type":"codeVoice","code":"SDWebImageErrorBadImageData"},{"type":"text","text":" will be used."},{"type":"text","text":" "},{"type":"text","text":"Note this options is not compatible with "},{"type":"codeVoice","code":"SDImageCacheDecodeFirstFrameOnly"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/matchAnimatedImageClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheMatchAnimatedImageClass"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/matchanimatedimageclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/queryMemoryData":{"role":"symbol","title":"queryMemoryData","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, we do not query image data when the image is already cached in memory. This mask can force to query image data at the same time. However, this query is asynchronously unless you specify "},{"type":"codeVoice","code":"SDImageCacheQueryMemoryDataSync"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryMemoryData"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/querymemorydata"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/optionset-implementations"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/avoidDecodeImage":{"role":"symbol","title":"avoidDecodeImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidDecodeImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation."},{"type":"text","text":" "},{"type":"text","text":"However, this process may increase the memory usage as well. If you are experiencing a issue due to excessive memory consumption, This flag can prevent decode the image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/avoidDecodeImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheAvoidDecodeImage"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/avoiddecodeimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"role":"symbol","title":"SDImageCacheOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheOptions"}],"abstract":[{"type":"text","text":"Image Cache Options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheOptions"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/decodeFirstFrameOnly":{"role":"symbol","title":"decodeFirstFrameOnly","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFirstFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, we decode the animated image. This flag can force decode the first frame only and produce the static image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/decodeFirstFrameOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheDecodeFirstFrameOnly"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/decodefirstframeonly"},"doc://com.dailymotion.SDWebImage/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s10SetAlgebraP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/avoidDecodeImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/matchAnimatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/preloadAllFrames","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryDiskDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryData","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/scaleDownLargeImages"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryDiskDataSync\/title","value":"SDImageCacheQueryDiskDataSync"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryDiskDataSync\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1preloadAllFrames\/title","value":"SDImageCachePreloadAllFrames"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1preloadAllFrames\/fragments","value":[{"kind":"identifier","text":"SDImageCachePreloadAllFrames"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1scaleDownLargeImages\/title","value":"SDImageCacheScaleDownLargeImages"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1scaleDownLargeImages\/fragments","value":[{"kind":"identifier","text":"SDImageCacheScaleDownLargeImages"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryMemoryDataSync\/title","value":"SDImageCacheQueryMemoryDataSync"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryMemoryDataSync\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1matchAnimatedImageClass\/title","value":"SDImageCacheMatchAnimatedImageClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1matchAnimatedImageClass\/fragments","value":[{"kind":"identifier","text":"SDImageCacheMatchAnimatedImageClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryMemoryData\/title","value":"SDImageCacheQueryMemoryData"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryMemoryData\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryMemoryData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1avoidDecodeImage\/title","value":"SDImageCacheAvoidDecodeImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1avoidDecodeImage\/fragments","value":[{"kind":"identifier","text":"SDImageCacheAvoidDecodeImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","value":"SDImageCacheOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments","value":[{"kind":"identifier","text":"SDImageCacheOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1decodeFirstFrameOnly\/title","value":"SDImageCacheDecodeFirstFrameOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1decodeFirstFrameOnly\/fragments","value":[{"kind":"identifier","text":"SDImageCacheDecodeFirstFrameOnly"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}