{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCopying","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"title":"SDImageCacheConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDImageCacheConfig","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheExpireType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheReadingOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheWritingOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/fileManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/ioQueueAttributes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxDiskAge","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxDiskSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCost","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/memoryCacheClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldCacheImagesInMemory","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldDisableiCloud","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenEnterBackground","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenTerminate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldUseWeakMemoryCache"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/default"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/shouldUseWeakMemoryCache":{"role":"symbol","title":"shouldUseWeakMemoryCache","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldUseWeakMemoryCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldUseWeakMemoryCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldUseWeakMemoryCache"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/shoulduseweakmemorycache"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/default":{"role":"symbol","title":"default","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"}],"abstract":[{"type":"text","text":"Gets the default cache config used for shared instance or initialization when it does not provide any cache config. Such as "},{"type":"codeVoice","code":"SDImageCache.sharedImageCache"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/default"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/maxMemoryCount":{"role":"symbol","title":"maxMemoryCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum number of objects in-memory image cache should hold."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 0. Which means there is no memory count limit."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxMemoryCount"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycount"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/maxDiskSize":{"role":"symbol","title":"maxDiskSize","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDiskSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum size of the disk cache, in bytes."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 0. Which means there is no cache size limit."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxDiskSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxDiskSize"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/maxdisksize"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/fileManager":{"role":"symbol","title":"fileManager","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fileManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"FileManager","preciseIdentifier":"c:objc(cs)NSFileManager"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The custom file manager for disk cache. Pass nil to let disk cache choose the proper file manager."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/fileManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fileManager"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/filemanager"},"doc://com.dailymotion.SDWebImage/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCopying"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/maxMemoryCost":{"role":"symbol","title":"maxMemoryCost","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxMemoryCost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"The maximum “total cost” of the in-memory image cache. The cost function is the bytes size held in memory."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCost","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxMemoryCost"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/maxmemorycost"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheWritingOptions":{"role":"symbol","title":"diskCacheWritingOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheWritingOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"WritingOptions","preciseIdentifier":"c:@E@NSDataWritingOptions"}],"abstract":[{"type":"text","text":"The writing options while writing cache to disk."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"NSDataWritingAtomic"},{"type":"text","text":". You can set this to "},{"type":"codeVoice","code":"NSDataWritingWithoutOverwriting"},{"type":"text","text":" to prevent overwriting an existing file."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheWritingOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"diskCacheWritingOptions"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachewritingoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheReadingOptions":{"role":"symbol","title":"diskCacheReadingOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheReadingOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSData","preciseIdentifier":"c:objc(cs)NSData"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"ReadingOptions","preciseIdentifier":"c:@E@NSDataReadingOptions"}],"abstract":[{"type":"text","text":"The reading options while reading cache from disk."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 0. You can set this to "},{"type":"codeVoice","code":"NSDataReadingMappedIfSafe"},{"type":"text","text":" to improve performance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheReadingOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"diskCacheReadingOptions"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcachereadingoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/shouldCacheImagesInMemory":{"role":"symbol","title":"shouldCacheImagesInMemory","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldCacheImagesInMemory"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to use memory cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldCacheImagesInMemory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldCacheImagesInMemory"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/shouldcacheimagesinmemory"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/shouldRemoveExpiredDataWhenTerminate":{"role":"symbol","title":"shouldRemoveExpiredDataWhenTerminate","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRemoveExpiredDataWhenTerminate"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to remove the expired disk data when application been terminated. This operation is processed in sync to ensure clean up."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenTerminate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldRemoveExpiredDataWhenTerminate"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/shouldremoveexpireddatawhenterminate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheClass":{"role":"symbol","title":"diskCacheClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[{"type":"text","text":"The custom disk cache class. Provided class instance must conform to "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol to allow usage."},{"type":"text","text":" "},{"type":"text","text":"Defaults to built-in "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"diskCacheClass"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcacheclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/maxDiskAge":{"role":"symbol","title":"maxDiskAge","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxDiskAge"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The maximum length of time to keep an image in the disk cache, in seconds."},{"type":"text","text":" "},{"type":"text","text":"Setting this to a negative value means no expiring."},{"type":"text","text":" "},{"type":"text","text":"Setting this to zero means that all cached files would be removed when do expiration check."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 1 week."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxDiskAge","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxDiskAge"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/maxdiskage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/shouldDisableiCloud":{"role":"symbol","title":"shouldDisableiCloud","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldDisableiCloud"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to disable iCloud backup"},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldDisableiCloud","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldDisableiCloud"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/shoulddisableicloud"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/ioQueueAttributes":{"role":"symbol","title":"ioQueueAttributes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"ioQueueAttributes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"__OS_dispatch_queue_attr"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The dispatch queue attr for ioQueue. You can config the QoS and concurrent\/serial to internal IO queue. The ioQueue is used by SDImageCache to access read\/write for disk data."},{"type":"text","text":" "},{"type":"text","text":"Defaults we use "},{"type":"codeVoice","code":"DISPATCH_QUEUE_SERIAL"},{"type":"text","text":"(NULL), to use serial dispatch queue to ensure single access for disk data. It’s safe but may be slow."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/ioQueueAttributes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"ioQueueAttributes"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/ioqueueattributes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","title":"SDImageCacheConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/diskCacheExpireType":{"role":"symbol","title":"diskCacheExpireType","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskCacheExpireType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfigExpireType","preciseIdentifier":"c:@E@SDImageCacheConfigExpireType"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheExpireType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"diskCacheExpireType"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/diskcacheexpiretype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/shouldRemoveExpiredDataWhenEnterBackground":{"role":"symbol","title":"shouldRemoveExpiredDataWhenEnterBackground","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldRemoveExpiredDataWhenEnterBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether or not to remove the expired disk data when application entering the background. (Not works for macOS)"},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenEnterBackground","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldRemoveExpiredDataWhenEnterBackground"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/shouldremoveexpireddatawhenenterbackground"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig/memoryCacheClass":{"role":"symbol","title":"memoryCacheClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"memoryCacheClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"}],"abstract":[{"type":"text","text":"The custom memory cache class. Provided class instance must conform to "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" protocol to allow usage."},{"type":"text","text":" "},{"type":"text","text":"Defaults to built-in "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" class."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/memoryCacheClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"memoryCacheClass"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfig\/memorycacheclass"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheExpireType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheReadingOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/diskCacheWritingOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/fileManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/ioQueueAttributes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxDiskAge","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxDiskSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCost","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/maxMemoryCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/memoryCacheClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldCacheImagesInMemory","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldDisableiCloud","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenEnterBackground","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldRemoveExpiredDataWhenTerminate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/shouldUseWeakMemoryCache"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig\/default"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldUseWeakMemoryCache\/title","value":"shouldUseWeakMemoryCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldUseWeakMemoryCache\/fragments","value":[{"kind":"identifier","text":"shouldUseWeakMemoryCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1default\/title","value":"defaultCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1default\/fragments","value":[{"kind":"identifier","text":"defaultCacheConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCount\/title","value":"maxMemoryCount"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCount\/fragments","value":[{"kind":"identifier","text":"maxMemoryCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxDiskSize\/title","value":"maxDiskSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxDiskSize\/fragments","value":[{"kind":"identifier","text":"maxDiskSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1fileManager\/title","value":"fileManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1fileManager\/fragments","value":[{"kind":"identifier","text":"fileManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCost\/title","value":"maxMemoryCost"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxMemoryCost\/fragments","value":[{"kind":"identifier","text":"maxMemoryCost"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheWritingOptions\/title","value":"diskCacheWritingOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheWritingOptions\/fragments","value":[{"kind":"identifier","text":"diskCacheWritingOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheReadingOptions\/title","value":"diskCacheReadingOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheReadingOptions\/fragments","value":[{"kind":"identifier","text":"diskCacheReadingOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldCacheImagesInMemory\/title","value":"shouldCacheImagesInMemory"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldCacheImagesInMemory\/fragments","value":[{"kind":"identifier","text":"shouldCacheImagesInMemory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldRemoveExpiredDataWhenTerminate\/title","value":"shouldRemoveExpiredDataWhenTerminate"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldRemoveExpiredDataWhenTerminate\/fragments","value":[{"kind":"identifier","text":"shouldRemoveExpiredDataWhenTerminate"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheClass\/title","value":"diskCacheClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheClass\/fragments","value":[{"kind":"identifier","text":"diskCacheClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxDiskAge\/title","value":"maxDiskAge"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1maxDiskAge\/fragments","value":[{"kind":"identifier","text":"maxDiskAge"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldDisableiCloud\/title","value":"shouldDisableiCloud"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldDisableiCloud\/fragments","value":[{"kind":"identifier","text":"shouldDisableiCloud"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1ioQueueAttributes\/title","value":"ioQueueAttributes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1ioQueueAttributes\/fragments","value":[{"kind":"identifier","text":"ioQueueAttributes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title","value":"SDImageCacheConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheExpireType\/title","value":"diskCacheExpireType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1diskCacheExpireType\/fragments","value":[{"kind":"identifier","text":"diskCacheExpireType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldRemoveExpiredDataWhenEnterBackground\/title","value":"shouldRemoveExpiredDataWhenEnterBackground"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1shouldRemoveExpiredDataWhenEnterBackground\/fragments","value":[{"kind":"identifier","text":"shouldRemoveExpiredDataWhenEnterBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1memoryCacheClass\/title","value":"memoryCacheClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig~1memoryCacheClass\/fragments","value":[{"kind":"identifier","text":"memoryCacheClass"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}