{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageScaleFactorForKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagescalefactorforkey(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagescalefactorforkey(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleFactorForKey(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Return the image scale factor for the specify key, supports file name and url key."},{"type":"text","text":" "},{"type":"text","text":"This is the built-in way to check the scale factor when we have no context about it. Because scale factor is not stored in image data (It’s typically from filename)."},{"type":"text","text":" "},{"type":"text","text":"However, you can also provide custom scale factor as well, see "},{"type":"codeVoice","code":"SDWebImageContextImageScaleFactor"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageScaleFactorForKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"SDImageScaleFactorForKey(_:)","roleHeading":"Function","role":"symbol","symbolKind":"func","externalID":"c:@F@SDImageScaleFactorForKey","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageScaleFactorForKey"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageScaleFactorForKey(_:)":{"role":"symbol","title":"SDImageScaleFactorForKey(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageScaleFactorForKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"abstract":[{"type":"text","text":"Return the image scale factor for the specify key, supports file name and url key."},{"type":"text","text":" "},{"type":"text","text":"This is the built-in way to check the scale factor when we have no context about it. Because scale factor is not stored in image data (It’s typically from filename)."},{"type":"text","text":" "},{"type":"text","text":"However, you can also provide custom scale factor as well, see "},{"type":"codeVoice","code":"SDWebImageContextImageScaleFactor"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageScaleFactorForKey(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageScaleFactorForKey"}],"url":"\/documentation\/sdwebimage\/sdimagescalefactorforkey(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","path":"\/metadata\/title","value":"SDImageScaleFactorForKey"},{"op":"replace","path":"\/metadata\/symbolKind","value":"func"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageScaleFactorForKey"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"c:@T@CGFloat"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageScaleFactorForKey"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"internalParam","text":"key"},{"kind":"text","text":")"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleFactorForKey(_:)\/title","value":"SDImageScaleFactorForKey"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageScaleFactorForKey(_:)\/fragments","value":[{"kind":"identifier","text":"SDImageScaleFactorForKey"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}