{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachetype"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image Cache Type"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"}],"title":"SDImageCacheType","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@SDImageCacheType","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/all","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/disk","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/memory","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/none"]},{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/disk":{"role":"symbol","title":"SDImageCacheType.disk","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"disk"}],"abstract":[{"type":"text","text":"For query and contains op in response, means the image was obtained from the disk cache."},{"type":"text","text":" "},{"type":"text","text":"For op in request, means process only disk cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/disk","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeDisk"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype\/disk"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachetype\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachetype\/rawrepresentable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType":{"role":"symbol","title":"SDImageCacheType","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"}],"abstract":[{"type":"text","text":"Image Cache Type"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheType"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/memory":{"role":"symbol","title":"SDImageCacheType.memory","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"memory"}],"abstract":[{"type":"text","text":"For query and contains op in response, means the image was obtained from the memory cache."},{"type":"text","text":" "},{"type":"text","text":"For op in request, means process only memory cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/memory","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeMemory"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype\/memory"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/none":{"role":"symbol","title":"SDImageCacheType.none","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"none"}],"abstract":[{"type":"text","text":"For query and contains op in response, means the image isn’t available in the image cache"},{"type":"text","text":" "},{"type":"text","text":"For op in request, this type is not available and take no effect."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/none","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeNone"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype\/none"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachetype\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheType/all":{"role":"symbol","title":"SDImageCacheType.all","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"all"}],"abstract":[{"type":"text","text":"For query and contains op in response, this type is not available and take no effect."},{"type":"text","text":" "},{"type":"text","text":"For op in request, means process both memory cache and disk cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/all","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheTypeAll"}],"url":"\/documentation\/sdwebimage\/sdimagecachetype\/all"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/all","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/disk","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/memory","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheType\/none"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSInteger","preciseIdentifier":"c:@T@NSInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1disk\/title","value":"SDImageCacheTypeDisk"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1disk\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeDisk"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/title","value":"SDImageCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType\/fragments","value":[{"kind":"identifier","text":"SDImageCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1memory\/title","value":"SDImageCacheTypeMemory"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1memory\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeMemory"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1none\/title","value":"SDImageCacheTypeNone"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1none\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeNone"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1all\/title","value":"SDImageCacheTypeAll"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheType~1all\/fragments","value":[{"kind":"identifier","text":"SDImageCacheTypeAll"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}