{"abstract":[{"type":"text","text":"Pipeline transformer. Which you can bind multiple transformers together to let the image to be transformed one by one in order and generate the final image."}],"relationshipsSections":[{"title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","type":"conformsTo"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/init(transformers:)"],"generated":true},{"title":"Instance Properties","anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/preserveImageMetadata","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/transformers"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","interfaceLanguage":"swift"},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagepipelinetransformer"]}],"metadata":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImagePipelineTransformer","kind":"identifier"}],"externalID":"c:objc(cs)SDImagePipelineTransformer","navigatorTitle":[{"kind":"identifier","text":"SDImagePipelineTransformer"}],"title":"SDImagePipelineTransformer","modules":[{"name":"SDWebImage"}],"roleHeading":"Class","symbolKind":"class"},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImagePipelineTransformer"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"anchor":"overview","text":"Overview","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"Because transformers are lightweight, if you want to append or arrange transformers, create another pipeline transformer instead. This class is considered as immutable."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer/transformers":{"kind":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transformers"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageTransformer","kind":"typeIdentifier","text":"SDImageTransformer"},{"kind":"text","text":"]"}],"url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer\/transformers","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/transformers","abstract":[{"type":"text","text":"All transformers in pipeline"}],"title":"transformers","type":"topic","navigatorTitle":[{"text":"transformers","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","type":"unresolvable","title":"NSObject"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer/init(transformers:)":{"title":"init(transformers:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"transformers"},{"text":": [any ","kind":"text"},{"text":"SDImageTransformer","preciseIdentifier":"c:objc(pl)SDImageTransformer","kind":"typeIdentifier"},{"kind":"text","text":"])"}],"type":"topic","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/init(transformers:)","navigatorTitle":[{"kind":"identifier","text":"transformerWithTransformers:"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer\/init(transformers:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer/preserveImageMetadata":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer\/preserveimagemetadata","title":"preserveImageMetadata","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/preserveImageMetadata","navigatorTitle":[{"text":"preserveImageMetadata","kind":"identifier"}],"type":"topic","abstract":[{"text":"For pipeline transformer, this property is readonly and always return NO. We handle each transformer’s choice inside implementation","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preserveImageMetadata","kind":"identifier"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImagePipelineTransformer","kind":"identifier"}],"type":"topic","title":"SDImagePipelineTransformer","abstract":[{"text":"Pipeline transformer. Which you can bind multiple transformers together to let the image to be transformed one by one in order and generate the final image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer","kind":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SDImagePipelineTransformer"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImagePipelineTransformer"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/preserveImageMetadata","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/transformers"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Type-Methods","title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer\/init(transformers:)"]}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"],"type":"conformsTo"}],"op":"replace"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImagePipelineTransformer"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","value":"SDImageTransformer","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageTransformer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageTransformer"}]},{"value":"transformers","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1transformers\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1transformers\/fragments","value":[{"text":"transformers","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1init(transformers:)\/title","value":"transformerWithTransformers:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1init(transformers:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithTransformers:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1preserveImageMetadata\/title","value":"preserveImageMetadata","op":"replace"},{"value":[{"text":"preserveImageMetadata","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer~1preserveImageMetadata\/fragments"},{"value":"SDImagePipelineTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/fragments","value":[{"kind":"identifier","text":"SDImagePipelineTransformer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImagePipelineTransformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}