{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the image cache protocol to provide custom image cache for "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Though the best practice to custom image cache, is to write your own class which conform "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol for "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"However, if your own cache implementation contains more advanced feature beyond "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like "},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"}],"title":"SDImageCacheProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDImageCache","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/clear(with:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/containsImage(forKey:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/removeImage(forKey:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:options:context:cacheType:completion:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/store(_:imageData:forKey:cacheType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"storeImage:imageData:forKey:cacheType:completion:"}],"deprecated":true,"role":"symbol","title":"store(_:imageData:forKey:cacheType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Store the image into image cache for the given key. If cache type is memory only, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:cacheType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/store(_:imagedata:forkey:cachetype:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/store(_:imageData:forKey:options:context:cacheType:completion:)":{"role":"symbol","title":"store(_:imageData:forKey:options:context:cacheType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"imageData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Store the image into image cache for the given key. If cache type is memory only, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:options:context:cacheType:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"storeImage:imageData:forKey:options:context:cacheType:completion:"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/store(_:imagedata:forkey:options:context:cachetype:completion:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"role":"symbol","title":"SDImageCachesManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCachesManager"}],"abstract":[{"type":"text","text":"A caches manager to manage multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/queryImage(forKey:options:context:cacheType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"queryImageForKey:options:context:cacheType:completion:"}],"role":"symbol","title":"queryImage(forKey:options:context:cacheType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheQueryCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Query the cached image from image cache for given key. The operation can be used to cancel the query."},{"type":"text","text":" "},{"type":"text","text":"If image is cached in memory, completion is called synchronously, else asynchronously and depends on the options arg (See "},{"type":"codeVoice","code":"SDWebImageQueryDiskSync"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:cacheType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/queryimage(forkey:options:context:cachetype:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/removeImage(forKey:cacheType:completion:)":{"deprecated":true,"role":"symbol","title":"removeImage(forKey:cacheType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Remove the image from image cache for the given key. If cache type is memory only, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/removeImage(forKey:cacheType:completion:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeImageForKey:cacheType:completion:"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/removeimage(forkey:cachetype:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/clear(with:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"clearWithCacheType:completion:"}],"deprecated":true,"role":"symbol","title":"clear(with:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"clear"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Clear all the cached images for image cache. If cache type is memory only, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/clear(with:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/clear(with:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"role":"symbol","title":"SDImageCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCache"}],"abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"type":"text","text":"asynchronous so it doesn’t add unnecessary latency to the UI."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"role":"symbol","title":"SDImageCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"}],"abstract":[{"type":"text","text":"This is the image cache protocol to provide custom image cache for "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Though the best practice to custom image cache, is to write your own class which conform "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol for "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"However, if your own cache implementation contains more advanced feature beyond "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like "},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/containsImage(forKey:cacheType:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"containsImageForKey:cacheType:completion:"}],"deprecated":true,"role":"symbol","title":"containsImage(forKey:cacheType:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheType","preciseIdentifier":"c:@E@SDImageCacheType"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheContainsCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheContainsCompletionBlock"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Check if image cache contains the image for the given key (does not load the image). If image is cached in memory, completion is called synchronously, else asynchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/containsImage(forKey:cacheType:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/containsimage(forkey:cachetype:completion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol/queryImage(forKey:options:context:completion:)":{"navigatorTitle":[{"kind":"identifier","text":"queryImageForKey:options:context:completion:"}],"deprecated":true,"role":"symbol","title":"queryImage(forKey:options:context:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheQueryCompletionBlock","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Query the cached image from image cache for given key. The operation can be used to cancel the query."},{"type":"text","text":" "},{"type":"text","text":"If image is cached in memory, completion is called synchronously, else asynchronously and depends on the options arg (See "},{"type":"codeVoice","code":"SDWebImageQueryDiskSync"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:completion:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol\/queryimage(forkey:options:context:completion:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/clear(with:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/containsImage(forKey:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/queryImage(forKey:options:context:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/removeImage(forKey:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol\/store(_:imageData:forKey:options:context:cacheType:completion:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCache"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1store(_:imageData:forKey:cacheType:completion:)\/title","value":"storeImage:imageData:forKey:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1store(_:imageData:forKey:cacheType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeImage:imageData:forKey:cacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1store(_:imageData:forKey:options:context:cacheType:completion:)\/title","value":"storeImage:imageData:forKey:options:context:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1store(_:imageData:forKey:options:context:cacheType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeImage:imageData:forKey:options:context:cacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title","value":"SDImageCachesManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1queryImage(forKey:options:context:cacheType:completion:)\/title","value":"queryImageForKey:options:context:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1queryImage(forKey:options:context:cacheType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryImageForKey:options:context:cacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1removeImage(forKey:cacheType:completion:)\/title","value":"removeImageForKey:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1removeImage(forKey:cacheType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeImageForKey:cacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1clear(with:completion:)\/title","value":"clearWithCacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1clear(with:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearWithCacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1containsImage(forKey:cacheType:completion:)\/title","value":"containsImageForKey:cacheType:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1containsImage(forKey:cacheType:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"containsImageForKey:cacheType:completion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1queryImage(forKey:options:context:completion:)\/title","value":"queryImageForKey:options:context:completion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol~1queryImage(forKey:options:context:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryImageForKey:options:context:completion:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}