{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachecheckcompletionblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachecheckcompletionblock"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheCheckCompletionBlock"},{"text":" = (","kind":"text"},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheCheckCompletionBlock"},"schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"modules":[{"name":"SDWebImage"}],"title":"SDImageCacheCheckCompletionBlock","symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheCheckCompletionBlock"}],"externalID":"c:SDImageCacheDefine.h@T@SDImageCacheCheckCompletionBlock","roleHeading":"Type Alias","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheCheckCompletionBlock":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheCheckCompletionBlock"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachecheckcompletionblock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheCheckCompletionBlock","kind":"symbol","abstract":[],"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"}],"title":"SDImageCacheCheckCompletionBlock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDImageCacheCheckCompletionBlock","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"}]},{"value":[{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"add","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"kind":"text","text":" "},{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCheckCompletionBlock\/title","value":"SDImageCacheCheckCompletionBlock","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCheckCompletionBlock\/fragments","value":[{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SDImageCacheCheckCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCheckCompletionBlock\/navigatorTitle"}]}]}