{"sections":[],"abstract":[{"type":"text","text":"These enum is used to represent the High Dynamic Range type during image encoding\/decoding."},{"type":"text","text":" "},{"type":"text","text":"There are alao other HDR type in history before ISO Standard (ISO 21496-1), including Google and Apple’s old OSs captured photos, but which is non-standard and we do not support."}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageHDRType"}]}],"kind":"declarations"}],"kind":"symbol","metadata":{"title":"SDImageHDRType","modules":[{"name":"SDWebImage"}],"externalID":"c:@E@SDImageHDRType","fragments":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageHDRType"}],"symbolKind":"enum","role":"symbol","roleHeading":"Enumeration","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRType"}]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagehdrtype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagehdrtype"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/ISOHDR","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/SDR","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/isoGainMap"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true},{"title":"Initializers","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/init(rawValue:)"],"anchor":"Initializers"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/RawRepresentable-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/isoGainMap":{"abstract":[{"text":"ISO Gain Map based HDR (supported by nearly all format, including tranditional JPEG, which stored the gain map into XMP)","type":"text"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"isoGainMap"}],"kind":"symbol","title":"SDImageHDRType.isoGainMap","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/isogainmap","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/isoGainMap","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRTypeISOGainMap"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/SDR":{"abstract":[{"type":"text","text":"SDR, mostly only 8 bits color per components, RGBA8"}],"title":"SDImageHDRType.SDR","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRTypeSDR"}],"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDR"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/SDR","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/sdr","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/Equatable-Implementations":{"abstract":[],"kind":"article","title":"Equatable Implementations","role":"collectionGroup","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/equatable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/Equatable-Implementations"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY","title":"Swift.RawRepresentable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype","role":"symbol","fragments":[{"text":"enum","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageHDRType","kind":"identifier"}],"title":"SDImageHDRType","navigatorTitle":[{"kind":"identifier","text":"SDImageHDRType"}],"abstract":[{"type":"text","text":"These enum is used to represent the High Dynamic Range type during image encoding\/decoding."},{"type":"text","text":" "},{"type":"text","text":"There are alao other HDR type in history before ISO Standard (ISO 21496-1), including Google and Apple’s old OSs captured photos, but which is non-standard and we do not support."}]},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","title":"Swift.Sendable"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/ISOHDR":{"abstract":[{"type":"text","text":"ISO HDR (supported by modern format only, like HEIF\/AVIF\/JPEG-XL)"}],"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"ISOHDR","kind":"identifier"}],"kind":"symbol","title":"SDImageHDRType.ISOHDR","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/isohdr","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/ISOHDR","navigatorTitle":[{"text":"SDImageHDRTypeISOHDR","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/RawRepresentable-Implementations":{"abstract":[],"title":"RawRepresentable Implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/RawRepresentable-Implementations","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/rawrepresentable-implementations","kind":"article","role":"collectionGroup","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHDRType/init(rawValue:)":{"kind":"symbol","type":"topic","title":"init(rawValue:)","url":"\/documentation\/sdwebimage\/sdimagehdrtype\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"kind":"text","text":")"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/init(rawValue:)","abstract":[]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"value":"SDImageHDRType","op":"replace","path":"\/metadata\/title"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageHDRType","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageHDRType","kind":"identifier"}]},{"value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/ISOHDR","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/SDR","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHDRType\/isoGainMap"],"anchor":"Enumeration-Cases","title":"Enumeration Cases","generated":true}],"op":"replace","path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDImageHDRType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":";","kind":"text"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1isoGainMap\/title","value":"SDImageHDRTypeISOGainMap"},{"value":[{"kind":"identifier","text":"SDImageHDRTypeISOGainMap"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1isoGainMap\/fragments","op":"replace"},{"op":"replace","value":"SDImageHDRTypeSDR","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1SDR\/title"},{"value":[{"kind":"identifier","text":"SDImageHDRTypeSDR"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1SDR\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/title","value":"SDImageHDRType","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageHDRType"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/fragments"},{"value":[{"text":"SDImageHDRType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1ISOHDR\/title","op":"replace","value":"SDImageHDRTypeISOHDR"},{"value":[{"kind":"identifier","text":"SDImageHDRTypeISOHDR"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHDRType~1ISOHDR\/fragments"}]}]}