{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"overview","level":2,"type":"heading","text":"Overview"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Note: the "},{"type":"codeVoice","code":"coders"},{"type":"text","text":" getter will return the coders in their reversed order"},{"type":"text","text":" "},{"type":"text","text":"Example:"}]},{"type":"unorderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"by default we internally set coders = "},{"type":"codeVoice","code":"IOCoder"},{"type":"text","text":", "},{"type":"codeVoice","code":"GIFCoder"},{"type":"text","text":", "},{"type":"codeVoice","code":"APNGCoder"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"calling "},{"type":"codeVoice","code":"coders"},{"type":"text","text":" will return "},{"type":"codeVoice","code":"@[IOCoder, GIFCoder, APNGCoder]"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"call "},{"type":"codeVoice","code":"[addCoder:[MyCrazyCoder new]]"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"calling "},{"type":"codeVoice","code":"coders"},{"type":"text","text":" now returns "},{"type":"codeVoice","code":"@[IOCoder, GIFCoder, APNGCoder, MyCrazyCoder]"}]}]}]},{"anchor":"Coders","level":2,"type":"heading","text":"Coders"},{"type":"paragraph","inlineContent":[{"type":"text","text":"A coder must conform to the "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" protocol or even to "},{"type":"codeVoice","code":"SDProgressiveImageCoder"},{"type":"text","text":" if it supports progressive decoding"},{"type":"text","text":" "},{"type":"text","text":"Conformance is important because that way, they will implement "},{"type":"codeVoice","code":"canDecodeFromData"},{"type":"text","text":" or "},{"type":"codeVoice","code":"canEncodeToFormat"},{"type":"text","text":" "},{"type":"text","text":"Those methods are called on each coder in the array (using the priority order) until one of them returns YES."},{"type":"text","text":" "},{"type":"text","text":"That means that coder can decode that data \/ encode to that format"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecodersmanager"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Global object holding the array of coders, so that we avoid passing them from object to object."},{"type":"text","text":" "},{"type":"text","text":"Uses a priority queue behind scenes, which means the latest added coders have the highest priority."},{"type":"text","text":" "},{"type":"text","text":"This is done so when encoding\/decoding something, we go through the list and ask each coder if they can handle the current data."},{"type":"text","text":" "},{"type":"text","text":"That way, users can add their custom coders while preserving our existing prebuilt ones"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"}],"title":"SDImageCodersManager","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDImageCodersManager","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCodersManager"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/coders"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/addCoder(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/removeCoder(_:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/shared"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCodersManager","preciseIdentifier":"c:objc(cs)SDImageCodersManager"}],"abstract":[{"type":"text","text":"Returns the global shared coders manager instance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/shared"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/removeCoder(_:)":{"role":"symbol","title":"removeCoder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCoder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Remove a coder in the coders array."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/removeCoder(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"removeCoder:"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/removecoder(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"role":"symbol","title":"SDImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom image decoding\/encoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/coders":{"role":"symbol","title":"coders","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"coders"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"All coders in coders manager. The coders array is a priority queue, which means the later added coder will have the highest priority"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/coders","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"coders"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/coders"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager":{"role":"symbol","title":"SDImageCodersManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"}],"abstract":[{"type":"text","text":"Global object holding the array of coders, so that we avoid passing them from object to object."},{"type":"text","text":" "},{"type":"text","text":"Uses a priority queue behind scenes, which means the latest added coders have the highest priority."},{"type":"text","text":" "},{"type":"text","text":"This is done so when encoding\/decoding something, we go through the list and ask each coder if they can handle the current data."},{"type":"text","text":" "},{"type":"text","text":"That way, users can add their custom coders while preserving our existing prebuilt ones"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCodersManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager/addCoder(_:)":{"role":"symbol","title":"addCoder(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCoder"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDImageCoder","preciseIdentifier":"c:objc(pl)SDImageCoder"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add a new coder to the end of coders array. Which has the highest priority."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/addCoder(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCoder:"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager\/addcoder(_:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCodersManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCodersManager"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCodersManager"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/coders","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/shared"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/addCoder(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager\/removeCoder(_:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1shared\/title","value":"sharedManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1shared\/fragments","value":[{"kind":"identifier","text":"sharedManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1removeCoder(_:)\/title","value":"removeCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1removeCoder(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeCoder:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments","value":[{"kind":"identifier","text":"SDImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1coders\/title","value":"coders"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1coders\/fragments","value":[{"kind":"identifier","text":"coders"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/title","value":"SDImageCodersManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/fragments","value":[{"kind":"identifier","text":"SDImageCodersManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1addCoder(_:)\/title","value":"addCoder:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager~1addCoder(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCoder:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}