{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageloader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageloader"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself."},{"type":"text","text":" "},{"type":"text","text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call "},{"type":"codeVoice","code":"SDImageLoaderDecodeImageData"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDImageLoaderDecodeProgressiveImageData"},{"type":"text","text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block."},{"type":"text","text":" "},{"type":"text","text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoader"}],"title":"SDImageLoader","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDImageLoader","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/requestImage(with:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:options:context:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"role":"symbol","title":"SDWebImageDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloader"}],"abstract":[{"type":"text","text":"Asynchronous downloader dedicated and optimized for image loading."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloader"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/shouldBlockFailedURL(with:error:options:context:)":{"role":"symbol","title":"shouldBlockFailedURL(with:error:options:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBlockFailedURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the error from image loader should be marked indeed un-recoverable or not, with associated options and context."},{"type":"text","text":" "},{"type":"text","text":"If this return YES, failed URL which does not using "},{"type":"codeVoice","code":"SDWebImageRetryFailed"},{"type":"text","text":" will be blocked into black list. Else not."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:options:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:options:context:"}],"url":"\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:options:context:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/requestImage(with:options:context:progress:completed:)":{"navigatorTitle":[{"kind":"identifier","text":"requestImageWithURL:options:context:progress:completed:"}],"role":"symbol","title":"requestImage(with:options:context:progress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageLoaderCompletedBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderCompletedBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Load the image and image data with the given URL and return the image data. You’re responsible for producing the image instance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/requestImage(with:options:context:progress:completed:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimageloader\/requestimage(with:options:context:progress:completed:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/canRequestImage(for:options:context:)":{"role":"symbol","title":"canRequestImage(for:options:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether current image loader supports to load the provide image URL, with associated options and context."},{"type":"text","text":" "},{"type":"text","text":"This will be checked every time a new image request come for loader. If this return NO, we will mark this image load as failed. If return YES, we will start to call "},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:options:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"canRequestImageForURL:options:context:"}],"url":"\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:options:context:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"role":"symbol","title":"SDImageLoader","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoader"}],"abstract":[{"type":"text","text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself."},{"type":"text","text":" "},{"type":"text","text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call "},{"type":"codeVoice","code":"SDImageLoaderDecodeImageData"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDImageLoaderDecodeProgressiveImageData"},{"type":"text","text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block."},{"type":"text","text":" "},{"type":"text","text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"url":"\/documentation\/sdwebimage\/sdimageloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager":{"role":"symbol","title":"SDImageLoadersManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoadersManager"}],"abstract":[{"type":"text","text":"A loaders manager to manage multiple loaders"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageLoadersManager"}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/canRequestImage(for:)":{"navigatorTitle":[{"kind":"identifier","text":"canRequestImageForURL:"}],"deprecated":true,"role":"symbol","title":"canRequestImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether current image loader supports to load the provide image URL."},{"type":"text","text":" "},{"type":"text","text":"This will be checked every time a new image request come for loader. If this return NO, we will mark this image load as failed. If return YES, we will start to call "},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/shouldBlockFailedURL(with:error:)":{"navigatorTitle":[{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:"}],"deprecated":true,"role":"symbol","title":"shouldBlockFailedURL(with:error:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"shouldBlockFailedURL"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":", "},{"kind":"externalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the error from image loader should be marked indeed un-recoverable or not."},{"type":"text","text":" "},{"type":"text","text":"If this return YES, failed URL which does not using "},{"type":"codeVoice","code":"SDWebImageRetryFailed"},{"type":"text","text":" will be blocked into black list. Else not."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDImageLoader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageLoader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageLoader"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/requestImage(with:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:options:context:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoader"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title","value":"SDWebImageDownloader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:options:context:)\/title","value":"shouldBlockFailedURLWithURL:error:options:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:options:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:options:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1requestImage(with:options:context:progress:completed:)\/title","value":"requestImageWithURL:options:context:progress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1requestImage(with:options:context:progress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"requestImageWithURL:options:context:progress:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:options:context:)\/title","value":"canRequestImageForURL:options:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:options:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canRequestImageForURL:options:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"kind":"identifier","text":"SDImageLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/title","value":"SDImageLoadersManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/fragments","value":[{"kind":"identifier","text":"SDImageLoadersManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:)\/title","value":"canRequestImageForURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canRequestImageForURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:)\/title","value":"shouldBlockFailedURLWithURL:error:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}