{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderoption"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderoption"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/init(rawValue:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeFileExtensionHint","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodePreserveAspectRatio","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeScaleDownLimitBytes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeScaleFactor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeThumbnailPixelSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeToHDR","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeTypeIdentifierHint","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeUseLazyDecoding","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeBackgroundColor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeCompressionQuality","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeEmbedThumbnail","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeMaxFileSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeMaxPixelSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeToHDR","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/webImageContext"],"generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/_SwiftNewtypeWrapper-Implementations"],"title":"Default Implementations","anchor":"Default-Implementations","generated":true}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCoderOption"}],"externalID":"c:SDImageCoder.h@T@SDImageCoderOption","roleHeading":"Structure","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"SDImageCoderOption","symbolKind":"struct"},"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","type":"conformsTo"}],"sections":[],"references":{"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeEmbedThumbnail":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeEmbedThumbnail"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","abstract":[{"text":"A Boolean value indicating the encoding format should contains a thumbnail image into the output data. Only some of image format (like JPEG\/HEIF\/AVIF) support this behavior. The embed thumbnail will be used during next time thumbnail decoding (provided ","type":"text"},{"code":".thumbnailPixelSize","type":"codeVoice"},{"text":"), which is faster than full image thumbnail decoding. (NSNumber)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to NO, which does not embed any thumbnail."}],"navigatorTitle":[{"text":"SDImageCoderEncodeEmbedThumbnail","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodeembedthumbnail","title":"encodeEmbedThumbnail","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeEmbedThumbnail"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeFirstFrameOnly":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"decodeFirstFrameOnly","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","abstract":[{"text":"A Boolean value indicating whether to decode the first frame only for animated image during decoding. (NSNumber). If not provide, decode animated image if need.","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeFirstFrameOnly"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodefirstframeonly","title":"decodeFirstFrameOnly","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeFirstFrameOnly"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodePreserveAspectRatio":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodePreserveAspectRatio","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"title":"decodePreserveAspectRatio","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodepreserveaspectratio","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodePreserveAspectRatio","abstract":[{"type":"text","text":"A Boolean value indicating whether to keep the original aspect ratio when generating thumbnail images (or bitmap images from vector format)."},{"text":" ","type":"text"},{"text":"Defaults to YES.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeFileExtensionHint":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeFileExtensionHint","navigatorTitle":[{"text":"SDImageCoderDecodeFileExtensionHint","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeFileExtensionHint","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodefileextensionhint","abstract":[{"type":"text","text":"A NSString value indicating the source image’s file extension. Example: “jpg”, “nef”, “tif”, don’t prefix the dot"},{"text":" ","type":"text"},{"text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF","type":"text"},{"type":"text","text":" "},{"text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser","type":"text"}],"title":"decodeFileExtensionHint","type":"topic","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeThumbnailPixelSize":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeThumbnailPixelSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeThumbnailPixelSize"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeThumbnailPixelSize","abstract":[{"text":"A CGSize value indicating whether or not to generate the thumbnail images (or bitmap images from vector format). When this value is provided, the decoder will generate a thumbnail image which pixel size is smaller than or equal to (depends the ","type":"text"},{"code":".preserveAspectRatio","type":"codeVoice"},{"text":") the value size.","type":"text"},{"type":"text","text":" "},{"text":"Defaults to CGSizeZero, which means no thumbnail generation at all.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodethumbnailpixelsize","kind":"symbol","title":"decodeThumbnailPixelSize","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeScaleDownLimitBytes":{"navigatorTitle":[{"text":"SDImageCoderDecodeScaleDownLimitBytes","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","kind":"symbol","title":"decodeScaleDownLimitBytes","abstract":[{"type":"text","text":"A NSUInteger value to provide the limit bytes during decoding. This can help to avoid OOM on large frame count animated image or large pixel static image when you don’t know how much RAM it occupied before decoding"},{"text":" ","type":"text"},{"text":"The decoder will do these logic based on limit bytes:","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeScaleDownLimitBytes","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodescaledownlimitbytes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/_SwiftNewtypeWrapper-Implementations":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/_SwiftNewtypeWrapper-Implementations","type":"topic","title":"_SwiftNewtypeWrapper Implementations","kind":"article","role":"collectionGroup","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/_swiftnewtypewrapper-implementations","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeFirstFrameOnly":{"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeFirstFrameOnly"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeFirstFrameOnly"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodefirstframeonly","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeFirstFrameOnly","title":"encodeFirstFrameOnly","abstract":[{"text":"A Boolean value indicating whether to encode the first frame only for animated image during encoding. (NSNumber). If not provide, encode animated image if need.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeBackgroundColor":{"type":"topic","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeBackgroundColor","navigatorTitle":[{"text":"SDImageCoderEncodeBackgroundColor","kind":"identifier"}],"title":"encodeBackgroundColor","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodebackgroundcolor","abstract":[{"text":"A UIColor(NSColor) value to used for non-alpha image encoding when the input image has alpha channel, the background color will be used to compose the alpha one. If not provide, use white color.","type":"text"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"encodeBackgroundColor"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeMaxFileSize":{"role":"symbol","abstract":[{"text":"A NSUInteger value specify the max output data bytes size after encoding. Some lossy format like JPEG\/HEIF supports the hint for codec to automatically reduce the quality and match the file size you want. Note this option will override the ","type":"text"},{"code":"SDImageCoderEncodeCompressionQuality","type":"codeVoice"},{"text":", because now the quality is decided by the encoder. (NSNumber)","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeMaxFileSize"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier","text":"SDImageCoderOption"}],"title":"encodeMaxFileSize","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodemaxfilesize","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeMaxFileSize"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeMaxFileSize"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/Equatable-Implementations":{"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/equatable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/Equatable-Implementations","title":"Equatable Implementations","abstract":[],"kind":"article","role":"collectionGroup"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeMaxPixelSize":{"role":"symbol","abstract":[{"text":"A CGSize value indicating the max image resolution in pixels during encoding. For vector image, this also effect the output vector data information about width and height. The encoder will not generate the encoded image larger than this limit. Note it always use the aspect ratio of input image..","type":"text"},{"type":"text","text":" "},{"text":"Defaults to CGSizeZero, which means no max size limit at all.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeMaxPixelSize"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"encodeMaxPixelSize","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodemaxpixelsize","type":"topic","kind":"symbol","navigatorTitle":[{"text":"SDImageCoderEncodeMaxPixelSize","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeMaxPixelSize"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeTypeIdentifierHint":{"type":"topic","abstract":[{"type":"text","text":"A NSString value (UTI) indicating the source image’s file extension. Example: “public.jpeg-2000”, “com.nikon.raw-image”, “public.tiff”"},{"type":"text","text":" "},{"text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF","type":"text"},{"text":" ","type":"text"},{"text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodetypeidentifierhint","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeTypeIdentifierHint","navigatorTitle":[{"text":"SDImageCoderDecodeTypeIdentifierHint","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeTypeIdentifierHint"},{"kind":"text","text":": "},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"decodeTypeIdentifierHint","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeCompressionQuality":{"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderEncodeCompressionQuality"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"encodeCompressionQuality","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodecompressionquality","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeCompressionQuality","title":"encodeCompressionQuality","abstract":[{"text":"A double value between 0.0-1.0 indicating the encode compression quality to produce the image data. 1.0 resulting in no compression and 0.0 resulting in the maximum compression possible. If not provide, use 1.0. (NSNumber)","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeScaleFactor":{"role":"symbol","abstract":[{"text":"A CGFloat value which is greater than or equal to 1.0. This value specify the image scale factor for decoding. If not provide, use 1.0. (NSNumber)","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeScaleFactor"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"title":"decodeScaleFactor","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodescalefactor","type":"topic","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeScaleFactor"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeScaleFactor"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption":{"title":"SDImageCoderOption","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderoption","fragments":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoderOption"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"SDImageCoderOption","kind":"identifier"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeUseLazyDecoding":{"navigatorTitle":[{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeUseLazyDecoding"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","kind":"typeIdentifier","text":"SDImageCoderOption"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodeuselazydecoding","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeUseLazyDecoding","title":"decodeUseLazyDecoding","abstract":[{"text":"A BOOL value indicating whether to use lazy-decoding. Defaults to NO on animated image coder, but defaults to YES on static image coder.","type":"text"},{"text":" ","type":"text"},{"text":"CGImageRef, this image object typically support lazy-decoding, via the ","type":"text"},{"type":"codeVoice","code":"CGDataProviderCreateDirectAccess"},{"text":" or ","type":"text"},{"code":"CGDataProviderCreateSequential","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"Which allows you to provide a lazy-called callback to access bitmap buffer, so that you can achieve lazy-decoding when consumer actually need bitmap buffer"},{"text":" ","type":"text"},{"type":"text","text":"UIKit on iOS use heavy on this and ImageIO codec prefers to lazy-decoding for common Hardware-Accelerate format like JPEG\/PNG\/HEIC"},{"text":" ","type":"text"},{"text":"But however, the consumer may access bitmap buffer when running on main queue, like CoreAnimation layer render image. So this is a trade-off","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"You can force us to disable the lazy-decoding and always allocate bitmap buffer on RAM, but this may have higher ratio of OOM (out of memory)"}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/encodeToHDR":{"abstract":[{"text":"A NSUInteger (","type":"text"},{"type":"codeVoice","code":"SDImageHDRType.rawValue"},{"type":"text","text":") value (stored inside NSNumber) to provide converting to HDR during encoding. Read the below carefully to choose the value."}],"title":"encodeToHDR","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/encodetohdr","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodeToHDR"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption","text":"SDImageCoderOption"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/encodeToHDR","kind":"symbol","navigatorTitle":[{"text":"SDImageCoderEncodeToHDR","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/webImageContext":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/webImageContext","abstract":[{"text":"A SDWebImageContext object which hold the original context options from top-level API. (SDWebImageContext)","type":"text"},{"type":"text","text":" "},{"text":"This option is ignored for all built-in coders and take no effect.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"But this may be useful for some custom coders, because some business logic may dependent on things other than image or image data information only."},{"type":"text","text":" "},{"type":"text","text":"Only the unknown context from top-level API (See SDWebImageDefine.h) may be passed in during image loading."},{"type":"text","text":" "},{"type":"text","text":"See "},{"type":"codeVoice","code":"SDWebImageContext"},{"text":" for more detailed information.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/webimagecontext","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webImageContext","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageCoderOption","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"navigatorTitle":[{"text":"SDImageCoderWebImageContext","kind":"identifier"}],"deprecated":true,"kind":"symbol","title":"webImageContext","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/init(rawValue:)":{"abstract":[],"title":"init(rawValue:)","url":"\/documentation\/sdwebimage\/sdimagecoderoption\/init(rawvalue:)","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":")","kind":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/init(rawValue:)","kind":"symbol","type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderOption/decodeToHDR":{"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodeToHDR","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"}],"type":"topic","abstract":[{"type":"text","text":"A Boolean ("},{"type":"codeVoice","code":"SDImageHDRType.rawValue"},{"text":") value (stored inside NSNumber) to provide converting to HDR during decoding. Currently if number is 0 (","type":"text"},{"code":"SDImageHDRTypeSDR","type":"codeVoice"},{"type":"text","text":"), use SDR, else use HDR. But we may extend this option to represent "},{"type":"codeVoice","code":"SDImageHDRType"},{"text":" all cases in the future (means, think this options as uint number, but not actual boolean)","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderOption\/decodeToHDR","navigatorTitle":[{"text":"SDImageCoderDecodeToHDR","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderoption\/decodetohdr","kind":"symbol","title":"decodeToHDR","role":"symbol"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","value":"SDImageCoderOption","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"path":"\/metadata\/fragments","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCoderOption"}]},{"path":"\/topicSections","op":"replace","value":null},{"op":"replace","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SDImageCoderOption"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeEmbedThumbnail\/title","value":"SDImageCoderEncodeEmbedThumbnail"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeEmbedThumbnail\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderEncodeEmbedThumbnail"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeFirstFrameOnly\/title","value":"SDImageCoderDecodeFirstFrameOnly"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeFirstFrameOnly\/fragments","value":[{"text":"SDImageCoderDecodeFirstFrameOnly","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodePreserveAspectRatio\/title","value":"SDImageCoderDecodePreserveAspectRatio","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodePreserveAspectRatio\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodePreserveAspectRatio"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeFileExtensionHint\/title","op":"replace","value":"SDImageCoderDecodeFileExtensionHint"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeFileExtensionHint\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeFileExtensionHint"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeThumbnailPixelSize\/title","op":"replace","value":"SDImageCoderDecodeThumbnailPixelSize"},{"value":[{"kind":"identifier","text":"SDImageCoderDecodeThumbnailPixelSize"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeThumbnailPixelSize\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeScaleDownLimitBytes\/title","value":"SDImageCoderDecodeScaleDownLimitBytes"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeScaleDownLimitBytes\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeScaleDownLimitBytes"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeFirstFrameOnly\/title","op":"replace","value":"SDImageCoderEncodeFirstFrameOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeFirstFrameOnly\/fragments","value":[{"text":"SDImageCoderEncodeFirstFrameOnly","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeBackgroundColor\/title","value":"SDImageCoderEncodeBackgroundColor"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeBackgroundColor\/fragments","value":[{"kind":"identifier","text":"SDImageCoderEncodeBackgroundColor"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeMaxFileSize\/title","value":"SDImageCoderEncodeMaxFileSize","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeMaxFileSize\/fragments","op":"replace","value":[{"text":"SDImageCoderEncodeMaxFileSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeMaxPixelSize\/title","value":"SDImageCoderEncodeMaxPixelSize","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeMaxPixelSize\/fragments","value":[{"text":"SDImageCoderEncodeMaxPixelSize","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeTypeIdentifierHint\/title","op":"replace","value":"SDImageCoderDecodeTypeIdentifierHint"},{"op":"replace","value":[{"text":"SDImageCoderDecodeTypeIdentifierHint","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeTypeIdentifierHint\/fragments"},{"value":"SDImageCoderEncodeCompressionQuality","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeCompressionQuality\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SDImageCoderEncodeCompressionQuality"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeCompressionQuality\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeScaleFactor\/title","value":"SDImageCoderDecodeScaleFactor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeScaleFactor\/fragments","value":[{"kind":"identifier","text":"SDImageCoderDecodeScaleFactor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/title","value":"SDImageCoderOption"},{"value":[{"kind":"identifier","text":"SDImageCoderOption"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/fragments"},{"op":"replace","value":[{"text":"SDImageCoderOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeUseLazyDecoding\/title","value":"SDImageCoderDecodeUseLazyDecoding"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeUseLazyDecoding\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCoderDecodeUseLazyDecoding"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeToHDR\/title","value":"SDImageCoderEncodeToHDR"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1encodeToHDR\/fragments","value":[{"text":"SDImageCoderEncodeToHDR","kind":"identifier"}]},{"value":"SDImageCoderWebImageContext","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1webImageContext\/title","op":"replace"},{"op":"replace","value":[{"text":"SDImageCoderWebImageContext","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1webImageContext\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeToHDR\/title","value":"SDImageCoderDecodeToHDR"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderOption~1decodeToHDR\/fragments","value":[{"text":"SDImageCoderDecodeToHDR","kind":"identifier"}]}]}]}