{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"roleHeading":"Enumeration","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"title":"SDImageCacheConfigExpireType","externalID":"c:@E@SDImageCacheConfigExpireType","role":"symbol","symbolKind":"enum","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype"]}],"abstract":[{"type":"text","text":"Image Cache Expire Type"}],"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/accessDate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/changeDate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/creationDate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/modificationDate"],"anchor":"Enumeration-Cases","generated":true,"title":"Enumeration Cases"},{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/init(rawValue:)"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/RawRepresentable-Implementations"],"generated":true,"title":"Default Implementations","anchor":"Default-Implementations"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/Equatable-Implementations":{"title":"Equatable Implementations","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/equatable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/Equatable-Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/modificationDate":{"title":"SDImageCacheConfigExpireType.modificationDate","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/modificationdate","type":"topic","abstract":[{"text":"When the image cache is created or modified it will update this value (Default)","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/modificationDate","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireTypeModificationDate"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"case"},{"text":" ","kind":"text"},{"kind":"identifier","text":"modificationDate"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/changeDate":{"title":"SDImageCacheConfigExpireType.changeDate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/changeDate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"changeDate","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}],"abstract":[{"text":"When the image cache is created, modified, renamed, file attribute updated (like permission, xattr)  it will update this value","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/changedate","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/accessDate":{"fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"accessDate","kind":"identifier"}],"title":"SDImageCacheConfigExpireType.accessDate","abstract":[{"text":"When the image cache is accessed it will update this value","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/accessdate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/accessDate","role":"symbol","type":"topic","navigatorTitle":[{"text":"SDImageCacheConfigExpireTypeAccessDate","kind":"identifier"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY","title":"Swift.RawRepresentable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/init(rawValue:)":{"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"?("},{"text":"rawValue","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}],"title":"init(rawValue:)","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/init(rawvalue:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/init(rawValue:)","role":"symbol","type":"topic","kind":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/creationDate":{"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireTypeCreationDate"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/creationDate","abstract":[{"type":"text","text":"When the image cache is created it will update this value"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/creationdate","role":"symbol","title":"SDImageCacheConfigExpireType.creationDate","fragments":[{"text":"case","kind":"keyword"},{"text":" ","kind":"text"},{"text":"creationDate","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType/RawRepresentable-Implementations":{"title":"RawRepresentable Implementations","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype\/rawrepresentable-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/RawRepresentable-Implementations","role":"collectionGroup","type":"topic","kind":"article"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfigExpireType":{"type":"topic","role":"symbol","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType","url":"\/documentation\/sdwebimage\/sdimagecacheconfigexpiretype","abstract":[{"type":"text","text":"Image Cache Expire Type"}],"kind":"symbol","title":"SDImageCacheConfigExpireType","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheConfigExpireType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}]},{"op":"replace","value":[{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Enumeration-Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/accessDate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/changeDate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/creationDate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfigExpireType\/modificationDate"],"generated":true,"title":"Enumeration Cases"}]},{"value":null,"path":"\/relationshipsSections","op":"replace"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfigExpireType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SDImageCacheConfigExpireTypeModificationDate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1modificationDate\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1modificationDate\/fragments","op":"replace","value":[{"text":"SDImageCacheConfigExpireTypeModificationDate","kind":"identifier"}]},{"value":"SDImageCacheConfigExpireTypeChangeDate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1changeDate\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1changeDate\/fragments","op":"replace","value":[{"text":"SDImageCacheConfigExpireTypeChangeDate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1accessDate\/title","op":"replace","value":"SDImageCacheConfigExpireTypeAccessDate"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1accessDate\/fragments","value":[{"text":"SDImageCacheConfigExpireTypeAccessDate","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1creationDate\/title","value":"SDImageCacheConfigExpireTypeCreationDate"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType~1creationDate\/fragments","value":[{"text":"SDImageCacheConfigExpireTypeCreationDate","kind":"identifier"}]},{"op":"replace","value":"SDImageCacheConfigExpireType","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/title"},{"value":[{"text":"SDImageCacheConfigExpireType","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCacheConfigExpireType"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfigExpireType\/navigatorTitle"}]}]}