{"topicSections":[{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder\/shared"],"anchor":"Type-Properties"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageGIFCoder"}],"platforms":["iOS"]}]},{"content":[{"anchor":"overview","text":"Overview","level":2,"type":"heading"},{"type":"aside","style":"note","content":[{"type":"paragraph","inlineContent":[{"code":"SDImageIOCoder","type":"codeVoice"},{"type":"text","text":" supports GIF but only as static (will use the 1st frame)."}]}],"name":"Note"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Use "},{"code":"SDImageGIFCoder","type":"codeVoice"},{"text":" for fully animated GIFs. For ","type":"text"},{"code":"UIImageView","type":"codeVoice"},{"type":"text","text":", it will produce animated "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"("},{"code":"NSImage","type":"codeVoice"},{"text":" on macOS) for rendering. For ","type":"text"},{"code":"SDAnimatedImageView","type":"codeVoice"},{"type":"text","text":", it will use "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" for rendering."}]}],"type":"aside","style":"note","name":"Note"},{"name":"Note","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The recommended approach for animated GIFs is using "},{"code":"SDAnimatedImage","type":"codeVoice"},{"type":"text","text":" with "},{"code":"SDAnimatedImageView","type":"codeVoice"},{"type":"text","text":". It’s more performant than "},{"code":"UIImageView","type":"codeVoice"},{"type":"text","text":" for GIF displaying(especially on memory usage)"}]}],"type":"aside","style":"note"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagegifcoder"]},{"paths":["\/documentation\/sdwebimage\/sdimagegifcoder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"metadata":{"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageGIFCoder","title":"SDImageGIFCoder","symbolKind":"class","navigatorTitle":[{"text":"SDImageGIFCoder","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageGIFCoder","kind":"identifier"}],"role":"symbol","roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Built in coder using ImageIO that supports animated GIF encoding\/decoding"}],"sections":[],"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder","type":"topic","title":"SDImageIOAnimatedCoder","kind":"symbol","abstract":[{"text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"role":"symbol","navigatorTitle":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageGIFCoder":{"kind":"symbol","type":"topic","title":"SDImageGIFCoder","navigatorTitle":[{"text":"SDImageGIFCoder","kind":"identifier"}],"abstract":[{"text":"Built in coder using ImageIO that supports animated GIF encoding\/decoding","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","url":"\/documentation\/sdwebimage\/sdimagegifcoder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageGIFCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageGIFCoder/shared":{"url":"\/documentation\/sdwebimage\/sdimagegifcoder\/shared","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder\/shared","navigatorTitle":[{"text":"sharedCoder","kind":"identifier"}],"title":"shared","type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageGIFCoder","text":"SDImageGIFCoder"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"type":"topic","abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"code":"SDAnimatedImageCoder","type":"codeVoice"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"title":"SDAnimatedImageProvider"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"text":" ","type":"text"},{"text":"These methods are all required to implement.","type":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder","title":"SDProgressiveImageCoder","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"type":"topic","title":"SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder","navigatorTitle":[{"text":"SDImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the image coder protocol to provide custom image decoding\/encoding.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods are all required to implement."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDImageGIFCoder"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageGIFCoder","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageGIFCoder","kind":"identifier"}]},{"value":[{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder\/shared"],"anchor":"Type-Properties"}],"path":"\/topicSections","op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"title":"Inherits From","type":"inheritsFrom"},{"title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"],"type":"conformsTo","kind":"relationships"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SDImageGIFCoder","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"SDImageIOAnimatedCoder","preciseIdentifier":"c:objc(cs)SDImageIOAnimatedCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"value":"SDImageIOAnimatedCoder","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title"},{"value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/navigatorTitle","op":"replace","value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/title","value":"SDImageGIFCoder"},{"value":[{"text":"SDImageGIFCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/fragments"},{"value":[{"kind":"identifier","text":"SDImageGIFCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder~1shared\/title","value":"sharedCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder~1shared\/fragments","op":"replace","value":[{"kind":"identifier","text":"sharedCoder"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","op":"replace","value":"SDAnimatedImageCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}],"op":"replace"},{"op":"replace","value":"SDAnimatedImageProvider","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}]},{"value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title","value":"SDProgressiveImageCoder","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments","value":[{"text":"SDProgressiveImageCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},{"value":"SDImageCoder","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title"},{"op":"replace","value":[{"text":"SDImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/navigatorTitle"}]}]}