{"sections":[],"abstract":[{"type":"text","text":"Core Image filter transformer"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"topicSections":[{"anchor":"Initializers","generated":true,"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/init(filter:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/filter"],"anchor":"Instance-Properties","generated":true}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","kind":"relationships"}],"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageFilterTransformer","kind":"identifier"}]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagefiltertransformer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagefiltertransformer"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageFilterTransformer","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Class","symbolKind":"class","title":"SDImageFilterTransformer","externalID":"c:objc(cs)SDImageFilterTransformer","navigatorTitle":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer":{"kind":"symbol","navigatorTitle":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer","title":"SDImageFilterTransformer","abstract":[{"text":"Core Image filter transformer","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageFilterTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagebasetransformer","title":"SDImageBaseTransformer","abstract":[{"text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like ","type":"text"},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"text":") instead.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer/init(filter:)":{"kind":"symbol","navigatorTitle":[{"text":"transformerWithFilter:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer\/init(filter:)","title":"init(filter:)","abstract":[],"fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIFilter","preciseIdentifier":"c:objc(cs)CIFilter"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/init(filter:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer/filter":{"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"filter"},{"kind":"text","text":": "},{"text":"CIFilter","preciseIdentifier":"c:objc(cs)CIFilter","kind":"typeIdentifier"}],"navigatorTitle":[{"kind":"identifier","text":"filter"}],"title":"filter","kind":"symbol","abstract":[{"type":"text","text":"The CIFilter to be applied to the image."}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer\/filter","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/filter"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDImageFilterTransformer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageFilterTransformer"}],"op":"replace"},{"op":"replace","value":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":[{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/filter"],"generated":true},{"generated":true,"title":"Type Methods","anchor":"Type-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/init(filter:)"]}],"op":"replace","path":"\/topicSections"},{"value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"]}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SDImageFilterTransformer","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageBaseTransformer","text":"SDImageBaseTransformer","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","op":"replace","value":"SDImageTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/title","op":"replace","value":"SDImageFilterTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/fragments","value":[{"text":"SDImageFilterTransformer","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDImageFilterTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/navigatorTitle","op":"replace"},{"value":"SDImageBaseTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/title","op":"replace"},{"value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/navigatorTitle","value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer~1init(filter:)\/title","value":"transformerWithFilter:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer~1init(filter:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"transformerWithFilter:"}],"op":"replace"},{"value":"filter","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer~1filter\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer~1filter\/fragments","value":[{"text":"filter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}