{"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"kind":"symbol","metadata":{"roleHeading":"Class","role":"symbol","symbolKind":"class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCache"}],"title":"SDImageCache","externalID":"c:objc(cs)SDImageCache","navigatorTitle":[{"text":"SDImageCache","kind":"identifier"}],"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom"},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s8CopyableP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecache-swift.class"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","interfaceLanguage":"swift"},"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:config:)"],"anchor":"Initializers","generated":true,"title":"Initializers"},{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/additionalCachePathBlock","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/config","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskCachePath","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/memoryCache"],"title":"Instance Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/cachePath(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/calculateSize(completionBlock:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearDisk(onCompletion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearMemory()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/deleteOldFiles(completionBlock:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataExists(withKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataQuery(forKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageExists(withKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromDiskCache(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromDiskCache(forKey:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromMemoryCache(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:cacheType:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImage(forKey:fromDisk:withCompletion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImage(forKey:withCompletion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImageFromDisk(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImageFromMemory(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:toDisk:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:imageData:forKey:options:context:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:imageData:forKey:toDisk:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImage(toMemory:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImageData(_:forKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImageData(toDisk:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/totalDiskCount()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/totalDiskSize()"]},{"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/defaultDiskCacheDirectory","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/shared"],"generated":true}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/storeImageData(toDisk:forKey:)":{"type":"topic","abstract":[{"type":"text","text":"Synchronously store an image data into disk cache at the given key."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImageData(toDisk:forKey:)","title":"storeImageData(toDisk:forKey:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/storeimagedata(todisk:forkey:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"storeImageData","kind":"identifier"},{"kind":"text","text":"("},{"text":"toDisk","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"storeImageDataToDisk:forKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/store(_:imageData:forKey:toDisk:completion:)":{"abstract":[{"text":"Asynchronously store an image into memory and disk cache at the given key.","type":"text"}],"title":"store(_:imageData:forKey:toDisk:completion:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:imageData:forKey:toDisk:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"store"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"imageData","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"toDisk"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"kind":"text","text":", "},{"kind":"externalParam","text":"completion"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"storeImage:imageData:forKey:toDisk:completion:"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:imagedata:forkey:todisk:completion:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/clearDisk(onCompletion:)":{"title":"clearDisk(onCompletion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"clearDisk","kind":"identifier"},{"kind":"text","text":"("},{"text":"onCompletion","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearDiskOnCompletion:"}],"abstract":[{"type":"text","text":"Asynchronously clear all disk cached images. Non-blocking method - returns immediately."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearDisk(onCompletion:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/cleardisk(oncompletion:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskImageExists(withKey:completion:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageExists(withKey:completion:)","role":"symbol","navigatorTitle":[{"text":"diskImageExistsWithKey:completion:","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimageexists(withkey:completion:)","abstract":[{"text":"Asynchronously check if image exists in disk cache already (does not load the image)","type":"text"}],"title":"diskImageExists(withKey:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"diskImageExists","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"withKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDImageCacheCheckCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheCheckCompletionBlock"},{"text":"?)","kind":"text"}]},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/removeImageFromDisk(forKey:)":{"title":"removeImageFromDisk(forKey:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeImageFromDisk","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"removeImageFromDiskForKey:","kind":"identifier"}],"abstract":[{"type":"text","text":"Synchronously remove the image from disk cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImageFromDisk(forKey:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/removeimagefromdisk(forkey:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/totalDiskCount()":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/totaldiskcount()","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/totalDiskCount()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalDiskCount"},{"text":"() -> ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"}],"abstract":[{"text":"Get the number of images in the disk cache","type":"text"}],"title":"totalDiskCount()","navigatorTitle":[{"text":"totalDiskCount","kind":"identifier"}],"role":"symbol","type":"topic","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDImageCache"}],"kind":"symbol","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCache","kind":"identifier"}],"title":"SDImageCache","abstract":[{"type":"text","text":"SDImageCache maintains a memory cache and a disk cache. Disk cache write operations are performed"},{"type":"text","text":" "},{"text":"asynchronous so it doesn’t add unnecessary latency to the UI.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/defaultDiskCacheDirectory":{"type":"topic","abstract":[{"type":"text","text":"Control the default disk cache directory. This will effect all the SDImageCache instance created after modification, even for shared image cache."},{"text":" ","type":"text"},{"type":"text","text":"This can be used to share the same disk cache with the App and App Extension (Today\/Notification Widget) using "},{"type":"codeVoice","code":"- [NSFileManager.containerURLForSecurityApplicationGroupIdentifier:]"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/defaultDiskCacheDirectory","title":"defaultDiskCacheDirectory","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/defaultdiskcachedirectory","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultDiskCacheDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"defaultDiskCacheDirectory","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/memoryCache":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/memoryCache","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"memoryCache","kind":"identifier"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDMemoryCache","text":"SDMemoryCacheProtocol"}],"navigatorTitle":[{"text":"memoryCache","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/memorycache","title":"memoryCache","type":"topic","abstract":[{"type":"text","text":"The memory cache implementation object used for current image cache."},{"text":" ","type":"text"},{"type":"text","text":"By default we use "},{"type":"codeVoice","code":"SDMemoryCache"},{"text":" class, you can also use this to call your own implementation class method.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/imageFromMemoryCache(forKey:)":{"title":"imageFromMemoryCache(forKey:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageFromMemoryCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"imageFromMemoryCacheForKey:"}],"abstract":[{"type":"text","text":"Synchronously query the memory cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromMemoryCache(forKey:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefrommemorycache(forkey:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/imageFromDiskCache(forKey:options:context:)":{"title":"imageFromDiskCache(forKey:options:context:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromdiskcache(forkey:options:context:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imageFromDiskCache","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"imageFromDiskCacheForKey:options:context:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromDiskCache(forKey:options:context:)","abstract":[{"text":"Synchronously query the disk cache. With the options and context which may effect the image generation. (Such as transformer, animated image, thumbnail, etc)","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/store(_:forKey:completion:)":{"abstract":[{"text":"Asynchronously store an image into memory and disk cache at the given key.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"storeImage:forKey:completion:"}],"title":"store(_:forKey:completion:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:forkey:completion:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:completion:)","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"store"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskCache":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskCache","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"diskCache","kind":"identifier"},{"kind":"text","text":": any "},{"text":"SDDiskCacheProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDDiskCache"}],"navigatorTitle":[{"kind":"identifier","text":"diskCache"}],"title":"diskCache","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskcache","abstract":[{"type":"text","text":"The disk cache implementation object used for current image cache."},{"type":"text","text":" "},{"type":"text","text":"By default we use "},{"code":"SDMemoryCache","type":"codeVoice"},{"type":"text","text":" class, you can also use this to call your own implementation class method."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/removeImageFromMemory(forKey:)":{"title":"removeImageFromMemory(forKey:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeImageFromMemory"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"removeImageFromMemoryForKey:","kind":"identifier"}],"abstract":[{"type":"text","text":"Synchronously remove the image from memory cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImageFromMemory(forKey:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/removeimagefrommemory(forkey:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/init(namespace:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:)","kind":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"namespace"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"initWithNamespace:","kind":"identifier"}],"title":"init(namespace:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/init(namespace:)","abstract":[{"type":"text","text":"Init a new cache store with a specific namespace"},{"text":" ","type":"text"},{"type":"text","text":"The final disk cache directory should looks like ($directory\/$namespace). And the default config of shared cache, should result in (~\/Library\/Caches\/com.hackemist.SDImageCache\/default\/)"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/totalDiskSize()":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/totalDiskSize()","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"totalDiskSize","kind":"identifier"},{"kind":"text","text":"() -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"}],"navigatorTitle":[{"text":"totalDiskSize","kind":"identifier"}],"title":"totalDiskSize()","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/totaldisksize()","abstract":[{"type":"text","text":"Get the total bytes size of images in the disk cache"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/removeImage(forKey:withCompletion:)":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/removeimage(forkey:withcompletion:)","abstract":[{"type":"text","text":"Asynchronously remove the image from memory and disk cache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImage(forKey:withCompletion:)","title":"removeImage(forKey:withCompletion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"withCompletion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"removeImageForKey:withCompletion:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/imageFromCache(forKey:options:context:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:options:context:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageFromCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"imageFromCacheForKey:options:context:","kind":"identifier"}],"title":"imageFromCache(forKey:options:context:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromcache(forkey:options:context:)","abstract":[{"type":"text","text":"Synchronously query the cache (memory and or disk) after checking the memory cache. With the options and context which may effect the image generation. (Such as transformer, animated image, thumbnail, etc)"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:options:context:done:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"queryCacheOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"done"},{"kind":"text","text":": "},{"text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"queryCacheOperationForKey:options:context:done:","kind":"identifier"}],"type":"topic","role":"symbol","title":"queryCacheOperation(forKey:options:context:done:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:done:)","abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:done:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/removeImage(forKey:fromDisk:withCompletion:)":{"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeImage"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"text":"fromDisk","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"},{"text":", ","kind":"text"},{"text":"withCompletion","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"title":"removeImage(forKey:fromDisk:withCompletion:)","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImage(forKey:fromDisk:withCompletion:)","navigatorTitle":[{"text":"removeImageForKey:fromDisk:withCompletion:","kind":"identifier"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/removeimage(forkey:fromdisk:withcompletion:)","abstract":[{"type":"text","text":"Asynchronously remove the image from memory and optionally disk cache"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/cachePath(forKey:)":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/cachepath(forkey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/cachePath(forKey:)","abstract":[{"type":"text","text":"Get the cache path for a certain key"}],"title":"cachePath(forKey:)","navigatorTitle":[{"text":"cachePathForKey:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cachePath"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/clearMemory()":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/clearmemory()","title":"clearMemory()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearMemory"},{"kind":"text","text":"()"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"clearMemory"}],"abstract":[{"text":"Synchronously Clear all memory cached images","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearMemory()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:options:done:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:done:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheOperation"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"kind":"text","text":", "},{"text":"done","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"text":"SDImageCacheToken","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken"},{"kind":"text","text":"?"}],"navigatorTitle":[{"text":"queryCacheOperationForKey:options:done:","kind":"identifier"}],"title":"queryCacheOperation(forKey:options:done:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:done:)","abstract":[{"type":"text","text":"Asynchronously queries the cache with operation and call the completion when done."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/imageFromDiskCache(forKey:)":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromdiskcache(forkey:)","abstract":[{"type":"text","text":"Synchronously query the disk cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromDiskCache(forKey:)","title":"imageFromDiskCache(forKey:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageFromDiskCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"imageFromDiskCacheForKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheProtocol"}],"navigatorTitle":[{"text":"SDImageCacheProtocol","kind":"identifier"}],"abstract":[{"text":"This is the image cache protocol to provide custom image cache for ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Though the best practice to custom image cache, is to write your own class which conform ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"code":"SDDiskCache","type":"codeVoice"},{"type":"text","text":" protocol for "},{"code":"SDImageCache","type":"codeVoice"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"However, if your own cache implementation contains more advanced feature beyond ","type":"text"},{"code":"SDImageCache","type":"codeVoice"},{"text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like ","type":"text"},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"title":"SDImageCacheProtocol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskImageDataQuery(forKey:completion:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataQuery(forKey:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"diskImageDataQuery"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryDataCompletionBlock","text":"SDImageCacheQueryDataCompletionBlock","kind":"typeIdentifier"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"diskImageDataQueryForKey:completion:"}],"title":"diskImageDataQuery(forKey:completion:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimagedataquery(forkey:completion:)","abstract":[{"type":"text","text":"Asynchronously query the image data for the given key in disk cache. You can decode the image data to image after loaded."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskCachePath":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskCachePath","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"diskCachePath"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"navigatorTitle":[{"text":"diskCachePath","kind":"identifier"}],"type":"topic","abstract":[{"text":"The disk cache’s root path","type":"text"}],"role":"symbol","title":"diskCachePath","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskcachepath"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/storeImage(toMemory:forKey:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"storeImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"toMemory"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"kind":"identifier","text":"storeImageToMemory:forKey:"}],"title":"storeImage(toMemory:forKey:)","kind":"symbol","abstract":[{"type":"text","text":"Synchronously store an image into memory cache at the given key."}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/storeimage(tomemory:forkey:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImage(toMemory:forKey:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskImageDataExists(withKey:)":{"abstract":[{"type":"text","text":"Synchronously check if image data exists in disk cache already (does not load the image)"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"diskImageDataExistsWithKey:","kind":"identifier"}],"title":"diskImageDataExists(withKey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataExists(withKey:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimagedataexists(withkey:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"diskImageDataExists"},{"text":"(","kind":"text"},{"text":"withKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/calculateSize(completionBlock:)":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/calculatesize(completionblock:)","abstract":[{"type":"text","text":"Asynchronously calculate the disk cache’s size."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/calculateSize(completionBlock:)","title":"calculateSize(completionBlock:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"calculateSize","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"completionBlock"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheCalculateSizeBlock","kind":"typeIdentifier","text":"SDImageCacheCalculateSizeBlock"},{"text":"?)","kind":"text"}],"type":"topic","navigatorTitle":[{"text":"calculateSizeWithCompletionBlock:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/s8CopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8CopyableP","title":"Swift.Copyable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/store(_:forKey:toDisk:completion:)":{"role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:forkey:todisk:completion:)","abstract":[{"type":"text","text":"Asynchronously store an image into memory and disk cache at the given key."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:toDisk:completion:)","title":"store(_:forKey:toDisk:completion:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"store","kind":"identifier"},{"kind":"text","text":"("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"toDisk"},{"kind":"text","text":": "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageNoParamsBlock","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock"},{"kind":"text","text":"?)"}],"type":"topic","navigatorTitle":[{"text":"storeImage:forKey:toDisk:completion:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:options:context:cacheType:done:)":{"navigatorTitle":[{"kind":"identifier","text":"queryCacheOperationForKey:options:context:cacheType:done:"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:cacheType:done:)","title":"queryCacheOperation(forKey:options:context:cacheType:done:)","abstract":[{"text":"Asynchronously queries the cache with operation and call the completion when done.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:options:context:cachetype:done:)","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"queryCacheOperation","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"text":"SDImageCacheOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?, ","kind":"text"},{"kind":"externalParam","text":"cacheType"},{"kind":"text","text":": "},{"text":"SDImageCacheType","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"done"},{"kind":"text","text":": "},{"text":"SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheToken","text":"SDImageCacheToken"},{"kind":"text","text":"?"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/store(_:imageData:forKey:options:context:cacheType:completion:)":{"type":"topic","abstract":[{"text":"Asynchronously store an image into memory and disk cache at the given key.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:imageData:forKey:options:context:cacheType:completion:)","title":"store(_:imageData:forKey:options:context:cacheType:completion:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/store(_:imagedata:forkey:options:context:cachetype:completion:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"store","kind":"identifier"},{"text":"(","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageData"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"kind":"text","text":": ["},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"cacheType"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheType","text":"SDImageCacheType"},{"kind":"text","text":", "},{"text":"completion","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock","kind":"typeIdentifier"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"storeImage:imageData:forKey:options:context:cacheType:completion:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/storeImageData(_:forKey:completion:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImageData(_:forKey:completion:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"storeImageData","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier","text":"Data"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"completion"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"storeImageData:forKey:completion:","kind":"identifier"}],"title":"storeImageData(_:forKey:completion:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/storeimagedata(_:forkey:completion:)","abstract":[{"text":"Asynchronously store an image data into disk cache at the given key.","type":"text"}]},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/queryCacheOperation(forKey:done:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:done:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryCacheOperation"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"forKey"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?, "},{"text":"done","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheQueryCompletionBlock","kind":"typeIdentifier","text":"SDImageCacheQueryCompletionBlock"},{"text":"?) -> ","kind":"text"},{"text":"SDImageCacheToken","preciseIdentifier":"c:objc(cs)SDImageCacheToken","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"queryCacheOperationForKey:done:"}],"title":"queryCacheOperation(forKey:done:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/querycacheoperation(forkey:done:)","abstract":[{"text":"Asynchronously queries the cache with operation and call the completion when done.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/deleteOldFiles(completionBlock:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/deleteOldFiles(completionBlock:)","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/deleteoldfiles(completionblock:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"deleteOldFiles","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"completionBlock"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageNoParamsBlock","text":"SDWebImageNoParamsBlock"},{"text":"?)","kind":"text"}],"abstract":[{"type":"text","text":"Asynchronously remove all expired cached image from disk. Non-blocking method - returns immediately."}],"title":"deleteOldFiles(completionBlock:)","navigatorTitle":[{"text":"deleteOldFilesWithCompletionBlock:","kind":"identifier"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/init(namespace:diskCacheDirectory:)":{"type":"topic","abstract":[{"text":"Init a new cache store with a specific namespace and directory.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The final disk cache directory should looks like ($directory\/$namespace). And the default config of shared cache, should result in (~\/Library\/Caches\/com.hackemist.SDImageCache\/default\/)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:)","title":"init(namespace:diskCacheDirectory:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/init(namespace:diskcachedirectory:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"namespace","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"diskCacheDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?)","kind":"text"}],"role":"symbol","navigatorTitle":[{"text":"initWithNamespace:diskCacheDirectory:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/additionalCachePathBlock":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/additionalCachePathBlock","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"additionalCachePathBlock"},{"kind":"text","text":": "},{"text":"SDImageCacheAdditionalCachePathBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageCacheDefine.h@T@SDImageCacheAdditionalCachePathBlock"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"additionalCachePathBlock","kind":"identifier"}],"title":"additionalCachePathBlock","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/additionalcachepathblock","abstract":[{"text":"The additional disk cache path to check if the query from disk cache not exist;","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The "},{"code":"key","type":"codeVoice"},{"type":"text","text":" param is the image cache key. The returned file path will be used to load the disk cache. If return nil, ignore it."},{"text":" ","type":"text"},{"type":"text","text":"Useful if you want to bundle pre-loaded images with your app"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/shared":{"navigatorTitle":[{"kind":"identifier","text":"sharedImageCache"}],"abstract":[{"text":"Returns global shared cache instance","type":"text"}],"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageCache","preciseIdentifier":"c:objc(cs)SDImageCache","kind":"typeIdentifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/shared","type":"topic","title":"shared","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/shared"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/config":{"url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/config","title":"config","abstract":[{"type":"text","text":"Cache Config object - storing all kind of settings."},{"type":"text","text":" "},{"type":"text","text":"The property is copy so change of current config will not accidentally affect other cache’s config."}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/config","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"config"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/imageFromCache(forKey:)":{"abstract":[{"text":"Synchronously query the cache (memory and or disk) after checking the memory cache.","type":"text"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageFromCache","kind":"identifier"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"imageFromCache(forKey:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/imagefromcache(forkey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:)","navigatorTitle":[{"text":"imageFromCacheForKey:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/init(namespace:diskCacheDirectory:config:)":{"type":"topic","abstract":[{"type":"text","text":"Init a new cache store with a specific namespace, directory and config."},{"text":" ","type":"text"},{"type":"text","text":"The final disk cache directory should looks like ($directory\/$namespace). And the default config of shared cache, should result in (~\/Library\/Caches\/com.hackemist.SDImageCache\/default\/)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:config:)","title":"init(namespace:diskCacheDirectory:config:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/init(namespace:diskcachedirectory:config:)","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"namespace","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"diskCacheDirectory","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"text":"SDImageCacheConfig","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"},{"kind":"text","text":"?)"}],"role":"symbol","navigatorTitle":[{"text":"initWithNamespace:diskCacheDirectory:config:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCache-swift.class/diskImageData(forKey:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageData(forKey:)","kind":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"diskImageData"},{"kind":"text","text":"("},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?) -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"diskImageDataForKey:","kind":"identifier"}],"title":"diskImageData(forKey:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdimagecache-swift.class\/diskimagedata(forkey:)","abstract":[{"type":"text","text":"Synchronously query the image data for the given key in disk cache. You can decode the image data to image after loaded."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCache"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/additionalCachePathBlock","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/config","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskCachePath","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/memoryCache"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"},{"title":"Instance Methods","anchor":"Instance-Methods","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/cachePath(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/calculateSize(completionBlock:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearDisk(onCompletion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/clearMemory()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/deleteOldFiles(completionBlock:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageData(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataExists(withKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageDataQuery(forKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/diskImageExists(withKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromCache(forKey:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromDiskCache(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromDiskCache(forKey:options:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/imageFromMemoryCache(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/init(namespace:diskCacheDirectory:config:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:cacheType:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:context:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/queryCacheOperation(forKey:options:done:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImage(forKey:fromDisk:withCompletion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImage(forKey:withCompletion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImageFromDisk(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/removeImageFromMemory(forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:forKey:toDisk:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:imageData:forKey:options:context:cacheType:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/store(_:imageData:forKey:toDisk:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImage(toMemory:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImageData(_:forKey:completion:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/storeImageData(toDisk:forKey:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/totalDiskCount()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/totalDiskSize()"]},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/defaultDiskCacheDirectory","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCache-swift.class\/shared"],"generated":true}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCache","kind":"identifier"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"storeImageDataToDisk:forKey:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1storeImageData(toDisk:forKey:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"storeImageDataToDisk:forKey:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1storeImageData(toDisk:forKey:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:imageData:forKey:toDisk:completion:)\/title","value":"storeImage:imageData:forKey:toDisk:completion:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:imageData:forKey:toDisk:completion:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"storeImage:imageData:forKey:toDisk:completion:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1clearDisk(onCompletion:)\/title","value":"clearDiskOnCompletion:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1clearDisk(onCompletion:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"clearDiskOnCompletion:"}]},{"value":"diskImageExistsWithKey:completion:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageExists(withKey:completion:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"diskImageExistsWithKey:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageExists(withKey:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImageFromDisk(forKey:)\/title","value":"removeImageFromDiskForKey:"},{"value":[{"text":"- ","kind":"text"},{"text":"removeImageFromDiskForKey:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImageFromDisk(forKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1totalDiskCount()\/title","value":"totalDiskCount"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1totalDiskCount()\/fragments","value":[{"kind":"text","text":"- "},{"text":"totalDiskCount","kind":"identifier"}]},{"value":"SDImageCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"value":[{"text":"SDImageCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class\/navigatorTitle","op":"replace"},{"value":"defaultDiskCacheDirectory","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1defaultDiskCacheDirectory\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1defaultDiskCacheDirectory\/fragments","op":"replace","value":[{"kind":"identifier","text":"defaultDiskCacheDirectory"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1memoryCache\/title","value":"memoryCache","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1memoryCache\/fragments","value":[{"text":"memoryCache","kind":"identifier"}]},{"op":"replace","value":"imageFromMemoryCacheForKey:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromMemoryCache(forKey:)\/title"},{"op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageFromMemoryCacheForKey:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromMemoryCache(forKey:)\/fragments"},{"value":"imageFromDiskCacheForKey:options:context:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromDiskCache(forKey:options:context:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageFromDiskCacheForKey:options:context:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromDiskCache(forKey:options:context:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:forKey:completion:)\/title","value":"storeImage:forKey:completion:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:forKey:completion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"storeImage:forKey:completion:"}]},{"value":"diskCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskCache\/title","op":"replace"},{"op":"replace","value":[{"text":"diskCache","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskCache\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImageFromMemory(forKey:)\/title","op":"replace","value":"removeImageFromMemoryForKey:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeImageFromMemoryForKey:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImageFromMemory(forKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:)\/title","value":"initWithNamespace:"},{"value":[{"kind":"text","text":"- "},{"text":"initWithNamespace:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:)\/fragments","op":"replace"},{"value":"totalDiskSize","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1totalDiskSize()\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"totalDiskSize","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1totalDiskSize()\/fragments"},{"value":"removeImageForKey:withCompletion:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImage(forKey:withCompletion:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImage(forKey:withCompletion:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeImageForKey:withCompletion:","kind":"identifier"}]},{"value":"imageFromCacheForKey:options:context:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromCache(forKey:options:context:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageFromCacheForKey:options:context:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromCache(forKey:options:context:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:done:)\/title","value":"queryCacheOperationForKey:options:context:done:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:done:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"queryCacheOperationForKey:options:context:done:","kind":"identifier"}]},{"value":"removeImageForKey:fromDisk:withCompletion:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImage(forKey:fromDisk:withCompletion:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1removeImage(forKey:fromDisk:withCompletion:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeImageForKey:fromDisk:withCompletion:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1cachePath(forKey:)\/title","value":"cachePathForKey:","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"cachePathForKey:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1cachePath(forKey:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1clearMemory()\/title","value":"clearMemory","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"clearMemory","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1clearMemory()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:done:)\/title","value":"queryCacheOperationForKey:options:done:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:done:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"queryCacheOperationForKey:options:done:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromDiskCache(forKey:)\/title","op":"replace","value":"imageFromDiskCacheForKey:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imageFromDiskCacheForKey:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromDiskCache(forKey:)\/fragments","op":"replace"},{"value":"SDImageCache","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","op":"replace"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageDataQuery(forKey:completion:)\/title","op":"replace","value":"diskImageDataQueryForKey:completion:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"diskImageDataQueryForKey:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageDataQuery(forKey:completion:)\/fragments"},{"op":"replace","value":"diskCachePath","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskCachePath\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskCachePath\/fragments","value":[{"text":"diskCachePath","kind":"identifier"}],"op":"replace"},{"value":"storeImageToMemory:forKey:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1storeImage(toMemory:forKey:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1storeImage(toMemory:forKey:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"storeImageToMemory:forKey:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageDataExists(withKey:)\/title","op":"replace","value":"diskImageDataExistsWithKey:"},{"value":[{"text":"- ","kind":"text"},{"text":"diskImageDataExistsWithKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageDataExists(withKey:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1calculateSize(completionBlock:)\/title","op":"replace","value":"calculateSizeWithCompletionBlock:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1calculateSize(completionBlock:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"calculateSizeWithCompletionBlock:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:forKey:toDisk:completion:)\/title","value":"storeImage:forKey:toDisk:completion:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"storeImage:forKey:toDisk:completion:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:forKey:toDisk:completion:)\/fragments"},{"op":"replace","value":"queryCacheOperationForKey:options:context:cacheType:done:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:cacheType:done:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:options:context:cacheType:done:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"queryCacheOperationForKey:options:context:cacheType:done:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:imageData:forKey:options:context:cacheType:completion:)\/title","op":"replace","value":"storeImage:imageData:forKey:options:context:cacheType:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"storeImage:imageData:forKey:options:context:cacheType:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1store(_:imageData:forKey:options:context:cacheType:completion:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1storeImageData(_:forKey:completion:)\/title","value":"storeImageData:forKey:completion:"},{"value":[{"kind":"text","text":"- "},{"text":"storeImageData:forKey:completion:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1storeImageData(_:forKey:completion:)\/fragments","op":"replace"},{"value":"queryCacheOperationForKey:done:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:done:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1queryCacheOperation(forKey:done:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"queryCacheOperationForKey:done:","kind":"identifier"}]},{"value":"deleteOldFilesWithCompletionBlock:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1deleteOldFiles(completionBlock:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"deleteOldFilesWithCompletionBlock:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1deleteOldFiles(completionBlock:)\/fragments","op":"replace"},{"value":"initWithNamespace:diskCacheDirectory:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:diskCacheDirectory:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"initWithNamespace:diskCacheDirectory:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:diskCacheDirectory:)\/fragments"},{"value":"additionalCachePathBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1additionalCachePathBlock\/title","op":"replace"},{"value":[{"kind":"identifier","text":"additionalCachePathBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1additionalCachePathBlock\/fragments","op":"replace"},{"value":"sharedImageCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1shared\/title"},{"value":[{"text":"sharedImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1shared\/fragments"},{"value":"config","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1config\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1config\/fragments","value":[{"kind":"identifier","text":"config"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromCache(forKey:)\/title","value":"imageFromCacheForKey:","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"imageFromCacheForKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1imageFromCache(forKey:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:diskCacheDirectory:config:)\/title","value":"initWithNamespace:diskCacheDirectory:config:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1init(namespace:diskCacheDirectory:config:)\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithNamespace:diskCacheDirectory:config:"}]},{"value":"diskImageDataForKey:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageData(forKey:)\/title","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"diskImageDataForKey:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCache-swift.class~1diskImageData(forKey:)\/fragments"}]}]}