{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManager"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"abstract":[{"type":"text","text":"A caches manager to manage multiple caches."}],"sections":[],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"type":"conformsTo","kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/caches","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/clearOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/containsOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/queryOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/storeOperationPolicy"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/addCache(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeCache(_:)"],"title":"Instance Methods","anchor":"Instance-Methods","generated":true},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/shared"],"generated":true,"anchor":"Type-Properties"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager"]}],"metadata":{"roleHeading":"Class","symbolKind":"class","title":"SDImageCachesManager","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCachesManager","kind":"identifier"}],"externalID":"c:objc(cs)SDImageCachesManager","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCachesManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","url":"\/documentation\/sdwebimage\/sdimagecachesmanager","type":"topic","abstract":[{"text":"A caches manager to manage multiple caches.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"kind":"symbol","title":"SDImageCachesManager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/removeCache(_:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeCache(_:)","kind":"symbol","abstract":[{"text":"Remove a cache in the caches array.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"removeCache:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeCache","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCache","text":"SDImageCacheProtocol"},{"text":")","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/removecache(_:)","title":"removeCache(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/queryOperationPolicy":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/queryOperationPolicy","abstract":[{"type":"text","text":"Operation policy for query op."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"code":"Serial","type":"codeVoice"},{"text":", means query all caches serially (one completion called then next begin) until one cache query success (","type":"text"},{"type":"codeVoice","code":"image"},{"type":"text","text":" != nil)."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"queryOperationPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy"}],"title":"queryOperationPolicy","navigatorTitle":[{"kind":"identifier","text":"queryOperationPolicy"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/queryoperationpolicy"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheProtocol"}],"navigatorTitle":[{"text":"SDImageCacheProtocol","kind":"identifier"}],"abstract":[{"text":"This is the image cache protocol to provide custom image cache for ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Though the best practice to custom image cache, is to write your own class which conform ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"code":"SDDiskCache","type":"codeVoice"},{"type":"text","text":" protocol for "},{"code":"SDImageCache","type":"codeVoice"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"However, if your own cache implementation contains more advanced feature beyond ","type":"text"},{"code":"SDImageCache","type":"codeVoice"},{"text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like ","type":"text"},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"title":"SDImageCacheProtocol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/clearOperationPolicy":{"role":"symbol","navigatorTitle":[{"text":"clearOperationPolicy","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearOperationPolicy"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/clearoperationpolicy","abstract":[{"type":"text","text":"Operation policy for clear op."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"Concurrent"},{"type":"text","text":", means clear all caches concurrently."}],"type":"topic","title":"clearOperationPolicy","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/clearOperationPolicy","kind":"symbol"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/storeOperationPolicy":{"title":"storeOperationPolicy","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/storeOperationPolicy","type":"topic","abstract":[{"type":"text","text":"Operation policy for store op."},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"HighestOnly","type":"codeVoice"},{"text":", means store to the highest priority cache only.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/storeoperationpolicy","role":"symbol","navigatorTitle":[{"text":"storeOperationPolicy","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"storeOperationPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/removeOperationPolicy":{"title":"removeOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/removeoperationpolicy","navigatorTitle":[{"text":"removeOperationPolicy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"removeOperationPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Operation policy for remove op."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"Concurrent"},{"type":"text","text":", means remove all caches concurrently."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeOperationPolicy","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/addCache(_:)":{"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/addcache(_:)","type":"topic","abstract":[{"type":"text","text":"Add a new cache to the end of caches array. Which has the highest priority."}],"navigatorTitle":[{"text":"addCache:","kind":"identifier"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/addCache(_:)","role":"symbol","title":"addCache(_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"addCache"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageCache","kind":"typeIdentifier","text":"SDImageCacheProtocol"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/caches":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/caches","abstract":[{"type":"text","text":"All caches in caches manager. The caches array is a priority queue, which means the later added cache will have the highest priority"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"caches"},{"text":": [any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageCache","kind":"typeIdentifier","text":"SDImageCacheProtocol"},{"text":"]?","kind":"text"}],"title":"caches","navigatorTitle":[{"kind":"identifier","text":"caches"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/caches"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/containsOperationPolicy":{"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"containsOperationPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/containsoperationpolicy","title":"containsOperationPolicy","abstract":[{"type":"text","text":"Operation policy for contains op."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"code":"Serial","type":"codeVoice"},{"type":"text","text":", means check all caches serially (one completion called then next begin) until one cache check success ("},{"type":"codeVoice","code":"containsCacheType"},{"type":"text","text":" != None)."}],"navigatorTitle":[{"text":"containsOperationPolicy","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/containsOperationPolicy"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/shared":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDImageCachesManager","text":"SDImageCachesManager","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/shared","title":"shared","abstract":[{"type":"text","text":"Returns the global shared caches manager instance. By default we will set ["},{"type":"codeVoice","code":"SDImageCache.sharedImageCache"},{"type":"text","text":"] into the caches array."}],"navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/shared"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"path":"\/metadata\/title","op":"replace","value":"SDImageCachesManager"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SDImageCachesManager","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/caches","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/clearOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/containsOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/queryOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeOperationPolicy","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/storeOperationPolicy"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/addCache(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeCache(_:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/shared"],"generated":true,"anchor":"Type-Properties"}]},{"path":"\/relationshipsSections","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"type":"conformsTo","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"],"title":"Conforms To"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCachesManager","kind":"identifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title","value":"SDImageCachesManager"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","op":"replace","value":[{"text":"SDImageCachesManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeCache(_:)\/title","value":"removeCache:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeCache(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeCache:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1queryOperationPolicy\/title","value":"queryOperationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1queryOperationPolicy\/fragments","value":[{"text":"queryOperationPolicy","kind":"identifier"}]},{"value":"SDImageCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}],"op":"replace"},{"value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/navigatorTitle"},{"value":"clearOperationPolicy","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1clearOperationPolicy\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1clearOperationPolicy\/fragments","value":[{"kind":"identifier","text":"clearOperationPolicy"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1storeOperationPolicy\/title","value":"storeOperationPolicy","op":"replace"},{"value":[{"text":"storeOperationPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1storeOperationPolicy\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeOperationPolicy\/title","op":"replace","value":"removeOperationPolicy"},{"value":[{"text":"removeOperationPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeOperationPolicy\/fragments","op":"replace"},{"op":"replace","value":"addCache:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1addCache(_:)\/title"},{"value":[{"text":"- ","kind":"text"},{"text":"addCache:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1addCache(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1caches\/title","value":"caches","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1caches\/fragments","value":[{"text":"caches","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1containsOperationPolicy\/title","op":"replace","value":"containsOperationPolicy"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1containsOperationPolicy\/fragments","value":[{"kind":"identifier","text":"containsOperationPolicy"}],"op":"replace"},{"op":"replace","value":"sharedManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1shared\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1shared\/fragments","value":[{"kind":"identifier","text":"sharedManager"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}