{"kind":"symbol","abstract":[{"text":"A transformer protocol to transform the image load from cache or from download.","type":"text"},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"code":"transformer","type":"codeVoice"},{"type":"text","text":" property or context option "},{"type":"codeVoice","code":"SDWebImageContextImageTransformer"},{"text":").","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":"."}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"},"metadata":{"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"SDImageTransformer","externalID":"c:objc(pl)SDImageTransformer","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDImageTransformer","kind":"identifier"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Overview","anchor":"overview","type":"heading","level":2},{"content":[{"type":"paragraph","inlineContent":[{"text":"The transform process is called from a global queue in order to not to block the main queue.","type":"text"}]}],"style":"note","type":"aside","name":"Note"}],"kind":"content"}],"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/preserveImageMetadata","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/transformerKey"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/transformedImage(with:forKey:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"schemaVersion":{"minor":3,"patch":0,"major":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagetransformer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagetransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"title":"Inherits From"},{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFlippingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRotationTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"],"title":"Conforming Types","type":"conformingTypes"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRotationTransformer":{"url":"\/documentation\/sdwebimage\/sdimagerotationtransformer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageRotationTransformer"}],"title":"SDImageRotationTransformer","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRotationTransformer","abstract":[{"type":"text","text":"Image rotation transformer"}],"type":"topic","navigatorTitle":[{"text":"SDImageRotationTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer":{"abstract":[{"type":"text","text":"Image round corner transformer"}],"title":"SDImageRoundCornerTransformer","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","kind":"symbol","navigatorTitle":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer":{"title":"SDImageTintTransformer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer","type":"topic","navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}],"abstract":[{"type":"text","text":"Image tint color transformer"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer/transformerKey":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transformerKey"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/transformerKey","abstract":[{"text":"For each transformer, it must contains its cache key to used to store the image cache or query from the cache. This key will be appened after the original cache key generated by URL or from user.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Which means, the cache should match what your transformer logic do. The same "},{"code":"input image","type":"codeVoice"},{"text":" + ","type":"text"},{"type":"codeVoice","code":"transformer key"},{"type":"text","text":", should always generate the same "},{"type":"codeVoice","code":"output image"},{"type":"text","text":"."}],"role":"symbol","type":"topic","title":"transformerKey","url":"\/documentation\/sdwebimage\/sdimagetransformer\/transformerkey","required":true,"navigatorTitle":[{"text":"transformerKey","kind":"identifier"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagebasetransformer","title":"SDImageBaseTransformer","abstract":[{"text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like ","type":"text"},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"text":") instead.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer":{"kind":"symbol","navigatorTitle":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer","title":"SDImageFilterTransformer","abstract":[{"text":"Core Image filter transformer","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageFilterTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImagePipelineTransformer":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImagePipelineTransformer","kind":"identifier"}],"type":"topic","title":"SDImagePipelineTransformer","abstract":[{"text":"Pipeline transformer. Which you can bind multiple transformers together to let the image to be transformed one by one in order and generate the final image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImagePipelineTransformer","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer","url":"\/documentation\/sdwebimage\/sdimagepipelinetransformer","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCroppingTransformer":{"title":"SDImageCroppingTransformer","role":"symbol","navigatorTitle":[{"text":"SDImageCroppingTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecroppingtransformer","abstract":[{"type":"text","text":"Image cropping transformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCroppingTransformer"}],"kind":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer/transformedImage(with:forKey:)":{"abstract":[{"text":"Transform the image to another image.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/transformedImage(with:forKey:)","required":true,"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"transformedImage"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"transformedImage(with:forKey:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagetransformer\/transformedimage(with:forkey:)","navigatorTitle":[{"kind":"identifier","text":"transformedImageWithImage:forKey:"}],"deprecated":true,"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer/preserveImageMetadata":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"preserveImageMetadata"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"preserveImageMetadata","kind":"identifier"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimagetransformer\/preserveimagemetadata","kind":"symbol","required":true,"abstract":[{"type":"text","text":"Defaults to YES if you don’t implements this method."},{"text":" ","type":"text"},{"type":"text","text":"We keep some metadata like Image Format ("},{"code":"sd_imageFormat","type":"codeVoice"},{"text":")\/ Animated Loop Count (","type":"text"},{"code":"sd_imageLoopCount","type":"codeVoice"},{"text":") via associated object on UIImage instance.","type":"text"},{"text":" ","type":"text"},{"text":"When transformer generate a new UIImage instance, in most cases you still want to keep these information. So this is what for during the image loading pipeline.","type":"text"},{"text":" ","type":"text"},{"text":"If the value is YES, we will keep and override the metadata ","type":"text"},{"inlineContent":[{"text":"After you generate the UIImage","type":"text"}],"type":"strong"},{"type":"text","text":" "},{"text":"If the value is NO, we will not touch the UIImage metadata and it’s controlled by you during the generation. Read ","type":"text"},{"type":"codeVoice","code":"UIImage+Medata.h"},{"text":" and pick the metadata you want for the new generated UIImage.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/preserveImageMetadata","type":"topic","title":"preserveImageMetadata"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFlippingTransformer":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageFlippingTransformer"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFlippingTransformer","url":"\/documentation\/sdwebimage\/sdimageflippingtransformer","abstract":[{"type":"text","text":"Image flipping transformer"}],"kind":"symbol","title":"SDImageFlippingTransformer","navigatorTitle":[{"text":"SDImageFlippingTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer":{"url":"\/documentation\/sdwebimage\/sdimageblurtransformer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBlurTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","type":"topic","navigatorTitle":[{"text":"SDImageBlurTransformer","kind":"identifier"}],"abstract":[{"text":"Image blur effect transformer","type":"text"}],"role":"symbol","title":"SDImageBlurTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageResizingTransformer":{"navigatorTitle":[{"text":"SDImageResizingTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageresizingtransformer","title":"SDImageResizingTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","type":"topic","abstract":[{"type":"text","text":"Image resizing transformer"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageResizingTransformer","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Protocol","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SDImageTransformer"},{"op":"replace","value":"protocol","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageTransformer"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageTransformer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/preserveImageMetadata","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/transformerKey"]},{"title":"Instance Methods","generated":true,"anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer\/transformedImage(with:forKey:)"]}]},{"op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"]},{"title":"Conforming Types","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImagePipelineTransformer"],"kind":"relationships","type":"conformingTypes"}],"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTransformer","kind":"identifier"},{"kind":"text","text":" <"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"kind":"text","text":">"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRotationTransformer\/title","value":"SDImageRotationTransformer"},{"op":"replace","value":[{"text":"SDImageRotationTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRotationTransformer\/fragments"},{"value":[{"text":"SDImageRotationTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRotationTransformer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/title","value":"SDImageRoundCornerTransformer","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageRoundCornerTransformer"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/navigatorTitle","value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"op":"replace"},{"value":"SDImageTintTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/title"},{"op":"replace","value":[{"text":"SDImageTintTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/fragments"},{"value":[{"text":"SDImageTintTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/navigatorTitle"},{"value":"transformerKey","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1transformerKey\/title"},{"op":"replace","value":[{"text":"transformerKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1transformerKey\/fragments"},{"value":"SDImageBaseTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/fragments"},{"value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/title","value":"SDImageFilterTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/fragments","value":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/navigatorTitle","value":[{"text":"SDImageFilterTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/title","value":"SDImagePipelineTransformer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/fragments","value":[{"text":"SDImagePipelineTransformer","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDImagePipelineTransformer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImagePipelineTransformer\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","value":"SDImageTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"text":"SDImageTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace"},{"value":"SDImageCroppingTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/fragments","value":[{"text":"SDImageCroppingTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/navigatorTitle","value":[{"text":"SDImageCroppingTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1transformedImage(with:forKey:)\/title","value":"transformedImageWithImage:forKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1transformedImage(with:forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"transformedImageWithImage:forKey:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1preserveImageMetadata\/title","op":"replace","value":"preserveImageMetadata"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer~1preserveImageMetadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"preserveImageMetadata"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFlippingTransformer\/title","op":"replace","value":"SDImageFlippingTransformer"},{"value":[{"kind":"identifier","text":"SDImageFlippingTransformer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFlippingTransformer\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageFlippingTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFlippingTransformer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/title","op":"replace","value":"SDImageBlurTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageBlurTransformer"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/navigatorTitle","value":[{"text":"SDImageBlurTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/title","value":"SDImageResizingTransformer","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/fragments","op":"replace","value":[{"text":"SDImageResizingTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageResizingTransformer"}]}]}]}