{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecoder"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOCoder"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom image decoding\/encoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"title":"SDImageCoder","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDImageCoder","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCoder"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canDecode(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canEncode(to:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/decodedImage(with:options:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/encodedData(with:format:options:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"role":"symbol","title":"SDProgressiveImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}],"url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageGIFCoder":{"role":"symbol","title":"SDImageGIFCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageGIFCoder"}],"abstract":[{"type":"text","text":"Built in coder using ImageIO that supports animated GIF encoding\/decoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageGIFCoder"}],"url":"\/documentation\/sdwebimage\/sdimagegifcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"role":"symbol","title":"SDImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom image decoding\/encoding."},{"type":"text","text":" "},{"type":"text","text":"These methods are all required to implement."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/decodedImage(with:options:)":{"navigatorTitle":[{"kind":"identifier","text":"decodedImageWithData:options:"}],"role":"symbol","title":"decodedImage(with:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Decode the image data to image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/decodedImage(with:options:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoder\/decodedimage(with:options:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/encodedData(with:format:options:)":{"navigatorTitle":[{"kind":"identifier","text":"encodedDataWithImage:format:options:"}],"role":"symbol","title":"encodedData(with:format:options:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"encodedData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"format"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"kind":"text","text":", "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Encode the image to image data."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/encodedData(with:format:options:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoder\/encodeddata(with:format:options:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/canEncode(to:)":{"navigatorTitle":[{"kind":"identifier","text":"canEncodeToFormat:"}],"role":"symbol","title":"canEncode(to:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canEncode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"to"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns YES if this coder can encode some image. Otherwise, it should be passed to another coder."},{"type":"text","text":" "},{"type":"text","text":"For custom coder which introduce new image format, you’d better define a new "},{"type":"codeVoice","code":"SDImageFormat"},{"type":"text","text":" using like this. If you’re creating public coder plugin for new image format, also update "},{"type":"codeVoice","code":"https:\/\/github.com\/rs\/SDWebImage\/wiki\/Coder-Plugin-List"},{"type":"text","text":" to avoid same value been defined twice."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canEncode(to:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoder\/canencode(to:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAPNGCoder":{"role":"symbol","title":"SDImageAPNGCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageAPNGCoder"}],"abstract":[{"type":"text","text":"Built in coder using ImageIO that supports APNG encoding\/decoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageAPNGCoder"}],"url":"\/documentation\/sdwebimage\/sdimageapngcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCodersManager":{"role":"symbol","title":"SDImageCodersManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCodersManager"}],"abstract":[{"type":"text","text":"Global object holding the array of coders, so that we avoid passing them from object to object."},{"type":"text","text":" "},{"type":"text","text":"Uses a priority queue behind scenes, which means the latest added coders have the highest priority."},{"type":"text","text":" "},{"type":"text","text":"This is done so when encoding\/decoding something, we go through the list and ask each coder if they can handle the current data."},{"type":"text","text":" "},{"type":"text","text":"That way, users can add their custom coders while preserving our existing prebuilt ones"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCodersManager"}],"url":"\/documentation\/sdwebimage\/sdimagecodersmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder/canDecode(from:)":{"navigatorTitle":[{"kind":"identifier","text":"canDecodeFromData:"}],"role":"symbol","title":"canDecode(from:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canDecode"},{"kind":"text","text":"("},{"kind":"externalParam","text":"from"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Returns YES if this coder can decode some data. Otherwise, the data should be passed to another coder."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canDecode(from:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoder\/candecode(from:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder":{"role":"symbol","title":"SDImageAWebPCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageAWebPCoder"}],"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageAWebPCoder"}],"url":"\/documentation\/sdwebimage\/sdimageawebpcoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"role":"symbol","title":"SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"abstract":[{"type":"text","text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class."},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"role":"symbol","title":"SDAnimatedImageCoder","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"abstract":[{"type":"text","text":"This is the animated image coder protocol for custom animated image class like  "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":". Through it inherit from "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":" to detect the proper coder for specify animated image format."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHEICCoder":{"role":"symbol","title":"SDImageHEICCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageHEICCoder"}],"abstract":[{"type":"text","text":"This coder is used for HEIC (HEIF with HEVC container codec) image format."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the static HEIC (.heic) support in iOS 11\/macOS 10.13\/tvOS 11\/watchOS 4+."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the animated HEIC (.heics) support in iOS 13\/macOS 10.15\/tvOS 13\/watchOS 6+."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/nokiatech.github.io\/heif\/technical.html for the standard."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageHEICCoder"}],"url":"\/documentation\/sdwebimage\/sdimageheiccoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOCoder":{"role":"symbol","title":"SDImageIOCoder","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageIOCoder"}],"abstract":[{"type":"text","text":"Built in coder that supports PNG, JPEG, TIFF, includes support for progressive decoding."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageIOCoder"}],"url":"\/documentation\/sdwebimage\/sdimageiocoder"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoder"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCoder"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canDecode(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/canEncode(to:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/decodedImage(with:options:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder\/encodedData(with:format:options:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCodersManager"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title","value":"SDProgressiveImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments","value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/title","value":"SDImageGIFCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/fragments","value":[{"kind":"identifier","text":"SDImageGIFCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments","value":[{"kind":"identifier","text":"SDImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1decodedImage(with:options:)\/title","value":"decodedImageWithData:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1decodedImage(with:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"decodedImageWithData:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1encodedData(with:format:options:)\/title","value":"encodedDataWithImage:format:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1encodedData(with:format:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"encodedDataWithImage:format:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canEncode(to:)\/title","value":"canEncodeToFormat:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canEncode(to:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canEncodeToFormat:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/title","value":"SDImageAPNGCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/fragments","value":[{"kind":"identifier","text":"SDImageAPNGCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/title","value":"SDImageCodersManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCodersManager\/fragments","value":[{"kind":"identifier","text":"SDImageCodersManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canDecode(from:)\/title","value":"canDecodeFromData:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder~1canDecode(from:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canDecodeFromData:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/title","value":"SDImageAWebPCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/fragments","value":[{"kind":"identifier","text":"SDImageAWebPCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title","value":"SDImageIOAnimatedCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","value":"SDAnimatedImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/title","value":"SDImageHEICCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/fragments","value":[{"kind":"identifier","text":"SDImageHEICCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOCoder\/title","value":"SDImageIOCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOCoder\/fragments","value":[{"kind":"identifier","text":"SDImageIOCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}