{"abstract":[{"text":"Image tint color transformer","type":"text"}],"metadata":{"navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageTintTransformer","title":"SDImageTintTransformer","role":"symbol","symbolKind":"class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}]},"sections":[],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"type":"conformsTo","title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDImageTintTransformer","kind":"identifier"}],"platforms":["iOS"]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagetinttransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","topicSections":[{"title":"Initializers","generated":true,"anchor":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:blendMode:)"]},{"title":"Instance Properties","anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/blendMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/tintColor"],"generated":true}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"},"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer":{"title":"SDImageTintTransformer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer","type":"topic","navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}],"abstract":[{"type":"text","text":"Image tint color transformer"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/blendMode":{"navigatorTitle":[{"text":"blendMode","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/blendmode","abstract":[{"text":"The blend mode, defaults to ","type":"text"},{"type":"codeVoice","code":"sourceIn"},{"type":"text","text":" if you use the initializer without blend mode"}],"role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"blendMode","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGBlendMode","preciseIdentifier":"c:@E@CGBlendMode"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/blendMode","kind":"symbol","title":"blendMode","type":"topic"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/tintColor":{"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/tintcolor","title":"tintColor","navigatorTitle":[{"text":"tintColor","kind":"identifier"}],"type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"tintColor","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"The tint color."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/tintColor","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/init(color:blendMode:)":{"navigatorTitle":[{"kind":"identifier","text":"transformerWithColor:blendMode:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:blendMode:)","type":"topic","title":"init(color:blendMode:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"color","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"blendMode","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@CGBlendMode","text":"CGBlendMode","kind":"typeIdentifier"},{"kind":"text","text":")"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:blendmode:)","kind":"symbol","role":"symbol","abstract":[]},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagebasetransformer","title":"SDImageBaseTransformer","abstract":[{"text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like ","type":"text"},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"text":") instead.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer/init(color:)":{"navigatorTitle":[{"text":"transformerWithColor:","kind":"identifier"}],"title":"init(color:)","kind":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:)","role":"symbol","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"color"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)UIColor","kind":"typeIdentifier","text":"UIColor"},{"kind":"text","text":")"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer\/init(color:)","abstract":[]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"SDImageTintTransformer","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","value":[{"text":"SDImageTintTransformer","kind":"identifier"}],"path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SDImageTintTransformer"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/blendMode","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/tintColor"],"title":"Instance Properties"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer\/init(color:blendMode:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"],"kind":"relationships","type":"inheritsFrom"}],"path":"\/relationshipsSections","op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageTintTransformer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageBaseTransformer","text":"SDImageBaseTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/title","op":"replace","value":"SDImageTintTransformer"},{"value":[{"text":"SDImageTintTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageTintTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","value":"SDImageTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageTransformer"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","op":"replace","value":[{"text":"SDImageTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1blendMode\/title","value":"blendMode"},{"value":[{"text":"blendMode","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1blendMode\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1tintColor\/title","value":"tintColor","op":"replace"},{"value":[{"text":"tintColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1tintColor\/fragments"},{"op":"replace","value":"transformerWithColor:blendMode:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:blendMode:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"transformerWithColor:blendMode:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:blendMode:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/title","value":"SDImageBaseTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/fragments","value":[{"text":"SDImageBaseTransformer","kind":"identifier"}]},{"value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:)\/title","op":"replace","value":"transformerWithColor:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer~1init(color:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithColor:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}