{"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/init(radius:corners:borderWidth:borderColor:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/borderColor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/borderWidth","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/cornerRadius","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/corners"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"}],"relationshipsSections":[{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"],"title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"]}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageRoundCornerTransformer","kind":"identifier"}]}],"kind":"declarations"}],"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageroundcornertransformer"]},{"paths":["\/documentation\/sdwebimage\/sdimageroundcornertransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Class","title":"SDImageRoundCornerTransformer","navigatorTitle":[{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"role":"symbol","modules":[{"name":"SDWebImage"}],"symbolKind":"class","externalID":"c:objc(cs)SDImageRoundCornerTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"}]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer"},"sections":[],"abstract":[{"type":"text","text":"Image round corner transformer"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer":{"abstract":[{"type":"text","text":"Image round corner transformer"}],"title":"SDImageRoundCornerTransformer","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","kind":"symbol","navigatorTitle":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/borderColor":{"kind":"symbol","abstract":[{"type":"text","text":"The border stroke color. nil means clear color."}],"title":"borderColor","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/borderColor","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/bordercolor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"borderColor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor","text":"UIColor"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"borderColor"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/corners":{"type":"topic","abstract":[{"type":"text","text":"A bitmask value that identifies the corners that you want"},{"text":" ","type":"text"},{"text":"rounded. You can use this parameter to round only a subset","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"of the corners of the rectangle."}],"url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/corners","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"corners","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner","text":"SDRectCorner","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"corners","kind":"identifier"}],"kind":"symbol","title":"corners","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/corners"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagebasetransformer","title":"SDImageBaseTransformer","abstract":[{"text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like ","type":"text"},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"text":") instead.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/cornerRadius":{"kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cornerRadius"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/cornerRadius","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/cornerradius","abstract":[{"text":"The radius of each corner oval. Values larger than half the","type":"text"},{"type":"text","text":" "},{"text":"rectangle’s width or height are clamped appropriately to","type":"text"},{"type":"text","text":" "},{"type":"text","text":"half the width or height."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cornerRadius","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"role":"symbol","title":"cornerRadius"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/borderWidth":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/borderWidth","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/borderwidth","role":"symbol","abstract":[{"type":"text","text":"The inset border line width. Values larger than half the rectangle’s"},{"type":"text","text":" "},{"type":"text","text":"width or height are clamped appropriately to half the width"},{"text":" ","type":"text"},{"type":"text","text":"or height."}],"navigatorTitle":[{"kind":"identifier","text":"borderWidth"}],"type":"topic","title":"borderWidth","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"borderWidth","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer/init(radius:corners:borderWidth:borderColor:)":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"transformerWithRadius:corners:borderWidth:borderColor:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer\/init(radius:corners:borderwidth:bordercolor:)","kind":"symbol","title":"init(radius:corners:borderWidth:borderColor:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/init(radius:corners:borderWidth:borderColor:)","fragments":[{"text":"convenience","kind":"keyword"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"text":"corners","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDRectCorner","kind":"typeIdentifier","preciseIdentifier":"c:UIImage+Transform.h@T@SDRectCorner"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"borderWidth"},{"text":": ","kind":"text"},{"text":"CGFloat","preciseIdentifier":"s:14CoreFoundation7CGFloatV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"borderColor","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIColor","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIColor"},{"text":"?)","kind":"text"}]},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDImageRoundCornerTransformer"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageRoundCornerTransformer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/borderColor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/borderWidth","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/cornerRadius","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/corners"],"anchor":"Instance-Properties","title":"Instance Properties","generated":true},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer\/init(radius:corners:borderWidth:borderColor:)"],"generated":true,"anchor":"Type-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"],"kind":"relationships","type":"inheritsFrom"}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","text":"SDImageBaseTransformer","preciseIdentifier":"c:objc(cs)SDImageBaseTransformer"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/title","value":"SDImageRoundCornerTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/fragments","value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1borderColor\/title","op":"replace","value":"borderColor"},{"value":[{"text":"borderColor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1borderColor\/fragments"},{"op":"replace","value":"corners","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1corners\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1corners\/fragments","value":[{"kind":"identifier","text":"corners"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/title","value":"SDImageBaseTransformer","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/fragments","op":"replace","value":[{"text":"SDImageBaseTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/navigatorTitle","value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"op":"replace"},{"value":"cornerRadius","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1cornerRadius\/title","op":"replace"},{"value":[{"text":"cornerRadius","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1cornerRadius\/fragments"},{"value":"SDImageTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"text":"SDImageTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1borderWidth\/title","op":"replace","value":"borderWidth"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1borderWidth\/fragments","value":[{"text":"borderWidth","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1init(radius:corners:borderWidth:borderColor:)\/title","op":"replace","value":"transformerWithRadius:corners:borderWidth:borderColor:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"transformerWithRadius:corners:borderWidth:borderColor:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer~1init(radius:corners:borderWidth:borderColor:)\/fragments"}]}]}