{"relationshipsSections":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"kind":"relationships","type":"inheritedBy","title":"Inherited By","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFlippingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRotationTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"]},{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"type":"conformsTo","title":"Conforms To"}],"abstract":[{"type":"text","text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like "},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"type":"text","text":") instead."}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","interfaceLanguage":"swift"},"topicSections":[{"title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer\/preserveImageMetadata"],"anchor":"Instance-Properties"}],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagebasetransformer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagebasetransformer"]}],"sections":[],"metadata":{"role":"symbol","navigatorTitle":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"SDImageBaseTransformer","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageBaseTransformer","title":"SDImageBaseTransformer","symbolKind":"class","roleHeading":"Class"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageBaseTransformer"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer":{"kind":"symbol","navigatorTitle":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer","title":"SDImageFilterTransformer","abstract":[{"text":"Core Image filter transformer","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageFilterTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRoundCornerTransformer":{"abstract":[{"type":"text","text":"Image round corner transformer"}],"title":"SDImageRoundCornerTransformer","url":"\/documentation\/sdwebimage\/sdimageroundcornertransformer","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageRoundCornerTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","kind":"symbol","navigatorTitle":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagebasetransformer","title":"SDImageBaseTransformer","abstract":[{"text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like ","type":"text"},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"text":") instead.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer/preserveImageMetadata":{"role":"symbol","title":"preserveImageMetadata","url":"\/documentation\/sdwebimage\/sdimagebasetransformer\/preserveimagemetadata","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer\/preserveImageMetadata","navigatorTitle":[{"kind":"identifier","text":"preserveImageMetadata"}],"type":"topic","abstract":[{"type":"text","text":"For concrete transformer, this property is readwrite and defaults to YES. You can choose whether to preserve image metadata "},{"inlineContent":[{"type":"text","text":"After you generate the UIImage"}],"type":"strong"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"preserveImageMetadata"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"}]},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer":{"url":"\/documentation\/sdwebimage\/sdimageblurtransformer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBlurTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","type":"topic","navigatorTitle":[{"text":"SDImageBlurTransformer","kind":"identifier"}],"abstract":[{"text":"Image blur effect transformer","type":"text"}],"role":"symbol","title":"SDImageBlurTransformer"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageRotationTransformer":{"url":"\/documentation\/sdwebimage\/sdimagerotationtransformer","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageRotationTransformer"}],"title":"SDImageRotationTransformer","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRotationTransformer","abstract":[{"type":"text","text":"Image rotation transformer"}],"type":"topic","navigatorTitle":[{"text":"SDImageRotationTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCroppingTransformer":{"title":"SDImageCroppingTransformer","role":"symbol","navigatorTitle":[{"text":"SDImageCroppingTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecroppingtransformer","abstract":[{"type":"text","text":"Image cropping transformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCroppingTransformer"}],"kind":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFlippingTransformer":{"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageFlippingTransformer"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFlippingTransformer","url":"\/documentation\/sdwebimage\/sdimageflippingtransformer","abstract":[{"type":"text","text":"Image flipping transformer"}],"kind":"symbol","title":"SDImageFlippingTransformer","navigatorTitle":[{"text":"SDImageFlippingTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageResizingTransformer":{"navigatorTitle":[{"text":"SDImageResizingTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageresizingtransformer","title":"SDImageResizingTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","type":"topic","abstract":[{"type":"text","text":"Image resizing transformer"}],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageResizingTransformer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","title":"NSObject"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTintTransformer":{"title":"SDImageTintTransformer","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer","type":"topic","navigatorTitle":[{"text":"SDImageTintTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagetinttransformer","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageTintTransformer","kind":"identifier"}],"abstract":[{"type":"text","text":"Image tint color transformer"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDImageBaseTransformer","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageBaseTransformer"}]},{"value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer\/preserveImageMetadata"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"}],"path":"\/topicSections","op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"title":"Inherited By","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFlippingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageResizingTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRotationTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageRoundCornerTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTintTransformer"],"type":"inheritedBy"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"],"title":"Conforms To","kind":"relationships","type":"conformsTo"}],"op":"replace","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/title","value":"SDImageFilterTransformer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageFilterTransformer"}]},{"value":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/title","value":"SDImageRoundCornerTransformer"},{"value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/fragments"},{"op":"replace","value":[{"text":"SDImageRoundCornerTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRoundCornerTransformer\/navigatorTitle"},{"value":"SDImageBaseTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/fragments","value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"op":"replace"},{"value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/navigatorTitle","op":"replace"},{"value":"preserveImageMetadata","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer~1preserveImageMetadata\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer~1preserveImageMetadata\/fragments","value":[{"kind":"identifier","text":"preserveImageMetadata"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/title","value":"SDImageBlurTransformer","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageBlurTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/navigatorTitle","op":"replace","value":[{"text":"SDImageBlurTransformer","kind":"identifier"}]},{"op":"replace","value":"SDImageRotationTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRotationTransformer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRotationTransformer\/fragments","value":[{"text":"SDImageRotationTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageRotationTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageRotationTransformer"}],"op":"replace"},{"value":"SDImageCroppingTransformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/title"},{"value":[{"text":"SDImageCroppingTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCroppingTransformer"}]},{"value":"SDImageTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","op":"replace"},{"value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","value":[{"text":"SDImageTransformer","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFlippingTransformer\/title","value":"SDImageFlippingTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFlippingTransformer\/fragments","op":"replace","value":[{"text":"SDImageFlippingTransformer","kind":"identifier"}]},{"op":"replace","value":[{"kind":"identifier","text":"SDImageFlippingTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFlippingTransformer\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/title","value":"SDImageResizingTransformer"},{"value":[{"kind":"identifier","text":"SDImageResizingTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageResizingTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageResizingTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/title","value":"SDImageTintTransformer"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageTintTransformer"}]},{"value":[{"kind":"identifier","text":"SDImageTintTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTintTransformer\/navigatorTitle","op":"replace"}]}]}