{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageforcedecodepolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"type":"text","text":" "},{"type":"text","text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"type":"codeVoice","code":"pre-process"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"type":"text","text":" "},{"type":"text","text":"The downside is that force-decode may consume RAM and CPU, and may loss the "},{"type":"codeVoice","code":"lazy"},{"type":"text","text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: "},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"title":"SDImageForceDecodePolicy","roleHeading":"Enumeration","role":"symbol","symbolKind":"enum","externalID":"c:@E@SDImageForceDecodePolicy","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/always","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/automatic","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/never"]},{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/init(rawValue:)"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/RawRepresentable-Implementations"],"generated":true}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/automatic":{"role":"symbol","title":"SDImageForceDecodePolicy.automatic","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"automatic"}],"abstract":[{"type":"text","text":"Based on input CGImage’s colorspace, alignment, bitmapinfo, if it may trigger "},{"type":"codeVoice","code":"CA::copy_image"},{"type":"text","text":" extra copy, we will force-decode, else don’t"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/automatic","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicyAutomatic"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/automatic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"?("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/never":{"role":"symbol","title":"SDImageForceDecodePolicy.never","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"never"}],"abstract":[{"type":"text","text":"Never force decode input CGImage"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/never","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicyNever"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/never"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/rawrepresentable-implementations"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy":{"role":"symbol","title":"SDImageForceDecodePolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"abstract":[{"type":"text","text":"The policy to force-decode the origin CGImage (produced by Image Coder Plugin)"},{"type":"text","text":" "},{"type":"text","text":"Some CGImage may be lazy, or not lazy, but need extra copy to render on screen"},{"type":"text","text":" "},{"type":"text","text":"The force-decode step help to "},{"type":"codeVoice","code":"pre-process"},{"type":"text","text":" to get the best suitable CGImage to render, which can increase frame rate"},{"type":"text","text":" "},{"type":"text","text":"The downside is that force-decode may consume RAM and CPU, and may loss the "},{"type":"codeVoice","code":"lazy"},{"type":"text","text":" support (lazy CGImage can be purged when memory warning, and re-created if need), see more: "},{"type":"codeVoice","code":"SDImageCoderDecodeUseLazyDecoding"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageForceDecodePolicy/always":{"role":"symbol","title":"SDImageForceDecodePolicy.always","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"always"}],"abstract":[{"type":"text","text":"Always force decode input CGImage (only once)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/always","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageForceDecodePolicyAlways"}],"url":"\/documentation\/sdwebimage\/sdimageforcedecodepolicy\/always"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDImageForceDecodePolicy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/always","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/automatic","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageForceDecodePolicy\/never"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageForceDecodePolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1automatic\/title","value":"SDImageForceDecodePolicyAutomatic"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1automatic\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicyAutomatic"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1never\/title","value":"SDImageForceDecodePolicyNever"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1never\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicyNever"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/title","value":"SDImageForceDecodePolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1always\/title","value":"SDImageForceDecodePolicyAlways"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageForceDecodePolicy~1always\/fragments","value":[{"kind":"identifier","text":"SDImageForceDecodePolicyAlways"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}