{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCroppingTransformer"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecroppingtransformer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecroppingtransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Image cropping transformer"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCroppingTransformer"}],"title":"SDImageCroppingTransformer","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDImageCroppingTransformer","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCroppingTransformer"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer\/init(rect:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer\/rect"]}],"references":{"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCroppingTransformer/init(rect:)":{"role":"symbol","title":"init(rect:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer\/init(rect:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"transformerWithRect:"}],"url":"\/documentation\/sdwebimage\/sdimagecroppingtransformer\/init(rect:)"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"role":"symbol","title":"SDImageTransformer","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageTransformer"}],"abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"type":"text","text":"You can provide transformer to cache and manager (Through the "},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"type":"codeVoice","code":"SDWebImageContextImageTransformer"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagetransformer"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCroppingTransformer/rect":{"role":"symbol","title":"rect","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"rect"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGRect","preciseIdentifier":"c:@S@CGRect"}],"abstract":[{"type":"text","text":"Image’s inner rect."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer\/rect","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"rect"}],"url":"\/documentation\/sdwebimage\/sdimagecroppingtransformer\/rect"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCroppingTransformer":{"role":"symbol","title":"SDImageCroppingTransformer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCroppingTransformer"}],"abstract":[{"type":"text","text":"Image cropping transformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCroppingTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagecroppingtransformer"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCroppingTransformer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCroppingTransformer"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCroppingTransformer"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer\/rect"]},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCroppingTransformer\/init(rect:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCroppingTransformer"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer~1init(rect:)\/title","value":"transformerWithRect:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer~1init(rect:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"transformerWithRect:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","value":"SDImageTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer~1rect\/title","value":"rect"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer~1rect\/fragments","value":[{"kind":"identifier","text":"rect"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/title","value":"SDImageCroppingTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCroppingTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageCroppingTransformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}