{"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachecalculatesizeblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachecalculatesizeblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheCalculateSizeBlock"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"},{"text":" = (","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:SDImageCacheDefine.h@T@SDImageCacheCalculateSizeBlock","symbolKind":"typealias","role":"symbol","roleHeading":"Type Alias","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}],"title":"SDImageCacheCalculateSizeBlock","modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheCalculateSizeBlock":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecachecalculatesizeblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}],"navigatorTitle":[{"text":"SDImageCacheCalculateSizeBlock","kind":"identifier"}],"kind":"symbol","title":"SDImageCacheCalculateSizeBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheCalculateSizeBlock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","value":"SDImageCacheCalculateSizeBlock","op":"replace"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDImageCacheCalculateSizeBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageCacheCalculateSizeBlock","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#l#l)","text":"void (^)(unsigned long, unsigned long)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","value":"SDImageCacheCalculateSizeBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCalculateSizeBlock\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCalculateSizeBlock\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}]},{"value":[{"kind":"identifier","text":"SDImageCacheCalculateSizeBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheCalculateSizeBlock\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}