{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageFrame"}],"languages":["swift"]}]},{"kind":"content","content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you need to specify animated images loop count, use "},{"type":"codeVoice","code":"sd_imageLoopCount"},{"type":"text","text":" property in "},{"type":"codeVoice","code":"UIImage+Metadata.h"},{"type":"text","text":"."}]}],"style":"note","name":"Note","type":"aside"}]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame"},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageFrame","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Class","role":"symbol","externalID":"c:objc(cs)SDImageFrame","navigatorTitle":[{"text":"SDImageFrame","kind":"identifier"}],"symbolKind":"class","title":"SDImageFrame"},"topicSections":[{"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/init(image:duration:)"],"generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/duration","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/image"],"anchor":"Instance-Properties","generated":true,"title":"Instance Properties"}],"abstract":[{"type":"text","text":"This class is used for creating animated images via "},{"type":"codeVoice","code":"animatedImageWithFrames"},{"text":" in ","type":"text"},{"code":"SDImageCoderHelper","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageframe"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageframe"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"kind":"relationships","type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame/duration":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"}],"url":"\/documentation\/sdwebimage\/sdimageframe\/duration","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/duration","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"duration","kind":"identifier"}],"title":"duration","abstract":[{"text":"The duration of current frame to be displayed. The number is seconds but not milliseconds. You should not set this to zero.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame/frameWithImage:duration:":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/frameWithImage:duration:","title":"frameWithImage:duration:","navigatorTitle":[{"text":"frameWithImage:duration:","kind":"identifier"}],"type":"topic","fragments":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"frameWithImage:duration:"}],"abstract":[{"text":"Create a frame instance with specify image and duration","type":"text"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdimageframe\/framewithimage:duration:","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame/image":{"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"image","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"}],"url":"\/documentation\/sdwebimage\/sdimageframe\/image","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/image","type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"text":"image","kind":"identifier"}],"title":"image","abstract":[{"text":"The image of current frame. You should not set an animated image.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame","title":"SDImageFrame","navigatorTitle":[{"text":"SDImageFrame","kind":"identifier"}],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageFrame","kind":"identifier"}],"abstract":[{"text":"This class is used for creating animated images via ","type":"text"},{"code":"animatedImageWithFrames","type":"codeVoice"},{"text":" in ","type":"text"},{"code":"SDImageCoderHelper","type":"codeVoice"},{"text":".","type":"text"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdimageframe","kind":"symbol"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFrame/init(image:duration:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/init(image:duration:)","title":"init(image:duration:)","navigatorTitle":[{"text":"initWithImage:duration:","kind":"identifier"}],"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"image","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":")","kind":"text"}],"abstract":[{"type":"text","text":"Create a frame instance with specify image and duration"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdimageframe\/init(image:duration:)","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDImageFrame","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"class","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageFrame"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageFrame","kind":"identifier"}]},{"op":"replace","value":[{"generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/duration","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/image"],"title":"Instance Properties","anchor":"Instance-Properties"},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/init(image:duration:)"],"generated":true,"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFrame\/frameWithImage:duration:"],"title":"Type Methods","anchor":"Type-Methods","generated":true}],"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageFrame","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"duration","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame~1duration\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame~1duration\/fragments","value":[{"text":"duration","kind":"identifier"}],"op":"replace"},{"value":"image","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame~1image\/title","op":"replace"},{"value":[{"text":"image","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame~1image\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/title","op":"replace","value":"SDImageFrame"},{"op":"replace","value":[{"text":"SDImageFrame","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame\/navigatorTitle","value":[{"text":"SDImageFrame","kind":"identifier"}],"op":"replace"},{"value":"initWithImage:duration:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame~1init(image:duration:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithImage:duration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFrame~1init(image:duration:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}