{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageloadersmanager"]}],"abstract":[{"text":"A loaders manager to manage multiple loaders","type":"text"}],"sections":[],"relationshipsSections":[{"kind":"relationships","type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"type":"conformsTo"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager"},"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/loaders"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/addLoader(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/removeLoader(_:)"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/shared"],"anchor":"Type-Properties","generated":true,"title":"Type Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageLoadersManager","kind":"identifier"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoadersManager"}],"navigatorTitle":[{"text":"SDImageLoadersManager","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDImageLoadersManager","role":"symbol","roleHeading":"Class","title":"SDImageLoadersManager"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/addLoader(_:)":{"navigatorTitle":[{"kind":"identifier","text":"addLoader:"}],"title":"addLoader(_:)","url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/addloader(_:)","role":"symbol","abstract":[{"type":"text","text":"Add a new image loader to the end of loaders array. Which has the highest priority."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/addLoader(_:)","kind":"symbol","type":"topic","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"addLoader"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader","text":"SDImageLoader"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/shared":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/shared","abstract":[{"type":"text","text":"Returns the global shared loaders manager instance. By default we will set ["},{"code":"SDWebImageDownloader.sharedDownloader","type":"codeVoice"},{"text":"] into the loaders array.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageLoadersManager","text":"SDImageLoadersManager","kind":"typeIdentifier"}],"title":"shared","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/shared"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoadersManager","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager","title":"SDImageLoadersManager","navigatorTitle":[{"kind":"identifier","text":"SDImageLoadersManager"}],"kind":"symbol","abstract":[{"text":"A loaders manager to manage multiple loaders","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/loaders":{"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"loaders","kind":"identifier"},{"kind":"text","text":": [any "},{"text":"SDImageLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader"},{"text":"]?","kind":"text"}],"title":"loaders","kind":"symbol","type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/loaders","navigatorTitle":[{"text":"loaders","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/loaders","abstract":[{"type":"text","text":"All image loaders in manager. The loaders array is a priority queue, which means the later added loader will have the highest priority"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoadersManager/removeLoader(_:)":{"role":"symbol","navigatorTitle":[{"text":"removeLoader:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/removeLoader(_:)","type":"topic","title":"removeLoader(_:)","abstract":[{"type":"text","text":"Remove an image loader in the loaders array."}],"url":"\/documentation\/sdwebimage\/sdimageloadersmanager\/removeloader(_:)","kind":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeLoader"},{"text":"(any ","kind":"text"},{"text":"SDImageLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader"},{"kind":"text","text":")"}]},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDImageLoadersManager"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageLoadersManager"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageLoadersManager","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"replace","value":[{"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/loaders"],"generated":true},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/addLoader(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/removeLoader(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"generated":true,"anchor":"Type-Properties","title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoadersManager\/shared"]}]},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"text":"SDImageLoadersManager","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"text":"SDImageLoader","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageLoader"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle"},{"value":"addLoader:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1addLoader(_:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1addLoader(_:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"addLoader:","kind":"identifier"}],"op":"replace"},{"value":"sharedManager","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1shared\/title"},{"value":[{"kind":"identifier","text":"sharedManager"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1shared\/fragments","op":"replace"},{"value":"SDImageLoadersManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/fragments","value":[{"kind":"identifier","text":"SDImageLoadersManager"}],"op":"replace"},{"value":[{"text":"SDImageLoadersManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager\/navigatorTitle"},{"value":"loaders","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1loaders\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1loaders\/fragments","value":[{"text":"loaders","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1removeLoader(_:)\/title","value":"removeLoader:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoadersManager~1removeLoader(_:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"removeLoader:","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}