{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheadditionalcachepathblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheadditionalcachepathblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheAdditionalCachePathBlock","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}],"title":"SDImageCacheAdditionalCachePathBlock","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:SDImageCacheDefine.h@T@SDImageCacheAdditionalCachePathBlock","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheAdditionalCachePathBlock":{"role":"symbol","title":"SDImageCacheAdditionalCachePathBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheAdditionalCachePathBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}],"url":"\/documentation\/sdwebimage\/sdimagecacheadditionalcachepathblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheAdditionalCachePathBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString *(^)(NSString *)","preciseIdentifier":"c:BF*$objc(cs)NSString(#S2_)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheAdditionalCachePathBlock\/title","value":"SDImageCacheAdditionalCachePathBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheAdditionalCachePathBlock\/fragments","value":[{"kind":"identifier","text":"SDImageCacheAdditionalCachePathBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}