{"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"metadata":{"symbolKind":"typealias","roleHeading":"Type Alias","title":"SDImageCacheQueryDataCompletionBlock","externalID":"c:SDImageCacheDefine.h@T@SDImageCacheQueryDataCompletionBlock","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryDataCompletionBlock"}],"role":"symbol"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"},{"kind":"text","text":" = ("},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","text":"Void","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryDataCompletionBlock","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachequerydatacompletionblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachequerydatacompletionblock"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheQueryDataCompletionBlock":{"type":"topic","abstract":[],"url":"\/documentation\/sdwebimage\/sdimagecachequerydatacompletionblock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheQueryDataCompletionBlock","kind":"symbol","title":"SDImageCacheQueryDataCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheQueryDataCompletionBlock"}],"navigatorTitle":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"path":"\/metadata\/title","op":"replace","value":"SDImageCacheQueryDataCompletionBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"value":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#*$objc(cs)NSData)","text":"void (^)(NSData *)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"value":"SDImageCacheQueryDataCompletionBlock","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryDataCompletionBlock\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryDataCompletionBlock\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryDataCompletionBlock"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheQueryDataCompletionBlock\/navigatorTitle","value":[{"text":"SDImageCacheQueryDataCompletionBlock","kind":"identifier"}]}]}]}