{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageFormat","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}],"roleHeading":"Structure","title":"SDImageFormat","symbolKind":"struct","modules":[{"name":"SDWebImage"}],"externalID":"c:NSData+ImageContentType.h@T@SDImageFormat","role":"symbol"},"abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"text":"For custom coder plugin, it can also extern the enum for supported format. See ","type":"text"},{"code":"SDImageCoder","type":"codeVoice"},{"text":" for more detailed information.","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"struct","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}]}],"kind":"declarations"}],"sections":[],"relationshipsSections":[{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"title":"Conforms To","kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageformat"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageformat"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","interfaceLanguage":"swift"},"kind":"symbol","topicSections":[{"generated":true,"title":"Initializers","anchor":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/init(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/BMP","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/GIF","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/HEIC","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/HEIF","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/JPEG","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/PDF","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/PNG","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/RAW","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/SVG","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/TIFF","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/undefined","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/webP"],"anchor":"Type-Properties","generated":true},{"title":"Default Implementations","generated":true,"anchor":"Default-Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/_SwiftNewtypeWrapper-Implementations"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/_SwiftNewtypeWrapper-Implementations":{"url":"\/documentation\/sdwebimage\/sdimageformat\/_swiftnewtypewrapper-implementations","type":"topic","role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/_SwiftNewtypeWrapper-Implementations","abstract":[],"title":"_SwiftNewtypeWrapper Implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/init(_:)":{"abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/init(_:)","url":"\/documentation\/sdwebimage\/sdimageformat\/init(_:)","title":"init(_:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"Int","kind":"typeIdentifier","preciseIdentifier":"s:Si"},{"text":")","kind":"text"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/webP":{"abstract":[],"title":"webP","navigatorTitle":[{"text":"SDImageFormatWebP","kind":"identifier"}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"webP","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/webP","url":"\/documentation\/sdwebimage\/sdimageformat\/webp","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/Equatable-Implementations":{"kind":"article","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/Equatable-Implementations","type":"topic","url":"\/documentation\/sdwebimage\/sdimageformat\/equatable-implementations","title":"Equatable Implementations","role":"collectionGroup"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/undefined":{"type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"undefined"},{"text":": ","kind":"text"},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/undefined","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageFormatUndefined"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/undefined","title":"undefined"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/GIF":{"url":"\/documentation\/sdwebimage\/sdimageformat\/gif","title":"GIF","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SDImageFormatGIF"}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/GIF","role":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"GIF","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/BMP":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/BMP","abstract":[],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"BMP","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","kind":"typeIdentifier"}],"title":"BMP","navigatorTitle":[{"text":"SDImageFormatBMP","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimageformat\/bmp"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/init(rawValue:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"rawValue","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:Si","kind":"typeIdentifier","text":"Int"},{"kind":"text","text":")"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/init(rawvalue:)","role":"symbol","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/init(rawValue:)","title":"init(rawValue:)"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/PNG":{"url":"\/documentation\/sdwebimage\/sdimageformat\/png","kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"PNG"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageFormat","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/PNG","type":"topic","navigatorTitle":[{"text":"SDImageFormatPNG","kind":"identifier"}],"abstract":[],"role":"symbol","title":"PNG"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/JPEG":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"JPEG","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/jpeg","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageFormatJPEG"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/JPEG","title":"JPEG"},"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","title":"Swift.BitwiseCopyable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/PDF":{"type":"topic","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"PDF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/pdf","role":"symbol","abstract":[],"kind":"symbol","navigatorTitle":[{"text":"SDImageFormatPDF","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/PDF","title":"PDF"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/HEIC":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/HEIC","navigatorTitle":[{"kind":"identifier","text":"SDImageFormatHEIC"}],"title":"HEIC","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageformat\/heic","abstract":[],"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"HEIC"},{"kind":"text","text":": "},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat":{"kind":"symbol","title":"SDImageFormat","role":"symbol","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"text":"SDImageFormat","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"You can use switch case like normal enum. It’s also recommended to add a default case. You should not assume anything about the raw value."},{"text":" ","type":"text"},{"type":"text","text":"For custom coder plugin, it can also extern the enum for supported format. See "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" for more detailed information."}],"url":"\/documentation\/sdwebimage\/sdimageformat","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat","navigatorTitle":[{"kind":"identifier","text":"SDImageFormat"}]},"doc://com.dailymotion.SDWebImage/s8SendableP":{"title":"Swift.Sendable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/TIFF":{"role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"TIFF","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageFormatTIFF"}],"title":"TIFF","kind":"symbol","abstract":[],"url":"\/documentation\/sdwebimage\/sdimageformat\/tiff","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/TIFF"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/RAW":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/RAW","type":"topic","url":"\/documentation\/sdwebimage\/sdimageformat\/raw","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageFormatRAW"}],"kind":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"RAW","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"abstract":[],"title":"RAW"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/SVG":{"role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SVG","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageFormatSVG"}],"title":"SVG","kind":"symbol","abstract":[],"url":"\/documentation\/sdwebimage\/sdimageformat\/svg","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/SVG"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFormat/HEIF":{"navigatorTitle":[{"text":"SDImageFormatHEIF","kind":"identifier"}],"title":"HEIF","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFormat\/HEIF","type":"topic","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"HEIF","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat","text":"SDImageFormat","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdimageformat\/heif","abstract":[]}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","value":"SDImageFormat","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"typealias"},{"value":[{"kind":"identifier","text":"SDImageFormat"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageFormat"}],"op":"replace"},{"op":"replace","value":null,"path":"\/topicSections"},{"op":"replace","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSInteger","text":"NSInteger"},{"text":" ","kind":"text"},{"text":"SDImageFormat","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1webP\/title","value":"SDImageFormatWebP"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1webP\/fragments","op":"replace","value":[{"text":"SDImageFormatWebP","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1undefined\/title","value":"SDImageFormatUndefined"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1undefined\/fragments","value":[{"text":"SDImageFormatUndefined","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDImageFormatGIF","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1GIF\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1GIF\/fragments","value":[{"text":"SDImageFormatGIF","kind":"identifier"}]},{"value":"SDImageFormatBMP","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1BMP\/title","op":"replace"},{"value":[{"text":"SDImageFormatBMP","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1BMP\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1PNG\/title","value":"SDImageFormatPNG","op":"replace"},{"value":[{"text":"SDImageFormatPNG","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1PNG\/fragments"},{"op":"replace","value":"SDImageFormatJPEG","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1JPEG\/title"},{"value":[{"kind":"identifier","text":"SDImageFormatJPEG"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1JPEG\/fragments","op":"replace"},{"value":"SDImageFormatPDF","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1PDF\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1PDF\/fragments","value":[{"kind":"identifier","text":"SDImageFormatPDF"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1HEIC\/title","value":"SDImageFormatHEIC"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1HEIC\/fragments","value":[{"kind":"identifier","text":"SDImageFormatHEIC"}]},{"value":"SDImageFormat","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/title","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageFormat"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/fragments"},{"value":[{"text":"SDImageFormat","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1TIFF\/title","op":"replace","value":"SDImageFormatTIFF"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1TIFF\/fragments","value":[{"text":"SDImageFormatTIFF","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1RAW\/title","value":"SDImageFormatRAW"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageFormatRAW"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1RAW\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1SVG\/title","value":"SDImageFormatSVG","op":"replace"},{"value":[{"text":"SDImageFormatSVG","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1SVG\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1HEIF\/title","value":"SDImageFormatHEIF"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFormat~1HEIF\/fragments","value":[{"text":"SDImageFormatHEIF","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}