{"topicSections":[{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/animatedImageUTType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/defaultLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/delayTimeProperty","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/dictionaryProperty","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/imageFormat","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/imageUTType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/loopCountProperty","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/unclampedDelayTimeProperty"],"anchor":"Type-Properties"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","interfaceLanguage":"swift"},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder"],"kind":"relationships","title":"Inherited By","type":"inheritedBy"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageioanimatedcoder"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"title":"SDImageIOAnimatedCoder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"roleHeading":"Class","modules":[{"name":"SDWebImage"}],"role":"symbol","externalID":"c:objc(cs)SDImageIOAnimatedCoder","symbolKind":"class"},"abstract":[{"type":"text","text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class."},{"text":" ","type":"text"},{"text":"All of the properties need the subclass to implement and works as expected.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"platforms":["iOS"]}]}],"references":{"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageGIFCoder":{"kind":"symbol","type":"topic","title":"SDImageGIFCoder","navigatorTitle":[{"text":"SDImageGIFCoder","kind":"identifier"}],"abstract":[{"text":"Built in coder using ImageIO that supports animated GIF encoding\/decoding","type":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","url":"\/documentation\/sdwebimage\/sdimagegifcoder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageGIFCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/imageFormat":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/imageFormat","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageFormat","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDImageFormat","kind":"typeIdentifier","preciseIdentifier":"c:NSData+ImageContentType.h@T@SDImageFormat"}],"navigatorTitle":[{"text":"imageFormat","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/imageformat","title":"imageFormat","type":"topic","abstract":[{"type":"text","text":"The supported animated image format. Such as "},{"code":"SDImageFormatGIF","type":"codeVoice"},{"type":"text","text":"."}]},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageHEICCoder":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageheiccoder","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageHEICCoder"}],"navigatorTitle":[{"text":"SDImageHEICCoder","kind":"identifier"}],"abstract":[{"text":"This coder is used for HEIC (HEIF with HEVC container codec) image format.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the static HEIC (.heic) support in iOS 11\/macOS 10.13\/tvOS 11\/watchOS 4+."},{"text":" ","type":"text"},{"type":"text","text":"Image\/IO provide the animated HEIC (.heics) support in iOS 13\/macOS 10.15\/tvOS 13\/watchOS 6+."},{"type":"text","text":" "},{"type":"text","text":"See https:\/\/nokiatech.github.io\/heif\/technical.html for the standard."}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder","title":"SDImageHEICCoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/defaultLoopCount":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/defaultLoopCount","url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/defaultloopcount","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"defaultLoopCount","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"type":"topic","kind":"symbol","abstract":[{"text":"The default loop count when there are no any loop count information inside image container metadata.","type":"text"},{"type":"text","text":" "},{"text":"For example, for GIF format, the standard use 1 (play once). For APNG format, the standard use 0 (infinity loop).","type":"text"}],"title":"defaultLoopCount","navigatorTitle":[{"kind":"identifier","text":"defaultLoopCount"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"type":"topic","title":"SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder","navigatorTitle":[{"text":"SDImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the image coder protocol to provide custom image decoding\/encoding.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods are all required to implement."}]},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/dictionaryProperty":{"abstract":[{"text":"The image container property key used in Image\/IO API. Such as ","type":"text"},{"code":"kCGImagePropertyGIFDictionary","type":"codeVoice"},{"type":"text","text":"."}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"dictionaryProperty"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"title":"dictionaryProperty","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/dictionaryProperty","navigatorTitle":[{"text":"dictionaryProperty","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/dictionaryproperty","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"text":" ","type":"text"},{"text":"These methods are all required to implement.","type":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder","title":"SDProgressiveImageCoder","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder","type":"topic","title":"SDImageIOAnimatedCoder","kind":"symbol","abstract":[{"text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"role":"symbol","navigatorTitle":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAPNGCoder":{"type":"topic","title":"SDImageAPNGCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAPNGCoder","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimageapngcoder","navigatorTitle":[{"kind":"identifier","text":"SDImageAPNGCoder"}],"kind":"symbol","abstract":[{"type":"text","text":"Built in coder using ImageIO that supports APNG encoding\/decoding"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/imageUTType":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/imageuttype","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/imageUTType","abstract":[{"type":"text","text":"The supported image format UTI Type. Such as "},{"type":"codeVoice","code":"kSDUTTypeGIF"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This can be used for cases when we can not detect "},{"code":"SDImageFormat. Such as progressive decoding's hint format ","type":"codeVoice"},{"type":"text","text":"kCGImageSourceTypeIdentifierHint`."}],"title":"imageUTType","navigatorTitle":[{"kind":"identifier","text":"imageUTType"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageUTType"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"kind":"symbol","type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/delayTimeProperty":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delayTimeProperty"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/delayTimeProperty","navigatorTitle":[{"kind":"identifier","text":"delayTimeProperty"}],"abstract":[{"type":"text","text":"The image delay time property key used in Image\/IO API. Such as "},{"type":"codeVoice","code":"kCGImagePropertyGIFDelayTime"},{"text":".","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/delaytimeproperty","kind":"symbol","title":"delayTimeProperty","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"type":"topic","abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"code":"SDAnimatedImageCoder","type":"codeVoice"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"title":"SDAnimatedImageProvider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/loopCountProperty":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/loopcountproperty","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/loopCountProperty","role":"symbol","abstract":[{"text":"The image loop count property key used in Image\/IO API. Such as ","type":"text"},{"type":"codeVoice","code":"kCGImagePropertyGIFLoopCount"},{"text":".","type":"text"}],"title":"loopCountProperty","kind":"symbol","type":"topic","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loopCountProperty"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"loopCountProperty","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/animatedImageUTType":{"abstract":[{"type":"text","text":"Some image codec use different UTI Type between animated image and static image."},{"type":"text","text":" "},{"text":"For this case, override this method and return the UTI for animated image encoding.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/animatedimageuttype","title":"animatedImageUTType","navigatorTitle":[{"text":"animatedImageUTType","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"animatedImageUTType","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/animatedImageUTType","role":"symbol","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder/unclampedDelayTimeProperty":{"navigatorTitle":[{"text":"unclampedDelayTimeProperty","kind":"identifier"}],"abstract":[{"text":"The image unclamped delay time property key used in Image\/IO  API. Such as ","type":"text"},{"code":"kCGImagePropertyGIFUnclampedDelayTime","type":"codeVoice"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/unclampedDelayTimeProperty","url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder\/unclampeddelaytimeproperty","title":"unclampedDelayTimeProperty","kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"unclampedDelayTimeProperty","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAWebPCoder","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"text":" ","type":"text"},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"url":"\/documentation\/sdwebimage\/sdimageawebpcoder","title":"SDImageAWebPCoder"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDImageIOAnimatedCoder"},{"value":"class","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/animatedImageUTType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/defaultLoopCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/delayTimeProperty","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/dictionaryProperty","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/imageFormat","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/imageUTType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/loopCountProperty","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder\/unclampedDelayTimeProperty"],"generated":true,"anchor":"Type-Properties","title":"Type Properties"}],"op":"replace"},{"path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAPNGCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageGIFCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageHEICCoder"],"kind":"relationships","type":"inheritedBy","title":"Inherited By"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"],"kind":"relationships","title":"Conforms To"}],"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageIOAnimatedCoder"},{"kind":"text","text":" : "},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/title","value":"SDImageGIFCoder","op":"replace"},{"value":[{"text":"SDImageGIFCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/fragments"},{"value":[{"text":"SDImageGIFCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageGIFCoder\/navigatorTitle"},{"value":"imageFormat","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1imageFormat\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1imageFormat\/fragments","value":[{"text":"imageFormat","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/title","value":"SDImageHEICCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/fragments","value":[{"kind":"identifier","text":"SDImageHEICCoder"}]},{"value":[{"text":"SDImageHEICCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageHEICCoder\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1defaultLoopCount\/title","value":"defaultLoopCount"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1defaultLoopCount\/fragments","value":[{"kind":"identifier","text":"defaultLoopCount"}]},{"value":"SDImageCoder","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/navigatorTitle","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1dictionaryProperty\/title","value":"dictionaryProperty"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1dictionaryProperty\/fragments","value":[{"text":"dictionaryProperty","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDProgressiveImageCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title"},{"value":[{"text":"SDProgressiveImageCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments"},{"value":[{"text":"SDProgressiveImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/navigatorTitle","op":"replace"},{"value":"SDAnimatedImageCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","op":"replace"},{"value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments"},{"value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle"},{"op":"replace","value":"SDImageIOAnimatedCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title"},{"value":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments"},{"value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/title","op":"replace","value":"SDImageAPNGCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/fragments","op":"replace","value":[{"text":"SDImageAPNGCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAPNGCoder\/navigatorTitle","op":"replace","value":[{"text":"SDImageAPNGCoder","kind":"identifier"}]},{"value":"imageUTType","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1imageUTType\/title"},{"value":[{"kind":"identifier","text":"imageUTType"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1imageUTType\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1delayTimeProperty\/title","value":"delayTimeProperty"},{"op":"replace","value":[{"text":"delayTimeProperty","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1delayTimeProperty\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","value":"SDAnimatedImageProvider","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments","value":[{"kind":"identifier","text":"SDAnimatedImageProvider"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/navigatorTitle","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"loopCountProperty","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1loopCountProperty\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1loopCountProperty\/fragments","value":[{"text":"loopCountProperty","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1animatedImageUTType\/title","op":"replace","value":"animatedImageUTType"},{"op":"replace","value":[{"text":"animatedImageUTType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1animatedImageUTType\/fragments"},{"value":"unclampedDelayTimeProperty","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1unclampedDelayTimeProperty\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder~1unclampedDelayTimeProperty\/fragments","value":[{"kind":"identifier","text":"unclampedDelayTimeProperty"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/title","value":"SDImageAWebPCoder","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/fragments","value":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/navigatorTitle","value":[{"text":"SDImageAWebPCoder","kind":"identifier"}]}]}]}