{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloadersetprogressivecoder(_:_:)"]},{"paths":["\/documentation\/sdwebimage\/sdimageloadersetprogressivecoder(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderSetProgressiveCoder(_:_:)"},"abstract":[{"type":"text","text":"This function set the progressive decoder for current loading operation. If no progressive decoding is happended, pass nil."}],"metadata":{"symbolKind":"func","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoaderSetProgressiveCoder","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageOperation","text":"SDWebImageOperation"},{"kind":"text","text":", (any "},{"preciseIdentifier":"c:objc(pl)SDProgressiveImageCoder","text":"SDProgressiveImageCoder","kind":"typeIdentifier"},{"kind":"text","text":")?)"}],"externalID":"c:@F@SDImageLoaderSetProgressiveCoder","modules":[{"name":"SDWebImage"}],"roleHeading":"Function","role":"symbol","title":"SDImageLoaderSetProgressiveCoder(_:_:)","navigatorTitle":[{"text":"SDImageLoaderSetProgressiveCoder","kind":"identifier"}]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoaderSetProgressiveCoder"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"operation","kind":"internalParam"},{"kind":"text","text":": any "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","text":"SDWebImageOperation","preciseIdentifier":"c:objc(pl)SDWebImageOperation","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"progressiveCoder","kind":"internalParam"},{"kind":"text","text":": (any "},{"kind":"typeIdentifier","text":"SDProgressiveImageCoder","preciseIdentifier":"c:objc(pl)SDProgressiveImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"},{"kind":"text","text":")?)"}]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The loading operation to associate the progerssive decoder.","type":"text"}]}],"name":"progressiveCoder"}]}],"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"text":" ","type":"text"},{"text":"These methods are all required to implement.","type":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder","title":"SDProgressiveImageCoder","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"url":"\/documentation\/sdwebimage\/sdwebimageoperation","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOperation"}],"navigatorTitle":[{"text":"SDWebImageOperation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SDWebImageOperation","abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderSetProgressiveCoder(_:_:)":{"title":"SDImageLoaderSetProgressiveCoder(_:_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderSetProgressiveCoder(_:_:)","type":"topic","url":"\/documentation\/sdwebimage\/sdimageloadersetprogressivecoder(_:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageLoaderSetProgressiveCoder"},{"text":"(any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDWebImageOperation","text":"SDWebImageOperation","kind":"typeIdentifier"},{"text":", (any ","kind":"text"},{"text":"SDProgressiveImageCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDProgressiveImageCoder"},{"kind":"text","text":")?)"}],"navigatorTitle":[{"text":"SDImageLoaderSetProgressiveCoder","kind":"identifier"}],"abstract":[{"text":"This function set the progressive decoder for current loading operation. If no progressive decoding is happended, pass nil.","type":"text"}],"kind":"symbol","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Function","op":"replace"},{"op":"replace","value":"SDImageLoaderSetProgressiveCoder","path":"\/metadata\/title"},{"value":"func","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDImageLoaderSetProgressiveCoder","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"text":" ","kind":"text"},{"text":"SDImageLoaderSetProgressiveCoder","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:Qoobjc(pl)SDWebImageOperation","text":"id<SDWebImageOperation>","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"operation","kind":"internalParam"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDProgressiveImageCoder","text":"id<SDProgressiveImageCoder>"},{"kind":"text","text":" "},{"text":"progressiveCoder","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"replace","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The loading operation to associate the progerssive decoder."}]}],"name":"progressiveCoder"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title","value":"SDProgressiveImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments","value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},{"value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title","value":"SDWebImageOperation","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments","value":[{"text":"SDWebImageOperation","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageOperation"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderSetProgressiveCoder(_:_:)\/title","op":"replace","value":"SDImageLoaderSetProgressiveCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderSetProgressiveCoder(_:_:)\/fragments","value":[{"text":"SDImageLoaderSetProgressiveCoder","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}