{"sections":[],"abstract":[{"type":"text","text":"This function get the progressive decoder for current loading operation. If no progressive decoding is happended or decoder is not able to construct, return nil."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoaderGetProgressiveCoder","kind":"identifier"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"operation","kind":"internalParam"},{"text":": any ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","text":"SDWebImageOperation","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageOperation"},{"text":") -> (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDProgressiveImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","text":"SDProgressiveImageCoder","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The progressive decoder associated with the loading operation.","type":"text"}],"type":"paragraph"}]}],"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"title":"SDImageLoaderGetProgressiveCoder(_:)","externalID":"c:@F@SDImageLoaderGetProgressiveCoder","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageLoaderGetProgressiveCoder","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDWebImageOperation","text":"SDWebImageOperation"},{"kind":"text","text":") -> (any "},{"kind":"typeIdentifier","text":"SDProgressiveImageCoder","preciseIdentifier":"c:objc(pl)SDProgressiveImageCoder"},{"kind":"text","text":")?"}],"symbolKind":"func","role":"symbol","roleHeading":"Function","navigatorTitle":[{"text":"SDImageLoaderGetProgressiveCoder","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloadergetprogressivecoder(_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageloadergetprogressivecoder(_:)"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderGetProgressiveCoder(_:)","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderGetProgressiveCoder(_:)":{"abstract":[{"type":"text","text":"This function get the progressive decoder for current loading operation. If no progressive decoding is happended or decoder is not able to construct, return nil."}],"title":"SDImageLoaderGetProgressiveCoder(_:)","type":"topic","url":"\/documentation\/sdwebimage\/sdimageloadergetprogressivecoder(_:)","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageLoaderGetProgressiveCoder"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderGetProgressiveCoder(_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoaderGetProgressiveCoder","kind":"identifier"},{"kind":"text","text":"(any "},{"preciseIdentifier":"c:objc(pl)SDWebImageOperation","kind":"typeIdentifier","text":"SDWebImageOperation"},{"text":") -> (any ","kind":"text"},{"text":"SDProgressiveImageCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDProgressiveImageCoder"},{"kind":"text","text":")?"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"url":"\/documentation\/sdwebimage\/sdwebimageoperation","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOperation"}],"navigatorTitle":[{"text":"SDWebImageOperation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SDWebImageOperation","abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"text":" ","type":"text"},{"text":"These methods are all required to implement.","type":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder","title":"SDProgressiveImageCoder","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"value":"SDImageLoaderGetProgressiveCoder","op":"replace","path":"\/metadata\/title"},{"value":"func","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageLoaderGetProgressiveCoder"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"id<SDProgressiveImageCoder>","preciseIdentifier":"c:Qoobjc(pl)SDProgressiveImageCoder","kind":"typeIdentifier"},{"kind":"text","text":" "},{"text":"SDImageLoaderGetProgressiveCoder","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDWebImageOperation","text":"id<SDWebImageOperation>"},{"text":" ","kind":"text"},{"text":"operation","kind":"internalParam"},{"text":");","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The progressive decoder associated with the loading operation."}]}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"SDImageLoaderGetProgressiveCoder","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderGetProgressiveCoder(_:)\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageLoaderGetProgressiveCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderGetProgressiveCoder(_:)\/fragments"},{"value":"SDWebImageOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments","value":[{"text":"SDWebImageOperation","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageOperation"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title","value":"SDProgressiveImageCoder","op":"replace"},{"value":[{"text":"SDProgressiveImageCoder","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/navigatorTitle","value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]}]}]}