{"abstract":[{"type":"text","text":"Image blur effect transformer"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"relationshipsSections":[{"title":"Inherits From","type":"inheritsFrom","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"sections":[],"metadata":{"roleHeading":"Class","modules":[{"name":"SDWebImage"}],"role":"symbol","title":"SDImageBlurTransformer","symbolKind":"class","navigatorTitle":[{"text":"SDImageBlurTransformer","kind":"identifier"}],"externalID":"c:objc(cs)SDImageBlurTransformer","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBlurTransformer"}]},"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/init(radius:)"],"anchor":"Initializers","title":"Initializers","generated":true},{"generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/blurRadius"],"title":"Instance Properties","anchor":"Instance-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageBlurTransformer","kind":"identifier"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageblurtransformer"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageblurtransformer"]}],"references":{"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer/blurRadius":{"url":"\/documentation\/sdwebimage\/sdimageblurtransformer\/blurradius","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"blurRadius","kind":"identifier"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"}],"title":"blurRadius","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/blurRadius","abstract":[{"type":"text","text":"The radius of the blur in points, 0 means no blur effect."}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"blurRadius"}]},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer/init(radius:)":{"navigatorTitle":[{"kind":"identifier","text":"transformerWithRadius:"}],"url":"\/documentation\/sdwebimage\/sdimageblurtransformer\/init(radius:)","title":"init(radius:)","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/init(radius:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"radius","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable","title":"Swift.CVarArg"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBlurTransformer":{"url":"\/documentation\/sdwebimage\/sdimageblurtransformer","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBlurTransformer"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer","type":"topic","navigatorTitle":[{"text":"SDImageBlurTransformer","kind":"identifier"}],"abstract":[{"text":"Image blur effect transformer","type":"text"}],"role":"symbol","title":"SDImageBlurTransformer"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageBaseTransformer":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageBaseTransformer"}],"url":"\/documentation\/sdwebimage\/sdimagebasetransformer","title":"SDImageBaseTransformer","abstract":[{"text":"This is the base class for our built-in concrete transformers. You should not use this class directlly, use cconcrete subclass (like ","type":"text"},{"code":"SDImageRoundCornerTransformer","type":"codeVoice"},{"text":") instead.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageBaseTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDImageBlurTransformer","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageBlurTransformer","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDImageBlurTransformer"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/blurRadius"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBlurTransformer\/init(radius:)"],"title":"Type Methods","anchor":"Type-Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"}]},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageBlurTransformer","kind":"identifier"},{"kind":"text","text":" : "},{"preciseIdentifier":"c:objc(cs)SDImageBaseTransformer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageBaseTransformer","text":"SDImageBaseTransformer","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"op":"replace","value":"SDImageTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title"},{"op":"replace","value":[{"text":"SDImageTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments"},{"value":[{"kind":"identifier","text":"SDImageTransformer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle","op":"replace"},{"value":"blurRadius","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer~1blurRadius\/title","op":"replace"},{"op":"replace","value":[{"text":"blurRadius","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer~1blurRadius\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer~1init(radius:)\/title","value":"transformerWithRadius:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer~1init(radius:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"transformerWithRadius:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/title","value":"SDImageBlurTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/fragments","value":[{"kind":"identifier","text":"SDImageBlurTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBlurTransformer\/navigatorTitle","value":[{"text":"SDImageBlurTransformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/title","value":"SDImageBaseTransformer","op":"replace"},{"value":[{"text":"SDImageBaseTransformer","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageBaseTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageBaseTransformer"}]}]}]}