{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"platforms":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"name":"iPadOS","deprecated":false,"introducedAt":"14.0","unavailable":false,"beta":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageAWebPCoder"}],"externalID":"c:objc(cs)SDImageAWebPCoder","role":"symbol","title":"SDImageAWebPCoder","symbolKind":"class","roleHeading":"Class","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAWebPCoder","kind":"identifier"}]},"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"type":"text","text":" "},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"topicSections":[{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder\/shared"],"generated":true,"anchor":"Type-Properties"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageawebpcoder"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageawebpcoder"]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAWebPCoder","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"text":"Overview","level":2,"anchor":"overview","type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"Currently Image\/IO seems does not supports WebP encoding, if you need WebP encoding, use the custom codec below."}],"type":"paragraph"}],"style":"note","type":"aside","name":"Note"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"type":"text","text":"If you need to support lower firmware version for WebP, you can have a try at https:\/\/github.com\/SDWebImage\/SDWebImageWebPCoder"}],"type":"paragraph"}],"style":"note"}],"kind":"content"}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"kind":"relationships","title":"Conforms To","type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"]}],"sections":[],"schemaVersion":{"major":0,"patch":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder"},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageProvider":{"type":"topic","abstract":[{"type":"text","text":"This is the animated image protocol to provide the basic function for animated image rendering. It’s adopted by "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" and "},{"code":"SDAnimatedImageCoder","type":"codeVoice"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageProvider","url":"\/documentation\/sdwebimage\/sdanimatedimageprovider","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"text":"SDAnimatedImageProvider","kind":"identifier"}],"navigatorTitle":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"title":"SDAnimatedImageProvider"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoder":{"type":"topic","title":"SDImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCoder"}],"url":"\/documentation\/sdwebimage\/sdimagecoder","navigatorTitle":[{"text":"SDImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the image coder protocol to provide custom image decoding\/encoding.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"These methods are all required to implement."}]},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder","type":"topic","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageAWebPCoder","kind":"identifier"}],"role":"symbol","navigatorTitle":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"abstract":[{"type":"text","text":"This coder is used for Google WebP and Animated WebP(AWebP) image format."},{"text":" ","type":"text"},{"type":"text","text":"Image\/IO provide the WebP decoding support in iOS 14\/macOS 11\/tvOS 14\/watchOS 7+."}],"url":"\/documentation\/sdwebimage\/sdimageawebpcoder","title":"SDImageAWebPCoder"},"doc://com.dailymotion.SDWebImage/SH":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageAWebPCoder/shared":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageAWebPCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageAWebPCoder"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimageawebpcoder\/shared","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder\/shared","title":"shared","type":"topic","abstract":[],"navigatorTitle":[{"text":"sharedCoder","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageIOAnimatedCoder":{"url":"\/documentation\/sdwebimage\/sdimageioanimatedcoder","type":"topic","title":"SDImageIOAnimatedCoder","kind":"symbol","abstract":[{"text":"This is the abstract class for all animated coder, which use the Image\/IO API. You can not use this directly as real coders. A exception will be raised if you use this class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of the properties need the subclass to implement and works as expected."},{"type":"text","text":" "},{"type":"text","text":"For Image\/IO, See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/imageio"}],"role":"symbol","navigatorTitle":[{"text":"SDImageIOAnimatedCoder","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageIOAnimatedCoder","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDProgressiveImageCoder":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDProgressiveImageCoder"}],"abstract":[{"type":"text","text":"This is the image coder protocol to provide custom progressive image decoding."},{"text":" ","type":"text"},{"text":"These methods are all required to implement.","type":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdprogressiveimagecoder","title":"SDProgressiveImageCoder","type":"topic","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDProgressiveImageCoder"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDAnimatedImageCoder":{"type":"topic","title":"SDAnimatedImageCoder","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDAnimatedImageCoder"}],"url":"\/documentation\/sdwebimage\/sdanimatedimagecoder","navigatorTitle":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"This is the animated image coder protocol for custom animated image class like  ","type":"text"},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":". Through it inherit from ","type":"text"},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":". We currentlly only use the method "},{"type":"codeVoice","code":"canDecodeFromData:"},{"text":" to detect the proper coder for specify animated image format.","type":"text"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/platforms","value":[{"introducedAt":"14.0","unavailable":false,"beta":false,"name":"iOS","deprecated":false},{"name":"iPadOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"beta":false,"unavailable":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0"}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"value":"SDImageAWebPCoder","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"kind":"identifier","text":"SDImageAWebPCoder"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SDImageAWebPCoder","kind":"identifier"}]},{"path":"\/topicSections","op":"replace","value":[{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageAWebPCoder\/shared"],"generated":true,"anchor":"Type-Properties"}]},{"value":[{"kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder"],"title":"Inherits From"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDAnimatedImageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDProgressiveImageCoder"],"kind":"relationships"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SDImageAWebPCoder","kind":"identifier"},{"kind":"text","text":" : "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageIOAnimatedCoder","kind":"typeIdentifier","text":"SDImageIOAnimatedCoder","preciseIdentifier":"c:objc(cs)SDImageIOAnimatedCoder"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/title","value":"SDAnimatedImageProvider"},{"op":"replace","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageProvider\/navigatorTitle","value":[{"text":"SDAnimatedImageProvider","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/title","value":"SDImageCoder"},{"value":[{"kind":"identifier","text":"SDImageCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoder\/navigatorTitle","value":[{"text":"SDImageCoder","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/title","value":"SDImageAWebPCoder","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/fragments","value":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder\/navigatorTitle","value":[{"text":"SDImageAWebPCoder","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder~1shared\/title","value":"sharedCoder"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageAWebPCoder~1shared\/fragments","op":"replace","value":[{"text":"sharedCoder","kind":"identifier"}]},{"op":"replace","value":"SDImageIOAnimatedCoder","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/fragments","value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageIOAnimatedCoder\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDImageIOAnimatedCoder"}]},{"value":"SDProgressiveImageCoder","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/title"},{"value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDProgressiveImageCoder"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDProgressiveImageCoder\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/title","value":"SDAnimatedImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/fragments","value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}]},{"value":[{"text":"SDAnimatedImageCoder","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDAnimatedImageCoder\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}