{"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper","interfaceLanguage":"swift"},"relationshipsSections":[{"title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","kind":"relationships"}],"topicSections":[{"anchor":"Type-Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultDecodeSolution","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultScaleDownLimitBytes"],"title":"Type Properties"},{"title":"Type Methods","generated":true,"anchor":"Type-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/animatedImage(with:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageContainsAlpha(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:orientation:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateScaled(_:size:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHDR(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHardwareSupported(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsLazy(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/colorSpaceGetDeviceRGB()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedAndScaledDownImage(with:limitBytes:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedAndScaledDownImage(with:limitBytes:policy:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:policy:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/exifOrientation(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/frames(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/imageOrientation(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/preferredPixelFormat(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)"]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecoderhelper"]}],"abstract":[{"type":"text","text":"Provide some common helper methods for building the image decoder\/encoder."}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"role":"symbol","roleHeading":"Class","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCoderHelper"}],"title":"SDImageCoderHelper","externalID":"c:objc(cs)SDImageCoderHelper","navigatorTitle":[{"text":"SDImageCoderHelper","kind":"identifier"}],"symbolKind":"class"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCoderHelper","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/imageOrientation(from:)":{"type":"topic","abstract":[{"type":"text","text":"Convert an EXIF image orientation to an iOS one."}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/imageorientation(from:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageOrientation","kind":"identifier"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"CGImagePropertyOrientation","kind":"typeIdentifier","preciseIdentifier":"c:@E@CGImagePropertyOrientation"},{"kind":"text","text":") -> "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageOrientation","text":"Orientation","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"imageOrientationFromEXIFOrientation:","kind":"identifier"}],"kind":"symbol","title":"imageOrientation(from:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/imageOrientation(from:)"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","title":"Swift.Hashable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/defaultScaleDownLimitBytes":{"type":"topic","abstract":[{"type":"text","text":"Control the default limit bytes to scale down largest images."},{"text":" ","type":"text"},{"type":"text","text":"This value must be larger than 4 Bytes (at least 1x1 pixel). Defaults to 60MB on iOS\/tvOS, 90MB on macOS, 30MB on watchOS."}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/defaultscaledownlimitbytes","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"defaultScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"defaultScaleDownLimitBytes","kind":"identifier"}],"kind":"symbol","title":"defaultScaleDownLimitBytes","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultScaleDownLimitBytes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageContainsAlpha(_:)":{"title":"cgImageContainsAlpha(_:)","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageContainsAlpha(_:)","type":"topic","navigatorTitle":[{"text":"CGImageContainsAlpha:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecontainsalpha(_:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageContainsAlpha"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"abstract":[{"text":"Check whether CGImage contains alpha channel.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageIsHardwareSupported(_:)":{"navigatorTitle":[{"kind":"identifier","text":"CGImageIsHardwareSupported:"}],"role":"symbol","title":"cgImageIsHardwareSupported(_:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHardwareSupported(_:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishardwaresupported(_:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"cgImageIsHardwareSupported","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"abstract":[{"text":"Check whether CGImage is hardware supported to rendering on screen, without the trigger of ","type":"text"},{"type":"codeVoice","code":"CA::Render::copy_image"},{"type":"text","text":" "},{"type":"text","text":"You can debug the copied image by using Xcode’s "},{"code":"Color Copied Image","type":"codeVoice"},{"text":", the copied image will turn Cyan and occupy double RAM for bitmap buffer.","type":"text"},{"type":"text","text":" "},{"text":"Typically, when the CGImage’s using the method above (","type":"text"},{"type":"codeVoice","code":"colorspace"},{"text":" \/ ","type":"text"},{"type":"codeVoice","code":"alignment"},{"type":"text","text":" \/ "},{"code":"bitmapInfo","type":"codeVoice"},{"type":"text","text":") can render withtout the copy."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/preferredPixelFormat(_:)":{"navigatorTitle":[{"text":"preferredPixelFormat:","kind":"identifier"}],"role":"symbol","title":"preferredPixelFormat(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/preferredPixelFormat(_:)","type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/preferredpixelformat(_:)","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"preferredPixelFormat"},{"kind":"text","text":"("},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"text":") -> ","kind":"text"},{"text":"SDImagePixelFormat","preciseIdentifier":"c:@S@SDImagePixelFormat","kind":"typeIdentifier"}],"abstract":[{"text":"Tthis returns the pixel format ","type":"text"},{"inlineContent":[{"type":"text","text":"Preferred from current hardward && OS using runtime detection"}],"type":"strong"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/colorSpaceGetDeviceRGB()":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/colorSpaceGetDeviceRGB()","type":"topic","kind":"symbol","navigatorTitle":[{"text":"colorSpaceGetDeviceRGB","kind":"identifier"}],"title":"colorSpaceGetDeviceRGB()","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/colorspacegetdevicergb()","abstract":[{"type":"text","text":"For coders who use "},{"type":"codeVoice","code":"CGImageCreate"},{"type":"text","text":", use the information below to create an effient CGImage which can be render on GPU without Core Animation’s extra copy ("},{"type":"codeVoice","code":"CA::Render::copy_image"},{"type":"text","text":"), which can be debugged using "},{"type":"codeVoice","code":"Color Copied Image"},{"text":" in Xcode Instruments","type":"text"},{"type":"text","text":" "},{"type":"codeVoice","code":"CGImageCreate"},{"text":"’s ","type":"text"},{"code":"bytesPerRow","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"space"},{"text":", ","type":"text"},{"type":"codeVoice","code":"bitmapInfo"},{"text":" params should use the information below.","type":"text"}],"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"colorSpaceGetDeviceRGB","kind":"identifier"},{"text":"() -> ","kind":"text"},{"text":"CGColorSpace","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGColorSpaceRef"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageCreateDecoded(_:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:)","kind":"symbol","navigatorTitle":[{"text":"CGImageCreateDecoded:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatedecoded(_:)","abstract":[{"text":"Create a decoded CGImage by the provided CGImage. This follows The Create Rule and you are response to call release after usage.","type":"text"},{"type":"text","text":" "},{"text":"It will detect whether image contains alpha channel, then create a new bitmap context with the same size of image, and draw it. This can ensure that the image do not need extra decoding after been set to the imageView.","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgImageCreateDecoded","kind":"identifier"},{"kind":"text","text":"("},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@T@CGImageRef","text":"CGImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"cgImageCreateDecoded(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)":{"role":"symbol","kind":"symbol","title":"scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","navigatorTitle":[{"text":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"scaledSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"CGSize","preciseIdentifier":"c:@S@CGSize"},{"kind":"text","text":", "},{"text":"limitBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"text":"bytesPerPixel","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"frameCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"}],"type":"topic","abstract":[{"type":"text","text":"Calculate the limited image size with the bytes, when using "},{"type":"codeVoice","code":"SDImageCoderDecodeScaleDownLimitBytes"},{"type":"text","text":". This preserve aspect ratio and never scale up"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:limitbytes:bytesperpixel:framecount:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageCreateScaled(_:size:)":{"title":"cgImageCreateScaled(_:size:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatescaled(_:size:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateScaled(_:size:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"cgImageCreateScaled"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef","text":"CGImage"},{"text":", ","kind":"text"},{"text":"size","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":"?"}],"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Create a scaled CGImage by the provided CGImage and size. This follows The Create Rule and you are response to call release after usage."},{"type":"text","text":" "},{"type":"text","text":"It will detect whether the image size matching the scale size, if not, stretch the image to the target size."}],"navigatorTitle":[{"kind":"identifier","text":"CGImageCreateScaled:size:"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/defaultDecodeSolution":{"title":"defaultDecodeSolution","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultDecodeSolution"},{"text":": ","kind":"text"},{"text":"SDImageCoderDecodeSolution","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCoderDecodeSolution"}],"type":"topic","abstract":[{"type":"text","text":"Control the default force decode solution. Available solutions  in "},{"type":"codeVoice","code":"SDImageCoderDecodeSolution"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultDecodeSolution","navigatorTitle":[{"text":"defaultDecodeSolution","kind":"identifier"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/defaultdecodesolution","role":"symbol"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper":{"role":"symbol","abstract":[{"text":"Provide some common helper methods for building the image decoder\/encoder.","type":"text"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCoderHelper","kind":"identifier"}],"title":"SDImageCoderHelper","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCoderHelper"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageIsHDR(_:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHDR(_:)","role":"symbol","navigatorTitle":[{"text":"CGImageIsHDR:","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageishdr(_:)","abstract":[{"type":"text","text":"Check if the CGImage is using HDR color space."}],"title":"cgImageIsHDR(_:)","kind":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cgImageIsHDR","kind":"identifier"},{"text":"(","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":") -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/frames(from:)":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"frames","kind":"identifier"},{"text":"(","kind":"text"},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?) -> ["},{"text":"SDImageFrame","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageFrame"},{"kind":"text","text":"]?"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Return frames array from an animated image."},{"type":"text","text":" "},{"text":"For UIKit, this will unapply the patch for the description above and then create frames array. This will also work for normal animated UIImage.","type":"text"},{"text":" ","type":"text"},{"text":"For AppKit, NSImage does not support animates other than GIF. This will try to decode the GIF imageRep and then create frames array.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/frames(from:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/frames(from:)","title":"frames(from:)","navigatorTitle":[{"kind":"identifier","text":"framesFromAnimatedImage:"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/animatedImage(with:)":{"role":"symbol","abstract":[{"text":"Return an animated image with frames array.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"For UIKit, this will apply the patch and then create animated UIImage. The patch is because that "},{"type":"codeVoice","code":"+[UIImage animatedImageWithImages:duration:]"},{"type":"text","text":" just use the average of duration for each image. So it will not work if different frame has different duration. Therefore we repeat the specify frame for specify times to let it work."},{"type":"text","text":" "},{"type":"text","text":"For AppKit, NSImage does not support animates other than GIF. This will try to encode the frames to GIF format and then create an animated NSImage for rendering. Attention the animated image may loss some detail if the input frames contain full alpha channel because GIF only supports 1 bit alpha channel. (For 1 pixel, either transparent or not)"}],"type":"topic","navigatorTitle":[{"text":"animatedImageWithFrames:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/animatedimage(with:)","kind":"symbol","title":"animatedImage(with:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/animatedImage(with:)","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"animatedImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageFrame","text":"SDImageFrame","kind":"typeIdentifier"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}]},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/exifOrientation(from:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/exifOrientation(from:)","abstract":[{"type":"text","text":"Convert an iOS orientation to an EXIF image orientation."}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/exiforientation(from:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"exifOrientation"},{"kind":"text","text":"("},{"text":"from","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"."},{"preciseIdentifier":"c:@E@UIImageOrientation","text":"Orientation","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:@E@CGImagePropertyOrientation","text":"CGImagePropertyOrientation","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"exifOrientationFromImageOrientation:","kind":"identifier"}],"kind":"symbol","title":"exifOrientation(from:)","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/decodedAndScaledDownImage(with:limitBytes:policy:)":{"type":"topic","abstract":[{"type":"text","text":"Return the decoded and probably scaled down image by the provided image. If the image pixels bytes size large than the limit bytes, will try to scale down. Or just works as "},{"type":"codeVoice","code":"decodedImageWithImage:"},{"type":"text","text":", never scale up."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedAndScaledDownImage(with:limitBytes:policy:)","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedandscaleddownimage(with:limitbytes:policy:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedAndScaledDownImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?, ","kind":"text"},{"text":"limitBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"policy"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageForceDecodePolicy","text":"SDImageForceDecodePolicy"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"decodedAndScaledDownImageWithImage:limitBytes:policy:","kind":"identifier"}],"title":"decodedAndScaledDownImage(with:limitBytes:policy:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageIsLazy(_:)":{"kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageIsLazy"},{"text":"(","kind":"text"},{"text":"CGImage","kind":"typeIdentifier","preciseIdentifier":"c:@T@CGImageRef"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimageislazy(_:)","type":"topic","navigatorTitle":[{"text":"CGImageIsLazy:","kind":"identifier"}],"role":"symbol","title":"cgImageIsLazy(_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsLazy(_:)","abstract":[{"type":"text","text":"Detect whether the CGImage is lazy and not-yet decoded. (lazy means, only when the caller access the underlying bitmap buffer via provider like "},{"type":"codeVoice","code":"CGDataProviderCopyData"},{"type":"text","text":" or "},{"code":"CGDataProviderRetainBytePtr","type":"codeVoice"},{"text":", the decoder will allocate memory, it’s a lazy allocation)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"The implementation use the Core Graphics internal to check whether the CGImage is "},{"type":"codeVoice","code":"CGImageProvider"},{"type":"text","text":" based, or "},{"type":"codeVoice","code":"CGDataProvider"},{"type":"text","text":" based. The "},{"code":"CGDataProvider","type":"codeVoice"},{"text":" based is treated as non-lazy.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/decodedImage(with:)":{"role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"decodedImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"decodedImageWithImage:","kind":"identifier"}],"title":"decodedImage(with:)","kind":"symbol","abstract":[{"type":"text","text":"Return the decoded image by the provided image. This one unlike "},{"code":"CGImageCreateDecoded:","type":"codeVoice"},{"type":"text","text":", will not decode the image which contains alpha channel or animated image. On iOS 15+, this may use "},{"code":"UIImage.preparingForDisplay()","type":"codeVoice"},{"type":"text","text":" to use CMPhoto for better performance than the old solution."}],"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedimage(with:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)":{"abstract":[{"type":"text","text":"Scale the image size based on provided scale size, whether or not to preserve aspect ratio, whether or not to scale up."}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"scaledSize","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"withImageSize"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"scale","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@S@CGSize","text":"CGSize","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"preserveAspectRatio","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"kind":"text","text":", "},{"kind":"externalParam","text":"shouldScaleUp"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"}],"kind":"symbol","title":"scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/scaledsize(withimagesize:scale:preserveaspectratio:shouldscaleup:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)","navigatorTitle":[{"text":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/cgImageCreateDecoded(_:orientation:)":{"url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/cgimagecreatedecoded(_:orientation:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:orientation:)","role":"symbol","kind":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cgImageCreateDecoded"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"kind":"text","text":", "},{"text":"orientation","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CGImagePropertyOrientation","preciseIdentifier":"c:@E@CGImagePropertyOrientation"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"CGImage","preciseIdentifier":"c:@T@CGImageRef"},{"text":"?","kind":"text"}],"navigatorTitle":[{"kind":"identifier","text":"CGImageCreateDecoded:orientation:"}],"title":"cgImageCreateDecoded(_:orientation:)","abstract":[{"text":"Create a decoded CGImage by the provided CGImage and orientation. This follows The Create Rule and you are response to call release after usage.","type":"text"},{"type":"text","text":" "},{"text":"It will detect whether image contains alpha channel, then create a new bitmap context with the same size of image, and draw it. This can ensure that the image do not need extra decoding after been set to the imageView.","type":"text"}]},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/decodedAndScaledDownImage(with:limitBytes:)":{"navigatorTitle":[{"text":"decodedAndScaledDownImageWithImage:limitBytes:","kind":"identifier"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"decodedAndScaledDownImage","kind":"identifier"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"limitBytes","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"kind":"symbol","title":"decodedAndScaledDownImage(with:limitBytes:)","abstract":[{"text":"Return the decoded and probably scaled down image by the provided image. If the image pixels bytes size large than the limit bytes, will try to scale down. Or just works as ","type":"text"},{"code":"decodedImageWithImage:","type":"codeVoice"},{"text":", never scale up.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedAndScaledDownImage(with:limitBytes:)","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedandscaleddownimage(with:limitbytes:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCoderHelper/decodedImage(with:policy:)":{"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:policy:)","navigatorTitle":[{"text":"decodedImageWithImage:policy:","kind":"identifier"}],"type":"topic","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodedImage"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?, ","kind":"text"},{"text":"policy","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDImageForceDecodePolicy","preciseIdentifier":"c:@E@SDImageForceDecodePolicy","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"title":"decodedImage(with:policy:)","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecoderhelper\/decodedimage(with:policy:)","abstract":[{"type":"text","text":"Return the decoded image by the provided image. This one unlike "},{"code":"CGImageCreateDecoded:","type":"codeVoice"},{"type":"text","text":", will not decode the image which contains alpha channel or animated image. On iOS 15+, this may use "},{"code":"UIImage.preparingForDisplay()","type":"codeVoice"},{"type":"text","text":" to use CMPhoto for better performance than the old solution."}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDImageCoderHelper","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCoderHelper"}]},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCoderHelper"}],"op":"replace"},{"path":"\/topicSections","value":[{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultDecodeSolution","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/defaultScaleDownLimitBytes"],"anchor":"Type-Properties","generated":true},{"anchor":"Type-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/animatedImage(with:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageContainsAlpha(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateDecoded(_:orientation:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageCreateScaled(_:size:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHDR(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsHardwareSupported(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/cgImageIsLazy(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/colorSpaceGetDeviceRGB()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedAndScaledDownImage(with:limitBytes:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedAndScaledDownImage(with:limitBytes:policy:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/decodedImage(with:policy:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/exifOrientation(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/frames(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/imageOrientation(from:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/preferredPixelFormat(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCoderHelper\/scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)"],"title":"Type Methods","generated":true}],"op":"replace"},{"path":"\/relationshipsSections","op":"replace","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCoderHelper"},{"kind":"text","text":" : "},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"imageOrientationFromEXIFOrientation:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1imageOrientation(from:)\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1imageOrientation(from:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"imageOrientationFromEXIFOrientation:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1defaultScaleDownLimitBytes\/title","op":"replace","value":"defaultScaleDownLimitBytes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1defaultScaleDownLimitBytes\/fragments","value":[{"kind":"identifier","text":"defaultScaleDownLimitBytes"}]},{"op":"replace","value":"CGImageContainsAlpha:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageContainsAlpha(_:)\/title"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"CGImageContainsAlpha:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageContainsAlpha(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHardwareSupported(_:)\/title","op":"replace","value":"CGImageIsHardwareSupported:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHardwareSupported(_:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"CGImageIsHardwareSupported:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1preferredPixelFormat(_:)\/title","value":"preferredPixelFormat:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"preferredPixelFormat:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1preferredPixelFormat(_:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1colorSpaceGetDeviceRGB()\/title","value":"colorSpaceGetDeviceRGB"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1colorSpaceGetDeviceRGB()\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"colorSpaceGetDeviceRGB","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateDecoded(_:)\/title","op":"replace","value":"CGImageCreateDecoded:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateDecoded(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"CGImageCreateDecoded:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)\/title","op":"replace","value":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:"},{"value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"scaledSizeWithImageSize:limitBytes:bytesPerPixel:frameCount:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:limitBytes:bytesPerPixel:frameCount:)\/fragments"},{"op":"replace","value":"CGImageCreateScaled:size:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateScaled(_:size:)\/title"},{"value":[{"text":"+ ","kind":"text"},{"text":"CGImageCreateScaled:size:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateScaled(_:size:)\/fragments","op":"replace"},{"value":"defaultDecodeSolution","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1defaultDecodeSolution\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1defaultDecodeSolution\/fragments","value":[{"kind":"identifier","text":"defaultDecodeSolution"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/title","op":"replace","value":"SDImageCoderHelper"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/fragments","value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper\/navigatorTitle","value":[{"text":"SDImageCoderHelper","kind":"identifier"}],"op":"replace"},{"value":"CGImageIsHDR:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHDR(_:)\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsHDR(_:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"CGImageIsHDR:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1frames(from:)\/title","value":"framesFromAnimatedImage:"},{"value":[{"text":"+ ","kind":"text"},{"text":"framesFromAnimatedImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1frames(from:)\/fragments","op":"replace"},{"value":"animatedImageWithFrames:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1animatedImage(with:)\/title"},{"op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"animatedImageWithFrames:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1animatedImage(with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1exifOrientation(from:)\/title","value":"exifOrientationFromImageOrientation:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1exifOrientation(from:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"text":"exifOrientationFromImageOrientation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedAndScaledDownImage(with:limitBytes:policy:)\/title","value":"decodedAndScaledDownImageWithImage:limitBytes:policy:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedAndScaledDownImage(with:limitBytes:policy:)\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedAndScaledDownImageWithImage:limitBytes:policy:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsLazy(_:)\/title","value":"CGImageIsLazy:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageIsLazy(_:)\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"CGImageIsLazy:","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedImage(with:)\/title","value":"decodedImageWithImage:"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"decodedImageWithImage:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedImage(with:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)\/title","value":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1scaledSize(withImageSize:scale:preserveAspectRatio:shouldScaleUp:)\/fragments","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"scaledSizeWithImageSize:scaleSize:preserveAspectRatio:shouldScaleUp:"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateDecoded(_:orientation:)\/title","value":"CGImageCreateDecoded:orientation:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1cgImageCreateDecoded(_:orientation:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"CGImageCreateDecoded:orientation:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedAndScaledDownImage(with:limitBytes:)\/title","value":"decodedAndScaledDownImageWithImage:limitBytes:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedAndScaledDownImage(with:limitBytes:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decodedAndScaledDownImageWithImage:limitBytes:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedImage(with:policy:)\/title","op":"replace","value":"decodedImageWithImage:policy:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCoderHelper~1decodedImage(with:policy:)\/fragments","op":"replace","value":[{"text":"+ ","kind":"text"},{"kind":"identifier","text":"decodedImageWithImage:policy:"}]}]}]}