{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCache"},{"kind":"text","text":"<"},{"kind":"genericParameter","text":"KeyType"},{"kind":"text","text":", "},{"kind":"genericParameter","text":"ObjectType"},{"kind":"text","text":"> "},{"kind":"keyword","text":"where"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"KeyType"},{"kind":"text","text":" : AnyObject, "},{"kind":"typeIdentifier","text":"ObjectType"},{"kind":"text","text":" : AnyObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdmemorycache-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdmemorycache-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSCache"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A memory cache which auto purge the cache on memory warning and support weak cache."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCache"}],"title":"SDMemoryCache","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDMemoryCache","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDMemoryCache"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class\/config"]}],"references":{"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol":{"role":"symbol","title":"SDMemoryCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCacheProtocol"}],"abstract":[{"type":"text","text":"A protocol to allow custom memory cache used in SDImageCache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDMemoryCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCache-swift.class":{"role":"symbol","title":"SDMemoryCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCache"}],"abstract":[{"type":"text","text":"A memory cache which auto purge the cache on memory warning and support weak cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDMemoryCache"}],"url":"\/documentation\/sdwebimage\/sdmemorycache-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCache-swift.class/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class\/config","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"config"}],"url":"\/documentation\/sdwebimage\/sdmemorycache-swift.class\/config"},"doc://com.dailymotion.SDWebImage/objc(cs)NSCache":{"type":"unresolvable","title":"NSCache","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSCache"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDMemoryCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDMemoryCache"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDMemoryCache"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCache-swift.class\/config"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSCache"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCache"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSCache","preciseIdentifier":"c:objc(cs)NSCache"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/title","value":"SDMemoryCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDMemoryCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class\/title","value":"SDMemoryCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class\/fragments","value":[{"kind":"identifier","text":"SDMemoryCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class~1config\/title","value":"config"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCache-swift.class~1config\/fragments","value":[{"kind":"identifier","text":"config"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}