{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDScaledImageForScaleFactor(_:_:)"},"kind":"symbol","abstract":[{"text":"Scale the image with the scale factor. If no need to scale, return the original image.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"This works for "},{"type":"codeVoice","code":"UIImage"},{"text":"(UIKit) or ","type":"text"},{"code":"NSImage","type":"codeVoice"},{"text":"(AppKit). And this function also preserve the associated value in ","type":"text"},{"code":"UIImage+Metadata.h","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdscaledimageforscalefactor(_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdscaledimageforscalefactor(_:_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"externalID":"c:@F@SDScaledImageForScaleFactor","symbolKind":"func","role":"symbol","roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDScaledImageForScaleFactor"},{"text":"(","kind":"text"},{"preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat","kind":"typeIdentifier"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"SDScaledImageForScaleFactor"}],"title":"SDScaledImageForScaleFactor(_:_:)","modules":[{"name":"SDWebImage"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDScaledImageForScaleFactor"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"scale"},{"text":": ","kind":"text"},{"text":"CGFloat","kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"image"},{"text":": ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"name":"scale","content":[{"type":"paragraph","inlineContent":[{"text":"The image scale factor","type":"text"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"The image"}],"type":"paragraph"}],"name":"image"}]},{"kind":"content","content":[{"type":"heading","level":2,"anchor":"return-value","text":"Return Value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The scaled image"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDScaledImageForScaleFactor(_:_:)":{"abstract":[{"text":"Scale the image with the scale factor. If no need to scale, return the original image.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This works for "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":"(UIKit) or "},{"code":"NSImage","type":"codeVoice"},{"type":"text","text":"(AppKit). And this function also preserve the associated value in "},{"type":"codeVoice","code":"UIImage+Metadata.h"},{"text":".","type":"text"}],"title":"SDScaledImageForScaleFactor(_:_:)","url":"\/documentation\/sdwebimage\/sdscaledimageforscalefactor(_:_:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDScaledImageForScaleFactor","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"s:14CoreFoundation7CGFloatV","text":"CGFloat"},{"text":", ","kind":"text"},{"text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDScaledImageForScaleFactor(_:_:)","kind":"symbol","navigatorTitle":[{"text":"SDScaledImageForScaleFactor","kind":"identifier"}],"type":"topic","role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Function","path":"\/metadata\/roleHeading","op":"replace"},{"path":"\/metadata\/title","op":"replace","value":"SDScaledImageForScaleFactor"},{"path":"\/metadata\/symbolKind","value":"func","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDScaledImageForScaleFactor"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"kind":"text","text":" * "},{"text":"SDScaledImageForScaleFactor","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@CGFloat","kind":"typeIdentifier","text":"CGFloat"},{"kind":"text","text":" "},{"text":"scale","kind":"internalParam"},{"kind":"text","text":", "},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" * ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"scale","content":[{"inlineContent":[{"text":"The image scale factor","type":"text"}],"type":"paragraph"}]},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The image"}],"type":"paragraph"}]}]}},{"value":{"content":[{"type":"heading","text":"Return Value","level":2,"anchor":"return-value"},{"type":"paragraph","inlineContent":[{"text":"The scaled image","type":"text"}]}],"kind":"content"},"op":"replace","path":"\/primaryContentSections\/2"},{"op":"replace","value":"SDScaledImageForScaleFactor","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDScaledImageForScaleFactor(_:_:)\/title"},{"value":[{"text":"SDScaledImageForScaleFactor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDScaledImageForScaleFactor(_:_:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}