{"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdscaledimageforkey(_:_:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdscaledimageforkey(_:_:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDScaledImageForKey(_:_:)"},"sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"modules":[{"name":"SDWebImage"}],"title":"SDScaledImageForKey(_:_:)","externalID":"c:@F@SDScaledImageForKey","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDScaledImageForKey","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"symbolKind":"func","role":"symbol","roleHeading":"Function","navigatorTitle":[{"text":"SDScaledImageForKey","kind":"identifier"}]},"abstract":[{"type":"text","text":"Scale the image with the scale factor for the specify key. If no need to scale, return the original image."},{"text":" ","type":"text"},{"text":"This works for ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":"(UIKit) or ","type":"text"},{"code":"NSImage","type":"codeVoice"},{"text":"(AppKit). And this function also preserve the associated value in ","type":"text"},{"type":"codeVoice","code":"UIImage+Metadata.h"},{"type":"text","text":"."}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDScaledImageForKey"},{"text":"(","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"image","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The image cache key"}],"type":"paragraph"}],"name":"key"},{"name":"image","content":[{"inlineContent":[{"type":"text","text":"The image"}],"type":"paragraph"}]}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"The scaled image","type":"text"}]}]},{"content":[{"level":2,"type":"heading","text":"Discussion","anchor":"discussion"},{"type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"This is actually a convenience function, which firstly call ","type":"text"},{"code":"SDImageScaleFactorForKey","type":"codeVoice"},{"type":"text","text":" and then call "},{"type":"codeVoice","code":"SDScaledImageForScaleFactor"},{"type":"text","text":", kept for backward compatibility."}]}],"style":"note","name":"Note"}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDScaledImageForKey(_:_:)":{"abstract":[{"type":"text","text":"Scale the image with the scale factor for the specify key. If no need to scale, return the original image."},{"text":" ","type":"text"},{"type":"text","text":"This works for "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":"(UIKit) or "},{"code":"NSImage","type":"codeVoice"},{"text":"(AppKit). And this function also preserve the associated value in ","type":"text"},{"type":"codeVoice","code":"UIImage+Metadata.h"},{"type":"text","text":"."}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDScaledImageForKey","kind":"identifier"},{"text":"(","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":"?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage","text":"UIImage"},{"text":"?","kind":"text"}],"kind":"symbol","title":"SDScaledImageForKey(_:_:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdscaledimageforkey(_:_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDScaledImageForKey(_:_:)","navigatorTitle":[{"text":"SDScaledImageForKey","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Function"},{"op":"replace","value":"SDScaledImageForKey","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"func"},{"path":"\/metadata\/fragments","value":[{"text":"SDScaledImageForKey","kind":"identifier"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" * ","kind":"text"},{"text":"SDScaledImageForKey","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":", ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIImage","kind":"typeIdentifier","text":"UIImage"},{"text":" * ","kind":"text"},{"kind":"internalParam","text":"image"},{"kind":"text","text":");"}],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The image cache key"}],"type":"paragraph"}],"name":"key"},{"name":"image","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image"}]}]}]}},{"value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"type":"text","text":"The scaled image"}],"type":"paragraph"}],"kind":"content"},"path":"\/primaryContentSections\/2","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDScaledImageForKey(_:_:)\/title","value":"SDScaledImageForKey","op":"replace"},{"value":[{"kind":"identifier","text":"SDScaledImageForKey"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDScaledImageForKey(_:_:)\/fragments","op":"replace"}]}]}