{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDThumbnailedKeyForKey","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"text":"thumbnailPixelSize","kind":"internalParam"},{"kind":"text","text":": "},{"text":"CGSize","preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"preserveAspectRatio"},{"text":": ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"},{"text":") -> ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"key","content":[{"inlineContent":[{"text":"The original cache key","type":"text"}],"type":"paragraph"}]},{"name":"thumbnailPixelSize","content":[{"inlineContent":[{"type":"text","text":"The thumbnail pixel size"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The preserve aspect ratio option","type":"text"}],"type":"paragraph"}],"name":"preserveAspectRatio"}]},{"kind":"content","content":[{"level":2,"type":"heading","text":"Return Value","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The thumbnailed cache key"}]}]},{"content":[{"text":"Discussion","type":"heading","anchor":"discussion","level":2},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"If you have both transformer and thumbnail applied for image, call "},{"type":"codeVoice","code":"SDThumbnailedKeyForKey"},{"type":"text","text":" firstly and then with "},{"type":"codeVoice","code":"SDTransformedKeyForKey"},{"type":"text","text":".`"}]}],"type":"aside","name":"Note","style":"note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdthumbnailedkeyforkey(_:_:_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdthumbnailedkeyforkey(_:_:_:)"]}],"abstract":[{"type":"text","text":"Return the thumbnailed cache key which applied with specify thumbnailSize and preserveAspectRatio control."}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDThumbnailedKeyForKey(_:_:_:)","interfaceLanguage":"swift"},"kind":"symbol","sections":[],"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"metadata":{"modules":[{"name":"SDWebImage"}],"title":"SDThumbnailedKeyForKey(_:_:_:)","navigatorTitle":[{"kind":"identifier","text":"SDThumbnailedKeyForKey"}],"roleHeading":"Function","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDThumbnailedKeyForKey","kind":"identifier"},{"kind":"text","text":"("},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":", "},{"preciseIdentifier":"s:Sb","kind":"typeIdentifier","text":"Bool"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"text":"?","kind":"text"}],"externalID":"c:@F@SDThumbnailedKeyForKey","symbolKind":"func","role":"symbol"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDThumbnailedKeyForKey(_:_:_:)":{"type":"topic","abstract":[{"text":"Return the thumbnailed cache key which applied with specify thumbnailSize and preserveAspectRatio control.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdthumbnailedkeyforkey(_:_:_:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDThumbnailedKeyForKey(_:_:_:)","kind":"symbol","title":"SDThumbnailedKeyForKey(_:_:_:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDThumbnailedKeyForKey"},{"kind":"text","text":"("},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"text":", ","kind":"text"},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"kind":"text","text":"?"}],"navigatorTitle":[{"kind":"identifier","text":"SDThumbnailedKeyForKey"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","value":"Function","path":"\/metadata\/roleHeading"},{"value":"SDThumbnailedKeyForKey","op":"replace","path":"\/metadata\/title"},{"op":"replace","value":"func","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDThumbnailedKeyForKey"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"SDThumbnailedKeyForKey"},{"text":"(","kind":"text"},{"text":"NSString","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"key","kind":"internalParam"},{"kind":"text","text":", "},{"preciseIdentifier":"c:@S@CGSize","kind":"typeIdentifier","text":"CGSize"},{"text":" ","kind":"text"},{"text":"thumbnailPixelSize","kind":"internalParam"},{"kind":"text","text":", "},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":" ","kind":"text"},{"text":"preserveAspectRatio","kind":"internalParam"},{"text":");","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The original cache key"}]}]},{"name":"thumbnailPixelSize","content":[{"type":"paragraph","inlineContent":[{"text":"The thumbnail pixel size","type":"text"}]}]},{"name":"preserveAspectRatio","content":[{"inlineContent":[{"type":"text","text":"The preserve aspect ratio option"}],"type":"paragraph"}]}]}},{"path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"inlineContent":[{"text":"The thumbnailed cache key","type":"text"}],"type":"paragraph"}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDThumbnailedKeyForKey(_:_:_:)\/title","value":"SDThumbnailedKeyForKey"},{"op":"replace","value":[{"text":"SDThumbnailedKeyForKey","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDThumbnailedKeyForKey(_:_:_:)\/fragments"}]}]}