{"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderRequestModifierProtocol","kind":"identifier"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"This is the protocol for downloader request modifier."},{"type":"text","text":" "},{"text":"We can use a block to specify the downloader request modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"topicSections":[{"title":"Instance Methods","anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol\/modifiedRequest(with:)"],"generated":true}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","interfaceLanguage":"swift"},"sections":[],"metadata":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"title":"SDWebImageDownloaderRequestModifierProtocol","externalID":"c:objc(pl)SDWebImageDownloaderRequestModifier","roleHeading":"Protocol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"symbolKind":"protocol","modules":[{"name":"SDWebImage"}],"role":"symbol"},"schemaVersion":{"minor":3,"patch":0,"major":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships"},{"type":"conformingTypes","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class"],"kind":"relationships","title":"Conforming Types"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierProtocol":{"type":"topic","abstract":[{"type":"text","text":"This is the protocol for downloader request modifier."},{"type":"text","text":" "},{"text":"We can use a block to specify the downloader request modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","kind":"symbol","title":"SDWebImageDownloaderRequestModifierProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifierProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class","role":"symbol","abstract":[{"text":"A downloader request modifier class with block.","type":"text"}],"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"type":"topic","title":"SDWebImageDownloaderRequestModifier","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierProtocol/modifiedRequest(with:)":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"modifiedRequest","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"text":"?","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol\/modifiedrequest(with:)","abstract":[{"text":"Modify the original URL request and return a new one instead. You can modify the HTTP header, cachePolicy, etc for this URL.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"modifiedRequestWithRequest:","kind":"identifier"}],"required":true,"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol\/modifiedRequest(with:)","role":"symbol","title":"modifiedRequest(with:)"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Protocol","path":"\/metadata\/roleHeading"},{"value":"SDWebImageDownloaderRequestModifier","op":"replace","path":"\/metadata\/title"},{"value":"protocol","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol\/modifiedRequest(with:)"],"anchor":"Instance-Methods"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"},{"title":"Conforming Types","type":"conformingTypes","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class"]}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"},{"text":" <","kind":"text"},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject"},{"text":">","kind":"text"}]}],"kind":"declarations"}},{"value":"SDWebImageDownloaderRequestModifier","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/title","op":"replace"},{"value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/title","op":"replace","value":"SDWebImageDownloaderRequestModifier"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol~1modifiedRequest(with:)\/title","op":"replace","value":"modifiedRequestWithRequest:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol~1modifiedRequest(with:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"modifiedRequestWithRequest:","kind":"identifier"}],"op":"replace"}]}]}