{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"SDWebImageErrorDownloadStatusCodeKey","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageerrordownloadstatuscodekey"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageerrordownloadstatuscodekey"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageErrorDownloadStatusCodeKey"},"abstract":[{"type":"text","text":"The HTTP status code for invalid download response (NSNumber *)"}],"metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Global Variable","navigatorTitle":[{"text":"SDWebImageErrorDownloadStatusCodeKey","kind":"identifier"}],"title":"SDWebImageErrorDownloadStatusCodeKey","symbolKind":"var","externalID":"c:@SDWebImageErrorDownloadStatusCodeKey","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageErrorDownloadStatusCodeKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}]},"schemaVersion":{"minor":3,"patch":0,"major":0},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageErrorDownloadStatusCodeKey":{"abstract":[{"type":"text","text":"The HTTP status code for invalid download response (NSNumber *)"}],"title":"SDWebImageErrorDownloadStatusCodeKey","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerrordownloadstatuscodekey","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageErrorDownloadStatusCodeKey"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageErrorDownloadStatusCodeKey","fragments":[{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"SDWebImageErrorDownloadStatusCodeKey","kind":"identifier"},{"text":": ","kind":"text"},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageErrorDownloadStatusCodeKey"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDWebImageErrorDownloadStatusCodeKey","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSString","preciseIdentifier":"c:objc(cs)NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"SDWebImageErrorDownloadStatusCodeKey","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageErrorDownloadStatusCodeKey\/title","value":"SDWebImageErrorDownloadStatusCodeKey","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageErrorDownloadStatusCodeKey"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageErrorDownloadStatusCodeKey\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}