{"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterBlock"},"metadata":{"title":"SDWebImageCacheKeyFilterBlock","symbolKind":"typealias","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"}],"externalID":"c:SDWebImageCacheKeyFilter.h@T@SDWebImageCacheKeyFilterBlock","modules":[{"name":"SDWebImage"}],"fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"}],"role":"symbol","roleHeading":"Type Alias"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"},{"text":" = (","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilterblock"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilterblock"]}],"kind":"symbol","sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilterBlock":{"title":"SDWebImageCacheKeyFilterBlock","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterBlock","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilterblock","role":"symbol","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"}],"kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageCacheKeyFilterBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"}]},{"path":"\/metadata\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageCacheKeyFilterBlock","kind":"identifier"}]},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString *(^)(NSURL *)","preciseIdentifier":"c:BF*$objc(cs)NSString(#*$objc(cs)NSURL)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"SDWebImageCacheKeyFilterBlock","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterBlock\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterBlock\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterBlock\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageCacheKeyFilterBlock","kind":"identifier"}]}]}]}