{"schemaVersion":{"patch":0,"major":0,"minor":3},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","kind":"relationships"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprogressindicator"]},{"paths":["\/documentation\/sdwebimage\/sdwebimageprogressindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator"},"metadata":{"modules":[{"name":"SDWebImage"}],"title":"SDWebImageProgressIndicator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageProgressIndicator","kind":"identifier"}],"externalID":"c:objc(cs)SDWebImageProgressIndicator","roleHeading":"Class","navigatorTitle":[{"text":"SDWebImageProgressIndicator","kind":"identifier"}],"symbolKind":"class"},"abstract":[{"type":"text","text":"Progress indicator class."},{"type":"text","text":" "},{"text":"for UIKit(macOS), it use a ","type":"text"},{"code":"UIProgressView","type":"codeVoice"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"code":"NSProgressIndicator","type":"codeVoice"},{"text":" with the bar style.","type":"text"}],"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/indicatorView"],"generated":true,"anchor":"Instance-Properties"},{"generated":true,"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/bar","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/default"],"anchor":"Type-Properties"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageProgressIndicator","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}]}],"kind":"symbol","sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator/default":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"`default`","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageProgressIndicator","text":"SDWebImageProgressIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/default","abstract":[{"type":"text","text":"default-style progress indicator"}],"role":"symbol","navigatorTitle":[{"text":"defaultIndicator","kind":"identifier"}],"kind":"symbol","type":"topic","title":"default","url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator\/default"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator","abstract":[{"type":"text","text":"Progress indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIProgressView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"type":"codeVoice","code":"NSProgressIndicator"},{"text":" with the bar style.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"kind":"symbol","type":"topic","title":"SDWebImageProgressIndicator","url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator/indicatorView":{"role":"symbol","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"indicatorView","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIProgressView","text":"UIProgressView","kind":"typeIdentifier"}],"navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator\/indicatorview","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/indicatorView","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","abstract":[{"text":"A protocol to custom the indicator during the image loading.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageIndicator","kind":"identifier"}],"kind":"symbol","title":"SDWebImageIndicator","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator/bar":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"bar","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageProgressIndicator","text":"SDWebImageProgressIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/bar","abstract":[{"text":"bar-style progress indicator","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"barIndicator","kind":"identifier"}],"kind":"symbol","type":"topic","title":"bar","url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator\/bar"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","value":"Class","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDWebImageProgressIndicator","op":"replace"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"text":"SDWebImageProgressIndicator","kind":"identifier"}]},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Properties","title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/indicatorView"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/bar","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator\/default"],"generated":true,"anchor":"Type-Properties"}]},{"op":"replace","path":"\/relationshipsSections","value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageProgressIndicator","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1default\/title","value":"defaultIndicator","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1default\/fragments","value":[{"text":"defaultIndicator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/title","value":"SDWebImageProgressIndicator","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/fragments","value":[{"text":"SDWebImageProgressIndicator","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"text":"SDWebImageProgressIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1indicatorView\/title","value":"indicatorView"},{"value":[{"kind":"identifier","text":"indicatorView"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1indicatorView\/fragments","op":"replace"},{"value":"SDWebImageIndicator","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments","value":[{"text":"SDWebImageIndicator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1bar\/title","value":"barIndicator","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator~1bar\/fragments","op":"replace","value":[{"text":"barIndicator","kind":"identifier"}]}]}]}