{"topicSections":[{"generated":true,"anchor":"Initializers","title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/init(block:)"]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]}],"kind":"declarations"}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"kind":"symbol","abstract":[{"text":"A cache key filter class with block.","type":"text"}],"metadata":{"externalID":"c:objc(cs)SDWebImageCacheKeyFilter","title":"SDWebImageCacheKeyFilter","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}],"symbolKind":"class","modules":[{"name":"SDWebImage"}],"roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}],"role":"symbol"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilter-swift.class/init(block:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class\/init(block:)","title":"init(block:)","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/init(block:)","kind":"symbol","type":"topic","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"block","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageCacheKeyFilterBlock","preciseIdentifier":"c:SDWebImageCacheKeyFilter.h@T@SDWebImageCacheKeyFilterBlock"},{"kind":"text","text":")"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilter-swift.class/cacheKeyFilterWithBlock:":{"abstract":[],"title":"cacheKeyFilterWithBlock:","navigatorTitle":[{"kind":"identifier","text":"cacheKeyFilterWithBlock:"}],"fragments":[{"kind":"text","text":"+ "},{"text":"cacheKeyFilterWithBlock:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/cacheKeyFilterWithBlock:","url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class\/cachekeyfilterwithblock:","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilter-swift.class":{"role":"symbol","kind":"symbol","title":"SDWebImageCacheKeyFilter","url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class","navigatorTitle":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}],"type":"topic","abstract":[{"type":"text","text":"A cache key filter class with block."}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilterProtocol":{"type":"topic","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageCacheKeyFilterProtocol","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol","url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilterprotocol","abstract":[{"text":"This is the protocol for cache key filter.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We can use a block to specify the cache key filter. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"code":"@convention(block)","type":"codeVoice"},{"type":"text","text":" to store a block into context options."}],"kind":"symbol","title":"SDWebImageCacheKeyFilterProtocol","navigatorTitle":[{"text":"SDWebImageCacheKeyFilterProtocol","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"value":"SDWebImageCacheKeyFilter","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"value":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/init(block:)"]},{"anchor":"Type-Methods","generated":true,"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class\/cacheKeyFilterWithBlock:"]}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol"],"title":"Conforms To","type":"conformsTo"}]},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilter"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","text":"NSObject","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class~1init(block:)\/title","value":"initWithBlock:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithBlock:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class~1init(block:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/title","value":"SDWebImageCacheKeyFilter","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/fragments","value":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}]},{"value":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/title","op":"replace","value":"SDWebImageCacheKeyFilter"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/navigatorTitle","value":[{"text":"SDWebImageCacheKeyFilter","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}