{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageIndicator"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageindicator"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol to custom the indicator during the image loading."},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageIndicator"}],"title":"SDWebImageIndicator","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDWebImageIndicator","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageIndicator"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/indicatorView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/startAnimatingIndicator()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/stopAnimatingIndicator()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/updateProgress(_:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"role":"symbol","title":"SDWebImageActivityIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"type":"codeVoice","code":"NSProgressIndicator"},{"type":"text","text":" with the spinning style."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/indicatorView":{"navigatorTitle":[{"kind":"identifier","text":"indicatorView"}],"role":"symbol","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"}],"abstract":[{"type":"text","text":"The view associate to the indicator."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/indicatorView","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator\/indicatorview"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/updateProgress(_:)":{"navigatorTitle":[{"kind":"identifier","text":"updateIndicatorProgress:"}],"role":"symbol","title":"updateProgress(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"updateProgress"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Update the loading progress (0-1.0) for indicator. Optional"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/updateProgress(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator\/updateprogress(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressIndicator":{"role":"symbol","title":"SDWebImageProgressIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"abstract":[{"type":"text","text":"Progress indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"type":"codeVoice","code":"UIProgressView"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"type":"codeVoice","code":"NSProgressIndicator"},{"type":"text","text":" with the bar style."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageprogressindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"role":"symbol","title":"SDWebImageIndicator","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageIndicator"}],"abstract":[{"type":"text","text":"A protocol to custom the indicator during the image loading."},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/startAnimatingIndicator()":{"navigatorTitle":[{"kind":"identifier","text":"startAnimatingIndicator"}],"role":"symbol","title":"startAnimatingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"startAnimatingIndicator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Start the animating for indicator."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/startAnimatingIndicator()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator\/startanimatingindicator()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator/stopAnimatingIndicator()":{"navigatorTitle":[{"kind":"identifier","text":"stopAnimatingIndicator"}],"role":"symbol","title":"stopAnimatingIndicator()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"stopAnimatingIndicator"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Stop the animating for indicator."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/stopAnimatingIndicator()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator\/stopanimatingindicator()"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/indicatorView"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/startAnimatingIndicator()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/stopAnimatingIndicator()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator\/updateProgress(_:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressIndicator"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageIndicator"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","value":"SDWebImageActivityIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1indicatorView\/title","value":"indicatorView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1indicatorView\/fragments","value":[{"kind":"identifier","text":"indicatorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1updateProgress(_:)\/title","value":"updateIndicatorProgress:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1updateProgress(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"updateIndicatorProgress:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/title","value":"SDWebImageProgressIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageProgressIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title","value":"SDWebImageIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1startAnimatingIndicator()\/title","value":"startAnimatingIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1startAnimatingIndicator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"startAnimatingIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1stopAnimatingIndicator()\/title","value":"stopAnimatingIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator~1stopAnimatingIndicator()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"stopAnimatingIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}