{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV","text":"URLRequest"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:10Foundation10URLRequestV","kind":"typeIdentifier","text":"URLRequest"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Alias","navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"}],"externalID":"c:SDWebImageDownloaderRequestModifier.h@T@SDWebImageDownloaderRequestModifierBlock","symbolKind":"typealias","title":"SDWebImageDownloaderRequestModifierBlock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierblock"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierBlock"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierBlock":{"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"}],"abstract":[],"role":"symbol","title":"SDWebImageDownloaderRequestModifierBlock","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierBlock","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"path":"\/metadata\/title","value":"SDWebImageDownloaderRequestModifierBlock","op":"replace"},{"op":"replace","value":"typealias","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierBlock"}]},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"text":"NSURLRequest *(^)(NSURLRequest *)","preciseIdentifier":"c:BF*$objc(cs)NSURLRequest(#S2_)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierBlock\/title","value":"SDWebImageDownloaderRequestModifierBlock","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierBlock\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierBlock\/navigatorTitle","value":[{"text":"SDWebImageDownloaderRequestModifierBlock","kind":"identifier"}]}]}]}