{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOperation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoperation"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoperation"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOperation"}],"title":"SDWebImageOperation","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDWebImageOperation","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageOperation"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation\/isCancelled"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation\/cancel()"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"role":"symbol","title":"SDWebImageDownloaderOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"abstract":[{"type":"text","text":"The download operation class for SDWebImageDownloader."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheToken":{"role":"symbol","title":"SDImageCacheToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheToken"}],"abstract":[{"type":"text","text":"A token associated with each cache query. Can be used to cancel a cache query"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheToken"}],"url":"\/documentation\/sdwebimage\/sdimagecachetoken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation/cancel()":{"navigatorTitle":[{"kind":"identifier","text":"cancel"}],"role":"symbol","title":"cancel()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Cancel the operation"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation\/cancel()","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageoperation\/cancel()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetchToken":{"role":"symbol","title":"SDWebImagePrefetchToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetchToken"}],"abstract":[{"type":"text","text":"A token represents a list of URLs, can be used to cancel the download."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePrefetchToken"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetchtoken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"role":"symbol","title":"SDWebImageOperation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOperation"}],"abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimageoperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation/isCancelled":{"role":"symbol","title":"isCancelled","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isCancelled"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether the operation has been cancelled."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation\/isCancelled","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelled"}],"url":"\/documentation\/sdwebimage\/sdwebimageoperation\/iscancelled"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken":{"role":"symbol","title":"SDWebImageDownloadToken","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloadToken"}],"abstract":[{"type":"text","text":"A token associated with each download. Can be used to cancel a download"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloadToken"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation":{"role":"symbol","title":"SDWebImageCombinedOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"abstract":[{"type":"text","text":"A combined operation representing the cache and loader operation. You can use it to cancel the load process."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageOperation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageOperation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageOperation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation\/isCancelled"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation\/cancel()"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheToken","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetchToken"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOperation"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/title","value":"SDImageCacheToken"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheToken\/fragments","value":[{"kind":"identifier","text":"SDImageCacheToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation~1cancel()\/title","value":"cancel"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation~1cancel()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/title","value":"SDWebImagePrefetchToken"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetchToken\/fragments","value":[{"kind":"identifier","text":"SDWebImagePrefetchToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title","value":"SDWebImageOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments","value":[{"kind":"identifier","text":"SDWebImageOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation~1isCancelled\/title","value":"cancelled"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation~1isCancelled\/fragments","value":[{"kind":"identifier","text":"cancelled"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken\/title","value":"SDWebImageDownloadToken"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloadToken"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/title","value":"SDWebImageCombinedOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/fragments","value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}