{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The prefetcher delegate protocol"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}],"title":"SDWebImagePrefetcherDelegate","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDWebImagePrefetcherDelegate","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)"]}],"references":{"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)":{"navigatorTitle":[{"kind":"identifier","text":"imagePrefetcher:didFinishWithTotalCount:skippedCount:"}],"role":"symbol","title":"imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDWebImagePrefetcher","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didFinishWithTotalCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"skippedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when all images are prefetched. Which means it’s called when all URLs from all of prefetching finished."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didfinishwithtotalcount:skippedcount:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)":{"navigatorTitle":[{"kind":"identifier","text":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:"}],"role":"symbol","title":"imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePrefetcher"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDWebImagePrefetcher","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher"},{"kind":"text","text":", "},{"kind":"externalParam","text":"didPrefetchURL"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"finishedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"kind":"externalParam","text":"totalCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Called when an image was prefetched. Which means it’s called when one URL from any of prefetching finished."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didprefetchurl:finishedcount:totalcount:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate":{"role":"symbol","title":"SDWebImagePrefetcherDelegate","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}],"abstract":[{"type":"text","text":"The prefetcher delegate protocol"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImagePrefetcherDelegate"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)\/title","value":"imagePrefetcher:didFinishWithTotalCount:skippedCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePrefetcher:didFinishWithTotalCount:skippedCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)\/title","value":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/title","value":"SDWebImagePrefetcherDelegate"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/fragments","value":[{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}