{"metadata":{"roleHeading":"Global Variable","title":"SDWebImageErrorDomain","navigatorTitle":[{"text":"SDWebImageErrorDomain","kind":"identifier"}],"externalID":"c:@SDWebImageErrorDomain","fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"role":"symbol","modules":[{"name":"SDWebImage"}],"symbolKind":"var"},"schemaVersion":{"major":0,"minor":3,"patch":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageErrorDomain","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageerrordomain"]},{"paths":["\/documentation\/sdwebimage\/sdwebimageerrordomain"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"abstract":[{"type":"text","text":"An error domain represent SDWebImage loading system with custom codes"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageErrorDomain"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"}],"languages":["swift"],"platforms":["iOS"]}]}],"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageErrorDomain":{"type":"topic","abstract":[{"type":"text","text":"An error domain represent SDWebImage loading system with custom codes"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageErrorDomain","url":"\/documentation\/sdwebimage\/sdwebimageerrordomain","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageErrorDomain","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"navigatorTitle":[{"text":"SDWebImageErrorDomain","kind":"identifier"}],"title":"SDWebImageErrorDomain"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageErrorDomain"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageErrorDomain","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageErrorDomain","kind":"identifier"},{"text":";","kind":"text"}]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageErrorDomain\/title","op":"replace","value":"SDWebImageErrorDomain"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageErrorDomain\/fragments","value":[{"text":"SDWebImageErrorDomain","kind":"identifier"}]}]}]}