{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherCompletionBlock"},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetchercompletionblock"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetchercompletionblock"]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"roleHeading":"Type Alias","modules":[{"name":"SDWebImage"}],"externalID":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherCompletionBlock","role":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"}],"symbolKind":"typealias","title":"SDWebImagePrefetcherCompletionBlock"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"},{"text":" = (","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"s:s4Voida","kind":"typeIdentifier","text":"Void"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherCompletionBlock":{"title":"SDWebImagePrefetcherCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherCompletionBlock","navigatorTitle":[{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"}],"fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetchercompletionblock","type":"topic","kind":"symbol","role":"symbol","abstract":[]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDWebImagePrefetcherCompletionBlock","op":"replace","path":"\/metadata\/title"},{"value":"typealias","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BFv(#l#l)","kind":"typeIdentifier","text":"void (^)(unsigned long, unsigned long)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherCompletionBlock\/title","value":"SDWebImagePrefetcherCompletionBlock"},{"value":[{"text":"SDWebImagePrefetcherCompletionBlock","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherCompletionBlock\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImagePrefetcherCompletionBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherCompletionBlock\/navigatorTitle"}]}]}