{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSOperation"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDataDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The download operation class for SDWebImageDownloader."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"title":"SDWebImageDownloaderOperation","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDWebImageDownloaderOperation","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/init(request:inSession:options:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/init(request:inSession:options:context:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableContentTypes-7m1yq","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes-8qb9b","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/context","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/credential-2a76w","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/dataTask-74nib","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/metrics-3t9yf","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/minimumProgressInterval-24x9p","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/options","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/request-8hnoo","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/response-4nwkj"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/cancel(_:)"]}],"references":{"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/minimumProgressInterval-24x9p":{"role":"symbol","title":"minimumProgressInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumProgressInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The minimum interval about progress percent during network downloading. Which means the next progress callback and current progress callback’s progress percent difference should be larger or equal to this value. However, the final finish download progress callback does not get effected."},{"type":"text","text":" "},{"type":"text","text":"The value should be 0.0-1.0."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/minimumProgressInterval-24x9p","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minimumProgressInterval"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/minimumprogressinterval-24x9p"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol":{"role":"symbol","title":"SDWebImageDownloaderOperationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"abstract":[{"type":"text","text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from "},{"type":"codeVoice","code":"NSOperation"},{"type":"text","text":" and conform to this protocol"},{"type":"text","text":" "},{"type":"text","text":"For the description about these methods, see "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/cancel(_:)":{"role":"symbol","title":"cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Cancels a set of callbacks. Once all callbacks are canceled, the operation is cancelled."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/cancel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancel:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/cancel(_:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/objc(cs)NSOperation":{"type":"unresolvable","title":"NSOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSOperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/request-8hnoo":{"role":"symbol","title":"request","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The request used by the operation’s task."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/request-8hnoo","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"request"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/request-8hnoo"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/init(request:inSession:options:context:)":{"role":"symbol","title":"init(request:inSession:options:context:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/init(request:inSession:options:context:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRequest:inSession:options:context:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/init(request:insession:options:context:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"role":"symbol","title":"SDWebImageOperation","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOperation"}],"abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimageoperation"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/objc(pl)NSURLSessionDataDelegate":{"type":"unresolvable","title":"Foundation.URLSessionDataDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDataDelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/acceptableStatusCodes-8qb9b":{"role":"symbol","title":"acceptableStatusCodes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableStatusCodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response status code. The status code which beyond the range will mark the download operation failed."},{"type":"text","text":" "},{"type":"text","text":"For example, if we config [200, 400) but server response is 503, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadStatusCode"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to [200,400). Nil means no validation at all."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes-8qb9b","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptableStatusCodes"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablestatuscodes-8qb9b"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"role":"symbol","title":"SDWebImageDownloaderOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"abstract":[{"type":"text","text":"The download operation class for SDWebImageDownloader."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/response-4nwkj":{"role":"symbol","title":"response","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The response returned by the operation’s task."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/response-4nwkj","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"response"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/response-4nwkj"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/metrics-3t9yf":{"role":"symbol","title":"metrics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The collected metrics from "},{"type":"codeVoice","code":"-URLSession:task:didFinishCollectingMetrics:"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This can be used to collect the network metrics like download duration, DNS lookup duration, SSL handshake duration, etc. See Apple’s documentation: https:\/\/developer.apple.com\/documentation\/foundation\/urlsessiontaskmetrics"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/metrics-3t9yf","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metrics"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/metrics-3t9yf"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/options":{"role":"symbol","title":"options","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"abstract":[{"type":"text","text":"The options for the receiver."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/options","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"options"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/options"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/init(request:inSession:options:)":{"role":"symbol","title":"init(request:inSession:options:)","fragments":[{"kind":"keyword","text":"convenience"},{"kind":"text","text":" "},{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Initializes a "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"},{"type":"text","text":" object"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/init(request:inSession:options:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithRequest:inSession:options:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/init(request:insession:options:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/addHandlers(forProgress:completed:)":{"role":"symbol","title":"addHandlers(forProgress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Adds handlers for progress and completion. Returns a token that can be passed to -cancel: to cancel this set of"},{"type":"text","text":" "},{"type":"text","text":"callbacks."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addHandlersForProgress:completed:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/addhandlers(forprogress:completed:)"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/objc(pl)NSURLSessionTaskDelegate":{"type":"unresolvable","title":"Foundation.URLSessionTaskDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionTaskDelegate"},"doc://com.dailymotion.SDWebImage/objc(pl)NSURLSessionDelegate":{"type":"unresolvable","title":"Foundation.URLSessionDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/dataTask-74nib":{"role":"symbol","title":"dataTask","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataTask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The operation’s task"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/dataTask-74nib","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"dataTask"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/datatask-74nib"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/acceptableContentTypes-7m1yq":{"role":"symbol","title":"acceptableContentTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableContentTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response content type. The content type beyond the set will mark the download operation failed."},{"type":"text","text":" "},{"type":"text","text":"For example, if we config [“image\/png”] but server response is “application\/json”, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadContentType"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Normally you don’t need this for image format detection because we use image’s data file signature magic bytes: https:\/\/en.wikipedia.org\/wiki\/List_of_file_signatures"},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil. Nil means no validation at all."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableContentTypes-7m1yq","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptableContentTypes"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/acceptablecontenttypes-7m1yq"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/context":{"role":"symbol","title":"context","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"abstract":[{"type":"text","text":"The context for the receiver."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/context","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"context"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/context"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class/credential-2a76w":{"role":"symbol","title":"credential","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"credential"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The credential used for authentication challenges in "},{"type":"codeVoice","code":"-URLSession:task:didReceiveChallenge:completionHandler:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/credential-2a76w","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"credential"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class\/credential-2a76w"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableContentTypes-7m1yq","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/acceptableStatusCodes-8qb9b","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/context","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/credential-2a76w","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/dataTask-74nib","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/metrics-3t9yf","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/minimumProgressInterval-24x9p","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/options","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/request-8hnoo","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/response-4nwkj"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/addHandlers(forProgress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/cancel(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/init(request:inSession:options:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class\/init(request:inSession:options:context:)"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSOperation","preciseIdentifier":"c:objc(cs)NSOperation"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1minimumProgressInterval-24x9p\/title","value":"minimumProgressInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1minimumProgressInterval-24x9p\/fragments","value":[{"kind":"identifier","text":"minimumProgressInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1cancel(_:)\/title","value":"cancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1request-8hnoo\/title","value":"request"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1request-8hnoo\/fragments","value":[{"kind":"identifier","text":"request"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1init(request:inSession:options:context:)\/title","value":"initWithRequest:inSession:options:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1init(request:inSession:options:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequest:inSession:options:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title","value":"SDWebImageOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments","value":[{"kind":"identifier","text":"SDWebImageOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableStatusCodes-8qb9b\/title","value":"acceptableStatusCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableStatusCodes-8qb9b\/fragments","value":[{"kind":"identifier","text":"acceptableStatusCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1response-4nwkj\/title","value":"response"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1response-4nwkj\/fragments","value":[{"kind":"identifier","text":"response"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1metrics-3t9yf\/title","value":"metrics"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1metrics-3t9yf\/fragments","value":[{"kind":"identifier","text":"metrics"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1options\/title","value":"options"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1options\/fragments","value":[{"kind":"identifier","text":"options"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1init(request:inSession:options:)\/title","value":"initWithRequest:inSession:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1init(request:inSession:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequest:inSession:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1addHandlers(forProgress:completed:)\/title","value":"addHandlersForProgress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1addHandlers(forProgress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addHandlersForProgress:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1dataTask-74nib\/title","value":"dataTask"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1dataTask-74nib\/fragments","value":[{"kind":"identifier","text":"dataTask"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableContentTypes-7m1yq\/title","value":"acceptableContentTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1acceptableContentTypes-7m1yq\/fragments","value":[{"kind":"identifier","text":"acceptableContentTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1context\/title","value":"context"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1context\/fragments","value":[{"kind":"identifier","text":"context"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1credential-2a76w\/title","value":"credential"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class~1credential-2a76w\/fragments","value":[{"kind":"identifier","text":"credential"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}