{"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"SDWebImageAnimationOptions","symbolKind":"typealias","navigatorTitle":[{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"role":"symbol","roleHeading":"Type Alias","externalID":"c:SDWebImageTransition.h@T@SDWebImageAnimationOptions"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageAnimationOptions","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageanimationoptions"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageanimationoptions"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDWebImageAnimationOptions","kind":"identifier"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","text":"UIView","preciseIdentifier":"c:objc(cs)UIView"},{"kind":"text","text":"."},{"kind":"typeIdentifier","text":"AnimationOptions","preciseIdentifier":"c:@E@UIViewAnimationOptions"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageAnimationOptions":{"abstract":[],"url":"\/documentation\/sdwebimage\/sdwebimageanimationoptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageAnimationOptions","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"navigatorTitle":[{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"title":"SDWebImageAnimationOptions","kind":"symbol","type":"topic","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Alias","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageAnimationOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"value":[{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImageAnimationOptions"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:@E@UIViewAnimationOptions","text":"UIViewAnimationOptions","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SDWebImageAnimationOptions","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageAnimationOptions\/title","op":"replace","value":"SDWebImageAnimationOptions"},{"op":"replace","value":[{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageAnimationOptions\/fragments"},{"value":[{"text":"SDWebImageAnimationOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageAnimationOptions\/navigatorTitle"}]}]}