{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":" = "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderCompletedBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderCompletedBlock","text":"SDImageLoaderCompletedBlock"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloadercompletedblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloadercompletedblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"title":"SDWebImageDownloaderCompletedBlock","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderCompletedBlock":{"role":"symbol","title":"SDWebImageDownloaderCompletedBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderCompletedBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloadercompletedblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderCompletedBlock":{"role":"symbol","title":"SDImageLoaderCompletedBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoaderCompletedBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderCompletedBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageLoaderCompletedBlock"}],"url":"\/documentation\/sdwebimage\/sdimageloadercompletedblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderCompletedBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderCompletedBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderCompletedBlock","text":"SDImageLoaderCompletedBlock"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/title","value":"SDWebImageDownloaderCompletedBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderCompletedBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderCompletedBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderCompletedBlock\/title","value":"SDImageLoaderCompletedBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderCompletedBlock\/fragments","value":[{"kind":"identifier","text":"SDImageLoaderCompletedBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}