{"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/init(cache:loader:)"],"generated":true,"title":"Initializers","anchor":"Initializers"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKeyFilter","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheSerializer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/delegate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/imageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/imageLoader","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/isRunning","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/optionsProcessor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/transformer"],"title":"Instance Properties","generated":true,"anchor":"Instance-Properties"},{"title":"Instance Methods","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKey(for:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKey(for:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cancelAll()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/removeAllFailedURLs()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/removeFailedURL(_:)"],"anchor":"Instance-Methods"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageLoader","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/shared"],"title":"Type Properties","generated":true,"anchor":"Type-Properties"}],"abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"type":"text","text":" "},{"type":"text","text":"You can use this class directly to benefit from web image downloading with caching in another context than"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManager"}],"platforms":["iOS"]}],"kind":"declarations"},{"kind":"content","content":[{"type":"heading","level":2,"text":"Overview","anchor":"overview"},{"inlineContent":[{"text":"Here is a simple example of how to use SDWebImageManager:","type":"text"}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"SDWebImageManager *manager = [SDWebImageManager sharedManager];"},{"text":" ","type":"text"},{"text":"[manager loadImageWithURL:imageURL","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"options:0"},{"type":"text","text":" "},{"type":"text","text":"progress:nil"},{"type":"text","text":" "},{"type":"text","text":"completed:^(UIImage *image, NSData *data, NSError *error, SDImageCacheType cacheType, BOOL finished, NSURL *imageURL) {"},{"text":" ","type":"text"},{"text":"if (image) {","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"\/\/ do something with image"},{"text":" ","type":"text"},{"text":"}","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"}];"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagemanager"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To"}],"kind":"symbol","sections":[],"metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageManager"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageManager"}],"role":"symbol","title":"SDWebImageManager","symbolKind":"class","roleHeading":"Class","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDWebImageManager"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/imageLoader":{"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"imageLoader","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/imageloader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/imageLoader","abstract":[{"type":"text","text":"The image loader used by manager to load image."}],"title":"imageLoader","type":"topic","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageLoader"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader","text":"SDImageLoader"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/loadImage(with:options:progress:completed:)":{"type":"topic","title":"loadImage(with:options:progress:completed:)","navigatorTitle":[{"kind":"identifier","text":"loadImageWithURL:options:progress:completed:"}],"abstract":[{"type":"text","text":"Downloads the image at the given URL if not present in cache or return the cached version otherwise."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock","text":"SDInternalCompletionBlock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","kind":"typeIdentifier","text":"SDWebImageCombinedOperation"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:progress:completed:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:progress:completed:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/delegate":{"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/delegate","type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/delegate","role":"symbol","abstract":[{"type":"text","text":"The delegate for manager. Defaults to nil."}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"delegate"},{"text":": (any ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageManagerDelegate","preciseIdentifier":"c:objc(pl)SDWebImageManagerDelegate"},{"kind":"text","text":")?"}],"navigatorTitle":[{"text":"delegate","kind":"identifier"}],"title":"delegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/removeFailedURL(_:)":{"title":"removeFailedURL(_:)","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/removefailedurl(_:)","abstract":[{"text":"Remove the specify URL from failed black list.","type":"text"}],"type":"topic","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeFailedURL"},{"text":"(","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"removeFailedURL:","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/removeFailedURL(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/cancelAll()":{"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/cancelall()","title":"cancelAll()","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancelAll","kind":"identifier"},{"text":"()","kind":"text"}],"type":"topic","kind":"symbol","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"cancelAll"}],"abstract":[{"type":"text","text":"Cancel all current operations"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cancelAll()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/optionsProcessor":{"navigatorTitle":[{"text":"optionsProcessor","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/optionsprocessor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"optionsProcessor","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"SDWebImageOptionsProcessorProtocol","preciseIdentifier":"c:objc(pl)SDWebImageOptionsProcessor","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","title":"optionsProcessor","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/optionsProcessor","abstract":[{"text":"The options processor is used, to have a global control for all the image request options and context option for current manager.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/loadImage(with:options:context:progress:completed:)":{"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:context:progress:completed:)","navigatorTitle":[{"kind":"identifier","text":"loadImageWithURL:options:context:progress:completed:"}],"kind":"symbol","role":"symbol","type":"topic","abstract":[{"type":"text","text":"Downloads the image at the given URL if not present in cache or return the cached version otherwise."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:context:progress:completed:)","title":"loadImage(with:options:context:progress:completed:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"text":"progress","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDImageLoaderProgressBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock"},{"kind":"text","text":"?, "},{"text":"completed","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock","kind":"typeIdentifier","text":"SDInternalCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","text":"SDWebImageCombinedOperation"},{"text":"?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/isRunning":{"type":"topic","abstract":[{"text":"Check one or more operations running","type":"text"}],"navigatorTitle":[{"kind":"identifier","text":"running"}],"title":"isRunning","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/isRunning","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/isrunning","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"isRunning","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}]},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/defaultImageLoader":{"abstract":[{"text":"The default image loader for manager which is created with no arguments. Such as shared manager or init.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil. Means using "},{"type":"codeVoice","code":"SDWebImageDownloader.sharedDownloader"}],"title":"defaultImageLoader","navigatorTitle":[{"kind":"identifier","text":"defaultImageLoader"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"defaultImageLoader"},{"text":": (any ","kind":"text"},{"text":"SDImageLoader","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader"},{"text":")?","kind":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageLoader","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/defaultimageloader","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/cacheSerializer":{"navigatorTitle":[{"kind":"identifier","text":"cacheSerializer"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/cacheserializer","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cacheSerializer","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"SDWebImageCacheSerializerProtocol","preciseIdentifier":"c:objc(pl)SDWebImageCacheSerializer","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"title":"cacheSerializer","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheSerializer","type":"topic","abstract":[{"type":"text","text":"The cache serializer is used to convert the decoded image, the source downloaded data, to the actual data used for storing to the disk cache. If you return nil, means to generate the data from the image instance, see "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":"."},{"text":" ","type":"text"},{"text":"For example, if you are using WebP images and facing the slow decoding time issue when later retrieving from disk cache again. You can try to encode the decoded image to JPEG\/PNG format to disk cache instead of source downloaded data.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/shared":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/shared","kind":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageManager","text":"SDWebImageManager"}],"type":"topic","role":"symbol","navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"abstract":[{"type":"text","text":"Returns global shared manager instance."}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/shared"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/cacheKey(for:)":{"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/cachekey(for:)","navigatorTitle":[{"kind":"identifier","text":"cacheKeyForURL:"}],"kind":"symbol","role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"cacheKey","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"cacheKey(for:)","abstract":[{"text":"Return the cache key for a given URL, does not considerate transformer or thumbnail.","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKey(for:)","type":"topic"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/init(cache:loader:)":{"abstract":[{"text":"Allows to specify instance of cache and image loader used with image manager.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"cache","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCache","text":"SDImageCacheProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loader"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageLoader","text":"SDImageLoader","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(cache:loader:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/init(cache:loader:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/init(cache:loader:)","navigatorTitle":[{"text":"initWithCache:loader:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/cacheKeyFilter":{"abstract":[{"text":"The cache filter is used to convert an URL into a cache key each time SDWebImageManager need cache key to use image cache.","type":"text"}],"title":"cacheKeyFilter","navigatorTitle":[{"kind":"identifier","text":"cacheKeyFilter"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"cacheKeyFilter","kind":"identifier"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDWebImageCacheKeyFilter","text":"SDWebImageCacheKeyFilterProtocol","kind":"typeIdentifier"},{"kind":"text","text":")?"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKeyFilter","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/cachekeyfilter","kind":"symbol","role":"symbol","type":"topic"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/cacheKey(for:context:)":{"kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"cacheKeyForURL:context:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKey(for:context:)","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/cachekey(for:context:)","role":"symbol","abstract":[{"type":"text","text":"Return the cache key for a given URL and context option."}],"title":"cacheKey(for:context:)","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cacheKey","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/defaultImageCache":{"role":"symbol","abstract":[{"text":"The default image cache when the manager which is created with no arguments. Such as shared manager or init.","type":"text"},{"text":" ","type":"text"},{"text":"Defaults to nil. Means using ","type":"text"},{"code":"SDImageCache.sharedImageCache","type":"codeVoice"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultImageCache"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/defaultimagecache","kind":"symbol","title":"defaultImageCache","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageCache","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"defaultImageCache","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"SDImageCacheProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCache"},{"text":")?","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/transformer":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/transformer","type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/transformer","title":"transformer","navigatorTitle":[{"kind":"identifier","text":"transformer"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"transformer","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"SDImageTransformer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageTransformer"},{"text":")?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The image transformer for manager. It’s used for image transform after the image load finished and store the transformed image to cache, see "},{"type":"codeVoice","code":"SDImageTransformer"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil, which means no transform is applied."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","url":"\/documentation\/sdwebimage\/sdwebimagemanager","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","navigatorTitle":[{"text":"SDWebImageManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"text":" ","type":"text"},{"text":"You can use this class directly to benefit from web image downloading with caching in another context than","type":"text"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageManager","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/imageCache":{"abstract":[{"type":"text","text":"The image cache used by manager to query image cache."}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageCache"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SDImageCache","kind":"typeIdentifier","text":"SDImageCacheProtocol"}],"kind":"symbol","title":"imageCache","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/imagecache","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/imageCache","navigatorTitle":[{"text":"imageCache","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/removeAllFailedURLs()":{"title":"removeAllFailedURLs()","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeAllFailedURLs"},{"text":"()","kind":"text"}],"type":"topic","abstract":[{"type":"text","text":"Remove all the URL from failed black list."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/removeAllFailedURLs()","navigatorTitle":[{"kind":"identifier","text":"removeAllFailedURLs"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/removeallfailedurls()","role":"symbol"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","title":"Swift.CVarArg"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageManager"},{"path":"\/metadata\/symbolKind","value":"class","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDWebImageManager","kind":"identifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageManager"}]},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKeyFilter","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheSerializer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/delegate","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/imageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/imageLoader","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/isRunning","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/optionsProcessor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/transformer"],"title":"Instance Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKey(for:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKey(for:context:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cancelAll()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/init(cache:loader:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/removeAllFailedURLs()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/removeFailedURL(_:)"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"},{"title":"Type Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageLoader","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/shared"],"anchor":"Type-Properties"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"text":"SDWebImageManager","kind":"identifier"},{"text":" : ","kind":"text"},{"text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1imageLoader\/title","value":"imageLoader","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1imageLoader\/fragments","value":[{"text":"imageLoader","kind":"identifier"}]},{"value":"loadImageWithURL:options:progress:completed:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:progress:completed:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"loadImageWithURL:options:progress:completed:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:progress:completed:)\/fragments"},{"value":"delegate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1delegate\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1delegate\/fragments","value":[{"text":"delegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1removeFailedURL(_:)\/title","value":"removeFailedURL:"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeFailedURL:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1removeFailedURL(_:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cancelAll()\/title","value":"cancelAll","op":"replace"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"cancelAll","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cancelAll()\/fragments"},{"value":"optionsProcessor","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1optionsProcessor\/title","op":"replace"},{"value":[{"text":"optionsProcessor","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1optionsProcessor\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:context:progress:completed:)\/title","value":"loadImageWithURL:options:context:progress:completed:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:context:progress:completed:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadImageWithURL:options:context:progress:completed:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"running","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1isRunning\/title"},{"op":"replace","value":[{"text":"running","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1isRunning\/fragments"},{"value":"defaultImageLoader","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1defaultImageLoader\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1defaultImageLoader\/fragments","value":[{"kind":"identifier","text":"defaultImageLoader"}]},{"value":"cacheSerializer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheSerializer\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheSerializer\/fragments","value":[{"text":"cacheSerializer","kind":"identifier"}]},{"value":"sharedManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1shared\/title","op":"replace"},{"value":[{"text":"sharedManager","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1shared\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKey(for:)\/title","value":"cacheKeyForURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKey(for:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"cacheKeyForURL:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1init(cache:loader:)\/title","value":"initWithCache:loader:"},{"op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCache:loader:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1init(cache:loader:)\/fragments"},{"value":"cacheKeyFilter","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKeyFilter\/title","op":"replace"},{"value":[{"text":"cacheKeyFilter","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKeyFilter\/fragments","op":"replace"},{"value":"cacheKeyForURL:context:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKey(for:context:)\/title","op":"replace"},{"value":[{"kind":"text","text":"- "},{"text":"cacheKeyForURL:context:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKey(for:context:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1defaultImageCache\/title","value":"defaultImageCache","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1defaultImageCache\/fragments","value":[{"text":"defaultImageCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1transformer\/title","value":"transformer","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1transformer\/fragments","value":[{"text":"transformer","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageManager"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1imageCache\/title","value":"imageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1imageCache\/fragments","value":[{"kind":"identifier","text":"imageCache"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1removeAllFailedURLs()\/title","value":"removeAllFailedURLs","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1removeAllFailedURLs()\/fragments","value":[{"text":"- ","kind":"text"},{"text":"removeAllFailedURLs","kind":"identifier"}]}]}]}