{"metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"modules":[{"name":"SDWebImage"}],"roleHeading":"Protocol","symbolKind":"protocol","title":"SDWebImageManagerDelegate","externalID":"c:objc(pl)SDWebImageManagerDelegate","navigatorTitle":[{"text":"SDWebImageManagerDelegate","kind":"identifier"}],"role":"symbol"},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SDWebImageManagerDelegate","kind":"identifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol","kind":"typeIdentifier"}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanagerdelegate"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanagerdelegate"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate","interfaceLanguage":"swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"topicSections":[{"anchor":"Instance-Methods","generated":true,"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldBlockFailedURL:withError:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldDownloadImageFor:)"]}],"abstract":[{"text":"The manager delegate protocol.","type":"text"}],"kind":"symbol","sections":[],"references":{"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate/imageManager(_:shouldDownloadImageFor:)":{"title":"imageManager(_:shouldDownloadImageFor:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldDownloadImageFor:)","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shoulddownloadimagefor:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageManager","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImageManager","preciseIdentifier":"c:objc(cs)SDWebImageManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldDownloadImageFor","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Sb","text":"Bool"}],"navigatorTitle":[{"kind":"identifier","text":"imageManager:shouldDownloadImageForURL:"}],"abstract":[{"text":"Controls which image should be downloaded when the image is not found in the cache.","type":"text"}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate/imageManager(_:shouldBlockFailedURL:withError:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldBlockFailedURL:withError:)","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate\/imagemanager(_:shouldblockfailedurl:witherror:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageManager"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SDWebImageManager","text":"SDWebImageManager","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"withError"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"type":"topic","abstract":[{"text":"Controls the complicated logic to mark as failed URLs when download error occur.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If the delegate implement this method, we will not use the built-in way to mark URL as failed based on error code;"}],"kind":"symbol","title":"imageManager(_:shouldBlockFailedURL:withError:)","navigatorTitle":[{"kind":"identifier","text":"imageManager:shouldBlockFailedURL:withError:"}],"required":true},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManagerDelegate":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate","navigatorTitle":[{"text":"SDWebImageManagerDelegate","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanagerdelegate","abstract":[{"type":"text","text":"The manager delegate protocol."}],"kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"role":"symbol","title":"SDWebImageManagerDelegate"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","value":"Protocol","op":"replace"},{"value":"SDWebImageManagerDelegate","path":"\/metadata\/title","op":"replace"},{"path":"\/metadata\/symbolKind","value":"protocol","op":"replace"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"op":"replace"},{"path":"\/topicSections","value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldBlockFailedURL:withError:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManagerDelegate\/imageManager(_:shouldDownloadImageFor:)"],"generated":true,"title":"Instance Methods"}],"op":"replace"},{"op":"replace","path":"\/relationshipsSections","value":[{"kind":"relationships","title":"Inherits From","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"]}]},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"text":"SDWebImageManagerDelegate","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"imageManager:shouldDownloadImageForURL:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldDownloadImageFor:)\/title"},{"value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"imageManager:shouldDownloadImageForURL:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldDownloadImageFor:)\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldBlockFailedURL:withError:)\/title","value":"imageManager:shouldBlockFailedURL:withError:","op":"replace"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imageManager:shouldBlockFailedURL:withError:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate~1imageManager(_:shouldBlockFailedURL:withError:)\/fragments"},{"value":"SDWebImageManagerDelegate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageManagerDelegate"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManagerDelegate\/navigatorTitle","value":[{"text":"SDWebImageManagerDelegate","kind":"identifier"}]}]}]}