{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"},{"kind":"text","text":" = ("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Void","preciseIdentifier":"s:s4Voida"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransitioncompletionblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransitioncompletionblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionCompletionBlock","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}],"title":"SDWebImageTransitionCompletionBlock","roleHeading":"Type Alias","role":"symbol","symbolKind":"typealias","externalID":"c:SDWebImageTransition.h@T@SDWebImageTransitionCompletionBlock","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransitionCompletionBlock":{"role":"symbol","title":"SDWebImageTransitionCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionCompletionBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransitioncompletionblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageTransitionCompletionBlock"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"void (^)(_Bool)","preciseIdentifier":"c:BFv(#b)"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionCompletionBlock\/title","value":"SDWebImageTransitionCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionCompletionBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}