{"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"relationshipsSections":[{"title":"Conforms To","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/s25ExpressibleByArrayLiteralP","doc:\/\/com.dailymotion.SDWebImage\/s9OptionSetP","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","doc:\/\/com.dailymotion.SDWebImage\/s10SetAlgebraP"],"type":"conformsTo","kind":"relationships"}],"metadata":{"role":"symbol","title":"SDWebImageDownloaderOptions","navigatorTitle":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"externalID":"c:@E@SDWebImageDownloaderOptions","roleHeading":"Structure","fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"symbolKind":"struct","modules":[{"name":"SDWebImage"}]},"topicSections":[{"generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/init(rawValue:)"],"anchor":"Initializers","title":"Initializers"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/allowInvalidSSLCertificates","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/avoidDecodeImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/continueInBackground","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/handleCookies","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/highPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/ignoreCachedResponse","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/lowPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/matchAnimatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/preloadAllFrames","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/progressiveLoad","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/scaleDownLargeImages","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/useNSURLCache"],"title":"Type Properties","anchor":"Type-Properties","generated":true},{"generated":true,"title":"Default Implementations","anchor":"Default-Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/OptionSet-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/SetAlgebra-Implementations"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/matchAnimatedImageClass":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/matchAnimatedImageClass","type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/matchanimatedimageclass","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderMatchAnimatedImageClass"}],"abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"text":" context option (like using ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":"), we may still use ","type":"text"},{"type":"codeVoice","code":"UIImage"},{"text":" when the memory cache hit, or image decoder is not available, to behave as a fallback solution.","type":"text"},{"type":"text","text":" "},{"text":"Using this option, can ensure we always produce image with your provided class. If failed, a error with code ","type":"text"},{"type":"codeVoice","code":"SDWebImageErrorBadImageData"},{"text":" will been used.","type":"text"},{"text":" ","type":"text"},{"text":"Note this options is not compatible with ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderDecodeFirstFrameOnly"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"title":"matchAnimatedImageClass","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchAnimatedImageClass","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/SY":{"title":"Swift.RawRepresentable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/decodeFirstFrameOnly":{"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"decodeFirstFrameOnly"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions"}],"abstract":[{"text":"By default, we decode the animated image. This flag can force decode the first frame only and produce the static image.","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderDecodeFirstFrameOnly","kind":"identifier"}],"title":"decodeFirstFrameOnly","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/decodeFirstFrameOnly","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/decodefirstframeonly"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/preloadAllFrames":{"role":"symbol","title":"preloadAllFrames","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"preloadAllFrames","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/preloadAllFrames","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/preloadallframes","navigatorTitle":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}],"abstract":[{"text":"By default, for ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":", we decode the animated image frame during rendering to reduce memory usage. This flag actually trigger "},{"type":"codeVoice","code":"preloadAllAnimatedImageFrames = YES"},{"type":"text","text":" after image load from network"}]},"doc://com.dailymotion.SDWebImage/s8SendableP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","title":"Swift.Sendable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/s25ExpressibleByArrayLiteralP":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/s25ExpressibleByArrayLiteralP","title":"Swift.ExpressibleByArrayLiteral","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/SetAlgebra-Implementations":{"abstract":[],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/setalgebra-implementations","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/SetAlgebra-Implementations","kind":"article","role":"collectionGroup","title":"SetAlgebra Implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/init(rawValue:)":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/init(rawValue:)","title":"init(rawValue:)","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/init(rawvalue:)","abstract":[],"fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"rawValue"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions","role":"symbol","title":"SDWebImageDownloaderOptions","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"kind":"symbol","abstract":[{"type":"text","text":"Downloader options"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/ignoreCachedResponse":{"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"ignoreCachedResponse"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"abstract":[{"type":"text","text":"Call completion block with nil image\/imageData if the image was read from NSURLCache"},{"type":"text","text":" "},{"text":"And the error code is ","type":"text"},{"code":"SDWebImageErrorCacheNotModified","type":"codeVoice"},{"text":" ","type":"text"},{"text":"This flag should be combined with ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderUseNSURLCache"},{"type":"text","text":"."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderIgnoreCachedResponse","kind":"identifier"}],"title":"ignoreCachedResponse","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/ignoreCachedResponse","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/ignorecachedresponse"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/avoidDecodeImage":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/avoidDecodeImage","navigatorTitle":[{"text":"SDWebImageDownloaderAvoidDecodeImage","kind":"identifier"}],"title":"avoidDecodeImage","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/avoiddecodeimage","deprecated":true,"abstract":[{"type":"text","text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation."},{"type":"text","text":" "},{"type":"text","text":"However, this process may increase the memory usage as well. If you are experiencing a issue due to excessive memory consumption, This flag can prevent decode the image."}],"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avoidDecodeImage"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/continueInBackground":{"kind":"symbol","type":"topic","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"continueInBackground","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageDownloaderOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}],"abstract":[{"text":"In iOS 4+, continue the download of the image if the app goes to background. This is achieved by asking the system for","type":"text"},{"type":"text","text":" "},{"type":"text","text":"extra time in background to let the request finish. If the background task expires the operation will be cancelled."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderContinueInBackground","kind":"identifier"}],"title":"continueInBackground","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/continueInBackground","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/continueinbackground"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/highPriority":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/highPriority","navigatorTitle":[{"text":"SDWebImageDownloaderHighPriority","kind":"identifier"}],"title":"highPriority","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/highpriority","abstract":[{"type":"text","text":"Put the download in the high queue priority and task priority."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"highPriority"},{"text":": ","kind":"text"},{"text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/handleCookies":{"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/handlecookies","kind":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"handleCookies","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions"}],"abstract":[{"text":"Handles cookies stored in NSHTTPCookieStore by setting","type":"text"},{"type":"text","text":" "},{"type":"text","text":"NSMutableURLRequest.HTTPShouldHandleCookies = YES;"}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageDownloaderHandleCookies","kind":"identifier"}],"title":"handleCookies","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/handleCookies","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/progressiveLoad":{"abstract":[{"text":"This flag enables progressive download, the image is displayed progressively during download as a browser would do.","type":"text"}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/progressiveLoad","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloaderProgressiveLoad","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/progressiveload","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"progressiveLoad","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","kind":"typeIdentifier","text":"SDWebImageDownloaderOptions"}],"title":"progressiveLoad"},"doc://com.dailymotion.SDWebImage/s15BitwiseCopyableP":{"title":"Swift.BitwiseCopyable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s15BitwiseCopyableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/Equatable-Implementations":{"abstract":[],"role":"collectionGroup","kind":"article","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/Equatable-Implementations","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/equatable-implementations","title":"Equatable Implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/allowInvalidSSLCertificates":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/allowInvalidSSLCertificates","navigatorTitle":[{"text":"SDWebImageDownloaderAllowInvalidSSLCertificates","kind":"identifier"}],"title":"allowInvalidSSLCertificates","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/allowinvalidsslcertificates","abstract":[{"type":"text","text":"Enable to allow untrusted SSL certificates."},{"type":"text","text":" "},{"text":"Useful for testing purposes. Use with caution in production.","type":"text"}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"allowInvalidSSLCertificates","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/s9OptionSetP":{"title":"Swift.OptionSet","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s9OptionSetP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/OptionSet-Implementations":{"type":"topic","abstract":[],"kind":"article","role":"collectionGroup","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/OptionSet-Implementations","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/optionset-implementations","title":"OptionSet Implementations"},"doc://com.dailymotion.SDWebImage/s10SetAlgebraP":{"title":"Swift.SetAlgebra","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s10SetAlgebraP","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/useNSURLCache":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/useNSURLCache","navigatorTitle":[{"text":"SDWebImageDownloaderUseNSURLCache","kind":"identifier"}],"title":"useNSURLCache","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/usensurlcache","abstract":[{"text":"By default, request prevent the use of NSURLCache. With this flag, NSURLCache","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"is used with default policies."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"useNSURLCache","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","kind":"typeIdentifier","text":"SDWebImageDownloaderOptions"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/lowPriority":{"abstract":[{"type":"text","text":"Put the download in the low queue priority and task priority."}],"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/lowPriority","type":"topic","navigatorTitle":[{"text":"SDWebImageDownloaderLowPriority","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/lowpriority","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"lowPriority","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}],"title":"lowPriority"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOptions/scaleDownLargeImages":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/scaleDownLargeImages","navigatorTitle":[{"text":"SDWebImageDownloaderScaleDownLargeImages","kind":"identifier"}],"title":"scaleDownLargeImages","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoptions\/scaledownlargeimages","abstract":[{"type":"text","text":"By default, images are decoded respecting their original size. On iOS, this flag will scale down the"},{"type":"text","text":" "},{"type":"text","text":"images to a size compatible with the constrained memory of devices."},{"text":" ","type":"text"},{"text":"This flag take no effect if ","type":"text"},{"type":"codeVoice","code":"SDWebImageDownloaderAvoidDecodeImage"},{"type":"text","text":" is set. And it will be ignored if "},{"code":"SDWebImageDownloaderProgressiveLoad","type":"codeVoice"},{"type":"text","text":" is set."}],"fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"scaleDownLargeImages"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageDownloaderOptions","text":"SDWebImageDownloaderOptions","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Enumeration","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"SDWebImageDownloaderOptions","op":"replace"},{"value":"enum","path":"\/metadata\/symbolKind","op":"replace"},{"value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/allowInvalidSSLCertificates","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/avoidDecodeImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/continueInBackground","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/handleCookies","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/highPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/ignoreCachedResponse","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/lowPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/matchAnimatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/preloadAllFrames","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/progressiveLoad","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/scaleDownLargeImages","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOptions\/useNSURLCache"],"anchor":"Enumeration-Cases","generated":true}]},{"path":"\/relationshipsSections","value":null,"op":"replace"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"enum","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderOptions"},{"text":": ","kind":"text"},{"text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":";"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"value":"SDWebImageDownloaderMatchAnimatedImageClass","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1matchAnimatedImageClass\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderMatchAnimatedImageClass"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1matchAnimatedImageClass\/fragments"},{"value":"SDWebImageDownloaderDecodeFirstFrameOnly","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1decodeFirstFrameOnly\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1decodeFirstFrameOnly\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecodeFirstFrameOnly"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1preloadAllFrames\/title","value":"SDWebImageDownloaderPreloadAllFrames","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1preloadAllFrames\/fragments","value":[{"text":"SDWebImageDownloaderPreloadAllFrames","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/title","op":"replace","value":"SDWebImageDownloaderOptions"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/fragments"},{"value":[{"text":"SDWebImageDownloaderOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1ignoreCachedResponse\/title","value":"SDWebImageDownloaderIgnoreCachedResponse"},{"value":[{"text":"SDWebImageDownloaderIgnoreCachedResponse","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1ignoreCachedResponse\/fragments"},{"op":"replace","value":"SDWebImageDownloaderAvoidDecodeImage","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1avoidDecodeImage\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1avoidDecodeImage\/fragments","value":[{"text":"SDWebImageDownloaderAvoidDecodeImage","kind":"identifier"}]},{"op":"replace","value":"SDWebImageDownloaderContinueInBackground","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1continueInBackground\/title"},{"value":[{"text":"SDWebImageDownloaderContinueInBackground","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1continueInBackground\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1highPriority\/title","value":"SDWebImageDownloaderHighPriority"},{"value":[{"text":"SDWebImageDownloaderHighPriority","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1highPriority\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1handleCookies\/title","value":"SDWebImageDownloaderHandleCookies"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1handleCookies\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderHandleCookies","kind":"identifier"}]},{"value":"SDWebImageDownloaderProgressiveLoad","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1progressiveLoad\/title"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderProgressiveLoad"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1progressiveLoad\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1allowInvalidSSLCertificates\/title","op":"replace","value":"SDWebImageDownloaderAllowInvalidSSLCertificates"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1allowInvalidSSLCertificates\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderAllowInvalidSSLCertificates"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1useNSURLCache\/title","value":"SDWebImageDownloaderUseNSURLCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1useNSURLCache\/fragments","value":[{"text":"SDWebImageDownloaderUseNSURLCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1lowPriority\/title","value":"SDWebImageDownloaderLowPriority","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageDownloaderLowPriority","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1lowPriority\/fragments"},{"value":"SDWebImageDownloaderScaleDownLargeImages","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1scaleDownLargeImages\/title","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageDownloaderScaleDownLargeImages"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOptions~1scaleDownLargeImages\/fragments","op":"replace"}]}]}