{"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageDownloadToken","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","symbolKind":"class","title":"SDWebImageDownloadToken","externalID":"c:objc(cs)SDWebImageDownloadToken","roleHeading":"Class","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloadToken"}]},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloadtoken"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloadtoken"]}],"abstract":[{"type":"text","text":"A token associated with each download. Can be used to cancel a download"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloadToken"}],"platforms":["iOS"],"languages":["swift"]}]}],"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/metrics","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/request","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/response","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/url"],"generated":true,"anchor":"Instance-Properties","title":"Instance Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/cancel()"],"title":"Instance Methods","generated":true,"anchor":"Instance-Methods"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/SQ":{"title":"Swift.Equatable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken":{"abstract":[{"type":"text","text":"A token associated with each download. Can be used to cancel a download"}],"kind":"symbol","role":"symbol","title":"SDWebImageDownloadToken","navigatorTitle":[{"text":"SDWebImageDownloadToken","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken","url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageDownloadToken","kind":"identifier"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken/request":{"type":"topic","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"request","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLRequest","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation10URLRequestV"},{"text":"?","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/request","url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken\/request","abstract":[{"type":"text","text":"The download’s request."}],"kind":"symbol","title":"request","navigatorTitle":[{"text":"request","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOperation":{"url":"\/documentation\/sdwebimage\/sdwebimageoperation","role":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOperation"}],"navigatorTitle":[{"text":"SDWebImageOperation","kind":"identifier"}],"type":"topic","kind":"symbol","title":"SDWebImageOperation","abstract":[{"type":"text","text":"A protocol represents cancelable operation."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken/response":{"role":"symbol","kind":"symbol","title":"response","navigatorTitle":[{"kind":"identifier","text":"response"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken\/response","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"response","kind":"identifier"},{"text":": ","kind":"text"},{"text":"URLResponse","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/response","abstract":[{"text":"The download’s response.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken/cancel()":{"type":"topic","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"cancel","kind":"identifier"},{"text":"()","kind":"text"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/cancel()","url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken\/cancel()","abstract":[{"text":"Cancel the current download.","type":"text"}],"kind":"symbol","title":"cancel()","navigatorTitle":[{"text":"cancel","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken/url":{"abstract":[{"text":"The download’s URL.","type":"text"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/url","navigatorTitle":[{"text":"url","kind":"identifier"}],"type":"topic","role":"symbol","kind":"symbol","title":"url","url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken\/url"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloadToken/metrics":{"role":"symbol","kind":"symbol","title":"metrics","navigatorTitle":[{"kind":"identifier","text":"metrics"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloadtoken\/metrics","type":"topic","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"metrics","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics","text":"URLSessionTaskMetrics","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/metrics","abstract":[{"text":"The download’s metrics. This will be nil if download operation does not support metrics.","type":"text"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"ObjectiveC.NSObjectProtocol","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Class","op":"replace"},{"value":"SDWebImageDownloadToken","op":"replace","path":"\/metadata\/title"},{"value":"class","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"SDWebImageDownloadToken","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageDownloadToken"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"anchor":"Instance-Properties","title":"Instance Properties","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/metrics","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/request","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/response","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/url"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloadToken\/cancel()"],"anchor":"Instance-Methods","generated":true,"title":"Instance Methods"}],"op":"replace"},{"value":[{"type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOperation"],"kind":"relationships","type":"conformsTo","title":"Conforms To"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"@interface","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloadToken"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace"},{"value":"SDWebImageDownloadToken","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken\/fragments","op":"replace","value":[{"text":"SDWebImageDownloadToken","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDWebImageDownloadToken"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken\/navigatorTitle","op":"replace"},{"op":"replace","value":"request","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1request\/title"},{"op":"replace","value":[{"kind":"identifier","text":"request"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1request\/fragments"},{"value":"SDWebImageOperation","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/title"},{"value":[{"kind":"identifier","text":"SDWebImageOperation"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageOperation"}]},{"value":"response","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1response\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1response\/fragments","value":[{"text":"response","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1cancel()\/title","value":"cancel","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"text":"cancel","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1cancel()\/fragments"},{"op":"replace","value":"url","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1url\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1url\/fragments","value":[{"text":"url","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1metrics\/title","op":"replace","value":"metrics"},{"value":[{"text":"metrics","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloadToken~1metrics\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}