{"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageProgressUnitCountUnknown"},{"text":": ","kind":"text"},{"text":"Int64","kind":"typeIdentifier","preciseIdentifier":"s:s5Int64V"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprogressunitcountunknown"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprogressunitcountunknown"]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressUnitCountUnknown","interfaceLanguage":"swift"},"abstract":[{"text":"The value specify that the image progress unit count cannot be determined because the progressBlock is not been called.","type":"text"}],"metadata":{"externalID":"c:@SDWebImageProgressUnitCountUnknown","title":"SDWebImageProgressUnitCountUnknown","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageProgressUnitCountUnknown","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"symbolKind":"var","roleHeading":"Global Variable","modules":[{"name":"SDWebImage"}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageProgressUnitCountUnknown","kind":"identifier"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageProgressUnitCountUnknown":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageProgressUnitCountUnknown","title":"SDWebImageProgressUnitCountUnknown","abstract":[{"type":"text","text":"The value specify that the image progress unit count cannot be determined because the progressBlock is not been called."}],"type":"topic","navigatorTitle":[{"text":"SDWebImageProgressUnitCountUnknown","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprogressunitcountunknown","kind":"symbol","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageProgressUnitCountUnknown","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int64V","text":"Int64","kind":"typeIdentifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"SDWebImageProgressUnitCountUnknown","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageProgressUnitCountUnknown","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"int64_t","kind":"typeIdentifier","preciseIdentifier":"c:@T@int64_t"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageProgressUnitCountUnknown"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressUnitCountUnknown\/title","value":"SDWebImageProgressUnitCountUnknown"},{"op":"replace","value":[{"text":"SDWebImageProgressUnitCountUnknown","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageProgressUnitCountUnknown\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}