{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderconfig"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCopying","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The class contains all the config for image downloader"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"title":"SDWebImageDownloaderConfig","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDWebImageDownloaderConfig","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableContentTypes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableStatusCodes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/downloadTimeout","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/executionOrder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/maxConcurrentDownloads","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/minimumProgressInterval","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/operationClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/password","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/sessionConfiguration","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/urlCredential","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/username"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/default"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/downloadTimeout":{"role":"symbol","title":"downloadTimeout","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadTimeout"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The timeout value (in seconds) for each download operation."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 15.0."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/downloadTimeout","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadTimeout"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/downloadtimeout"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/maxConcurrentDownloads":{"role":"symbol","title":"maxConcurrentDownloads","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"maxConcurrentDownloads"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"}],"abstract":[{"type":"text","text":"The maximum number of concurrent downloads."},{"type":"text","text":" "},{"type":"text","text":"Defaults to 6."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/maxConcurrentDownloads","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"maxConcurrentDownloads"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/maxconcurrentdownloads"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/executionOrder":{"role":"symbol","title":"executionOrder","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"executionOrder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderExecutionOrder","preciseIdentifier":"c:@E@SDWebImageDownloaderExecutionOrder"}],"abstract":[{"type":"text","text":"Changes download operations execution order."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"SDWebImageDownloaderFIFOExecutionOrder"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/executionOrder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"executionOrder"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/executionorder"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/sessionConfiguration":{"role":"symbol","title":"sessionConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The custom session configuration in use by NSURLSession. If you don’t provide one, we will use "},{"type":"codeVoice","code":"defaultSessionConfiguration"},{"type":"text","text":" instead."},{"type":"text","text":" "},{"type":"text","text":"Defatuls to nil."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/sessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionConfiguration"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/sessionconfiguration"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/password":{"role":"symbol","title":"password","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"password"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set password using for HTTP Basic authentication."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/password","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"password"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/password"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/operationClass":{"role":"symbol","title":"operationClass","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"operationClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"AnyClass","preciseIdentifier":"s:s8AnyClassa"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Gets\/Sets a subclass of "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"},{"type":"text","text":" as the default"},{"type":"text","text":" "},{"type":"codeVoice","code":"NSOperation"},{"type":"text","text":" to be used each time SDWebImage constructs a request"},{"type":"text","text":" "},{"type":"text","text":"operation to download an image."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/operationClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"operationClass"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/operationclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig":{"role":"symbol","title":"SDWebImageDownloaderConfig","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"abstract":[{"type":"text","text":"The class contains all the config for image downloader"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/acceptableStatusCodes":{"role":"symbol","title":"acceptableStatusCodes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableStatusCodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response status code. The status code which beyond the range will mark the download operation failed."},{"type":"text","text":" "},{"type":"text","text":"For example, if we config [200, 400) but server response is 503, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadStatusCode"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Defaults to [200,400). Nil means no validation at all."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableStatusCodes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptableStatusCodes"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/acceptablestatuscodes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/default":{"role":"symbol","title":"default","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"`default`"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderConfig","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig"}],"abstract":[{"type":"text","text":"Gets the default downloader config used for shared instance or initialization when it does not provide any downloader config. Such as "},{"type":"codeVoice","code":"SDWebImageDownloader.sharedDownloader"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/default","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultDownloaderConfig"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/default"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/minimumProgressInterval":{"role":"symbol","title":"minimumProgressInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumProgressInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[{"type":"text","text":"The minimum interval about progress percent during network downloading. Which means the next progress callback and current progress callback’s progress percent difference should be larger or equal to this value. However, the final finish download progress callback does not get effected."},{"type":"text","text":" "},{"type":"text","text":"The value should be 0.0-1.0."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/minimumProgressInterval","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"minimumProgressInterval"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/minimumprogressinterval"},"doc://com.dailymotion.SDWebImage/objc(pl)NSCopying":{"type":"unresolvable","title":"NSCopying","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCopying"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/username":{"role":"symbol","title":"username","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"username"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set username using for HTTP Basic authentication."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/username","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"username"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/username"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/urlCredential":{"role":"symbol","title":"urlCredential","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"urlCredential"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the default URL credential to be set for request operations."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/urlCredential","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"urlCredential"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/urlcredential"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderConfig/acceptableContentTypes":{"role":"symbol","title":"acceptableContentTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableContentTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">?"}],"abstract":[{"type":"text","text":"Set the acceptable HTTP Response content type. The content type beyond the set will mark the download operation failed."},{"type":"text","text":" "},{"type":"text","text":"For example, if we config [“image\/png”] but server response is “application\/json”, the download will fail with error code "},{"type":"codeVoice","code":"SDWebImageErrorInvalidDownloadContentType"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Normally you don’t need this for image format detection because we use image’s data file signature magic bytes: https:\/\/en.wikipedia.org\/wiki\/List_of_file_signatures"},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil. Nil means no validation at all."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableContentTypes","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"acceptableContentTypes"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderconfig\/acceptablecontenttypes"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderConfig"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableContentTypes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/acceptableStatusCodes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/downloadTimeout","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/executionOrder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/maxConcurrentDownloads","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/minimumProgressInterval","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/operationClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/password","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/sessionConfiguration","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/urlCredential","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/username"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderConfig\/default"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSCopying"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderConfig"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1downloadTimeout\/title","value":"downloadTimeout"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1downloadTimeout\/fragments","value":[{"kind":"identifier","text":"downloadTimeout"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1maxConcurrentDownloads\/title","value":"maxConcurrentDownloads"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1maxConcurrentDownloads\/fragments","value":[{"kind":"identifier","text":"maxConcurrentDownloads"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1executionOrder\/title","value":"executionOrder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1executionOrder\/fragments","value":[{"kind":"identifier","text":"executionOrder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1sessionConfiguration\/title","value":"sessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1sessionConfiguration\/fragments","value":[{"kind":"identifier","text":"sessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1password\/title","value":"password"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1password\/fragments","value":[{"kind":"identifier","text":"password"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1operationClass\/title","value":"operationClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1operationClass\/fragments","value":[{"kind":"identifier","text":"operationClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/title","value":"SDWebImageDownloaderConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1acceptableStatusCodes\/title","value":"acceptableStatusCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1acceptableStatusCodes\/fragments","value":[{"kind":"identifier","text":"acceptableStatusCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1default\/title","value":"defaultDownloaderConfig"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1default\/fragments","value":[{"kind":"identifier","text":"defaultDownloaderConfig"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1minimumProgressInterval\/title","value":"minimumProgressInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1minimumProgressInterval\/fragments","value":[{"kind":"identifier","text":"minimumProgressInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1username\/title","value":"username"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1username\/fragments","value":[{"kind":"identifier","text":"username"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1urlCredential\/title","value":"urlCredential"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1urlCredential\/fragments","value":[{"kind":"identifier","text":"urlCredential"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1acceptableContentTypes\/title","value":"acceptableContentTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderConfig~1acceptableContentTypes\/fragments","value":[{"kind":"identifier","text":"acceptableContentTypes"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}