{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"URLSessionDataDelegate","preciseIdentifier":"c:objc(pl)NSURLSessionDataDelegate"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDataDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionTaskDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from "},{"type":"codeVoice","code":"NSOperation"},{"type":"text","text":" and conform to this protocol"},{"type":"text","text":" "},{"type":"text","text":"For the description about these methods, see "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"title":"SDWebImageDownloaderOperationProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDWebImageDownloaderOperation","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:context:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/acceptableContentTypes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/acceptableStatusCodes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/credential","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/dataTask","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/metrics","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/minimumProgressInterval","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/request","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/response"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:decodeOptions:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/cancel(_:)"]}],"references":{"doc://com.dailymotion.SDWebImage/objc(pl)NSURLSessionDelegate":{"type":"unresolvable","title":"Foundation.URLSessionDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/init(request:inSession:options:context:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithRequest:inSession:options:context:"}],"role":"symbol","title":"init(request:inSession:options:context:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?)"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:context:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:insession:options:context:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperation-swift.class":{"role":"symbol","title":"SDWebImageDownloaderOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"abstract":[{"type":"text","text":"The download operation class for SDWebImageDownloader."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperation-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/cancel(_:)":{"navigatorTitle":[{"kind":"identifier","text":"cancel:"}],"role":"symbol","title":"cancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancel"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/cancel(_:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/cancel(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/dataTask":{"navigatorTitle":[{"kind":"identifier","text":"dataTask"}],"role":"symbol","title":"dataTask","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"dataTask"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTask","preciseIdentifier":"c:objc(cs)NSURLSessionTask"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/dataTask","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/datatask"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/acceptableStatusCodes":{"navigatorTitle":[{"kind":"identifier","text":"acceptableStatusCodes"}],"role":"symbol","title":"acceptableStatusCodes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableStatusCodes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"IndexSet","preciseIdentifier":"s:10Foundation8IndexSetV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/acceptableStatusCodes","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/acceptablestatuscodes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/credential":{"role":"symbol","title":"credential","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"credential"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLCredential","preciseIdentifier":"c:objc(cs)NSURLCredential"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/credential","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"credential"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/credential"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/response":{"navigatorTitle":[{"kind":"identifier","text":"response"}],"role":"symbol","title":"response","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"response"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLResponse","preciseIdentifier":"c:objc(cs)NSURLResponse"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/response","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/response"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/minimumProgressInterval":{"navigatorTitle":[{"kind":"identifier","text":"minimumProgressInterval"}],"role":"symbol","title":"minimumProgressInterval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"minimumProgressInterval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/minimumProgressInterval","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/minimumprogressinterval"},"doc://com.dailymotion.SDWebImage/objc(pl)NSURLSessionTaskDelegate":{"type":"unresolvable","title":"NSURLSessionTaskDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionTaskDelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/init(request:inSession:options:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithRequest:inSession:options:"}],"role":"symbol","title":"init(request:inSession:options:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"inSession"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSession","preciseIdentifier":"c:objc(cs)NSURLSession"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/init(request:insession:options:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSURLSessionDataDelegate":{"type":"unresolvable","title":"NSURLSessionDataDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDataDelegate"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/addHandlers(forProgress:completed:)":{"navigatorTitle":[{"kind":"identifier","text":"addHandlersForProgress:completed:"}],"role":"symbol","title":"addHandlers(forProgress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/addhandlers(forprogress:completed:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/request":{"navigatorTitle":[{"kind":"identifier","text":"request"}],"role":"symbol","title":"request","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"request"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLRequest","preciseIdentifier":"s:10Foundation10URLRequestV"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/request","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/request"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/acceptableContentTypes":{"navigatorTitle":[{"kind":"identifier","text":"acceptableContentTypes"}],"role":"symbol","title":"acceptableContentTypes","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"acceptableContentTypes"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Set","preciseIdentifier":"s:Sh"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":">?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/acceptableContentTypes","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/acceptablecontenttypes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/addHandlers(forProgress:completed:decodeOptions:)":{"navigatorTitle":[{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}],"role":"symbol","title":"addHandlers(forProgress:completed:decodeOptions:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addHandlers"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forProgress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"decodeOptions"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDImageCoderOption","preciseIdentifier":"c:SDImageCoder.h@T@SDImageCoderOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?) -> "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:decodeOptions:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/addhandlers(forprogress:completed:decodeoptions:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol":{"role":"symbol","title":"SDWebImageDownloaderOperationProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"abstract":[{"type":"text","text":"Describes a downloader operation. If one wants to use a custom downloader op, it needs to inherit from "},{"type":"codeVoice","code":"NSOperation"},{"type":"text","text":" and conform to this protocol"},{"type":"text","text":" "},{"type":"text","text":"For the description about these methods, see "},{"type":"codeVoice","code":"SDWebImageDownloaderOperation"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderOperationProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderOperationProtocol/metrics":{"role":"symbol","title":"metrics","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"metrics"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionTaskMetrics","preciseIdentifier":"c:objc(cs)NSURLSessionTaskMetrics"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/metrics","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"metrics"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderoperationprotocol\/metrics"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/acceptableContentTypes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/acceptableStatusCodes","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/credential","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/dataTask","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/metrics","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/minimumProgressInterval","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/request","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/response"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/addHandlers(forProgress:completed:decodeOptions:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/cancel(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperationProtocol\/init(request:inSession:options:context:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionDataDelegate","doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSURLSessionTaskDelegate"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderOperation-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderOperation"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSURLSessionTaskDelegate"},{"kind":"text","text":", "},{"kind":"keyword","text":"NSURLSessionDataDelegate"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1init(request:inSession:options:context:)\/title","value":"initWithRequest:inSession:options:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1init(request:inSession:options:context:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequest:inSession:options:context:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperation-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1cancel(_:)\/title","value":"cancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1cancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1dataTask\/title","value":"dataTask"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1dataTask\/fragments","value":[{"kind":"identifier","text":"dataTask"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1acceptableStatusCodes\/title","value":"acceptableStatusCodes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1acceptableStatusCodes\/fragments","value":[{"kind":"identifier","text":"acceptableStatusCodes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1credential\/title","value":"credential"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1credential\/fragments","value":[{"kind":"identifier","text":"credential"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1response\/title","value":"response"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1response\/fragments","value":[{"kind":"identifier","text":"response"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1minimumProgressInterval\/title","value":"minimumProgressInterval"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1minimumProgressInterval\/fragments","value":[{"kind":"identifier","text":"minimumProgressInterval"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1init(request:inSession:options:)\/title","value":"initWithRequest:inSession:options:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1init(request:inSession:options:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithRequest:inSession:options:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1addHandlers(forProgress:completed:)\/title","value":"addHandlersForProgress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1addHandlers(forProgress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addHandlersForProgress:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1request\/title","value":"request"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1request\/fragments","value":[{"kind":"identifier","text":"request"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1acceptableContentTypes\/title","value":"acceptableContentTypes"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1acceptableContentTypes\/fragments","value":[{"kind":"identifier","text":"acceptableContentTypes"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1addHandlers(forProgress:completed:decodeOptions:)\/title","value":"addHandlersForProgress:completed:decodeOptions:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1addHandlers(forProgress:completed:decodeOptions:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addHandlersForProgress:completed:decodeOptions:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/title","value":"SDWebImageDownloaderOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderOperation"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1metrics\/title","value":"metrics"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderOperationProtocol~1metrics\/fragments","value":[{"kind":"identifier","text":"metrics"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}