{"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageerrordownloadcontenttypekey"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageerrordownloadcontenttypekey"]}],"abstract":[{"type":"text","text":"The HTTP MIME content type for invalid download response (NSString *)"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageErrorDownloadContentTypeKey"}],"roleHeading":"Global Variable","externalID":"c:@SDWebImageErrorDownloadContentTypeKey","role":"symbol","symbolKind":"var","title":"SDWebImageErrorDownloadContentTypeKey","fragments":[{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageErrorDownloadContentTypeKey"},{"kind":"text","text":": "},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"}]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageErrorDownloadContentTypeKey","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageErrorDownloadContentTypeKey","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"}],"platforms":["iOS"],"languages":["swift"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageErrorDownloadContentTypeKey":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageErrorDownloadContentTypeKey","abstract":[{"type":"text","text":"The HTTP MIME content type for invalid download response (NSString *)"}],"fragments":[{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageErrorDownloadContentTypeKey","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"}],"title":"SDWebImageErrorDownloadContentTypeKey","navigatorTitle":[{"text":"SDWebImageErrorDownloadContentTypeKey","kind":"identifier"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageerrordownloadcontenttypekey"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SDWebImageErrorDownloadContentTypeKey","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"value":[{"text":"SDWebImageErrorDownloadContentTypeKey","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageErrorDownloadContentTypeKey"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageErrorDownloadContentTypeKey\/title","value":"SDWebImageErrorDownloadContentTypeKey"},{"value":[{"kind":"identifier","text":"SDWebImageErrorDownloadContentTypeKey"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageErrorDownloadContentTypeKey\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}