{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/indicatorView"],"generated":true,"title":"Instance Properties","anchor":"Instance-Properties"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/gray","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/grayLarge","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/large","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/medium","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/white","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/whiteLarge"],"title":"Type Properties","anchor":"Type-Properties","generated":true}],"metadata":{"externalID":"c:objc(cs)SDWebImageActivityIndicator","modules":[{"name":"SDWebImage"}],"symbolKind":"class","title":"SDWebImageActivityIndicator","navigatorTitle":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"role":"symbol","roleHeading":"Class"},"schemaVersion":{"major":0,"patch":0,"minor":3},"abstract":[{"text":"Activity indicator class.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"for AppKit(macOS), it use a ","type":"text"},{"code":"NSProgressIndicator","type":"codeVoice"},{"type":"text","text":" with the spinning style."}],"kind":"symbol","relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"title":"Inherits From","kind":"relationships","type":"inheritsFrom"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","kind":"relationships"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/white":{"abstract":[{"text":"white-style activity indicator","type":"text"}],"title":"white","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/white","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"white","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator","kind":"typeIdentifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/white","kind":"symbol","navigatorTitle":[{"text":"whiteIndicator","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageIndicator":{"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageIndicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator","abstract":[{"text":"A protocol to custom the indicator during the image loading.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"All of these methods are called from main queue."}],"role":"symbol","navigatorTitle":[{"text":"SDWebImageIndicator","kind":"identifier"}],"kind":"symbol","title":"SDWebImageIndicator","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageindicator"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/grayLarge":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/grayLarge","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"grayLargeIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/graylarge","abstract":[{"text":"large gray-style activity indicator","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grayLarge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageActivityIndicator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"title":"grayLarge"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/whiteLarge":{"title":"whiteLarge","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/whiteLarge","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/whitelarge","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"whiteLarge","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageActivityIndicator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"navigatorTitle":[{"text":"whiteLargeIndicator","kind":"identifier"}],"abstract":[{"type":"text","text":"large white-style activity indicator"}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/indicatorView":{"navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"type":"topic","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicatorView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","text":"UIActivityIndicatorView","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/indicatorView","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/indicatorview","kind":"symbol"},"doc://com.dailymotion.SDWebImage/SQ":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/medium":{"role":"symbol","navigatorTitle":[{"text":"mediumIndicator","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/medium","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"medium"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator"}],"title":"medium","abstract":[{"type":"text","text":"medium activity indicator"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/medium","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/large":{"navigatorTitle":[{"text":"largeIndicator","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/large","title":"large","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/large","abstract":[{"text":"These indicator use the system style, supports dark mode if available (iOS 13+\/macOS 10.14+)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"large activity indicator"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"large","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/gray":{"navigatorTitle":[{"kind":"identifier","text":"grayIndicator"}],"type":"topic","title":"gray","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"gray","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","kind":"typeIdentifier"}],"abstract":[{"text":"These indicator use the fixed color without dark mode support","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"gray-style activity indicator"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/gray","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/gray","kind":"symbol"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"type":"topic","abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"code":"NSProgressIndicator","type":"codeVoice"},{"type":"text","text":" with the spinning style."}],"kind":"symbol","title":"SDWebImageActivityIndicator","navigatorTitle":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"title":"Swift.CustomStringConvertible","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageActivityIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"replace","value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"path":"\/topicSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/indicatorView"],"title":"Instance Properties","anchor":"Instance-Properties","generated":true},{"title":"Type Properties","anchor":"Type-Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/gray","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/grayLarge","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/large","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/medium","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/white","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/whiteLarge"],"generated":true}],"op":"replace"},{"value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"type":"inheritsFrom","title":"Inherits From","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageIndicator"]}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageActivityIndicator"},{"text":" : ","kind":"text"},{"text":"NSObject","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSObject"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"whiteIndicator","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1white\/title"},{"value":[{"text":"whiteIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1white\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/title","value":"SDWebImageIndicator"},{"value":[{"kind":"identifier","text":"SDWebImageIndicator"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageIndicator\/navigatorTitle","value":[{"text":"SDWebImageIndicator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1grayLarge\/title","value":"grayLargeIndicator"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1grayLarge\/fragments","value":[{"kind":"identifier","text":"grayLargeIndicator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1whiteLarge\/title","value":"whiteLargeIndicator"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1whiteLarge\/fragments","value":[{"text":"whiteLargeIndicator","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1indicatorView\/title","value":"indicatorView"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1indicatorView\/fragments","value":[{"kind":"identifier","text":"indicatorView"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1medium\/title","value":"mediumIndicator"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1medium\/fragments","op":"replace","value":[{"text":"mediumIndicator","kind":"identifier"}]},{"value":"largeIndicator","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1large\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1large\/fragments","value":[{"text":"largeIndicator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1gray\/title","value":"grayIndicator"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1gray\/fragments","value":[{"kind":"identifier","text":"grayIndicator"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","value":"SDWebImageActivityIndicator"},{"op":"replace","value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments"},{"value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/navigatorTitle","op":"replace"}]}]}