{"abstract":[{"text":"A downloader request modifier class with block.","type":"text"}],"topicSections":[{"title":"Initializers","anchor":"Initializers","generated":true,"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(block:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(body:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(headers:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:headers:body:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"kind":"symbol","schemaVersion":{"major":0,"patch":0,"minor":3},"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships"},{"type":"conformsTo","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"title":"Conforms To","kind":"relationships"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"metadata":{"externalID":"c:objc(cs)SDWebImageDownloaderRequestModifier","symbolKind":"class","role":"symbol","roleHeading":"Class","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"title":"SDWebImageDownloaderRequestModifier","modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(method:headers:body:)":{"type":"topic","abstract":[{"type":"text","text":"Create the request modifier with HTTP Method, Headers and Body."}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:headers:body:)","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(method:headers:body:)","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"text":"method","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"String","kind":"typeIdentifier","preciseIdentifier":"s:SS"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"headers"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:SS","text":"String","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"body"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV","text":"Data"},{"text":"?)","kind":"text"}],"navigatorTitle":[{"text":"initWithMethod:headers:body:","kind":"identifier"}],"title":"init(method:headers:body:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(method:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:)","abstract":[{"text":"Create the request modifier with HTTP Method.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(method:)","role":"symbol","fragments":[{"kind":"identifier","text":"init"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"method"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"kind":"text","text":"?)"}],"navigatorTitle":[{"text":"initWithMethod:","kind":"identifier"}],"kind":"symbol","title":"init(method:)","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(headers:)":{"abstract":[{"text":"Create the request modifier with HTTP Headers.","type":"text"}],"title":"init(headers:)","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(headers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"headers","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(headers:)","kind":"symbol","navigatorTitle":[{"text":"initWithHeaders:","kind":"identifier"}],"type":"topic","role":"symbol"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject","title":"NSObject"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ","title":"Swift.Equatable"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifierProtocol":{"type":"topic","abstract":[{"type":"text","text":"This is the protocol for downloader request modifier."},{"type":"text","text":" "},{"text":"We can use a block to specify the downloader request modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifierprotocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol","kind":"symbol","title":"SDWebImageDownloaderRequestModifierProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifierProtocol"}],"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifierProtocol","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class","role":"symbol","abstract":[{"text":"A downloader request modifier class with block.","type":"text"}],"navigatorTitle":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"type":"topic","title":"SDWebImageDownloaderRequestModifier","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(block:)":{"navigatorTitle":[{"text":"initWithBlock:","kind":"identifier"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(block:)","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(block:)","kind":"symbol","abstract":[{"type":"text","text":"Create the request modifier with block"}],"role":"symbol","title":"init(block:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"text":"block","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDownloaderRequestModifier.h@T@SDWebImageDownloaderRequestModifierBlock","text":"SDWebImageDownloaderRequestModifierBlock","kind":"typeIdentifier"},{"text":")","kind":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/init(body:)":{"navigatorTitle":[{"kind":"identifier","text":"initWithBody:"}],"type":"topic","abstract":[{"text":"Create the request modifier with HTTP Body.","type":"text"}],"title":"init(body:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(body:)","url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/init(body:)","kind":"symbol","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"body","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Data","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?)","kind":"text"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderRequestModifier-swift.class/requestModifierWithBlock:":{"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderrequestmodifier-swift.class\/requestmodifierwithblock:","navigatorTitle":[{"text":"requestModifierWithBlock:","kind":"identifier"}],"title":"requestModifierWithBlock:","type":"topic","kind":"symbol","fragments":[{"kind":"text","text":"+ "},{"text":"requestModifierWithBlock:","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/requestModifierWithBlock:","abstract":[{"text":"Create the request modifier with block","type":"text"}]},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible"},"doc://com.dailymotion.SDWebImage/SH":{"title":"Swift.Hashable","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"title":"Swift.CVarArg","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Class","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderRequestModifier"},{"path":"\/metadata\/symbolKind","op":"replace","value":"class"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}],"op":"replace"},{"path":"\/metadata\/navigatorTitle","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(block:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(body:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(headers:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/init(method:headers:body:)"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifier-swift.class\/requestModifierWithBlock:"],"title":"Type Methods","generated":true,"anchor":"Type-Methods"}]},{"path":"\/relationshipsSections","value":[{"type":"inheritsFrom","title":"Inherits From","kind":"relationships","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderRequestModifierProtocol"],"title":"Conforms To","type":"conformsTo","kind":"relationships"}],"op":"replace"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}]}]},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(method:headers:body:)\/title","value":"initWithMethod:headers:body:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(method:headers:body:)\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithMethod:headers:body:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(method:)\/title","value":"initWithMethod:"},{"value":[{"text":"- ","kind":"text"},{"text":"initWithMethod:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(method:)\/fragments","op":"replace"},{"value":"initWithHeaders:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(headers:)\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(headers:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithHeaders:","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/title","value":"SDWebImageDownloaderRequestModifier","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderRequestModifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifierProtocol\/navigatorTitle","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/title","value":"SDWebImageDownloaderRequestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/fragments","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageDownloaderRequestModifier","kind":"identifier"}]},{"value":"initWithBlock:","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(block:)\/title"},{"op":"replace","value":[{"text":"- ","kind":"text"},{"text":"initWithBlock:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(block:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(body:)\/title","value":"initWithBody:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithBody:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderRequestModifier-swift.class~1init(body:)\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}