{"kind":"symbol","variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherprogressblock"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherprogressblock"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherProgressBlock"},"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Alias","navigatorTitle":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}],"externalID":"c:SDWebImagePrefetcher.h@T@SDWebImagePrefetcherProgressBlock","title":"SDWebImagePrefetcherProgressBlock","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImagePrefetcherProgressBlock"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"},{"kind":"text","text":" = ("},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"s:s4Voida","text":"Void"}]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherProgressBlock":{"role":"symbol","abstract":[],"type":"topic","navigatorTitle":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherprogressblock","kind":"symbol","title":"SDWebImagePrefetcherProgressBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherProgressBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"op":"replace","value":"SDWebImagePrefetcherProgressBlock","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}]},{"op":"replace","value":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(unsigned long, unsigned long)","preciseIdentifier":"c:BFv(#l#l)"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"]}]}},{"value":"SDWebImagePrefetcherProgressBlock","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherProgressBlock\/title"},{"value":[{"kind":"identifier","text":"SDWebImagePrefetcherProgressBlock"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherProgressBlock\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherProgressBlock\/navigatorTitle","value":[{"text":"SDWebImagePrefetcherProgressBlock","kind":"identifier"}]}]}]}