{"abstract":[{"text":"This is the protocol for cache serializer.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"We can use a block to specify the cache serializer. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"code":"@convention(block)","type":"codeVoice"},{"text":" to store a block into context options.","type":"text"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol"},"kind":"symbol","sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"schemaVersion":{"patch":0,"minor":3,"major":0},"metadata":{"navigatorTitle":[{"text":"SDWebImageCacheSerializerProtocol","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"symbolKind":"protocol","role":"symbol","roleHeading":"Protocol","externalID":"c:objc(pl)SDWebImageCacheSerializer","title":"SDWebImageCacheSerializerProtocol","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageCacheSerializerProtocol","kind":"identifier"}]},"topicSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol\/cacheData(with:originalData:imageURL:)"],"generated":true,"anchor":"Instance-Methods","title":"Instance Methods"}],"relationshipsSections":[{"type":"inheritsFrom","title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class"],"kind":"relationships","type":"conformingTypes","title":"Conforming Types"}],"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheSerializerProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializerProtocol":{"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol","navigatorTitle":[{"text":"SDWebImageCacheSerializerProtocol","kind":"identifier"}],"title":"SDWebImageCacheSerializerProtocol","role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol","abstract":[{"type":"text","text":"This is the protocol for cache serializer."},{"text":" ","type":"text"},{"text":"We can use a block to specify the cache serializer. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using ","type":"text"},{"code":"@convention(block)","type":"codeVoice"},{"type":"text","text":" to store a block into context options."}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCacheSerializerProtocol"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializerProtocol/cacheData(with:originalData:imageURL:)":{"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol\/cacheData(with:originalData:imageURL:)","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheData"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UIImage","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"originalData","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"imageURL"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?) -> ","kind":"text"},{"preciseIdentifier":"s:10Foundation4DataV","text":"Data","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"abstract":[{"text":"Provide the image data associated to the image and store to disk cache","type":"text"}],"role":"symbol","required":true,"navigatorTitle":[{"text":"cacheDataWithImage:originalData:imageURL:","kind":"identifier"}],"title":"cacheData(with:originalData:imageURL:)","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecacheserializerprotocol\/cachedata(with:originaldata:imageurl:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializer-swift.class":{"kind":"symbol","type":"topic","title":"SDWebImageCacheSerializer","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"abstract":[{"text":"A cache serializer class with block.","type":"text"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageCacheSerializer","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","type":"unresolvable","title":"NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Protocol","path":"\/metadata\/roleHeading","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageCacheSerializer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"path":"\/metadata\/fragments"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}]},{"value":[{"anchor":"Instance-Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerProtocol\/cacheData(with:originalData:imageURL:)"],"title":"Instance Methods","generated":true}],"op":"replace","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"replace","value":[{"title":"Inherits From","kind":"relationships","type":"inheritsFrom","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"]},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class"],"title":"Conforming Types","type":"conformingTypes","kind":"relationships"}]},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageCacheSerializer","kind":"identifier"},{"text":" <","kind":"text"},{"preciseIdentifier":"c:objc(pl)NSObject","text":"NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"}},{"value":"SDWebImageCacheSerializer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol\/title","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageCacheSerializer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol\/fragments"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol~1cacheData(with:originalData:imageURL:)\/title","value":"cacheDataWithImage:originalData:imageURL:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerProtocol~1cacheData(with:originalData:imageURL:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"cacheDataWithImage:originalData:imageURL:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/title","value":"SDWebImageCacheSerializer"},{"value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/fragments","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/navigatorTitle"}]}]}