{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderprogressblock"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderprogressblock"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","interfaceLanguage":"swift"},"metadata":{"symbolKind":"typealias","externalID":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock","fragments":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"role":"symbol","title":"SDWebImageDownloaderProgressBlock","roleHeading":"Type Alias","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"},{"kind":"text","text":" = "},{"preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","text":"SDImageLoaderProgressBlock","kind":"typeIdentifier"}]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderProgressBlock":{"role":"symbol","type":"topic","abstract":[],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderProgressBlock","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"title":"SDWebImageDownloaderProgressBlock","navigatorTitle":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderprogressblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderProgressBlock":{"abstract":[],"title":"SDImageLoaderProgressBlock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","url":"\/documentation\/sdwebimage\/sdimageloaderprogressblock","kind":"symbol","role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Type Alias","path":"\/metadata\/roleHeading","op":"replace"},{"value":"SDWebImageDownloaderProgressBlock","op":"replace","path":"\/metadata\/title"},{"value":"typealias","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageDownloaderProgressBlock"}]},{"value":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}],"op":"replace","path":"\/metadata\/navigatorTitle"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"typedef","kind":"keyword"},{"text":" ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","kind":"typeIdentifier","text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock"},{"kind":"text","text":" "},{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","value":"SDWebImageDownloaderProgressBlock","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/fragments","op":"replace","value":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderProgressBlock\/navigatorTitle","value":[{"text":"SDWebImageDownloaderProgressBlock","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/title","value":"SDImageLoaderProgressBlock"},{"value":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/fragments"},{"value":[{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/navigatorTitle","op":"replace"}]}]}