{"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol"},"abstract":[{"text":"This is the protocol for options processor.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Options processor can be used, to control the final result for individual image request’s "},{"code":"SDWebImageOptions","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"SDWebImageContext"},{"type":"text","text":" "},{"text":"Implements the protocol to have a global control for each indivadual image request’s option.","type":"text"}],"topicSections":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol\/processedResult(for:options:context:)"]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptionsprocessorprotocol"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageoptionsprocessorprotocol"]}],"metadata":{"role":"symbol","symbolKind":"protocol","navigatorTitle":[{"text":"SDWebImageOptionsProcessorProtocol","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(pl)SDWebImageOptionsProcessor","title":"SDWebImageOptionsProcessorProtocol","roleHeading":"Protocol","fragments":[{"kind":"keyword","text":"protocol"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOptionsProcessorProtocol"}]},"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom","title":"Inherits From"},{"type":"conformingTypes","kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class"]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOptionsProcessorProtocol"},{"text":" : ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)NSObject","text":"NSObjectProtocol"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptionsProcessor-swift.class":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptionsProcessor"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptionsprocessor-swift.class","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageOptionsProcessor","kind":"identifier"}],"title":"SDWebImageOptionsProcessor","role":"symbol","type":"topic","abstract":[{"text":"A options processor class with block.","type":"text"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptionsProcessorProtocol":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptionsProcessorProtocol"}],"type":"topic","title":"SDWebImageOptionsProcessorProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol","url":"\/documentation\/sdwebimage\/sdwebimageoptionsprocessorprotocol","abstract":[{"text":"This is the protocol for options processor.","type":"text"},{"text":" ","type":"text"},{"text":"Options processor can be used, to control the final result for individual image request’s ","type":"text"},{"code":"SDWebImageOptions","type":"codeVoice"},{"type":"text","text":" and "},{"code":"SDWebImageContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"Implements the protocol to have a global control for each indivadual image request’s option."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptionsProcessorProtocol"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptionsProcessorProtocol/processedResult(for:options:context:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol\/processedResult(for:options:context:)","navigatorTitle":[{"kind":"identifier","text":"processedResultForURL:options:context:"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptionsprocessorprotocol\/processedresult(for:options:context:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"processedResult"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"text":": [","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageOptionsResult","text":"SDWebImageOptionsResult"},{"kind":"text","text":"?"}],"title":"processedResult(for:options:context:)","role":"symbol","type":"topic","required":true,"abstract":[{"type":"text","text":"Return the processed options result for specify image URL, with its options and context"}],"kind":"symbol"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"title":"NSObject","type":"unresolvable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageOptionsProcessor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"value":[{"text":"SDWebImageOptionsProcessor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageOptionsProcessor"}]},{"path":"\/topicSections","value":[{"generated":true,"anchor":"Instance-Methods","title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol\/processedResult(for:options:context:)"]}],"op":"replace"},{"value":[{"title":"Inherits From","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","type":"inheritsFrom"},{"kind":"relationships","title":"Conforming Types","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessor-swift.class"],"type":"conformingTypes"}],"op":"replace","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageOptionsProcessor"},{"kind":"text","text":" <"},{"text":"NSObject","preciseIdentifier":"c:objc(pl)NSObject","kind":"typeIdentifier"},{"text":">","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessor-swift.class\/title","value":"SDWebImageOptionsProcessor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessor-swift.class\/fragments","value":[{"text":"SDWebImageOptionsProcessor","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDWebImageOptionsProcessor"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessor-swift.class\/navigatorTitle"},{"op":"replace","value":"SDWebImageOptionsProcessor","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol\/fragments","value":[{"text":"SDWebImageOptionsProcessor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol\/navigatorTitle","value":[{"text":"SDWebImageOptionsProcessor","kind":"identifier"}]},{"value":"processedResultForURL:options:context:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol~1processedResult(for:options:context:)\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol~1processedResult(for:options:context:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"processedResultForURL:options:context:"}]}]}]}