{"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerBlock","interfaceLanguage":"swift"},"metadata":{"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Alias","navigatorTitle":[{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}],"title":"SDWebImageCacheSerializerBlock","externalID":"c:SDWebImageCacheSerializer.h@T@SDWebImageCacheSerializerBlock","symbolKind":"typealias","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializerblock"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializerblock"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"typealias","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheSerializerBlock"},{"kind":"text","text":" = ("},{"text":"UIImage","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIImage"},{"text":", ","kind":"text"},{"text":"Data","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation4DataV"},{"text":"?, ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?) -> ","kind":"text"},{"text":"Data","preciseIdentifier":"s:10Foundation4DataV","kind":"typeIdentifier"},{"text":"?","kind":"text"}]}],"kind":"declarations"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializerBlock":{"title":"SDWebImageCacheSerializerBlock","role":"symbol","navigatorTitle":[{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}],"abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerBlock","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagecacheserializerblock"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Alias"},{"value":"SDWebImageCacheSerializerBlock","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"typealias","op":"replace"},{"value":[{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}],"path":"\/metadata\/navigatorTitle"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:BF*$objc(cs)NSData(#*$objc(cs)UIImage#S2_#*$objc(cs)NSURL)","text":"NSData *(^)(UIImage *, NSData *, NSURL *)","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerBlock\/title","value":"SDWebImageCacheSerializerBlock","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerBlock\/fragments","op":"replace","value":[{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerBlock\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageCacheSerializerBlock","kind":"identifier"}]}]}]}