{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/s25ExpressibleByArrayLiteralP","doc:\/\/com.dailymotion.SDWebImage\/s9OptionSetP","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP","doc:\/\/com.dailymotion.SDWebImage\/s10SetAlgebraP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"WebCache options"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"}],"title":"SDWebImageOptions","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@E@SDWebImageOptions","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/allowInvalidSSLCertificates","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidAutoSetImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidDecodeImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/continueInBackground","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/delayPlaceholder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/forceTransition","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromCacheOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromLoaderOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/handleCookies","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/highPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/lowPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/matchAnimatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/preloadAllFrames","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/progressiveLoad","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryDiskDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryMemoryData","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryMemoryDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/refreshCached","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/retryFailed","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/scaleDownLargeImages","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/transformAnimatedImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/transformVectorImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/waitStoreCache"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/OptionSet-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/SetAlgebra-Implementations"],"generated":true}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/transformAnimatedImage":{"role":"symbol","title":"transformAnimatedImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformAnimatedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"We usually don’t apply transform on animated images as most transformers could not manage animated images."},{"type":"text","text":" "},{"type":"text","text":"Use this flag to transform them anyway."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/transformAnimatedImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransformAnimatedImage"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/transformanimatedimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/retryFailed":{"role":"symbol","title":"retryFailed","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retryFailed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when a URL fail to be downloaded, the URL is blacklisted so the library won’t keep trying."},{"type":"text","text":" "},{"type":"text","text":"This flag disable this blacklisting."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/retryFailed","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageRetryFailed"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/retryfailed"},"doc://com.dailymotion.SDWebImage/s25ExpressibleByArrayLiteralP":{"type":"unresolvable","title":"Swift.ExpressibleByArrayLiteral","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s25ExpressibleByArrayLiteralP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/preloadAllFrames":{"role":"symbol","title":"preloadAllFrames","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"preloadAllFrames"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, for "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":", we decode the animated image frame during rendering to reduce memory usage. However, you can specify to preload all frames into memory to reduce CPU usage when the animated image is shared by lots of imageViews."},{"type":"text","text":" "},{"type":"text","text":"This will actually trigger "},{"type":"codeVoice","code":"preloadAllAnimatedImageFrames"},{"type":"text","text":" in the background queue(Disk Cache & Download only)."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/preloadAllFrames","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImagePreloadAllFrames"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/preloadallframes"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"role":"symbol","title":"SDWebImageOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"}],"abstract":[{"type":"text","text":"WebCache options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/queryMemoryDataSync":{"role":"symbol","title":"queryMemoryDataSync","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when you only specify "},{"type":"codeVoice","code":"SDWebImageQueryMemoryData"},{"type":"text","text":", we query the memory image data asynchronously. Combined this mask as well to query the memory image data synchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryMemoryDataSync","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageQueryMemoryDataSync"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/querymemorydatasync"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/allowInvalidSSLCertificates":{"role":"symbol","title":"allowInvalidSSLCertificates","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"allowInvalidSSLCertificates"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"Enable to allow untrusted SSL certificates."},{"type":"text","text":" "},{"type":"text","text":"Useful for testing purposes. Use with caution in production."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/allowInvalidSSLCertificates","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageAllowInvalidSSLCertificates"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/allowinvalidsslcertificates"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/decodeFirstFrameOnly":{"role":"symbol","title":"decodeFirstFrameOnly","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decodeFirstFrameOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, we decode the animated image. This flag can force decode the first frame only and produce the static image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/decodeFirstFrameOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDecodeFirstFrameOnly"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/decodefirstframeonly"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/transformVectorImage":{"role":"symbol","title":"transformVectorImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformVectorImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"We usually don’t apply transform on vector images, because vector images supports dynamically changing to any size, rasterize to a fixed size will loss details. To modify vector images, you can process the vector data at runtime (such as modifying PDF tag \/ SVG element)."},{"type":"text","text":" "},{"type":"text","text":"Use this flag to transform them anyway."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/transformVectorImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransformVectorImage"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/transformvectorimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/queryMemoryData":{"role":"symbol","title":"queryMemoryData","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryData"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, we do not query image data when the image is already cached in memory. This mask can force to query image data at the same time. However, this query is asynchronously unless you specify "},{"type":"codeVoice","code":"SDWebImageQueryMemoryDataSync"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryMemoryData","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageQueryMemoryData"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/querymemorydata"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/delayPlaceholder":{"role":"symbol","title":"delayPlaceholder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"delayPlaceholder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, placeholder images are loaded while the image is loading. This flag will delay the loading"},{"type":"text","text":" "},{"type":"text","text":"of the placeholder image until after the image has finished loading."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/delayPlaceholder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDelayPlaceholder"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/delayplaceholder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/highPriority":{"role":"symbol","title":"highPriority","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"highPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, images are loaded in the order in which they were queued. This flag moves them to"},{"type":"text","text":" "},{"type":"text","text":"the front of the queue."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/highPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageHighPriority"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/highpriority"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/progressiveLoad":{"role":"symbol","title":"progressiveLoad","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"progressiveLoad"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"This flag enables progressive download, the image is displayed progressively during download as a browser would do."},{"type":"text","text":" "},{"type":"text","text":"By default, the image is only displayed once completely downloaded."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/progressiveLoad","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageProgressiveLoad"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/progressiveload"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/continueInBackground":{"role":"symbol","title":"continueInBackground","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"continueInBackground"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"In iOS 4+, continue the download of the image if the app goes to background. This is achieved by asking the system for"},{"type":"text","text":" "},{"type":"text","text":"extra time in background to let the request finish. If the background task expires the operation will be cancelled."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/continueInBackground","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/continueinbackground"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/avoidDecodeImage":{"role":"symbol","title":"avoidDecodeImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidDecodeImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation."},{"type":"text","text":" "},{"type":"text","text":"However, this process may increase the memory usage as well. If you are experiencing a issue due to excessive memory consumption, This flag can prevent decode the image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidDecodeImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageAvoidDecodeImage"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/avoiddecodeimage"},"doc://com.dailymotion.SDWebImage/s9OptionSetP":{"type":"unresolvable","title":"Swift.OptionSet","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s9OptionSetP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/SetAlgebra-Implementations":{"role":"collectionGroup","title":"SetAlgebra Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/SetAlgebra-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/setalgebra-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/forceTransition":{"role":"symbol","title":"forceTransition","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"forceTransition"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageTransition"},{"type":"text","text":" to do some view transition after the image load finished, this transition is only applied for image when the callback from manager is asynchronous (from network, or disk cache query)"},{"type":"text","text":" "},{"type":"text","text":"This mask can force to apply view transition for any cases, like memory cache query, or sync disk cache query."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/forceTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageForceTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/forcetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/refreshCached":{"role":"symbol","title":"refreshCached","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"refreshCached"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"Even if the image is cached, respect the HTTP response cache control, and refresh the image from remote location if needed."},{"type":"text","text":" "},{"type":"text","text":"The disk caching will be handled by NSURLCache instead of SDWebImage leading to slight performance degradation."},{"type":"text","text":" "},{"type":"text","text":"This option helps deal with images changing behind the same request URL, e.g. Facebook graph api profile pics."},{"type":"text","text":" "},{"type":"text","text":"If a cached image is refreshed, the completion block is called once with the cached image and again with the final image."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/refreshCached","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageRefreshCached"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/refreshcached"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/fromLoaderOnly":{"role":"symbol","title":"fromLoaderOnly","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromLoaderOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, we query the cache before the image is load from the loader. This flag can prevent this to load from loader only."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromLoaderOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageFromLoaderOnly"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/fromloaderonly"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/matchAnimatedImageClass":{"role":"symbol","title":"matchAnimatedImageClass","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"matchAnimatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"type":"text","text":" context option (like using "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":"), we may still use "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" when the memory cache hit, or image decoder is not available to produce one exactlly matching your custom class as a fallback solution."},{"type":"text","text":" "},{"type":"text","text":"Using this option, can ensure we always callback image with your provided class. If failed to produce one, a error with code "},{"type":"codeVoice","code":"SDWebImageErrorBadImageData"},{"type":"text","text":" will been used."},{"type":"text","text":" "},{"type":"text","text":"Note this options is not compatible with "},{"type":"codeVoice","code":"SDWebImageDecodeFirstFrameOnly"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/matchAnimatedImageClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageMatchAnimatedImageClass"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/matchanimatedimageclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/fromCacheOnly":{"role":"symbol","title":"fromCacheOnly","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fromCacheOnly"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when the cache missed, the image is load from the loader. This flag can prevent this to load from cache only."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromCacheOnly","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageFromCacheOnly"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/fromcacheonly"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/waitStoreCache":{"role":"symbol","title":"waitStoreCache","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"waitStoreCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when we load the image from network, the image will be written to the cache (memory and disk, controlled by your "},{"type":"codeVoice","code":"storeCacheType"},{"type":"text","text":" context option)"},{"type":"text","text":" "},{"type":"text","text":"This maybe an asynchronously operation and the final "},{"type":"codeVoice","code":"SDInternalCompletionBlock"},{"type":"text","text":" callback does not guarantee the disk cache written is finished and may cause logic error. (For example, you modify the disk data just in completion block, however, the disk cache is not ready)"},{"type":"text","text":" "},{"type":"text","text":"If you need to process with the disk cache in the completion block, you should use this option to ensure the disk cache already been written when callback."},{"type":"text","text":" "},{"type":"text","text":"Note if you use this when using the custom cache serializer, or using the transformer, we will also wait until the output image data written is finished."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/waitStoreCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageWaitStoreCache"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/waitstorecache"},"doc://com.dailymotion.SDWebImage/s10SetAlgebraP":{"type":"unresolvable","title":"Swift.SetAlgebra","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s10SetAlgebraP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/OptionSet-Implementations":{"role":"collectionGroup","title":"OptionSet Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/OptionSet-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageoptions\/optionset-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/queryDiskDataSync":{"role":"symbol","title":"queryDiskDataSync","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryDiskDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, when the memory cache miss, we query the disk cache asynchronously. This mask can force to query disk cache (when memory cache miss) synchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryDiskDataSync","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageQueryDiskDataSync"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/querydiskdatasync"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/avoidAutoSetImage":{"role":"symbol","title":"avoidAutoSetImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidAutoSetImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, image is added to the imageView after download. But in some cases, we want to"},{"type":"text","text":" "},{"type":"text","text":"have the hand before setting the image (apply a filter or add it with cross-fade animation for instance)"},{"type":"text","text":" "},{"type":"text","text":"Use this flag if you want to manually set the image in the completion when success"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidAutoSetImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageAvoidAutoSetImage"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/avoidautosetimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/lowPriority":{"role":"symbol","title":"lowPriority","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"lowPriority"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, image downloads are started during UI interactions, this flags disable this feature,"},{"type":"text","text":" "},{"type":"text","text":"leading to delayed download on UIScrollView deceleration for instance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/lowPriority","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageLowPriority"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/lowpriority"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/handleCookies":{"role":"symbol","title":"handleCookies","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"handleCookies"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"Handles cookies stored in NSHTTPCookieStore by setting"},{"type":"text","text":" "},{"type":"text","text":"NSMutableURLRequest.HTTPShouldHandleCookies = YES;"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/handleCookies","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageHandleCookies"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/handlecookies"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions/scaleDownLargeImages":{"role":"symbol","title":"scaleDownLargeImages","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"scaleDownLargeImages"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"}],"abstract":[{"type":"text","text":"By default, images are decoded respecting their original size."},{"type":"text","text":" "},{"type":"text","text":"This flag will scale down the images to a size compatible with the constrained memory of devices."},{"type":"text","text":" "},{"type":"text","text":"To control the limit memory bytes, check "},{"type":"codeVoice","code":"SDImageCoderHelper.defaultScaleDownLimitBytes"},{"type":"text","text":" (Defaults to 60MB on iOS)"},{"type":"text","text":" "},{"type":"text","text":"This will actually translate to use context option "},{"type":"codeVoice","code":".imageThumbnailPixelSize"},{"type":"text","text":" from v5.5.0 (Defaults to (3966, 3966) on iOS). Previously does not."},{"type":"text","text":" "},{"type":"text","text":"This flags effect the progressive and animated images as well from v5.5.0. Previously does not."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/scaleDownLargeImages","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions\/scaledownlargeimages"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"enum"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Enumeration Cases","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/allowInvalidSSLCertificates","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidAutoSetImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/avoidDecodeImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/continueInBackground","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/decodeFirstFrameOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/delayPlaceholder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/forceTransition","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromCacheOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/fromLoaderOnly","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/handleCookies","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/highPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/lowPriority","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/matchAnimatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/preloadAllFrames","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/progressiveLoad","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryDiskDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryMemoryData","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/queryMemoryDataSync","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/refreshCached","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/retryFailed","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/scaleDownLargeImages","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/transformAnimatedImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/transformVectorImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions\/waitStoreCache"]}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1transformAnimatedImage\/title","value":"SDWebImageTransformAnimatedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1transformAnimatedImage\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransformAnimatedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1retryFailed\/title","value":"SDWebImageRetryFailed"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1retryFailed\/fragments","value":[{"kind":"identifier","text":"SDWebImageRetryFailed"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1preloadAllFrames\/title","value":"SDWebImagePreloadAllFrames"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1preloadAllFrames\/fragments","value":[{"kind":"identifier","text":"SDWebImagePreloadAllFrames"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1queryMemoryDataSync\/title","value":"SDWebImageQueryMemoryDataSync"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1queryMemoryDataSync\/fragments","value":[{"kind":"identifier","text":"SDWebImageQueryMemoryDataSync"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1allowInvalidSSLCertificates\/title","value":"SDWebImageAllowInvalidSSLCertificates"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1allowInvalidSSLCertificates\/fragments","value":[{"kind":"identifier","text":"SDWebImageAllowInvalidSSLCertificates"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1decodeFirstFrameOnly\/title","value":"SDWebImageDecodeFirstFrameOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1decodeFirstFrameOnly\/fragments","value":[{"kind":"identifier","text":"SDWebImageDecodeFirstFrameOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1transformVectorImage\/title","value":"SDWebImageTransformVectorImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1transformVectorImage\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransformVectorImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1queryMemoryData\/title","value":"SDWebImageQueryMemoryData"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1queryMemoryData\/fragments","value":[{"kind":"identifier","text":"SDWebImageQueryMemoryData"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1delayPlaceholder\/title","value":"SDWebImageDelayPlaceholder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1delayPlaceholder\/fragments","value":[{"kind":"identifier","text":"SDWebImageDelayPlaceholder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1highPriority\/title","value":"SDWebImageHighPriority"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1highPriority\/fragments","value":[{"kind":"identifier","text":"SDWebImageHighPriority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1progressiveLoad\/title","value":"SDWebImageProgressiveLoad"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1progressiveLoad\/fragments","value":[{"kind":"identifier","text":"SDWebImageProgressiveLoad"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1continueInBackground\/title","value":"SDWebImageContinueInBackground"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1continueInBackground\/fragments","value":[{"kind":"identifier","text":"SDWebImageContinueInBackground"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidDecodeImage\/title","value":"SDWebImageAvoidDecodeImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidDecodeImage\/fragments","value":[{"kind":"identifier","text":"SDWebImageAvoidDecodeImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1forceTransition\/title","value":"SDWebImageForceTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1forceTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageForceTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1refreshCached\/title","value":"SDWebImageRefreshCached"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1refreshCached\/fragments","value":[{"kind":"identifier","text":"SDWebImageRefreshCached"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1fromLoaderOnly\/title","value":"SDWebImageFromLoaderOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1fromLoaderOnly\/fragments","value":[{"kind":"identifier","text":"SDWebImageFromLoaderOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1matchAnimatedImageClass\/title","value":"SDWebImageMatchAnimatedImageClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1matchAnimatedImageClass\/fragments","value":[{"kind":"identifier","text":"SDWebImageMatchAnimatedImageClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1fromCacheOnly\/title","value":"SDWebImageFromCacheOnly"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1fromCacheOnly\/fragments","value":[{"kind":"identifier","text":"SDWebImageFromCacheOnly"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1waitStoreCache\/title","value":"SDWebImageWaitStoreCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1waitStoreCache\/fragments","value":[{"kind":"identifier","text":"SDWebImageWaitStoreCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1queryDiskDataSync\/title","value":"SDWebImageQueryDiskDataSync"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1queryDiskDataSync\/fragments","value":[{"kind":"identifier","text":"SDWebImageQueryDiskDataSync"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidAutoSetImage\/title","value":"SDWebImageAvoidAutoSetImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1avoidAutoSetImage\/fragments","value":[{"kind":"identifier","text":"SDWebImageAvoidAutoSetImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1lowPriority\/title","value":"SDWebImageLowPriority"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1lowPriority\/fragments","value":[{"kind":"identifier","text":"SDWebImageLowPriority"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1handleCookies\/title","value":"SDWebImageHandleCookies"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1handleCookies\/fragments","value":[{"kind":"identifier","text":"SDWebImageHandleCookies"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1scaleDownLargeImages\/title","value":"SDWebImageScaleDownLargeImages"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions~1scaleDownLargeImages\/fragments","value":[{"kind":"identifier","text":"SDWebImageScaleDownLargeImages"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}