{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A downloader response modifier class with block."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"title":"SDWebImageDownloaderDecryptor","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDWebImageDownloaderDecryptor","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/init(block:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/base64"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptorProtocol":{"role":"symbol","title":"SDWebImageDownloaderDecryptorProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptorProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for downloader decryptor. Which decrypt the original encrypted data before decoding. Note progressive decoding is not compatible for decryptor."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the downloader decryptor. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptorProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptorprotocol"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class":{"role":"symbol","title":"SDWebImageDownloaderDecryptor","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"abstract":[{"type":"text","text":"A downloader response modifier class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class/init(block:)":{"role":"symbol","title":"init(block:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderDecryptorBlock","preciseIdentifier":"c:SDWebImageDownloaderDecryptor.h@T@SDWebImageDownloaderDecryptorBlock"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the data decryptor with block"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/init(block:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/init(block:)"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class/decryptorWithBlock:":{"role":"symbol","title":"decryptorWithBlock:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"decryptorWithBlock:"}],"abstract":[{"type":"text","text":"Create the data decryptor with block"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/decryptorWithBlock:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decryptorWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/decryptorwithblock:"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderDecryptor-swift.class/base64":{"role":"symbol","title":"base64","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"base64"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderDecryptor","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderDecryptor"}],"abstract":[{"type":"text","text":"Base64 Encoded image data decryptor"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/base64","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"base64Decryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderdecryptor-swift.class\/base64"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderDecryptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/init(block:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/base64"]},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptor-swift.class\/decryptorWithBlock:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderDecryptorProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorProtocol\/title","value":"SDWebImageDownloaderDecryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptorProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/title","value":"SDWebImageDownloaderDecryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderDecryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1init(block:)\/title","value":"initWithBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1init(block:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1base64\/title","value":"base64Decryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderDecryptor-swift.class~1base64\/fragments","value":[{"kind":"identifier","text":"base64Decryptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}