{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A downloader response modifier class with block."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"title":"SDWebImageDownloaderResponseModifier","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDWebImageDownloaderResponseModifier","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(block:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(headers:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:version:headers:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(version:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(version:)":{"role":"symbol","title":"init(version:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Create the response modifier with HTTP Version. Status code defaults to 200."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(version:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithVersion:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(version:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(statusCode:version:headers:)":{"role":"symbol","title":"init(statusCode:version:headers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":", "},{"kind":"externalParam","text":"version"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Create the response modifier with HTTP Status Code, Version and Headers."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:version:headers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStatusCode:version:headers:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(statuscode:version:headers:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/responseModifierWithBlock:":{"role":"symbol","title":"responseModifierWithBlock:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"responseModifierWithBlock:"}],"abstract":[{"type":"text","text":"Create the response modifier with block"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/responseModifierWithBlock:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"responseModifierWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/responsemodifierwithblock:"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(headers:)":{"role":"symbol","title":"init(headers:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"headers"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"]?)"}],"abstract":[{"type":"text","text":"Create the response modifier with HTTP Headers. Status code defaults to 200."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(headers:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithHeaders:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(headers:)"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(block:)":{"role":"symbol","title":"init(block:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderResponseModifierBlock","preciseIdentifier":"c:SDWebImageDownloaderResponseModifier.h@T@SDWebImageDownloaderResponseModifierBlock"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the response modifier with block"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(block:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(block:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifierProtocol":{"role":"symbol","title":"SDWebImageDownloaderResponseModifierProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for downloader response modifier."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the downloader response modifier. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifierProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifierprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class/init(statusCode:)":{"role":"symbol","title":"init(statusCode:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"statusCode"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int","preciseIdentifier":"s:Si"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Create the response modifier with HTTP Status code."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithStatusCode:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class\/init(statuscode:)"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloaderResponseModifier-swift.class":{"role":"symbol","title":"SDWebImageDownloaderResponseModifier","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"abstract":[{"type":"text","text":"A downloader response modifier class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloaderresponsemodifier-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloaderResponseModifier"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(block:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(headers:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(statusCode:version:headers:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/init(version:)"]},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifier-swift.class\/responseModifierWithBlock:"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloaderResponseModifierProtocol"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(version:)\/title","value":"initWithVersion:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(version:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithVersion:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(statusCode:version:headers:)\/title","value":"initWithStatusCode:version:headers:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(statusCode:version:headers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatusCode:version:headers:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(headers:)\/title","value":"initWithHeaders:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(headers:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithHeaders:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(block:)\/title","value":"initWithBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(block:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/title","value":"SDWebImageDownloaderResponseModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifierProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(statusCode:)\/title","value":"initWithStatusCode:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class~1init(statusCode:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithStatusCode:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/title","value":"SDWebImageDownloaderResponseModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloaderResponseModifier-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloaderResponseModifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}