{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloader"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagedownloader"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Asynchronous downloader dedicated and optimized for image loading."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloader"}],"title":"SDWebImageDownloader","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDWebImageDownloader","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloader"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/init(config:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/config","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/currentDownloadCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/decryptor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/isSuspended","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/requestModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/responseModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/sessionConfiguration"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/cancelAllDownloads()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:options:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/invalidateSessionAndCancel(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/setValue(_:forHTTPHeaderField:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/value(forHTTPHeaderField:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/shared"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/init(config:)":{"role":"symbol","title":"init(config:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderConfig","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Creates an instance of a downloader with specified downloader config."},{"type":"text","text":" "},{"type":"text","text":"You can specify session configuration, timeout or operation class through downloader config."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/init(config:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithConfig:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/init(config:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"role":"symbol","title":"SDImageLoader","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoader"}],"abstract":[{"type":"text","text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself."},{"type":"text","text":" "},{"type":"text","text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call "},{"type":"codeVoice","code":"SDImageLoaderDecodeImageData"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDImageLoaderDecodeProgressiveImageData"},{"type":"text","text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block."},{"type":"text","text":" "},{"type":"text","text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"url":"\/documentation\/sdwebimage\/sdimageloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/config":{"role":"symbol","title":"config","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"config"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderConfig","preciseIdentifier":"c:objc(cs)SDWebImageDownloaderConfig"}],"abstract":[{"type":"text","text":"Downloader Config object - storing all kind of settings."},{"type":"text","text":" "},{"type":"text","text":"Most config properties support dynamic changes during download, except something like "},{"type":"codeVoice","code":"sessionConfiguration"},{"type":"text","text":", see "},{"type":"codeVoice","code":"SDWebImageDownloaderConfig"},{"type":"text","text":" for more detail."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/config","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"config"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/config"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/currentDownloadCount":{"role":"symbol","title":"currentDownloadCount","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"currentDownloadCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"}],"abstract":[{"type":"text","text":"Shows the current amount of downloads that still need to be downloaded"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/currentDownloadCount","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"currentDownloadCount"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/currentdownloadcount"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/isSuspended":{"role":"symbol","title":"isSuspended","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"isSuspended"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Gets\/Sets the download queue suspension state."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/isSuspended","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"suspended"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/issuspended"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/invalidateSessionAndCancel(_:)":{"role":"symbol","title":"invalidateSessionAndCancel(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"invalidateSessionAndCancel"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Invalidates the managed session, optionally canceling pending operations."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/invalidateSessionAndCancel(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"invalidateSessionAndCancel:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/invalidatesessionandcancel(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/sessionConfiguration":{"role":"symbol","title":"sessionConfiguration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"sessionConfiguration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URLSessionConfiguration","preciseIdentifier":"c:objc(cs)NSURLSessionConfiguration"}],"abstract":[{"type":"text","text":"The configuration in use by the internal NSURLSession. If you want to provide a custom sessionConfiguration, use "},{"type":"codeVoice","code":"SDWebImageDownloaderConfig.sessionConfiguration"},{"type":"text","text":" and create a new downloader instance."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/sessionConfiguration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sessionConfiguration"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/sessionconfiguration"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/downloadImage(with:options:context:progress:completed:)":{"role":"symbol","title":"downloadImage(with:options:context:progress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SDWebImageDownloadToken","preciseIdentifier":"c:objc(cs)SDWebImageDownloadToken"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a SDWebImageDownloader async downloader instance with a given URL"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:options:context:progress:completed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadImageWithURL:options:context:progress:completed:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/downloadimage(with:options:context:progress:completed:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/cancelAllDownloads()":{"role":"symbol","title":"cancelAllDownloads()","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cancelAllDownloads"},{"kind":"text","text":"()"}],"abstract":[{"type":"text","text":"Cancels all download operations in the queue"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/cancelAllDownloads()","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cancelAllDownloads"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/cancelalldownloads()"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/downloadImage(with:options:progress:completed:)":{"role":"symbol","title":"downloadImage(with:options:progress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderOptions","preciseIdentifier":"c:@E@SDWebImageDownloaderOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderProgressBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SDWebImageDownloadToken","preciseIdentifier":"c:objc(cs)SDWebImageDownloadToken"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a SDWebImageDownloader async downloader instance with a given URL"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:options:progress:completed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadImageWithURL:options:progress:completed:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/downloadimage(with:options:progress:completed:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/downloadImage(with:completed:)":{"role":"symbol","title":"downloadImage(with:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderCompletedBlock","preciseIdentifier":"c:SDWebImageDownloader.h@T@SDWebImageDownloaderCompletedBlock"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"SDWebImageDownloadToken","preciseIdentifier":"c:objc(cs)SDWebImageDownloadToken"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Creates a SDWebImageDownloader async downloader instance with a given URL"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:completed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"downloadImageWithURL:completed:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/downloadimage(with:completed:)"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/setValue(_:forHTTPHeaderField:)":{"role":"symbol","title":"setValue(_:forHTTPHeaderField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setValue"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forHTTPHeaderField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?)"}],"abstract":[{"type":"text","text":"Set a value for a HTTP header to be appended to each download HTTP request."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/setValue(_:forHTTPHeaderField:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"setValue:forHTTPHeaderField:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/setvalue(_:forhttpheaderfield:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader":{"role":"symbol","title":"SDWebImageDownloader","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloader"}],"abstract":[{"type":"text","text":"Asynchronous downloader dedicated and optimized for image loading."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageDownloader"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/decryptor":{"role":"symbol","title":"decryptor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"decryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderDecryptorProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderDecryptor"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the decryptor to decrypt the original download data before image decoding. This can be used for encrypted image data, like Base64."},{"type":"text","text":" "},{"type":"text","text":"This decryptor method will be called for each downloading image data. Return the original data means no modification. Return nil will mark this download failed."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download data."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/decryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"decryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/decryptor"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/shared":{"role":"symbol","title":"shared","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloader","preciseIdentifier":"c:objc(cs)SDWebImageDownloader"}],"abstract":[{"type":"text","text":"Returns the global shared downloader instance. Which use the "},{"type":"codeVoice","code":"SDWebImageDownloaderConfig.defaultDownloaderConfig"},{"type":"text","text":" config."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/shared","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"sharedDownloader"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/shared"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/value(forHTTPHeaderField:)":{"role":"symbol","title":"value(forHTTPHeaderField:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"value"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forHTTPHeaderField"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Returns the value of the specified HTTP header field."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/value(forHTTPHeaderField:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"valueForHTTPHeaderField:"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/value(forhttpheaderfield:)"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/responseModifier":{"role":"symbol","title":"responseModifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"responseModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderResponseModifierProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderResponseModifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the response modifier to modify the original download response during image load."},{"type":"text","text":" "},{"type":"text","text":"This response modifier method will be called for each downloading image response. Return the original response means no modification. Return nil will mark current download as cancelled."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download response."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/responseModifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"responseModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/responsemodifier"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageDownloader/requestModifier":{"role":"symbol","title":"requestModifier","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"requestModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageDownloaderRequestModifierProtocol","preciseIdentifier":"c:objc(pl)SDWebImageDownloaderRequestModifier"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Set the request modifier to modify the original download request before image load."},{"type":"text","text":" "},{"type":"text","text":"This request modifier method will be called for each downloading image request. Return the original request means no modification. Return nil will cancel the download request."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil, means does not modify the original download request."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/requestModifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"requestModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagedownloader\/requestmodifier"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageDownloader"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageDownloader"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/config","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/currentDownloadCount","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/decryptor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/isSuspended","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/requestModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/responseModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/sessionConfiguration"]},{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/cancelAllDownloads()","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:options:context:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/downloadImage(with:options:progress:completed:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/init(config:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/invalidateSessionAndCancel(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/setValue(_:forHTTPHeaderField:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/value(forHTTPHeaderField:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageDownloader\/shared"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageDownloader"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1init(config:)\/title","value":"initWithConfig:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1init(config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"kind":"identifier","text":"SDImageLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1config\/title","value":"config"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1config\/fragments","value":[{"kind":"identifier","text":"config"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1currentDownloadCount\/title","value":"currentDownloadCount"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1currentDownloadCount\/fragments","value":[{"kind":"identifier","text":"currentDownloadCount"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1isSuspended\/title","value":"suspended"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1isSuspended\/fragments","value":[{"kind":"identifier","text":"suspended"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1invalidateSessionAndCancel(_:)\/title","value":"invalidateSessionAndCancel:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1invalidateSessionAndCancel(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"invalidateSessionAndCancel:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1sessionConfiguration\/title","value":"sessionConfiguration"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1sessionConfiguration\/fragments","value":[{"kind":"identifier","text":"sessionConfiguration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1downloadImage(with:options:context:progress:completed:)\/title","value":"downloadImageWithURL:options:context:progress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1downloadImage(with:options:context:progress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"downloadImageWithURL:options:context:progress:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1cancelAllDownloads()\/title","value":"cancelAllDownloads"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1cancelAllDownloads()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cancelAllDownloads"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1downloadImage(with:options:progress:completed:)\/title","value":"downloadImageWithURL:options:progress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1downloadImage(with:options:progress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"downloadImageWithURL:options:progress:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1downloadImage(with:completed:)\/title","value":"downloadImageWithURL:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1downloadImage(with:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"downloadImageWithURL:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1setValue(_:forHTTPHeaderField:)\/title","value":"setValue:forHTTPHeaderField:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1setValue(_:forHTTPHeaderField:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setValue:forHTTPHeaderField:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/title","value":"SDWebImageDownloader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader\/fragments","value":[{"kind":"identifier","text":"SDWebImageDownloader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1decryptor\/title","value":"decryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1decryptor\/fragments","value":[{"kind":"identifier","text":"decryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1shared\/title","value":"sharedDownloader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1shared\/fragments","value":[{"kind":"identifier","text":"sharedDownloader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1value(forHTTPHeaderField:)\/title","value":"valueForHTTPHeaderField:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1value(forHTTPHeaderField:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"valueForHTTPHeaderField:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1responseModifier\/title","value":"responseModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1responseModifier\/fragments","value":[{"kind":"identifier","text":"responseModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1requestModifier\/title","value":"requestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageDownloader~1requestModifier\/fragments","value":[{"kind":"identifier","text":"requestModifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}