{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObjectProtocol","preciseIdentifier":"c:objc(pl)NSObject"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilterprotocol"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecachekeyfilterprotocol"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This is the protocol for cache key filter."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the cache key filter. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"}],"title":"SDWebImageCacheKeyFilterProtocol","roleHeading":"Protocol","role":"symbol","symbolKind":"protocol","externalID":"c:objc(pl)SDWebImageCacheKeyFilter","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol\/cacheKey(for:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilter-swift.class":{"role":"symbol","title":"SDWebImageCacheKeyFilter","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}],"abstract":[{"type":"text","text":"A cache key filter class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}],"url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilter-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilterProtocol/cacheKey(for:)":{"navigatorTitle":[{"kind":"identifier","text":"cacheKeyForURL:"}],"role":"symbol","title":"cacheKey(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheKey"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"?"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol\/cacheKey(for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilterprotocol\/cachekey(for:)"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilterProtocol":{"role":"symbol","title":"SDWebImageCacheKeyFilterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for cache key filter."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the cache key filter. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilterprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Protocol"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageCacheKeyFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"protocol"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol\/cacheKey(for:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilter-swift.class"],"kind":"relationships","title":"Conforming Types","type":"conformingTypes"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilter"},{"kind":"text","text":"<"},{"kind":"keyword","text":"NSObject"},{"kind":"text","text":">"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/title","value":"SDWebImageCacheKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilter-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol~1cacheKey(for:)\/title","value":"cacheKeyForURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol~1cacheKey(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"cacheKeyForURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/title","value":"SDWebImageCacheKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}