{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH","doc:\/\/com.dailymotion.SDWebImage\/SY","doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/init(_:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/init(rawValue:)"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/animatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/cacheKeyFilter","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/cacheSerializer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/customManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadDecryptor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadRequestModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadResponseModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageLoader","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imagePreserveAspectRatio","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageScaleFactor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageThumbnailPixelSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTypeIdentifierHint","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/loaderCachedImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalImageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalQueryCacheType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalStoreCacheType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/queryCacheType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/setImageOperationKey","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/storeCacheType"]},{"title":"Default Implementations","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/Equatable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/RawRepresentable-Implementations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/_SwiftNewtypeWrapper-Implementations"],"generated":true}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"title":"SDWebImageContextOption","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:SDWebImageDefine.h@T@SDWebImageContextOption","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/downloadRequestModifier":{"role":"symbol","title":"downloadRequestModifier","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadRequestModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to modify the image download request. It’s used for downloader to modify the original request from URL and options. If you provide one, it will ignore the "},{"type":"codeVoice","code":"requestModifier"},{"type":"text","text":" in downloader and use provided one instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadRequestModifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextDownloadRequestModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/downloadrequestmodifier"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/customManager":{"deprecated":true,"role":"symbol","title":"customManager","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"customManager"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A SDWebImageManager instance to control the image download and cache process using in UIImageView+WebCache category and likes. If not provided, use the shared manager (SDWebImageManager *)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/customManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextCustomManager"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/custommanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/_SwiftNewtypeWrapper-Implementations":{"role":"collectionGroup","title":"_SwiftNewtypeWrapper Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/_SwiftNewtypeWrapper-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/_swiftnewtypewrapper-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/originalStoreCacheType":{"role":"symbol","title":"originalStoreCacheType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalStoreCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"The same behavior like "},{"type":"codeVoice","code":"SDWebImageContextStoreCacheType"},{"type":"text","text":", but control the store cache type for the original image when you use image transformer feature. This allows the detail control of cache storage for these two images. For example, if you want to store the transformed image into both memory\/disk cache, store the original image into disk cache only, use "},{"type":"codeVoice","code":"[.storeCacheType : .all, .originalStoreCacheType : .disk]"},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":", which store the original full image data into disk cache after storing the transformed image. This is suitable for most common cases to avoid re-downloading the full data for different transform variants. (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalStoreCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOriginalStoreCacheType"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/originalstorecachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/setImageOperationKey":{"role":"symbol","title":"setImageOperationKey","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"setImageOperationKey"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A String to be used as the operation key for view category to store the image load operation. This is used for view instance which supports different image loading process. If nil, will use the class name as operation key. (NSString *)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/setImageOperationKey","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextSetImageOperationKey"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/setimageoperationkey"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/queryCacheType":{"role":"symbol","title":"queryCacheType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A SDImageCacheType raw value which specify the source of cache to query. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":" to query from disk cache only; "},{"type":"codeVoice","code":"SDImageCacheTypeMemory"},{"type":"text","text":" to query from memory only. And "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":" to query from both memory cache and disk cache. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeNone"},{"type":"text","text":" is invalid and totally ignore the cache query."},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":". (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/queryCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/querycachetype"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/RawRepresentable-Implementations":{"role":"collectionGroup","title":"RawRepresentable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/RawRepresentable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/rawrepresentable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/cacheSerializer":{"role":"symbol","title":"cacheSerializer","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheSerializer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to convert the decoded image, the source downloaded data, to the actual data. It’s used for manager to store image to the disk cache. If you provide one, it will ignore the "},{"type":"codeVoice","code":"cacheSerializer"},{"type":"text","text":" in manager and use provided one instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/cacheSerializer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextCacheSerializer"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/cacheserializer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/originalImageCache":{"role":"symbol","title":"originalImageCache","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalImageCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms to "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" protocol. It’s used to control the cache for original image when using the transformer. If you provide one, the original image (full size image) will query and write from that cache instance instead, the transformed image will query and write from the default "},{"type":"codeVoice","code":"SDWebImageContextImageCache"},{"type":"text","text":" instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalImageCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOriginalImageCache"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/originalimagecache"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/loaderCachedImage":{"role":"symbol","title":"loaderCachedImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"loaderCachedImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A "},{"type":"codeVoice","code":"UIImage"},{"type":"text","text":" instance from "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":" when you specify "},{"type":"codeVoice","code":"SDWebImageRefreshCached"},{"type":"text","text":" and image cache hit."},{"type":"text","text":" "},{"type":"text","text":"This can be a hint for image loader to load the image from network and refresh the image from remote location if needed. If the image from remote location does not change, you should call the completion with "},{"type":"codeVoice","code":"SDWebImageErrorCacheNotModified"},{"type":"text","text":" error. (UIImage)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/loaderCachedImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextLoaderCachedImage"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/loadercachedimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageScaleFactor":{"role":"symbol","title":"imageScaleFactor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageScaleFactor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A CGFloat raw value which specify the image scale factor. The number should be greater than or equal to 1.0. If not provide or the number is invalid, we will use the cache key to specify the scale factor. (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageScaleFactor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageScaleFactor"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagescalefactor"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/downloadResponseModifier":{"role":"symbol","title":"downloadResponseModifier","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadResponseModifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to modify the image download response. It’s used for downloader to modify the original response from URL and options.  If you provide one, it will ignore the "},{"type":"codeVoice","code":"responseModifier"},{"type":"text","text":" in downloader and use provided one instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadResponseModifier","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextDownloadResponseModifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/downloadresponsemodifier"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageCoder":{"role":"symbol","title":"imageCoder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms to "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" protocol. It’s used to override the default image coder for image decoding(including progressive) and encoding during the image loading process."},{"type":"text","text":" "},{"type":"text","text":"If you use this context option, we will not always use "},{"type":"codeVoice","code":"SDImageCodersManager.shared"},{"type":"text","text":" to loop through all registered coders and find the suitable one. Instead, we will arbitrarily use the exact provided coder without extra checking (We may not call "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageCoder"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageDecodeOptions":{"role":"symbol","title":"imageDecodeOptions","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageDecodeOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A Dictionary (SDImageCoderOptions) value, which pass the extra decoding options to the SDImageCoder. Introduced in SDWebImage 5.14.0"},{"type":"text","text":" "},{"type":"text","text":"You can pass additional decoding related options to the decoder, extensible and control by you. And pay attention this dictionary may be retained by decoded image via "},{"type":"codeVoice","code":"UIImage.sd_decodeOptions"},{"type":"text","text":""},{"type":"text","text":" "},{"type":"text","text":"This context option replace the deprecated "},{"type":"codeVoice","code":"SDImageCoderWebImageContext"},{"type":"text","text":", which may cause retain cycle (cache -> image -> options -> context -> cache)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageDecodeOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodeoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imagePreserveAspectRatio":{"role":"symbol","title":"imagePreserveAspectRatio","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imagePreserveAspectRatio"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A Boolean value indicating whether to keep the original aspect ratio when generating thumbnail images (or bitmap images from vector format)."},{"type":"text","text":" "},{"type":"text","text":"Defaults to YES. (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imagePreserveAspectRatio","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImagePreserveAspectRatio"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagepreserveaspectratio"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/animatedImageClass":{"role":"symbol","title":"animatedImageClass","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A Class object which the instance is a "},{"type":"codeVoice","code":"UIImage\/NSImage"},{"type":"text","text":" subclass and adopt "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol. We will call "},{"type":"codeVoice","code":"initWithData:scale:options:"},{"type":"text","text":" to create the instance (or "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" when using progressive download) . If the instance create failed, fallback to normal "},{"type":"codeVoice","code":"UIImage\/NSImage"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This can be used to improve animated images rendering performance (especially memory usage on big animated images) with "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" (Class)."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/animatedImageClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/animatedimageclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/originalQueryCacheType":{"role":"symbol","title":"originalQueryCacheType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"originalQueryCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"The same behavior like "},{"type":"codeVoice","code":"SDWebImageContextQueryCacheType"},{"type":"text","text":", but control the query cache type for the original image when you use image transformer feature. This allows the detail control of cache query for these two images. For example, if you want to query the transformed image from both memory\/disk cache, query the original image from disk cache only, use "},{"type":"codeVoice","code":"[.queryCacheType : .all, .originalQueryCacheType : .disk]"},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":", which query the original full image data from disk cache after transformed image cache miss. This is suitable for most common cases to avoid re-downloading the full data for different transform variants. (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalQueryCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOriginalQueryCacheType"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/originalquerycachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageTransformer":{"role":"symbol","title":"imageTransformer","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTransformer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms "},{"type":"codeVoice","code":"SDImageTransformer"},{"type":"text","text":" protocol. It’s used for image transform after the image load finished and store the transformed image to cache. If you provide one, it will ignore the "},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" in manager and use provided one instead. If you pass NSNull, the transformer feature will be disabled. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTransformer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageTransformer"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetransformer"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageCache":{"role":"symbol","title":"imageCache","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms to "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" protocol. It’s used to override the image manager’s cache during the image loading pipeline."},{"type":"text","text":" "},{"type":"text","text":"In other word, if you just want to specify a custom cache during image loading, you don’t need to re-create a dummy SDWebImageManager instance with the cache. If not provided, use the image manager’s cache (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageCache"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagecache"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/Equatable-Implementations":{"role":"collectionGroup","title":"Equatable Implementations","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/Equatable-Implementations","kind":"article","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/equatable-implementations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/storeCacheType":{"role":"symbol","title":"storeCacheType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"storeCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A SDImageCacheType raw value which specify the store cache type when the image has just been downloaded and will be stored to the cache. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeNone"},{"type":"text","text":" to disable cache storage; "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":" to store in disk cache only; "},{"type":"codeVoice","code":"SDImageCacheTypeMemory"},{"type":"text","text":" to store in memory only. And "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":" to store in both memory cache and disk cache."},{"type":"text","text":" "},{"type":"text","text":"If you use image transformer feature, this actually apply for the transformed image, but not the original image itself. Use "},{"type":"codeVoice","code":"SDWebImageContextOriginalStoreCacheType"},{"type":"text","text":" if you want to control the original image’s store cache type at the same time."},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":". (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/storeCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextStoreCacheType"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/storecachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageLoader":{"role":"symbol","title":"imageLoader","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageLoader"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms to "},{"type":"codeVoice","code":"SDImageLoader"},{"type":"text","text":" protocol. It’s used to override the image manager’s loader during the image loading pipeline."},{"type":"text","text":" "},{"type":"text","text":"In other word, if you just want to specify a custom loader during image loading, you don’t need to re-create a dummy SDWebImageManager instance with the loader. If not provided, use the image manager’s cache (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageLoader"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imageloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/init(rawValue:)":{"role":"symbol","title":"init(rawValue:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"rawValue"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/init(rawValue:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/init(rawvalue:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageThumbnailPixelSize":{"role":"symbol","title":"imageThumbnailPixelSize","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageThumbnailPixelSize"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A CGSize raw value indicating whether or not to generate the thumbnail images (or bitmap images from vector format). When this value is provided, the decoder will generate a thumbnail image which pixel size is smaller than or equal to (depends the "},{"type":"codeVoice","code":".imagePreserveAspectRatio"},{"type":"text","text":") the value size."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageThumbnailPixelSize","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageThumbnailPixelSize"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagethumbnailpixelsize"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageTypeIdentifierHint":{"role":"symbol","title":"imageTypeIdentifierHint","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTypeIdentifierHint"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A NSString value (UTI) indicating the source image’s file extension. Example: “public.jpeg-2000”, “com.nikon.raw-image”, “public.tiff”"},{"type":"text","text":" "},{"type":"text","text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF"},{"type":"text","text":" "},{"type":"text","text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTypeIdentifierHint","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageTypeIdentifierHint"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetypeidentifierhint"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/cacheKeyFilter":{"role":"symbol","title":"cacheKeyFilter","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to convert an URL into a cache key. It’s used when manager need cache key to use image cache. If you provide one, it will ignore the "},{"type":"codeVoice","code":"cacheKeyFilter"},{"type":"text","text":" in manager and use provided one instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/cacheKeyFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextCacheKeyFilter"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/cachekeyfilter"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/downloadDecryptor":{"role":"symbol","title":"downloadDecryptor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadDecryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to decrypt the image download data. This can be used for image data decryption, such as Base64 encoded image. If you provide one, it will ignore the "},{"type":"codeVoice","code":"decryptor"},{"type":"text","text":" in downloader and use provided one instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadDecryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/downloaddecryptor"},"doc://com.dailymotion.SDWebImage/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s8SendableP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/init(_:)":{"role":"symbol","title":"init(_:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/init(_:)","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/init(_:)"},"doc://com.dailymotion.SDWebImage/SY":{"type":"unresolvable","title":"Swift.RawRepresentable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SY"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Alias"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/metadata\/symbolKind","value":"typealias"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Variables","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/animatedImageClass","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/cacheKeyFilter","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/cacheSerializer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/customManager","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadDecryptor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadRequestModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadResponseModifier","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCoder","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageLoader","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imagePreserveAspectRatio","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageScaleFactor","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageThumbnailPixelSize","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTransformer","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTypeIdentifierHint","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/loaderCachedImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalImageCache","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalQueryCacheType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalStoreCacheType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/queryCacheType","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/setImageOperationKey","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/storeCacheType"]}]},{"op":"replace","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"typedef"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"identifier","text":"SDWebImageContextOption"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadRequestModifier\/title","value":"SDWebImageContextDownloadRequestModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadRequestModifier\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextDownloadRequestModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1customManager\/title","value":"SDWebImageContextCustomManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1customManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextCustomManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalStoreCacheType\/title","value":"SDWebImageContextOriginalStoreCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalStoreCacheType\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOriginalStoreCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1setImageOperationKey\/title","value":"SDWebImageContextSetImageOperationKey"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1setImageOperationKey\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextSetImageOperationKey"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1queryCacheType\/title","value":"SDWebImageContextQueryCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1queryCacheType\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1cacheSerializer\/title","value":"SDWebImageContextCacheSerializer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1cacheSerializer\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextCacheSerializer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalImageCache\/title","value":"SDWebImageContextOriginalImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalImageCache\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOriginalImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1loaderCachedImage\/title","value":"SDWebImageContextLoaderCachedImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1loaderCachedImage\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextLoaderCachedImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageScaleFactor\/title","value":"SDWebImageContextImageScaleFactor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageScaleFactor\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageScaleFactor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadResponseModifier\/title","value":"SDWebImageContextDownloadResponseModifier"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadResponseModifier\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextDownloadResponseModifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageCoder\/title","value":"SDWebImageContextImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageCoder\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageCoder"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageDecodeOptions\/title","value":"SDWebImageContextImageDecodeOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageDecodeOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageDecodeOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imagePreserveAspectRatio\/title","value":"SDWebImageContextImagePreserveAspectRatio"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imagePreserveAspectRatio\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImagePreserveAspectRatio"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1animatedImageClass\/title","value":"SDWebImageContextAnimatedImageClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1animatedImageClass\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalQueryCacheType\/title","value":"SDWebImageContextOriginalQueryCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalQueryCacheType\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOriginalQueryCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTransformer\/title","value":"SDWebImageContextImageTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTransformer\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageTransformer"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageCache\/title","value":"SDWebImageContextImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageCache\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1storeCacheType\/title","value":"SDWebImageContextStoreCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1storeCacheType\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextStoreCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageLoader\/title","value":"SDWebImageContextImageLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageLoader\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageThumbnailPixelSize\/title","value":"SDWebImageContextImageThumbnailPixelSize"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageThumbnailPixelSize\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageThumbnailPixelSize"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTypeIdentifierHint\/title","value":"SDWebImageContextImageTypeIdentifierHint"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTypeIdentifierHint\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageTypeIdentifierHint"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1cacheKeyFilter\/title","value":"SDWebImageContextCacheKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1cacheKeyFilter\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextCacheKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadDecryptor\/title","value":"SDWebImageContextDownloadDecryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadDecryptor\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}