{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition"],"traits":[{"interfaceLanguage":"occ"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"},{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject","doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP","doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP","doc:\/\/com.dailymotion.SDWebImage\/SQ","doc:\/\/com.dailymotion.SDWebImage\/SH"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"title":"SDWebImageTransition","roleHeading":"Class","role":"symbol","symbolKind":"class","externalID":"c:objc(cs)SDWebImageTransition","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"]]},"topicSections":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animationOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/avoidAutoSetImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/completion","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/duration","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/prepares"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlUp","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromTop"]},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlUp(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromTop(duration:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"role":"symbol","title":"SDWebImageTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/curlUp":{"role":"symbol","title":"curlUp","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlUp"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Curl up transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlUp","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"curlUpTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/curlup"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/completion":{"role":"symbol","title":"completion","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"completion"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransitionCompletionBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionCompletionBlock"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A block object to be executed when the animation sequence ends."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/completion","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"completion"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/completion"},"doc://com.dailymotion.SDWebImage/s28CustomDebugStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomDebugStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s28CustomDebugStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromRight(duration:)":{"role":"symbol","title":"flipFromRight(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromRight"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Flip from right transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromRightTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromright(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/SQ":{"type":"unresolvable","title":"Swift.Equatable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SQ"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromBottom(duration:)":{"role":"symbol","title":"flipFromBottom(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromBottom"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Flip from bottom transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromBottomTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom(duration:)"},"doc://com.dailymotion.SDWebImage/SH":{"type":"unresolvable","title":"Swift.Hashable","identifier":"doc:\/\/com.dailymotion.SDWebImage\/SH"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/animationOptions":{"role":"symbol","title":"animationOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageAnimationOptions","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageAnimationOptions"}],"abstract":[{"type":"text","text":"A mask of options indicating how you want to perform the animations."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/animationoptions"},"doc://com.dailymotion.SDWebImage/s23CustomStringConvertibleP":{"type":"unresolvable","title":"Swift.CustomStringConvertible","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s23CustomStringConvertibleP"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromLeft(duration:)":{"role":"symbol","title":"flipFromLeft(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromLeft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Flip from left  transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromleft(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/prepares":{"role":"symbol","title":"prepares","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepares"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransitionPreparesBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionPreparesBlock"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A block object to be executed before the animation sequence starts."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/prepares","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepares"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/prepares"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/fade":{"role":"symbol","title":"fade","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"fade"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Fade-in transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fadeTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/fade"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/curlDown(duration:)":{"role":"symbol","title":"curlDown(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlDown"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Curl down transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"curlDownTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/curldown(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromBottom":{"role":"symbol","title":"flipFromBottom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Flip from bottom transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromBottomTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromTop(duration:)":{"role":"symbol","title":"flipFromTop(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromTop"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Flip from top transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromTop(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromTopTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromtop(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromLeft":{"role":"symbol","title":"flipFromLeft","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromLeft"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Flip from left transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromLeftTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromleft"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/curlUp(duration:)":{"role":"symbol","title":"curlUp(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlUp"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Curl up transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlUp(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"curlUpTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/curlup(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/avoidAutoSetImage":{"role":"symbol","title":"avoidAutoSetImage","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidAutoSetImage"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"By default, we set the image to the view at the beginning of the animations. You can disable this and provide custom set image process"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/avoidAutoSetImage","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"avoidAutoSetImage"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/avoidautosetimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/animations":{"role":"symbol","title":"animations","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animations"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransitionAnimationsBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionAnimationsBlock"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A block object that contains the changes you want to make to the specified view."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animations","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animations"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/animations"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromTop":{"role":"symbol","title":"flipFromTop","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromTop"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Flip from top transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromTop","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromTopTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromtop"},"doc://com.dailymotion.SDWebImage/s7CVarArgP":{"type":"unresolvable","title":"Swift.CVarArg","identifier":"doc:\/\/com.dailymotion.SDWebImage\/s7CVarArgP"},"doc://com.dailymotion.SDWebImage/objc(cs)NSObject":{"type":"unresolvable","title":"NSObject","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/duration":{"role":"symbol","title":"duration","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"}],"abstract":[{"type":"text","text":"The duration of the transition animation, measured in seconds. Defaults to 0.5."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/duration","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"duration"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/duration"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/curlDown":{"role":"symbol","title":"curlDown","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlDown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Curl down transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"curlDownTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/curldown"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/fade(duration:)":{"role":"symbol","title":"fade(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fade"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Fade-in transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"fadeTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/fade(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromRight":{"role":"symbol","title":"flipFromRight","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromRight"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Flip from right transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromRightTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromright"},"doc://com.dailymotion.SDWebImage/objc(pl)NSObject":{"type":"unresolvable","title":"ObjectiveC.NSObjectProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/objc(pl)NSObject"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Class"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/metadata\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animationOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animations","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/avoidAutoSetImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/completion","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/duration","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/prepares"]},{"title":"Type Properties","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlUp","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromTop"]},{"title":"Type Methods","identifiers":["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlUp(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight(duration:)","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromTop(duration:)"]}]},{"op":"replace","path":"\/relationshipsSections","value":[{"identifiers":["doc:\/\/com.dailymotion.SDWebImage\/objc(cs)NSObject"],"kind":"relationships","title":"Inherits From","type":"inheritsFrom"}]},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@interface"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"},{"kind":"text","text":" : "},{"kind":"typeIdentifier","text":"NSObject","preciseIdentifier":"c:objc(cs)NSObject"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlUp\/title","value":"curlUpTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlUp\/fragments","value":[{"kind":"identifier","text":"curlUpTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1completion\/title","value":"completion"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1completion\/fragments","value":[{"kind":"identifier","text":"completion"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromRight(duration:)\/title","value":"flipFromRightTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromRight(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromRightTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom(duration:)\/title","value":"flipFromBottomTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromBottomTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animationOptions\/title","value":"animationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animationOptions\/fragments","value":[{"kind":"identifier","text":"animationOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromLeft(duration:)\/title","value":"flipFromLeftTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromLeft(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1prepares\/title","value":"prepares"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1prepares\/fragments","value":[{"kind":"identifier","text":"prepares"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1fade\/title","value":"fadeTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1fade\/fragments","value":[{"kind":"identifier","text":"fadeTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlDown(duration:)\/title","value":"curlDownTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlDown(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"curlDownTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom\/title","value":"flipFromBottomTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom\/fragments","value":[{"kind":"identifier","text":"flipFromBottomTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromTop(duration:)\/title","value":"flipFromTopTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromTop(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromTopTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromLeft\/title","value":"flipFromLeftTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromLeft\/fragments","value":[{"kind":"identifier","text":"flipFromLeftTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlUp(duration:)\/title","value":"curlUpTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlUp(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"curlUpTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1avoidAutoSetImage\/title","value":"avoidAutoSetImage"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1avoidAutoSetImage\/fragments","value":[{"kind":"identifier","text":"avoidAutoSetImage"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animations\/title","value":"animations"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animations\/fragments","value":[{"kind":"identifier","text":"animations"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromTop\/title","value":"flipFromTopTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromTop\/fragments","value":[{"kind":"identifier","text":"flipFromTopTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1duration\/title","value":"duration"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1duration\/fragments","value":[{"kind":"identifier","text":"duration"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlDown\/title","value":"curlDownTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlDown\/fragments","value":[{"kind":"identifier","text":"curlDownTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1fade(duration:)\/title","value":"fadeTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1fade(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"fadeTransitionWithDuration:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromRight\/title","value":"flipFromRightTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromRight\/fragments","value":[{"kind":"identifier","text":"flipFromRightTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}