{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"animations"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionAnimationsBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionAnimationsBlock","text":"SDWebImageTransitionAnimationsBlock","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}]}],"abstract":[{"text":"A block object that contains the changes you want to make to the specified view.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/animations"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/animations"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animations","interfaceLanguage":"swift"},"metadata":{"externalID":"c:objc(cs)SDWebImageTransition(py)animations","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","modules":[{"name":"SDWebImage"}],"title":"animations","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animations","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransitionAnimationsBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionAnimationsBlock"},{"text":"?","kind":"text"}],"navigatorTitle":[{"text":"animations","kind":"identifier"}]},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/animations":{"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/animations","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"animations","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageTransitionAnimationsBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionAnimationsBlock","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"animations","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animations","abstract":[{"type":"text","text":"A block object that contains the changes you want to make to the specified view."}],"type":"topic","navigatorTitle":[{"text":"animations","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagetransition","title":"SDWebImageTransition","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"code":"sd_imageTransition","type":"codeVoice"},{"text":" in UIView+WebCache.h","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"code":"+[UIView transitionWithView:duration:options:animations:completion]","type":"codeVoice"},{"type":"text","text":" for transition animation."},{"text":" ","type":"text"},{"text":"for AppKit(macOS), we use ","type":"text"},{"code":"+[NSAnimationContext runAnimationGroup:completionHandler:]","type":"codeVoice"},{"text":" for transition animation. You can call ","type":"text"},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"text":" to grab the context during animations block.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SDWebImageTransition","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransitionAnimationsBlock":{"kind":"symbol","type":"topic","title":"SDWebImageTransitionAnimationsBlock","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransitionAnimationsBlock"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionAnimationsBlock","url":"\/documentation\/sdwebimage\/sdwebimagetransitionanimationsblock","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageTransitionAnimationsBlock"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"animations","op":"replace"},{"op":"replace","value":"property","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"animations","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"text":") ","kind":"text"},{"preciseIdentifier":"c:BFv(#*Q$objc(cs)UIView#*$objc(cs)UIImage)","text":"void (^)(__kindof UIView *, UIImage *)","kind":"typeIdentifier"},{"kind":"text","text":" "},{"kind":"identifier","text":"animations"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animations\/title","op":"replace","value":"animations"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animations\/fragments","value":[{"text":"animations","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","op":"replace","value":"SDWebImageTransition"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/navigatorTitle","value":[{"text":"SDWebImageTransition","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionAnimationsBlock\/title","value":"SDWebImageTransitionAnimationsBlock"},{"value":[{"kind":"identifier","text":"SDWebImageTransitionAnimationsBlock"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionAnimationsBlock\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionAnimationsBlock\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageTransitionAnimationsBlock","kind":"identifier"}]}]}]}