{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageAnimationOptions","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageAnimationOptions","text":"SDWebImageAnimationOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/animationoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/animationoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animationOptions","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A mask of options indicating how you want to perform the animations."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageAnimationOptions","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageAnimationOptions"}],"title":"animationOptions","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageTransition(py)animationOptions","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"animationOptions"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"role":"symbol","title":"SDWebImageTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/animationOptions":{"role":"symbol","title":"animationOptions","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationOptions"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageAnimationOptions","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageAnimationOptions"}],"abstract":[{"type":"text","text":"A mask of options indicating how you want to perform the animations."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/animationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"animationOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/animationoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageAnimationOptions":{"role":"symbol","title":"SDWebImageAnimationOptions","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageAnimationOptions"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageAnimationOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageAnimationOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimageanimationoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"animationOptions"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"animationOptions"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageAnimationOptions","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageAnimationOptions","text":"SDWebImageAnimationOptions"},{"kind":"text","text":" "},{"kind":"identifier","text":"animationOptions"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animationOptions\/title","value":"animationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1animationOptions\/fragments","value":[{"kind":"identifier","text":"animationOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageAnimationOptions\/title","value":"SDWebImageAnimationOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageAnimationOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageAnimationOptions"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}