{"abstract":[{"text":"A block object to be executed when the animation sequence ends.","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/completion"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/completion"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/completion","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageTransitionCompletionBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionCompletionBlock","kind":"typeIdentifier"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"sections":[],"metadata":{"title":"completion","symbolKind":"property","role":"symbol","roleHeading":"Instance Property","externalID":"c:objc(cs)SDWebImageTransition(py)completion","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completion","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionCompletionBlock","text":"SDWebImageTransitionCompletionBlock","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"completion","kind":"identifier"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/completion":{"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/completion","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"completion","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageTransitionCompletionBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionCompletionBlock","kind":"typeIdentifier"},{"text":"?","kind":"text"}],"title":"completion","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/completion","abstract":[{"text":"A block object to be executed when the animation sequence ends.","type":"text"}],"type":"topic","navigatorTitle":[{"text":"completion","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransitionCompletionBlock":{"url":"\/documentation\/sdwebimage\/sdwebimagetransitioncompletionblock","kind":"symbol","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"text":"SDWebImageTransitionCompletionBlock","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionCompletionBlock","type":"topic","navigatorTitle":[{"text":"SDWebImageTransitionCompletionBlock","kind":"identifier"}],"abstract":[],"role":"symbol","title":"SDWebImageTransitionCompletionBlock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagetransition","title":"SDWebImageTransition","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"code":"sd_imageTransition","type":"codeVoice"},{"text":" in UIView+WebCache.h","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"code":"+[UIView transitionWithView:duration:options:animations:completion]","type":"codeVoice"},{"type":"text","text":" for transition animation."},{"text":" ","type":"text"},{"text":"for AppKit(macOS), we use ","type":"text"},{"code":"+[NSAnimationContext runAnimationGroup:completionHandler:]","type":"codeVoice"},{"text":" for transition animation. You can call ","type":"text"},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"text":" to grab the context during animations block.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SDWebImageTransition","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"path":"\/metadata\/title","op":"replace","value":"completion"},{"value":"property","path":"\/metadata\/symbolKind","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"completion","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"copy","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:BFv(#b)","kind":"typeIdentifier","text":"void (^)(_Bool)"},{"text":" ","kind":"text"},{"kind":"identifier","text":"completion"},{"text":";","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":"completion","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1completion\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1completion\/fragments","op":"replace","value":[{"text":"completion","kind":"identifier"}]},{"value":"SDWebImageTransitionCompletionBlock","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionCompletionBlock\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionCompletionBlock\/fragments","value":[{"text":"SDWebImageTransitionCompletionBlock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionCompletionBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageTransitionCompletionBlock"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageTransition"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","op":"replace"},{"value":[{"text":"SDWebImageTransition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/navigatorTitle"}]}]}