{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlDown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition","text":"SDWebImageTransition"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/curldown"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/curldown"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Curl down transition."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"curlDownTransition"}],"role":"symbol","title":"curlDown","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlDown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"symbolKind":"property","externalID":"c:objc(cs)SDWebImageTransition(cpy)curlDownTransition","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/curlDown":{"role":"symbol","title":"curlDown","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"curlDown"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Curl down transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/curlDown","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"curlDownTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/curldown"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"role":"symbol","title":"SDWebImageTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"curlDownTransition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"curlDownTransition"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition","text":"SDWebImageTransition"},{"kind":"text","text":" * "},{"kind":"identifier","text":"curlDownTransition"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlDown\/title","value":"curlDownTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1curlDown\/fragments","value":[{"kind":"identifier","text":"curlDownTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}