{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/fade"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/fade"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"fade","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageTransition","text":"SDWebImageTransition"}],"externalID":"c:objc(cs)SDWebImageTransition(cpy)fadeTransition","roleHeading":"Type Property","title":"fade","role":"symbol","symbolKind":"property","navigatorTitle":[{"text":"fadeTransition","kind":"identifier"}],"extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"abstract":[{"text":"Fade-in transition.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"fade","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/fade":{"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"fade","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageTransition","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagetransition\/fade","title":"fade","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/fade","abstract":[{"text":"Fade-in transition.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"fadeTransition","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagetransition","title":"SDWebImageTransition","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"code":"sd_imageTransition","type":"codeVoice"},{"text":" in UIView+WebCache.h","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"code":"+[UIView transitionWithView:duration:options:animations:completion]","type":"codeVoice"},{"type":"text","text":" for transition animation."},{"text":" ","type":"text"},{"text":"for AppKit(macOS), we use ","type":"text"},{"code":"+[NSAnimationContext runAnimationGroup:completionHandler:]","type":"codeVoice"},{"text":" for transition animation. You can call ","type":"text"},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"text":" to grab the context during animations block.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SDWebImageTransition","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"value":"fadeTransition","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"fadeTransition","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"fadeTransition","kind":"identifier"},{"text":";","kind":"text"}]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"op":"replace","value":"fadeTransition","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1fade\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1fade\/fragments","value":[{"kind":"identifier","text":"fadeTransition"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition","op":"replace"},{"value":[{"text":"SDWebImageTransition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments"},{"op":"replace","value":[{"text":"SDWebImageTransition","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/navigatorTitle"}]}]}