{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromLeft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromleft(duration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromleft(duration:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft(duration:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Flip from left  transition with duration."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromLeft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"title":"flipFromLeft(duration:)","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImageTransition(cm)flipFromLeftTransitionWithDuration:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"role":"symbol","title":"SDWebImageTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromLeft(duration:)":{"role":"symbol","title":"flipFromLeft(duration:)","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromLeft"},{"kind":"text","text":"("},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}],"abstract":[{"type":"text","text":"Flip from left  transition with duration."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromLeft(duration:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromleft(duration:)"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Method"},{"op":"replace","path":"\/metadata\/title","value":"flipFromLeftTransitionWithDuration:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSTimeInterval","preciseIdentifier":"c:@T@NSTimeInterval"},{"kind":"text","text":")"},{"kind":"internalParam","text":"duration"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromLeft(duration:)\/title","value":"flipFromLeftTransitionWithDuration:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromLeft(duration:)\/fragments","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromLeftTransitionWithDuration:"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}