{"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"flipFromRight","kind":"identifier"},{"kind":"text","text":"("},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Transition duration, use ease-in-out"}],"type":"paragraph"}],"name":"duration"}]}],"abstract":[{"type":"text","text":"Flip from right transition with duration."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromright(duration:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromright(duration:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Type Method","modules":[{"name":"SDWebImage"}],"role":"symbol","extendedModule":"SDWebImage","title":"flipFromRight(duration:)","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"flipFromRightTransitionWithDuration:"}],"externalID":"c:objc(cs)SDWebImageTransition(cm)flipFromRightTransitionWithDuration:","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"flipFromRight","kind":"identifier"},{"kind":"text","text":"("},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Self"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight(duration:)","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromRight(duration:)":{"role":"symbol","type":"topic","abstract":[{"type":"text","text":"Flip from right transition with duration."}],"kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromRight(duration:)","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flipFromRight","kind":"identifier"},{"kind":"text","text":"("},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@T@NSTimeInterval","text":"TimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"title":"flipFromRight(duration:)","navigatorTitle":[{"text":"flipFromRightTransitionWithDuration:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfromright(duration:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagetransition","title":"SDWebImageTransition","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"code":"sd_imageTransition","type":"codeVoice"},{"text":" in UIView+WebCache.h","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"code":"+[UIView transitionWithView:duration:options:animations:completion]","type":"codeVoice"},{"type":"text","text":" for transition animation."},{"text":" ","type":"text"},{"text":"for AppKit(macOS), we use ","type":"text"},{"code":"+[NSAnimationContext runAnimationGroup:completionHandler:]","type":"codeVoice"},{"text":" for transition animation. You can call ","type":"text"},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"text":" to grab the context during animations block.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SDWebImageTransition","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Type Method","op":"replace"},{"path":"\/metadata\/title","value":"flipFromRightTransitionWithDuration:","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"method"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"flipFromRightTransitionWithDuration:"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"text","text":"+ ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"identifier","text":"flipFromRightTransitionWithDuration:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"text":"duration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"duration","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Transition duration, use ease-in-out"}]}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromRight(duration:)\/title","value":"flipFromRightTransitionWithDuration:","op":"replace"},{"op":"replace","value":[{"text":"+ ","kind":"text"},{"text":"flipFromRightTransitionWithDuration:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromRight(duration:)\/fragments"},{"value":"SDWebImageTransition","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","op":"replace"},{"value":[{"text":"SDWebImageTransition","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}