{"kind":"symbol","schemaVersion":{"minor":3,"patch":0,"major":0},"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Type Method","extendedModule":"SDWebImage","symbolKind":"method","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"flipFromBottom","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"duration"},{"text":": ","kind":"text"},{"text":"TimeInterval","preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Self"}],"externalID":"c:objc(cs)SDWebImageTransition(cm)flipFromBottomTransitionWithDuration:","title":"flipFromBottom(duration:)","navigatorTitle":[{"text":"flipFromBottomTransitionWithDuration:","kind":"identifier"}]},"abstract":[{"type":"text","text":"Flip from bottom transition with duration."}],"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromBottom"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"duration"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@T@NSTimeInterval","kind":"typeIdentifier","text":"TimeInterval"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"name":"duration","content":[{"inlineContent":[{"type":"text","text":"Transition duration, use ease-in-out"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom(duration:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom(duration:)"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom(duration:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromBottom(duration:)":{"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom(duration:)","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"flipFromBottom","kind":"identifier"},{"text":"(","kind":"text"},{"text":"duration","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"TimeInterval","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval"},{"text":") -> ","kind":"text"},{"text":"Self","kind":"typeIdentifier"}],"title":"flipFromBottom(duration:)","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom(duration:)","abstract":[{"text":"Flip from bottom transition with duration.","type":"text"}],"type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromBottomTransitionWithDuration:"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagetransition","title":"SDWebImageTransition","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"code":"sd_imageTransition","type":"codeVoice"},{"text":" in UIView+WebCache.h","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"code":"+[UIView transitionWithView:duration:options:animations:completion]","type":"codeVoice"},{"type":"text","text":" for transition animation."},{"text":" ","type":"text"},{"text":"for AppKit(macOS), we use ","type":"text"},{"code":"+[NSAnimationContext runAnimationGroup:completionHandler:]","type":"codeVoice"},{"text":" for transition animation. You can call ","type":"text"},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"text":" to grab the context during animations block.","type":"text"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"text":"SDWebImageTransition","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Method"},{"path":"\/metadata\/title","value":"flipFromBottomTransitionWithDuration:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"+ "},{"text":"flipFromBottomTransitionWithDuration:","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"flipFromBottomTransitionWithDuration:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","preciseIdentifier":"c:@T@NSTimeInterval","text":"NSTimeInterval"},{"kind":"text","text":") "},{"text":"duration","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"Transition duration, use ease-in-out","type":"text"}]}],"name":"duration"}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom(duration:)\/title","value":"flipFromBottomTransitionWithDuration:","op":"replace"},{"value":[{"kind":"text","text":"+ "},{"text":"flipFromBottomTransitionWithDuration:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom(duration:)\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/navigatorTitle","value":[{"text":"SDWebImageTransition","kind":"identifier"}]}]}]}