{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition","text":"SDWebImageTransition"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Flip from bottom transition."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"flipFromBottomTransition"}],"role":"symbol","title":"flipFromBottom","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"symbolKind":"property","externalID":"c:objc(cs)SDWebImageTransition(cpy)flipFromBottomTransition","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"role":"symbol","title":"SDWebImageTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/flipFromBottom":{"role":"symbol","title":"flipFromBottom","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"flipFromBottom"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition"}],"abstract":[{"type":"text","text":"Flip from bottom transition."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/flipFromBottom","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"flipFromBottomTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/flipfrombottom"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"flipFromBottomTransition"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"flipFromBottomTransition"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","preciseIdentifier":"c:objc(cs)SDWebImageTransition","text":"SDWebImageTransition"},{"kind":"text","text":" * "},{"kind":"identifier","text":"flipFromBottomTransition"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom\/title","value":"flipFromBottomTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1flipFromBottom\/fragments","value":[{"kind":"identifier","text":"flipFromBottomTransition"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}