{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepares"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionPreparesBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionPreparesBlock","text":"SDWebImageTransitionPreparesBlock"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/prepares"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagetransition\/prepares"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/prepares","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A block object to be executed before the animation sequence starts."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepares"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransitionPreparesBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionPreparesBlock"},{"kind":"text","text":"?"}],"title":"prepares","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageTransition(py)prepares","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"prepares"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition":{"role":"symbol","title":"SDWebImageTransition","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransition"}],"abstract":[{"type":"text","text":"This class is used to provide a transition animation after the view category load image finished. Use this on "},{"type":"codeVoice","code":"sd_imageTransition"},{"type":"text","text":" in UIView+WebCache.h"},{"type":"text","text":" "},{"type":"text","text":"for UIKit(iOS & tvOS), we use "},{"type":"codeVoice","code":"+[UIView transitionWithView:duration:options:animations:completion]"},{"type":"text","text":" for transition animation."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), we use "},{"type":"codeVoice","code":"+[NSAnimationContext runAnimationGroup:completionHandler:]"},{"type":"text","text":" for transition animation. You can call "},{"type":"codeVoice","code":"+[NSAnimationContext currentContext]"},{"type":"text","text":" to grab the context during animations block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransition"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransition/prepares":{"role":"symbol","title":"prepares","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepares"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageTransitionPreparesBlock","preciseIdentifier":"c:SDWebImageTransition.h@T@SDWebImageTransitionPreparesBlock"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"A block object to be executed before the animation sequence starts."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransition\/prepares","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"prepares"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransition\/prepares"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageTransitionPreparesBlock":{"role":"symbol","title":"SDWebImageTransitionPreparesBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageTransitionPreparesBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageTransitionPreparesBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageTransitionPreparesBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagetransitionpreparesblock"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"prepares"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"prepares"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"copy"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"void (^)(__kindof UIView *, UIImage *, NSData *, enum SDImageCacheType, NSURL *)","preciseIdentifier":"c:BFv(#*Q$objc(cs)UIView#*$objc(cs)UIImage#*$objc(cs)NSData#$@E@SDImageCacheType#*$objc(cs)NSURL)"},{"kind":"text","text":" "},{"kind":"identifier","text":"prepares"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/title","value":"SDWebImageTransition"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransition"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1prepares\/title","value":"prepares"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransition~1prepares\/fragments","value":[{"kind":"identifier","text":"prepares"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionPreparesBlock\/title","value":"SDWebImageTransitionPreparesBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageTransitionPreparesBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageTransitionPreparesBlock"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}