{"abstract":[{"type":"text","text":"Any user-provided info stored into coordinator, such as status value used for coordinator"}],"sections":[],"kind":"symbol","identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/userInfo","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"userInfo","kind":"identifier"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?"}],"platforms":["iOS"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator"]]},"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimagecoordinator\/userinfo"],"traits":[{"interfaceLanguage":"swift"}]}],"metadata":{"title":"userInfo","role":"symbol","platforms":[{"introducedAt":"14.0","name":"iOS","beta":false,"unavailable":false,"deprecated":false},{"unavailable":false,"beta":false,"name":"iPadOS","introducedAt":"14.0","deprecated":false},{"deprecated":false,"beta":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"name":"macOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"11.0"},{"name":"tvOS","beta":false,"deprecated":false,"unavailable":false,"introducedAt":"14.0"},{"deprecated":false,"name":"watchOS","unavailable":false,"beta":false,"introducedAt":"7.0"}],"roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userInfo"},{"text":": [","kind":"text"},{"preciseIdentifier":"s:s11AnyHashableV","text":"AnyHashable","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"externalID":"s:17SDWebImageSwiftUI08AnimatedB11CoordinatorC8userInfoSDys11AnyHashableVypGSgvp","symbolKind":"property","modules":[{"name":"SDWebImageSwiftUI"}]},"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator":{"abstract":[{"text":"A coordinator object used for ","type":"text"},{"type":"codeVoice","code":"AnimatedImage"},{"type":"text","text":"native view  bridge for UIKit\/AppKit."}],"title":"AnimatedImageCoordinator","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"AnimatedImageCoordinator","kind":"identifier"}],"navigatorTitle":[{"text":"AnimatedImageCoordinator","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator","type":"topic","kind":"symbol"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageCoordinator/userInfo":{"role":"symbol","title":"userInfo","type":"topic","kind":"symbol","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"userInfo"},{"kind":"text","text":": ["},{"text":"AnyHashable","kind":"typeIdentifier","preciseIdentifier":"s:s11AnyHashableV"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]?","kind":"text"}],"abstract":[{"text":"Any user-provided info stored into coordinator, such as status value used for coordinator","type":"text"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimagecoordinator\/userinfo","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageCoordinator\/userInfo"}},"variantOverrides":[{"patch":[{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/title","op":"replace","value":"AnimatedImageCoordinator"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/fragments","value":[{"text":"AnimatedImageCoordinator","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageCoordinator\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"AnimatedImageCoordinator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}