{"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grayLarge","kind":"identifier"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","kind":"typeIdentifier"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/grayLarge"},"abstract":[{"type":"text","text":"large gray-style activity indicator"}],"metadata":{"extendedModule":"SDWebImage","externalID":"c:objc(cs)SDWebImageActivityIndicator(cpy)grayLargeIndicator","navigatorTitle":[{"text":"grayLargeIndicator","kind":"identifier"}],"roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grayLarge","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"title":"grayLarge"},"kind":"symbol","sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/graylarge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/graylarge"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/grayLarge":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/grayLarge","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"grayLargeIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/graylarge","abstract":[{"text":"large gray-style activity indicator","type":"text"}],"type":"topic","role":"symbol","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"grayLarge","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageActivityIndicator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"title":"grayLarge"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"type":"topic","abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"code":"NSProgressIndicator","type":"codeVoice"},{"type":"text","text":" with the spinning style."}],"kind":"symbol","title":"SDWebImageActivityIndicator","navigatorTitle":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Type Property"},{"path":"\/metadata\/title","op":"replace","value":"grayLargeIndicator"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"grayLargeIndicator","kind":"identifier"}]},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"text":", ","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"grayLargeIndicator","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1grayLarge\/title","op":"replace","value":"grayLargeIndicator"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1grayLarge\/fragments","value":[{"kind":"identifier","text":"grayLargeIndicator"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","value":"SDWebImageActivityIndicator","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}]},{"op":"replace","value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}