{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/gray"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/gray"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/gray","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"These indicator use the fixed color without dark mode support"},{"type":"text","text":" "},{"type":"text","text":"gray-style activity indicator"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"title":"gray","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageActivityIndicator(cpy)grayIndicator","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"grayIndicator"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"role":"symbol","title":"SDWebImageActivityIndicator","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"type":"codeVoice","code":"UIActivityIndicatorView"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"type":"codeVoice","code":"NSProgressIndicator"},{"type":"text","text":" with the spinning style."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/gray":{"role":"symbol","title":"gray","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"gray"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"abstract":[{"type":"text","text":"These indicator use the fixed color without dark mode support"},{"type":"text","text":" "},{"type":"text","text":"gray-style activity indicator"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/gray","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"grayIndicator"}],"url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/gray"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Type Property"},{"op":"replace","path":"\/metadata\/title","value":"grayIndicator"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"grayIndicator"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"readonly"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonnull"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator"},{"kind":"text","text":" * "},{"kind":"identifier","text":"grayIndicator"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","value":"SDWebImageActivityIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments","value":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1gray\/title","value":"grayIndicator"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1gray\/fragments","value":[{"kind":"identifier","text":"grayIndicator"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}