{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicatorView"},{"text":": ","kind":"text"},{"text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","kind":"typeIdentifier"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}]}]}],"kind":"symbol","metadata":{"symbolKind":"property","role":"symbol","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"indicatorView"},{"text":": ","kind":"text"},{"text":"UIActivityIndicatorView","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView"}],"navigatorTitle":[{"kind":"identifier","text":"indicatorView"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:objc(cs)SDWebImageActivityIndicator(py)indicatorView","title":"indicatorView","roleHeading":"Instance Property"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/indicatorview"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/indicatorview"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/indicatorView"},"schemaVersion":{"major":0,"minor":3,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/indicatorView":{"navigatorTitle":[{"text":"indicatorView","kind":"identifier"}],"type":"topic","title":"indicatorView","fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"indicatorView"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","text":"UIActivityIndicatorView","kind":"typeIdentifier"}],"abstract":[],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/indicatorView","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/indicatorview","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"type":"topic","abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"code":"NSProgressIndicator","type":"codeVoice"},{"type":"text","text":" with the spinning style."}],"kind":"symbol","title":"SDWebImageActivityIndicator","navigatorTitle":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"indicatorView"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"indicatorView"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"UIActivityIndicatorView","preciseIdentifier":"c:objc(cs)UIActivityIndicatorView","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"indicatorView","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"indicatorView","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1indicatorView\/title"},{"value":[{"text":"indicatorView","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1indicatorView\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","value":"SDWebImageActivityIndicator","op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}]}]}]}