{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"large","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageActivityIndicator","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/large"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/large"]}],"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"large","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator","kind":"typeIdentifier"}],"role":"symbol","roleHeading":"Type Property","extendedModule":"SDWebImage","title":"large","symbolKind":"property","navigatorTitle":[{"text":"largeIndicator","kind":"identifier"}],"externalID":"c:objc(cs)SDWebImageActivityIndicator(cpy)largeIndicator","modules":[{"name":"SDWebImage"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/large"},"abstract":[{"text":"These indicator use the system style, supports dark mode if available (iOS 13+\/macOS 10.14+)","type":"text"},{"type":"text","text":" "},{"text":"large activity indicator","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/large":{"navigatorTitle":[{"text":"largeIndicator","kind":"identifier"}],"kind":"symbol","role":"symbol","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/large","title":"large","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/large","abstract":[{"text":"These indicator use the system style, supports dark mode if available (iOS 13+\/macOS 10.14+)","type":"text"},{"type":"text","text":" "},{"type":"text","text":"large activity indicator"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"large","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"type":"topic","abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"code":"NSProgressIndicator","type":"codeVoice"},{"type":"text","text":" with the spinning style."}],"kind":"symbol","title":"SDWebImageActivityIndicator","navigatorTitle":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"role":"symbol"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"value":"Type Property","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"largeIndicator"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"kind":"identifier","text":"largeIndicator"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"},{"kind":"text","text":" * "},{"text":"largeIndicator","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"largeIndicator","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1large\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1large\/fragments","op":"replace","value":[{"text":"largeIndicator","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","value":"SDWebImageActivityIndicator"},{"value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments","op":"replace"},{"value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}