{"primaryContentSections":[{"declarations":[{"languages":["swift"],"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"whiteLarge","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","kind":"typeIdentifier","text":"SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"text":" }","kind":"text"}],"platforms":["iOS"]}],"kind":"declarations"}],"abstract":[{"type":"text","text":"large white-style activity indicator"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/whitelarge"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageactivityindicator\/whitelarge"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","metadata":{"roleHeading":"Type Property","symbolKind":"property","title":"whiteLarge","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"whiteLarge","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","text":"SDWebImageActivityIndicator"}],"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"whiteLargeIndicator","kind":"identifier"}],"extendedModule":"SDWebImage","role":"symbol","externalID":"c:objc(cs)SDWebImageActivityIndicator(cpy)whiteLargeIndicator"},"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator"]]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/whiteLarge","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator/whiteLarge":{"title":"whiteLarge","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator\/whiteLarge","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator\/whitelarge","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"whiteLarge","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageActivityIndicator","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator"}],"navigatorTitle":[{"text":"whiteLargeIndicator","kind":"identifier"}],"abstract":[{"type":"text","text":"large white-style activity indicator"}],"kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageActivityIndicator":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","url":"\/documentation\/sdwebimage\/sdwebimageactivityindicator","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"type":"topic","abstract":[{"type":"text","text":"Activity indicator class."},{"type":"text","text":" "},{"type":"text","text":"for UIKit(macOS), it use a "},{"code":"UIActivityIndicatorView","type":"codeVoice"},{"text":".","type":"text"},{"type":"text","text":" "},{"type":"text","text":"for AppKit(macOS), it use a "},{"code":"NSProgressIndicator","type":"codeVoice"},{"type":"text","text":" with the spinning style."}],"kind":"symbol","title":"SDWebImageActivityIndicator","navigatorTitle":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Type Property","path":"\/metadata\/roleHeading"},{"value":"whiteLargeIndicator","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"whiteLargeIndicator","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"text":", ","kind":"text"},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"text":"SDWebImageActivityIndicator","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageActivityIndicator","preciseIdentifier":"c:objc(cs)SDWebImageActivityIndicator","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"whiteLargeIndicator","kind":"identifier"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1whiteLarge\/title","op":"replace","value":"whiteLargeIndicator"},{"value":[{"text":"whiteLargeIndicator","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator~1whiteLarge\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/title","op":"replace","value":"SDWebImageActivityIndicator"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageActivityIndicator"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageActivityIndicator\/navigatorTitle","value":[{"text":"SDWebImageActivityIndicator","kind":"identifier"}],"op":"replace"}]}]}