{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCache"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache","text":"SDImageCacheProtocol"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/addcache(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/addcache(_:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/addCache(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Add a new cache to the end of caches array. Which has the highest priority."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCache"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache"},{"kind":"text","text":")"}],"title":"addCache(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDImageCachesManager(im)addCache:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"addCache:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/addCache(_:)":{"role":"symbol","title":"addCache(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"addCache"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Add a new cache to the end of caches array. Which has the highest priority."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/addCache(_:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"addCache:"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/addcache(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"role":"symbol","title":"SDImageCachesManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCachesManager"}],"abstract":[{"type":"text","text":"A caches manager to manage multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"role":"symbol","title":"SDImageCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"}],"abstract":[{"type":"text","text":"This is the image cache protocol to provide custom image cache for "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Though the best practice to custom image cache, is to write your own class which conform "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol for "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"However, if your own cache implementation contains more advanced feature beyond "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like "},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"addCache:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCache:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"addCache:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id<SDImageCache>","preciseIdentifier":"c:Qoobjc(pl)SDImageCache"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"cache"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1addCache(_:)\/title","value":"addCache:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1addCache(_:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"addCache:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title","value":"SDImageCachesManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}