{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearOperationPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/clearoperationpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/clearoperationpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/clearOperationPolicy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Operation policy for clear op."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"Concurrent"},{"type":"text","text":", means clear all caches concurrently."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearOperationPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy"}],"title":"clearOperationPolicy","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCachesManager(py)clearOperationPolicy","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"clearOperationPolicy"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/clearOperationPolicy":{"role":"symbol","title":"clearOperationPolicy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearOperationPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy"}],"abstract":[{"type":"text","text":"Operation policy for clear op."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"Concurrent"},{"type":"text","text":", means clear all caches concurrently."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/clearOperationPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"clearOperationPolicy"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/clearoperationpolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"role":"symbol","title":"SDImageCachesManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCachesManager"}],"abstract":[{"type":"text","text":"A caches manager to manage multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"role":"symbol","title":"SDImageCachesManagerOperationPolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"abstract":[{"type":"text","text":"Policy for cache operation"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"clearOperationPolicy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"clearOperationPolicy"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"clearOperationPolicy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1clearOperationPolicy\/title","value":"clearOperationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1clearOperationPolicy\/fragments","value":[{"kind":"identifier","text":"clearOperationPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title","value":"SDImageCachesManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title","value":"SDImageCachesManagerOperationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}