{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsOperationPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/containsoperationpolicy"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/containsoperationpolicy"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/containsOperationPolicy","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Operation policy for contains op."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"Serial"},{"type":"text","text":", means check all caches serially (one completion called then next begin) until one cache check success ("},{"type":"codeVoice","code":"containsCacheType"},{"type":"text","text":" != None)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsOperationPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy"}],"title":"containsOperationPolicy","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDImageCachesManager(py)containsOperationPolicy","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"containsOperationPolicy"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/containsOperationPolicy":{"role":"symbol","title":"containsOperationPolicy","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"containsOperationPolicy"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy"}],"abstract":[{"type":"text","text":"Operation policy for contains op."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"type":"codeVoice","code":"Serial"},{"type":"text","text":", means check all caches serially (one completion called then next begin) until one cache check success ("},{"type":"codeVoice","code":"containsCacheType"},{"type":"text","text":" != None)."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/containsOperationPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"containsOperationPolicy"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/containsoperationpolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"role":"symbol","title":"SDImageCachesManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCachesManager"}],"abstract":[{"type":"text","text":"A caches manager to manage multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"role":"symbol","title":"SDImageCachesManagerOperationPolicy","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"abstract":[{"type":"text","text":"Policy for cache operation"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"containsOperationPolicy"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"containsOperationPolicy"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":") "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy"},{"kind":"identifier","text":"containsOperationPolicy"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1containsOperationPolicy\/title","value":"containsOperationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1containsOperationPolicy\/fragments","value":[{"kind":"identifier","text":"containsOperationPolicy"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title","value":"SDImageCachesManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title","value":"SDImageCachesManagerOperationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}