{"metadata":{"role":"symbol","roleHeading":"Instance Property","modules":[{"name":"SDWebImage"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"removeOperationPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"}],"title":"removeOperationPolicy","externalID":"c:objc(cs)SDImageCachesManager(py)removeOperationPolicy","navigatorTitle":[{"text":"removeOperationPolicy","kind":"identifier"}],"symbolKind":"property"},"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","abstract":[{"type":"text","text":"Operation policy for remove op."},{"type":"text","text":" "},{"type":"text","text":"Defaults to "},{"code":"Concurrent","type":"codeVoice"},{"type":"text","text":", means remove all caches concurrently."}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"primaryContentSections":[{"declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeOperationPolicy","kind":"identifier"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"text":" }","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeOperationPolicy","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/removeoperationpolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/removeoperationpolicy"]}],"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCachesManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","url":"\/documentation\/sdwebimage\/sdimagecachesmanager","type":"topic","abstract":[{"text":"A caches manager to manage multiple caches.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"kind":"symbol","title":"SDImageCachesManager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy","type":"topic","abstract":[{"text":"Policy for cache operation","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/removeOperationPolicy":{"title":"removeOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/removeoperationpolicy","navigatorTitle":[{"text":"removeOperationPolicy","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"removeOperationPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"}],"abstract":[{"type":"text","text":"Operation policy for remove op."},{"type":"text","text":" "},{"text":"Defaults to ","type":"text"},{"type":"codeVoice","code":"Concurrent"},{"type":"text","text":", means remove all caches concurrently."}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeOperationPolicy","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"removeOperationPolicy"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"removeOperationPolicy","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeOperationPolicy"},{"text":";","kind":"text"}],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title","op":"replace","value":"SDImageCachesManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}]},{"value":[{"text":"SDImageCachesManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title","value":"SDImageCachesManagerOperationPolicy"},{"op":"replace","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/navigatorTitle"},{"value":"removeOperationPolicy","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeOperationPolicy\/title","op":"replace"},{"value":[{"text":"removeOperationPolicy","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeOperationPolicy\/fragments"}]}]}