{"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/removecache(_:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/removecache(_:)"]}],"abstract":[{"type":"text","text":"Remove a cache in the caches array."}],"metadata":{"roleHeading":"Instance Method","title":"removeCache(_:)","navigatorTitle":[{"kind":"identifier","text":"removeCache:"}],"modules":[{"name":"SDWebImage"}],"role":"symbol","externalID":"c:objc(cs)SDImageCachesManager(im)removeCache:","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"removeCache","kind":"identifier"},{"kind":"text","text":"(any "},{"text":"SDImageCacheProtocol","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCache"},{"kind":"text","text":")"}]},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeCache"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"cache"},{"kind":"text","text":": any "},{"preciseIdentifier":"c:objc(pl)SDImageCache","kind":"typeIdentifier","text":"SDImageCacheProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol"},{"text":")","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"name":"cache","content":[{"inlineContent":[{"type":"text","text":"Cache"}],"type":"paragraph"}]}],"kind":"parameters"}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeCache(_:)"},"schemaVersion":{"patch":0,"major":0,"minor":3},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/removeCache(_:)":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/removeCache(_:)","kind":"symbol","abstract":[{"text":"Remove a cache in the caches array.","type":"text"}],"role":"symbol","type":"topic","navigatorTitle":[{"text":"removeCache:","kind":"identifier"}],"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeCache","kind":"identifier"},{"kind":"text","text":"(any "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCache","text":"SDImageCacheProtocol"},{"text":")","kind":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/removecache(_:)","title":"removeCache(_:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheProtocol"}],"navigatorTitle":[{"text":"SDImageCacheProtocol","kind":"identifier"}],"abstract":[{"text":"This is the image cache protocol to provide custom image cache for ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Though the best practice to custom image cache, is to write your own class which conform ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"code":"SDDiskCache","type":"codeVoice"},{"type":"text","text":" protocol for "},{"code":"SDImageCache","type":"codeVoice"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"However, if your own cache implementation contains more advanced feature beyond ","type":"text"},{"code":"SDImageCache","type":"codeVoice"},{"text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like ","type":"text"},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"title":"SDImageCacheProtocol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCachesManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","url":"\/documentation\/sdwebimage\/sdimagecachesmanager","type":"topic","abstract":[{"text":"A caches manager to manage multiple caches.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"kind":"symbol","title":"SDImageCachesManager"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"removeCache:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"removeCache:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"text":") ","kind":"text"},{"kind":"identifier","text":"removeCache:"},{"text":"(","kind":"text"},{"text":"id<SDImageCache>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDImageCache"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cache"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"Cache"}],"type":"paragraph"}],"name":"cache"}]},"op":"replace","path":"\/primaryContentSections\/1"},{"value":"removeCache:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeCache(_:)\/title","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"removeCache:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1removeCache(_:)\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","value":"SDImageCache"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","value":"SDImageCachesManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"kind":"identifier","text":"SDImageCachesManager"}],"op":"replace"},{"value":[{"text":"SDImageCachesManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/navigatorTitle"}]}]}