{"kind":"symbol","abstract":[{"text":"Returns the global shared caches manager instance. By default we will set [","type":"text"},{"type":"codeVoice","code":"SDImageCache.sharedImageCache"},{"text":"] into the caches array.","type":"text"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/shared","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"shared","externalID":"c:objc(cs)SDImageCachesManager(cpy)sharedManager","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"text":"SDImageCachesManager","preciseIdentifier":"c:objc(cs)SDImageCachesManager","kind":"typeIdentifier"}],"symbolKind":"property","role":"symbol","roleHeading":"Type Property"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shared","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCachesManager","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","text":"SDImageCachesManager"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"kind":"text","text":" }"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/shared"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/shared"],"traits":[{"interfaceLanguage":"occ"}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCachesManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","url":"\/documentation\/sdwebimage\/sdimagecachesmanager","type":"topic","abstract":[{"text":"A caches manager to manage multiple caches.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"kind":"symbol","title":"SDImageCachesManager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/shared":{"role":"symbol","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shared"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)SDImageCachesManager","text":"SDImageCachesManager","kind":"typeIdentifier"}],"kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/shared","title":"shared","abstract":[{"type":"text","text":"Returns the global shared caches manager instance. By default we will set ["},{"type":"codeVoice","code":"SDImageCache.sharedImageCache"},{"type":"text","text":"] into the caches array."}],"navigatorTitle":[{"text":"sharedManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/shared"}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"path":"\/metadata\/roleHeading","value":"Type Property","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"sharedManager"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"sharedManager","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"class","kind":"keyword"},{"kind":"text","text":", "},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"readonly","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCachesManager","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","text":"SDImageCachesManager"},{"text":" * ","kind":"text"},{"text":"sharedManager","kind":"identifier"},{"kind":"text","text":";"}],"platforms":["iOS"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","value":"SDImageCachesManager","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"text":"SDImageCachesManager","kind":"identifier"}]},{"value":[{"text":"SDImageCachesManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1shared\/title","value":"sharedManager"},{"value":[{"text":"sharedManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1shared\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}