{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"storeOperationPolicy"},{"text":": ","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","kind":"typeIdentifier","text":"SDImageCachesManagerOperationPolicy"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager"]]},"metadata":{"externalID":"c:objc(cs)SDImageCachesManager(py)storeOperationPolicy","navigatorTitle":[{"text":"storeOperationPolicy","kind":"identifier"}],"roleHeading":"Instance Property","title":"storeOperationPolicy","fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"storeOperationPolicy"},{"text":": ","kind":"text"},{"text":"SDImageCachesManagerOperationPolicy","preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"}],"modules":[{"name":"SDWebImage"}],"symbolKind":"property","role":"symbol"},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/storeOperationPolicy"},"abstract":[{"type":"text","text":"Operation policy for store op."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to "},{"code":"HighestOnly","type":"codeVoice"},{"type":"text","text":", means store to the highest priority cache only."}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/storeoperationpolicy"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecachesmanager\/storeoperationpolicy"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManagerOperationPolicy":{"fragments":[{"kind":"keyword","text":"enum"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCachesManagerOperationPolicy"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","url":"\/documentation\/sdwebimage\/sdimagecachesmanageroperationpolicy","type":"topic","abstract":[{"text":"Policy for cache operation","type":"text"}],"role":"symbol","navigatorTitle":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"kind":"symbol","title":"SDImageCachesManagerOperationPolicy"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager":{"fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageCachesManager","kind":"identifier"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager","url":"\/documentation\/sdwebimage\/sdimagecachesmanager","type":"topic","abstract":[{"text":"A caches manager to manage multiple caches.","type":"text"}],"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDImageCachesManager"}],"kind":"symbol","title":"SDImageCachesManager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCachesManager/storeOperationPolicy":{"title":"storeOperationPolicy","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManager\/storeOperationPolicy","type":"topic","abstract":[{"type":"text","text":"Operation policy for store op."},{"text":" ","type":"text"},{"text":"Defaults to ","type":"text"},{"code":"HighestOnly","type":"codeVoice"},{"text":", means store to the highest priority cache only.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimagecachesmanager\/storeoperationpolicy","role":"symbol","navigatorTitle":[{"text":"storeOperationPolicy","kind":"identifier"}],"fragments":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"storeOperationPolicy","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"}]}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"storeOperationPolicy","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"storeOperationPolicy","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"assign","kind":"keyword"},{"kind":"text","text":") "},{"preciseIdentifier":"c:@E@SDImageCachesManagerOperationPolicy","text":"SDImageCachesManagerOperationPolicy","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCachesManagerOperationPolicy","kind":"typeIdentifier"},{"text":" ","kind":"text"},{"text":"storeOperationPolicy","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}],"kind":"declarations"},"op":"replace"},{"value":"SDImageCachesManagerOperationPolicy","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/fragments","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManagerOperationPolicy\/navigatorTitle","op":"replace","value":[{"text":"SDImageCachesManagerOperationPolicy","kind":"identifier"}]},{"value":"SDImageCachesManager","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/fragments","value":[{"text":"SDImageCachesManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager\/navigatorTitle","value":[{"text":"SDImageCachesManager","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1storeOperationPolicy\/title","op":"replace","value":"storeOperationPolicy"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCachesManager~1storeOperationPolicy\/fragments","value":[{"text":"storeOperationPolicy","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}