{"sections":[],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"avoidDecodeImage","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"},{"kind":"text","text":" { "},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"5.14.0 introduce "},{"code":"SDImageCoderDecodeUseLazyDecoding","type":"codeVoice"},{"type":"text","text":", use that for better control from codec, instead of post-processing. Which acts the similar like this option but works for SDAnimatedImage as well (this one does not)"}]}],"style":"note"}]}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/avoiddecodeimage"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/avoiddecodeimage"]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"]]},"schemaVersion":{"minor":3,"patch":0,"major":0},"deprecationSummary":[{"inlineContent":[{"text":"Use SDWebImageContextImageForceDecodePolicy instead","type":"text"}],"type":"paragraph"}],"abstract":[{"text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"However, this process may increase the memory usage as well. If you are experiencing a issue due to excessive memory consumption, This flag can prevent decode the image."}],"kind":"symbol","metadata":{"role":"symbol","roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"symbolKind":"property","navigatorTitle":[{"text":"SDImageCacheAvoidDecodeImage","kind":"identifier"}],"title":"avoidDecodeImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"avoidDecodeImage"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions","kind":"typeIdentifier"}],"platforms":[{"deprecated":false,"beta":false,"name":"iOS","deprecatedAt":"8.0","message":"Use SDWebImageContextImageForceDecodePolicy instead","introducedAt":"8.0","unavailable":false},{"deprecatedAt":"8.0","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"8.0","name":"iPadOS","message":"Use SDWebImageContextImageForceDecodePolicy instead"},{"message":"Use SDWebImageContextImageForceDecodePolicy instead","name":"Mac Catalyst","beta":false,"deprecated":false,"deprecatedAt":"8.0","unavailable":false,"introducedAt":"8.0"}],"externalID":"c:@E@SDImageCacheOptions@SDImageCacheAvoidDecodeImage"},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/avoidDecodeImage","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/avoidDecodeImage":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/avoidDecodeImage","title":"avoidDecodeImage","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"avoidDecodeImage"},{"kind":"text","text":": "},{"text":"SDImageCacheOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"navigatorTitle":[{"text":"SDImageCacheAvoidDecodeImage","kind":"identifier"}],"deprecated":true,"type":"topic","abstract":[{"text":"By default, we will decode the image in the background during cache query and download from the network. This can help to improve performance because when rendering image on the screen, it need to be firstly decoded. But this happen on the main queue by Core Animation.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"However, this process may increase the memory usage as well. If you are experiencing a issue due to excessive memory consumption, This flag can prevent decode the image."}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/avoiddecodeimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions","navigatorTitle":[{"text":"SDImageCacheOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheOptions","kind":"identifier"}],"title":"SDImageCacheOptions","abstract":[{"text":"Image Cache Options","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"path":"\/metadata\/platforms","op":"replace","value":[{"deprecated":false,"beta":false,"deprecatedAt":"8.0","introducedAt":"8.0","name":"iOS","unavailable":false},{"deprecatedAt":"8.0","unavailable":false,"deprecated":false,"beta":false,"name":"iPadOS","introducedAt":"8.0"},{"introducedAt":"8.0","deprecatedAt":"8.0","unavailable":false,"name":"Mac Catalyst","deprecated":false,"beta":false}]},{"value":"Enumeration Case","op":"replace","path":"\/metadata\/roleHeading"},{"value":"SDImageCacheAvoidDecodeImage","op":"replace","path":"\/metadata\/title"},{"value":"case","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheAvoidDecodeImage"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"SDImageCacheAvoidDecodeImage","kind":"identifier"}],"platforms":["iOS"]}]}},{"op":"replace","value":"SDImageCacheAvoidDecodeImage","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1avoidDecodeImage\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1avoidDecodeImage\/fragments","op":"replace","value":[{"text":"SDImageCacheAvoidDecodeImage","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","op":"replace","value":"SDImageCacheOptions"},{"op":"replace","value":[{"text":"SDImageCacheOptions","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/navigatorTitle"}]}]}