{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/SetAlgebra-Implementations"]]},"abstract":[{"text":"Inherited from ","type":"text"},{"code":"SetAlgebra.isSuperset(of:)","type":"codeVoice"},{"text":".","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/issuperset(of:)"],"traits":[{"interfaceLanguage":"swift"}]}],"primaryContentSections":[{"declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"isSuperset","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"of"},{"kind":"text","text":" "},{"kind":"internalParam","text":"other"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/isSuperset(of:)","interfaceLanguage":"swift"},"sections":[],"metadata":{"modules":[{"name":"SDWebImage","relatedModules":["Swift"]}],"title":"isSuperset(of:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"isSuperset"},{"kind":"text","text":"("},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Self","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"s:s10SetAlgebraPsE10isSuperset2ofSbx_tF::SYNTHESIZED::c:@E@SDImageCacheOptions","symbolKind":"method","role":"symbol","extendedModule":"Swift"},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/isSuperset(of:)":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/issuperset(of:)","title":"isSuperset(of:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/isSuperset(of:)","abstract":[],"kind":"symbol","role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"isSuperset","kind":"identifier"},{"text":"(","kind":"text"},{"text":"of","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"Self"},{"kind":"text","text":") -> "},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions","navigatorTitle":[{"text":"SDImageCacheOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheOptions","kind":"identifier"}],"title":"SDImageCacheOptions","abstract":[{"text":"Image Cache Options","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/SetAlgebra-Implementations":{"kind":"article","url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/setalgebra-implementations","abstract":[],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/SetAlgebra-Implementations","role":"collectionGroup","title":"SetAlgebra Implementations"}},"variantOverrides":[{"patch":[{"value":"SDImageCacheOptions","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/navigatorTitle","value":[{"text":"SDImageCacheOptions","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}