{"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"type":"text","text":" context option (like using "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"code":"SDAnimatedImage","type":"codeVoice"},{"text":"), we may still use ","type":"text"},{"code":"UIImage","type":"codeVoice"},{"text":" when the memory cache hit, or image decoder is not available, to behave as a fallback solution.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Using this option, can ensure we always produce image with your provided class. If failed, an error with code "},{"code":"SDWebImageErrorBadImageData","type":"codeVoice"},{"text":" will be used.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Note this options is not compatible with "},{"type":"codeVoice","code":"SDImageCacheDecodeFirstFrameOnly"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/matchanimatedimageclass"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/matchanimatedimageclass"]}],"sections":[],"metadata":{"symbolKind":"property","externalID":"c:@E@SDImageCacheOptions@SDImageCacheMatchAnimatedImageClass","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"matchAnimatedImageClass"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:@E@SDImageCacheOptions","kind":"typeIdentifier","text":"SDImageCacheOptions"}],"title":"matchAnimatedImageClass","role":"symbol","roleHeading":"Type Property","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDImageCacheMatchAnimatedImageClass","kind":"identifier"}]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/matchAnimatedImageClass"},"kind":"symbol","primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"matchAnimatedImageClass","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","text":"SDImageCacheOptions"},{"text":" { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" }","kind":"text"}],"languages":["swift"]}]}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/matchAnimatedImageClass":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/matchanimatedimageclass","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/matchAnimatedImageClass","abstract":[{"type":"text","text":"By default, when you use "},{"type":"codeVoice","code":"SDWebImageContextAnimatedImageClass"},{"text":" context option (like using ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" which designed to use "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":"), we may still use "},{"code":"UIImage","type":"codeVoice"},{"type":"text","text":" when the memory cache hit, or image decoder is not available, to behave as a fallback solution."},{"type":"text","text":" "},{"text":"Using this option, can ensure we always produce image with your provided class. If failed, an error with code ","type":"text"},{"type":"codeVoice","code":"SDWebImageErrorBadImageData"},{"type":"text","text":" will be used."},{"type":"text","text":" "},{"text":"Note this options is not compatible with ","type":"text"},{"code":"SDImageCacheDecodeFirstFrameOnly","type":"codeVoice"},{"type":"text","text":", which always produce a UIImage\/NSImage."}],"kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"matchAnimatedImageClass","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDImageCacheOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"navigatorTitle":[{"text":"SDImageCacheMatchAnimatedImageClass","kind":"identifier"}],"role":"symbol","title":"matchAnimatedImageClass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"url":"\/documentation\/sdwebimage\/sdimagecacheoptions","navigatorTitle":[{"text":"SDImageCacheOptions","kind":"identifier"}],"kind":"symbol","role":"symbol","fragments":[{"text":"struct","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageCacheOptions","kind":"identifier"}],"title":"SDImageCacheOptions","abstract":[{"text":"Image Cache Options","type":"text"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","type":"topic"}},"variantOverrides":[{"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheMatchAnimatedImageClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDImageCacheMatchAnimatedImageClass","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"identifier","text":"SDImageCacheMatchAnimatedImageClass"}]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1matchAnimatedImageClass\/title","value":"SDImageCacheMatchAnimatedImageClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1matchAnimatedImageClass\/fragments","value":[{"text":"SDImageCacheMatchAnimatedImageClass","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","value":"SDImageCacheOptions"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments"},{"value":[{"kind":"identifier","text":"SDImageCacheOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/navigatorTitle"}],"traits":[{"interfaceLanguage":"occ"}]}]}