{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryDiskDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/querydiskdatasync"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/querydiskdatasync"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryDiskDataSync","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"By default, when the memory cache miss, we query the disk cache asynchronously. This mask can force to query disk cache (when memory cache miss) synchronously."},{"type":"text","text":" "},{"type":"text","text":"@note These 3 query options can be combined together. For the full list about these masks combination, see wiki page."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryDiskDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"title":"queryDiskDataSync","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@SDImageCacheOptions@SDImageCacheQueryDiskDataSync","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"role":"symbol","title":"SDImageCacheOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheOptions"}],"abstract":[{"type":"text","text":"Image Cache Options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheOptions"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/queryDiskDataSync":{"role":"symbol","title":"queryDiskDataSync","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryDiskDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, when the memory cache miss, we query the disk cache asynchronously. This mask can force to query disk cache (when memory cache miss) synchronously."},{"type":"text","text":" "},{"type":"text","text":"@note These 3 query options can be combined together. For the full list about these masks combination, see wiki page."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryDiskDataSync","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/querydiskdatasync"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheQueryDiskDataSync"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","value":"SDImageCacheOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments","value":[{"kind":"identifier","text":"SDImageCacheOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryDiskDataSync\/title","value":"SDImageCacheQueryDiskDataSync"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryDiskDataSync\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryDiskDataSync"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}