{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions","text":"SDImageCacheOptions"},{"kind":"text","text":" { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/querymemorydatasync"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimagecacheoptions\/querymemorydatasync"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryDataSync","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"By default, when you only specify "},{"type":"codeVoice","code":"SDImageCacheQueryMemoryData"},{"type":"text","text":", we query the memory image data asynchronously. Combined this mask as well to query the memory image data synchronously."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"title":"queryMemoryDataSync","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@E@SDImageCacheOptions@SDImageCacheQueryMemoryDataSync","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions":{"role":"symbol","title":"SDImageCacheOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheOptions"}],"abstract":[{"type":"text","text":"Image Cache Options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheOptions"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheOptions/queryMemoryDataSync":{"role":"symbol","title":"queryMemoryDataSync","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryMemoryDataSync"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheOptions","preciseIdentifier":"c:@E@SDImageCacheOptions"}],"abstract":[{"type":"text","text":"By default, when you only specify "},{"type":"codeVoice","code":"SDImageCacheQueryMemoryData"},{"type":"text","text":", we query the memory image data asynchronously. Combined this mask as well to query the memory image data synchronously."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheOptions\/queryMemoryDataSync","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}],"url":"\/documentation\/sdwebimage\/sdimagecacheoptions\/querymemorydatasync"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Enumeration Case"},{"op":"replace","path":"\/metadata\/title","value":"SDImageCacheQueryMemoryDataSync"},{"op":"replace","path":"\/metadata\/symbolKind","value":"case"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/title","value":"SDImageCacheOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions\/fragments","value":[{"kind":"identifier","text":"SDImageCacheOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryMemoryDataSync\/title","value":"SDImageCacheQueryMemoryDataSync"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheOptions~1queryMemoryDataSync\/fragments","value":[{"kind":"identifier","text":"SDImageCacheQueryMemoryDataSync"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}