{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"+ ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"cacheSerializerWithBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData *(^)(UIImage *, NSData *, NSURL *)","preciseIdentifier":"c:BF*$objc(cs)NSData(#*$objc(cs)UIImage#S2_#*$objc(cs)NSURL)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class\/cacheserializerwithblock:"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class\/cacheSerializerWithBlock:","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cacheSerializerWithBlock:"}],"title":"cacheSerializerWithBlock:","roleHeading":"Type Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImageCacheSerializer(cm)cacheSerializerWithBlock:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"cacheSerializerWithBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializer-swift.class/cacheSerializerWithBlock:":{"role":"symbol","title":"cacheSerializerWithBlock:","fragments":[{"kind":"text","text":"+ "},{"kind":"identifier","text":"cacheSerializerWithBlock:"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class\/cacheSerializerWithBlock:","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cacheSerializerWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class\/cacheserializerwithblock:"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializer-swift.class":{"role":"symbol","title":"SDWebImageCacheSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"abstract":[{"type":"text","text":"A cache serializer class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"url":"\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/title","value":"SDWebImageCacheSerializer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}