{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerBlock","preciseIdentifier":"c:SDWebImageCacheSerializer.h@T@SDWebImageCacheSerializerBlock","text":"SDWebImageCacheSerializerBlock"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class\/init(block:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class\/init(block:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class\/init(block:)","interfaceLanguage":"swift"},"kind":"symbol","metadata":{"fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageCacheSerializerBlock","preciseIdentifier":"c:SDWebImageCacheSerializer.h@T@SDWebImageCacheSerializerBlock"},{"kind":"text","text":")"}],"title":"init(block:)","roleHeading":"Initializer","role":"symbol","symbolKind":"init","externalID":"c:objc(cs)SDWebImageCacheSerializer(im)initWithBlock:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializerBlock":{"role":"symbol","title":"SDWebImageCacheSerializerBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheSerializerBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializerBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheSerializerBlock"}],"url":"\/documentation\/sdwebimage\/sdwebimagecacheserializerblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializer-swift.class/init(block:)":{"role":"symbol","title":"init(block:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"block"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageCacheSerializerBlock","preciseIdentifier":"c:SDWebImageCacheSerializer.h@T@SDWebImageCacheSerializerBlock"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class\/init(block:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"initWithBlock:"}],"url":"\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class\/init(block:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheSerializer-swift.class":{"role":"symbol","title":"SDWebImageCacheSerializer","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"abstract":[{"type":"text","text":"A cache serializer class with block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheSerializer-swift.class","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}],"url":"\/documentation\/sdwebimage\/sdwebimagecacheserializer-swift.class"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"initWithBlock:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"keyword","text":"id"},{"kind":"text","text":") "},{"kind":"identifier","text":"initWithBlock:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSData *(^)(UIImage *, NSData *, NSURL *)","preciseIdentifier":"c:BF*$objc(cs)NSData(#*$objc(cs)UIImage#S2_#*$objc(cs)NSURL)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"block"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerBlock\/title","value":"SDWebImageCacheSerializerBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializerBlock\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheSerializerBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class~1init(block:)\/title","value":"initWithBlock:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class~1init(block:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithBlock:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/title","value":"SDWebImageCacheSerializer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheSerializer-swift.class\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheSerializer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}