{"sections":[],"schemaVersion":{"patch":0,"minor":3,"major":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/init(config:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/init(config:)"]}],"metadata":{"externalID":"c:objc(pl)SDMemoryCache(im)initWithConfig:","fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"config"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"modules":[{"name":"SDWebImage"}],"required":true,"navigatorTitle":[{"text":"initWithConfig:","kind":"identifier"}],"roleHeading":"Initializer","symbolKind":"init","title":"init(config:)","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"init"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"typeIdentifier"},{"text":")","kind":"text"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"name":"config","content":[{"inlineContent":[{"text":"The cache config to be used to create the cache.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/init(config:)"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol"]]},"kind":"symbol","abstract":[{"type":"text","text":"Create a new memory cache instance with the specify cache config. You can check "},{"code":"maxMemoryCost","type":"codeVoice"},{"text":" and ","type":"text"},{"type":"codeVoice","code":"maxMemoryCount"},{"type":"text","text":" used for memory cache."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"title":"SDMemoryCacheProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","abstract":[{"type":"text","text":"A protocol to allow custom memory cache used in SDImageCache."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol/init(config:)":{"type":"topic","fragments":[{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"config","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","text":"SDImageCacheConfig"},{"text":")","kind":"text"}],"title":"init(config:)","kind":"symbol","abstract":[{"text":"Create a new memory cache instance with the specify cache config. You can check ","type":"text"},{"code":"maxMemoryCost","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"maxMemoryCount","type":"codeVoice"},{"type":"text","text":" used for memory cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/init(config:)","required":true,"role":"symbol","navigatorTitle":[{"text":"initWithConfig:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol\/init(config:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheConfig":{"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdimagecacheconfig","title":"SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheConfig"}],"type":"topic","abstract":[{"type":"text","text":"The class contains all the config for image cache"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDImageCacheConfig","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","value":"initWithConfig:","op":"replace"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"initWithConfig:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:*Qo","text":"id","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"text":"initWithConfig:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDImageCacheConfig","preciseIdentifier":"c:objc(cs)SDImageCacheConfig","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheConfig","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"text":"config","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0","op":"replace"},{"path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"config","content":[{"inlineContent":[{"type":"text","text":"The cache config to be used to create the cache."}],"type":"paragraph"}]}]},"op":"replace"},{"value":{"kind":"content","content":[{"text":"Return Value","anchor":"return-value","type":"heading","level":2},{"inlineContent":[{"type":"text","text":"The new memory cache instance."}],"type":"paragraph"}]},"op":"add","path":"\/primaryContentSections\/2"},{"value":"SDMemoryCache","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/title"},{"value":[{"kind":"identifier","text":"SDMemoryCache"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/navigatorTitle","value":[{"text":"SDMemoryCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1init(config:)\/title","op":"replace","value":"initWithConfig:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1init(config:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"initWithConfig:"}],"op":"replace"},{"op":"replace","value":"SDImageCacheConfig","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/fragments","value":[{"text":"SDImageCacheConfig","kind":"identifier"}]},{"value":[{"text":"SDImageCacheConfig","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheConfig\/navigatorTitle","op":"replace"}]}]}