{"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"removeObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"forKey"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"key"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The key identifying the value to be removed. If nil, this method has no effect.","type":"text"}],"type":"paragraph"}],"name":"key"}],"kind":"parameters"}],"metadata":{"required":true,"externalID":"c:objc(pl)SDMemoryCache(im)removeObjectForKey:","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"removeObject"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"modules":[{"name":"SDWebImage"}],"symbolKind":"method","title":"removeObject(forKey:)","role":"symbol","roleHeading":"Instance Method","navigatorTitle":[{"text":"removeObjectForKey:","kind":"identifier"}]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/removeObject(forKey:)","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/removeobject(forkey:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/removeobject(forkey:)"]}],"sections":[],"abstract":[{"text":"Removes the value of the specified key in the cache.","type":"text"}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol/removeObject(forKey:)":{"navigatorTitle":[{"text":"removeObjectForKey:","kind":"identifier"}],"abstract":[{"text":"Removes the value of the specified key in the cache.","type":"text"}],"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"removeObject","kind":"identifier"},{"text":"(","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":")","kind":"text"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol\/removeobject(forkey:)","type":"topic","required":true,"title":"removeObject(forKey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/removeObject(forKey:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"title":"SDMemoryCacheProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","abstract":[{"type":"text","text":"A protocol to allow custom memory cache used in SDImageCache."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"removeObjectForKey:","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"text":"- ","kind":"text"},{"text":"removeObjectForKey:","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"path":"\/topicSections","value":null,"op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"tokens":[{"text":"- (","kind":"text"},{"preciseIdentifier":"c:v","text":"void","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"removeObjectForKey:","kind":"identifier"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"id","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}],"platforms":["iOS"]}]}},{"op":"replace","value":{"parameters":[{"name":"key","content":[{"inlineContent":[{"text":"The key identifying the value to be removed. If nil, this method has no effect.","type":"text"}],"type":"paragraph"}]}],"kind":"parameters"},"path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1removeObject(forKey:)\/title","value":"removeObjectForKey:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1removeObject(forKey:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"removeObjectForKey:"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/title","value":"SDMemoryCache","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDMemoryCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/navigatorTitle","value":[{"text":"SDMemoryCache","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}