{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setObject"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"object"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":" "},{"kind":"internalParam","text":"key"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"objects that are put into it."}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/setobject(_:forkey:cost:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/setobject(_:forkey:cost:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/setObject(_:forKey:cost:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Sets the value of the specified key in the cache, and associates the key-value"},{"type":"text","text":" "},{"type":"text","text":"pair with the specified cost."}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"setObject:forKey:cost:"}],"role":"symbol","title":"setObject(_:forKey:cost:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"symbolKind":"method","externalID":"c:objc(pl)SDMemoryCache(im)setObject:forKey:cost:","required":true,"modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol/setObject(_:forKey:cost:)":{"navigatorTitle":[{"kind":"identifier","text":"setObject:forKey:cost:"}],"role":"symbol","title":"setObject(_:forKey:cost:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"setObject"},{"kind":"text","text":"("},{"kind":"keyword","text":"Any"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"forKey"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":", "},{"kind":"externalParam","text":"cost"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Sets the value of the specified key in the cache, and associates the key-value"},{"type":"text","text":" "},{"type":"text","text":"pair with the specified cost."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/setObject(_:forKey:cost:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol\/setobject(_:forkey:cost:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol":{"role":"symbol","title":"SDMemoryCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDMemoryCacheProtocol"}],"abstract":[{"type":"text","text":"A protocol to allow custom memory cache used in SDImageCache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDMemoryCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"setObject:forKey:cost:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setObject:forKey:cost:"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"void","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"kind":"identifier","text":"setObject:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"object"},{"kind":"text","text":" "},{"kind":"identifier","text":"forKey:"},{"kind":"text","text":"("},{"kind":"keyword","text":"id"},{"kind":"text","text":")"},{"kind":"internalParam","text":"key"},{"kind":"text","text":" "},{"kind":"identifier","text":"cost:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSUInteger","preciseIdentifier":"c:@T@NSUInteger"},{"kind":"text","text":")"},{"kind":"internalParam","text":"cost"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1setObject(_:forKey:cost:)\/title","value":"setObject:forKey:cost:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1setObject(_:forKey:cost:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"setObject:forKey:cost:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/title","value":"SDMemoryCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDMemoryCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}