{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"setObject","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"text":" ","kind":"text"},{"text":"object","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"?, ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":" "},{"text":"key","kind":"internalParam"},{"kind":"text","text":": "},{"kind":"keyword","text":"Any"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The object to be stored in the cache. If nil, it calls "},{"type":"codeVoice","code":"removeObjectForKey:"},{"text":".","type":"text"}]}],"name":"object"},{"name":"key","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The key with which to associate the value. If nil, this method has no effect."}]}]}],"kind":"parameters"},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"inlineContent":[{"text":"Unlike an NSMutableDictionary object, a cache does not copy the key","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"objects that are put into it."}],"type":"paragraph"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/setObject(_:forKey:)","interfaceLanguage":"swift"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/setobject(_:forkey:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdmemorycacheprotocol\/setobject(_:forkey:)"]}],"metadata":{"required":true,"role":"symbol","modules":[{"name":"SDWebImage"}],"externalID":"c:objc(pl)SDMemoryCache(im)setObject:forKey:","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"setObject","kind":"identifier"},{"kind":"text","text":"("},{"text":"Any","kind":"keyword"},{"text":"?, ","kind":"text"},{"text":"forKey","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":")","kind":"text"}],"navigatorTitle":[{"text":"setObject:forKey:","kind":"identifier"}],"title":"setObject(_:forKey:)","roleHeading":"Instance Method","symbolKind":"method"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol"]]},"schemaVersion":{"minor":3,"major":0,"patch":0},"sections":[],"kind":"symbol","abstract":[{"text":"Sets the value of the specified key in the cache (0 cost).","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol":{"fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"title":"SDMemoryCacheProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol","abstract":[{"type":"text","text":"A protocol to allow custom memory cache used in SDImageCache."}],"kind":"symbol","type":"topic","role":"symbol","navigatorTitle":[{"text":"SDMemoryCacheProtocol","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDMemoryCacheProtocol/setObject(_:forKey:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"setObject"},{"text":"(","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"?, "},{"text":"forKey","kind":"externalParam"},{"kind":"text","text":": "},{"text":"Any","kind":"keyword"},{"kind":"text","text":")"}],"title":"setObject(_:forKey:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDMemoryCacheProtocol\/setObject(_:forKey:)","type":"topic","kind":"symbol","required":true,"role":"symbol","navigatorTitle":[{"text":"setObject:forKey:","kind":"identifier"}],"abstract":[{"type":"text","text":"Sets the value of the specified key in the cache (0 cost)."}],"url":"\/documentation\/sdwebimage\/sdmemorycacheprotocol\/setobject(_:forkey:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"value":"setObject:forKey:","op":"replace","path":"\/metadata\/title"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setObject:forKey:"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"setObject:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"object","kind":"internalParam"},{"kind":"text","text":" "},{"text":"forKey:","kind":"identifier"},{"kind":"text","text":"("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"kind":"internalParam","text":"key"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"object","content":[{"inlineContent":[{"type":"text","text":"The object to be stored in the cache. If nil, it calls "},{"type":"codeVoice","code":"removeObjectForKey:"},{"text":".","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The key with which to associate the value. If nil, this method has no effect.","type":"text"}],"type":"paragraph"}],"name":"key"}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/title","op":"replace","value":"SDMemoryCache"},{"value":[{"kind":"identifier","text":"SDMemoryCache"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol\/navigatorTitle","op":"replace","value":[{"text":"SDMemoryCache","kind":"identifier"}]},{"op":"replace","value":"setObject:forKey:","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1setObject(_:forKey:)\/title"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"setObject:forKey:"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDMemoryCacheProtocol~1setObject(_:forKey:)\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}