{"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"keyword"},{"text":"(","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"text":"CIFilter","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)CIFilter"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimagefiltertransformer\/init(filter:)"]},{"paths":["\/documentation\/sdwebimage\/sdimagefiltertransformer\/init(filter:)"],"traits":[{"interfaceLanguage":"occ"}]}],"metadata":{"roleHeading":"Initializer","navigatorTitle":[{"text":"transformerWithFilter:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"symbolKind":"init","externalID":"c:objc(cs)SDImageFilterTransformer(cm)transformerWithFilter:","title":"init(filter:)","fragments":[{"kind":"keyword","text":"convenience"},{"text":" ","kind":"text"},{"text":"init","kind":"identifier"},{"text":"(","kind":"text"},{"text":"filter","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:objc(cs)CIFilter","text":"CIFilter","kind":"typeIdentifier"},{"kind":"text","text":")"}],"role":"symbol"},"kind":"symbol","schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/init(filter:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer/init(filter:)":{"kind":"symbol","navigatorTitle":[{"text":"transformerWithFilter:","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer\/init(filter:)","title":"init(filter:)","abstract":[],"fragments":[{"text":"convenience","kind":"keyword"},{"kind":"text","text":" "},{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"filter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"CIFilter","preciseIdentifier":"c:objc(cs)CIFilter"},{"text":")","kind":"text"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer\/init(filter:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageFilterTransformer":{"kind":"symbol","navigatorTitle":[{"text":"SDImageFilterTransformer","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdimagefiltertransformer","title":"SDImageFilterTransformer","abstract":[{"text":"Core Image filter transformer","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageFilterTransformer"}],"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageFilterTransformer","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"value":"Type Method","op":"replace","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"transformerWithFilter:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"+ ","kind":"text"},{"text":"transformerWithFilter:","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"+ (","kind":"text"},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"kind":"text","text":") "},{"text":"transformerWithFilter:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)CIFilter","text":"CIFilter","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"filter"},{"kind":"text","text":";"}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer~1init(filter:)\/title","op":"replace","value":"transformerWithFilter:"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer~1init(filter:)\/fragments","value":[{"kind":"text","text":"+ "},{"text":"transformerWithFilter:","kind":"identifier"}],"op":"replace"},{"op":"replace","value":"SDImageFilterTransformer","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/fragments","op":"replace","value":[{"text":"SDImageFilterTransformer","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageFilterTransformer\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageFilterTransformer"}]}]}]}