{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/animatedimageclass"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/animatedimageclass"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/animatedImageClass","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A Class object which the instance is a "},{"type":"codeVoice","code":"UIImage\/NSImage"},{"type":"text","text":" subclass and adopt "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol. We will call "},{"type":"codeVoice","code":"initWithData:scale:options:"},{"type":"text","text":" to create the instance (or "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" when using progressive download) . If the instance create failed, fallback to normal "},{"type":"codeVoice","code":"UIImage\/NSImage"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This can be used to improve animated images rendering performance (especially memory usage on big animated images) with "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" (Class)."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"title":"animatedImageClass","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDWebImageContextAnimatedImageClass","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/animatedImageClass":{"role":"symbol","title":"animatedImageClass","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"animatedImageClass"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A Class object which the instance is a "},{"type":"codeVoice","code":"UIImage\/NSImage"},{"type":"text","text":" subclass and adopt "},{"type":"codeVoice","code":"SDAnimatedImage"},{"type":"text","text":" protocol. We will call "},{"type":"codeVoice","code":"initWithData:scale:options:"},{"type":"text","text":" to create the instance (or "},{"type":"codeVoice","code":"initWithAnimatedCoder:scale:"},{"type":"text","text":" when using progressive download) . If the instance create failed, fallback to normal "},{"type":"codeVoice","code":"UIImage\/NSImage"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"This can be used to improve animated images rendering performance (especially memory usage on big animated images) with "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"type":"text","text":" (Class)."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/animatedImageClass","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/animatedimageclass"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextAnimatedImageClass"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1animatedImageClass\/title","value":"SDWebImageContextAnimatedImageClass"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1animatedImageClass\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextAnimatedImageClass"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}