{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/callbackQueue","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/callbackqueue"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/callbackqueue"],"traits":[{"interfaceLanguage":"occ"}]}],"sections":[],"kind":"symbol","abstract":[{"type":"text","text":"A "},{"code":"SDCallbackQueue","type":"codeVoice"},{"text":" instance which controls the ","type":"text"},{"type":"codeVoice","code":"Cache"},{"text":"\/","type":"text"},{"code":"Manager","type":"codeVoice"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"type":"text","text":"’s callback queue for their completionBlock."},{"type":"text","text":" "},{"text":"This is useful for user who call these 3 components in non-main queue and want to avoid callback in main queue.","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"metadata":{"roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDWebImageContextCallbackQueue","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDWebImageContextCallbackQueue","kind":"identifier"}],"extendedModule":"SDWebImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callbackQueue","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"title":"callbackQueue"},"primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callbackQueue","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"platforms":["iOS"],"languages":["swift"]}],"kind":"declarations"},{"content":[{"anchor":"discussion","level":2,"text":"Discussion","type":"heading"},{"style":"note","name":"Note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"For UI callback ("},{"type":"codeVoice","code":"sd_setImageWithURL"},{"text":"), we will still use main queue to dispatch, means if you specify a global queue, it will enqueue from the global queue to main queue.","type":"text"}]}]},{"type":"aside","name":"Note","style":"note","content":[{"inlineContent":[{"text":"This does not effect the components’ working queue (for example, ","type":"text"},{"type":"codeVoice","code":"Cache"},{"type":"text","text":" still query disk on internal ioQueue, "},{"code":"Loader","type":"codeVoice"},{"text":" still do network on URLSessionConfiguration.delegateQueue), change those config if you need.","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil. Which means main queue."}],"type":"paragraph"}]}],"kind":"content"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/callbackQueue":{"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/callbackqueue","type":"topic","title":"callbackQueue","abstract":[{"text":"A ","type":"text"},{"type":"codeVoice","code":"SDCallbackQueue"},{"text":" instance which controls the ","type":"text"},{"code":"Cache","type":"codeVoice"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"Manager"},{"type":"text","text":"\/"},{"code":"Loader","type":"codeVoice"},{"text":"’s callback queue for their completionBlock.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"This is useful for user who call these 3 components in non-main queue and want to avoid callback in main queue."}],"navigatorTitle":[{"text":"SDWebImageContextCallbackQueue","kind":"identifier"}],"role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/callbackQueue","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"callbackQueue","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","value":"SDWebImageContextCallbackQueue","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"var","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageContextCallbackQueue","kind":"identifier"}]},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextCallbackQueue"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]}},{"value":"SDWebImageContextCallbackQueue","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1callbackQueue\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1callbackQueue\/fragments","value":[{"text":"SDWebImageContextCallbackQueue","kind":"identifier"}]},{"value":"SDWebImageContextOption","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title"},{"op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]}]}]}