{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadDecryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/downloaddecryptor"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/downloaddecryptor"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadDecryptor","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to decrypt the image download data. This can be used for image data decryption, such as Base64 encoded image. If you provide one, it will ignore the "},{"type":"codeVoice","code":"decryptor"},{"type":"text","text":" in downloader and use provided one instead. (id"},{"type":"text","text":")"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadDecryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"title":"downloadDecryptor","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDWebImageContextDownloadDecryptor","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/downloadDecryptor":{"role":"symbol","title":"downloadDecryptor","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"downloadDecryptor"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance to decrypt the image download data. This can be used for image data decryption, such as Base64 encoded image. If you provide one, it will ignore the "},{"type":"codeVoice","code":"decryptor"},{"type":"text","text":" in downloader and use provided one instead. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/downloadDecryptor","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/downloaddecryptor"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextDownloadDecryptor"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadDecryptor\/title","value":"SDWebImageContextDownloadDecryptor"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1downloadDecryptor\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextDownloadDecryptor"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}