{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"kind":"symbol","sections":[],"metadata":{"roleHeading":"Type Property","externalID":"c:@SDWebImageContextImageTypeIdentifierHint","extendedModule":"SDWebImage","navigatorTitle":[{"text":"SDWebImageContextImageTypeIdentifierHint","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"imageTypeIdentifierHint","symbolKind":"property","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageTypeIdentifierHint","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier","text":"SDWebImageContextOption"}]},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTypeIdentifierHint"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier","text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","anchor":"discussion","level":2},{"name":"Note","style":"note","content":[{"inlineContent":[{"type":"text","text":"If you don’t provide this option, we will use the "},{"code":"URL.path","type":"codeVoice"},{"type":"text","text":" as file extension to calculate the UTI hint"}],"type":"paragraph"}],"type":"aside"},{"name":"Note","style":"note","type":"aside","content":[{"type":"paragraph","inlineContent":[{"text":"If you really don’t want any hint which effect the image result, pass ","type":"text"},{"type":"codeVoice","code":"NSNull.null"},{"text":" instead","type":"text"}]}]}],"kind":"content"}],"abstract":[{"type":"text","text":"A NSString value (UTI) indicating the source image’s file extension. Example: “public.jpeg-2000”, “com.nikon.raw-image”, “public.tiff”"},{"text":" ","type":"text"},{"type":"text","text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF"},{"text":" ","type":"text"},{"type":"text","text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetypeidentifierhint"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetypeidentifierhint"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTypeIdentifierHint","interfaceLanguage":"swift"},"schemaVersion":{"minor":3,"patch":0,"major":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageTypeIdentifierHint":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageTypeIdentifierHint"}],"title":"imageTypeIdentifierHint","kind":"symbol","abstract":[{"type":"text","text":"A NSString value (UTI) indicating the source image’s file extension. Example: “public.jpeg-2000”, “com.nikon.raw-image”, “public.tiff”"},{"type":"text","text":" "},{"text":"Some image file format share the same data structure but has different tag explanation, like TIFF and NEF\/SRW, see https:\/\/en.wikipedia.org\/wiki\/TIFF","type":"text"},{"type":"text","text":" "},{"type":"text","text":"Changing the file extension cause the different image result. The coder (like ImageIO) may use file extension to choose the correct parser"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTypeIdentifierHint","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageTypeIdentifierHint","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetypeidentifierhint","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]}},"variantOverrides":[{"patch":[{"value":"occ","path":"\/identifier\/interfaceLanguage","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageContextImageTypeIdentifierHint"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","value":[{"text":"SDWebImageContextImageTypeIdentifierHint","kind":"identifier"}],"path":"\/metadata\/fragments"},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","op":"add","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImageContextImageTypeIdentifierHint","kind":"identifier"},{"kind":"text","text":";"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTypeIdentifierHint\/title","value":"SDWebImageContextImageTypeIdentifierHint","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTypeIdentifierHint\/fragments","value":[{"text":"SDWebImageContextImageTypeIdentifierHint","kind":"identifier"}]},{"op":"replace","value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title"},{"value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}