{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"abstract":[{"text":"A Dictionary (SDImageCoderOptions) value, which pass the extra decoding options to the SDImageCoder. Introduced in SDWebImage 5.14.0","type":"text"},{"type":"text","text":" "},{"type":"text","text":"You can pass additional decoding related options to the decoder, extensible and control by you. And pay attention this dictionary may be retained by decoded image via "},{"type":"codeVoice","code":"UIImage.sd_decodeOptions"},{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"This context option replace the deprecated "},{"code":"SDImageCoderWebImageContext","type":"codeVoice"},{"type":"text","text":", which may cause retain cycle (cache -> image -> options -> context -> cache)"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageDecodeOptions","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"}]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","level":2,"anchor":"discussion","type":"heading"},{"style":"note","name":"Note","type":"aside","content":[{"inlineContent":[{"type":"text","text":"There are already individual options below like "},{"type":"codeVoice","code":".imageScaleFactor"},{"type":"text","text":", "},{"code":".imagePreserveAspectRatio","type":"codeVoice"},{"text":", each of individual options will override the same filed for this dictionary.","type":"text"}],"type":"paragraph"}]}]}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodeoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodeoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeOptions","interfaceLanguage":"swift"},"metadata":{"extendedModule":"SDWebImage","title":"imageDecodeOptions","externalID":"c:@SDWebImageContextImageDecodeOptions","symbolKind":"property","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageDecodeOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"SDWebImageContextImageDecodeOptions","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"role":"symbol"},"schemaVersion":{"minor":3,"major":0,"patch":0},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageDecodeOptions":{"navigatorTitle":[{"text":"SDWebImageContextImageDecodeOptions","kind":"identifier"}],"title":"imageDecodeOptions","kind":"symbol","abstract":[{"text":"A Dictionary (SDImageCoderOptions) value, which pass the extra decoding options to the SDImageCoder. Introduced in SDWebImage 5.14.0","type":"text"},{"type":"text","text":" "},{"text":"You can pass additional decoding related options to the decoder, extensible and control by you. And pay attention this dictionary may be retained by decoded image via ","type":"text"},{"code":"UIImage.sd_decodeOptions","type":"codeVoice"},{"type":"text","text":""},{"text":" ","type":"text"},{"type":"text","text":"This context option replace the deprecated "},{"type":"codeVoice","code":"SDImageCoderWebImageContext"},{"type":"text","text":", which may cause retain cycle (cache -> image -> options -> context -> cache)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeOptions","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageDecodeOptions"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodeoptions","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"path":"\/metadata\/title","value":"SDWebImageContextImageDecodeOptions","op":"replace"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"value":[{"kind":"identifier","text":"SDWebImageContextImageDecodeOptions"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"SDWebImageContextImageDecodeOptions","kind":"identifier"},{"text":";","kind":"text"}]}],"kind":"declarations"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageDecodeOptions\/title","value":"SDWebImageContextImageDecodeOptions","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageDecodeOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageDecodeOptions"}]},{"value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","op":"replace"}]}]}