{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTransformer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetransformer"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetransformer"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTransformer","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms "},{"type":"codeVoice","code":"SDImageTransformer"},{"type":"text","text":" protocol. It’s used for image transform after the image load finished and store the transformed image to cache. If you provide one, it will ignore the "},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" in manager and use provided one instead. If you pass NSNull, the transformer feature will be disabled. (id"},{"type":"text","text":")"}],"kind":"symbol","metadata":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageTransformer"}],"role":"symbol","title":"imageTransformer","roleHeading":"Type Property","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTransformer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"symbolKind":"property","externalID":"c:@SDWebImageContextImageTransformer","extendedModule":"SDWebImage","modules":[{"name":"SDWebImage"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageTransformer":{"role":"symbol","title":"imageTransformer","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageTransformer"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms "},{"type":"codeVoice","code":"SDImageTransformer"},{"type":"text","text":" protocol. It’s used for image transform after the image load finished and store the transformed image to cache. If you provide one, it will ignore the "},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" in manager and use provided one instead. If you pass NSNull, the transformer feature will be disabled. (id"},{"type":"text","text":")"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageTransformer","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageTransformer"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagetransformer"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextImageTransformer"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageTransformer"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextImageTransformer"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTransformer\/title","value":"SDWebImageContextImageTransformer"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageTransformer\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageTransformer"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}