{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagecoder"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagecoder"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCoder","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms to "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" protocol. It’s used to override the default image coder for image decoding(including progressive) and encoding during the image loading process."},{"type":"text","text":" "},{"type":"text","text":"If you use this context option, we will not always use "},{"type":"codeVoice","code":"SDImageCodersManager.shared"},{"type":"text","text":" to loop through all registered coders and find the suitable one. Instead, we will arbitrarily use the exact provided coder without extra checking (We may not call "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":")."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"title":"imageCoder","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDWebImageContextImageCoder","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageCoder"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageCoder":{"role":"symbol","title":"imageCoder","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageCoder"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A id"},{"type":"text","text":" instance which conforms to "},{"type":"codeVoice","code":"SDImageCoder"},{"type":"text","text":" protocol. It’s used to override the default image coder for image decoding(including progressive) and encoding during the image loading process."},{"type":"text","text":" "},{"type":"text","text":"If you use this context option, we will not always use "},{"type":"codeVoice","code":"SDImageCodersManager.shared"},{"type":"text","text":" to loop through all registered coders and find the suitable one. Instead, we will arbitrarily use the exact provided coder without extra checking (We may not call "},{"type":"codeVoice","code":"canDecodeFromData:"},{"type":"text","text":")."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageCoder","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageCoder"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagecoder"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextImageCoder"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageCoder"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextImageCoder"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageCoder\/title","value":"SDWebImageContextImageCoder"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageCoder\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageCoder"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}