{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageThumbnailPixelSize"},"metadata":{"externalID":"c:@SDWebImageContextImageThumbnailPixelSize","title":"imageThumbnailPixelSize","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"imageThumbnailPixelSize","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"symbolKind":"property","modules":[{"name":"SDWebImage"}],"roleHeading":"Type Property","navigatorTitle":[{"text":"SDWebImageContextImageThumbnailPixelSize","kind":"identifier"}],"extendedModule":"SDWebImage","role":"symbol"},"primaryContentSections":[{"kind":"declarations","declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"imageThumbnailPixelSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","text":"SDWebImageContextOption"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"When you pass "},{"type":"codeVoice","code":".preserveAspectRatio == NO"},{"type":"text","text":", the thumbnail image is stretched to match each dimension. When "},{"code":".preserveAspectRatio == YES","type":"codeVoice"},{"type":"text","text":", the thumbnail image’s width is limited to pixel size’s width, the thumbnail image’s height is limited to pixel size’s height. For common cases, you can just pass a square size to limit both."},{"type":"text","text":" "},{"type":"text","text":"Defaults to CGSizeZero, which means no thumbnail generation at all. (NSValue)"}]}],"type":"aside","name":"Note","style":"note"},{"style":"note","name":"Note","content":[{"inlineContent":[{"text":"When this value is used, we will trigger thumbnail decoding for url, and the callback’s data ","type":"text"},{"type":"strong","inlineContent":[{"text":"will be nil","type":"text"}]},{"type":"text","text":" (because this time the data saved to disk does not match the image return to you. If you need full size data, query the cache with full size url key)"}],"type":"paragraph"}],"type":"aside"}],"kind":"content"}],"abstract":[{"type":"text","text":"A CGSize raw value indicating whether or not to generate the thumbnail images (or bitmap images from vector format). When this value is provided, the decoder will generate a thumbnail image which pixel size is smaller than or equal to (depends the "},{"code":".imagePreserveAspectRatio","type":"codeVoice"},{"type":"text","text":") the value size."}],"sections":[],"schemaVersion":{"minor":3,"major":0,"patch":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagethumbnailpixelsize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagethumbnailpixelsize"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageThumbnailPixelSize":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageThumbnailPixelSize"}],"abstract":[{"text":"A CGSize raw value indicating whether or not to generate the thumbnail images (or bitmap images from vector format). When this value is provided, the decoder will generate a thumbnail image which pixel size is smaller than or equal to (depends the ","type":"text"},{"type":"codeVoice","code":".imagePreserveAspectRatio"},{"type":"text","text":") the value size."}],"title":"imageThumbnailPixelSize","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageThumbnailPixelSize","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagethumbnailpixelsize","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"text":"imageThumbnailPixelSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"}],"type":"topic","kind":"symbol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextImageThumbnailPixelSize"},{"path":"\/metadata\/symbolKind","op":"replace","value":"var"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"SDWebImageContextImageThumbnailPixelSize","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"path":"\/relationshipsSections","op":"add"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextImageThumbnailPixelSize"},{"text":";","kind":"text"}]}],"kind":"declarations"}},{"value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]},{"value":"SDWebImageContextImageThumbnailPixelSize","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageThumbnailPixelSize\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageThumbnailPixelSize\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageThumbnailPixelSize"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}