{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeToHDR"},"metadata":{"modules":[{"name":"SDWebImage"}],"role":"symbol","roleHeading":"Type Property","symbolKind":"property","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageDecodeToHDR"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageDecodeToHDR"}],"externalID":"c:@SDWebImageContextImageDecodeToHDR","extendedModule":"SDWebImage","title":"imageDecodeToHDR"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"imageDecodeToHDR"},{"kind":"text","text":": "},{"text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}]}]},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"content":[{"type":"paragraph","inlineContent":[{"text":"Supported by iOS 17 and above when using ImageIO coder (third-party coder can support lower firmware)","type":"text"},{"text":" ","type":"text"},{"type":"text","text":"Defaults to @(NO), decoder will automatically convert SDR."}]}],"type":"aside","name":"Note","style":"note"}],"kind":"content"}],"abstract":[{"text":"A Boolean value (NSNumber) to provide converting to HDR during decoding. Currently if number is 0, use SDR, else use HDR. But we may extend this option to use ","type":"text"},{"code":"NSUInteger","type":"codeVoice"},{"type":"text","text":" in the future (means, think this options as int number, but not actual boolean)"}],"sections":[],"schemaVersion":{"major":0,"minor":3,"patch":0},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodetohdr"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodetohdr"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageDecodeToHDR":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextImageDecodeToHDR"}],"abstract":[{"type":"text","text":"A Boolean value (NSNumber) to provide converting to HDR during decoding. Currently if number is 0, use SDR, else use HDR. But we may extend this option to use "},{"type":"codeVoice","code":"NSUInteger"},{"text":" in the future (means, think this options as int number, but not actual boolean)","type":"text"}],"title":"imageDecodeToHDR","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageDecodeToHDR","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagedecodetohdr","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageDecodeToHDR","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageContextImageDecodeToHDR"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageContextImageDecodeToHDR","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSString","text":"NSString"},{"kind":"text","text":" * "},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageContextImageDecodeToHDR"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption","op":"replace"},{"value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageDecodeToHDR\/title","value":"SDWebImageContextImageDecodeToHDR","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageDecodeToHDR\/fragments","value":[{"text":"SDWebImageContextImageDecodeToHDR","kind":"identifier"}]}]}]}