{"metadata":{"symbolKind":"property","externalID":"c:@SDWebImageContextImageScaleDownLimitBytes","role":"symbol","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"SDWebImageContextImageScaleDownLimitBytes","kind":"identifier"}],"title":"imageScaleDownLimitBytes","roleHeading":"Type Property","fragments":[{"text":"static","kind":"keyword"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"imageScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"extendedModule":"SDWebImage"},"abstract":[{"text":"A NSUInteger value to provide the limit bytes during decoding. This can help to avoid OOM on large frame count animated image or large pixel static image when you don’t know how much RAM it occupied before decoding","type":"text"},{"text":" ","type":"text"},{"text":"The decoder will do these logic based on limit bytes:","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"imageScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","text":"SDWebImageContextOption"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"type":"heading","anchor":"discussion","level":2,"text":"Discussion"},{"type":"orderedList","items":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Get the total frame count (static image means 1)"}]}]},{"content":[{"inlineContent":[{"type":"text","text":"Calculate the "},{"type":"codeVoice","code":"framePixelSize"},{"text":" width\/height to ","type":"text"},{"code":"sqrt(limitBytes \/ frameCount \/ bytesPerPixel)","type":"codeVoice"},{"text":", keeping aspect ratio (at least 1x1)","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"If the "},{"code":"framePixelSize < originalImagePixelSize","type":"codeVoice"},{"text":", then do thumbnail decoding (see ","type":"text"},{"type":"codeVoice","code":"SDImageCoderDecodeThumbnailPixelSize"},{"text":") use the ","type":"text"},{"code":"framePixelSize","type":"codeVoice"},{"text":" and ","type":"text"},{"code":"preseveAspectRatio = YES","type":"codeVoice"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Else, use the full pixel decoding (small than limit bytes)"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"Whatever result, this does not effect the animated\/static behavior of image. So even if you set "},{"code":"limitBytes = 1 && frameCount = 100","type":"codeVoice"},{"type":"text","text":", we will stll create animated image with each frame "},{"type":"codeVoice","code":"1x1"},{"text":" pixel size.","type":"text"}]}]}]},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"This option has higher priority than ","type":"text"},{"type":"codeVoice","code":".imageThumbnailPixelSize"}]}]}],"kind":"content"}],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"sections":[],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageScaleDownLimitBytes","interfaceLanguage":"swift"},"schemaVersion":{"patch":0,"major":0,"minor":3},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagescaledownlimitbytes"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagescaledownlimitbytes"],"traits":[{"interfaceLanguage":"occ"}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageScaleDownLimitBytes":{"navigatorTitle":[{"text":"SDWebImageContextImageScaleDownLimitBytes","kind":"identifier"}],"title":"imageScaleDownLimitBytes","kind":"symbol","abstract":[{"type":"text","text":"A NSUInteger value to provide the limit bytes during decoding. This can help to avoid OOM on large frame count animated image or large pixel static image when you don’t know how much RAM it occupied before decoding"},{"type":"text","text":" "},{"type":"text","text":"The decoder will do these logic based on limit bytes:"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageScaleDownLimitBytes","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imagescaledownlimitbytes","type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":"Global Variable","op":"replace","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextImageScaleDownLimitBytes"},{"op":"replace","value":"var","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextImageScaleDownLimitBytes"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"value":null,"path":"\/relationshipsSections","op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"text":"SDWebImageContextImageScaleDownLimitBytes","kind":"identifier"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace","value":"SDWebImageContextOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageScaleDownLimitBytes\/title","value":"SDWebImageContextImageScaleDownLimitBytes"},{"value":[{"text":"SDWebImageContextImageScaleDownLimitBytes","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageScaleDownLimitBytes\/fragments"}],"traits":[{"interfaceLanguage":"occ"}]}]}