{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"sections":[],"schemaVersion":{"patch":0,"major":0,"minor":3},"metadata":{"role":"symbol","title":"imageEncodeOptions","symbolKind":"property","navigatorTitle":[{"text":"SDWebImageContextImageEncodeOptions","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"externalID":"c:@SDWebImageContextImageEncodeOptions","extendedModule":"SDWebImage","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEncodeOptions","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"}],"roleHeading":"Type Property"},"abstract":[{"type":"text","text":"A Dictionary (SDImageCoderOptions) value, which pass the extra encode options to the SDImageCoder. Introduced in SDWebImage 5.15.0"},{"type":"text","text":" "},{"text":"You can pass encode options like ","type":"text"},{"type":"codeVoice","code":"compressionQuality"},{"type":"text","text":", "},{"code":"maxFileSize","type":"codeVoice"},{"text":", ","type":"text"},{"code":"maxPixelSize","type":"codeVoice"},{"type":"text","text":" to control the encoding related thing, this is used inside "},{"type":"codeVoice","code":"SDImageCache"},{"text":" during store logic.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imageencodeoptions"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/imageencodeoptions"],"traits":[{"interfaceLanguage":"occ"}]}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"imageEncodeOptions","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","kind":"typeIdentifier"}],"languages":["swift"]}],"kind":"declarations"},{"kind":"content","content":[{"text":"Discussion","type":"heading","level":2,"anchor":"discussion"},{"type":"aside","name":"Note","content":[{"inlineContent":[{"text":"For developer who use custom cache protocol (not SDImageCache instance), they need to upgrade and use these options for encoding.","type":"text"}],"type":"paragraph"}],"style":"note"}]}],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageEncodeOptions"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/imageEncodeOptions":{"navigatorTitle":[{"text":"SDWebImageContextImageEncodeOptions","kind":"identifier"}],"abstract":[{"text":"A Dictionary (SDImageCoderOptions) value, which pass the extra encode options to the SDImageCoder. Introduced in SDWebImage 5.15.0","type":"text"},{"type":"text","text":" "},{"text":"You can pass encode options like ","type":"text"},{"code":"compressionQuality","type":"codeVoice"},{"text":", ","type":"text"},{"code":"maxFileSize","type":"codeVoice"},{"type":"text","text":", "},{"type":"codeVoice","code":"maxPixelSize"},{"type":"text","text":" to control the encoding related thing, this is used inside "},{"code":"SDImageCache","type":"codeVoice"},{"text":" during store logic.","type":"text"}],"title":"imageEncodeOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/imageEncodeOptions","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/imageencodeoptions","role":"symbol","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imageEncodeOptions"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"patch":[{"path":"\/identifier\/interfaceLanguage","op":"replace","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"path":"\/metadata\/title","op":"replace","value":"SDWebImageContextImageEncodeOptions"},{"value":"var","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageContextImageEncodeOptions"}]},{"op":"add","value":null,"path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"extern","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageContextImageEncodeOptions"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"path":"\/primaryContentSections\/0"},{"op":"replace","value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title"},{"value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageEncodeOptions\/title","value":"SDWebImageContextImageEncodeOptions","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageContextImageEncodeOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1imageEncodeOptions\/fragments","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}