{"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalQueryCacheType"},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/originalquerycachetype"]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/originalquerycachetype"],"traits":[{"interfaceLanguage":"occ"}]}],"schemaVersion":{"patch":0,"minor":3,"major":0},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"sections":[],"metadata":{"role":"symbol","symbolKind":"property","modules":[{"name":"SDWebImage"}],"extendedModule":"SDWebImage","roleHeading":"Type Property","externalID":"c:@SDWebImageContextOriginalQueryCacheType","fragments":[{"kind":"keyword","text":"static"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"originalQueryCacheType","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"title":"originalQueryCacheType","navigatorTitle":[{"text":"SDWebImageContextOriginalQueryCacheType","kind":"identifier"}]},"abstract":[{"type":"text","text":"The same behavior like "},{"code":"SDWebImageContextQueryCacheType","type":"codeVoice"},{"text":", but control the query cache type for the original image when you use image transformer feature. This allows the detail control of cache query for these two images. For example, if you want to query the transformed image from both memory\/disk cache, query the original image from disk cache only, use ","type":"text"},{"code":"[.queryCacheType : .all, .originalQueryCacheType : .disk]","type":"codeVoice"},{"text":" ","type":"text"},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"code":"SDImageCacheTypeDisk","type":"codeVoice"},{"text":", which query the original full image data from disk cache after transformed image cache miss. This is suitable for most common cases to avoid re-downloading the full data for different transform variants. (NSNumber)","type":"text"}],"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"text":"let","kind":"keyword"},{"text":" ","kind":"text"},{"text":"originalQueryCacheType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"languages":["swift"]}],"kind":"declarations"},{"content":[{"level":2,"text":"Discussion","type":"heading","anchor":"discussion"},{"type":"aside","name":"Note","style":"note","content":[{"type":"paragraph","inlineContent":[{"text":"Which means, if you set this value to not be ","type":"text"},{"code":".none","type":"codeVoice"},{"type":"text","text":", we will query the original image from cache, then do transform with transformer, instead of actual downloading, which can save bandwidth usage."}]}]}],"kind":"content"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/originalQueryCacheType":{"fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"originalQueryCacheType","kind":"identifier"},{"kind":"text","text":": "},{"text":"SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/originalquerycachetype","title":"originalQueryCacheType","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/originalQueryCacheType","abstract":[{"text":"The same behavior like ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextQueryCacheType"},{"type":"text","text":", but control the query cache type for the original image when you use image transformer feature. This allows the detail control of cache query for these two images. For example, if you want to query the transformed image from both memory\/disk cache, query the original image from disk cache only, use "},{"type":"codeVoice","code":"[.queryCacheType : .all, .originalQueryCacheType : .disk]"},{"type":"text","text":" "},{"text":"If not provide or the value is invalid, we will use ","type":"text"},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":", which query the original full image data from disk cache after transformed image cache miss. This is suitable for most common cases to avoid re-downloading the full data for different transform variants. (NSNumber)"}],"role":"symbol","kind":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOriginalQueryCacheType"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Global Variable"},{"value":"SDWebImageContextOriginalQueryCacheType","path":"\/metadata\/title","op":"replace"},{"value":"var","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"SDWebImageContextOriginalQueryCacheType","kind":"identifier"}],"op":"replace"},{"path":"\/topicSections","op":"add","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"extern"},{"text":" ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSString","text":"NSString","kind":"typeIdentifier"},{"text":" * ","kind":"text"},{"kind":"keyword","text":"const"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageContextOriginalQueryCacheType"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"}},{"value":"SDWebImageContextOriginalQueryCacheType","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalQueryCacheType\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1originalQueryCacheType\/fragments","op":"replace","value":[{"kind":"identifier","text":"SDWebImageContextOriginalQueryCacheType"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace","value":"SDWebImageContextOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace"}]}]}