{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/querycachetype"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/querycachetype"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/queryCacheType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A SDImageCacheType raw value which specify the source of cache to query. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":" to query from disk cache only; "},{"type":"codeVoice","code":"SDImageCacheTypeMemory"},{"type":"text","text":" to query from memory only. And "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":" to query from both memory cache and disk cache. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeNone"},{"type":"text","text":" is invalid and totally ignore the cache query."},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":". (NSNumber)"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"title":"queryCacheType","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:@SDWebImageContextQueryCacheType","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/queryCacheType":{"role":"symbol","title":"queryCacheType","fragments":[{"kind":"keyword","text":"static"},{"kind":"text","text":" "},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"kind":"identifier","text":"queryCacheType"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"abstract":[{"type":"text","text":"A SDImageCacheType raw value which specify the source of cache to query. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":" to query from disk cache only; "},{"type":"codeVoice","code":"SDImageCacheTypeMemory"},{"type":"text","text":" to query from memory only. And "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":" to query from both memory cache and disk cache. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeNone"},{"type":"text","text":" is invalid and totally ignore the cache query."},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":". (NSNumber)"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/queryCacheType","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/querycachetype"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Global Variable"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextQueryCacheType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"extern"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"kind":"text","text":" * "},{"kind":"keyword","text":"const"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1queryCacheType\/title","value":"SDWebImageContextQueryCacheType"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1queryCacheType\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextQueryCacheType"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}