{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/storeCacheType","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"A SDImageCacheType raw value which specify the store cache type when the image has just been downloaded and will be stored to the cache. Specify "},{"type":"codeVoice","code":"SDImageCacheTypeNone"},{"text":" to disable cache storage; ","type":"text"},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"type":"text","text":" to store in disk cache only; "},{"code":"SDImageCacheTypeMemory","type":"codeVoice"},{"type":"text","text":" to store in memory only. And "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":" to store in both memory cache and disk cache."},{"type":"text","text":" "},{"text":"If you use image transformer feature, this actually apply for the transformed image, but not the original image itself. Use ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextOriginalStoreCacheType"},{"type":"text","text":" if you want to control the original image’s store cache type at the same time."},{"type":"text","text":" "},{"type":"text","text":"If not provide or the value is invalid, we will use "},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":". (NSNumber)"}],"metadata":{"extendedModule":"SDWebImage","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"storeCacheType","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"externalID":"c:@SDWebImageContextStoreCacheType","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextStoreCacheType"}],"roleHeading":"Type Property","title":"storeCacheType","role":"symbol","modules":[{"name":"SDWebImage"}],"symbolKind":"property"},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"text":" ","kind":"text"},{"text":"storeCacheType","kind":"identifier"},{"text":": ","kind":"text"},{"text":"SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"}],"languages":["swift"]}]}],"schemaVersion":{"minor":3,"patch":0,"major":0},"sections":[],"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage"],["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/storecachetype"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagecontextoption\/storecachetype"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption/storeCacheType":{"navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextStoreCacheType"}],"abstract":[{"type":"text","text":"A SDImageCacheType raw value which specify the store cache type when the image has just been downloaded and will be stored to the cache. Specify "},{"code":"SDImageCacheTypeNone","type":"codeVoice"},{"type":"text","text":" to disable cache storage; "},{"type":"codeVoice","code":"SDImageCacheTypeDisk"},{"text":" to store in disk cache only; ","type":"text"},{"type":"codeVoice","code":"SDImageCacheTypeMemory"},{"text":" to store in memory only. And ","type":"text"},{"code":"SDImageCacheTypeAll","type":"codeVoice"},{"type":"text","text":" to store in both memory cache and disk cache."},{"text":" ","type":"text"},{"text":"If you use image transformer feature, this actually apply for the transformed image, but not the original image itself. Use ","type":"text"},{"code":"SDWebImageContextOriginalStoreCacheType","type":"codeVoice"},{"text":" if you want to control the original image’s store cache type at the same time.","type":"text"},{"type":"text","text":" "},{"text":"If not provide or the value is invalid, we will use ","type":"text"},{"type":"codeVoice","code":"SDImageCacheTypeAll"},{"type":"text","text":". (NSNumber)"}],"title":"storeCacheType","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption\/storeCacheType","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption\/storecachetype","role":"symbol","fragments":[{"text":"static","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"keyword","text":"let"},{"kind":"text","text":" "},{"text":"storeCacheType","kind":"identifier"},{"kind":"text","text":": "},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"}],"kind":"symbol","type":"topic"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Global Variable","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"SDWebImageContextStoreCacheType"},{"op":"replace","path":"\/metadata\/symbolKind","value":"var"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"SDWebImageContextStoreCacheType","kind":"identifier"}]},{"op":"add","path":"\/topicSections","value":null},{"path":"\/relationshipsSections","value":null,"op":"add"},{"value":null,"path":"\/seeAlsoSections","op":"add"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"extern","kind":"keyword"},{"kind":"text","text":" "},{"kind":"typeIdentifier","text":"NSString","preciseIdentifier":"c:objc(cs)NSString"},{"text":" * ","kind":"text"},{"text":"const","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageContextStoreCacheType"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}]},{"value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1storeCacheType\/title","value":"SDWebImageContextStoreCacheType","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageContextStoreCacheType","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption~1storeCacheType\/fragments"}]}]}