{"sections":[],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didfinishwithtotalcount:skippedcount:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didfinishwithtotalcount:skippedcount:)"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Called when all images are prefetched. Which means it’s called when all URLs from all of prefetching finished."}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"optional"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePrefetcher"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"text":"imagePrefetcher","kind":"internalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher","text":"SDWebImagePrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWithTotalCount"},{"text":" ","kind":"text"},{"text":"totalCount","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":", "},{"text":"skippedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"text":"The current image prefetcher","type":"text"}]}],"name":"imagePrefetcher"},{"name":"totalCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The total number of images that were prefetched (whether successful or not)"}]}]},{"name":"skippedCount","content":[{"type":"paragraph","inlineContent":[{"text":"The total number of images that were skipped","type":"text"}]}]}]}],"metadata":{"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"text":"imagePrefetcher:didFinishWithTotalCount:skippedCount:","kind":"identifier"}],"role":"symbol","externalID":"c:objc(pl)SDWebImagePrefetcherDelegate(im)imagePrefetcher:didFinishWithTotalCount:skippedCount:","modules":[{"name":"SDWebImage"}],"title":"imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imagePrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didFinishWithTotalCount"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"text":"skippedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"UInt","kind":"typeIdentifier","preciseIdentifier":"s:Su"},{"text":")","kind":"text"}]},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher":{"title":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","navigatorTitle":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Prefetch some URLs in the cache for future use. Images are downloaded in low priority.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"imagePrefetcher"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher","kind":"typeIdentifier","text":"SDWebImagePrefetcher"},{"text":", ","kind":"text"},{"text":"didFinishWithTotalCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"skippedCount"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UInt","preciseIdentifier":"s:Su"},{"kind":"text","text":")"}],"navigatorTitle":[{"text":"imagePrefetcher:didFinishWithTotalCount:skippedCount:","kind":"identifier"}],"title":"imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)","kind":"symbol","abstract":[{"text":"Called when all images are prefetched. Which means it’s called when all URLs from all of prefetching finished.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didfinishwithtotalcount:skippedcount:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate":{"title":"SDWebImagePrefetcherDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate","navigatorTitle":[{"text":"SDWebImagePrefetcherDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The prefetcher delegate protocol","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"imagePrefetcher:didFinishWithTotalCount:skippedCount:","op":"replace","path":"\/metadata\/title"},{"path":"\/metadata\/symbolKind","value":"method","op":"replace"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"imagePrefetcher:didFinishWithTotalCount:skippedCount:"}]},{"value":null,"op":"add","path":"\/topicSections"},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:v","text":"void"},{"text":") ","kind":"text"},{"kind":"identifier","text":"imagePrefetcher:"},{"kind":"text","text":"("},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher","text":"SDWebImagePrefetcher"},{"kind":"text","text":" *) "},{"text":"imagePrefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"didFinishWithTotalCount:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"totalCount"},{"text":" ","kind":"text"},{"text":"skippedCount:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:@T@NSUInteger","kind":"typeIdentifier","text":"NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"skippedCount"},{"text":";","kind":"text"}],"languages":["occ"]}]}},{"path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current image prefetcher"}]}],"name":"imagePrefetcher"},{"content":[{"inlineContent":[{"type":"text","text":"The total number of images that were prefetched (whether successful or not)"}],"type":"paragraph"}],"name":"totalCount"},{"name":"skippedCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The total number of images that were skipped"}]}]}],"kind":"parameters"},"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/title","value":"SDWebImagePrefetcher","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/fragments","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/navigatorTitle","op":"replace","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)\/title","value":"imagePrefetcher:didFinishWithTotalCount:skippedCount:","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didFinishWithTotalCount:skippedCount:)\/fragments","op":"replace","value":[{"text":"- ","kind":"text"},{"text":"imagePrefetcher:didFinishWithTotalCount:skippedCount:","kind":"identifier"}]},{"op":"replace","value":"SDWebImagePrefetcherDelegate","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/title"},{"value":[{"text":"SDWebImagePrefetcherDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/fragments","op":"replace"},{"value":[{"text":"SDWebImagePrefetcherDelegate","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/navigatorTitle","op":"replace"}],"traits":[{"interfaceLanguage":"occ"}]}]}