{"metadata":{"platforms":[{"deprecated":false,"name":"iOS","unavailable":false,"beta":false,"introducedAt":"8.0"},{"name":"iPadOS","unavailable":false,"introducedAt":"8.0","deprecated":false,"beta":false},{"beta":false,"deprecated":false,"unavailable":false,"name":"Mac Catalyst","introducedAt":"8.0"}],"externalID":"c:objc(pl)SDWebImagePrefetcherDelegate(im)imagePrefetcher:didPrefetchURL:finishedCount:totalCount:","symbolKind":"method","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imagePrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImagePrefetcher","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didPrefetchURL"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"finishedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"kind":"text","text":", "},{"text":"totalCount","kind":"externalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:Su","text":"UInt"},{"text":")","kind":"text"}],"required":true,"navigatorTitle":[{"text":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:","kind":"identifier"}],"modules":[{"name":"SDWebImage"}],"title":"imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)","role":"symbol","roleHeading":"Instance Method"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate"]]},"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didprefetchurl:finishedcount:totalcount:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didprefetchurl:finishedcount:totalcount:)"]}],"sections":[],"kind":"symbol","identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)"},"primaryContentSections":[{"declarations":[{"languages":["swift"],"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"imagePrefetcher","kind":"identifier"},{"kind":"text","text":"("},{"text":"_","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"imagePrefetcher","kind":"internalParam"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher"},{"text":", ","kind":"text"},{"text":"didPrefetchURL","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"imageURL","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"text":"finishedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","kind":"typeIdentifier","text":"UInt"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalCount"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":")","kind":"text"}]}],"kind":"declarations"},{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current image prefetcher"}]}],"name":"imagePrefetcher"},{"content":[{"inlineContent":[{"type":"text","text":"The image url that was prefetched"}],"type":"paragraph"}],"name":"imageURL"},{"name":"finishedCount","content":[{"inlineContent":[{"text":"The total number of images that were prefetched (successful or not)","type":"text"}],"type":"paragraph"}]},{"name":"totalCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The total number of images that were to be prefetched"}]}]}],"kind":"parameters"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"type":"text","text":"Called when an image was prefetched. Which means it’s called when one URL from any of prefetching finished."}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate":{"title":"SDWebImagePrefetcherDelegate","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate","navigatorTitle":[{"text":"SDWebImagePrefetcherDelegate","kind":"identifier"}],"fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImagePrefetcherDelegate"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"The prefetcher delegate protocol","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcherDelegate/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)":{"fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"imagePrefetcher","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"didPrefetchURL"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"finishedCount","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:Su","text":"UInt","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"totalCount"},{"text":": ","kind":"text"},{"text":"UInt","preciseIdentifier":"s:Su","kind":"typeIdentifier"},{"text":")","kind":"text"}],"required":true,"url":"\/documentation\/sdwebimage\/sdwebimageprefetcherdelegate\/imageprefetcher(_:didprefetchurl:finishedcount:totalcount:)","title":"imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)","abstract":[{"text":"Called when an image was prefetched. Which means it’s called when one URL from any of prefetching finished.","type":"text"}],"navigatorTitle":[{"text":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:","kind":"identifier"}],"type":"topic","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcherDelegate\/imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImagePrefetcher":{"title":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","navigatorTitle":[{"text":"SDWebImagePrefetcher","kind":"identifier"}],"fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDWebImagePrefetcher","kind":"identifier"}],"url":"\/documentation\/sdwebimage\/sdwebimageprefetcher","type":"topic","kind":"symbol","role":"symbol","abstract":[{"text":"Prefetch some URLs in the cache for future use. Images are downloaded in low priority.","type":"text"}]}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"value":[{"kind":"text","text":"- "},{"text":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:","kind":"identifier"}],"op":"replace","path":"\/metadata\/fragments"},{"path":"\/topicSections","value":null,"op":"add"},{"path":"\/relationshipsSections","op":"add","value":null},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"path":"\/primaryContentSections\/0","op":"replace","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"void","kind":"typeIdentifier","preciseIdentifier":"c:v"},{"kind":"text","text":") "},{"text":"imagePrefetcher:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImagePrefetcher","text":"SDWebImagePrefetcher","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImagePrefetcher","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"imagePrefetcher","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"didPrefetchURL:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"kind":"internalParam","text":"imageURL"},{"text":" ","kind":"text"},{"kind":"identifier","text":"finishedCount:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@T@NSUInteger","text":"NSUInteger","kind":"typeIdentifier"},{"kind":"text","text":") "},{"text":"finishedCount","kind":"internalParam"},{"text":" ","kind":"text"},{"kind":"identifier","text":"totalCount:"},{"kind":"text","text":"("},{"text":"NSUInteger","kind":"typeIdentifier","preciseIdentifier":"c:@T@NSUInteger"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"totalCount"},{"text":";","kind":"text"}]}]}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The current image prefetcher"}]}],"name":"imagePrefetcher"},{"content":[{"inlineContent":[{"type":"text","text":"The image url that was prefetched"}],"type":"paragraph"}],"name":"imageURL"},{"name":"finishedCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The total number of images that were prefetched (successful or not)"}]}]},{"name":"totalCount","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The total number of images that were to be prefetched"}]}]}]}},{"value":"SDWebImagePrefetcherDelegate","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/fragments","op":"replace","value":[{"text":"SDWebImagePrefetcherDelegate","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate\/navigatorTitle","value":[{"text":"SDWebImagePrefetcherDelegate","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)\/title","value":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:"},{"value":[{"text":"- ","kind":"text"},{"text":"imagePrefetcher:didPrefetchURL:finishedCount:totalCount:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcherDelegate~1imagePrefetcher(_:didPrefetchURL:finishedCount:totalCount:)\/fragments"},{"op":"replace","value":"SDWebImagePrefetcher","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/title"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/fragments","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImagePrefetcher\/navigatorTitle","op":"replace","value":[{"text":"SDWebImagePrefetcher","kind":"identifier"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}