{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Whether current image loader supports to load the provide image URL."},{"type":"text","text":" "},{"type":"text","text":"This will be checked every time a new image request come for loader. If this return NO, we will mark this image load as failed. If return YES, we will start to call "},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":"."}],"kind":"symbol","metadata":{"modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"canRequestImageForURL:"}],"role":"symbol","title":"canRequestImage(for:)","roleHeading":"Instance Method","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"symbolKind":"method","externalID":"c:objc(pl)SDImageLoader(im)canRequestImageForURL:","required":true,"platforms":[{"deprecatedAt":"100000.0","beta":false,"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/canRequestImage(for:)":{"navigatorTitle":[{"kind":"identifier","text":"canRequestImageForURL:"}],"deprecated":true,"role":"symbol","title":"canRequestImage(for:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"for"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?) -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"abstract":[{"type":"text","text":"Whether current image loader supports to load the provide image URL."},{"type":"text","text":" "},{"type":"text","text":"This will be checked every time a new image request come for loader. If this return NO, we will mark this image load as failed. If return YES, we will start to call "},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":"."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:)","kind":"symbol","required":true,"type":"topic","url":"\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"role":"symbol","title":"SDImageLoader","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoader"}],"abstract":[{"type":"text","text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself."},{"type":"text","text":" "},{"type":"text","text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call "},{"type":"codeVoice","code":"SDImageLoaderDecodeImageData"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDImageLoaderDecodeProgressiveImageData"},{"type":"text","text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block."},{"type":"text","text":" "},{"type":"text","text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"url":"\/documentation\/sdwebimage\/sdimageloader"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/platforms","value":[{"deprecatedAt":"34464.0","beta":false,"unavailable":false,"name":"iOS","introducedAt":"8.0","deprecated":false}]},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"canRequestImageForURL:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canRequestImageForURL:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","text":"BOOL","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"kind":"identifier","text":"canRequestImageForURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:)\/title","value":"canRequestImageForURL:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"canRequestImageForURL:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"kind":"identifier","text":"SDImageLoader"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}