{"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"optional","kind":"keyword"},{"text":" ","kind":"text"},{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier"},{"text":" = [], ","kind":"text"},{"text":"context","kind":"externalParam"},{"kind":"text","text":": ["},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","text":"SDWebImageContextOption","kind":"typeIdentifier"},{"text":" : ","kind":"text"},{"kind":"keyword","text":"Any"},{"text":"]?) -> ","kind":"text"},{"preciseIdentifier":"s:Sb","text":"Bool","kind":"typeIdentifier"}],"languages":["swift"]}]},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"text":"The image URL to be loaded.","type":"text"}],"type":"paragraph"}],"name":"url"},{"content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this request"}],"type":"paragraph"}],"name":"options"},{"name":"context","content":[{"inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"type":"codeVoice","code":"SDWebImageContextOption"},{"type":"text","text":". This hold the extra objects which "},{"type":"codeVoice","code":"options"},{"text":" enum can not hold.","type":"text"}],"type":"paragraph"}]}]},{"content":[{"type":"heading","anchor":"return-value","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"YES to continue download, NO to stop download."}],"type":"paragraph"}],"kind":"content"}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:options:context:)","interfaceLanguage":"swift"},"metadata":{"navigatorTitle":[{"text":"canRequestImageForURL:options:context:","kind":"identifier"}],"externalID":"c:objc(pl)SDImageLoader(im)canRequestImageForURL:options:context:","role":"symbol","platforms":[{"name":"iOS","introducedAt":"8.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","introducedAt":"8.0","beta":false,"unavailable":false,"deprecated":false},{"name":"Mac Catalyst","deprecated":false,"beta":false,"unavailable":false,"introducedAt":"8.0"}],"title":"canRequestImage(for:options:context:)","roleHeading":"Instance Method","symbolKind":"method","fragments":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"kind":"identifier","text":"canRequestImage"},{"kind":"text","text":"("},{"text":"for","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"kind":"text","text":"?, "},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"text":"Bool","preciseIdentifier":"s:Sb","kind":"typeIdentifier"}],"modules":[{"name":"SDWebImage"}]},"abstract":[{"type":"text","text":"Whether current image loader supports to load the provide image URL, with associated options and context."},{"type":"text","text":" "},{"type":"text","text":"This will be checked every time a new image request come for loader. If this return NO, we will mark this image load as failed. If return YES, we will start to call "},{"code":"requestImageWithURL:options:context:progress:completed:","type":"codeVoice"},{"text":".","type":"text"}],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"]]},"schemaVersion":{"major":0,"minor":3,"patch":0},"kind":"symbol","variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:options:context:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:options:context:)"]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/canRequestImage(for:options:context:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"kind":"text","text":" "},{"text":"canRequestImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"for","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimageloader\/canrequestimage(for:options:context:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/canRequestImage(for:options:context:)","title":"canRequestImage(for:options:context:)","navigatorTitle":[{"text":"canRequestImageForURL:options:context:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Whether current image loader supports to load the provide image URL, with associated options and context.","type":"text"},{"type":"text","text":" "},{"text":"This will be checked every time a new image request come for loader. If this return NO, we will mark this image load as failed. If return YES, we will start to call ","type":"text"},{"code":"requestImageWithURL:options:context:progress:completed:","type":"codeVoice"},{"text":".","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","value":"Instance Method","op":"replace"},{"op":"replace","path":"\/metadata\/title","value":"canRequestImageForURL:options:context:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"text":"canRequestImageForURL:options:context:","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"op":"replace","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"text":"BOOL","preciseIdentifier":"c:@T@BOOL","kind":"typeIdentifier"},{"kind":"text","text":") "},{"kind":"identifier","text":"canRequestImageForURL:"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":" "},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"text":") ","kind":"text"},{"text":"options","kind":"internalParam"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","text":"SDWebImageContext","kind":"typeIdentifier"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"],"platforms":["iOS"]}]},"path":"\/primaryContentSections\/0"},{"op":"replace","path":"\/primaryContentSections\/1","value":{"kind":"parameters","parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The image URL to be loaded."}]}]},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this request"}],"type":"paragraph"}]},{"name":"context","content":[{"inlineContent":[{"text":"A context contains different options to perform specify changes or processes, see ","type":"text"},{"type":"codeVoice","code":"SDWebImageContextOption"},{"text":". This hold the extra objects which ","type":"text"},{"code":"options","type":"codeVoice"},{"text":" enum can not hold.","type":"text"}],"type":"paragraph"}]}]}},{"value":{"kind":"content","content":[{"anchor":"return-value","type":"heading","text":"Return Value","level":2},{"inlineContent":[{"type":"text","text":"YES to continue download, NO to stop download."}],"type":"paragraph"}]},"op":"replace","path":"\/primaryContentSections\/2"},{"value":"SDWebImageContextOption","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","op":"replace"},{"op":"replace","value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments"},{"value":[{"text":"SDWebImageContextOption","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","op":"replace","value":"SDImageLoader"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","op":"replace","value":[{"text":"SDImageLoader","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle","op":"replace","value":[{"text":"SDImageLoader","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:options:context:)\/title","value":"canRequestImageForURL:options:context:"},{"value":[{"text":"- ","kind":"text"},{"text":"canRequestImageForURL:options:context:","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1canRequestImage(for:options:context:)\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle"}]}]}