{"metadata":{"role":"symbol","title":"shouldBlockFailedURL(with:error:options:context:)","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","navigatorTitle":[{"text":"shouldBlockFailedURLWithURL:error:options:context:","kind":"identifier"}],"platforms":[{"deprecated":false,"unavailable":false,"introducedAt":"8.0","beta":false,"name":"iOS"},{"name":"iPadOS","deprecated":false,"unavailable":false,"beta":false,"introducedAt":"8.0"},{"unavailable":false,"name":"Mac Catalyst","beta":false,"introducedAt":"8.0","deprecated":false}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"shouldBlockFailedURL","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV","text":"URL"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP","text":"Error"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"externalID":"c:objc(pl)SDImageLoader(im)shouldBlockFailedURLWithURL:error:options:context:","symbolKind":"method"},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"]]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"optional","kind":"keyword"},{"kind":"text","text":" "},{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"kind":"internalParam","text":"url"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": any "},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":", "},{"text":"options","kind":"externalParam"},{"kind":"text","text":": "},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":" = [], ","kind":"text"},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"text":"]?) -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}]}],"kind":"declarations"},{"kind":"parameters","parameters":[{"content":[{"inlineContent":[{"type":"text","text":"The URL represent the image. Note this may not be a HTTP URL"}],"type":"paragraph"}],"name":"url"},{"name":"error","content":[{"type":"paragraph","inlineContent":[{"text":"The URL’s loading error, from previous ","type":"text"},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":" completedBlock’s error."}]}]},{"name":"options","content":[{"inlineContent":[{"text":"A mask to specify options to use for this request","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"type":"text","text":"A context contains different options to perform specify changes or processes, see "},{"type":"codeVoice","code":"SDWebImageContextOption"},{"type":"text","text":". This hold the extra objects which "},{"type":"codeVoice","code":"options"},{"type":"text","text":" enum can not hold."}],"type":"paragraph"}],"name":"context"}]},{"content":[{"anchor":"return-value","type":"heading","level":2,"text":"Return Value"},{"inlineContent":[{"type":"text","text":"Whether to block this url or not. Return YES to mark this URL as failed."}],"type":"paragraph"}],"kind":"content"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:options:context:)"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:options:context:)"]}],"schemaVersion":{"minor":3,"major":0,"patch":0},"abstract":[{"text":"Whether the error from image loader should be marked indeed un-recoverable or not, with associated options and context.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If this return YES, failed URL which does not using "},{"type":"codeVoice","code":"SDWebImageRetryFailed"},{"type":"text","text":" will be blocked into black list. Else not."}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:options:context:)","interfaceLanguage":"swift"},"sections":[],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"abstract":[],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageContextOption","kind":"identifier"}],"kind":"symbol","title":"SDWebImageContextOption","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontextoption","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","navigatorTitle":[{"text":"SDWebImageContextOption","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/shouldBlockFailedURL(with:error:options:context:)":{"role":"symbol","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":": "},{"preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier","text":"URL"},{"kind":"text","text":", "},{"text":"error","kind":"externalParam"},{"kind":"text","text":": any "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":", ","kind":"text"},{"text":"options","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"text":", ","kind":"text"},{"text":"context","kind":"externalParam"},{"text":": [","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"text":" : ","kind":"text"},{"text":"Any","kind":"keyword"},{"kind":"text","text":"]?) -> "},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:options:context:)","type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:options:context:)","title":"shouldBlockFailedURL(with:error:options:context:)","navigatorTitle":[{"text":"shouldBlockFailedURLWithURL:error:options:context:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Whether the error from image loader should be marked indeed un-recoverable or not, with associated options and context.","type":"text"},{"text":" ","type":"text"},{"text":"If this return YES, failed URL which does not using ","type":"text"},{"type":"codeVoice","code":"SDWebImageRetryFailed"},{"text":" will be blocked into black list. Else not.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"abstract":[],"title":"SDWebImageContext","type":"topic","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","url":"\/documentation\/sdwebimage\/sdwebimagecontext","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"shouldBlockFailedURLWithURL:error:options:context:","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:options:context:"}]},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"text":") ","kind":"text"},{"kind":"identifier","text":"shouldBlockFailedURLWithURL:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSURL","text":"NSURL"},{"text":" *) ","kind":"text"},{"text":"url","kind":"internalParam"},{"kind":"text","text":" "},{"text":"error:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSError","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSError"},{"text":" *) ","kind":"text"},{"text":"error","kind":"internalParam"},{"text":" ","kind":"text"},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"text":"context:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"SDWebImageContext","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext"},{"text":" *) ","kind":"text"},{"text":"context","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"}},{"op":"replace","path":"\/primaryContentSections\/1","value":{"parameters":[{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL represent the image. Note this may not be a HTTP URL"}]}],"name":"url"},{"name":"error","content":[{"inlineContent":[{"type":"text","text":"The URL’s loading error, from previous "},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":" completedBlock’s error."}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A mask to specify options to use for this request"}]}],"name":"options"},{"name":"context","content":[{"type":"paragraph","inlineContent":[{"text":"A context contains different options to perform specify changes or processes, see ","type":"text"},{"code":"SDWebImageContextOption","type":"codeVoice"},{"text":". This hold the extra objects which ","type":"text"},{"type":"codeVoice","code":"options"},{"text":" enum can not hold.","type":"text"}]}]}],"kind":"parameters"}},{"op":"replace","value":{"kind":"content","content":[{"level":2,"text":"Return Value","anchor":"return-value","type":"heading"},{"inlineContent":[{"type":"text","text":"Whether to block this url or not. Return YES to mark this URL as failed."}],"type":"paragraph"}]},"path":"\/primaryContentSections\/2"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageContextOption"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:options:context:)\/title","value":"shouldBlockFailedURLWithURL:error:options:context:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:options:context:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"shouldBlockFailedURLWithURL:error:options:context:","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader"},{"op":"replace","value":[{"kind":"identifier","text":"SDImageLoader"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments"},{"value":[{"text":"SDImageLoader","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"text":"SDWebImageOptions","kind":"identifier"}],"op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle"}]}]}