{"abstract":[{"text":"Whether the error from image loader should be marked indeed un-recoverable or not.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"If this return YES, failed URL which does not using "},{"code":"SDWebImageRetryFailed","type":"codeVoice"},{"text":" will be blocked into black list. Else not.","type":"text"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:)"]}],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:)"},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"]]},"sections":[],"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"kind":"keyword","text":"func"},{"text":" ","kind":"text"},{"text":"shouldBlockFailedURL","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"externalParam","text":"with"},{"text":" ","kind":"text"},{"text":"url","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","preciseIdentifier":"s:s5ErrorP","kind":"typeIdentifier"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}]}]},{"parameters":[{"name":"url","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL represent the image. Note this may not be a HTTP URL"}]}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The URL’s loading error, from previous "},{"type":"codeVoice","code":"requestImageWithURL:options:context:progress:completed:"},{"type":"text","text":" completedBlock’s error."}]}],"name":"error"}],"kind":"parameters"},{"kind":"content","content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"type":"paragraph","inlineContent":[{"text":"Whether to block this url or not. Return YES to mark this URL as failed.","type":"text"}]}]}],"metadata":{"externalID":"c:objc(pl)SDImageLoader(im)shouldBlockFailedURLWithURL:error:","symbolKind":"method","role":"symbol","required":true,"roleHeading":"Instance Method","fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"shouldBlockFailedURL"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:10Foundation3URLV","text":"URL","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"text":"Bool","kind":"typeIdentifier","preciseIdentifier":"s:Sb"}],"navigatorTitle":[{"text":"shouldBlockFailedURLWithURL:error:","kind":"identifier"}],"platforms":[{"name":"iOS","deprecated":false,"deprecatedAt":"100000.0","introducedAt":"8.0","unavailable":false,"beta":false},{"beta":false,"deprecatedAt":"100000.0","introducedAt":"8.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"introducedAt":"8.0","deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"beta":false,"name":"Mac Catalyst"}],"title":"shouldBlockFailedURL(with:error:)","modules":[{"name":"SDWebImage"}]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader/shouldBlockFailedURL(with:error:)":{"role":"symbol","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"shouldBlockFailedURL","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":", ","kind":"text"},{"text":"error","kind":"externalParam"},{"text":": any ","kind":"text"},{"text":"Error","kind":"typeIdentifier","preciseIdentifier":"s:s5ErrorP"},{"text":") -> ","kind":"text"},{"kind":"typeIdentifier","text":"Bool","preciseIdentifier":"s:Sb"}],"url":"\/documentation\/sdwebimage\/sdimageloader\/shouldblockfailedurl(with:error:)","deprecated":true,"type":"topic","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader\/shouldBlockFailedURL(with:error:)","title":"shouldBlockFailedURL(with:error:)","required":true,"navigatorTitle":[{"text":"shouldBlockFailedURLWithURL:error:","kind":"identifier"}],"kind":"symbol","abstract":[{"text":"Whether the error from image loader should be marked indeed un-recoverable or not.","type":"text"},{"text":" ","type":"text"},{"text":"If this return YES, failed URL which does not using ","type":"text"},{"type":"codeVoice","code":"SDWebImageRetryFailed"},{"text":" will be blocked into black list. Else not.","type":"text"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"value":[{"introducedAt":"8.0","deprecatedAt":"100000.0","unavailable":false,"deprecated":false,"beta":false,"name":"iOS"},{"beta":false,"deprecatedAt":"100000.0","introducedAt":"8.0","deprecated":false,"unavailable":false,"name":"iPadOS"},{"name":"Mac Catalyst","deprecated":false,"deprecatedAt":"100000.0","introducedAt":"8.0","unavailable":false,"beta":false}],"op":"replace","path":"\/metadata\/platforms"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"shouldBlockFailedURLWithURL:error:","path":"\/metadata\/title","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:"}],"path":"\/metadata\/fragments","op":"replace"},{"value":null,"path":"\/topicSections","op":"add"},{"op":"add","value":null,"path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"- (","kind":"text"},{"text":"BOOL","kind":"typeIdentifier","preciseIdentifier":"c:@T@BOOL"},{"kind":"text","text":") "},{"text":"shouldBlockFailedURLWithURL:","kind":"identifier"},{"kind":"text","text":"("},{"text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL","kind":"typeIdentifier"},{"kind":"text","text":" *) "},{"kind":"internalParam","text":"url"},{"text":" ","kind":"text"},{"text":"error:","kind":"identifier"},{"kind":"text","text":"("},{"preciseIdentifier":"c:objc(cs)NSError","kind":"typeIdentifier","text":"NSError"},{"kind":"text","text":" *) "},{"text":"error","kind":"internalParam"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"parameters":[{"name":"url","content":[{"inlineContent":[{"text":"The URL represent the image. Note this may not be a HTTP URL","type":"text"}],"type":"paragraph"}]},{"content":[{"inlineContent":[{"text":"The URL’s loading error, from previous ","type":"text"},{"code":"requestImageWithURL:options:context:progress:completed:","type":"codeVoice"},{"text":" completedBlock’s error.","type":"text"}],"type":"paragraph"}],"name":"error"}],"kind":"parameters"},"op":"replace","path":"\/primaryContentSections\/1"},{"op":"replace","path":"\/primaryContentSections\/2","value":{"kind":"content","content":[{"anchor":"return-value","text":"Return Value","level":2,"type":"heading"},{"inlineContent":[{"type":"text","text":"Whether to block this url or not. Return YES to mark this URL as failed."}],"type":"paragraph"}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"text":"SDImageLoader","kind":"identifier"}]},{"value":[{"text":"SDImageLoader","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:)\/title","op":"replace","value":"shouldBlockFailedURLWithURL:error:"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"shouldBlockFailedURLWithURL:error:"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader~1shouldBlockFailedURL(with:error:)\/fragments","op":"replace"}]}]}