{"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper"]]},"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/init(coder:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/init(coder:)"]}],"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(coder:)"},"schemaVersion":{"major":0,"patch":0,"minor":3},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"required"},{"kind":"text","text":" "},{"text":"init","kind":"keyword"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSCoder","kind":"typeIdentifier","text":"NSCoder"},{"text":")","kind":"text"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"role":"symbol","title":"init(coder:)","roleHeading":"Initializer","platforms":[{"name":"iOS","introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false},{"name":"iPadOS","unavailable":false,"deprecated":false,"beta":false,"introducedAt":"14.0"},{"unavailable":false,"beta":false,"deprecated":false,"name":"Mac Catalyst","introducedAt":"14.0"},{"unavailable":false,"beta":false,"name":"macOS","introducedAt":"11.0","deprecated":false},{"beta":false,"name":"tvOS","introducedAt":"14.0","unavailable":false,"deprecated":false},{"beta":false,"deprecated":false,"name":"watchOS","introducedAt":"7.0","unavailable":false}],"modules":[{"name":"SDWebImageSwiftUI"}],"symbolKind":"init","externalID":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper(im)initWithCoder:","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"text":"coder","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":")","kind":"text"}]},"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"title":"AnimatedImageViewWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"type":"topic","navigatorTitle":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/init(coder:)":{"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/init(coder:)","fragments":[{"kind":"identifier","text":"init"},{"text":"?(","kind":"text"},{"kind":"externalParam","text":"coder"},{"text":": ","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"kind":"text","text":")"}],"title":"init(coder:)","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"text":"initWithCoder:","kind":"identifier"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/init(coder:)","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","value":"occ","path":"\/identifier\/interfaceLanguage"},{"op":"replace","value":"Instance Method","path":"\/metadata\/roleHeading"},{"path":"\/metadata\/title","op":"replace","value":"initWithCoder:"},{"op":"replace","value":"method","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","op":"replace","value":[{"kind":"text","text":"- "},{"text":"initWithCoder:","kind":"identifier"}]},{"path":"\/topicSections","value":null,"op":"add"},{"op":"add","path":"\/relationshipsSections","value":null},{"path":"\/seeAlsoSections","op":"add","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"text","text":"- ("},{"text":"id","kind":"typeIdentifier","preciseIdentifier":"c:*Qo"},{"text":") ","kind":"text"},{"text":"initWithCoder:","kind":"identifier"},{"text":"(","kind":"text"},{"text":"NSCoder","kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)NSCoder"},{"text":" *) ","kind":"text"},{"text":"coder","kind":"internalParam"},{"kind":"text","text":";"}],"languages":["occ"]}],"kind":"declarations"}},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title","value":"AnimatedImageViewWrapper","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments","value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/navigatorTitle","value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1init(coder:)\/title","value":"initWithCoder:","op":"replace"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCoder:"}],"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1init(coder:)\/fragments","op":"replace"}]}]}