{"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/intrinsicContentSize","interfaceLanguage":"swift"},"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper"]]},"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"text":"override","kind":"keyword"},{"text":" ","kind":"text"},{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"},{"text":" { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" }"}],"languages":["swift"]}]}],"kind":"symbol","metadata":{"modules":[{"name":"SDWebImageSwiftUI"}],"role":"symbol","externalID":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper(py)intrinsicContentSize","symbolKind":"property","roleHeading":"Instance Property","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"}],"title":"intrinsicContentSize","navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"platforms":[{"name":"iOS","beta":false,"unavailable":false,"introducedAt":"14.0","deprecated":false},{"deprecated":false,"beta":false,"unavailable":false,"introducedAt":"14.0","name":"iPadOS"},{"unavailable":false,"deprecated":false,"introducedAt":"14.0","name":"Mac Catalyst","beta":false},{"name":"macOS","beta":false,"deprecated":false,"introducedAt":"11.0","unavailable":false},{"name":"tvOS","beta":false,"introducedAt":"14.0","unavailable":false,"deprecated":false},{"unavailable":false,"introducedAt":"7.0","beta":false,"deprecated":false,"name":"watchOS"}]},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/intrinsiccontentsize"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/intrinsiccontentsize"]}],"schemaVersion":{"patch":0,"major":0,"minor":3},"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"title":"AnimatedImageViewWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"type":"topic","navigatorTitle":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/intrinsicContentSize":{"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/intrinsiccontentsize","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"intrinsicContentSize"},{"text":": ","kind":"text"},{"text":"CGSize","kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize"}],"title":"intrinsicContentSize","role":"symbol","type":"topic","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"intrinsicContentSize"}],"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/intrinsicContentSize","kind":"symbol"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"value":"Instance Property","path":"\/metadata\/roleHeading","op":"replace"},{"value":"intrinsicContentSize","op":"replace","path":"\/metadata\/title"},{"value":"property","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}],"op":"replace"},{"value":null,"op":"add","path":"\/topicSections"},{"path":"\/relationshipsSections","op":"add","value":null},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"kind":"keyword","text":"readonly"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:@S@CGSize","text":"CGSize"},{"kind":"text","text":" "},{"text":"intrinsicContentSize","kind":"identifier"},{"kind":"text","text":";"}]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title","value":"AnimatedImageViewWrapper"},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments","value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"op":"replace"},{"value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/navigatorTitle"},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1intrinsicContentSize\/title","value":"intrinsicContentSize","op":"replace"},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1intrinsicContentSize\/fragments","value":[{"kind":"identifier","text":"intrinsicContentSize"}],"op":"replace"}]}]}