{"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper"]]},"identifier":{"url":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/wrapped","interfaceLanguage":"swift"},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"tokens":[{"kind":"attribute","text":"@objc"},{"kind":"text","text":" "},{"text":"@","kind":"attribute"},{"text":"MainActor","preciseIdentifier":"s:ScM","kind":"attribute"},{"text":" ","kind":"text"},{"kind":"keyword","text":"dynamic"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDAnimatedImageView","preciseIdentifier":"c:objc(cs)SDAnimatedImageView"}],"languages":["swift"]}],"kind":"declarations"}],"metadata":{"role":"symbol","symbolKind":"property","externalID":"c:@M@SDWebImageSwiftUI@objc(cs)AnimatedImageViewWrapper(py)wrapped","title":"wrapped","modules":[{"name":"SDWebImageSwiftUI"}],"fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"wrapped"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDAnimatedImageView","text":"SDAnimatedImageView"}],"platforms":[{"introducedAt":"14.0","deprecated":false,"unavailable":false,"beta":false,"name":"iOS"},{"beta":false,"name":"iPadOS","unavailable":false,"introducedAt":"14.0","deprecated":false},{"introducedAt":"14.0","name":"Mac Catalyst","deprecated":false,"unavailable":false,"beta":false},{"deprecated":false,"unavailable":false,"name":"macOS","introducedAt":"11.0","beta":false},{"beta":false,"deprecated":false,"unavailable":false,"introducedAt":"14.0","name":"tvOS"},{"introducedAt":"7.0","deprecated":false,"name":"watchOS","unavailable":false,"beta":false}],"roleHeading":"Instance Property","navigatorTitle":[{"text":"wrapped","kind":"identifier"}]},"kind":"symbol","schemaVersion":{"major":0,"minor":3,"patch":0},"abstract":[{"text":"The wrapped actual image view, using SDWebImage’s aniamted image view","type":"text"}],"variants":[{"traits":[{"interfaceLanguage":"swift"}],"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/wrapped"]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/wrapped"]}],"references":{"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI","kind":"symbol","url":"\/documentation\/sdwebimageswiftui","abstract":[],"title":"SDWebImageSwiftUI","type":"topic","role":"collection"},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper/wrapped":{"identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper\/wrapped","kind":"symbol","type":"topic","title":"wrapped","role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"text":"wrapped","kind":"identifier"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDAnimatedImageView","kind":"typeIdentifier","text":"SDAnimatedImageView"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper\/wrapped","abstract":[{"text":"The wrapped actual image view, using SDWebImage’s aniamted image view","type":"text"}],"navigatorTitle":[{"text":"wrapped","kind":"identifier"}]},"doc://com.dreampiggy.SDWebImageSwiftUI/documentation/SDWebImageSwiftUI/AnimatedImageViewWrapper":{"role":"symbol","kind":"symbol","identifier":"doc:\/\/com.dreampiggy.SDWebImageSwiftUI\/documentation\/SDWebImageSwiftUI\/AnimatedImageViewWrapper","abstract":[{"type":"text","text":"Use wrapper to solve tne "},{"type":"codeVoice","code":"UIImageView"},{"type":"text","text":"\/"},{"type":"codeVoice","code":"NSImageView"},{"type":"text","text":" frame size become image size issue (SwiftUI’s Bug)"}],"title":"AnimatedImageViewWrapper","fragments":[{"text":"class","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"AnimatedImageViewWrapper"}],"type":"topic","navigatorTitle":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"url":"\/documentation\/sdwebimageswiftui\/animatedimageviewwrapper"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","value":"Instance Property","path":"\/metadata\/roleHeading"},{"op":"replace","path":"\/metadata\/title","value":"wrapped"},{"path":"\/metadata\/symbolKind","value":"property","op":"replace"},{"path":"\/metadata\/fragments","op":"replace","value":[{"text":"wrapped","kind":"identifier"}]},{"path":"\/topicSections","op":"add","value":null},{"op":"add","value":null,"path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDAnimatedImageView","text":"SDAnimatedImageView"},{"text":" * ","kind":"text"},{"kind":"identifier","text":"wrapped"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]},"op":"replace"},{"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1wrapped\/title","value":"wrapped","op":"replace"},{"value":[{"text":"wrapped","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper~1wrapped\/fragments","op":"replace"},{"op":"replace","value":"AnimatedImageViewWrapper","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/title"},{"value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dreampiggy.SDWebImageSwiftUI~1documentation~1SDWebImageSwiftUI~1AnimatedImageViewWrapper\/navigatorTitle","value":[{"text":"AnimatedImageViewWrapper","kind":"identifier"}]}]}]}