{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol","preciseIdentifier":"c:objc(pl)SDWebImageCacheKeyFilter","text":"SDWebImageCacheKeyFilterProtocol"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]},{"kind":"content","content":[{"anchor":"discussion","level":2,"type":"heading","text":"Discussion"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The following example sets a filter in the application delegate that will remove any query-string from the"},{"type":"text","text":" "},{"type":"text","text":"URL before to use it as a cache key:"}]},{"type":"paragraph","inlineContent":[{"type":"text","text":"SDWebImageManager.sharedManager.cacheKeyFilter =[SDWebImageCacheKeyFilter cacheKeyFilterWithBlock:^NSString * _Nullable(NSURL * _Nonnull url) {"},{"type":"text","text":" "},{"type":"text","text":"url = [[NSURL alloc] initWithScheme:url.scheme host:url.host path:url.path];"},{"type":"text","text":" "},{"type":"text","text":"return [url absoluteString];"},{"type":"text","text":" "},{"type":"text","text":"}];"}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/cachekeyfilter"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/cachekeyfilter"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKeyFilter","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The cache filter is used to convert an URL into a cache key each time SDWebImageManager need cache key to use image cache."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageCacheKeyFilterProtocol","preciseIdentifier":"c:objc(pl)SDWebImageCacheKeyFilter"},{"kind":"text","text":"?"}],"title":"cacheKeyFilter","roleHeading":"Instance Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageManager(py)cacheKeyFilter","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"cacheKeyFilter"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/cacheKeyFilter":{"role":"symbol","title":"cacheKeyFilter","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"cacheKeyFilter"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageCacheKeyFilterProtocol","preciseIdentifier":"c:objc(pl)SDWebImageCacheKeyFilter"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The cache filter is used to convert an URL into a cache key each time SDWebImageManager need cache key to use image cache."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/cacheKeyFilter","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"cacheKeyFilter"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/cachekeyfilter"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManager"}],"abstract":[{"type":"text","text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes."},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"type":"text","text":" "},{"type":"text","text":"You can use this class directly to benefit from web image downloading with caching in another context than"},{"type":"text","text":" "},{"type":"text","text":"a UIView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageManager"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCacheKeyFilterProtocol":{"role":"symbol","title":"SDWebImageCacheKeyFilterProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"}],"abstract":[{"type":"text","text":"This is the protocol for cache key filter."},{"type":"text","text":" "},{"type":"text","text":"We can use a block to specify the cache key filter. But Using protocol can make this extensible, and allow Swift user to use it easily instead of using "},{"type":"codeVoice","code":"@convention(block)"},{"type":"text","text":" to store a block into context options."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCacheKeyFilterProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCacheKeyFilterProtocol"}],"url":"\/documentation\/sdwebimage\/sdwebimagecachekeyfilterprotocol"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"cacheKeyFilter"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"cacheKeyFilter"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"strong"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SDWebImageCacheKeyFilter>","preciseIdentifier":"c:Qoobjc(pl)SDWebImageCacheKeyFilter"},{"kind":"text","text":" * "},{"kind":"identifier","text":"cacheKeyFilter"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKeyFilter\/title","value":"cacheKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1cacheKeyFilter\/fragments","value":[{"kind":"identifier","text":"cacheKeyFilter"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/title","value":"SDWebImageCacheKeyFilter"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCacheKeyFilterProtocol\/fragments","value":[{"kind":"identifier","text":"SDWebImageCacheKeyFilter"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}