{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImageCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache","text":"SDImageCacheProtocol"},{"kind":"text","text":"? { "},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/defaultimagecache"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/defaultimagecache"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageCache","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The default image cache when the manager which is created with no arguments. Such as shared manager or init."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil. Means using "},{"type":"codeVoice","code":"SDImageCache.sharedImageCache"}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImageCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache"},{"kind":"text","text":"?"}],"title":"defaultImageCache","roleHeading":"Type Property","role":"symbol","symbolKind":"property","externalID":"c:objc(cs)SDWebImageManager(cpy)defaultImageCache","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"defaultImageCache"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManager"}],"abstract":[{"type":"text","text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes."},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"type":"text","text":" "},{"type":"text","text":"You can use this class directly to benefit from web image downloading with caching in another context than"},{"type":"text","text":" "},{"type":"text","text":"a UIView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageManager"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"role":"symbol","title":"SDImageCacheProtocol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageCacheProtocol"}],"abstract":[{"type":"text","text":"This is the image cache protocol to provide custom image cache for "},{"type":"codeVoice","code":"SDWebImageManager"},{"type":"text","text":"."},{"type":"text","text":" "},{"type":"text","text":"Though the best practice to custom image cache, is to write your own class which conform "},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"type":"codeVoice","code":"SDDiskCache"},{"type":"text","text":" protocol for "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"type":"text","text":"However, if your own cache implementation contains more advanced feature beyond "},{"type":"codeVoice","code":"SDImageCache"},{"type":"text","text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like "},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageCacheProtocol"}],"url":"\/documentation\/sdwebimage\/sdimagecacheprotocol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/defaultImageCache":{"role":"symbol","title":"defaultImageCache","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"defaultImageCache"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"The default image cache when the manager which is created with no arguments. Such as shared manager or init."},{"type":"text","text":" "},{"type":"text","text":"Defaults to nil. Means using "},{"type":"codeVoice","code":"SDImageCache.sharedImageCache"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/defaultImageCache","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"defaultImageCache"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/defaultimagecache"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"op":"replace","path":"\/metadata\/title","value":"defaultImageCache"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"identifier","text":"defaultImageCache"}]},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"kind":"keyword","text":"class"},{"kind":"text","text":", "},{"kind":"keyword","text":"nonatomic"},{"kind":"text","text":", "},{"kind":"keyword","text":"assign"},{"kind":"text","text":", "},{"kind":"keyword","text":"unsafe_unretained"},{"kind":"text","text":", "},{"kind":"keyword","text":"readwrite"},{"kind":"text","text":", "},{"kind":"keyword","text":"nullable"},{"kind":"text","text":") "},{"kind":"typeIdentifier","text":"id<SDImageCache>","preciseIdentifier":"c:Qoobjc(pl)SDImageCache"},{"kind":"text","text":" *"},{"kind":"identifier","text":"defaultImageCache"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","value":"SDImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"kind":"identifier","text":"SDImageCache"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1defaultImageCache\/title","value":"defaultImageCache"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1defaultImageCache\/fragments","value":[{"kind":"identifier","text":"defaultImageCache"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}