{"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/init(cache:loader:)","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/init(cache:loader:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/init(cache:loader:)"]}],"schemaVersion":{"major":0,"patch":0,"minor":3},"kind":"symbol","hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"sections":[],"metadata":{"modules":[{"name":"SDWebImage"}],"roleHeading":"Initializer","symbolKind":"init","role":"symbol","navigatorTitle":[{"kind":"identifier","text":"initWithCache:loader:"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cache"},{"kind":"text","text":": any "},{"text":"SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"text":"loader","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","text":"SDImageLoader","preciseIdentifier":"c:objc(pl)SDImageLoader"},{"text":")","kind":"text"}],"title":"init(cache:loader:)","externalID":"c:objc(cs)SDWebImageManager(im)initWithCache:loader:"},"abstract":[{"text":"Allows to specify instance of cache and image loader used with image manager.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"cache"},{"kind":"text","text":": any "},{"text":"SDImageCacheProtocol","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","preciseIdentifier":"c:objc(pl)SDImageCache"},{"kind":"text","text":", "},{"text":"loader","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageLoader","text":"SDImageLoader","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader"},{"kind":"text","text":")"}],"languages":["swift"]}]}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/init(cache:loader:)":{"abstract":[{"text":"Allows to specify instance of cache and image loader used with image manager.","type":"text"}],"fragments":[{"text":"init","kind":"identifier"},{"kind":"text","text":"("},{"text":"cache","kind":"externalParam"},{"text":": any ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageCache","text":"SDImageCacheProtocol"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"loader"},{"text":": any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDImageLoader","text":"SDImageLoader","kind":"typeIdentifier"},{"kind":"text","text":")"}],"kind":"symbol","title":"init(cache:loader:)","role":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/init(cache:loader:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/init(cache:loader:)","navigatorTitle":[{"text":"initWithCache:loader:","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageCacheProtocol":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageCacheProtocol","type":"topic","url":"\/documentation\/sdwebimage\/sdimagecacheprotocol","kind":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDImageCacheProtocol"}],"navigatorTitle":[{"text":"SDImageCacheProtocol","kind":"identifier"}],"abstract":[{"text":"This is the image cache protocol to provide custom image cache for ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":".","type":"text"},{"text":" ","type":"text"},{"text":"Though the best practice to custom image cache, is to write your own class which conform ","type":"text"},{"type":"codeVoice","code":"SDMemoryCache"},{"type":"text","text":" or "},{"code":"SDDiskCache","type":"codeVoice"},{"type":"text","text":" protocol for "},{"code":"SDImageCache","type":"codeVoice"},{"type":"text","text":" class (See more on "},{"type":"codeVoice","code":"SDImageCacheConfig.memoryCacheClass & SDImageCacheConfig.diskCacheClass"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"However, if your own cache implementation contains more advanced feature beyond ","type":"text"},{"code":"SDImageCache","type":"codeVoice"},{"text":" itself, you can consider to provide this instead. For example, you can even use a cache manager like ","type":"text"},{"type":"codeVoice","code":"SDImageCachesManager"},{"type":"text","text":" to register multiple caches."}],"title":"SDImageCacheProtocol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoader":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoader","title":"SDImageLoader","abstract":[{"text":"This is the protocol to specify custom image load process. You can create your own class to conform this protocol and use as a image loader to load image from network or any available remote resources defined by yourself.","type":"text"},{"type":"text","text":" "},{"text":"If you want to implement custom loader for image download from network or local file, you just need to concentrate on image data download only. After the download finish, call ","type":"text"},{"code":"SDImageLoaderDecodeImageData","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"SDImageLoaderDecodeProgressiveImageData","type":"codeVoice"},{"text":" to use the built-in decoding process and produce image (Remember to call in the global queue). And finally callback the completion block.","type":"text"},{"text":" ","type":"text"},{"text":"If you directly get the image instance using some third-party SDKs, such as image directly from Photos framework. You can process the image data and image instance by yourself without that built-in decoding process. And finally callback the completion block.","type":"text"}],"url":"\/documentation\/sdwebimage\/sdimageloader","kind":"symbol","role":"symbol","fragments":[{"text":"protocol","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoader","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoader"}],"type":"topic"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","url":"\/documentation\/sdwebimage\/sdwebimagemanager","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","navigatorTitle":[{"text":"SDWebImageManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"text":" ","type":"text"},{"text":"You can use this class directly to benefit from web image downloading with caching in another context than","type":"text"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Method"},{"path":"\/metadata\/title","value":"initWithCache:loader:","op":"replace"},{"value":"method","op":"replace","path":"\/metadata\/symbolKind"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"initWithCache:loader:"}],"op":"replace"},{"op":"add","path":"\/topicSections","value":null},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","value":null,"path":"\/seeAlsoSections"},{"value":{"declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","preciseIdentifier":"c:*Qo","text":"id"},{"text":") ","kind":"text"},{"kind":"identifier","text":"initWithCache:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"id<SDImageCache>","preciseIdentifier":"c:Qoobjc(pl)SDImageCache"},{"kind":"text","text":") "},{"kind":"internalParam","text":"cache"},{"kind":"text","text":" "},{"text":"loader:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDImageLoader","text":"id<SDImageLoader>"},{"kind":"text","text":") "},{"text":"loader","kind":"internalParam"},{"kind":"text","text":";"}],"platforms":["iOS"],"languages":["occ"]}],"kind":"declarations"},"op":"replace","path":"\/primaryContentSections\/0"},{"path":"\/primaryContentSections\/1","op":"add","value":{"content":[{"anchor":"return-value","level":2,"text":"Return Value","type":"heading"},{"inlineContent":[{"text":"New instance of ","type":"text"},{"type":"codeVoice","code":"SDWebImageManager"},{"text":" with specified cache and loader.","type":"text"}],"type":"paragraph"}],"kind":"content"}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1init(cache:loader:)\/title","value":"initWithCache:loader:","op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1init(cache:loader:)\/fragments","value":[{"kind":"text","text":"- "},{"text":"initWithCache:loader:","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/title","op":"replace","value":"SDImageCache"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/fragments","value":[{"text":"SDImageCache","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageCacheProtocol\/navigatorTitle","value":[{"text":"SDImageCache","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/title","value":"SDImageLoader","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/fragments","value":[{"kind":"identifier","text":"SDImageLoader"}],"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoader\/navigatorTitle","value":[{"kind":"identifier","text":"SDImageLoader"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"text":"SDWebImageManager","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/navigatorTitle","value":[{"kind":"identifier","text":"SDWebImageManager"}]}]}]}