{"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:progress:completed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:progress:completed:)"]}],"sections":[],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"loadImage","kind":"identifier"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"SDWebImageOptions","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":" = [], "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":" "},{"text":"progressBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"SDImageLoaderProgressBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock"},{"text":"?, ","kind":"text"},{"text":"completed","kind":"externalParam"},{"text":" ","kind":"text"},{"text":"completedBlock","kind":"internalParam"},{"text":": ","kind":"text"},{"text":"@escaping","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"typeIdentifier","text":"SDInternalCompletionBlock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDInternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","text":"SDWebImageCombinedOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation"},{"text":"?","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"parameters":[{"content":[{"inlineContent":[{"text":"The URL to the image","type":"text"}],"type":"paragraph"}],"name":"url"},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this request"}],"type":"paragraph"}]},{"name":"progressBlock","content":[{"type":"paragraph","inlineContent":[{"text":"A block called while image is downloading","type":"text"},{"type":"text","text":" "},{"type":"text","text":"@note the progress block is executed on a background queue"}]}]},{"name":"completedBlock","content":[{"type":"paragraph","inlineContent":[{"text":"A block called when operation has been completed.","type":"text"}]}]}],"kind":"parameters"},{"kind":"content","content":[{"level":2,"text":"Return Value","type":"heading","anchor":"return-value"},{"inlineContent":[{"type":"text","text":"Returns an instance of SDWebImageCombinedOperation, which you can cancel the loading process."}],"type":"paragraph"}]},{"kind":"content","content":[{"text":"Discussion","anchor":"discussion","type":"heading","level":2},{"type":"paragraph","inlineContent":[{"text":"This parameter is required.","type":"text"}]},{"type":"paragraph","inlineContent":[{"text":"This block has no return value and takes the requested UIImage as first parameter and the NSData representation as second parameter.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"In case of error the image parameter is nil and the third parameter may contain an NSError."}]},{"inlineContent":[{"type":"text","text":"The forth parameter is an "},{"type":"codeVoice","code":"SDImageCacheType"},{"type":"text","text":" enum indicating if the image was retrieved from the local cache"},{"type":"text","text":" "},{"type":"text","text":"or from the memory cache or from the network."}],"type":"paragraph"},{"type":"paragraph","inlineContent":[{"type":"text","text":"The fifth parameter is set to NO when the SDWebImageProgressiveLoad option is used and the image is"},{"text":" ","type":"text"},{"type":"text","text":"downloading. This block is thus called repeatedly with a partial image. When image is fully downloaded, the"},{"text":" ","type":"text"},{"type":"text","text":"block is called a last time with the full image and the last parameter set to YES."}]},{"inlineContent":[{"type":"text","text":"The last parameter is the original image URL"}],"type":"paragraph"}]}],"kind":"symbol","identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:progress:completed:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Downloads the image at the given URL if not present in cache or return the cached version otherwise."}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","preciseIdentifier":"s:10Foundation3URLV","kind":"typeIdentifier"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"text":": ","kind":"text"},{"text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"text":"SDInternalCompletionBlock","kind":"typeIdentifier","preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock"},{"kind":"text","text":") -> "},{"preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","kind":"typeIdentifier","text":"SDWebImageCombinedOperation"},{"kind":"text","text":"?"}],"role":"symbol","modules":[{"name":"SDWebImage"}],"roleHeading":"Instance Method","symbolKind":"method","navigatorTitle":[{"kind":"identifier","text":"loadImageWithURL:options:progress:completed:"}],"externalID":"c:objc(cs)SDWebImageManager(im)loadImageWithURL:options:progress:completed:","title":"loadImage(with:options:progress:completed:)"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/loadImage(with:options:progress:completed:)":{"type":"topic","title":"loadImage(with:options:progress:completed:)","navigatorTitle":[{"kind":"identifier","text":"loadImageWithURL:options:progress:completed:"}],"abstract":[{"type":"text","text":"Downloads the image at the given URL if not present in cache or return the cached version otherwise."}],"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"text":"(","kind":"text"},{"text":"with","kind":"externalParam"},{"text":": ","kind":"text"},{"text":"URL","kind":"typeIdentifier","preciseIdentifier":"s:10Foundation3URLV"},{"text":"?, ","kind":"text"},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"preciseIdentifier":"c:@E@SDWebImageOptions","kind":"typeIdentifier","text":"SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"progress"},{"text":": ","kind":"text"},{"text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","kind":"typeIdentifier"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"text":": ","kind":"text"},{"preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock","text":"SDInternalCompletionBlock","kind":"typeIdentifier"},{"text":") -> ","kind":"text"},{"preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","kind":"typeIdentifier","text":"SDWebImageCombinedOperation"},{"kind":"text","text":"?"}],"kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:progress:completed:)","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:progress:completed:)","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"title":"SDWebImageOptions","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","type":"topic","abstract":[{"type":"text","text":"WebCache options"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions","role":"symbol","navigatorTitle":[{"text":"SDWebImageOptions","kind":"identifier"}],"fragments":[{"kind":"keyword","text":"struct"},{"text":" ","kind":"text"},{"text":"SDWebImageOptions","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDInternalCompletionBlock":{"abstract":[],"title":"SDInternalCompletionBlock","kind":"symbol","type":"topic","fragments":[{"kind":"keyword","text":"typealias"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDInternalCompletionBlock"}],"role":"symbol","url":"\/documentation\/sdwebimage\/sdinternalcompletionblock","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDInternalCompletionBlock","navigatorTitle":[{"kind":"identifier","text":"SDInternalCompletionBlock"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderProgressBlock":{"abstract":[],"title":"SDImageLoaderProgressBlock","type":"topic","fragments":[{"text":"typealias","kind":"keyword"},{"text":" ","kind":"text"},{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"navigatorTitle":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","url":"\/documentation\/sdwebimage\/sdimageloaderprogressblock","kind":"symbol","role":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation":{"title":"SDWebImageCombinedOperation","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"navigatorTitle":[{"text":"SDWebImageCombinedOperation","kind":"identifier"}],"abstract":[{"text":"A combined operation representing the cache and loader operation. You can use it to cancel the load process.","type":"text"}],"type":"topic","role":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation","kind":"symbol"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","url":"\/documentation\/sdwebimage\/sdwebimagemanager","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","navigatorTitle":[{"text":"SDWebImageManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"text":" ","type":"text"},{"text":"You can use this class directly to benefit from web image downloading with caching in another context than","type":"text"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"value":"loadImageWithURL:options:progress:completed:","op":"replace","path":"\/metadata\/title"},{"value":"method","path":"\/metadata\/symbolKind","op":"replace"},{"path":"\/metadata\/fragments","value":[{"text":"- ","kind":"text"},{"text":"loadImageWithURL:options:progress:completed:","kind":"identifier"}],"op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"path":"\/relationshipsSections","value":null,"op":"add"},{"path":"\/seeAlsoSections","value":null,"op":"add"},{"value":{"kind":"declarations","declarations":[{"tokens":[{"text":"- (","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","kind":"typeIdentifier","text":"SDWebImageCombinedOperation"},{"kind":"text","text":" *) "},{"text":"loadImageWithURL:","kind":"identifier"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *) "},{"text":"url","kind":"internalParam"},{"kind":"text","text":" "},{"text":"options:","kind":"identifier"},{"text":"(","kind":"text"},{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","text":"SDWebImageOptions","kind":"typeIdentifier","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":") "},{"kind":"internalParam","text":"options"},{"text":" ","kind":"text"},{"text":"progress:","kind":"identifier"},{"text":"(","kind":"text"},{"preciseIdentifier":"c:BFv(#L#L#*$objc(cs)NSURL)","text":"void (^)(long, long, NSURL *)","kind":"typeIdentifier"},{"text":") ","kind":"text"},{"kind":"internalParam","text":"progressBlock"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed:"},{"text":"(","kind":"text"},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSData *, NSError *, enum SDImageCacheType, _Bool, NSURL *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#*$objc(cs)NSError#$@E@SDImageCacheType#b#*$objc(cs)NSURL)"},{"kind":"text","text":") "},{"text":"completedBlock","kind":"internalParam"},{"text":";","kind":"text"}],"platforms":["iOS"],"languages":["occ"]}]},"op":"replace","path":"\/primaryContentSections\/0"},{"value":{"kind":"parameters","parameters":[{"name":"url","content":[{"inlineContent":[{"type":"text","text":"The URL to the image"}],"type":"paragraph"}]},{"name":"options","content":[{"inlineContent":[{"type":"text","text":"A mask to specify options to use for this request"}],"type":"paragraph"}]},{"name":"progressBlock","content":[{"inlineContent":[{"text":"A block called while image is downloading","type":"text"},{"text":" ","type":"text"},{"text":"@note the progress block is executed on a background queue","type":"text"}],"type":"paragraph"}]},{"content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"A block called when operation has been completed."}]}],"name":"completedBlock"}]},"path":"\/primaryContentSections\/1","op":"replace"},{"path":"\/primaryContentSections\/2","op":"replace","value":{"kind":"content","content":[{"text":"Return Value","level":2,"type":"heading","anchor":"return-value"},{"type":"paragraph","inlineContent":[{"type":"text","text":"Returns an instance of SDWebImageCombinedOperation, which you can cancel the loading process."}]}]}},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:progress:completed:)\/title","op":"replace","value":"loadImageWithURL:options:progress:completed:"},{"value":[{"text":"- ","kind":"text"},{"text":"loadImageWithURL:options:progress:completed:","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:progress:completed:)\/fragments","op":"replace"},{"value":"SDWebImageOptions","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title"},{"value":[{"kind":"identifier","text":"SDWebImageOptions"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDInternalCompletionBlock\/title","value":"SDInternalCompletionBlock","op":"replace"},{"op":"replace","value":[{"text":"SDInternalCompletionBlock","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDInternalCompletionBlock\/fragments"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDInternalCompletionBlock\/navigatorTitle","value":[{"kind":"identifier","text":"SDInternalCompletionBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/title","value":"SDImageLoaderProgressBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/fragments","value":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/navigatorTitle","value":[{"text":"SDImageLoaderProgressBlock","kind":"identifier"}],"op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/title","value":"SDWebImageCombinedOperation","op":"replace"},{"value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/navigatorTitle","op":"replace","value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}]},{"value":"SDWebImageManager","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageManager"}],"op":"replace"},{"value":[{"text":"SDWebImageManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/navigatorTitle"}]}]}