{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":" "},{"kind":"internalParam","text":"url"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":" = [], "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption","text":"SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":" "},{"kind":"internalParam","text":"progressBlock"},{"kind":"text","text":": "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock","text":"SDImageLoaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":" "},{"kind":"internalParam","text":"completedBlock"},{"kind":"text","text":": "},{"kind":"keyword","text":"@escaping"},{"kind":"text","text":" "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDInternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock","text":"SDInternalCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","text":"SDWebImageCombinedOperation"},{"kind":"text","text":"?"}],"languages":["swift"],"platforms":["iOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:context:progress:completed:)"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:context:progress:completed:)"],"traits":[{"interfaceLanguage":"occ"}]}],"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:context:progress:completed:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Downloads the image at the given URL if not present in cache or return the cached version otherwise."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDInternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SDWebImageCombinedOperation","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation"},{"kind":"text","text":"?"}],"title":"loadImage(with:options:context:progress:completed:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"c:objc(cs)SDWebImageManager(im)loadImageWithURL:options:context:progress:completed:","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"kind":"identifier","text":"loadImageWithURL:options:context:progress:completed:"}]},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageManager"}],"abstract":[{"type":"text","text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes."},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"type":"text","text":" "},{"type":"text","text":"You can use this class directly to benefit from web image downloading with caching in another context than"},{"type":"text","text":" "},{"type":"text","text":"a UIView."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageManager"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContextOption":{"role":"symbol","title":"SDWebImageContextOption","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageContextOption"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContextOption","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageContextOption"}],"url":"\/documentation\/sdwebimage\/sdwebimagecontextoption"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDInternalCompletionBlock":{"role":"symbol","title":"SDInternalCompletionBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDInternalCompletionBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDInternalCompletionBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDInternalCompletionBlock"}],"url":"\/documentation\/sdwebimage\/sdinternalcompletionblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageContext":{"role":"symbol","title":"SDWebImageContext","fragments":[{"kind":"identifier","text":"SDWebImageContext"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage\/sdwebimagecontext"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/loadImage(with:options:context:progress:completed:)":{"role":"symbol","title":"loadImage(with:options:context:progress:completed:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"loadImage"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"URL","preciseIdentifier":"s:10Foundation3URLV"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"options"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions"},{"kind":"text","text":", "},{"kind":"externalParam","text":"context"},{"kind":"text","text":": ["},{"kind":"typeIdentifier","text":"SDWebImageContextOption","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContextOption"},{"kind":"text","text":" : "},{"kind":"keyword","text":"Any"},{"kind":"text","text":"]?, "},{"kind":"externalParam","text":"progress"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDImageLoaderProgressBlock","preciseIdentifier":"c:SDImageLoader.h@T@SDImageLoaderProgressBlock"},{"kind":"text","text":"?, "},{"kind":"externalParam","text":"completed"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"SDInternalCompletionBlock","preciseIdentifier":"c:SDWebImageManager.h@T@SDInternalCompletionBlock"},{"kind":"text","text":") -> "},{"kind":"typeIdentifier","text":"SDWebImageCombinedOperation","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation"},{"kind":"text","text":"?"}],"abstract":[{"type":"text","text":"Downloads the image at the given URL if not present in cache or return the cached version otherwise."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/loadImage(with:options:context:progress:completed:)","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"loadImageWithURL:options:context:progress:completed:"}],"url":"\/documentation\/sdwebimage\/sdwebimagemanager\/loadimage(with:options:context:progress:completed:)"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageLoaderProgressBlock":{"role":"symbol","title":"SDImageLoaderProgressBlock","fragments":[{"kind":"keyword","text":"typealias"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDImageLoaderProgressBlock"}],"abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageLoaderProgressBlock","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}],"url":"\/documentation\/sdwebimage\/sdimageloaderprogressblock"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptions":{"role":"symbol","title":"SDWebImageOptions","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptions"}],"abstract":[{"type":"text","text":"WebCache options"}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptions"}],"url":"\/documentation\/sdwebimage\/sdwebimageoptions"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"role":"collection","title":"SDWebImage","abstract":[],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","kind":"symbol","type":"topic","url":"\/documentation\/sdwebimage"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageCombinedOperation":{"role":"symbol","title":"SDWebImageCombinedOperation","fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"abstract":[{"type":"text","text":"A combined operation representing the cache and loader operation. You can use it to cancel the load process."}],"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}],"url":"\/documentation\/sdwebimage\/sdwebimagecombinedoperation"}},"variantOverrides":[{"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Method"},{"op":"replace","path":"\/metadata\/title","value":"loadImageWithURL:options:context:progress:completed:"},{"op":"replace","path":"\/metadata\/symbolKind","value":"method"},{"op":"replace","path":"\/metadata\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadImageWithURL:options:context:progress:completed:"}]},{"op":"add","path":"\/topicSections","value":null},{"op":"add","path":"\/relationshipsSections","value":null},{"op":"add","path":"\/seeAlsoSections","value":null},{"op":"replace","path":"\/primaryContentSections\/0","value":{"kind":"declarations","declarations":[{"tokens":[{"kind":"text","text":"- ("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageCombinedOperation","preciseIdentifier":"c:objc(cs)SDWebImageCombinedOperation","text":"SDWebImageCombinedOperation"},{"kind":"text","text":" *) "},{"kind":"identifier","text":"loadImageWithURL:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"NSURL","preciseIdentifier":"c:objc(cs)NSURL"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"url"},{"kind":"text","text":" "},{"kind":"identifier","text":"options:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptions","preciseIdentifier":"c:@E@SDWebImageOptions","text":"SDWebImageOptions"},{"kind":"text","text":")"},{"kind":"internalParam","text":"options"},{"kind":"text","text":" "},{"kind":"identifier","text":"context:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageContext","preciseIdentifier":"c:SDWebImageDefine.h@T@SDWebImageContext","text":"SDWebImageContext"},{"kind":"text","text":" *)"},{"kind":"internalParam","text":"context"},{"kind":"text","text":" "},{"kind":"identifier","text":"progress:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(long, long, NSURL *)","preciseIdentifier":"c:BFv(#L#L#*$objc(cs)NSURL)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"progressBlock"},{"kind":"text","text":" "},{"kind":"identifier","text":"completed:"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"void (^)(UIImage *, NSData *, NSError *, enum SDImageCacheType, _Bool, NSURL *)","preciseIdentifier":"c:BFv(#*$objc(cs)UIImage#*$objc(cs)NSData#*$objc(cs)NSError#$@E@SDImageCacheType#b#*$objc(cs)NSURL)"},{"kind":"text","text":")"},{"kind":"internalParam","text":"completedBlock"},{"kind":"text","text":";"}],"languages":["occ"],"platforms":["iOS"]}]}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","value":[{"kind":"identifier","text":"SDWebImageManager"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/title","value":"SDWebImageContextOption"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageContextOption\/fragments","value":[{"kind":"identifier","text":"SDWebImageContextOption"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDInternalCompletionBlock\/title","value":"SDInternalCompletionBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDInternalCompletionBlock\/fragments","value":[{"kind":"identifier","text":"SDInternalCompletionBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:context:progress:completed:)\/title","value":"loadImageWithURL:options:context:progress:completed:"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1loadImage(with:options:context:progress:completed:)\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"loadImageWithURL:options:context:progress:completed:"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/title","value":"SDImageLoaderProgressBlock"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageLoaderProgressBlock\/fragments","value":[{"kind":"identifier","text":"SDImageLoaderProgressBlock"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/title","value":"SDWebImageOptions"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptions\/fragments","value":[{"kind":"identifier","text":"SDWebImageOptions"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/title","value":"SDWebImageCombinedOperation"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageCombinedOperation\/fragments","value":[{"kind":"identifier","text":"SDWebImageCombinedOperation"}]}],"traits":[{"interfaceLanguage":"occ"}]}]}