{"sections":[],"identifier":{"interfaceLanguage":"swift","url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/optionsProcessor"},"schemaVersion":{"minor":3,"major":0,"patch":0},"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/optionsprocessor"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/optionsprocessor"]}],"kind":"symbol","metadata":{"externalID":"c:objc(cs)SDWebImageManager(py)optionsProcessor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"optionsProcessor"},{"text":": (any ","kind":"text"},{"preciseIdentifier":"c:objc(pl)SDWebImageOptionsProcessor","kind":"typeIdentifier","text":"SDWebImageOptionsProcessorProtocol"},{"kind":"text","text":")?"}],"symbolKind":"property","role":"symbol","roleHeading":"Instance Property","title":"optionsProcessor","modules":[{"name":"SDWebImage"}],"navigatorTitle":[{"text":"optionsProcessor","kind":"identifier"}]},"primaryContentSections":[{"declarations":[{"platforms":["iOS"],"languages":["swift"],"tokens":[{"text":"var","kind":"keyword"},{"text":" ","kind":"text"},{"text":"optionsProcessor","kind":"identifier"},{"kind":"text","text":": (any "},{"preciseIdentifier":"c:objc(pl)SDWebImageOptionsProcessor","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol","text":"SDWebImageOptionsProcessorProtocol","kind":"typeIdentifier"},{"text":")? { ","kind":"text"},{"kind":"keyword","text":"get"},{"kind":"text","text":" "},{"kind":"keyword","text":"set"},{"kind":"text","text":" }"}]}],"kind":"declarations"},{"content":[{"type":"heading","text":"Discussion","level":2,"anchor":"discussion"},{"name":"Note","type":"aside","style":"note","content":[{"inlineContent":[{"text":"If you use ","type":"text"},{"type":"codeVoice","code":"transformer"},{"text":", ","type":"text"},{"code":"cacheKeyFilter","type":"codeVoice"},{"text":" or ","type":"text"},{"code":"cacheSerializer","type":"codeVoice"},{"type":"text","text":" property of manager, the input context option already apply those properties before passed. This options processor is a better replacement for those property in common usage."},{"text":" ","type":"text"},{"type":"text","text":"For example, you can control the global options, based on the URL or original context option like the below code."}],"type":"paragraph"}]},{"inlineContent":[{"type":"text","text":"SDWebImageManager.sharedManager.optionsProcessor = [SDWebImageOptionsProcessor optionsProcessorWithBlock:^SDWebImageOptionsResult * _Nullable(NSURL * _Nullable url, SDWebImageOptions options, SDWebImageContext * _Nullable context) {"},{"text":" ","type":"text"},{"type":"text","text":"\/\/ Only do animation on "},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":" ","type":"text"},{"text":"if (!context[SDWebImageContextAnimatedImageClass]) {","type":"text"},{"type":"text","text":" "},{"text":"options |= SDWebImageDecodeFirstFrameOnly;","type":"text"},{"type":"text","text":" "},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"\/\/ Do not force decode for png url"},{"type":"text","text":" "},{"type":"text","text":"if ([url.lastPathComponent isEqualToString:@“png”]) {"},{"text":" ","type":"text"},{"type":"text","text":"options |= SDWebImageAvoidDecodeImage;"},{"text":" ","type":"text"},{"type":"text","text":"}"},{"type":"text","text":" "},{"type":"text","text":"\/\/ Always use screen scale factor"},{"type":"text","text":" "},{"type":"text","text":"SDWebImageMutableContext *mutableContext = [NSDictionary dictionaryWithDictionary:context];"},{"text":" ","type":"text"},{"text":"mutableContext[SDWebImageContextImageScaleFactor] = @(UIScreen.mainScreen.scale);","type":"text"},{"text":" ","type":"text"},{"text":"context = [mutableContext copy];","type":"text"}],"type":"paragraph"},{"code":[" return [[SDWebImageOptionsResult alloc] initWithOptions:options context:context];"],"syntax":null,"type":"codeListing"},{"type":"paragraph","inlineContent":[{"text":"}];","type":"text"}]}],"kind":"content"}],"abstract":[{"text":"The options processor is used, to have a global control for all the image request options and context option for current manager.","type":"text"}],"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/optionsProcessor":{"navigatorTitle":[{"text":"optionsProcessor","kind":"identifier"}],"role":"symbol","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/optionsprocessor","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"text":"optionsProcessor","kind":"identifier"},{"text":": (any ","kind":"text"},{"text":"SDWebImageOptionsProcessorProtocol","preciseIdentifier":"c:objc(pl)SDWebImageOptionsProcessor","kind":"typeIdentifier"},{"text":")?","kind":"text"}],"type":"topic","title":"optionsProcessor","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/optionsProcessor","abstract":[{"text":"The options processor is used, to have a global control for all the image request options and context option for current manager.","type":"text"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageOptionsProcessorProtocol":{"role":"symbol","navigatorTitle":[{"kind":"identifier","text":"SDWebImageOptionsProcessorProtocol"}],"type":"topic","title":"SDWebImageOptionsProcessorProtocol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageOptionsProcessorProtocol","url":"\/documentation\/sdwebimage\/sdwebimageoptionsprocessorprotocol","abstract":[{"text":"This is the protocol for options processor.","type":"text"},{"text":" ","type":"text"},{"text":"Options processor can be used, to control the final result for individual image request’s ","type":"text"},{"code":"SDWebImageOptions","type":"codeVoice"},{"type":"text","text":" and "},{"code":"SDWebImageContext","type":"codeVoice"},{"type":"text","text":" "},{"type":"text","text":"Implements the protocol to have a global control for each indivadual image request’s option."}],"kind":"symbol","fragments":[{"kind":"keyword","text":"protocol"},{"kind":"text","text":" "},{"kind":"identifier","text":"SDWebImageOptionsProcessorProtocol"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","url":"\/documentation\/sdwebimage\/sdwebimagemanager","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","navigatorTitle":[{"text":"SDWebImageManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"text":" ","type":"text"},{"text":"You can use this class directly to benefit from web image downloading with caching in another context than","type":"text"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageManager","kind":"identifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"op":"replace","path":"\/identifier\/interfaceLanguage","value":"occ"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Instance Property"},{"path":"\/metadata\/title","value":"optionsProcessor","op":"replace"},{"path":"\/metadata\/symbolKind","op":"replace","value":"property"},{"value":[{"text":"optionsProcessor","kind":"identifier"}],"path":"\/metadata\/fragments","op":"replace"},{"op":"add","value":null,"path":"\/topicSections"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","op":"replace","value":{"declarations":[{"languages":["occ"],"platforms":["iOS"],"tokens":[{"kind":"keyword","text":"@property"},{"kind":"text","text":" ("},{"text":"nonatomic","kind":"keyword"},{"text":", ","kind":"text"},{"text":"strong","kind":"keyword"},{"text":") ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDWebImageOptionsProcessor","text":"id<SDWebImageOptionsProcessor>"},{"text":" ","kind":"text"},{"kind":"identifier","text":"optionsProcessor"},{"kind":"text","text":";"}]}],"kind":"declarations"}},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1optionsProcessor\/title","value":"optionsProcessor"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1optionsProcessor\/fragments","value":[{"text":"optionsProcessor","kind":"identifier"}],"op":"replace"},{"value":"SDWebImageOptionsProcessor","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol\/title"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol\/fragments","op":"replace","value":[{"text":"SDWebImageOptionsProcessor","kind":"identifier"}]},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageOptionsProcessorProtocol\/navigatorTitle","value":[{"text":"SDWebImageOptionsProcessor","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager","op":"replace"},{"value":[{"text":"SDWebImageManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments"},{"value":[{"kind":"identifier","text":"SDWebImageManager"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/navigatorTitle"}]}]}