{"kind":"symbol","schemaVersion":{"patch":0,"minor":3,"major":0},"abstract":[{"text":"The image transformer for manager. It’s used for image transform after the image load finished and store the transformed image to cache, see ","type":"text"},{"type":"codeVoice","code":"SDImageTransformer"},{"type":"text","text":"."},{"type":"text","text":" "},{"text":"Defaults to nil, which means no transform is applied.","type":"text"}],"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformer"},{"text":": (any ","kind":"text"},{"text":"SDImageTransformer","preciseIdentifier":"c:objc(pl)SDImageTransformer","kind":"typeIdentifier","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer"},{"text":")? { ","kind":"text"},{"text":"get","kind":"keyword"},{"text":" ","kind":"text"},{"text":"set","kind":"keyword"},{"text":" }","kind":"text"}],"platforms":["iOS"],"languages":["swift"]}]},{"content":[{"text":"Discussion","anchor":"discussion","level":2,"type":"heading"},{"content":[{"inlineContent":[{"type":"text","text":"This will affect all the load requests for this manager if you provide. However, you can pass "},{"type":"codeVoice","code":"SDWebImageContextImageTransformer"},{"text":" in context arg to explicitly use that transformer instead.","type":"text"}],"type":"paragraph"}],"type":"aside","name":"Note","style":"note"}],"kind":"content"}],"variants":[{"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/transformer"],"traits":[{"interfaceLanguage":"swift"}]},{"traits":[{"interfaceLanguage":"occ"}],"paths":["\/documentation\/sdwebimage\/sdwebimagemanager\/transformer"]}],"sections":[],"hierarchy":{"paths":[["doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager"]]},"metadata":{"navigatorTitle":[{"text":"transformer","kind":"identifier"}],"symbolKind":"property","title":"transformer","externalID":"c:objc(cs)SDWebImageManager(py)transformer","roleHeading":"Instance Property","modules":[{"name":"SDWebImage"}],"role":"symbol","fragments":[{"text":"var","kind":"keyword"},{"kind":"text","text":" "},{"kind":"identifier","text":"transformer"},{"kind":"text","text":": (any "},{"text":"SDImageTransformer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageTransformer"},{"kind":"text","text":")?"}]},"identifier":{"url":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/transformer","interfaceLanguage":"swift"},"references":{"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager":{"role":"symbol","title":"SDWebImageManager","url":"\/documentation\/sdwebimage\/sdwebimagemanager","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager","navigatorTitle":[{"text":"SDWebImageManager","kind":"identifier"}],"type":"topic","abstract":[{"text":"The SDWebImageManager is the class behind the UIImageView+WebCache category and likes.","type":"text"},{"type":"text","text":" "},{"type":"text","text":"It ties the asynchronous downloader (SDWebImageDownloader) with the image cache store (SDImageCache)."},{"text":" ","type":"text"},{"text":"You can use this class directly to benefit from web image downloading with caching in another context than","type":"text"},{"type":"text","text":" "},{"text":"a UIView.","type":"text"}],"fragments":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"SDWebImageManager","kind":"identifier"}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDWebImageManager/transformer":{"identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDWebImageManager\/transformer","type":"topic","kind":"symbol","url":"\/documentation\/sdwebimage\/sdwebimagemanager\/transformer","title":"transformer","navigatorTitle":[{"kind":"identifier","text":"transformer"}],"fragments":[{"kind":"keyword","text":"var"},{"text":" ","kind":"text"},{"text":"transformer","kind":"identifier"},{"kind":"text","text":": (any "},{"text":"SDImageTransformer","kind":"typeIdentifier","preciseIdentifier":"c:objc(pl)SDImageTransformer"},{"text":")?","kind":"text"}],"role":"symbol","abstract":[{"type":"text","text":"The image transformer for manager. It’s used for image transform after the image load finished and store the transformed image to cache, see "},{"type":"codeVoice","code":"SDImageTransformer"},{"type":"text","text":"."},{"text":" ","type":"text"},{"type":"text","text":"Defaults to nil, which means no transform is applied."}]},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage":{"title":"SDWebImage","kind":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage","type":"topic","abstract":[],"url":"\/documentation\/sdwebimage","role":"collection"},"doc://com.dailymotion.SDWebImage/documentation/SDWebImage/SDImageTransformer":{"type":"topic","abstract":[{"type":"text","text":"A transformer protocol to transform the image load from cache or from download."},{"type":"text","text":" "},{"text":"You can provide transformer to cache and manager (Through the ","type":"text"},{"type":"codeVoice","code":"transformer"},{"type":"text","text":" property or context option "},{"code":"SDWebImageContextImageTransformer","type":"codeVoice"},{"type":"text","text":")."},{"type":"text","text":" "},{"text":"From v5.20, the transformer class also can be used on animated image frame post-transform logic, see ","type":"text"},{"type":"codeVoice","code":"SDAnimatedImageView"},{"text":".","type":"text"}],"kind":"symbol","role":"symbol","identifier":"doc:\/\/com.dailymotion.SDWebImage\/documentation\/SDWebImage\/SDImageTransformer","url":"\/documentation\/sdwebimage\/sdimagetransformer","fragments":[{"text":"protocol","kind":"keyword"},{"kind":"text","text":" "},{"text":"SDImageTransformer","kind":"identifier"}],"navigatorTitle":[{"text":"SDImageTransformer","kind":"identifier"}],"title":"SDImageTransformer"}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"path":"\/identifier\/interfaceLanguage","value":"occ","op":"replace"},{"op":"replace","path":"\/metadata\/roleHeading","value":"Instance Property"},{"value":"transformer","op":"replace","path":"\/metadata\/title"},{"op":"replace","path":"\/metadata\/symbolKind","value":"property"},{"value":[{"kind":"identifier","text":"transformer"}],"op":"replace","path":"\/metadata\/fragments"},{"value":null,"path":"\/topicSections","op":"add"},{"value":null,"op":"add","path":"\/relationshipsSections"},{"value":null,"op":"add","path":"\/seeAlsoSections"},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"tokens":[{"text":"@property","kind":"keyword"},{"text":" (","kind":"text"},{"text":"nonatomic","kind":"keyword"},{"kind":"text","text":", "},{"text":"strong","kind":"keyword"},{"kind":"text","text":") "},{"text":"id<SDImageTransformer>","kind":"typeIdentifier","preciseIdentifier":"c:Qoobjc(pl)SDImageTransformer"},{"text":" ","kind":"text"},{"text":"transformer","kind":"identifier"},{"text":";","kind":"text"}],"languages":["occ"]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/title","value":"SDWebImageManager"},{"value":[{"kind":"identifier","text":"SDWebImageManager"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/fragments","op":"replace"},{"value":[{"text":"SDWebImageManager","kind":"identifier"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager\/navigatorTitle"},{"value":"transformer","op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1transformer\/title"},{"op":"replace","value":[{"text":"transformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDWebImageManager~1transformer\/fragments"},{"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/title","op":"replace","value":"SDImageTransformer"},{"op":"replace","value":[{"text":"SDImageTransformer","kind":"identifier"}],"path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/fragments"},{"value":[{"kind":"identifier","text":"SDImageTransformer"}],"op":"replace","path":"\/references\/doc:~1~1com.dailymotion.SDWebImage~1documentation~1SDWebImage~1SDImageTransformer\/navigatorTitle"}]}]}